### ISSUE TITLE
.htaccess getting overwritten on restart

### ISSUE THREAD

**Issue by pbrn46** [bitnami/containers#1012]
### Name and Version

bitnami/wordpress:6

### What steps will reproduce the bug?

1. Use `docker-compose.yaml`
2. Use `WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes`
3. Use either `WORDPRESS_HTACCESS_OVERRIDE_NONE=no` or `yes`
4. Mount volume `./wordpress_data:/bitnami/wordpress`
5. `docker-compose up -d`
6. Modify `./wordpress_data/.htaccess` or `./wordpress_data/wordpress-htaccess.conf`
7. Restart `docker-compose down && docker-compose up -d`

### What is the expected behavior?

`.htaccess` should remain the same as edited when restarting the container.

### What do you see instead?

`.htaccess` gets overwritten to a blank file.

### Additional information

I've also tried mounting a local `.htaccess` file: `./public:.htaccess:/opt/bitnami/wordpress/.htaccess`, but the container starts and hangs because it tries and fails to remove the `/opt/bitnami/wordpress/.htaccess` with the error that it is locked or busy, or for some reason `cp: 'wp-config.php' and '/bitnami/wordpress/wp-config.php' are the same file`

The docs don't seem to be clear as to what to mount in order for the `.htaccess` to be persisted, but the mounting of `/bitnami/wordpress` doesn't appear to work.

**Comment by javsalgar** [comment]
Hi!

The issue is that we are only persisting in this case the wordpress-htaccess.conf file. If you need to persist the root .htaccess as well, you may need to add it to the persistence by tweaking the WORDPRESS_DATA_TO_PERSIST variable

https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/rootfs/opt/bitnami/scripts/wordpress-env.sh#L113

It should look like `WORDPRESS_DATA_TO_PERSIST="wp-config.php wp-content .htaccess"

**Comment by pbrn46** [comment]
Hi @javsalgar!

I've tried using the `WORDPRESS_DATA_TO_PERSIST` variable, but it still gets overwritten to a blank .htaccess file upon restart. 

I'm using the following configuration:

```yml
# ...
    volumes:
      - ./wordpress_data:/bitnami/wordpress
    environment:
      # ...
      - WORDPRESS_HTACCESS_OVERRIDE_NONE=no
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
      - WORDPRESS_DATA_TO_PERSIST=wp-config.php wp-content .htaccess
# ...
```

I've tried to persist using the `wordpress-htaccess.conf`, but that gets overwritten to defaults every time as well.
```yml
# ...
    volumes:
      - ./wordpress_data:/bitnami/wordpress
    environment:
      # ...
      # - WORDPRESS_HTACCESS_OVERRIDE_NONE=no
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
      # - WORDPRESS_DATA_TO_PERSIST=wp-config.php wp-content .htaccess
# ...
```

Here are my docker logs, in case it's useful:

```
wordpress 17:58:50.76 
wordpress 17:58:50.76 Welcome to the Bitnami wordpress container
wordpress 17:58:50.76 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 17:58:50.76 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 17:58:50.76 
wordpress 17:58:50.77 INFO  ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 17:58:50.78 INFO  ==> Configuring Apache ServerTokens directive
wordpress 17:58:50.82 INFO  ==> Configuring PHP options
wordpress 17:58:50.82 INFO  ==> Setting PHP opcache.enable option
wordpress 17:58:50.83 INFO  ==> Setting PHP expose_php option
wordpress 17:58:50.84 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ls: cannot access '/bitnami/wordpress': Operation not permitted
wordpress 17:58:51.22 INFO  ==> Ensuring WordPress directories exist
wordpress 17:59:44.83 INFO  ==> Trying to connect to the database server
wordpress 17:59:44.83 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 17:59:45.56 INFO  ==> Installing WordPress
wordpress 17:59:46.69 INFO  ==> Persisting WordPress installation
wordpress 17:59:48.63 INFO  ==> ** WordPress setup finished! **

wordpress 17:59:48.64 INFO  ==> ** Starting Apache **
```

**Comment by corico44** [comment]
Hello! 
Thank you very much for opening the issue. We have reviewed it and we have some doubts: are you using the latest version of the container? Could you provide us with your entire docker compose?

When trying to recreate your problem with the indicated variables, we have no problem persisting the data and modifying any of the two modified files, the content is not deleted. In your case, the volumes are not persisting.

Could you also confirm if the logs you have provided are from the first or the second run?

**Comment by pbrn46** [comment]
It seems every time I restart the container, I have to manually set the permissions of `wp-config.php` to be writable every time now or the container will not start. It will throw a `cp: cannot create regular file '/bitnami/wordpress/wp-config.php': Permission denied`

There seems to be some sort of permission issue happening. I am using an older docker version 18.09.3 and docker-compose 1.13.0 on ubuntu 16.04.6. The stack may just be too old. I'm spinning up a new server to test my configuration now, and I'll report back with my results.

All the images are pulled to be the latest.
```
$ docker-compose pull
Pulling db (bitnami/mariadb:10.3)...
10.3: Pulling from bitnami/mariadb
Digest: sha256:2a97f038a764249773611ed334eadb01e8c92664d2819463b5de207b373d7e9d
Status: Image is up to date for bitnami/mariadb:10.3
Pulling phpmyadmin (phpmyadmin/phpmyadmin:latest)...
latest: Pulling from phpmyadmin/phpmyadmin
Digest: sha256:ae6dadd9cf3c158e42937788f7255fa820ea3daef0349226d8d43f32e76535e1
Status: Image is up to date for phpmyadmin/phpmyadmin:latest
Pulling wordpress (bitnami/wordpress:6)...
6: Pulling from bitnami/wordpress
Digest: sha256:004627fb7d2f22e0985060551232e1fd6ddd9cbf02b741755d59cb144d76e43e
Status: Image is up to date for bitnami/wordpress:6
```

Here is the `docker-compose.yml`. The commented portions are things I've been trying.

```yml
version: '3'

services:
  db:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami'
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      default:
        aliases:
          - localdb
    ports:
      - ${MARIADB_PUBLIC_PORT}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: always
    networks:
      - default
    ports:
      - ${PMA_PUBLIC_PORT}:80
    environment:
      PMA_HOST: localdb
  wordpress:
    image: 'bitnami/wordpress:6'
    # user: root
    depends_on:
      - db
    restart: always
    volumes:
      # - ./public/.htaccess:/opt/bitnami/wordpress/wordpress-htaccess.conf
      - ./wordpress_data/wordpress:/bitnami/wordpress
    networks:
      - default
      - proxy
    ports:
      - ${WP_PUBLIC_PORT}:80
    environment:
      - MARIADB_HOST=localdb
      - MARIADB_PORT_NUMBER=${MARIADB_PORT}
      - WORDPRESS_DATABASE_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DATABASE_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
      - WORDPRESS_SCHEME=https
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - PHP_ENABLE_OPCACHE=0
      # - WORDPRESS_HTACCESS_OVERRIDE_NONE=no
      # - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
      # - WORDPRESS_DATA_TO_PERSIST=wp-config.php wp-content .htaccess

networks:
  default:
  proxy:
    external:
      name: nginx-proxy

volumes:
  mariadb_data:
      driver: local
```

Logs with htaccess override
```
WORDPRESS_HTACCESS_OVERRIDE_NONE=yes
WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
```
```
$ docker logs shopalivecadevdocker_wordpress_1 
wordpress 22:10:50.16 
wordpress 22:10:50.16 Welcome to the Bitnami wordpress container
wordpress 22:10:50.16 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 22:10:50.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 22:10:50.17 
wordpress 22:10:50.17 INFO  ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 22:10:50.60 INFO  ==> Configuring Apache ServerTokens directive
wordpress 22:10:50.74 INFO  ==> Configuring PHP options
wordpress 22:10:50.74 INFO  ==> Setting PHP opcache.enable option
wordpress 22:10:50.78 INFO  ==> Setting PHP expose_php option
wordpress 22:10:50.80 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ls: cannot access '/bitnami/wordpress': Operation not permitted
wordpress 22:10:51.75 INFO  ==> Ensuring WordPress directories exist
wordpress 22:11:47.18 INFO  ==> Trying to connect to the database server
wordpress 22:11:47.25 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 22:11:48.08 INFO  ==> Installing WordPress
wordpress 22:11:49.19 INFO  ==> Persisting WordPress installation
wordpress 22:11:51.21 INFO  ==> ** WordPress setup finished! **

wordpress 22:11:51.22 INFO  ==> ** Starting Apache **
[Mon Aug 08 22:11:51.259299 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:11:51.259635 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:11:51.276354 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:11:51.276651 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:11:51.284515 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Mon Aug 08 22:11:51.284537 2022] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

Logs with no htaccess override
```
WORDPRESS_HTACCESS_OVERRIDE_NONE=no
WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
```
```
$ docker logs shopalivecadevdocker_wordpress_1 
wordpress 22:12:53.71 
wordpress 22:12:53.72 Welcome to the Bitnami wordpress container
wordpress 22:12:53.73 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 22:12:53.73 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 22:12:53.73 
wordpress 22:12:53.74 INFO  ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 22:12:53.79 INFO  ==> Configuring Apache ServerTokens directive
wordpress 22:12:53.84 INFO  ==> Configuring PHP options
wordpress 22:12:53.85 INFO  ==> Setting PHP opcache.enable option
wordpress 22:12:53.88 INFO  ==> Setting PHP expose_php option
wordpress 22:12:53.93 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ls: cannot access '/bitnami/wordpress': Operation not permitted
wordpress 22:12:54.15 INFO  ==> Ensuring WordPress directories exist
wordpress 22:13:53.64 INFO  ==> Trying to connect to the database server
wordpress 22:13:53.65 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 22:13:54.39 INFO  ==> Installing WordPress
wordpress 22:13:55.50 INFO  ==> Persisting WordPress installation
wordpress 22:13:57.71 INFO  ==> ** WordPress setup finished! **

wordpress 22:13:57.72 INFO  ==> ** Starting Apache **
[Mon Aug 08 22:13:57.759349 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:13:57.759621 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:13:57.779523 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:13:57.779765 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 08 22:13:57.787568 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Mon Aug 08 22:13:57.787588 2022] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```
