### ISSUE TITLE
[bitnami/postgresql-repmgr] Cannot specify a custom pg_hba.conf

### ISSUE THREAD

**Issue by Scharfenberg** [bitnami/containers#1048]
**Description**

I'm trying to specify a custom pg_hba.conf file for my postresql-repmgr cluster consisting of two nodes in streaming replication setup.
Unfortunately I cannot use the bind mount approach from the README as I'm using docker swarm.
Therefore I've tried two other approaches -- both without success.
1. Mounting the pg_hba.conf file to `/bitnami/repmgr/conf/pg_hba.conf` using the docker swarm config mechanism.
2. Mounting `/bitnami/repmgr/conf` as a volume with the nfs driver.
3. As third approach I've also tried to use docker-compose just as shown in the README. Again without success.

**Approach 1**
The excerpt from my compose file:
```
[...]
services:
  pg-0:
    image: bitnami/postgresql-repmgr:12.3.0
[...]
    configs:
    - source: pg_hba.conf
      target: /bitnami/repmgr/conf/pg_hba.conf
      uid: "1001"
      gid: "0"
      mode: 0774
[...]
configs:
  pg_hba.conf:
    file: pg_hba.conf
[...]
```
The resulting error message (from my log server):
```
"2020-05-25T10:58:02.049Z","t460s-dockerswarm-2","[38;5;6mrepmgr [38;5;5m10:58:02.04 [0m[38;5;2mINFO [0m ==> Preparing PostgreSQL configuration..."
"2020-05-25T10:58:02.155Z","t460s-dockerswarm-2","[38;5;6mpostgresql [38;5;5m10:58:02.15 [0m[38;5;2mINFO [0m ==> Stopping PostgreSQL..."
"2020-05-25T10:58:02.152Z","t460s-dockerswarm-2","cp: cannot create regular file '/bitnami/postgresql/conf/pg_hba.conf': Permission denied"
"2020-05-25T10:58:02.034Z","t460s-dockerswarm-2","[38;5;6mrepmgr [38;5;5m10:58:02.03 [0m[38;5;2mINFO [0m ==> There are no nodes with primary role. Assuming the primary role..."
"2020-05-25T10:58:02.056Z","t460s-dockerswarm-2","[38;5;6mpostgresql [38;5;5m10:58:02.05 [0m[38;5;2mINFO [0m ==> postgresql.conf file not detected. Generating it..."
```
Notes:
* This approach actually works if I first deploy my service(s) without a custom pg_hba.conf, then update my compose file with the pg_bha.conf file and redeploy. Of course this procedure is very inconvenient -- at least in dev/test scenarios. Maybe it could be a way to go in production as services are deployed once and only redeployed afterwards.
* When adding `user: root` to my services to circumvent issues due to the non-root container I encounter the same password authentication issue as in approach 2. 

**Approach 2**
The excerpt from my compose file:
```
[...]
services:
  pg-0:
    image: bitnami/postgresql-repmgr:12.3.0
[...]
    volumes:
    - pg-primary-vol:/bitnami/postgresql
    - pg-config-vol:/bitnami/repmgr/conf/
[...]
volumes:
  pg-primary-vol:
  pg-config-vol:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.137.110,rw"
      device: ":/mnt/storage1/postgresql/conf"
[...]
```
The resulting error message (from docker service logs):
```
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | [2020-05-25 11:33:45] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | [2020-05-25 11:33:45] [INFO] connecting to database "user=repmgr password=repmgr host=pg-0 dbname=repmgr port=5432 connect_timeout=5"
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | [2020-05-25 11:33:45] [DEBUG] connecting to: "user=repmgr password=repmgr connect_timeout=5 dbname=repmgr host=pg-0 port=5432 fallback_application_name=repmgr"
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | [2020-05-25 11:33:45] [ERROR] connection to database failed
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | [2020-05-25 11:33:45] [DETAIL]
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | FATAL:  password authentication failed for user "repmgr"
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    |
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    | [2020-05-25 11:33:45] [DETAIL] attempted to connect using:
postgres_pg-0.1.akaolj1sa768@t460s-dockerswarm-2    |   user=repmgr password=repmgr connect_timeout=5 dbname=repmgr host=pg-0 port=5432 fallback_application_name=repmgr
```
Notes:
* for testing puposes I've copied the pg_hba.conf from a running version of the container (aka without custom pg_hba.conf) to my nfs conf directory.
* mounting an empty conf directory does not result in this error.
* adding the files postgresql.conf and repmgr.conf (from a running version of the container) to the conf dir does not help.
* From the practical point of view I consider this approach as very inconvenient as it implies copying config files from my project directory to some place in the filesystem that I have to mount first.

**Approach 3**
I've taken the example docker-compose.yml file and added this bind mount to both postgres services:
```
    volumes:
      - ./conf:/bitnami/repmgr/conf/
```
Of course I've also set the correct permissions on the host holder and its content.
As long as the folder is empty everything works fine. As soon as I add the pg_hba.conf the start of the primary container fails with error 2 on the first run:
```
[...]
pg-0_1  | postgresql 20:17:35.41 INFO  ==> Initializing PostgreSQL database...
pg-0_1  | postgresql 20:17:35.41 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
pg-0_1  | postgresql 20:17:35.42 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
pg-0_1  | postgresql 20:17:36.89 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql 20:17:37.03 INFO  ==> Changing password of postgres
pg-0_1  | postgresql 20:17:37.05 INFO  ==> Stopping PostgreSQL...
postgres_pg-0_1 exited with code 2
```
On the second and each subsequent run (without deleting my volumes) I get this already known error:
```
[...]
pg-0_1  | postgresql 20:17:55.19 INFO  ==> Deploying PostgreSQL with persisted data...
pg-1_1  | repmgr 20:17:55.20 INFO  ==> Preparing repmgr configuration...
pg-1_1  | repmgr 20:17:55.21 INFO  ==> Initializing Repmgr...
pg-1_1  | repmgr 20:17:55.22 INFO  ==> Waiting for primary node...
pg-0_1  | postgresql 20:17:55.22 INFO  ==> Stopping PostgreSQL...
pg-0_1  | postgresql-repmgr 20:17:55.23 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **
pg-0_1  |
pg-0_1  | postgresql 20:17:55.30 INFO  ==> Starting PostgreSQL in background...
pg-0_1  | postgresql-repmgr 20:17:55.43 INFO  ==> ** Starting repmgrd **
pg-0_1  | [2020-05-25 20:17:55] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
pg-0_1  | [2020-05-25 20:17:55] [INFO] connecting to database "user=repmgr password=repmgr host=pg-0 dbname=repmgr port=5432 connect_timeout=5"
pg-0_1  | [2020-05-25 20:17:55] [DEBUG] connecting to: "user=repmgr password=repmgr connect_timeout=5 dbname=repmgr host=pg-0 port=5432 fallback_application_name=repmgr"
pg-0_1  | [2020-05-25 20:17:55] [ERROR] connection to database failed
pg-0_1  | [2020-05-25 20:17:55] [DETAIL]
pg-0_1  | FATAL:  password authentication failed for user "repmgr"
pg-0_1  |
pg-0_1  | [2020-05-25 20:17:55] [DETAIL] attempted to connect using:
pg-0_1  |   user=repmgr password=repmgr connect_timeout=5 dbname=repmgr host=pg-0 port=5432 fallback_application_name=repmgr
postgres_pg-0_1 exited with code 6
pg-1_1  | postgresql 20:19:56.06 INFO  ==> Stopping PostgreSQL...
postgres_pg-1_1 exited with code 1
```

**General steps to reproduce the issues in approach 1 and 2**
When modifying and testing my docker-compose.yml file I use these steps to have a clean setup each time:
1. `docker stack rm postgres`
2. `docker volume prune` on all involved docker nodes
3. update docker-compose.yml (e.g. add the volume in approach 2)
4. `docker stack deploy --compose-file docker-compose.yml postgres`

**The full docker-compose.yml file used in approach 1 and 2**
(currently approach 2 is active by outcommenting approach 1 elements):
```
---
version: "3.8"

services:
  pg-0:
    image: bitnami/postgresql-repmgr:12.3.0
    environment:
    - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgres_password
    - REPMGR_PARTNER_NODES=pg-0,pg-1
    - REPMGR_NODE_NAME=pg-0
    - REPMGR_NODE_NETWORK_NAME=pg-0
    - REPMGR_PRIMARY_HOST=pg-0
    - REPMGR_PASSWORD_FILE=/run/secrets/repmgr_password
    - REPMGR_LOG_LEVEL=DEBUG
    volumes:
    - pg-primary-vol:/bitnami/postgresql
    - pg-config-vol:/bitnami/repmgr/conf/
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 256000000
    ports:
    - "5432:5432"
    networks:
    - application-net
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
        - node.role == worker
          #endpoint_mode: dnsrr
    configs:
    - source: additional-postgresql.conf
      target: /bitnami/postgresql/conf/conf.d/additional-postgresql.conf
      #- source: pg_hba.conf
      #  target: /bitnami/repmgr/conf/pg_hba.conf
      #  uid: "1001"
      #  gid: "0"
      #  mode: 0774
    secrets:
    - postgres_password
    - repmgr_password
      #logging:
      #  driver: gelf
      #  options:
      #    gelf-address: 'tcp://192.168.137.101:12201'

  pg-1:
    image: bitnami/postgresql-repmgr:12.3.0
    environment:
    - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgres_password
    - REPMGR_PARTNER_NODES=pg-0,pg-1
    - REPMGR_NODE_NAME=pg-1
    - REPMGR_NODE_NETWORK_NAME=pg-1
    - REPMGR_PRIMARY_HOST=pg-0
    - REPMGR_PASSWORD_FILE=/run/secrets/repmgr_password
    volumes:
    - pg-replica-vol:/bitnami/postgresql
    - pg-config-vol:/bitnami/repmgr/conf/
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 256000000
    ports:
    - "5433:5432"
    networks:
    - application-net
    deploy:
      placement:
        constraints:
        - node.labels.type != primary
        - node.role == worker
          #endpoint_mode: dnsrr
    configs:
    - source: additional-postgresql.conf
      target: /bitnami/postgresql/conf/conf.d/additional-postgresql.conf
      #- source: pg_hba.conf
      #  target: /bitnami/repmgr/conf/pg_hba.conf
      #  uid: "1001"
      #  gid: "0"
      #  mode: 0774
    secrets:
    - postgres_password
    - repmgr_password
      #logging:
      #  driver: gelf
      #  options:
      #    gelf-address: 'tcp://192.168.137.101:12201'

networks:
  application-net:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  pg-primary-vol:
  pg-replica-vol:
  pg-config-vol:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.137.110,rw"
      device: ":/mnt/storage1/postgresql/conf"

configs:
  additional-postgresql.conf:
    file: additional-postgresql.conf
    name: additional-postgresql.conf-${ADDITIONAL_POSTGRES_CONF}
  pg_hba.conf:
    file: pg_hba.conf
    name: pg_hba.conf-${PG_HBA_CONF}

secrets:
  postgres_password:
    external: true
  repmgr_password:
    external: true
```

**Output of docker version**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of docker info**
```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 8
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: t1hnu0591w01txen8chuue8y0
  Is Manager: true
  ClusterID: lv4nsc1znjt3nvuam6sr4jgt7
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.137.101
  Manager Addresses:
   192.168.137.101:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-9-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.886GiB
 Name: t460s-dockerswarm-1
 ID: HZD6:A6CE:KFV6:7YME:DOSW:QUPB:NVVH:CZBC:3KWJ:BMHO:EY6S:JMHF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
