### ISSUE TITLE
Can't run matomo docker image on the bitnami ghost apache server 

### ISSUE THREAD

**Issue by rimonhanna** [bitnami/containers#1074]
### Name and Version

bitnami/matomo:latest

### What steps will reproduce the bug?

I have an azure VM created from the bitnami ghost template from the azure marketplace
I'm trying to deploy bitnami matomo docker image on the same vm to add analytics to my blog
but the docker container is failing to launch

1. create azure vm with bitnami ghost template
2. install docker & docker-compose on vm
3. download matomo docker-compose file 
4. configure docker-compose file to use persistent path
5. run docker compose up -d command
6. add virtual hosts to apache2 server configuration

docker-compose.yml:

```
version: "2"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    user: root
    restart: always
    ports:
      - "3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=false
      - MARIADB_USER=bn_matomo
      - MARIADB_PASSWORD=bn_matomo@123
      - MARIADB_ROOT_PASSWORD=bn_matomo@123
      - MARIADB_DATABASE=bitnami_matomo
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - "/home/bitnami/matomo/mariadb:/bitnami/mariadb"
  matomo:
    image: docker.io/bitnami/matomo:4
    restart: always
    ports:
      - "7000:8080"
      - "7443:8443"
    extra_hosts:
      - "matomo.rimonhanna.com:127.0.0.1"
    hostname: matomo.rimonhanna.com
    domainname: rimonhanna.com
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=no
      - MATOMO_DATABASE_PASSWORD=bn_matomo@123
    volumes:
      - "/home/bitnami/matomo/matomo:/bitnami/matomo"
    depends_on:
      - mariadb
```

### What is the expected behavior?

docker container launches successfully 

### What do you see instead?

docker container fails and keeps restarting
docker logs rimon_matomo_1    
shows:
```
matomo 21:27:40.37 INFO  ==> ** Starting Matomo setup **
realpath: /bitnami/apache/conf: No such file or directory
matomo 21:27:40.40 INFO  ==> Configuring Apache ServerTokens directive
matomo 21:27:40.41 INFO  ==> Configuring PHP options
matomo 21:27:40.42 INFO  ==> Setting PHP expose_php option
matomo 21:27:40.43 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo 21:27:40.51 INFO  ==> Ensuring Matomo directories exist
matomo 21:27:40.51 INFO  ==> Trying to connect to the database server
matomo 21:27:40.53 INFO  ==> Starting apache in background
[Thu Jul 28 21:27:40.609242 2022] [ssl:warn] [pid 83] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 28 21:27:40.609850 2022] [ssl:warn] [pid 83] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
matomo 21:27:40.65 INFO  ==> apache started
matomo 21:27:40.66 INFO  ==> Passing Matomo installation wizard
matomo 21:27:41.60 ERROR ==> An error occurred while installing Matomo
```
