### ISSUE TITLE
使用docker-compose up -d启动 discourse_discourse_1直接退出

### ISSUE THREAD

**Issue by 601579263** [bitnami/containers#11026]
### Name and Version

bitnami/discourse:2 , discourse_discourse_1

### What steps will reproduce the bug?

直接启动就退出了,数据库能连接上

### What is the expected behavior?

直接启动就退出了,数据库能连接上，
 Populating database这一步就退出了,没有启动成功

### What do you see instead?
```
postgresql_1  | 
postgresql_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresql_1  | 
postgresql_1  | 2022-10-22 04:08:11.556 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgresql_1  | 2022-10-22 04:08:11.557 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql_1  | 2022-10-22 04:08:11.557 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresql_1  | 2022-10-22 04:08:11.558 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql_1  | 2022-10-22 04:08:11.565 UTC [26] LOG:  database system was shut down at 2022-10-22 04:07:13 UTC
postgresql_1  | 2022-10-22 04:08:11.567 UTC [1] LOG:  database system is ready to accept connections
discourse_1   | discourse 04:08:20.96 
discourse_1   | discourse 04:08:20.96 Welcome to the Bitnami discourse container
discourse_1   | discourse 04:08:20.96 Subscribe to project updates by watching https://github.com/bitnami/containers
discourse_1   | discourse 04:08:20.96 Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse_1   | discourse 04:08:20.96 
discourse_1   | discourse 04:08:20.97 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse_1   | discourse 04:08:20.97 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
discourse_1   | discourse 04:08:20.97 INFO  ==> Trying to connect to the database server
discourse_1   | discourse 04:08:20.98 INFO  ==> Creating database example_discourse
discourse_1   | discourse 04:08:21.02 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
discourse_1   | discourse 04:08:21.02 INFO  ==> Creating Discourse configuration file
discourse_1   | discourse 04:08:21.05 INFO  ==> Ensuring Discourse directories exist
discourse_1   | discourse 04:08:21.05 INFO  ==> Trying to connect to the database server
discourse_1   | discourse 04:08:21.06 INFO  ==> Populating database
```

### Additional information

这是docker-compose.yml的文件

```yaml
version: '2'
services:
  postgresql:
    image: postgres:12.4
    volumes:
      - './data:/var/lib/postgresql/data'
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
#      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_DATABASE=example_discourse
      - POSTGRES_POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: docker.io/bitnami/redis:6.0
    user: root
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis12345
    volumes:
      - './data3:/var/lib/redis/data3'
  discourse:
    image: docker.io/bitnami/discourse:2
    ports:
      - '13000:3000'
    volumes:
      - './data1:/var/lib/discourse/data'
    depends_on:
      - postgresql
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_USERNAME=siteadmin
      - DISCOURSE_PASSWORD=siteadmin12345
      - DISCOURSE_HOST=192.168.184.132
      - DISCOURSE_DATABASE_HOST=192.168.184.132
      - DISCOURSE_DATABASE_PORT_NUMBER=15432
      - DISCOURSE_DATABASE_USER=postgres
      - DISCOURSE_DATABASE_PASSWORD=postgres
      - DISCOURSE_DATABASE_NAME=example_discourse
      - DISCOURSE_REDIS_HOST=192.168.184.132
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=example_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - './data2:/var/lib/discourse/data2'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    ports:
      - '14330:3000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_USERNAME=siteadmin
      - DISCOURSE_PASSWORD=siteadmin12345
      - DISCOURSE_HOST=192.168.184.132
      - DISCOURSE_DATABASE_HOST=192.168.184.132
      - DISCOURSE_DATABASE_PORT_NUMBER=15432
      - DISCOURSE_DATABASE_USER=postgres
      - DISCOURSE_DATABASE_PASSWORD=postgres
      - DISCOURSE_DATABASE_NAME=example_discourse
      - DISCOURSE_REDIS_HOST=192.168.184.132
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```
