### ISSUE TITLE
[bitnami/openldap] Setting LDAP_ROOT doesn't affect DN in openldap image

### ISSUE THREAD

**Issue by Venem** [bitnami/containers#11200]
### Name and Version

bitnami/openldap:latest

### What steps will reproduce the bug?

Setting LDAP_ROOT to something other than the default `dn=example,dn=org` does not affect the configuration of the container.

Attempting to set it to `dn=example,dn=com` does not change it accordingly.

Set `LDAP_LOGLEVEL=-1` and run `docker logs -f openldap`.

My docker-compose.yml:
```
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      #- LDAP_ADMIN_PASSWORD_FILE=/run/secrets/openldap_admin
      - LDAP_ADMIN_PASSWORD=pass
      - LDAP_LOGLEVEL=-1
    volumes:
      - ./data:/bitnami/openldap
    restart: unless-stopped
    secrets:
      - openldap_admin
    networks:
      auth:
        ipv4_address: 172.150.1.1

secrets:
  openldap_admin:
    file: ../secrets/openldap_admin

networks:
  auth:
    external: true
```

### What is the expected behavior?

oldRootDN below should be `cn=admin,dc=example,dc=com`.

### What do you see instead?

```
# CRC32 fe2b2cfc
dn: olcDatabase={2}mdb
objectClass: olcDatabaseConfig
objectClass: olcMdbConfig
olcDatabase: {2}mdb
olcDbDirectory: /bitnami/openldap/data
olcDbIndex: objectClass eq,pres
olcDbIndex: ou,cn,mail,surname,givenname eq,pres,sub
structuralObjectClass: olcMdbConfig
entryUUID: 56ac1404-e743-103c-8664-216694aadcba
creatorsName: cn=config
createTimestamp: 20221023172448Z
olcSuffix: dc=example,dc=org
olcRootDN: cn=admin,dc=example,dc=org
olcRootPW:: <REDACTED_PASSWORD_HASH>
entryCSN: 20221023172449.118557Z#000000#000#000000
modifiersName: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
modifyTimestamp: 20221023172449Z
```
### Additional information

I'm not experienced with LDAP so if this is a configuration error on my part, I apologise. Thanks in advance.

edit: fix image tag
