### ISSUE TITLE
[bitnami/jaspereports] Running upgrade script fail

### ISSUE THREAD

**Issue by rombru** [bitnami/containers#11414]
### Name and Version

bitnami/jaspereports:8.1.0

### What steps will reproduce the bug?

Hello,

1. Run jasperreports using docker-compose up, with a postgres database

Exemple of services :
```yaml
jasperreports:
    container_name: jasperreports
    image: docker.io/bitnami/jasperreports:8.1.0
    ports:
      - '8081:8080'
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    depends_on:
      - db-postgresql
    environment:
      - JASPERREPORTS_USERNAME=jasperadmin
      - JASPERREPORTS_PASSWORD=jasperadmin
      - JASPERREPORTS_DATABASE_TYPE=postgresql
      - JASPERREPORTS_DATABASE_HOST=db-postgresql
      - JASPERREPORTS_DATABASE_NAME=test
      - JASPERREPORTS_DATABASE_USER=test
      - JASPERREPORTS_DATABASE_PASSWORD=test
      - JASPERREPORTS_DATABASE_PORT_NUMBER=5432
    networks:
      my-network-docker:
  db-postgresql:
    container_name: db-postgresql
    image: postgis/postgis:13-master
    volumes:
      - ./postgres-initdb/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 9432:5432
    networks:
      my-network-docker:

volumes:
    jasperreports_data:

networks:
  my-network-docker:
    driver: bridge
```
2. Let the containers initialize themselves, everything works fine
3. Stop the containers
4. Redo docker-compose up
5. At the step "Running upgrade script", jasper try to re-execute the last scripts
https://github.com/TIBCOSoftware/jasperreports-server-ce/blob/master/jasperserver/buildomatic/install_resources/sql/postgresql/upgrade-postgresql-8.0.0-8.1.0-ce.sql
And fail because these statements have already been executed

The same kind of behavior happened with the version 8, and 8.0.2

### What is the expected behavior?

Not reexecute the update every time the container is started 

### What do you see instead?
```
jasperreports | jasperreports 18:14:11.59 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
jasperreports | jasperreports 18:14:11.60 INFO  ==> Configuring port numbers
jasperreports | jasperreports 18:14:11.61 INFO  ==> Persisted webapps detected
jasperreports | jasperreports 18:14:11.63 INFO  ==> Restoring persisted JasperReports installation
jasperreports | jasperreports 18:14:11.65 INFO  ==> Trying to connect to the database server
jasperreports | jasperreports 18:14:11.68 INFO  ==> Executing upgrade scripts
jasperreports | jasperreports 18:14:11.68 INFO  ==> Running upgrade script
postgresql    | 2022-10-25 18:14:14.723 UTC [37] ERROR:  relation "jifavoriteresource" already exists
postgresql    | 2022-10-25 18:14:14.723 UTC [37] STATEMENT:    create table JIFavoriteResource ( id int8 not null, user_id int8 not null, resource_id int8 not null, creation_date timestamp not null, primary key (id) )
postgresql    | 2022-10-25 18:14:14.727 UTC [37] ERROR:  relation "ukrj25jnmtcmddlfp23n7duhpv" already exists
postgresql    | 2022-10-25 18:14:14.727 UTC [37] STATEMENT:    alter table JIFavoriteResource add constraint UKrj25jnmtcmddlfp23n7duhpv unique (user_id, resource_id)
postgresql    | 2022-10-25 18:14:14.727 UTC [37] ERROR:  constraint "fke3ak4arnheeorbrsc4u8m8pi0" for relation "jifavoriteresource" already exists
postgresql    | 2022-10-25 18:14:14.727 UTC [37] STATEMENT:    alter table JIFavoriteResource add constraint FKe3ak4arnheeorbrsc4u8m8pi0 foreign key (user_id) references JIUser on delete cascade
postgresql    | 2022-10-25 18:14:14.728 UTC [37] ERROR:  constraint "fk63man3dkmekfr2hgfifi3ne8c" for relation "jifavoriteresource" already exists
postgresql    | 2022-10-25 18:14:14.728 UTC [37] STATEMENT:    alter table JIFavoriteResource add constraint FK63man3dkmekfr2hgfifi3ne8c foreign key (resource_id) references JIResource on delete cascade
postgresql    | 2022-10-25 18:14:14.728 UTC [37] ERROR:  relation "jifavoriteresource_resource_id_idx" already exists
postgresql    | 2022-10-25 18:14:14.728 UTC [37] STATEMENT:    create index JIFavoriteResource_resource_id_idx on JIFavoriteResource (resource_id)
```
