### ISSUE TITLE
[bitnami/openldap] Certificate modification is not detected automatically.

### ISSUE THREAD

**Issue by FabienZa** [bitnami/containers#12828]
### Name and Version

bitnami/openldap:2.6

### Environment :  
Ubuntu Server 22.04
### Config :  
docker-compose.yml
```yml
services:
  openldap:
    image: bitnami/openldap:2.6
    env_file: openldap.env
    ports:
      - 636:1636
    volumes:
      - ./data:/bitnami/openldap
      - ./certs:/opt/bitnami/openldap/certs
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
```

In container /opt/bitnami/openldap/certs
```bash
/opt/bitnami/openldap/certs$ ls
cert.pem  isrg-root-x1-cross-signed.pem  key.pem 
```

### What is the expected behavior?

The openldap container should automatically detect and use the newly generated certificate?

### What do you see instead?

Certificate modification is not detected automatically.

So when the certificate is expired and the new certificate was not detected we have the errors :  
```
ldap-openldap-1  | 636787d1.378875fd 0x7f2d13fff700 TLS: can't accept: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired.
ldap-openldap-1  | 636787d1.378accd5 0x7f2d13fff700 conn=446084 fd=14 closed (TLS negotiation failure)
```

We need to restart container to use the new certificate.

### Error :   
Certificate modification is not detected automatically.

Our certificate expires every 3 months. It is automatically renewed before it expires. Unfortunately, the container openldap does not detect its renewal and continues to use the old certificate. When it expires we can no longer use openldap. For the new certificate to take effect, we must restart the container.

Is this a bug or is this the normal behavior of the container? If this is the normal behavior, how to make openldap detect the certificate change without having to restart the container ?

Thank you for your help.
