### ISSUE TITLE
Replica set of mongo not able to connect to Primary node in Docker Swarm

### ISSUE THREAD

**Issue by jainamtrivedi-crest** [bitnami/containers#13145]
### Name and Version

bitnami/mongodb:4.4

### What steps will reproduce the bug?

I want to deploy my application over docker swarm. I have configured mongodb-primary as the primary node and created two replicas as mentioned in the official docs [here](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/docker-compose-replicaset.yml).

Here is my docker-compose.yml file:
```yaml
version: '3.3'

services:
  rabbitmq-stats:
    image: docker.io/bitnami/rabbitmq:3.8
    networks:
      - app-tier
    volumes:
      - /mnt/nfs/opt/NFSdir/rabbitmq-stats:/bitnami
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
      - BITNAMI_DEBUG=true
    ports:
      - '15672:15672'
  rabbitmq-disc1:
    image: docker.io/bitnami/rabbitmq:3.8
    networks:
      - app-tier
    volumes:
      - /mnt/nfs/opt/NFSdir/rabbitmq-disc1:/bitnami
    depends_on:
      - rabbitmq-stats
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
  mongodb-primary:
    image: docker.io/bitnami/mongodb:4.4
    networks:
      - app-tier
    volumes:
      - type: volume
        source: mongodb-primary-storage
        target: /bitnami/mongodb
        volume:
          nocopy: true
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=cteadmin
      - MONGODB_PASSWORD=cteadmin
      - MONGODB_DATABASE=cte
      - BITNAMI_DEBUG=true
  mongodb-replica1:
    image: docker.io/bitnami/mongodb:4.4
    networks:
      - app-tier
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-replica1
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
  mongodb-replica2:
    image: docker.io/bitnami/mongodb:4.4
    networks:
      - app-tier
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-replica2
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
  core:
    image: docker.io/netskopetechnicalalliances/cloudexchange:core4-latest
    networks:
      - app-tier
    depends_on:
      - mongodb-primary
      - rabbitmq-stats
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: plugins-dir
        target: /opt/netskope/plugins
      - type: volume
        source: repos-dir
        target: /opt/netskope/repos
    environment:
      - MONGO_CONNECTION_STRING=mongodb://cteadmin:cteadmin@mongodb-primary:27017,mongodb-replica1:27017,mongodb-replica2:27017/cte?replicaSet=replicaset
      - RABBITMQ_CONNECTION_STRING=amqp://user:bitnami@rabbitmq-stats;amqp://user:bitnami@rabbitmq-disc1
      - JWT_SECRET=secret
      - JWT_ALGORITHM=HS256
      - DOCKER_USERNAME=DOCKER_USERNAME
      - DOCKER_PASSWORD=DOCKER_PASSWORD
      - ENABLE_CELERY_BEAT=true
      - ANALYTICS_BASE_URL=http://localhost
      - ANALYTICS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbnN0YWxsYXRpb25faWQiOiJjMDAyIn0.w8SVrTcDjk8PkR4IcbWGwOyf6-OWfCUyOoCTgZvqHqc
    deploy:
      labels:
        - "traefik.http.routers.ce-api.rule=PathPrefix(`/api`)"
        - "traefik.http.services.ce-api.loadbalancer.server.port=80"
  worker:
    image: docker.io/testRepo/core:latest
    networks:
      - app-tier
    depends_on:
      - mongodb-primary
      - rabbitmq-stats
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs/opt/NFSdir/repos-dir:/opt/netskope/repos
      - /mnt/nfs/opt/NFSdir/plugins-dir:/opt/netskope/plugins
    environment:
      - MONGO_CONNECTION_STRING=mongodb://cteadmin:cteadmin@mongodb-primary:27017,mongodb-replica1:27017,mongodb-replica2:27017/cte?replicaSet=replicaset
      - RABBITMQ_CONNECTION_STRING=amqp://user:bitnami@rabbitmq-stats;amqp://user:bitnami@rabbitmq-disc1
      - JWT_SECRET=secret
      - JWT_ALGORITHM=HS256
      - DOCKER_USERNAME=DOCKER_USERNAME
      - DOCKER_PASSWORD=DOCKER_PASSWORD
      - ENABLE_CELERY_BEAT=false
      - ANALYTICS_BASE_URL=http://localhost
      - ANALYTICS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbnN0YWxsYXRpb25faWQiOiJjMDAyIn0.w8SVrTcDjk8PkR4IcbWGwOyf6-OWfCUyOoCTgZvqHqc
    deploy:
      labels:
        - "traefik.http.services.ce-api.loadbalancer.server.port=80"
  ui:
    image: index.docker.io/testRepo/ui:latest
    networks:
      - app-tier
    environment:
      - CE_API_URL=http://10.50.4.93/api # should be the address of traefik
    deploy:
      labels:
        - "traefik.http.routers.ce-ui.rule=PathPrefix(`/`)"
        - "traefik.http.services.ce-ui.loadbalancer.server.port=3000"
  traefik:
    image: traefik
    networks:
      - app-tier
    command: --api.insecure=true --providers.docker --providers.docker.swarmmode=true --log.level=DEBUG
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  app-tier:
    driver: overlay

volumes:
  mongodb-primary-storage:
    driver_opts:
      type: "nfs"
      o: "addr=10.50.2.89,nolock,soft,rw"
      device: ":/opt/NFSdir/mongodb-primary"
  plugins-dir:
    driver_opts:
      type: "nfs"
      o: "addr=10.50.2.89,nolock,soft,rw"
      device: ":/opt/NFSdir/plugins-dir"
  repos-dir:
    driver_opts:
      type: "nfs"
      o: "addr=10.50.2.89,nolock,soft,rw"
      device: ":/opt/NFSdirx/repos-dir"
```

Deploy this stack using docker stack command. UI and rabbitmq services are working fine but mongo replicas are not able to connect with `mongodb-primary`. It is throwing `MongoNetworkError: connect ECONNREFUSED 10.0.3.18:27017` and `cannot resolve host "mongodb-primary": lookup mongodb-primary on 127.0.0.11:53: server misbehaving` error while checking the logs of replicas' container. 

Also, the core container cannot connect with MongoDB containers and throw `ServerSelectionTimeout`. I suspect the issue is related to networking.

### What is the expected behavior?

Mongo Replicas should be able to connect with its primary host `mongodb-primary` and core should connect with MongoDB as well.

### What do you see instead?

It is throwing `MongoNetworkError: connect ECONNREFUSED 10.0.3.18:27017` and `cannot resolve host "mongodb-primary": lookup mongodb-primary on 127.0.0.11:53: server misbehaving` error while checking the logs of replicas' container. 

Also, the core container cannot connect with MongoDB containers and throw `ServerSelectionTimeout`. I suspect the issue is related to networking.
