### ISSUE TITLE
[bitnami/kafka] consumer connection timeout 

### ISSUE THREAD

**Issue by aozertsov** [bitnami/containers#13720]
### Name and Version

bitnami/kafka:3.2

### What steps will reproduce the bug?

I have the follow compose:

```
version: '3'
services:
  zookeeper:
    image: "bitnami/zookeeper"
    ports:
      - "2181:2181"
    environment:
      ZOO_ENABLE_AUTH: "yes"
      ZOO_SERVER_USERS: "zkclient"
      ZOO_SERVER_PASSWORDS: "zkpass"
      ZOO_CLIENT_USER: "zkclient"
      ZOO_CLIENT_PASSWORD: "zkpass"
      ZOO_MAX_SESSION_TIMEOUT: "400000"
    networks:
      - kafka-network

  kafka-server1:
    image: "bitnami/kafka:3.2"
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "INTERNAL://:29092,CLIENT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-server1:29092,CLIENT://<externalIPfor connection>:9092"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_MESSAGE_MAX_BYTES: 10000
      KAFKA_MESSAGE_MAX_BYTES: 10000

        #Client credentials
      KAFKA_CLIENT_USERS: "zkclient1"
      KAFKA_CLIENT_PASSWORDS: "zkpass1"
      #Zookeeper credentials
      KAFKA_ZOOKEEPER_PROTOCOL: "SASL"
      KAFKA_ZOOKEEPER_USER: "zkclient"
      KAFKA_ZOOKEEPER_PASSWORD: "zkpass"
      # OLD creds
      KAFKA_INTER_BROKER_USER: "zkclient"
      KAFKA_INTER_BROKER_PASSWORD: "zkpass"
    networks:
      - kafka-network
    depends_on:
      - zookeeper
```

bitnami produced follow kafka_jaas.conf:

`KafkaClient {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="zkclient1"
   password="zkpass1";
   };
KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="zkclient"
   password="zkpass"
   user_zkclient="zkpass"
   user_zkclient1="zkpass1";
   org.apache.kafka.common.security.scram.ScramLoginModule required;
   };
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="zkclient"
   password="zkpass";
   };`

Cluster starts and works correct, producer works by internal connection.
But, when I try to connect consumer (for example via Offset explorer), it's raise Timeout connection.

### What is the expected behavior?

Consumer connects to kafka with follow creds: 
`org.apache.kafka.common.security.plain.PlainLoginModule required username="zkclient1" password="zkpass1";`

### What do you see instead?

Timeout connection
