### ISSUE TITLE
[bitnami/tensorflow-serving] Configuration file mount not working

### ISSUE THREAD

**Issue by luomoxu** [bitnami/containers#13773]
### Name and Version

bitnami/tensorflow-serving:2.10.0

### What steps will reproduce the bug?

In the doc about Configuration file said
The image looks for configurations in `/bitnami/tensorflow-serving/conf/`
and in the example
```
services:
  tensorflow-serving:
  ...
    volumes:
      - /path/to/tensorflow-serving-persistence:/bitnami
  ...
```
```
$ vi /path/to/tensorflow-serving-persistence/conf/tensorflow-serving.conf
```
this is two different directory 

but it not most importantly

when I mount the `/bitnami` and try to set tensorflow-serving.conf with two different path

It not working for both path

### What do you see instead?

It not working for both path

**Comment by javsalgar** [comment]
Hi,

Could you share a complete docker-compose.yml that triggers the issue?

**Comment by luomoxu** [comment]
> 

I use in k8s,

> Hi,
> 
> Could you share a complete docker-compose.yml that triggers the issue?

```
version: '2'

services:
  tensorflow-serving:
    image: docker.io/bitnami/tensorflow-serving:2
    ports:
      - '8500:8500'
      - '8501:8501'
    volumes:
      - '/opt/tensorflow-serving/data:/bitnami'
```
