### ISSUE TITLE
trouble checking health for `mysql` containers because of `mysql_upgrade`-related restarts

### ISSUE THREAD

**Issue by hood** [bitnami/containers#13937]
### Name and Version

bitnami/mysql:8.0.28

### What steps will reproduce the bug?

Given a docker-compose file where a service depends on a `db` service which looks like the following
```yaml
  db:
    image: bitnami/mysql:8.0.28
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    healthcheck:
      test: "[ -f '/var/lib/mysql/mysql_upgrade_info' ] && out=$$(mysqladmin ping --host localhost --port 3306 --user myuser --password=mypassword 2&1); echo $$out | grep 'mysqld is alive' || { echo 'Healthcheck failed.'; exit 1; }"
      start_period: 10s
      interval: 4s
      timeout: 2s
      retries: 24
```

I'm having trouble checking the `db` container health state, since it's reporting a false `healthy` state, because the following steps (reporting log entries excerpts for clarity):
- Starting mysql in background
- Configuring authentication
- Running mysql_upgrade
- Stopping mysql
- Starting mysql in background
- Stopping mysql
- Starting MySQL 

Cause false positives, since the `mysql` process gets started and then stopped a few times.

### What is the expected behavior?

It'd be nice to have a solid, dependable way of determining wether the container is up and running and has finished the `mysql_upgrade` process. I've tried any kind of possible hack, but I see no way of checking whether the `mysql_upgrade` process has run already before proceeding with other healthchecks.

### What do you see instead?

False positives if the healthcheck happens in the middle of a start-stop cycle.
