### ISSUE TITLE
Dokuwiki After update to latest - error 500

### ISSUE THREAD

**Issue by stanthewizzard** [bitnami/containers#14153]
### Name and Version

bitnami/dokuwiki

### What steps will reproduce the bug?

docker compose

```yaml
version: '2'
services:
  dokuwiki:
    image: bitnami/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - '4040:8080'
    volumes:
      - /root/dokuwiki/data:/bitnami/dokuwiki
    environment:
      - DOKUWIKI_USERNAME=xxxx
      - DOKUWIKI_FULL_NAME=xxxx
      - DOKUWIKI_PASSWORD=passxxxx
      - DOKUWIKI_EMAIL=mailxxxx
      - DOKUWIKI_WIKI_NAME=xxxx

volumes:
  dokuwiki_data:
    driver: local
```

### What is the expected behavior?

Error 500
not working anymore

Recreating lead to same behavior

### What do you see instead?

```
dokuwiki 09:42:58.89 Welcome to the Bitnami dokuwiki container
dokuwiki 09:42:58.89 Subscribe to project updates by watching https://github.com/bitnami/containers
dokuwiki 09:42:58.89 Submit issues and feature requests at https://github.com/bitnami/containers/issues
dokuwiki 09:42:58.90 
dokuwiki 09:42:58.90 INFO  ==> ** Starting DokuWiki setup **
realpath: /bitnami/apache/conf: No such file or directory
dokuwiki 09:42:58.93 INFO  ==> Configuring Apache ServerTokens directive
dokuwiki 09:42:58.95 INFO  ==> Configuring PHP options
dokuwiki 09:42:58.95 INFO  ==> Setting PHP expose_php option
dokuwiki 09:42:59.05 INFO  ==> Restoring persisted DokuWiki installation
dokuwiki 09:42:59.46 INFO  ==> ** DokuWiki setup finished! **
dokuwiki 09:42:59.48 INFO  ==> ** Starting Apache **
[Fri Nov 18 09:42:59.570169 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Fri Nov 18 09:42:59.570745 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Nov 18 09:42:59.599381 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Fri Nov 18 09:42:59.599841 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Nov 18 09:42:59.611359 2022] [core:warn] [pid 1] AH00098: pid file /opt/bitnami/apache/var/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Nov 18 09:42:59.614572 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri Nov 18 09:42:59.614637 2022] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
[Fri Nov 18 09:43:09.551447 2022] [php7:warn] [pid 109] [client 192.168.0.30:47360] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Fri Nov 18 09:43:09.551497 2022] [php7:error] [pid 109] [client 192.168.0.30:47360] PHP Fatal error:  Unknown: Failed opening required '/opt/bitnami/dokuwiki/conf/auto_prepend.php' (include_path='.:/opt/bitnami/php/lib/php') in Unknown on line 0
192.168.0.30 - - [18/Nov/2022:09:43:09 +0000] "GET / HTTP/1.1" 500 -
```
