### ISSUE TITLE
[bitnami/mongodb] :13.4.4 stuck forever at `Validating settings in MONGODB_* env vars` helm

### ISSUE THREAD

**Issue by aniruddha2000** [bitnami/containers#14551]
### Name and Version

bitnami/mongodb:13.4.4

### What steps will reproduce the bug?

Arch - Arm64 MacBook Pro M1 Pro

Added mongodb as dependency in any project on MacBook M1 Pro.
When I start the entire project using `helm install <app-name> charts/` 

### What is the expected behavior?

Expected behaviour would be the mongodb running and showing 1/1 in the kubernetes output.

### What do you see instead?

```bash
mongodb 10:16:21.43                                                                                                                                   │                              │
│ mongodb 10:16:21.60 Welcome to the Bitnami mongodb container                                                                                          │                              │
│ mongodb 10:16:21.64 Subscribe to project updates by watching https://github.com/bitnami/containers                                                    │                              │
│ mongodb 10:16:21.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues                                                │                              │
│ mongodb 10:16:21.82                                                                                                                                   │                              │
│ mongodb 10:16:21.92 INFO  ==> ** Starting MongoDB setup **                                                                                            │                              │
│ mongodb 10:16:22.30 INFO  ==> Validating settings in MONGODB_* env vars...                                                                            │                              │
│ mongodb 10:38:15.28 INFO  ==> Initializing MongoDB...                                                                                                 │                              │
│ mongodb 10:40:41.21 INFO  ==> Deploying MongoDB from scratch...
```

Here it stuck for a long time

**Comment by aniruddha2000** [comment]
Some helm snippets

values.yaml - 
```yaml
mongodb:
  enabled: true
  auth:
    enabled: true
    username: admin
    database: gin-api-db
    existingSecret: mongodb-secret
```

_helpers.tpl
```yaml
{{/*
MongoDB ENV variables
*/}}
{{- define "chart.envMongo" -}}
{{- if .Values.mongodb.enabled -}}
- name: MONGODB_HOST
  value: "{{ include "chart.callNested" (list . "mongodb" "mongodb.fullname") }}"
{{- end }}
- name: MONGODB_DATABASE
  value: {{ .Values.mongodb.auth.database }}
- name: MONGODB_PORT
  value: "27017"
- name: MONGODB_USER
  value: {{ .Values.mongodb.auth.username }}
- name: MONGODB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.mongodb.auth.existingSecret }}
      key: mongodb-passwords
- name: MONGODB_ROOT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.mongodb.auth.existingSecret }}
      key: mongodb-root-password
{{- end }}
```

secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
type: Opaque
data:
  mongodb-passwords: cm9vdHBhc3N3b3JkCg==
  mongodb-root-password: cm9vdHBhc3N3b3JkCg==

```

**Comment by javsalgar** [comment]
Hi,

We've received issues with MongoDB amd64 on M1 machines. I'm afraid that this application in amd64 is not compatible with Macbook M1.

**Comment by aniruddha2000** [comment]
Is there any other workaround I can do? :)

**Comment by javsalgar** [comment]
Right now I didn't see any working workaround. However, I will leave this ticket open in case someone from the community wants to participate with their own experience.

**Comment by pedroresende** [comment]
I believe the problem to be m1 related, I've got exactly the same problem with docker-compose

```yaml
version: '3.8'
services:
  database:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_REPLICA_SET_KEY=replica
    ports:
      - '27017:27017'
    volumes:
      - ./data:/bitnami/mongodb
```
