### ISSUE TITLE
[bitnami/openldap] Mount volume not working

### ISSUE THREAD

**Issue by wiryonolau** [bitnami/containers#1475]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

docker-compose.yml
```yaml
version: "3.7"

services:
    openldap:
        image: bitnami/openldap:2.6
        ports:
            - "1636:1636"
        environment:
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=password
            - LDAP_ENABLE_TLS=yes
            - LDAP_LDAPS_PORT_NUMBER=1636
            - LDAP_ALLOW_ANON_BINDING=no
            - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
            - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
            - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldap.ca
        volumes:
            - ./data:/bitnami/openldap/
            - ./certs:/opt/bitnami/openldap/certs
```

```bash
docker-compose up
```

### What is the expected behavior?

Running normally

### What do you see instead?

```bash
[+] Running 1/1
 ⠿ Container openldap-openldap-1  Recreated                                              0.1s
Attaching to openldap-openldap-1
openldap-openldap-1  |  14:11:57.71 INFO  ==> ** Starting LDAP setup **
openldap-openldap-1  |  14:11:57.74 INFO  ==> Validating settings in LDAP_* env vars
openldap-openldap-1  |  14:11:57.75 INFO  ==> Initializing OpenLDAP...
openldap-openldap-1  | mkdir: cannot create directory '/bitnami/openldap/data': Permission denied
openldap-openldap-1 exited with code 1
```

If **data** folder not mount to /bitnami/openldap it works ok

**Comment by javsalgar** [comment]
Hi,

Bind mounting local volumes is problematic when working with non-root containers. Could you try adding more open permissions to the folder? Could you try with 777?

**Comment by justintime4tea** [comment]
I looked at all the other answers on the previous repo and here and none of it worked for me. What DID work is setting the user explicitly to 1000 like so:

```
openldap:
    user: "1000"
    container_name: openldap
    image: bitnami/openldap:latest
    env_file:
      - ./compose.env
    restart: unless-stopped
    ports:
      - '1389:1389'
      - '1636:1636'
    volumes:
      - ./openldap_data:/bitnami/openldap
```
