### ISSUE TITLE
[bitnami/schema-registry] Schema Registry container does not take into account environment variables

### ISSUE THREAD

**Issue by vivere-dally** [bitnami/containers#14849]
### Name and Version

bitnami/schema-registry:latest

### What steps will reproduce the bug?

1. Create a docker compose file
2. For schema registry, write the following config:
```yml
  kafka-schema-registry:
    image: bitnami/schema-registry
    container_name: kafka-schema-registry
    ports:
      - '5001:8081'
    restart: always
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=localhost:9092
      - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM=PLAIN
      - SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="<user>" password="<pass>";
```

### What do you see instead?

> [2022-11-24 12:55:54,117] INFO Logging initialized @448ms to org.eclipse.jetty.util.log.Slf4jLog (org.eclipse.jetty.util.log:170)
[2022-11-24 12:55:54,139] INFO Initial capacity 128, increased by 64, maximum capacity 2147483647. (io.confluent.rest.ApplicationServer:619)[2022-11-24 12:55:54,199] INFO Adding listener with HTTP/2: http://0.0.0.0:8081 (io.confluent.rest.ApplicationServer:488)
[2022-11-24 12:56:54,528] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication:77)io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryException: Failed to get Kafka cluster ID
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1574)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:171)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:71)   
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:90)
        at io.confluent.rest.Application.configureHandler(Application.java:285)
        at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:270)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.kafkaClusterId(KafkaSchemaRegistry.java:1572)
        ... 7 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes

### Additional information

The container does not take into account the environment variables that I am passing. Why is that? I was following this documentation from [confluent](https://docs.confluent.io/platform/current/schema-registry/installation/config.html).

Moreover, your [README](https://github.com/bitnami/containers/tree/main/bitnami/schema-registry) file on schema registry contains little to no information about configuring the container, as opposed to the Kafka container which has lots of examples.
