### ISSUE TITLE
[bitnami/logstash] custom build for plugins doesn't work

### ISSUE THREAD

**Issue by maxisam** [bitnami/containers#14942]
### Name and Version

bitnami/logstash:8.5.2-debian-11

### What steps will reproduce the bug?

Run the command like

`$ docker build --build-arg LOGSTASH_PLUGINS=logstash-input-s3 -t bitnami/logstash:latest 'https://github.com/bitnami/containers/blob/main/bitnami/logstash.git#master:8/debian-11'`

pull the repo and run the build locally still don't work

it throws error like

```sh
 > [ 9/10] RUN /opt/bitnami/scripts/logstash/postunpack.sh:
#13 0.513 logstash 18:06:27.13 INFO  ==> Creating Logstash daemon user
#13 23.52 logstash 18:06:50.14 INFO  ==> Configuring paths
#13 23.54 logstash 18:06:50.16 INFO  ==> Configuring logging to standard output
#13 23.54 logstash 18:06:50.16 INFO  ==> Installing plugins: logstash-input-s3
executor failed running [/bin/bash -o pipefail -c /opt/bitnami/scripts/logstash/postunpack.sh]
```
I tried kafka, it throws the same error

### What is the expected behavior?

it should work

### What do you see instead?

It throws error

**Comment by jotamartos** [comment]
Hi @maxisam,

If you deploy a fresh logstash container, you can test the plugin installation manually before automating it. The problem with logstash-input-s3 is this one

```
$ logstash-plugin install logstash-input-s3
...
Validating logstash-input-s3
ERROR: Installation aborted, plugin 'logstash-input-s3' is already provided by 'logstash-integration-aws'
``` 

However, I reproduced the issue when installing the kafka one (logstash-integration-kafka). As a workaround, you can set the plugin to install during the deployment process, for example by editing the docker-compose.yml file 

```
...
  logstash:
    image: docker.io/bitnami/logstash:8
    ports:
      - 8080:8080
    volumes:
      - logstash_data:/bitnami
    environment:
      - LOGSTASH_PLUGINS=logstash-integration-kafka
...
```

We will release a new revision of the container fixing the issue during the build process. 

Thanks
