### ISSUE TITLE
/opt/bitnami/scripts/libclickhouse.sh: line 94: CLICKHOUSE_MOUNTED_DIR: unbound variable

### ISSUE THREAD

**Issue by sigaev-pro** [bitnami/containers#14945]
### Name and Version

bitnami/clickhouse:latest

### What steps will reproduce the bug?

On locale, it's working perfectly. Here is the full docker-compose.yml:

```yaml
services:
  backend:
    profiles:
      - dev
      - prod
    build:
      context: ./backend
    container_name: jedi-backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      TRAEFIK_VIRTUAL_HOST: django.tradejedizzz123.xyz
    env_file:
      - environment.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.django.rule: Host(`django.tradejedizzz123.xyz`)
      traefik.http.routers.django.tls: "true"
      traefik.http.routers.django.tls.certresolver: letsEncrypt
    networks:
      proxy-django: null
      backend-database: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    restart: always

  mariadb:
    profiles:
      - dev
      - prod
    container_name: jedi-mariadb
    env_file:
      - environment.env
    image: mariadb:10.8
    networks:
      backend-database: null
      mariadb-phpmyadmin: null
    ports:
      - mode: ingress
        target: 3306
        published: "3306"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: ./volumes/mariadb-data
        target: /var/lib/mysql
      - type: bind
        source: ./volumes/mariadb-logs
        target: /var/log/mysql

  clickhouse:
    profiles:
      - dev
      - prod
    container_name: jedi-clickhouse
    env_file:
      - environment.env
    image: bitnami/clickhouse:latest
    networks:
      backend-database: null
    ports:
      - mode: ingress
        target: 9000
        published: "9000"
        protocol: tcp
      - mode: ingress
        target: 8123
        published: "8123"
        protocol: tcp
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    restart: always
    volumes:
      - type: bind
        source: ./volumes/clickhouse-config
        target: /etc/clickhouse-server

  redis:
    profiles:
      - dev
      - prod
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    container_name: jedi-redis
    env_file:
      - environment.env
    image: redis:7.0-alpine
    networks:
      backend-database: null
      redis-redis-insight: null
    ports:
      - mode: ingress
        target: 6379
        published: "6379"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: ./volumes/redis-data
        target: /data

  db-admin-phpmyadmin:
    profiles:
      - dev
      - prod
    container_name: jedi-phpmyadmin
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - environment.env
    image: phpmyadmin/phpmyadmin:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin.rule: Host(`phpmyadmin.tradejedizzz123.xyz`)
      traefik.http.routers.phpmyadmin.tls: "true"
      traefik.http.routers.phpmyadmin.tls.certresolver: letsEncrypt
    networks:
      mariadb-phpmyadmin: null
      proxy-phpmyadmin: null
    volumes:
      - type: bind
        source: ./volumes/phpmyadmin-sessions
        target: /sessions

  db-admin-redis-insight:
    profiles:
      - dev
      - prod
    container_name: jedi-dbadmin-redis-insight
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      TRAEFIK_VIRTUAL_HOST: redis-insight.tradejedizzz123.xyz
    image: redislabs/redisinsight:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.redis-insight.rule: Host(`redis-insight.tradejedizzz123.xyz`)
      traefik.http.routers.redis-insight.tls: "true"
      traefik.http.routers.redis-insight.tls.certresolver: letsEncrypt
    networks:
      proxy-redis-insight: null
      redis-redis-insight: null

  frontend-vue:
    profiles:
      - dev
      - prod
    build:
      context: ./frontend-vue
    container_name: jedi-frontend-vue
    depends_on:
      backend:
        condition: service_started
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      TRAEFIK_VIRTUAL_HOST: vue.tradejedizzz123.xyz
    labels:
      traefik.enable: "true"
      traefik.http.routers.vue.rule: Host(`vue.tradejedizzz123.xyz`)
      traefik.http.routers.vue.tls: "true"
      traefik.http.routers.vue.tls.certresolver: letsEncrypt
    networks:
      frontend-backend: null
      proxy-vue: null
    restart: always

  proxy-traefik:
    profiles:
      - prod
    command:
      - --providers.docker
    container_name: jedi-proxy-traefik
    image: traefik:v2.8.0
    networks:
      proxy-django: null
      proxy-phpmyadmin: null
      proxy-redis-insight: null
      proxy-vue: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./volumes/traefik-proxy-config
        target: /etc/traefik
        read_only: true
networks:
  backend-database: {}
  frontend-backend: {}
  mariadb-phpmyadmin: {}
  proxy-django: {}
  proxy-phpmyadmin: {}
  proxy-redis-insight: {}
  proxy-vue: {}
  redis-redis-insight: {}
```

But absolutely the same project on Ubuntu 22.04 server is not working.

I'm cloning repo by the root user, and make `sudo docker compose --profile dev up` and receive in log an error `/opt/bitnami/scripts/libclickhouse.sh: line 94: CLICKHOUSE_MOUNTED_DIR: unbound variable`

All volumes folders are created by the same user (root), nothing changed (absolutely clear OS), and enough resources (much more than on the dev machine). 

### What do you see instead?

It is problem with file permissions. I have tried to make structure myself with 0666 permissions, but it is not successful...
