### ISSUE TITLE
[bitnami/postgresql] "Permission denied" that occurs even when UID is 1001

### ISSUE THREAD

**Issue by dungsil** [bitnami/containers#1543]
### Name and Version

bitnami/postgresql:11

### What steps will reproduce the bug?

1. Write docker-compose.yml
```yaml
version: '3.8'
networks:
  postgres:
    driver: bridge
services:
  postgres__main:
    image: bitnami/postgresql:11
    restart: always
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/main/data:/bitnami/postgresql/data"
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: postgres
      POSTGRESQL_REPLICATION_PASSWORD: postgres
```
2. Run command `docker-compose up`

### What is the expected behavior?

Postgres Container running

### What do you see instead?

```
postgres__main_1  | postgresql 07:24:08.12 
postgres__main_1  | postgresql 07:24:08.12 Welcome to the Bitnami postgresql container
postgres__main_1  | postgresql 07:24:08.13 Subscribe to project updates by watching https://github.com/bitnami/containers
postgres__main_1  | postgresql 07:24:08.13 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgres__main_1  | postgresql 07:24:08.13 
postgres__main_1  | postgresql 07:24:08.16 INFO  ==> ** Starting PostgreSQL setup **
postgres__main_1  | postgresql 07:24:08.19 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres__main_1  | postgresql 07:24:08.20 INFO  ==> Loading custom pre-init scripts...
postgres__main_1  | postgresql 07:24:08.20 INFO  ==> Initializing PostgreSQL database...
postgres__main_1  | mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```

### Additional information

my directory permission
```
$ ls -al ./data/main

drwxrwx--- 3 1001 1001 4096  8월  2 16:19 .
drwxrwx--- 3 1001 1001 4096  8월  2 16:02 ..
drwxrwx--- 2 1001 1001 4096  8월  2 16:19 data
```

**Comment by javsalgar** [comment]
Hi,

Bind-mounting volumes is always problematic in non-root containers. Could you try adding more open permissions to the folder like 777?

**Comment by dungsil** [comment]
Hello @javsalgar ,

I changed the permission to 777 but I get the error `Operation not permitted`.

```
postgres__main_1  | postgresql 16:12:34.70 INFO  ==> ** Starting PostgreSQL setup **
postgres__main_1  | postgresql 16:12:34.72 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres__main_1  | postgresql 16:12:34.72 INFO  ==> Loading custom pre-init scripts...
postgres__main_1  | postgresql 16:12:34.73 INFO  ==> Initializing PostgreSQL database...
postgres__main_1  | chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgres__main_1  | postgresql 16:12:34.74 WARN  ==> Lack of permissions on data directory!
```

**Comment by javsalgar** [comment]
Could you add more details on the platform you are using to run docker?

**Comment by dungsil** [comment]
- OS:  Ubuntu 22.04 LTS (GNU/Linux 5.15.0-43-generic x86_64)
- Docker engine version: 20.10.17, build 100c701
- Docker compomse version: v2.6.1

Would this be enough? Let me know if you need anything more.

**Comment by dungsil** [comment]
Hello @javsalgar , 

I'm getting (probably) the same error on windows.


**docker-compose.yml**
```yml
version: "3.8"
volumes:
  app_pgdata:
services:
  postgresql:
    image: bitnami/postgresql:14
    ports:
      - "5432:5432"
    volumes:
      - "app_pgdata:/bitnami/postgresql"
```

**Log**
```
Starting docker_postgresql_1 ... done
Attaching to docker_postgresql_1
postgresql_1  | postgresql 12:51:02.61 
postgresql_1  | postgresql 12:51:02.61 Welcome to the Bitnami postgresql container
postgresql_1  | postgresql 12:51:02.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql_1  | postgresql 12:51:02.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql_1  | postgresql 12:51:02.61
postgresql_1  | postgresql 12:51:02.63 INFO  ==> ** Starting PostgreSQL setup **
postgresql_1  | postgresql 12:51:02.66 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql_1  | postgresql 12:51:02.67 INFO  ==> Loading custom pre-init scripts...
postgresql_1  | postgresql 12:51:02.67 INFO  ==> Initializing PostgreSQL database...
postgresql_1  | chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql_1  | postgresql 12:51:02.69 WARN  ==> Lack of permissions on data directory!
postgresql_1  | chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql_1  | postgresql 12:51:02.69 WARN  ==> Lack of permissions on data directory!
postgresql_1  | postgresql 12:51:02.69 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql_1  | postgresql 12:51:02.69 INFO  ==> Generating local authentication configuration
```

 - OS: Microsoft Windows 11 Pro (21H2, Build 22000.856)
 - Docker: v20.10.17 (build 100c701)
 - Docker compose: v1.29.2 (build 5becea4c)
