### ISSUE TITLE
[Kafka] Cannot turn on SASL when using KRAFT mode.

### ISSUE THREAD

**Issue by jiak94** [bitnami/containers#15543]
### Name and Version

bitnami/kafka:3.3.1

### What steps will reproduce the bug?

start the container when this configuration

```yaml
kafka:
    network_mode: host
    image: bitnami/kafka:3.3.1
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092,CONTROLLER://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://localhost:9092
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=no
    - KAFKA_KRAFT_CLUSTER_ID=V5t6x-LERXi-eUBdy_vacg
    - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M
    
    # Authentication Config
    - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-512
    - kFAKF_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512
    - KAFKA_CLIENT_USERS=autobootstrap
    - KAFKA_CLIENT_PASSWORDS=autobootstrap
```

### What is the expected behavior?

The docker container can start normally

### What do you see instead?
The container trying to create users in Zookeeper during initialization process, but `KRAFT` mode does not have Zookeeper
![image](https://user-images.githubusercontent.com/4082168/204937421-a5e52b30-96f8-4c64-b91f-fe24e85c9164.png)

**Comment by dimaqq** [comment]
Dunno if this helps: https://www.reddit.com/r/apachekafka/comments/z4nak8/kafka_kraft_sasl_plaintext/

**Comment by carrodher** [comment]
Could you provide the whole `docker-compose.yaml` you are using? Apart from that, could you please take a look at this [README section](https://github.com/bitnami/containers/tree/main/bitnami/kafka#kafka-without-zookeeper-kraft)? Just in case some configuration is missing

**Comment by jiak94** [comment]
@carrodher I have updated the description. My script works if I substitute `SASL_PLAINTEXT` with `PLAINTEXT` and set `ALLOW_PLAINTEXT_LISTENER` to `yes`. 

I can also share with you what I have found. `kafka_initialize` was called during the setup process. https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.3/debian-11/rootfs/opt/bitnami/scripts/kafka/setup.sh#L45

In the `kafka_initialize` function, `kafka_create_sasl_scram_zookeeper_users` was called and never checked if the container is using `KRAFT` mode. https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.3/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L865

I hope my found could help.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by piccit** [comment]
I thought there was currently no support in Kraft mode to create SCRAM users? https://kafka.apache.org/documentation/#kraft_missing

So I think the setup scripts trying to use ZK to configure for SCRAM _should_ be expected based on your `kFAKF_CFG_SASL_ENABLED_MECHANISMS`

**Comment by piccit** [comment]
FWIW, this seems configuration to be working for me. If it's true that SCRAM can't be used w/out ZK (per my previous comment), then I think the only thing that would need to be updated is the documentation
```
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:9094"
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,CLIENT://:9092,CONTROLLER://:9094,EXTERNAL://:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,CLIENT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
```
