### ISSUE TITLE
[bitnami/discourse] no download tool found (curl or wget required) on Bootstrapping

### ISSUE THREAD

**Issue by SebastianGode** [bitnami/containers#15988]
### Name and Version

bitnami/discourse

### What steps will reproduce the bug?

With the default docker-compose file from https://raw.githubusercontent.com/bitnami/containers/main/bitnami/discourse/docker-compose.yml it's not possible to start up the container correctly as Discourse is unsable to render pages.

Here's the log:
```
discourse_1   | discourse 12:35:50.95 INFO  ==> ** Starting Discourse **
discourse_1   |  [passenger_native_support.so] trying to compile for the current user (root) and Ruby interpreter...
discourse_1   |      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   |      Warning: compilation didn't succeed. To learn why, read this file:
discourse_1   |      /tmp/passenger_native_support-1s2wvfz.log
discourse_1   |  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
discourse_1   |      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   |      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.15/rubyext-ruby-2.7.7-x86_64-linux.tar.gz: no download tool found (curl or wget required)
discourse_1   |      Trying next mirror...
discourse_1   |      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.15/rubyext-ruby-2.7.7-x86_64-linux.tar.gz: no download tool found (curl or wget required)
discourse_1   |      Trying next mirror...
discourse_1   |      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.15/rubyext-ruby-2.7.7-x86_64-linux.tar.gz: no download tool found (curl or wget required)
discourse_1   |  [passenger_native_support.so] will not be used (can't compile or download)
discourse_1   |   --> Passenger will still operate normally.
discourse_1   | =============== Phusion Passenger(R) Standalone web server started ===============
discourse_1   | PID file: /opt/bitnami/discourse/passenger.3000.pid
discourse_1   | Log file: /opt/bitnami/discourse/log/passenger.3000.log
discourse_1   | Environment: production
discourse_1   | Accessible via: http://0.0.0.0:3000/
discourse_1   |
discourse_1   | You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
discourse_1   | Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
discourse_1   | ===============================================================================
discourse_1   | App 511 output:  [passenger_native_support.so] trying to compile for the current user (discourse) and Ruby interpreter...
discourse_1   | App 511 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   | App 511 output:      Warning: compilation didn't succeed. To learn why, read this file:
discourse_1   | App 511 output:      /tmp/passenger_native_support-4ap8le.log
discourse_1   | App 511 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
discourse_1   | App 511 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
discourse_1   | App 511 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.15/rubyext-ruby-2.7.7-x86_64-linux.tar.gz: no download tool found (curl or wget required)
discourse_1   | App 511 output:      Trying next mirror...
discourse_1   | App 511 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.15/rubyext-ruby-2.7.7-x86_64-linux.tar.gz: no download tool found (curl or wget required)
discourse_1   | App 511 output:      Trying next mirror...
discourse_1   | App 511 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.15/rubyext-ruby-2.7.7-x86_64-linux.tar.gz: no download tool found (curl or wget required)
discourse_1   | App 511 output:  [passenger_native_support.so] will not be used (can't compile or download)
discourse_1   | App 511 output:   --> Passenger will still operate normally.
```

### What do you see instead?

Using the container with the default docker-compose is not possible.

**Comment by javsalgar** [comment]
Hi,

Do you mean that, when accessing the Discourse page, nothing is shown?

**Comment by SebastianGode** [comment]
Hey,

Exactly, nothing is shown on the discourse page.
Once you load it the discourse container throws the error that it can't render the page.

**Comment by Mauraza** [comment]
Hi @SebastianGode,

Did you change `DISCOURSE_HOST=www.example.com`? Did you use this host to test?

**Comment by SebastianGode** [comment]
Hey @Mauraza 
I did change the host, but even with my own domain it still didn't work for me.

**Comment by Mauraza** [comment]
Hi @SebastianGode,

Could you try the following docker-compose.yaml?

```yml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    image: docker.io/bitnami/discourse:2.8.13
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=127.0.0.1
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0
      - PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0
  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

```

**Comment by ducnm-git** [comment]
> Hi @SebastianGode,
> 
> Could you try the following docker-compose.yaml?

I have the same issue, I replaced image tag, use `discourse:2.8.13` and it works, `discourse:2` don't.

```
<     image: docker.io/bitnami/discourse:2.8.13
---
>     image: docker.io/bitnami/discourse:2
```

**Comment by Mauraza** [comment]
Hi @ducnm-git,

I tried this docker-compose.yml 🔽  and every thing works fine, did you have something different?
```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    image: docker.io/bitnami/discourse:2
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=127.0.0.1
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0
      - PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0
  sidekiq:
    image: docker.io/bitnami/discourse:2
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=127.0.0.1
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

```
I would like to find out where is the error. Thanks!

**Comment by ducnm-git** [comment]
Hi [Mauraza](https://github.com/Mauraza), your docker-compose file works fine, without errors.

From https://github.com/bitnami/containers/tree/main/bitnami/discourse, README file may need to update or add more instructions.
>       - DISCOURSE_HOST=127.0.0.1
>       - PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0
>       - PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0

**Comment by Mauraza** [comment]
Hi @ducnm-git,

Meanwhile, we have a workaround for discourse works.

**Comment by kuznetsov-as** [comment]
Hi @Mauraza

I am trying to use your docker-compose.yml but as of today it is not working.

I tried using this docker-compose.yml: https://github.com/bitnami/containers/blob/main/bitnami/discourse/docker-compose.yml but it gives me an error no download tool found (curl or wget required)

At the moment I have this docker-compose.yml:

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=127.0.0.1
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0
      - PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0
  sidekiq:
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=127.0.0.1
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local

```

And there are no errors, the containers are raised, however, when accessing the Discourse page, only the loading animation (colored dots) is displayed

The developer tools in my browser show the following
![изображение](https://user-images.githubusercontent.com/59287316/225260279-a0dade21-0126-4a67-8501-72522e020a4c.png)

I've been struggling with this for a few days now and would appreciate any help
