### ISSUE TITLE
[bitnami/mysql] Support mysql `lower-case-table-names` and `default-time-zone` env vars

### ISSUE THREAD

**Issue by icefery** [bitnami/containers#16211]
### Name and Version

bitnami/mysql:8.0.31-debian-11-r15

### What is the problem this feature will solve?

official mysql image supports command-line options:

```yaml
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command:
      - --lower-case-table-names=1
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-time-zone=+8:00
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  default:
    external: true
    name: compose
volumes:
  mysql-data:
```

> `lower_case_table_names` can only be configured when initializing the server. Changing the `lower_case_table_names` setting after the server is initialized is prohibited.

### What is the feature you are proposing to solve the problem?

```bash
docker run                           \
  --name mysql                       \
  -e MYSQL_ROOT_PASSWORD=password123 \
  -e LOWER_CASE_TABLE_NAMES=1        \
  -e DEFAULT_TIME_ZONE="+8:00"       \
  bitnami/mysql:latest
```

### What alternatives have you considered?

mount `my.cnf`, but in this way we need to provider a file for docker or ConfigMap for helm chart, and it should be compatible with bitnami itself.

**Comment by javsalgar** [comment]
Hi,

Did you try setting the `MYSQL_EXTRA_FLAGS` variable? https://github.com/bitnami/containers/blob/main/bitnami/mysql/8.0/debian-11/rootfs/opt/bitnami/scripts/libmysql.sh#L25

**Comment by icefery** [comment]
> Hi,
>
> Did you try setting the `MYSQL_EXTRA_FLAGS` variable? https://github.com/bitnami/containers/blob/main/bitnami/mysql/8.0/debian-11/rootfs/opt/bitnami/scripts/libmysql.sh#L25

I have tried, but there are still some problems.

The following succeeded:

```yaml
environment:
  MYSQL_EXTRA_FLAGS: '--default-authentication-plugin=mysql_native_password --default-time-zone=+8:00'
```

But the following would fail and stop logging:

```yaml
environment:
  MYSQL_EXTRA_FLAGS: '--lower-case-table-names=1 --default-authentication-plugin=mysql_native_password --default-time-zone=+8:00'
```

```
Attaching to mysql
mysql  | mysql 17:36:17.86
mysql  | mysql 17:36:17.86 Welcome to the Bitnami mysql container
mysql  | mysql 17:36:17.86 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql  | mysql 17:36:17.86 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql  | mysql 17:36:17.87
mysql  | mysql 17:36:17.87 INFO  ==> ** Starting MySQL setup **
mysql  | mysql 17:36:17.89 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql  | mysql 17:36:17.90 INFO  ==> Initializing mysql database
mysql  | mysql 17:36:17.91 INFO  ==> Updating 'my.cnf' with custom configuration
mysql  | mysql 17:36:17.92 INFO  ==> Setting slow_query_log option
mysql  | mysql 17:36:17.92 INFO  ==> Setting long_query_time option
mysql  | mysql 17:36:17.93 INFO  ==> Installing database
mysql  | mysql 17:36:21.05 INFO  ==> Starting mysql in background
```

Because `lower_case_table_names` can only be configured when initializing the server, I guess it has not been added to the `${DB_BIN_DIR}/mysqld --initialize-insecure` args, but has been added to the start args, the code may be located at

- https://github.com/bitnami/containers/blob/main/bitnami/mysql/8.0/debian-11/rootfs/opt/bitnami/scripts/libmysql.sh#L725
- https://github.com/bitnami/containers/blob/main/bitnami/mysql/8.0/debian-11/rootfs/opt/bitnami/scripts/libmysql.sh#L415

**Comment by javsalgar** [comment]
Hi,

Could you launch the container with BITNAMI_DEBUG=true?

**Comment by icefery** [comment]
> Hi,
> 
> Could you launch the container with BITNAMI_DEBUG=true?

```yaml
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - 3306:3306
    environment:
      BITNAMI_DEBUG: true
      MYSQL_EXTRA_FLAGS: '--lower-case-table-names=1'
      MYSQL_ROOT_PASSWORD: root
```

![image](https://user-images.githubusercontent.com/61737634/223691066-4a294807-5833-469f-bc00-37934789b542.png)
