### ISSUE TITLE
[bitnami/moodle] Moodle Build Address already in use

### ISSUE THREAD

**Issue by lukasdietz** [bitnami/containers#16242]
### Name and Version

bitnami/moodle:4

### What steps will reproduce the bug?

Trying to build a moodle with EXTRA_LOCALES on a docker host with multiple other containers deployed already.
Cloned the repository and edit docker-compose.yml according to documentation to include extra locales (just copied this part over).

The relevant part looks like so:
```
 moodle:
    #image: docker.io/bitnami/moodle:4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA_LOCALES=fr_FR.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, it_IT.UTF-8 UTF-8, es_ES.UTF-8 UTF-8
```
Then tried to start with `docker-compose up -d`

### What is the expected behavior?

Expected to build a fresh container with extra locales. 

### What do you see instead?

Everything seems fine to Step 11/29. But on Step 12/29 it is failing with the Message "Address already in use". 
```
Step 12/29 : RUN chmod g+rwX /opt/bitnami
 ---> Running in 5507788f4c51
Address already in use
ERROR: Service 'moodle' failed to build
```

I am aware that it is likely to conflict with one of my other containers. But how do I get the conflicting port or even change it.
