### ISSUE TITLE
Don't run on macs with m1 chip (arm)

### ISSUE THREAD

**Issue by fuson** [bitnami/containers#16263]
### Name and Version

binami/jasperserver

### What steps will reproduce the bug?

start like README.md on mac with m1 chip

### What do you see instead?

2022-12-09 22:02:13 jasperreports 19:02:13.65 
2022-12-09 22:02:13 jasperreports 19:02:13.68 Welcome to the Bitnami jasperreports container
2022-12-09 22:02:13 jasperreports 19:02:13.70 Subscribe to project updates by watching https://github.com/bitnami/containers
2022-12-09 22:02:13 jasperreports 19:02:13.72 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2022-12-09 22:02:13 jasperreports 19:02:13.74 
2022-12-09 22:02:13 jasperreports 19:02:13.84 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
2022-12-09 22:02:13 jasperreports 19:02:13.94 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
2022-12-09 22:02:14 jasperreports 19:02:14.20 INFO  ==> Configuring port numbers
2022-12-09 22:02:14 jasperreports 19:02:14.35 INFO  ==> Ensuring Tomcat directories exist
2022-12-09 22:02:14 jasperreports 19:02:14.40 INFO  ==> Deploying Tomcat from scratch
2022-12-09 22:02:14 jasperreports 19:02:14.73 INFO  ==> Ensuring JasperReports directories exist
2022-12-09 22:02:14 jasperreports 19:02:14.79 INFO  ==> Trying to connect to the database server
2022-12-09 22:02:14 jasperreports 19:02:14.90 INFO  ==> Configuring JasperReports with settings provided via environment variables
2022-12-09 22:02:15 jasperreports 19:02:15.64 INFO  ==> Executing installation scripts
2022-12-09 22:04:09 jasperreports 19:04:09.65 INFO  ==> Executing deployment scripts

**Comment by BjornTheProgrammer** [comment]
I've gotten it to work just fine on my M1 using `docker.io/bitnami/wordpress-nginx:6` although I was having trouble utilizing it initially, I figured out that it was due to my MariaDB environment variables being inputted wrong. I would just double-check that your environment variables are as you expect for both MariaDB and Wordpress-Nginx, using the new inspect tab on the latest version of docker (forgive me if has always been there, I only just discovered it after updating). 

Here is a minimum viable docker-compose that should work (haven't tried it yet just based on mine)
```
version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_PASSWORD=12345678901234
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=jkladjflakjdsflakjdsflkjsadfl

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6
    container_name: wordpress
    ports:
      - '8080:8080'
    volumes:
      - 'wordpress:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_PASSWORD=12345678901234

volumes:
  mariadb:
  wordpress:
```
