### ISSUE TITLE
[bitnami/moodle] Can't get blocking direct ip access through HTTPS to work through Apache vhosts

### ISSUE THREAD

**Issue by alphadijkstra** [bitnami/containers#16663]
### Name and Version

bitnami/moodle

### What steps will reproduce the bug?

I want my moodle instance to block direct access to its ip address.
The only allowed address should be the domain name.

I managed to block direct access to the HTTP IP address but cannot get it to work for HTTPS.

My docker-compose.yml file:
```yaml
version: '3'
services:
  mariadb:
    restart: always
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - DOCKER_CONTENT_TRUST=1
      - BITNAMI_DEBUG=true
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=the_password
      - MARIADB_PASSWORD=another_password
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8
      - MARIADB_COLLATE=utf8_general_ci
    volumes:
      - '/home/a_user/mariadb:/bitnami/mariadb'
  moodle:
    restart: always
    image: docker.io/bitnami/moodle:latest
    healthcheck:
      test: [ "ping", "-c", "1", "-w", "mariadb"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DOCKER_CONTENT_TRUST=1
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=another_password
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_SKIP_BOOTSTRAP=yes
      - MOODLE_SKIP_INSTALL=yes
      - PHP_MAX_INPUT_VARS=7000
    volumes:
      - '/home/a_user/moodle:/bitnami/moodle'
      - '/home/a_user/moodledata:/bitnami/moodledata'
      - '/home/a_user/certificates:/certs'
      - '/home/a_user/apache/vhosts/bitnami.conf:/vhosts/bitnami.conf:ro'
    depends_on:
      - mariadb
```

My bitnami.conf file:
```
# Default Virtual Host configuration.

# Let apache know we're behind a SSL reverse proxy
SetEnvIf X-Forwarded-Proto https HTTPS=on

ServerSignature Off
ServerTokens Prod

<IfModule mod_headers.c>
 Header unset Server
 Header always unset X-Powered-By
 Header unset X-Powered-By
 Header unset X-CF-Powered-By
 Header unset X-Mod-Pagespeed
 Header unset X-Pingback
</IfModule>

<VirtualHost *:8080>
  ServerName IP_ADDRESS
  Redirect 403 / 
  ErrorDocument 403 "Please access our site via https://domainname"
  DocumentRoot /opt/bitnami/moodle
  UseCanonicalName Off
</VirtualHost>

<VirtualHost *:8080>
  ServerAlias domainname.com
  ServerName domainname.com
  DocumentRoot /opt/bitnami/moodle
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  <Directory "/opt/bitnami/moodle">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html

</VirtualHost>
```

### What is the expected behavior?

I expect the HTTPS://ip-address site to also redirect or show a message reading "no direct access allowed"

### What do you see instead?

The HTTPS://ip-address site just returns the normal HTTPS://domainname site.
However, looking at HTTP://ip-address does show the intended message instead of the site.

### Additional information

I tried many different ways to set up the virtualhost files but (due to lack of understanding) have not been able to get past certificate errors that pop-up for some reasons.
