### ISSUE TITLE
[bitnami/minio] defaultBuckets setting results in error while starting

### ISSUE THREAD

**Issue by yywing** [bitnami/containers#16846]
### Name and Version

bitnami/minio: 2022.12.2-debian-11-r0

### What steps will reproduce the bug?

minio DISTRIBUTED not work well with MINIO_DEFAULT_BUCKETS.

```yaml
version: '2'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket
  minio2:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_2_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket
  minio3:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_3_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket
  minio4:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_4_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
      - MINIO_DEFAULT_BUCKETS=my-first-bucket:private,my-second-bucket

volumes:
  minio_data:
    driver: local
  minio_2_data:
    driver: local
  minio_3_data:
    driver: local
  minio_4_data:
    driver: local
```

### What is the expected behavior?

create default buckets and start up.

### What do you see instead?

The first node setup done, will exit all node，so other node setup fail, container exit.

```
minio-minio4-1  |  09:25:34.56
minio-minio4-1  |  09:25:34.56 Welcome to the Bitnami minio container
minio-minio4-1  |  09:25:34.56 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio4-1  |  09:25:34.56 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio4-1  |  09:25:34.56
minio-minio4-1  |  09:25:34.56 INFO  ==> ** Starting MinIO setup **
minio-minio4-1  | minio 09:25:34.57 DEBUG ==> Validating settings in MINIO_* env vars..
minio-minio4-1  | minio 09:25:34.58 INFO  ==> Starting MinIO in background...
minio-minio2-1  |  09:25:34.89
minio-minio2-1  |  09:25:34.89 Welcome to the Bitnami minio container
minio-minio2-1  |  09:25:34.89 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio2-1  |  09:25:34.89 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio2-1  |  09:25:34.89
minio-minio2-1  |  09:25:34.89 INFO  ==> ** Starting MinIO setup **
minio-minio2-1  | minio 09:25:34.90 DEBUG ==> Validating settings in MINIO_* env vars..
minio-minio2-1  | minio 09:25:34.91 INFO  ==> Starting MinIO in background...
minio-minio3-1  |  09:25:35.04
minio-minio3-1  |  09:25:35.04 Welcome to the Bitnami minio container
minio-minio3-1  |  09:25:35.04 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio3-1  |  09:25:35.04 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio3-1  |  09:25:35.04
minio-minio-1   |  09:25:35.04
minio-minio3-1  |  09:25:35.04 INFO  ==> ** Starting MinIO setup **
minio-minio-1   |  09:25:35.04 Welcome to the Bitnami minio container
minio-minio-1   |  09:25:35.04 Subscribe to project updates by watching https://github.com/bitnami/containers
minio-minio-1   |  09:25:35.04 Submit issues and feature requests at https://github.com/bitnami/containers/issues
minio-minio-1   |  09:25:35.04
minio-minio-1   |  09:25:35.04 INFO  ==> ** Starting MinIO setup **
minio-minio3-1  | minio 09:25:35.04 DEBUG ==> Validating settings in MINIO_* env vars..
minio-minio-1   | minio 09:25:35.05 DEBUG ==> Validating settings in MINIO_* env vars..
minio-minio3-1  | minio 09:25:35.05 INFO  ==> Starting MinIO in background...
minio-minio-1   | minio 09:25:35.06 INFO  ==> Starting MinIO in background...
minio-minio2-1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
minio-minio2-1  | Automatically configured API requests per node based on available memory on the system: 779
minio-minio2-1  | All MinIO sub-systems initialized successfully in 56.310353ms
minio-minio4-1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
minio-minio2-1  | MinIO Object Storage Server
minio-minio2-1  | Copyright: 2015-2022 MinIO, Inc.
minio-minio2-1  | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-minio2-1  | Version: DEVELOPMENT.2022-12-12T19-27-27Z (go1.18.9 linux/amd64)
minio-minio2-1  |
minio-minio2-1  | Status:         4 Online, 0 Offline.
minio-minio2-1  | API: http://localhost:9000
minio-minio2-1  | Console: http://172.21.0.4:9001 http://127.0.0.1:9001
minio-minio2-1  |
minio-minio2-1  | Documentation: https://min.io/docs/minio/linux/index.html
minio-minio4-1  | Automatically configured API requests per node based on available memory on the system: 778
minio-minio4-1  | All MinIO sub-systems initialized successfully in 21.193992ms
minio-minio-1   | Waiting for all MinIO sub-systems to be initialized.. lock acquired
minio-minio-1   | Automatically configured API requests per node based on available memory on the system: 778
minio-minio-1   | All MinIO sub-systems initialized successfully in 55.215153ms
minio-minio3-1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
minio-minio4-1  | MinIO Object Storage Server
minio-minio4-1  | Copyright: 2015-2022 MinIO, Inc.
minio-minio4-1  | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-minio4-1  | Version: DEVELOPMENT.2022-12-12T19-27-27Z (go1.18.9 linux/amd64)
minio-minio4-1  |
minio-minio4-1  | Status:         4 Online, 0 Offline.
minio-minio4-1  | API: http://localhost:9000
minio-minio4-1  | Console: http://172.21.0.2:9001 http://127.0.0.1:9001
minio-minio4-1  |
minio-minio4-1  | Documentation: https://min.io/docs/minio/linux/index.html
minio-minio-1   | MinIO Object Storage Server
minio-minio-1   | Copyright: 2015-2022 MinIO, Inc.
minio-minio-1   | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-minio-1   | Version: DEVELOPMENT.2022-12-12T19-27-27Z (go1.18.9 linux/amd64)
minio-minio-1   |
minio-minio-1   | Status:         4 Online, 0 Offline.
minio-minio-1   | API: http://localhost:9000
minio-minio-1   | Console: http://172.21.0.5:9001 http://127.0.0.1:9001
minio-minio-1   |
minio-minio-1   | Documentation: https://min.io/docs/minio/linux/index.html
minio-minio3-1  | Automatically configured API requests per node based on available memory on the system: 777
minio-minio3-1  | All MinIO sub-systems initialized successfully in 129.749941ms
minio-minio3-1  | MinIO Object Storage Server
minio-minio3-1  | Copyright: 2015-2022 MinIO, Inc.
minio-minio3-1  | License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
minio-minio3-1  | Version: DEVELOPMENT.2022-12-12T19-27-27Z (go1.18.9 linux/amd64)
minio-minio3-1  |
minio-minio3-1  | Status:         4 Online, 0 Offline.
minio-minio3-1  | API: http://localhost:9000
minio-minio3-1  | Console: http://172.21.0.3:9001 http://127.0.0.1:9001
minio-minio3-1  |
minio-minio3-1  | Documentation: https://min.io/docs/minio/linux/index.html
minio-minio4-1  | minio 09:25:39.59 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio2-1  | minio 09:25:39.92 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio3-1  | minio 09:25:40.06 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio-1   | minio 09:25:40.07 INFO  ==> Adding local Minio host to 'mc' configuration...
minio-minio4-1  | minio 09:25:44.62 INFO  ==> Creating default buckets...
minio-minio4-1  | minio 09:25:44.66 INFO  ==> Bucket local/my-first-bucket already exists, skipping creation.
minio-minio4-1  | minio 09:25:44.69 INFO  ==> Bucket local/my-second-bucket already exists, skipping creation.
minio-minio4-1  | minio 09:25:44.73 INFO  ==> Stopping MinIO...
minio-minio3-1  | Stopping on service signal
minio-minio2-1  | Stopping on service signal
minio-minio-1   | Stopping on service signal
minio-minio4-1  | Stopping on service signal
minio-minio2-1  | minio 09:25:44.95 INFO  ==> Creating default buckets...
minio-minio3-1  | minio 09:25:45.10 INFO  ==> Creating default buckets...
minio-minio-1   | minio 09:25:45.10 INFO  ==> Creating default buckets...
minio-minio4-1  |
minio-minio4-1  |  09:25:45.80 INFO  ==> ** MinIO setup finished! **
minio-minio4-1  | minio 09:25:45.80 INFO  ==> ** Starting MinIO **
minio-minio4-1  | Waiting for atleast 1 remote servers with valid configuration to be online
minio-minio4-1  | Following servers are currently offline or unreachable [http://minio:9000/data is unreachable: Post "http://minio:9000/minio/bootstrap/v1/verify": dial tcp 172.21.0.5:9000: connect: connection refused http://minio2:9000/data is unreachable: Post "http://minio2:9000/minio/bootstrap/v1/verify": dial tcp 172.21.0.4:9000: connect: connection refused http://minio3:9000/data is unreachable: Post "http://minio3:9000/minio/bootstrap/v1/verify": dial tcp 172.21.0.3:9000: connect: connection refused]
minio-minio2-1  | mc: <ERROR> Unable to make bucket `local/my-first-bucket`. Put "http://localhost:9000/my-first-bucket/": dial tcp 127.0.0.1:9000: connect: connection refused
minio-minio2-1  | minio 09:25:48.93 INFO  ==> MinIO is already stopped...
minio-minio2-1 exited with code 1
minio-minio3-1  | mc: <ERROR> Unable to make bucket `local/my-first-bucket`. Put "http://localhost:9000/my-first-bucket/": dial tcp 127.0.0.1:9000: connect: connection refused
minio-minio3-1  | minio 09:25:49.71 INFO  ==> MinIO is already stopped...
minio-minio3-1 exited with code 1
minio-minio-1   | mc: <ERROR> Unable to make bucket `local/my-first-bucket`. Put "http://localhost:9000/my-first-bucket/": dial tcp 127.0.0.1:9000: connect: connection refused
minio-minio-1   | minio 09:25:50.47 INFO  ==> MinIO is already stopped...
minio-minio-1 exited with code 1
```
