### ISSUE TITLE
[bitnami/mastodon] I can not see the images in a post

### ISSUE THREAD

**Issue by tunopendientes** [bitnami/containers#17565]
### Name and Version

last

### What steps will reproduce the bug?

When I post with an image, the image is not possible to see it. It just appears like a broken image if I push over the image.

This is my docker-compose

```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    container_name: postgresql
    restart: always
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_mastodon
      - POSTGRESQL_USERNAME=bn_mastodon
      - POSTGRESQL_PASSWORD=xxx
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis
    restart: always
    volumes:
      - 'redis_data:/bitnami/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    container_name: elasticsearch
    restart: always
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    environment:
      - ELASTICSEARCH_ENABLE_SECURITY=true
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=true
      - ELASTICSEARCH_PASSWORD=bitnami123
  mastodon:
    image: docker.io/bitnami/mastodon:4
    container_name: mastodon
    restart: always
    ports:
      - 82:3000
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=web
      - MASTODON_ADMIN_USERNAME=whatever
      - MASTODON_HTTPS_ENABLED=true
      - LOCAL_DOMAIN=www.ccc.com
      - MASTODON_ADMIN_PASSWORD=xxx
      - MASTODON_ADMIN_EMAIL=whatever@gmail.com
      - MASTODON_DATABASE_PASSWORD=xxx
      - MASTODON_ELASTICSEARCH_PASSWORD=bitnami123
  mastodon-streaming:
    image: docker.io/bitnami/mastodon:4
    container_name: mastodon-streaming
    restart: always
    ports:
      - 4000:4000
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=streaming
      - MASTODON_DATABASE_PASSWORD=xxx
      - MASTODON_ELASTICSEARCH_PASSWORD=bitnami123
  mastodon-sidekiq:
    image: docker.io/bitnami/mastodon:4
    container_name: mastodon-sidekiq
    restart: always
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=sidekiq
      - MASTODON_DATABASE_PASSWORD=xxx
      - MASTODON_ELASTICSEARCH_PASSWORD=bitnami123
volumes:
  postgresql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  mastodon_data:
    driver: local
```

I have a docker nginx proxy manager

Thanks

### What do you see instead?

I see no image at all. I tried many times
