### ISSUE TITLE
[bitnami/odoo] Filesystem permission issue with non-root user

### ISSUE THREAD

**Issue by tobru** [bitnami/containers#17806]
### Name and Version

bitnami/odoo:latest

### What steps will reproduce the bug?

Run the Odoo container with a non-root user, e.g.:

```yaml
spec:
[...]
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: odoo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: odoo
        helm.sh/chart: odoo-23.0.3
    spec:
[...]
        securityContext:
          runAsUser: 1001
```

This is produced by the Helm values:

```
podSecurityContext:
  enabled: true
  runAsUser: 1001
containerSecurityContext:
  enabled: true
  runAsUser: 1001
```

Or run it on OpenShift, which injects something like that:

```yaml
[...]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1001160000
[...]
```

### What is the expected behavior?

Data can be properly persisted.

### What do you see instead?

On first start:

```
[...]
2022-12-22 09:03:44,302 50 INFO defaultdb odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2022-12-22 09:03:44,302 50 INFO defaultdb odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections  
odoo 09:03:44.66 INFO  ==> Updating admin user credentials
UPDATE 1
odoo 09:03:44.71 INFO  ==> Persisting Odoo installation
rm: cannot remove '/opt/bitnami/odoo/addons': Permission denied
```

on subsequent starts:

```
odoo 09:04:31.54 
odoo 09:04:31.54 Welcome to the Bitnami odoo container
odoo 09:04:31.54 Subscribe to project updates by watching https://github.com/bitnami/containers
odoo 09:04:31.55 Submit issues and feature requests at https://github.com/bitnami/containers/issues
odoo 09:04:31.55 
odoo 09:04:31.55 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
odoo 09:04:31.58 DEBUG ==> Validating settings in ODOO_* environment variables...
odoo 09:04:31.60 INFO  ==> Restoring persisted Odoo installation
rm: cannot remove '/opt/bitnami/odoo/addons': Permission denied
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/containers/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by fmulero** [comment]
Hi Tobias,

Just to let you know, I reproduced your issue using the following values. I faced some problems because some odoo scripts was trying to retrieve user information and it was failing because the user id 1001 was not in the `/etc/passwd` file:
```yaml
image:
  debug: true
podSecurityContext:
  enabled: true
  runAsUser: 1001
containerSecurityContext:
  enabled: true
  runAsUser: 1001
persistence:
  enabled: true
volumePermissions:
  enabled: true
extraVolumes:
  - name: etc-hack
    emptyDir: {}
extraVolumeMounts:
  - name: etc-hack
    mountPath: /etc/passwd
    subPath: passwd
initContainers:
  - name: fix-user
    image: "bitnami/odoo:16.0.20221115-debian-11-r4"
    securityContext:
      runAsUser: 1001
    command:
      - '/bin/sh'
      - '-c'
      - |
        myuid=$(id -u)
        mygid=$(id -g)
        uidentry=$(getent passwd $myuid)
        cp /etc/passwd /opt/my-etc/passwd
        if [ -z "$uidentry" ] ; then
            if [ -w /opt/my-etc/passwd ] ; then
                echo "$myuid:x:$myuid:$mygid:container uid:${PWD}:/bin/false" >> /opt/my-etc/passwd
                cat /opt/my-etc/passwd
            else
                echo "Container ENTRYPOINT failed to add passwd entry for container UID"
            fi
        fi
    volumeMounts:
    - name: etc-hack
      mountPath: /opt/my-etc
``` 

Note: Thanks to @ebuildy for sharing the [etc-hack](https://gist.github.com/ebuildy/00c67312ec23ad78fbdd08128181eca1)
