### ISSUE TITLE
[bitnami/openldap]: backup strategy

### ISSUE THREAD

**Issue by sixsax** [bitnami/containers#1781]
### Name and Version

bitnami/openldap:2.6

### What is the problem this feature will solve?

any advice about automatic backup strategy using slapcat? 

### What is the feature you are proposing to solve the problem?

None

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by unmacaque** [comment]
Here is how I back up my openldap container:

1. Add an additional backup volume to the openldap container, e.g. at `/backup`
2. Use [ofelia](https://github.com/mcuadros/ofelia) to periodically run slapcat in the openldap container.

Here is an exemplary compose definition of the ofelia container:

```
services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-exec.openldap-backup-config.schedule: "@weekly"
      ofelia.job-exec.openldap-backup-config.container: openldap
      ofelia.job-exec.openldap-backup-config.command: 'sh -c "slapcat -n 0 -F /bitnami/openldap/slapd.d/ | gzip > /backup/config_$$(date -Iseconds).ldif.gz"'
      ofelia.job-exec.openldap-backup-data.schedule: "@weekly"
      ofelia.job-exec.openldap-backup-data.container: openldap
      ofelia.job-exec.openldap-backup-data.command: 'sh -c "slapcat -n 2 -F /bitnami/openldap/slapd.d/ | gzip > /backup/data_$$(date -Iseconds).ldif.gz"'
```

All that remains is to copy the backup archives from the `/backup` directory. For this purpose, I bind the backup volume to an rsyncd container, which is the target of a separate backup script. You may also choose to copy the files directly using `docker cp` if you wish to.
