### ISSUE TITLE
[bitnami/mastodon] localhost used?

### ISSUE THREAD

**Issue by freakyy85** [bitnami/containers#18195]
### Name and Version

bitnami/mastodon

### What steps will reproduce the bug?

docker-compose.yml:
```yaml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_mastodon
      - POSTGRESQL_USERNAME=bn_mastodon
      - POSTGRESQL_PASSWORD=somepass
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - 'redis_data:/bitnami/redis'
    environment:
      - REDIS_PASSWORD=somepass
      - ALLOW_EMPTY_PASSWORD=no
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    environment:
      - ELASTICSEARCH_ENABLE_SECURITY=true
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=true
      - ELASTICSEARCH_PASSWORD=somepass
  mastodon:
    image: docker.io/bitnami/mastodon:4
    ports:
      - 127.0.0.1:8181:3000
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MASTODON_MODE=web
      - MASTODON_DATABASE_PASSWORD=somepass
      - MASTODON_ELASTICSEARCH_PASSWORD=somepass
      - MASTODON_REDIS_PASSWORD=somepass
      - SMTP_SERVER=mail.your-server.de
      - SMTP_LOGIN=mastodon-noreply@bitsnbytes.chat
      - SMTP_PASSWORD=somepass
      - SMTP_ENABLE_STARTTLS=always
  mastodon-streaming:
    image: docker.io/bitnami/mastodon:4
    ports:
      - 4000:4000
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MASTODON_MODE=streaming
      - MASTODON_DATABASE_PASSWORD=somepass
      - MASTODON_ELASTICSEARCH_PASSWORD=somepass
  mastodon-sidekiq:
    image: docker.io/bitnami/mastodon:4
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MASTODON_MODE=sidekiq
      - MASTODON_DATABASE_PASSWORD=somepass
      - MASTODON_ELASTICSEARCH_PASSWORD=somepass
      - MASTODON_REDIS_PASSWORD=somepass
      - SMTP_SERVER=mail.your-server.de
      - SMTP_LOGIN=mastodon-noreply@bitsnbytes.chat
      - SMTP_PASSWORD=somepass
      - SMTP_ENABLE_STARTTLS=always
volumes:
  postgresql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  mastodon_data:
    driver: local
```

### What is the expected behavior?

Not using localhost the mastodon is reachable over mastodon.bitsnbytes.chat. How can I set this as the default address? If I upload for example an image it tries to reach it under 127.0.0.1.
Also, it doesn't send emails.

It would be nice if someone could help with these two problems. :)

Thank you very much! :D

### What do you see instead?

missing pictures, no emails.
