### ISSUE TITLE
rootless mode not working

### ISSUE THREAD

**Issue by nico-pwn** [bitnami/containers#18446]
### Name and Version

bitnami/suitecrm:8

### What steps will reproduce the bug?

1. install docker: https://docs.docker.com/engine/install/
2. create user with ID/GID "1001"
3. login as 1001 user
4. setup rootless mode
5. download suitecrm compose file from docker hub
6. adjust docker-compose setting to use non-root user as stated in changelog 7.11.18-debian-10-r13: 
> The SuiteCRM container now supports the "non-root" user approach, but it still runs as the root user by default. When running as a non-root user, all services will be run under the same user and Cron jobs will be disabled as crond requires to be run as a superuser. To run as a non-root user, change USER root to USER 1001 in the Dockerfile, or use user: 1001 in docker-compose.yml.

### What is the expected behavior?

the suitecrm container starts

### What do you see instead?

the container doesn't start

#### docker compose log output

```
[...]
suitecrm-suitecrm-1  | rm: cannot remove '/opt/bitnami/suitecrm/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest/Arrays/IsArrayContainingInOrder.php': Permission denied
suitecrm-suitecrm-1  | rm: cannot remove '/opt/bitnami/suitecrm/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest/Util.php': Permission denied
suitecrm-suitecrm-1  | rm: cannot remove '/opt/bitnami/suitecrm/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest/MatcherAssert.php': Permission denied
suitecrm-suitecrm-1  | rm: cannot remove '/opt/bitnami/suitecrm/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest/StringDescription.php': Permission denied
suitecrm-suitecrm-1  | rm: cannot remove '/opt/bitnami/suitecrm/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest/NullDescription.php': Permission denied
```

#### docker compose ps
```
NAME                  IMAGE                               COMMAND                  SERVICE             CREATED             STATUS                      PORTS
suitecrm-mariadb-1    docker.io/bitnami/mariadb:10.6      "/opt/bitnami/script…"   mariadb             16 minutes ago      Up 16 minutes               3306/tcp
suitecrm-suitecrm-1   docker.io/bitnami/suitecrm:latest   "/opt/bitnami/script…"   suitecrm            5 minutes ago       Exited (1) 24 seconds ago
```

**Comment by nico-pwn** [comment]
### docker-compose.yml 
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_PASSWORD=bitnami123
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: docker.io/bitnami/suitecrm:latest
    ports:
      - '80:8080'
      - '443:8443'
    user: "1001:1001"
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami123
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```
