### ISSUE TITLE
[bitmani/cassandra] startup fails with permission issues

### ISSUE THREAD

**Issue by nlescure-pictet** [bitnami/containers#19069]
### Name and Version

bitmain/cassandra:4.0.7

### What steps will reproduce the bug?

Here is my docker-compose:

```yaml
version: '2'
services:
  cassandra:
    image: bitnami/cassandra:4.0.7
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USER=root
      - CASSANDRA_PASSWORD=password
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_CLUSTER_NAME=myCluster
      - CASSANDRA_HOST=cassandra
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=200M
    restart: always
    volumes:
      - cassandra-data-4:/bitnami

volumes:
  cassandra-data-4:
    driver: local
```

doing a docker logs cassandra shows:
```
cassandra 15:23:40.20 INFO  ==> ** Starting Cassandra setup **
cassandra 15:23:40.20 INFO  ==> Validating settings in CASSANDRA_* env vars..
cassandra 15:23:40.23 INFO  ==> Initializing Cassandra database...
cp: cannot create regular file '/opt/bitnami/cassandra/conf/README.txt': Permission denied
```

### What is the expected behavior?

Container should start

### What do you see instead?

a write permission error
