### ISSUE TITLE
[bitnami/rabbitmq] ls: cannot access '/opt/bitnami/rabbitmq/.rabbitmq/mnesia': Operation not permitted

### ISSUE THREAD

**Issue by victorgawk** [bitnami/containers#20752]
### Name and Version

bitnami/rabbitmq:3.11.6

### What steps will reproduce the bug?

Enterprise Linux Server 7.9
Docker version 1.13.1, build 07f3374/1.13.1
docker-compose version 1.9.0, build 258538

start a rabbitmq container using this docker-compose.yaml:

```yaml
version: '2'

services:

  rabbit:
    image: bitnami/rabbitmq:3.11.6
    container_name: rabbit
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - 'rabbit_data:/bitnami'

volumes:

  rabbit_data:
    driver: local
```

### What is the expected behavior?

the RabbitMQ server should start normally.

### What do you see instead?

the RabbitMQ server could not start and the following logs are displayed:
```
rabbitmq 22:17:10.19
rabbitmq 22:17:10.20 Welcome to the Bitnami rabbitmq container
rabbitmq 22:17:10.20 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 22:17:10.21 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 22:17:10.21
rabbitmq 22:17:10.21 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 22:17:10.23 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 22:17:10.29 INFO  ==> Initializing RabbitMQ...
ls: cannot access '/opt/bitnami/rabbitmq/.rabbitmq/mnesia': Operation not permitted
rabbitmq 22:17:10.39 INFO  ==> Starting RabbitMQ in background...
rabbitmq 22:19:02.34 ERROR ==> Couldn't start RabbitMQ in background.
```
