### ISSUE TITLE
[bitnami/pgbouncer] Allow multiple DB connections

### ISSUE THREAD

**Issue by FStefanni** [bitnami/containers#20874]
### Name and Version

bitnami/pgbouncer:1.18.0

### What is the problem this feature will solve?

A single Postgres instance can have multiple DB's.
PgBouncer supports this in its configuration files ([official doc](https://www.pgbouncer.org/config.html#section-databases)), just by specifying multiple times the connection parameters.

Right now, this image does not seems to support this feature.
This forces to have at least one PGBouncer instance for each DB, which is not convenient.

### What is the feature you are proposing to solve the problem?

Supporting to specify multiple DB's, maybe via env vars.
For the very basic and most common use case, it could be enough to allow to specify a list inside the POSTGRESQL_DATABASE env var, e.g.:

```
POSTGRESQL_DATABASE="mydb1,mydb2,other-my-db"
```

### What alternatives have you considered?

I considered to deploy multiple instances of PgBouncer image, but it is not an optimal solution (it is just a workaround).

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward this to the team but we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding the feature and we will review. Would you like to contribute?

**Comment by FStefanni** [comment]
Hi,

at the moment I am very full, so I cannot contribute, sorry.
Nevertheless, I have given a quick look to the options, and I have found that it is possible to  provide a configuration file, which is fine for the most complex use cases.

In the end, for my case I have set the following line in the config file:

```
[databases]
*=host=10.10.10.10 port=5432
```

So it is enough to support the creation of something like this with the env variables, to support at least this common use case. I have done some tests, and I was not able to generate it via current env vars.

Regards

**Comment by FStefanni** [comment]
Bump!

**Comment by defanator** [comment]
Came across the same issue with this image. Is there any reason to verify environment variables in case when a full configuration is present via e.g. volume mount? It looks really weird:

```
% docker run -v $(pwd)/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini bitnami/pgbouncer
pgbouncer 15:16:30.21
pgbouncer 15:16:30.21 Welcome to the Bitnami pgbouncer container
pgbouncer 15:16:30.21 Subscribe to project updates by watching https://github.com/bitnami/containers
pgbouncer 15:16:30.21 Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgbouncer 15:16:30.22
pgbouncer 15:16:30.23 INFO  ==> ** Starting PgBouncer setup **
pgbouncer 15:16:30.24 INFO  ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 15:16:30.24 ERROR ==> POSTGRESQL_PASSWORD must be set
```

**Comment by emibcn** [comment]
In the meanwhile, I've created this script and mounted in `/docker-entrypoint-initdb.d/`. What it does:
- Add a couple of options not managed (yet) by this great Bitnami image
- Copies the defined line in `[databases]` changing the database `*` with `postgres`:

```bash
#!/bin/bash -e

set -euo pipefail

. /opt/bitnami/scripts/liblog.sh

auth_dbname="postgres"

if [ "${PGBOUNCER_DATABASE}" != '*' ]
then
    debug "No wildcard database. Skipping extra database definition for '${auth_dbname}'"
    exit 0
fi

info "Wildcard database detected. Adding extra database definition for '${auth_dbname}'"

database_value="$(
    ini-file get \
        --section "databases" \
        --key "\*" \
        "${PGBOUNCER_CONF_FILE}"
)"

# Set extra database
ini-file set \
    --ignore-inline-comments \
    --section "databases" \
    --key "${auth_dbname}" \
    --value "${database_value}" \
    "${PGBOUNCER_CONF_FILE}"

# Set `postgres` as the auth database
ini-file set \
    --ignore-inline-comments \
    --section "pgbouncer" \
    --key "auth_dbname" \
    --value "${auth_dbname}" \
    "${PGBOUNCER_CONF_FILE}"

# Get better logging
ini-file set \
    --ignore-inline-comments \
    --section "pgbouncer" \
    --key "application_name_add_host" \
    --value "1" \
    "${PGBOUNCER_CONF_FILE}"
```

**Comment by cvrajeesh** [comment]
Setting `PGBOUNCER_DATABASE` to `*` worked for me

**Comment by gongomgra** [comment]
Just a quick note to let you know we are taking a look into this issue. I'm adding the on-hold tag.

**Comment by gongomgra** [comment]
Hi all,

After some investigation, I have found it is possible to configure multiple backend database connections in pgbouncer by using the combination of some of the environment variables already availables: one or more `PGBOUNCER_DSN_${i}` (where `i` starts in zero, `0`), and the `PGBOUNDER_USERLIST_FILE` to provide the connection credentials from a volume for security reasons. The updated `docker-compose.yaml` file looks like the one below:

```yaml
  pg1:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'pg1_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=bitnami123
      - POSTGRESQL_DATABASE=db1

  pg2:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'pg2_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=bitnami456
      - POSTGRESQL_DATABASE=db2

  pg3:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'pg3_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=bitnami789
      - POSTGRESQL_DATABASE=db3

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    volumes:
      - './userlists.txt:/bitnami/userlists.txt'
    environment:
      - POSTGRESQL_HOST=pg1
      - ALLOW_EMPTY_PASSWORD=yes
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_USERLIST_FILE=/bitnami/userlists.txt
      - PGBOUNCER_DSN_0=pg2=host=pg2 port=5432 dbname=db2
      - PGBOUNCER_DSN_1=pg3=host=pg3 port=5432 dbname=db3
volumes:
  pg1_data:
    driver: local
  pg2_data:
    driver: local
  pg3_data:
    driver: local
```

Notice you need to provide at least one database connection using the default `POSTGRESQL_HOST` variable, as the pgbouncer initialization logic checks connectivity with that database (initialization process will fail otherwise).

```
$ docker exec -it -u root bfde5464661d cat /opt/bitnami/pgbouncer/conf/pgbouncer.ini
[databases]
postgres=host=pg1 port=5432 dbname=postgres
pg2=host=pg2 port=5432 dbname=db2
pg3=host=pg3 port=5432 dbname=db3

[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
unix_socket_dir=/tmp/
unix_socket_mode=0777
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=trust
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
admin_users=postgres
client_tls_sslmode=disable
server_tls_sslmode=disable
stats_period=60
```

In the same way, you can check that the content of your local `userlists.txt` file gets into the pgbouncer auth file `/opt/bitnami/pgbouncer/conf/userlist.txt`. Using the config files above, I was able to connect with the `pg2` server by running the command below (it is the only one running PostgreSQL 15.x in my docker-compose file)

```

$ docker exec -it -u root bfde5464661d psql -p 6432 -U postgres pg2 -c "show server_version;"
 server_version
----------------
 15.4
(1 row)
```

Hope it helps!
