### ISSUE TITLE
[bitnami/mongodb] :stuck forever at Validating settings in MONGODB_* env vars

### ISSUE THREAD

**Issue by pedroresende** [bitnami/containers#21232]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

- Mac M1
- Docker Desktop 4.15.0

### What is the expected behavior?

To work

### What do you see instead?

![image](https://user-images.githubusercontent.com/951377/213868175-4fec7bba-ffc6-4faa-ab3c-a6404bb86b64.png)

### Additional information

docker-compose.yml file
```yaml
version: '3.8'
services:
  database:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_REPLICA_SET_KEY=replicaset
    ports:
      - '27017:27017'
    volumes:
      - ./data:/bitnami/mongodb
```
