### ISSUE TITLE
[bitnami/openldap] OpenLDAP is unable to create admin user on bootstrap

### ISSUE THREAD

**Issue by goldmont** [bitnami/containers#21490]
### Name and Version

bitnami/openldap:latest

### What steps will reproduce the bug?

Hi there,

I'm using the following `docker-compose` with the latest **OpenLDAP** [image](https://hub.docker.com/layers/bitnami/openldap/latest/images/sha256-b7a29cc7f054f91b8b2e7b79fc42b21e62ecccb5086c9ba0ea9cb224c0c5d4ce?context=explore) (b7a29cc7f054):
```yaml
version: "3.8"

services:
  ldap:
    container_name: ldap
    image: bitnami/openldap:latest
    user: '1000'
    restart: unless-stopped
    environment:
      - BITNAMI_DEBUG=true
      - ALLOW_EMPTY_PASSWORD=no
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_ROOT="dc=lab,dc=school"
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
    volumes:
      - ./data:/bitnami/openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    networks:
      - ldap_network

networks:
  ldap_network:
    external: true
```

OpenLDAP is unable to create `admin` user. I've already tried to empty the `data` folder and to recreate the container but it seems a bug.

Furthermore, when I try to login using `admin` user, I get the error `49`:
![image](https://user-images.githubusercontent.com/6855692/213936359-e0145dc6-6fc5-4a0f-9759-7c25e32cfbd1.png)

### What is the expected behavior?

Be able to login with `admin` user.

### What do you see instead?

As you can see in the output below, two errors are logged:
`ldap_modify: Invalid syntax (21)` and then `exited with code 21`

```
ldap  |  19:30:31.15 INFO  ==> ** Starting LDAP setup **
ldap  |  19:30:31.17 INFO  ==> Validating settings in LDAP_* env vars
ldap  |  19:30:31.18 INFO  ==> Initializing OpenLDAP...
ldap  |  19:30:31.18 DEBUG ==> Ensuring expected directories/files exist...
ldap  |  19:30:31.19 INFO  ==> Creating LDAP online configuration
ldap  |  19:30:31.21 INFO  ==> Starting OpenLDAP server in background
ldap  | 63cd8ed7.0ceb2604 0x7fa083339740 @(#) $OpenLDAP: slapd 2.6.3 (Jan 17 2023 16:44:38) $
ldap  | 	@a34c3898a374:/bitnami/blacksmith-sandox/openldap-2.6.3/servers/slapd
ldap  | 63cd8ed7.0dedb3f9 0x7fa083339740 slapd starting
ldap  |  19:30:32.22 INFO  ==> Configure LDAP credentials for admin user
ldap  | SASL/EXTERNAL authentication started
ldap  | 63cd8ed8.0dd1e57a 0x7fa081b97700 conn=1000 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
ldap  | 63cd8ed8.0dd55be9 0x7fa081b97700 conn=1000 op=0 BIND dn="" method=163
ldap  | 63cd8ed8.0dd7655a 0x7fa081b97700 conn=1000 op=0 BIND authcid="gidNumber=0+uidNumber=1000,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1000,cn=peercred,cn=external,cn=auth"
ldap  | 63cd8ed8.0dd7be25 0x7fa081b97700 conn=1000 op=0 BIND dn="gidNumber=0+uidNumber=1000,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
ldap  | SASL username: gidNumber=0+uidNumber=1000,cn=peercred,cn=external,cn=auth
ldap  | SASL SSF: 0
ldap  | 63cd8ed8.0dd96e4d 0x7fa081b97700 conn=1000 op=0 RESULT tag=97 err=0 qtime=0.000031 etime=0.000307 text=
ldap  | 63cd8ed8.0dde3b3f 0x7fa081396700 conn=1000 op=1 MOD dn="olcDatabase={2}mdb,cn=config"
ldap  | 63cd8ed8.0ddfdc7c 0x7fa081396700 conn=1000 op=1 MOD attr=olcSuffix
ldap  | 63cd8ed8.0de18f02 0x7fa081396700 conn=1000 op=1 RESULT tag=103 err=21 qtime=0.000061 etime=0.000301 text=olcSuffix: value #0 invalid per syntax
ldap  | ldap_modify: Invalid syntax (21)
ldap  | 	additional info: olcSuffix: value #0 invalid per syntax
ldap  | 63cd8ed8.0de766da 0x7fa081b97700 conn=1000 op=2 UNBIND
ldap  | 63cd8ed8.0de8b84a 0x7fa081b97700 conn=1000 fd=12 closed
ldap  | modifying entry "olcDatabase={2}mdb,cn=config"
ldap  | 
ldap  | 63cd8ed8.0e2e2777 0x7fa082398700 daemon: shutdown requested and initiated.
ldap  | 63cd8ed8.0e31dcaf 0x7fa082398700 slapd shutdown: waiting for 0 operations/tasks to finish
ldap  | 63cd8ed8.0ecb98d6 0x7fa083339740 slapd stopped.
ldap exited with code 21
ldap  |  19:30:33.76 INFO  ==> Validating settings in LDAP_* env vars
ldap  |  19:30:33.77 INFO  ==> Initializing OpenLDAP...
ldap  |  19:30:33.77 DEBUG ==> Ensuring expected directories/files exist...
ldap  |  19:30:33.78 INFO  ==> Using persisted data
ldap  |  19:30:33.78 INFO  ==> ** LDAP setup finished! **
ldap  | 
ldap  |  19:30:33.80 INFO  ==> ** Starting slapd **
ldap  | 63cd8ed9.30841691 0x7fa585a66740 @(#) $OpenLDAP: slapd 2.6.3 (Jan 17 2023 16:44:38) $
ldap  | 	@a34c3898a374:/bitnami/blacksmith-sandox/openldap-2.6.3/servers/slapd
ldap  | 63cd8ed9.30f1edff 0x7fa585a66740 slapd starting
ldap  | 63cd8fc8.1ca8b8f3 0x7fa57ffff700 conn=1000 fd=12 ACCEPT from IP=192.168.2.220:49502 (IP=0.0.0.0:1389)
ldap  | 63cd8fc8.1caea39a 0x7fa57ffff700 conn=1000 op=0 BIND dn="cn=admin,dc=lab,dc=school" method=128
ldap  | 63cd8fc8.1cb05718 0x7fa57ffff700 conn=1000 op=0 RESULT tag=97 err=49 qtime=0.000013 etime=0.000151 text=
ldap  | 63cd8fc8.1cb9347e 0x7fa57ffff700 conn=1000 fd=12 closed (connection lost)
```
