### ISSUE TITLE
[bitnami/nginx] [emerg] open() "/opt/bitnami/nginx/off" failed (13: Permission denied)

### ISSUE THREAD

**Issue by dethknite** [bitnami/containers#21905]
### Name and Version

bitnami/nginx:1.23.3-debian-11-r18 (latest)

### What steps will reproduce the bug?

Working fine in nginx:1.23.3-debian-11-r17. Container autoupdated and now it crashes on start.

### What is the expected behavior?

nginx:1.23.3-debian-11-r17  (output)
```
nginx 12:12:25.83 
nginx 12:12:25.84 Welcome to the Bitnami nginx container
nginx 12:12:25.84 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx 12:12:25.84 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx 12:12:25.84 
nginx 12:12:25.84 INFO  ==> ** Starting NGINX setup **
nginx 12:12:25.86 INFO  ==> Validating settings in NGINX_* env vars
nginx 12:12:25.93 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 12:12:25.94 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
nginx 12:12:26.00 INFO  ==> ** NGINX setup finished! **
nginx 12:12:26.01 INFO  ==> ** Starting NGINX **
```

### What do you see instead?

nginx:1.23.3-debian-11-r18  (output)
```
nginx 12:04:14.67 Welcome to the Bitnami nginx container
nginx 12:04:14.67 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx 12:04:14.67 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx 12:04:14.67 
nginx 12:04:14.67 INFO  ==> ** Starting NGINX setup **
nginx 12:04:14.69 INFO  ==> Validating settings in NGINX_* env vars
nginx 12:04:14.79 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 12:04:14.79 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
nginx 12:04:14.82 INFO  ==> ** NGINX setup finished! **
nginx 12:04:14.83 INFO  ==> ** Starting NGINX **
2023/01/27 12:04:14 [emerg] 1#1: open() "/opt/bitnami/nginx/off" failed (13: Permission denied)
nginx: [emerg] open() "/opt/bitnami/nginx/off" failed (13: Permission denied)
nginx 12:05:08.40 
nginx 12:05:08.40 Welcome to the Bitnami nginx container
nginx 12:05:08.40 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx 12:05:08.40 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx 12:05:08.40 
nginx 12:05:08.41 INFO  ==> ** Starting NGINX setup **
nginx 12:05:08.42 INFO  ==> Validating settings in NGINX_* env vars
nginx 12:05:08.51 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 12:05:08.51 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
nginx 12:05:08.53 INFO  ==> ** NGINX setup finished! **
```

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose.yml that triggers the issue? We would like to reproduce it in our side.

**Comment by dethknite** [comment]
@javsalgar Looks like there are some other related issues opened in apache. Thanks for looking into it. Here is the basic yml contents.

```
version: '2'

services:
  nginx:
    container_name: web-nginx
    image: bitnami/nginx:latest
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    volumes:
      - ./etc-localtime/localtime:/etc/localtime:ro
      - ./nginx-vhost:/opt/bitnami/nginx/conf/server_blocks:ro
      - ./nginx-logs:/logs
      - ./nginx-cache:/etc/nginx/cache
      - /pathto/app1:/app1
      - /pathto/app2:/app2
      - /pathto/certificates:/certificates:ro
```
