### ISSUE TITLE
bitnami/phpmyadmin - probably ignore ingress settings

### ISSUE THREAD

**Issue by tebaly** [bitnami/containers#22599]
### Name and Version

bitnami/phpmyadmin 10.4.1

### What steps will reproduce the bug?
```
  ingress:
    enabled: false
```

### What is the expected behavior?

My own Ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  annotations:
    ***
spec:
  rules:
    - host: ***
      http:
        paths:
          - backend:
              service:
                name: phpmyadmin
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ***
      secretName: ***
```

## start server ***
	server {
		server_name ***
		
		listen 80  ;
		listen [::]:80  ;
		listen 443  ssl http2 ;
		listen [::]:443  ssl http2 ;
		
		set $proxy_upstream_name "-";
		
		ssl_certificate_by_lua_block {
			certificate.call()
		}
		
		location / {  <<<<------------------------------------------------------------------------------- !!!
			
			set $namespace      "phpmyadmin";
			set $ingress_name   "phpmyadmin-ingress";
			set $service_name   "phpmyadmin";
			set $service_port   "http";
			set $location_path  "/";
			set $global_rate_limit_exceeding n;
			
			rewrite_by_lua_block <...>
			
		}
		
		location / {  <<<<------------------------------------------------------------------------------- !!!
			
			set $namespace      "phpmyadmin";
			set $ingress_name   "phpmyadmin-ingress";
			set $service_name   "phpmyadmin";
			set $service_port   "http";
			set $location_path  "/";
			set $global_rate_limit_exceeding n;
			
			rewrite_by_lua_block <...>
			
		}
		
	}
	## end server ***
