### ISSUE TITLE
[bitnami/moodle] image will not run on other port then 8080

### ISSUE THREAD

**Issue by hugokoopmans** [bitnami/containers#22787]
### Name and Version

bitnami/moodle:4

### What steps will reproduce the bug?

run behind nginx proxy
set docker-compose with port 8081:8080 instead of 8080:8080

### What is the expected behavior?

i expect the moodle container to not be affected by the outside port change and just run normally

### What do you see instead?

502 bad gateway

### Additional information

my usecase is that i want to be able to (temporally) run two Moodle versions on the same host. I am migrating from 3.8 to 4.1. Both servers run normally if I only run one of them. as soon as I run them both (and switch the outside port to something else then 8080 the nginx reports a Bad Gateway. I validated the nginx traffic is actually delivered to the right port.

working docker-compose.yml

```
  version: '3'
  services:
    mariadb:
      image: docker.io/bitnami/mariadb:10.6
      restart: always
      environment:
        #- ALLOW_EMPTY_PASSWORD=no
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_CHARACTER_SET=utf8mb4
        - MARIADB_COLLATE=utf8mb4_unicode_ci
      volumes:
        - '/data/docker/moodle4/mariadb_data:/bitnami/mariadb'
    moodle:
      image: docker.io/bitnami/moodle:4
      restart: always
      environment:
        - MOODLE_DATABASE_HOST=mariadb
        - MOODLE_DATABASE_PORT_NUMBER=3306
        - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
        - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
        - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
        #- ALLOW_EMPTY_PASSWORD=no
        # MOODLE section
        - MOODLE_USERNAME=adminx
        - MOODLE_PASSWORD=${MOODLE_PASSWORD}
        - MOODLE_EMAIL=academy@test.com
        # letsencrypt
        - VIRTUAL_HOST=test.nl
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=test.nl
        - LETSENCRYPT_EMAIL=me@test.com
        #- LETSENCRYPT_TEST='true'
        #- ACME_CA_URI='https://acme-staging.api.letsencrypt.org/directory'
        - MOODLE_SMTP_HOST=smtp.some.com
        - MOODLE_SMTP_PORT=465
        - MOODLE_SMTP_USER=user
        - MOODLE_SMTP_PASSWORD=${SMTP_PASSWORD}
        - MOODLE_SMTP_PROTOCOL=tls
      ports:
        - '8080:8080'
        #- '9443:8443'
        #- '25:25'
        #- '465:465'
        #- '587:587'
      volumes:
        - '/data/docker/moodle4/moodle_data:/bitnami/moodle'
        - '/data/docker/moodle4/moodledata_data:/bitnami/moodledata'
      depends_on:
        - mariadb
```

I need the VIRTUAL_PORT for the acme_compagion to pick up the changed port....

if i change the virtual port to 8081 and de port: - 8081:8080 moodle fails with a 502 bad gateway
