### ISSUE TITLE
Failed authentication with SASL_PLAINTEXT

### ISSUE THREAD

**Issue by rirorinn** [bitnami/containers#23077]
### Name and Version

bitnami/kafka:3.2.0-debian-11-r13

### What steps will reproduce the bug?

1. docker-compose.yml
```
version: "3"

services:
  zookeeper-0:
    image: bitnami/zookeeper:3.8.0-debian-11-r69
    restart: always
    hostname: zookeeper
    ports:
      - 3181:2181
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=admin
      - ZOO_SERVER_PASSWORDS=123456
      - ZOO_CLIENT_USER=admin
      - ZOO_CLIENT_PASSWORD=123456

  kafka-0:
    image: bitnami/kafka:3.2.0-debian-11-r13
    restart: always
    hostname: kafka-0
    ports:
      - 9099:9099
      - 9098:9098
    volumes:
      - /etc/localtime:/etc/localtime
      - ../kafka/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ../kafka/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=10.1.4.104:3181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=admin
      - KAFKA_ZOOKEEPER_PASSWORD=123456
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=72000

      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_LISTENERS=INTERNAL://:9098,CLIENT://:9099
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://{IP}:9098,CLIENT://{IP}:9099
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      - KAFKA_CERTIFICATE_PASSWORD=123456
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=123456
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=123456

    depends_on:
      - zookeeper-0
 ```

2.  enter the container and execute the following command
      -  kafka-configs.sh --bootstrap-server  {IP}:9098 --alter --add-config 'SCRAM-SHA-256=[password=password]' --entity-type users --entity-name user2
      -  kafka-acls.sh --bootstrap-server {IP}:9098 --add  --allow-principal User:user1 --operation Read --topic 'test‘

### What is the expected behavior?

1. user gets created
2. authentication
3. authorization with using acls

### What do you see instead?

1. 
```
 kafka-configs.sh --bootstrap-server  {IP}:9098 --alter --add-config 'SCRAM-SHA-256=[password=password]' --entity-type users --entity-name user1
```
```
Error while executing config command with args '--bootstrap-server {IP}:9098 --alter --add-config SCRAM-SHA-256=[password=password] --entity-type users --entity-name user1'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: alterUserScramCredentials
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
        at kafka.admin.ConfigCommand$.alterUserScramCredentialConfigs(ConfigCommand.scala:465)
        at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:428)
        at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:327)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:98)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: alterUserScramCredentials
```

2.
``` 
kafka-acls.sh --bootstrap-server {IP}:9098 --add  --allow-principal User:user1 --operation Read --topic 'test'
```
```
Adding ACLs for resource `ResourcePattern(resourceType=TOPIC, name=test
;, patternType=LITERAL)`:
        (principal=User:user1, host=*, operation=READ, permissionType=ALLOW)

Error while executing ACL command: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createAcls
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createAcls
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
        at kafka.admin.AclCommand$AdminClientService.$anonfun$addAcls$3(AclCommand.scala:115)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:193)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
        at kafka.admin.AclCommand$AdminClientService.$anonfun$addAcls$1(AclCommand.scala:112)
        at kafka.admin.AclCommand$AdminClientService.addAcls(AclCommand.scala:111)
        at kafka.admin.AclCommand$.main(AclCommand.scala:73)
        at kafka.admin.AclCommand.main(AclCommand.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: createAcls
```

### Additional information

the related log: 
```
Failed authentication with /172.25.0.1 (channelId=172.25.0.3:9098-172.25.0.1:42908-149) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)
```

auto generated JAAS authentication file:
```
I have no name!@kafka-0:/$ cd /opt/bitnami/kafka/config/
I have no name!@kafka-0:/opt/bitnami/kafka/config$ cat kafka_jaas.conf
KafkaClient {
   org.apache.kafka.common.security.plain.ScramLoginModule required
   username="user"
   password="123456";
   };
KafkaServer {
   org.apache.kafka.common.security.scram.ScramLoginModule required
   username="user"
   password="123456";
   };
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="123456";
   };
```

**Comment by javsalgar** [comment]
Hi,

Could you share how you generated the certificates so we can fully reproduce the issue?

**Comment by rirorinn** [comment]
I use [kafka-generate-ssl.sh](https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh) in this website https://github.com/bitnami/containers/tree/main/bitnami/kafka#:~:text=kafka%2Dgenerate%2Dssl.sh

copy this script to the server and execute.

all the passwords are 123456, and most of the other questions are .
```
Country Name (2 letter code) [XX]:.
State or Province Name (full name) []:.
Locality Name (eg, city) [Default City]:.
Organization Name (eg, company) [Default Company Ltd]:.
Organizational Unit Name (eg, section) []:.
Common Name (eg, your name or your server's hostname) []:{IP}
```

```
CN={IP}, OU=., O=., L=., ST=., C=.
```

**Comment by mdhont** [comment]
I've been able to reproduce the issue, thanks for reporting it. I've created a task to investigate it further.

**Comment by fevisera** [comment]
Hi @rirorinn,

After investigating this issue, the error is solved after doing the following.

Create a `config.properties` file with the credentials provided in the `docker-compose.yml`:
```
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="123456";
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
```
**Note:** the `user` and `password` should be replaced by the ones provided in the `docker-compose.yml`.

Add these environment variables to kafka in the `docker-compose.yml` to enable and configure ACL:
```
# Enable ACL
- KAFKA_CFG_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer
# Configure ACL for super user "user"
- KAFKA_CFG_SUPER_USERS=User:user
```

Your `docker-compose.yml` should look like this:
```
version: "3"

services:
  zookeeper-0:
    image: bitnami/zookeeper:latest
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=admin
      - ZOO_SERVER_PASSWORDS=123456
      - ZOO_CLIENT_USER=admin
      - ZOO_CLIENT_PASSWORD=123456

  kafka-0:
    image: bitnami/kafka:latest
    restart: always
    hostname: kafka-0
    ports:
      - 9098:9098
      - 9099:9099
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config.properties:/opt/bitnami/kafka/config/config.properties:ro
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=admin
      - KAFKA_ZOOKEEPER_PASSWORD=123456
      - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=72000

      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_LISTENERS=INTERNAL://:9098,CLIENT://:9099
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0:9098,CLIENT://kafka-0:9099
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      - KAFKA_CERTIFICATE_PASSWORD=123456
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=123456
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=123456

      # Configure ACL
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer
      - KAFKA_CFG_SUPER_USERS=User:user

    depends_on:
      - zookeeper-0
```
**Note:** removed the certificate because SSL is not being used. The SASL_PLAINTEXT authentication does not encrypt. Please, let me know if I get that wrong.

Running the kafka commands now works:
```
I have no name!@kafka-0:/$ kafka-configs.sh --bootstrap-server kafka-0:9098 --alter --add-config 'SCRAM-SHA-256=[password=password]' --entity-type users --entity-name user1 --command-config /opt/bitnami/kafka/config/config.properties
Completed updating config for user user1.
I have no name!@kafka-0:/$ kafka-acls.sh --bootstrap-server kafka-0:9098 --add  --allow-principal User:user1 --operation Read --topic 'test' --command-config /opt/bitnami/kafka/config/config.properties
Adding ACLs for resource `ResourcePattern(resourceType=TOPIC, name=test, patternType=LITERAL)`: 
        (principal=User:user1, host=*, operation=READ, permissionType=ALLOW) 

Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=test, patternType=LITERAL)`: 
        (principal=User:user1, host=*, operation=READ, permissionType=ALLOW) 
```

I'm closing this issue because the Timeout error for the SASL_PLAINTEXT authentication is solved by doing the steps I mentioned above.

Please, let me know if the problem is solved for you too, and if not, feel free to reopen the issue.

Thanks!
