### ISSUE TITLE
[bitnami/sonarqube] 使用docker运行后在市场安装Chinese Pack重启访问网站一直loading

### ISSUE THREAD

**Issue by Lihy6472** [bitnami/containers#23084]
### Name and Version

bitnami/sonarqube:9 && bitnami/postgresql:15

### What steps will reproduce the bug?

* docker-compose.yml：
```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/data/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    ports:
      - '9000:9000'
    volumes:
      - 'sonarqube_data:/data/bitnami/sonarqube'
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
volumes:
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
```

### What do you see instead?

* 访问页面显示：
 
![image](https://user-images.githubusercontent.com/116717391/216945481-0ad11b48-eafe-4e35-9795-cac4dc1d761c.png)

* F12开发者选项提示：

![image](https://user-images.githubusercontent.com/116717391/216946203-7a4ecaaf-bbc5-4936-bb42-f7f8fdd42973.png)

* docker-conpose logs sonarqube提示：

```
Attaching to sonar_sonarqube_1
sonarqube_1   | sonarqube 09:50:07.92 
sonarqube_1   | sonarqube 09:50:07.92 Welcome to the Bitnami sonarqube container
sonarqube_1   | sonarqube 09:50:07.92 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube_1   | sonarqube 09:50:07.92 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube_1   | sonarqube 09:50:07.92 
sonarqube_1   | sonarqube 09:50:07.93 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube_1   | sonarqube 09:50:07.95 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
sonarqube_1   | sonarqube 09:50:07.95 INFO  ==> Creating SonarQube configuration
sonarqube_1   | sonarqube 09:50:07.99 INFO  ==> Trying to connect to the database server
sonarqube_1   | sonarqube 09:50:08.00 INFO  ==> Ensuring SonarQube directories exist
sonarqube_1   | sonarqube 09:50:08.02 INFO  ==> Starting SonarQube in background
sonarqube_1   | sonarqube 09:50:08.55 INFO  ==> Waiting for SonarQube to start...
sonarqube_1   | sonarqube 09:50:32.62 INFO  ==> Configuring user credentials
sonarqube_1   | sonarqube 09:50:32.65 INFO  ==> Stopping SonarQube
sonarqube_1   | sonarqube 09:50:35.71 INFO  ==> Persisting SonarQube installation
sonarqube_1   | sonarqube 09:50:35.90 INFO  ==> ** SonarQube setup finished! **
sonarqube_1   | 
sonarqube_1   | sonarqube 09:50:35.92 INFO  ==> ** Starting SonarQube **
sonarqube_1   | Running SonarQube...
sonarqube_1   | sonarqube 09:55:53.04 
sonarqube_1   | sonarqube 09:55:53.04 Welcome to the Bitnami sonarqube container
sonarqube_1   | sonarqube 09:55:53.04 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube_1   | sonarqube 09:55:53.04 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube_1   | sonarqube 09:55:53.04 
sonarqube_1   | sonarqube 09:55:53.05 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube_1   | sonarqube 09:55:53.07 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
sonarqube_1   | sonarqube 09:55:53.07 INFO  ==> Creating SonarQube configuration
sonarqube_1   | sonarqube 09:55:53.10 INFO  ==> Trying to connect to the database server
sonarqube_1   | sonarqube 09:55:53.12 INFO  ==> Restoring persisted SonarQube installation
sonarqube_1   | sonarqube 09:55:53.14 INFO  ==> ** SonarQube setup finished! **
sonarqube_1   | 
sonarqube_1   | sonarqube 09:55:53.15 INFO  ==> ** Starting SonarQube **
sonarqube_1   | Running SonarQube...
sonarqube_1   | Removed stale pid file: /opt/bitnami/sonarqube/bin/linux-x86-64/../../pids/SonarQube.pid
sonarqube_1   | sonarqube 18:05:58.88 
sonarqube_1   | sonarqube 18:05:58.88 Welcome to the Bitnami sonarqube container
sonarqube_1   | sonarqube 18:05:58.89 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube_1   | sonarqube 18:05:58.89 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube_1   | sonarqube 18:05:58.89 
sonarqube_1   | sonarqube 18:05:58.89 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube_1   | sonarqube 18:05:58.91 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
sonarqube_1   | sonarqube 18:05:58.92 INFO  ==> Creating SonarQube configuration
sonarqube_1   | sonarqube 18:05:58.95 INFO  ==> Trying to connect to the database server
sonarqube_1   | sonarqube 18:05:58.97 INFO  ==> Restoring persisted SonarQube installation
sonarqube_1   | sonarqube 18:05:58.99 INFO  ==> ** SonarQube setup finished! **
sonarqube_1   | 
sonarqube_1   | sonarqube 18:05:59.01 INFO  ==> ** Starting SonarQube **
sonarqube_1   | Running SonarQube...
sonarqube_1   | Removed stale pid file: /opt/bitnami/sonarqube/bin/linux-x86-64/../../pids/SonarQube.pid
```

### Additional information

* 以下为系统版本及docker版本信息
```
root@test1-worker-3:~/sonar# docker-compose -v
docker-compose version 1.23.2, build 1110ad01
root@test1-worker-3:~/sonar# uname -a
Linux test1-worker-3 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@test1-worker-3:~/sonar# uname -a
Linux test1-worker-3 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@test1-worker-3:~/sonar# 
```
