### ISSUE TITLE
[bitnami/keycloak] admin user

### ISSUE THREAD

**Issue by m4rcoschmucki** [bitnami/containers#23144]
### Name and Version

bitnami/keycloak:20.0.3

### What steps will reproduce the bug?

There is the possibility to define an admin user with his password with the following environment variable:

```
KEYCLOAK_ADMIN_USER: admin
KEYCLOAK_ADMIN_PASSWORD: 1234
```

During the very first initial startup, Keycloak will create this admin user successfully.

During the future startup's of Keycloak, I get the following error message:

`ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
`

I get this error message, because this admin user were already created during the very first initial startup.

In your README, I'm able to see the following variable name:

`KEYCLOAK_CREATE_ADMIN_USER`: Create administrator user on boot. Default: true.

If I'm going to set the above variable to `false`, it does not work, still get the same error message.

### What is the expected behavior?

1. Defining the admin user with his password for the very first initial startup [IT WORKS!]
2. Setting the variable `KEYCLOAK_CREATE_ADMIN_USER: false` for the future startup's of Keycloak [IT DOES NOT WORKS!]

### What do you see instead?

`ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
`

### Additional information

1. I'm also not able to find the variable `KEYCLOAK_CREATE_ADMIN_USER` in your `/opt/bitnami/scripts/keycloak-env.sh`
2. Somehow this variable lost his life: https://github.com/bitnami/charts/pull/10831/files

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket. Does the container crash when trying to add the user that already exists?

**Comment by m4rcoschmucki** [comment]
Hi,

No, the keycloak container will not crash during startup, it will be up&running.

But please consider the following points:

1. If it would be a WARN instead of an ERROR, I would be able to live with it.
2. If you're going to monitor the docker-logs or k8s-pod-logs with another third party software, you get error notifications for nothing.
3. In general, ERROR's should no be ignored (even you could do it in our case???).

**Comment by dgomezleon** [comment]
Hi @m4rcoschmucki ,

Thanks for reporting it. We will remove `KEYCLOAK_CREATE_ADMIN_USER ` from our README.md.

I agree with you that with should be a WARN instead of an error. However, this is something that you should report directly to keycloak support.

**Comment by m4rcoschmucki** [comment]
Hi @dgomezleon 

Thank you for your feedback.

Honestly, I do not understand it.
What about to implement this variable again?

Many thanks for your feedback.

**Comment by dgomezleon** [comment]
Hi @m4rcoschmucki ,

Let me share with you this [comment](https://github.com/bitnami/charts/issues/10715#issuecomment-1161495230) in order to clear it up.

We used that variable to execute `add-user-keycloak.sh` script. However, Keycloak 17 switched to Quarkus ([thread](https://keycloak.discourse.group/t/keycloak-17-use-the-add-user-keycloak-script-is-missing/13568)).

That way, every time the service is started it will try to create an admin account based on `KEYCLOAK_ADMIN` environment variable.

I hope it helps

**Comment by m4rcoschmucki** [comment]
Hi @dgomezleon 

I'm not sure, but I think the reason why Keycloak is trying to create an admin user at every startup is because you've default values for the following variables defined in keycloak-env.sh:

```
export KEYCLOAK_ADMIN="${KEYCLOAK_ADMIN:-user}"
export KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:-bitnami}"
```

I think, if Keycloak will startup without values for the above environment variables, there will be no try of Keycloak to create an admin user, what do you think?

Many thanks for your feedback.

**Comment by dgomezleon** [comment]
Hi @m4rcoschmucki,

In that case, you could use this docker-compose to provide an empty `KEYCLOAK_ADMIN`:

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:20
    environment:
      - KEYCLOAK_ADMIN=
    depends_on:
      - postgresql
    ports:
      - "80:8080"

volumes:
  postgresql_data:
    driver: local
```

**Comment by m4rcoschmucki** [comment]
Hi @dgomezleon 

Thank you for your feedback.

Unfortunately it does not work, Keycloak is still trying to create an admin user.

But the difference is the following (without dash before env name and instead of an equal sign I have a colon --> but I'm using the docker-compose version 3 and not like you 2):

```
    environment:
      KEYCLOAK_ADMIN_USER:
      KEYCLOAK_ADMIN_PASSWORD:
```

The second test with the following did also not work (single quotes for the env value):

```
    environment:
      KEYCLOAK_ADMIN_USER: ''
      KEYCLOAK_ADMIN_PASSWORD: ''
```

Many thanks for your feedback.

**Comment by dgomezleon** [comment]
Hello @m4rcoschmucki ,

Using the code below worked for me too:

```
    environment:
      KEYCLOAK_ADMIN_USER:
      KEYCLOAK_ADMIN_PASSWORD:
```

You could share your whole `docker-compose.yaml` file and your exact `docker-compose` version in order to compare it.

Anyway, note this would avoid the creation of admin user at initial and future startups.

**Comment by m4rcoschmucki** [comment]
Hi @dgomezleon 

1. docker-compose version: `v2.0.1`

2. docker-compose file:

```
version: '3'

networks:
  default:
    name: test-docker-network01

services:
  keycloak-pg:
    image: docker.example.com/postgres:13
    container_name: keycloak-pg
    ports:
      - "5432"
    volumes:
        - /docker-home/data/keycloak/postgresql/data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M


  keycloak:
    image: docker.example.com/bitnami-keycloak:20.0.3
    container_name: keycloak
    ports:
      - 8090:8080
    environment:
      TZ: Europe/Berlin
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_ADDR: keycloak-pg
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN_USER:
      KEYCLOAK_ADMIN_PASSWORD:
      KEYCLOAK_LOG_LEVEL: info
      BITNAMI_DEBUG: 'true'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
```

3. log output during startup:

```keycloak 08:29:45.20 Welcome to the Bitnami keycloak container
keycloak 08:29:45.20 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 08:29:45.21 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 08:29:45.21
keycloak 08:29:45.21 INFO  ==> ** Starting keycloak setup **
keycloak 08:29:45.22 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 08:29:45.24 INFO  ==> Trying to connect to database server keycloak-pg...
keycloak 08:29:45.25 INFO  ==> Found database server listening at keycloak-pg:5432
keycloak 08:29:45.26 INFO  ==> Configuring database settings
keycloak 08:29:45.27 DEBUG ==> Setting db to 'postgres' in Keycloak configuration
keycloak 08:29:45.28 DEBUG ==> Setting db-url to 'jdbc:postgresql://keycloak-pg:5432/keycloak?currentSchema=public' in Keycloak configuration
keycloak 08:29:45.30 DEBUG ==> Setting db-username to 'keycloak' in Keycloak configuration
keycloak 08:29:45.31 DEBUG ==> Setting db-password to 'password' in Keycloak configuration
keycloak 08:29:45.32 INFO  ==> Enabling statistics
keycloak 08:29:45.33 DEBUG ==> Setting metrics-enabled to 'false' in Keycloak configuration
keycloak 08:29:45.34 INFO  ==> Configuring http settings
keycloak 08:29:45.35 DEBUG ==> Setting http-enabled to 'true' in Keycloak configuration
keycloak 08:29:45.36 DEBUG ==> Setting http-relative-path to '/' in Keycloak configuration
keycloak 08:29:45.37 DEBUG ==> Setting http-port to '8080' in Keycloak configuration
keycloak 08:29:45.38 DEBUG ==> Setting https-port to '8443' in Keycloak configuration
keycloak 08:29:45.40 INFO  ==> Configuring hostname settings
keycloak 08:29:45.40 DEBUG ==> Setting hostname-strict to 'false' in Keycloak configuration
keycloak 08:29:45.41 INFO  ==> Configuring cache count
keycloak 08:29:45.41 DEBUG ==> Setting cache to 'ispn' in Keycloak configuration
keycloak 08:29:45.42 INFO  ==> Configuring log level
keycloak 08:29:45.42 DEBUG ==> Setting log-level to 'info' in Keycloak configuration
keycloak 08:29:45.43 DEBUG ==> Setting log-console-output to 'default' in Keycloak configuration
keycloak 08:29:45.44 INFO  ==> Configuring proxy
keycloak 08:29:45.45 DEBUG ==> Setting proxy to 'passthrough' in Keycloak configuration
keycloak 08:29:45.46 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
keycloak 08:29:45.47 DEBUG ==> Sourcing /docker-entrypoint-initdb.d/0_startup.sh
keycloak 08:29:45.48 INFO  ==> ########################################
keycloak 08:29:45.48 INFO  ==> ###  customized startup of Keycloak  ###
keycloak 08:29:45.48 INFO  ==> ########################################
keycloak 08:29:45.48 INFO  ==> !!! POSTGRES DATABASE IS USED !!!
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2023-02-17 08:29:52,205 WARN  [org.keycloak.services] (build-17) KC-SERVICES0047: metrics (org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2023-02-17 08:29:53,216 WARN  [org.keycloak.services] (build-17) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2023-02-17 08:30:02,378 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 13402ms
Server configuration updated and persisted. Run the following command to review the configuration:

         kc.sh show-config

Next time you run the server, just run:

         kc.sh start --optimized

2023-02-17 08:30:04,788 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-02-17 08:30:06,758 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2023-02-17 08:30:08,540 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-02-17 08:30:08,617 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-02-17 08:30:08,675 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-02-17 08:30:08,807 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-02-17 08:30:09,074 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
2023-02-17 08:30:09,257 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2023-02-17 08:30:09,257 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-02-17 08:30:09,382 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2023-02-17 08:30:09,383 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2023-02-17 08:30:09,384 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2023-02-17 08:30:09,384 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2023-02-17 08:30:11,397 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 19ee28b6f5f0-26908: no members discovered after 2004 ms: creating cluster as coordinator
2023-02-17 08:30:11,413 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [19ee28b6f5f0-26908|0] (1) [19ee28b6f5f0-26908]
2023-02-17 08:30:11,426 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `19ee28b6f5f0-26908`, physical addresses are `[172.18.0.23:49117]`
2023-02-17 08:30:12,132 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: 19ee28b6f5f0-26908, Site name: null
2023-02-17 08:30:13,145 INFO  [io.quarkus] (main) Keycloak 20.0.3 on JVM (powered by Quarkus 2.13.6.Final) started in 10.494s. Listening on: http://0.0.0.0:8080
2023-02-17 08:30:13,146 INFO  [io.quarkus] (main) Profile prod activated.
2023-02-17 08:30:13,146 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2023-02-17 08:30:13,205 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'user' to realm 'master': user with username exists```
