### ISSUE TITLE
Updating suitecrm

### ISSUE THREAD

**Issue by cristiancordones** [bitnami/containers#23834]
### Name and Version

bitnami/suitecrm:8.2.3

### What steps will reproduce the bug?

My docker-compose file:
```yaml
  suitecrm:
    image: docker.io/bitnami/suitecrm:8.2.3
    ports:
      - '12002:8080'
      - '9443:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=...
      - SUITECRM_DATABASE_USER=...
      - SUITECRM_DATABASE_NAME=...
      - SUITECRM_DATABASE_PASSWORD=..
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_USERNAME=...
      - SUITECRM_PASSWORD=...
      - SUITECRM_EMAIL=...
      - SUITECRM_ENABLE_HTTPS=yes
      - SUITECRM_EXTERNAL_HTTP_PORT_NUMBER=80
      - SUITECRM_EXTERNAL_HTTPS_PORT_NUMBER=443
    volumes:
      - ./data/suitecrm_data:/bitnami/suitecrm
      - ./data/certs:/opt/bitnami/apache/conf/bitnami/certs
    depends_on:
      - mariadb
    networks:
      - suitecrm
    restart: always
```
I followed the update procedure:
1. docker pull bitnami/suitecrm:latest
2. docker-compose stop suitecrm
3. took a snapshot
4. docker-compose rm -v suitecrm
5. docker-compose up -d

After that checked, but the version is still 8.1.3. 
Is this because my volume is mounted  see config:     - ./data/suitecrm_data:/bitnami/suitecrm
What do I need to do, to get the instance updated?

Kind regards

### What is the expected behavior?

Expeted is 8.2.3

### What do you see instead?

I still see 8.1.3 in the about section
