### ISSUE TITLE
[bitnami/nginx] Regression enables HTTPS by default in Nginx container

### ISSUE THREAD

**Issue by syphr42** [bitnami/containers#24125]
### Name and Version

bitnami/nginx:1.23.3-debian-11-r24

### What steps will reproduce the bug?

1. Create the following Dockerfile based on bitnami/nginx:1.23.3-debian-11-r24 to remove the sample certificate and private key from the image (required to pass security scans that care about private keys embedded in images).

```Dockerfile
FROM bitnami/nginx:1.23.3-debian-11-r24

# Remove sample certs included with base image
RUN rm -rf /certs/*
```
2. Build the image: `docker build -t nginx-test .`
3. Run the image: `docker run --rm nginx-test`

### What is the expected behavior?

```
nginx 16:27:33.97 
nginx 16:27:33.97 Welcome to the Bitnami nginx container
nginx 16:27:33.98 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx 16:27:33.98 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx 16:27:33.98 
nginx 16:27:33.99 INFO  ==> ** Starting NGINX setup **
nginx 16:27:34.01 INFO  ==> Validating settings in NGINX_* env vars
nginx 16:27:34.04 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 16:27:34.06 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory

nginx 16:27:34.14 INFO  ==> ** NGINX setup finished! **
nginx 16:27:34.16 INFO  ==> ** Starting NGINX **
```

### What do you see instead?

```
nginx 16:27:53.77 
nginx 16:27:53.77 Welcome to the Bitnami nginx container
nginx 16:27:53.78 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx 16:27:53.80 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx 16:27:53.80 
nginx 16:27:53.81 INFO  ==> ** Starting NGINX setup **
nginx 16:27:53.87 INFO  ==> Validating settings in NGINX_* env vars
nginx 16:27:53.90 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 16:27:53.99 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory

nginx 16:27:54.05 INFO  ==> ** NGINX setup finished! **
nginx 16:27:54.08 INFO  ==> ** Starting NGINX **
2023/02/15 16:27:54 [emerg] 1#1: cannot load certificate "/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

### Additional information

If you delete only the private key (e.g. `rm -rf /certs/server.key`), the error still occurs, but on the read of the private key instead of the read of the public cert.

HTTPS should not be enabled by default so the cert and key should not be read without choosing to enable HTTPS.

The regression was caused by https://github.com/bitnami/containers/pull/23877 which enables SSL even when `NGINX_HTTPS_PORT_NUMBER` is not set.

Changing the Dockerfile above to `FROM bitnami/nginx:1.23.3-debian-11-r23` makes the image work again without the certs.

**Comment by andresbono** [comment]
Hi @syphr42, your issue seems related to the following ones:

- https://github.com/bitnami/charts/issues/13041
  - https://github.com/bitnami/containers/pull/11187
- https://github.com/bitnami/containers/issues/12995
  - https://github.com/bitnami/containers/pull/22519

We will try define a solution that suits all the reported use cases.

Thanks for reporting the issue.

**Comment by andresbono** [comment]
Hi again @syphr42, `bitnami/nginx 1.23.3-debian-11-r26` (https://github.com/bitnami/containers/pull/24227) fixes this issue. Please, give it a try and let us now!

**Comment by syphr42** [comment]
@andresbono Looks good on my end! Thanks for the quick turnaround.

**Comment by jgournet** [comment]
@andresbono : Would it be possible to port the same fix into "latest" ?
As far as I know, the current latest ( 1.23.4-debian-11-r7 ) is having this issue.

(let me know if I should create a new ticket)

Thanks a lot

**Comment by andresbono** [comment]
@jgournet could you please describe the issue you are having and how can we reproduce it? The fix is included in "latest" as well...

It is fine to reopen this ticket if the issue is related 👍

**Comment by jgournet** [comment]
Thanks for that confirmation about the fix being in latest.
So, issue I'm having is:
```
nginx 21:35:13.73 
nginx 21:35:13.73 Welcome to the Bitnami nginx container
nginx 21:35:13.73 Subscribe to project updates by watching https://github.com/bitnami/containers
nginx 21:35:13.73 Submit issues and feature requests at https://github.com/bitnami/containers/issues
nginx 21:35:13.73 
nginx 21:35:13.74 INFO  ==> ** Starting NGINX setup **
nginx 21:35:13.75 INFO  ==> Validating settings in NGINX_* env vars
nginx 21:35:13.75 WARN  ==> The NGINX configuration file '/opt/bitnami/nginx/conf/nginx.conf' is not writable by current user. Configurations based on environment variables will not be applied.
mkdir: cannot create directory '/opt/bitnami/nginx/conf/bitnami': Read-only file system
```

This happens on:
Image ID:       docker.io/bitnami/nginx@sha256:7b80ebbe65bc2b40555495ae21700fba4770972a71bebf4a5b292e43ab35aa1a

How to reproduce it ?
Now, that's the tricky part ...

1) This happens when running on EKS 1.24 and 1.25 ... but not in all our clusters (only 2 clusters out of 5 have this issue).
2) The issue is not even consistent: just keep on killing the faulty pod, and it will work after - so far, it seems that some nodes get the issue while other work fine
3) here are some parts of our configuration:
Pod:
```
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: NGINX_HTTP_PORT_NUMBER
      value: "8080"
    image: docker.io/bitnami/nginx:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: http
      timeoutSeconds: 5
    name: nginx
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 33306
      name: tcp33306
      protocol: TCP
    - containerPort: 33307
      name: tcp33307
      protocol: TCP
[...]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/bitnami/nginx/conf/
      name: nginx-conf
    - mountPath: /tmp
      name: tmp-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xc6l8
      readOnly: true
[...]
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: nginx.conf
        path: nginx.conf
      name: dbproxy-conf
    name: nginx-conf
  - emptyDir: {}
    name: tmp-volume
```

Config map:
```
apiVersion: v1
data:
  nginx.conf: |
    worker_processes  1;
    error_log  /opt/bitnami/nginx/logs/error.log notice;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 10000;
    events {
        worker_connections  10000;
    }
    http {
        proxy_temp_path /tmp/proxy_temp;
        client_body_temp_path /tmp/client_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  "/opt/bitnami/nginx/logs/access.log"  main;
        real_ip_header X-Forwarded-For;
        set_real_ip_from 10.10.0.0/16;
        sendfile        on;
        include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
        server {
          listen 8080;
          location = /health {
              access_log off;
              add_header 'Content-Type' 'application/json';
              return 200 '{"status":"UP"}';
          }
        }
    }


    stream {
        resolver 172.20.0.10 valid=30s;

        # SF360:
        map $remote_addr $360 {
          default 360.internal.dummy.com;
        }
        server {
          listen 33306;
          proxy_pass $360:80;
          proxy_connect_timeout 5s;
          proxy_timeout 5m;
        }
[...]
```

I don't think there's anything specific in there :) 

Additional note (and thus my original question):
This happens when using "latest", but if I set the image to be "1.23.3-debian-11-r26", it does NOT happen at all

(and yes, I realize that this sounds insane ...)

Thank you for your help !
