### ISSUE TITLE
[bitnami/jasperreports] Not run with external Mysql without SKIP_BOOTSTRAP

### ISSUE THREAD

**Issue by CarTerr** [bitnami/containers#24142]
### Name and Version

bitnami/jasperreports:8.1.0

### What steps will reproduce the bug?

1. Run jasperreports using docker-compose up, with external mysql

```
version: '2'
services:
  jasperreports:
    image: docker.io/bitnami/jasperreports:8.1.0
    ports:
      - '80:8080'
    volumes:

      - 'jasperreports_data:/bitnami/jasperreports'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - JASPERREPORTS_DATABASE_TYPE=mysql
      - JASPERREPORTS_DATABASE_HOST=192.168.1.149
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=root
      - JASPERREPORTS_DATABASE_PASSWORD=root
      - JASPERREPORTS_DATABASE_NAME=jasperserver_1
      - JASPERREPORTS_SKIP_BOOTSTRAP=no
     
volumes:
  jasperreports_data:
    driver: local
```
    
  2. BD create fine. Stop container
  ```
docker-compose down
 ```

3. Change JASPERREPORTS_SKIP_BOOTSTRAP from 'no' to 'yes' and run container.

### What is the expected behavior?

Jasperreport run without recreate DB

### What do you see instead?

container exited with code 1
![image](https://user-images.githubusercontent.com/3523808/219359649-2e3a994f-a379-4dd5-ab96-403d82cac160.png)
