### ISSUE TITLE
[bitnami/solr] Multiple SOLR_CORES with different SOLR_CORE_CONF_DIR is impossible

### ISSUE THREAD

**Issue by sylvanr** [bitnami/containers#24146]
### Name and Version

bitnami/solr:latest

### What steps will reproduce the bug?

I've got a docker compose setup for the latest bitnami/solr image, and I'm trying to start up two cores, with two different configurations as they have different content in their managed-schema specifically. 
```
solr:
    container_name: solr
    restart: always
    image: bitnami/solr:latest
    ports:
      - 8983:8983
    environment:
      # core setup
      - SOLR_CORES=activity,dataset
      - SOLR_CORE_CONF_DIR=/core_conf/activity,/core_conf/dataset
    volumes:
      - './activity/conf:/core_conf/activity'
      - './dataset/conf:/core_conf/budget'
```
where the core_conf is mounted with those different configurations.

Of course if I remove one of the list of conf dir's, this works, but both dataset and activity cores have the same config, which makes this unusable for now

### What is the expected behavior?

Two cores to be created with different configs as provided by the user.

### What do you see instead?

This is not possible and the process crashes

### Additional information

I'm not entirely sure this is a bug, it might be intended behaviour, so this might be a feature request? But for me logically if you are able to add different cores through a list, you should be able to pass a list of configurations as well, matching those cores.

If anyone knows whether or not this is intended, and if there is anything i can do to bypass this other than completely building the image from scratch, let me know!
