### ISSUE TITLE
[Note] InnoDB: WSREP: BF lock wait long for

### ISSUE THREAD

**Issue by smartycoder** [bitnami/containers#24155]
### Name and Version

bitnami/mariadb-galera:10.10.2

### What steps will reproduce the bug?

Galera cluster node2 is locked and I need to shut it down every day.

### What do you see instead?
```
InnoDB: WSREP: BF lock wait long for trx:0x53e3e query: UPDATE ...
```

**Comment by carrodher** [comment]
Could you please provide more info about how you are deploying the container?

**Comment by smartycoder** [comment]
> Could you please provide more info about how you are deploying the container?

Node1

```
version: '3.3'
services:
    mariadb-galera:
        image: bitnami/mariadb-galera:10.10.2
        user: root
        container_name: galera
        network_mode: host
        restart: always
        environment:
            - MARIADB_GALERA_CLUSTER_NAME=galera
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.16.0.138,172.16.0.139
            - MARIADB_GALERA_NODE_ADDRESS=172.16.0.138
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=s3cr3t
            - MARIADB_ROOT_PASSWORD=s3cr3t
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=s3cr3t
            - MARIADB_REPLICATION_USER=replica
            - MARIADB_REPLICATION_PASSWORD=s3cr3t
            - MARIADB_GALERA_CLUSTER_BOOTSTRAP=true
            #- MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=5000 --max_allowed_packet=134217728
        volumes:
            - ./data:/bitnami/mariadb
    
```

Node2:

```
version: '3.3'
services:
    mariadb-galera:
        image: bitnami/mariadb-galera:10.10.2
        user: root
        container_name: galera
        network_mode: host
        restart: always
        environment:
            - MARIADB_GALERA_CLUSTER_NAME=galera
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.16.0.138,172.16.0.139
            - MARIADB_GALERA_NODE_ADDRESS=172.16.0.139
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=s3cr3t
            - MARIADB_ROOT_PASSWORD=s3cr3t
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=s3cr3t
            - MARIADB_REPLICATION_USER=replica
            - MARIADB_REPLICATION_PASSWORD=s3cr3t
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=5000 --max_allowed_packet=134217728
        volumes:
            - ./data:/bitnami/mariadb
    
        
```
