### ISSUE TITLE
[bitnami/kafka] - Every single command is VERY SLOW

### ISSUE THREAD

**Issue by kitkars** [bitnami/containers#24486]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

Use this docker-compose yaml.

```
version: "3.2"
services:
  kafka1:
    image: 'bitnami/kafka:3.4'
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,INTERNAL://:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
```

- access the docker container `docker exec -it kafka bash`
- **_`cd /opt/bitnami/kafka/bin`_**
- Enter this command **kafka-topics.sh** and hit enter

### What is the expected behavior?

It should show kafa-topics.sh options more or less immediately.

### What do you see instead?

It takes 7 seconds!!!!!
