### ISSUE TITLE
[bitnami/kafka] KAFKA_KRAFT_CLUSTER_ID not working with docker-compose file despite being set

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/containers#24489]
### Name and Version

bitnami/kafka:latest (3.2.3)

### What steps will reproduce the bug?

writing docker-compose.yml file, enabling kafka_kraft and trying to set cluster id. 

Here is the docker-compose file

```
version: "3"
services:

  broker-1:
    image: 'bitnami/kafka:latest'
    container_name: broker-1
    ports:
      - '9092:9092'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_KRAFT_CLUSTER_ID = A370i42nQuCtnpFN-7I41Q
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093,2@broker-2:9095
    - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./run_workaround.sh:/tmp/run_workaround.sh
#    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka

  broker-2:
    image: 'bitnami/kafka:latest'
    container_name: broker-2
    ports:
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID = A370i42nQuCtnpFN-7I41Q
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9094
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093,2@broker-2:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./run_workaround.sh:/tmp/run_workaround.sh
#    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
```

### What is the expected behavior?

Launcinh the brokers with no issue

### What do you see instead?

KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
```
Creating new QuorumController with clusterId sW3uQO3mSQ-rL02_elnhZQ, authorizer Optional.empty.
```
and then an infinite loop of retries:
```
Unexpected error INCONSISTENT_CLUSTER_ID in VOTE response: InboundResponse(correlationId=0, data=VoteResponseData(errorCode=104, topics=[]), sourceId=1) (org.apache.kafka.raft.KafkaRaftClient)
```

**Comment by aoterolorenzo** [comment]
Hi @ETisREAL,

In an initial review our the code you provide, I see that the env var equal sign are surrounded by spaces.

After fixing that, both nodes seems to set the cluster id properly:

```
broker-1  | [2023-02-23 10:28:00,332] INFO [Controller 1] Creating new QuorumController with clusterId A370i42nQuCtnpFN-7I41Q
broker-2  | [2023-02-23 10:28:00,541] INFO [Controller 2] Creating new QuorumController with clusterId A370i42nQuCtnpFN-7I41Q
```

Fixed docker-composer.yaml:

```
version: "3"
services:

  broker-1:
    image: 'bitnami/kafka:latest'
    container_name: broker-1
    ports:
      - '9092:9092'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_KRAFT_CLUSTER_ID=A370i42nQuCtnpFN-7I41Q
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093,2@broker-2:9095
    - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./run_workaround.sh:/tmp/run_workaround.sh
#    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka

  broker-2:
    image: 'bitnami/kafka:latest'
    container_name: broker-2
    ports:
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=A370i42nQuCtnpFN-7I41Q
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9094
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093,2@broker-2:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./run_workaround.sh:/tmp/run_workaround.sh
#    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
```
