### ISSUE TITLE
[bitnami/openldap] LDAP_ADMIN_PASSWORD from Secret fails

### ISSUE THREAD

**Issue by AshtonKem** [bitnami/containers#24924]
### Name and Version

bitnami/openldap:latest

### What steps will reproduce the bug?

1. Create generic secret using desired admin password
2. Configure bitnami env to use secret for LDAP_ADMIN_PASSWORD
3. Deploy

### What is the expected behavior?

Should deploy openldap and run with the provided admin password.

### What do you see instead?

Crash backoff loop with error 123. Logs attached below.

```
 16:23:20.28 INFO  ==> ** Starting LDAP setup **
 16:23:20.35 INFO  ==> Validating settings in LDAP_* env vars
 16:23:20.36 INFO  ==> Initializing OpenLDAP...
 16:23:20.40 INFO  ==> Creating LDAP online configuration
 16:23:20.41 INFO  ==> Creating slapd.ldif
 16:23:20.46 INFO  ==> Starting OpenLDAP server in background
 16:23:21.48 INFO  ==> Configure LDAP credentials for admin user
 16:23:21.52 INFO  ==> Adding LDAP extra schemas
 16:23:21.58 INFO  ==> Loading custom LDIF files...
 16:23:21.58 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
```

### Additional information

This configuration works:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: identity
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ROOT
              value: dc=kemerling,dc=homelab
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "yes"
            - name: LDAP_ADMIN_PASSWORD
              value: foo
          ports:
            - name: tcp-ldap
              containerPort: 1389
          volumeMounts:
            - name:  ldifs
              mountPath: "/ldifs"
              readOnly: true
            - name: certs
              mountPath: "/opt/openldap/certs"
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: openldap-certs
        - name: ldifs
          configMap:
            name: openldap-ldifs
```

This one does not:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: identity
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ROOT
              value: dc=kemerling,dc=homelab
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "yes"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: adminpassword
          ports:
            - name: tcp-ldap
              containerPort: 1389
          volumeMounts:
            - name:  ldifs
              mountPath: "/ldifs"
              readOnly: true
            - name: certs
              mountPath: "/opt/openldap/certs"
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: openldap-certs
        - name: ldifs
          configMap:
            name: openldap-ldifs
```

Secret (should decode to "foo"):

```
apiVersion: v1
data:
  adminpassword: Zm9vCg==
kind: Secret
metadata:
  name: openldap
  namespace: identity
```

**Comment by AshtonKem** [comment]
Update: This is related to the "ldifs" ConfigMap. If I comment out that volumeMount, it begins as expected.

Here's the ldif ConfigMap:

```
apiversion: v1
kind: ConfigMap
metadata:
  name: openldap-ldifs
  namespace: identity
  labels:
    app.kubernetes.io/name: openldap
data:
  users.ldif: |-
    dn: dc=kemerling,dc=homelab
    dc: kemerling
    objectClass: dcObject
    objectClass: organization
    o: Kemerling Homelab

    dn: ou=People,dc=kemerling,dc=homelab
    objectClass: organizationalUnit
    ou: People

    dn: ou=Group,dc=kemerling,dc=homelab
    objectClass: organizationalUnit
    ou: Group
```

**Comment by AshtonKem** [comment]
Looks like it all works if I set `LDAP_ADMIN_USERNAME`, which I guess does not default if you provide `LDAP_ADMIN_PASSWORD`.

**Comment by AshtonKem** [comment]
Debug logs:

```
 20:27:00.13 INFO  ==> ** Starting LDAP setup **
 20:27:00.21 INFO  ==> Validating settings in LDAP_* env vars
 20:27:00.22 INFO  ==> Initializing OpenLDAP...
 20:27:00.23 DEBUG ==> Ensuring expected directories/files exist...
 20:27:00.26 INFO  ==> Creating LDAP online configuration
 20:27:00.27 INFO  ==> Creating slapd.ldif
 20:27:00.33 INFO  ==> Starting OpenLDAP server in background
63f67a94.14c7c240 0x7fb0a3372740 @(#) $OpenLDAP: slapd 2.6.4 (Feb 22 2023 11:46:45) $
 @e337c9d3914b:/bitnami/blacksmith-sandox/openldap-2.6.4/servers/slapd
63f67a94.1b5dd752 0x7fb0a3372740 slapd starting
 20:27:01.35 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
63f67a95.15b3a17f 0x7fb0625d0700 conn=1000 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
63f67a95.15b7cbec 0x7fb0625d0700 conn=1000 op=0 BIND dn="" method=163
63f67a95.15b97648 0x7fb0625d0700 conn=1000 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
63f67a95.15ba4226 0x7fb0625d0700 conn=1000 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
63f67a95.15bb7157 0x7fb0625d0700 conn=1000 op=0 RESULT tag=97 err=0 qtime=0.000020 etime=0.000286 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
63f67a95.15c30537 0x7fb061dcf700 conn=1000 op=1 MOD dn="olcDatabase={2}mdb,cn=config"
63f67a95.15c47a26 0x7fb061dcf700 conn=1000 op=1 MOD attr=olcSuffix
63f67a95.1b1759a4 0x7fb061dcf700 conn=1000 op=1 RESULT tag=103 err=0 qtime=0.000035 etime=0.089494 text=
63f67a95.1b1c434b 0x7fb061dcf700 conn=1000 op=2 MOD dn="olcDatabase={2}mdb,cn=config"
63f67a95.1b1d2dde 0x7fb061dcf700 conn=1000 op=2 MOD attr=olcRootDN
63f67a95.1f03260a 0x7fb061dcf700 conn=1000 op=2 RESULT tag=103 err=0 qtime=0.000025 etime=0.065551 text=
63f67a95.1f09404b 0x7fb0625d0700 conn=1000 op=3 MOD dn="olcDatabase={2}mdb,cn=config"
63f67a95.1f0a89b6 0x7fb0625d0700 conn=1000 op=3 MOD attr=olcRootPW
63f67a95.1f19fc6f 0x7fb0625d0700 conn=1000 op=3 RESULT tag=103 err=0 qtime=0.000035 etime=0.001175 text=
63f67a95.1f1f4103 0x7fb061dcf700 conn=1000 op=4 MOD dn="olcDatabase={1}monitor,cn=config"
63f67a95.1f207f77 0x7fb061dcf700 conn=1000 op=4 MOD attr=olcAccess
63f67a95.1f2e997f 0x7fb061dcf700 conn=1000 op=4 RESULT tag=103 err=0 qtime=0.000026 etime=0.001059 text=
modifying entry "olcDatabase={2}mdb,cn=config"
modifying entry "olcDatabase={2}mdb,cn=config"
modifying entry "olcDatabase={2}mdb,cn=config"
modifying entry "olcDatabase={1}monitor,cn=config"
63f67a95.1f330e2c 0x7fb0625d0700 conn=1000 op=5 UNBIND
63f67a95.1f34dd50 0x7fb0625d0700 conn=1000 fd=12 closed
 20:27:01.52 INFO  ==> Adding LDAP extra schemas
SASL/EXTERNAL authentication started
63f67a95.2050a45d 0x7fb061dcf700 conn=1001 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
63f67a95.205350a1 0x7fb061dcf700 conn=1001 op=0 BIND dn="" method=163
63f67a95.20549062 0x7fb061dcf700 conn=1001 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
63f67a95.20554897 0x7fb061dcf700 conn=1001 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
63f67a95.20563fe2 0x7fb061dcf700 conn=1001 op=0 RESULT tag=97 err=0 qtime=0.000023 etime=0.000222 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
63f67a95.2060728b 0x7fb0625d0700 conn=1001 op=1 ADD dn="cn=cosine,cn=schema,cn=config"
63f67a95.2096375a 0x7fb0625d0700 conn=1001 op=1 RESULT tag=105 err=0 qtime=0.000021 etime=0.003630 text=
63f67a95.2099815a 0x7fb061dcf700 conn=1001 op=2 UNBIND
adding new entry "cn=cosine,cn=schema,cn=config"
63f67a95.209b93da 0x7fb061dcf700 conn=1001 fd=12 closed
SASL/EXTERNAL authentication started
63f67a95.2121575d 0x7fb0625d0700 conn=1002 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
63f67a95.2123797a 0x7fb061dcf700 conn=1002 op=0 BIND dn="" method=163
63f67a95.21251719 0x7fb061dcf700 conn=1002 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
63f67a95.21260217 0x7fb061dcf700 conn=1002 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
63f67a95.212751b1 0x7fb061dcf700 conn=1002 op=0 RESULT tag=97 err=0 qtime=0.000022 etime=0.000279 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
63f67a95.212da91a 0x7fb0625d0700 conn=1002 op=1 ADD dn="cn=inetorgperson,cn=schema,cn=config"
63f67a95.21464df9 0x7fb0625d0700 conn=1002 op=1 RESULT tag=105 err=0 qtime=0.000026 etime=0.001695 text=
63f67a95.21493de1 0x7fb061dcf700 conn=1002 op=2 UNBIND
adding new entry "cn=inetorgperson,cn=schema,cn=config"
63f67a95.214ab421 0x7fb061dcf700 conn=1002 fd=12 closed
SASL/EXTERNAL authentication started
63f67a95.21e16be3 0x7fb0625d0700 conn=1003 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
63f67a95.21e322a4 0x7fb061dcf700 conn=1003 op=0 BIND dn="" method=163
63f67a95.21e48925 0x7fb061dcf700 conn=1003 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
63f67a95.21e58021 0x7fb061dcf700 conn=1003 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
63f67a95.21e6ad0b 0x7fb061dcf700 conn=1003 op=0 RESULT tag=97 err=0 qtime=0.000024 etime=0.000260 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
63f67a95.21ef3f58 0x7fb0625d0700 conn=1003 op=1 ADD dn="cn=nis,cn=schema,cn=config"
63f67a95.221088c3 0x7fb0625d0700 conn=1003 op=1 RESULT tag=105 err=0 qtime=0.000020 etime=0.002251 text=
63f67a95.2212aa71 0x7fb0625d0700 conn=1003 op=2 UNBIND
63f67a95.2213d5a6 0x7fb0625d0700 conn=1003 fd=12 closed
adding new entry "cn=nis,cn=schema,cn=config"
 20:27:01.58 INFO  ==> Loading custom LDIF files...
 20:27:01.58 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
63f67a95.247ff8d8 0x7fb061dcf700 conn=1004 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
63f67a95.2482413a 0x7fb0625d0700 conn=1004 op=0 BIND dn="cn=admin,dc=kemerling,dc=homelab" method=128
63f67a95.24851e79 0x7fb0625d0700 conn=1004 op=0 RESULT tag=97 err=49 qtime=0.000028 etime=0.000261 text=
ldap_bind: Invalid credentials (49)
63f67a95.2488ad25 0x7fb061dcf700 conn=1004 op=1 UNBIND
63f67a95.248a4794 0x7fb061dcf700 conn=1004 fd=12 closed
63f67a95.2557ebd3 0x7fb062dd1700 daemon: shutdown requested and initiated.
63f67a95.255dc618 0x7fb062dd1700 slapd shutdown: waiting for 0 operations/tasks to finish
63f67a95.265cd088 0x7fb0a3372740 slapd stopped.
```

**Comment by AshtonKem** [comment]
The big issue is that when you use k8s secrets, for some reason bash includes a newline when quoting into strings.

K8s config:
```
            - name: FOO
              value: foo
            - name: BAR
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: adminpassword
```

Console result:

```
I have no name!@openldap-b6d546d95-9bzxm:/$ echo $FOO
foo
I have no name!@openldap-b6d546d95-9bzxm:/$ echo $BAR
foo
I have no name!@openldap-b6d546d95-9bzxm:/$ echo "$FOO"
foo
I have no name!@openldap-b6d546d95-9bzxm:/$ echo "$BAR"
foo

I have no name!@openldap-b6d546d95-9bzxm:/$ 
```
