### ISSUE TITLE
[bitnami/kibana] kibana.yml doesn't effective when using volumes by docker-compose

### ISSUE THREAD

**Issue by 1170301013** [bitnami/containers#25714]
### Name and Version

bitnami/kibana:8.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. write a docker-compose.yml like this:
```yaml
version: "2"
services:
  elasticsearch-node1:
    image: docker.io/bitnami/elasticsearch:8.1.2
    user: root
    hostname: elasticsearch-node1
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ELASTICSEARCH_INGEST_GEOIP_DOWNLOADER_ENABLED=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./es/elasticsearch_node1_data:/bitnami"
    container_name: elasticsearch-node1
    networks:
       kafka_kafka_network:
         ipv4_address: 172.24.2.33

  elasticsearch-node2:
    image: docker.io/bitnami/elasticsearch:8.1.2
    user: root
    hostname: elasticsearch-node2
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ELASTICSEARCH_INGEST_GEOIP_DOWNLOADER_ENABLED=false
    volumes:
      - "./es/elasticsearch_node2_data:/bitnami"
    container_name: elasticsearch-node2
    networks:
       kafka_kafka_network:
         ipv4_address: 172.24.2.34

  elasticsearch-node3:
    image: docker.io/bitnami/elasticsearch:8.1.2
    user: root
    hostname: elasticsearch-node3
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_HEAP_SIZE=1g
      - ELASTICSEARCH_INGEST_GEOIP_DOWNLOADER_ENABLED=false
    volumes:
      - "./es/elasticsearch_node3_data:/bitnami"
    container_name: elasticsearch-node3
    networks:
      kafka_kafka_network:
        ipv4_address: 172.24.2.35

  kibana:
    image: docker.io/bitnami/kibana:8.1.2
    user: root
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - "./kibana.yml:/opt/bitnami/kibana/config/kibana.yml"
      - "./es/kibana_data:/bitnami/kibana"
    depends_on:
      - elasticsearch-node1
      - elasticsearch-node2
      - elasticsearch-node3
    container_name: kibana
#    environment:
#      - KIBANA_ELASTICSEARCH_URL=elasticsearch-node1
    networks:
      kafka_kafka_network:
        ipv4_address: 172.24.2.36

networks:
  kafka_kafka_network:
    external: true
```
network may need change yourself

2.write a kibana.yml like this:
```yaml
# For more configuration options see the configuration guide for Kibana in
# https://www.elastic.co/guide/index.html

# =================== System: Kibana Server ===================
# Kibana is served by a back end server. This setting specifies the port to use.
#server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
#server.host: "localhost"

# Enables you to specify a path to mount Kibana at if you are running behind a proxy.
# Use the `server.rewriteBasePath` setting to tell Kibana if it should remove the basePath
# from requests it receives, and to prevent a deprecation warning at startup.
# This setting cannot end in a slash.
#server.basePath: ""

# Specifies whether Kibana should rewrite requests that are prefixed with
# `server.basePath` or require that they are rewritten by your reverse proxy.
# Defaults to `false`.
#server.rewriteBasePath: false

# Specifies the public URL at which Kibana is available for end users. If
# `server.basePath` is configured this URL should end with the same basePath.
#server.publicBaseUrl: ""

# The maximum payload size in bytes for incoming server requests.
#server.maxPayload: 1048576

# The Kibana server's name. This is used for display purposes.
#server.name: "your-hostname"

# =================== System: Kibana Server (Optional) ===================
# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
#server.ssl.enabled: false
#server.ssl.certificate: /path/to/your/server.crt
#server.ssl.key: /path/to/your/server.key

# =================== System: Elasticsearch ===================
# The URLs of the Elasticsearch instances to use for all your queries.
#elasticsearch.hosts: ["http://localhost:9200"]

# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the Kibana
# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
#elasticsearch.username: "kibana_system"
#elasticsearch.password: "pass"

# Kibana can also authenticate to Elasticsearch via "service account tokens".
# Service account tokens are Bearer style tokens that replace the traditional username/password based configuration.
# Use this token instead of a username/password.
# elasticsearch.serviceAccountToken: "my_token"

# Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
# the elasticsearch.requestTimeout setting.
#elasticsearch.pingTimeout: 1500

# Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
# must be a positive integer.
#elasticsearch.requestTimeout: 30000

# Specifies whether Kibana should use compression for communications with elasticsearch
# Defaults to `false`.
#elasticsearch.compression: false

# List of Kibana client-side headers to send to Elasticsearch. To send *no* client-side
# headers, set this value to [] (an empty list).
#elasticsearch.requestHeadersWhitelist: [ authorization ]

# Header names and values that are sent to Elasticsearch. Any custom headers cannot be overwritten
# by client-side headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
#elasticsearch.customHeaders: {}

# Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
#elasticsearch.shardTimeout: 30000

# =================== System: Elasticsearch (Optional) ===================
# These files are used to verify the identity of Kibana to Elasticsearch and are required when
# xpack.security.http.ssl.client_authentication in Elasticsearch is set to required.
#elasticsearch.ssl.certificate: /path/to/your/client.crt
#elasticsearch.ssl.key: /path/to/your/client.key

# Enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
#elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
#elasticsearch.ssl.verificationMode: full

# =================== System: Logging ===================
# Set the value of this setting to off to suppress all logging output, or to debug to log everything. Defaults to 'info'
#logging.root.level: debug

# Enables you to specify a file where Kibana stores log output.
#logging.appenders.default:
#  type: file
#  fileName: /var/logs/kibana.log
#  layout:
#    type: json

# Logs queries sent to Elasticsearch.
#logging.loggers:
#  - name: elasticsearch.query
#    level: debug

# Logs http responses.
#logging.loggers:
#  - name: http.server.response
#    level: debug

# Logs system usage information.
#logging.loggers:
#  - name: metrics.ops
#    level: debug

# =================== System: Other ===================
# The path where Kibana stores persistent data not saved in Elasticsearch. Defaults to data
#path.data: data

# Specifies the path where Kibana creates the process ID file.
#pid.file: /run/kibana/kibana.pid

# Set the interval in milliseconds to sample system and process performance
# metrics. Minimum is 100ms. Defaults to 5000ms.
#ops.interval: 5000

# Specifies locale to be used for all localizable strings, dates and number formats.
# Supported languages are the following: English - en , by default , Chinese - zh-CN .
i18n.locale: "zh-CN"
# =================== Frequently used (Optional)===================

# =================== Saved Objects: Migrations ===================
# Saved object migrations run at startup. If you run into migration-related issues, you might need to adjust these settings.

# The number of documents migrated at a time.
# If Kibana can't start up or upgrade due to an Elasticsearch `circuit_breaking_exception`,
# use a smaller batchSize value to reduce the memory pressure. Defaults to 1000 objects per batch.
#migrations.batchSize: 1000

# The maximum payload size for indexing batches of upgraded saved objects.
# To avoid migrations failing due to a 413 Request Entity Too Large response from Elasticsearch.
# This value should be lower than or equal to your Elasticsearch cluster’s `http.max_content_length`
# configuration option. Default: 100mb
#migrations.maxBatchSizeBytes: 100mb

# The number of times to retry temporary migration failures. Increase the setting
# if migrations fail frequently with a message such as `Unable to complete the [...] step after
# 15 attempts, terminating`. Defaults to 15
#migrations.retryAttempts: 15

# =================== Search Autocomplete ===================
# Time in milliseconds to wait for autocomplete suggestions from Elasticsearch.
# This value must be a whole number greater than zero. Defaults to 1000ms
#data.autocomplete.valueSuggestions.timeout: 1000

# Maximum number of documents loaded by each shard to generate autocomplete suggestions.
# This value must be a whole number greater than zero. Defaults to 100_000
#data.autocomplete.valueSuggestions.terminateAfter: 100000
path:
  data: /bitnami/kibana/data
pid:
  file: /opt/bitnami/kibana/tmp/kibana.pid
server:
  host: 0.0.0.0
  port: 5601
elasticsearch:
  hosts: http://elasticsearch-node1:9200
```
3.dokcer-compose up -d
4.only "i18n.locale" is effective, "elasticsearch.hosts=elasticsearch-node1" will be converted to "elasticsearch" by default

### What is the expected behavior?

`elasticsearch.host` will change by mount kibana.yml 

### What do you see instead?

if enable this:
```yaml
#    environment:
#      - KIBANA_ELASTICSEARCH_URL=elasticsearch-node1
```
`elasticsearch.host` will change, but mount kibana.yml won't
