### ISSUE TITLE
[bitnami/redis] Why check if $REDIS_TLS_KEY_FILE_PASS  exists as a file path?

### ISSUE THREAD

**Issue by bdulive** [bitnami/containers#25764]
### Name and Version

bitnami/redis:6.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Below is my environment setting to enable TLS  in docker compose. 
Key file "server_key.pem" has passphrase "mypass". 
```
redis:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=redispass
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/server_certificate.pem
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/server_key.pem
      - REDIS_TLS_KEY_FILE_PASS=mypass
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca_certificate.pem
      - REDIS_TLS_AUTH_CLIENTS=no
  ......
```
When running compose, I get such error:
```
redis 07:25:02.06 INFO  ==> ** Starting Redis setup **
redis 07:25:02.10 ERROR ==> The passphrase for the private key file in the specified path mypass does not exist
```
I found this error message printed from libredis.sh:
```
if [[ -n "$REDIS_TLS_KEY_FILE_PASS" ]] && [[ ! -f "$REDIS_TLS_KEY_FILE_PASS" ]]; then
            print_validation_error "The passphrase for the private key file in the specified path ${REDIS_TLS_KEY_FILE_PASS} does not exist"
fi
```
$REDIS_TLS_KEY_FILE_PASS  is used to set "tls-key-file-pass".
```
! is_empty_value "$REDIS_TLS_KEY_FILE_PASS" && redis_conf_set tls-key-file-pass "$REDIS_TLS_KEY_FILE_PASS"
```
Per my understanding, REDIS_TLS_KEY_FILE_PASS is just a password.   Why check if it exists as a file path ?

### What do you see instead?
```
redis 07:25:02.06 INFO  ==> ** Starting Redis setup **
redis 07:25:02.10 ERROR ==> The passphrase for the private key file in the specified path mypass does not exist
```
