### ISSUE TITLE
[bitnami/kafka] Kraft Mode , SSL enabling on Controller

### ISSUE THREAD

**Issue by vishwaGitrepo** [bitnami/containers#25770]
### Name and Version

bitnami/kafka:3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are using the 3 on prem ubuntu VMs to run a container bitnami/kafka:3.3  on each node. We are using the kraft mode and enabled SSL on broker listener (used for clients and producers as well) and controller SSL, but facing issues with SSL on controller.
We are using this configuration,

![image](https://user-images.githubusercontent.com/86772132/222111677-bb12522d-d553-4040-9fd8-0c45bfb1bf77.png)

then we are getting this error in logs 
![image](https://user-images.githubusercontent.com/86772132/222112302-8e1e98aa-2d5b-4c12-a604-3f5b36150690.png)

but when we add this variable : -e KAFKA_CFG_LISTENER_NAME_CONTROLLER_SSL_CLIENT_AUTH=required 
we are getting this error 

![image](https://user-images.githubusercontent.com/86772132/222113817-e3dcccbb-b6fe-4a6e-bfa6-a3f66f19b925.png)

It kind of looks like SSL handshake error / unknow ca_unknown but the provided JKS keystore and Truststore are working fine for clients and producers and interbroker communication. so what are we missing here.Any help would be highly appreciated , Thanks.

### What is the expected behavior?

We are expecting the kafka running without any errors in logs.

### What do you see instead?

The above provided errors.

### Additional information

NA

**Comment by migruiz4** [comment]
Hi @vishwaGitrepo,

Could you please provide us with additional information so we can try to reproduce the issue?

It would be helpful if you could provide the `docker run` command in plaintext instead of image so we can copy it.

Additionally, it may be useful if you can share the content of your Kafka configuration inside the container, so we can have a look at it.

**Comment by migruiz4** [comment]
Hi @vishwaGitrepo,

I'm sorry for the late response.
Due to the complexity and customization of your use case, I haven't been able to reproduce the exact same conditions of your issue.

Although, in case it helps, I would like to share with you some of the deployments I have worked on, in case it helps you find the root cause your issue. 

In my scenarios, I will be using docker-compose to simplify the multiple VMs scenarios, although they could be easily converted to a `docker run` command like the one you shared.

<details>
  <summary>Minimum Kraft deployment using plaintext listener</summary>

```yaml
version: "2"
services:
  kafka1:
    image: docker.io/bitnami/kafka:3.4
    volumes:
      - "kafka1_data:/bitnami/kafka"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=76BLQI7sT_ql1mBfKsOk9Q
      #- KAFKA_CFG_SUPER_USERS="User:*"
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka2:
    image: docker.io/bitnami/kafka:3.4
    volumes:
      - "kafka2_data:/bitnami/kafka"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=76BLQI7sT_ql1mBfKsOk9Q
      #- KAFKA_CFG_SUPER_USERS="User:*"
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka3:
    image: docker.io/bitnami/kafka:3.4
    volumes:
      - "kafka3_data:/bitnami/kafka"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=76BLQI7sT_ql1mBfKsOk9Q
      #- KAFKA_CFG_SUPER_USERS="User:*"
      - ALLOW_PLAINTEXT_LISTENER=yes
volumes:
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local
```
</details>


<details>
  <summary>Minimum Kraft deployment using SSL listener</summary>


I generated my self-signed certificates using the following script:
```bash
#!/bin/bash
mkdir certs
# Root CA
echo "Creating CA certificate and key"
openssl req -new -x509 -keyout certs/ca.key -out certs/ca.crt -days 365 -subj "/CN=Sample CA/OU=US/O=US/ST=US/C=US" -passout pass:my_pass

echo "Creating Truststore"
keytool -keystore certs/kafka.truststore.jks -alias CARoot -import -file certs/ca.crt -storepass my_pass -keypass my_pass -noprompt

# Node certs
for i in {1..3}; do
    mkdir certs/node-$i
    echo "Creating node key"
    keytool -keystore certs/node-$i/kafka.keystore.jks -alias kafka$i -validity 365 -genkey -keyalg RSA -dname "cn=kafka$i, ou=US, o=US, c=US" -storepass my_pass -keypass my_pass
    echo "Creating certificate sign request"
    keytool -keystore certs/node-$i/kafka.keystore.jks -alias kafka$i -certreq -file certs/node-$i/tls.srl -storepass my_pass -keypass my_pass
    echo "Signing certificate request using self-signed CA"
    openssl x509 -req -CA certs/ca.crt -CAkey certs/ca.key \
        -in certs/node-$i/tls.srl -out certs/node-$i/tls.crt \
        -days 365 -CAcreateserial \
        -passin pass:my_pass
    echo "Adding Ca certificate to the keystore"
    keytool -keystore certs/node-$i/kafka.keystore.jks -alias CARoot -import -file certs/ca.crt -storepass my_pass -keypass my_pass -noprompt
    echo "Adding signed certificate"
    keytool -keystore certs/node-$i/kafka.keystore.jks -alias kafka$i -import -file certs/node-$i/tls.crt -storepass my_pass -keypass my_pass -noprompt

    cp "certs/kafka.truststore.jks" "certs/node-$i/kafka.truststore.jks"
    # Cleanup
    rm certs/node-$i/tls.crt certs/node-$i/tls.srl
done

rm certs/kafka.truststore.jks

```

docker-compose.yaml

```yaml
version: "2"
services:
  kafka1:
    image: docker.io/bitnami/kafka:3.4
    volumes:
      - "kafka1_data:/bitnami/kafka"
      - "./certs/node-1:/opt/bitnami/kafka/config/certs"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,SSL:SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=76BLQI7sT_ql1mBfKsOk9Q
      #- KAFKA_CFG_SUPER_USERS="User:*"
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SSL
      - KAFKA_CFG_SECURITY_PROTOCOL=SSL
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=my_pass
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=my_pass
      - KAFKA_CFG_SSL_KEY_PASSWORD=my_pass
  kafka2:
    image: docker.io/bitnami/kafka:3.4
    volumes:
      - "kafka2_data:/bitnami/kafka"
      - "./certs/node-2:/opt/bitnami/kafka/config/certs"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,SSL:SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka2:9092
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=76BLQI7sT_ql1mBfKsOk9Q
      #- KAFKA_CFG_SUPER_USERS="User:*"
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SSL
      - KAFKA_CFG_SECURITY_PROTOCOL=SSL
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=my_pass
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=my_pass
      - KAFKA_CFG_SSL_KEY_PASSWORD=my_pass
  kafka3:
    image: docker.io/bitnami/kafka:3.4
    volumes:
      - "kafka3_data:/bitnami/kafka"
      - "./certs/node-3:/opt/bitnami/kafka/config/certs"
    environment:
      - BITNAMI_DEBUG=yes
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,SSL:SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka3:9092
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=76BLQI7sT_ql1mBfKsOk9Q
      #- KAFKA_CFG_SUPER_USERS="User:*"
      - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SSL
      - KAFKA_CFG_SECURITY_PROTOCOL=SSL
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=my_pass
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=my_pass
      - KAFKA_CFG_SSL_KEY_PASSWORD=my_pass
volumes:
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local

```
</details>
