### ISSUE TITLE
[bitnami/rabbitmq] persistence not working with a docker named volume

### ISSUE THREAD

**Issue by lc-guy** [bitnami/containers#25799]
### Name and Version

bitnami/rabbitmq:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using the compose settings provided in [the documentation](https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#persisting-your-application), substituting the host volume with a named volume: 

```yaml
  rabbitmq:
    image: bitnami/rabbitmq
    restart: unless-stopped
    ports:
      - '15672:15672'
    environment:
      - "RABBITMQ_PLUGINS=rabbitmq_prometheus,rabbitmq_management"
    volumes:
      - rabbitmq_storage:/bitnami
    networks:
      - service_network
```

### What is the expected behavior?

We should see vhosts, users, queues, ... persist across restarts.

### What do you see instead?

Queues, vhosts, etc are not persisted. Indeed:

```
I have no name!@60b54c54e1eb:/bitnami/rabbitmq$ ls -l
total 4
drwxr-xr-x 2 root root 4096 Mar  1 09:41 conf
-rwxr-xr-x 1 root root    0 Mar  1 09:41 load_definitions.json
lrwxrwxrwx 1 root root   24 Feb 26 23:13 mnesia -> /var/lib/rabbitmq/mnesia
```

The mnesia folder, which contains the node data, is a symbolic link to another folder in /var/lib/rabbitmq, which is not persisted.
