### ISSUE TITLE
[bitnami/schema-registry] Doesn't support Kraft mode

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/containers#25807]
### Name and Version

bitnami/schema-registry:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Trying to launch a cluster with kafka brokers set as kraft, will result in schema registry not seeing the brokers.
This is the docker-compose.yml file

```
version: "3"
services:

  broker-1:
    image: 'bitnami/kafka:latest'
    container_name: broker-1
    ports:
      - '9092:29092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=A370i42nQuCtnpFN-7I41Q
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093,2@broker-2:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka

  broker-2:
    image: 'bitnami/kafka:latest'
    container_name: broker-2
    ports:
      - '9094:29094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=A370i42nQuCtnpFN-7I41Q
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095,EXTERNAL://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9094
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093,2@broker-2:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka

  schemaregistry:
    image: bitnami/schema-registry
    container_name: schema-registry
    depends_on:
      - broker-1
      - broker-2
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://localhost:9092,PLAINTEXT://localhost:9094
      - SCHEMA_REGISTRY_KAFKA_BOOTSTRAP_SERVERS=broker-1:9092,broker-2:9094
      - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    ports:
      - 8081:8081
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
```

### What is the expected behavior?

From the confluent documentation it should worl like this:

substituting: **SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181**
with: **SCHEMA_REGISTRY_KAFKA_BOOTSTRAP_SERVERS=broker-1:9092,broker-2:9094**

### What do you see instead?

Everythin boots up, but after some time I get this:
```
schema-registry  | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
schema-registry exited with code 1
```
