### ISSUE TITLE
[bitnami/kafka] Kraft crashing when setting up secure connection PEM

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/containers#26067]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Trying to spin up kafka in kraft mode securely ends up crashing.
I'm quite puzzed honestly, I'm following the documentation word for word but something isn't working.

This is my docker-compose.yml
```
version: '2'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=A370i42nQuCtnpFN-7I41Q
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_SSL,SASL_SSL:SASL_SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CERTIFICATE_PASSWORD=pasS123
      - KAFKA_TLS_TYPE=PEM
    volumes:
      - './kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      - './kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      - './kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
```

this is the structure of foder where I have the docker-compose file and certificates
```
.
├── docker-compose.yml
├── kafka.keystore.key
├── kafka.keystore.pem
└── kafka.truststore.pem

0 directories, 4 files
```

### What is the expected behavior?

It should boot up securely, I can't unserstand what is going wrong. Is it an issue if the certs are not inside a specific folder on the host? It shoudln't right? Am I mixing up the public and private key set up? 
My private key is kakfa.keystore.pem, while the public one is kafka.keystore.key. Is that right?

### What do you see instead?

Unfortunatly not many details to provide, these are all the logs I get before the container crashes.
```
kafka  | kafka 11:26:57.19 
kafka  | kafka 11:26:57.19 Welcome to the Bitnami kafka container
kafka  | kafka 11:26:57.19 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka  | kafka 11:26:57.20 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka  | kafka 11:26:57.20 
kafka  | kafka 11:26:57.20 INFO  ==> ** Starting Kafka setup **
kafka  | kafka 11:26:57.42 INFO  ==> Initializing Kafka...
kafka  | kafka 11:26:57.46 INFO  ==> No injected configuration files found, creating default config files
kafka  | kafka 11:26:57.80 INFO  ==> Initializing KRaft...
kafka  | kafka 11:26:57.81 INFO  ==> Formatting storage directories to add metadata...
kafka exited with code 1
```

### Additional information

I really like using you guys' images. I hope you can help me figure this one out
