### ISSUE TITLE
[bitnami/alertmanager] Alert Manger unable to persist

### ISSUE THREAD

**Issue by MengDanzz** [bitnami/containers#26680]
### Name and Version

bitnami/alertmanager:0.25.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use docker-compose create an alertmanager container and run .
```
  alertmanager:
    build: ./alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertdata/:/opt/bitnami/data
 ```
2. Silence an alarm from web frontend.
3. Restart.
4. Silenced alarm not exist, and ./alertdata dir is empty

### What is the expected behavior?

Silenced alarms should be persisted and `./alertdata` should not be empty. 

### What do you see instead?

Silenced alarms not persisted and `./alertdata` is empty.
