### ISSUE TITLE
[bitnami/kafka] Certain configuration exits container without error message

### ISSUE THREAD

**Issue by tfrokt** [bitnami/containers#26784]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

ARM64 (M1)

### What steps will reproduce the bug?

I tried to follow "[Accessing Apache Kafka with internal and external clients](https://hub.docker.com/r/bitnami/kafka)" to connect to Kafka from the docker environment as well as localhost. Tinkering with the variables, I came up with the following which exits the container without error: `streaming_examples-kafka-1 exited with code 1`

**docker-compose.yml**

```
version: "3"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'

    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9094
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
```

Related on [SO](https://stackoverflow.com/questions/75680387/access-bitnami-kafka-docker-container-from-everywhere).

### What is the expected behavior?

To see an error message.

### What do you see instead?

Container exits

### Additional information

https://stackoverflow.com/questions/75680387/access-bitnami-kafka-docker-container-from-everywhere
