### ISSUE TITLE
bitnami/logstash issues

### ISSUE THREAD

**Issue by tessierp** [bitnami/containers#26800]
### Name and Version

bitnami/logstash:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,

Here are a few issues I am experiencing with bitnami/logstash. I have deployed an ELK stack using Virtualbox and a NAT network. The network has only 1 VM where I deployed bitnami's kibana, elasticsearch and logstash. I am able to communicate with the VM from the host with port forwarding. All ports that I need have been forwarded as well (mainly portainer (9000), kibana (5601), elasticsearch (9200) and SSH (22).

my vm's hosts file has the basic entry

127.0.0.1     localhost
127.0.1.1     elk.mydomain.net   elk

my docker compose file has the following

```yaml
---
version: "3.8"
services:
  elasticsearch:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 100
        delay: 60s
        window: 60s
    depends_on:
      - logstash
    image: 'bitnami/elasticsearch:latest'
    environment:
      - PUID=998
      - PGID=998
      - TZ=America/Toronto
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - sysmon-net

  kibana:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 100
        delay: 90s
        window: 90s
    depends_on:
      - elasticsearch
    image: 'bitnami/kibana:latest'
    environment:
      - PUID=998
      - PGID=998
      - TZ=America/Toronto
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    volumes:
      - kibana-data:/bitnami/kibana
      - kibana-config:/bitnami/kibana/conf
    ports:
      - 5601:5601
    networks:
      - sysmon-net

  logstash:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 100
        delay: 30s
        window: 30s
    image: 'bitnami/logstash:latest'
    environment:
      - PUID=1001
      #- PUID=998
      - PGID=998
      - TZ=America/Toronto
      - LOGSTASH_EXPOSE_API=yes
      - LOGSTASH_API_PORT_NUMBER=9090
      - LOGSTASH_PIPELINE_CONF_FILENAME=pipelines.conf
      - LOGSTASH_ENABLE_MULTIPLE_PIPELINES=true
      - LOGSTASH_PLUGINS=logstash-integration-jdbc
    volumes:
      - logstash-data:/bitnami
      - logstash-config:/bitnami/logstash/config
      - logstash-pipeline:/bitnami/logstash/pipeline
      - /opt/bitnami/plugins/drivers/mssql:/bitnami/logstash/plugins/jdbc/drivers/mssql
    ports:
      - 9600:9600
      - 9090:9090
    networks:
      - sysmon-net

volumes:
  logstash-data:
    external: true
  logstash-config:
    external: true
  logstash-pipeline:
    external: true
  elasticsearch-data:
    external: true
  kibana-data:
    external: true
  kibana-config:
    external: true

networks:
  sysmon-net:
    driver: overlay
    attachable: true
```
And one of my pipelines has the following output defined

```
output {
  elasticsearch {
    # APP
    id => "elk_test"

    hosts => ["elk.mydomain.net:9200"]
    #user => "elastic"
    #password => "somepassword"
    index => "elk_test-%{+YYYY.MM}"
}
```

The issue I have is that logstash fails to connect to elastichsearch on port 9200. My guess is, it doesn't know how to resolve elk.mydomain.net. I have tried to login to the logstash container to ping however ping is not installed, curl neither... apt doesn't seem to work so I couldn't install them to verify.

From the VM, if I execute `curl elk.mydomain.net:9200`, I get a response from elasticsearch.

I am not 100% sure this is a bug, could be a config issue. If any of you have any idea, I would appreciate the input.

Thanks

### What is the expected behavior?

Would expect logstash to be able to connect to elasticsearch. The inability for me to ping from the container to see if that is possible makes it very difficult to troubleshoot what is going on.

### What do you see instead?

Connection to elasticsearch on port 9200.
