### ISSUE TITLE
[bitnami/kafka] Missing errors in logs output

### ISSUE THREAD

**Issue by falconepl** [bitnami/containers#26882]
### Name and Version

bitnami/kafka:3.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Let's assume that we have the following `docker-compose.yaml` file:
```yaml
services:
  kafka:
    image: docker.io/bitnami/kafka:3.4.0
    hostname: kafka
    ports:
      - "19092:19092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://127.0.0.1:19092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    driver: local
```

It is similar to what we can see in exemplary configuration for [Kafka without Zookeeper (KRaft)](https://github.com/bitnami/containers/tree/main/bitnami/kafka#kafka-without-zookeeper-kraft)

### What do you see instead?

We see is the following output when trying to run the container:
```sh
$ docker-compose up --detach; docker-compose logs -f
[+] Running 3/3
 ⠿ Network bitnami-kafka-kraft_default      Created                                                                                                                          0.1s
 ⠿ Volume "bitnami-kafka-kraft_kafka_data"  Created                                                                                                                          0.0s
 ⠿ Container bitnami-kafka-kraft-kafka-1    Started                                                                                                                          0.4s
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.01
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.01 Welcome to the Bitnami kafka container
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.01 Subscribe to project updates by watching https://github.com/bitnami/containers
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.02 Submit issues and feature requests at https://github.com/bitnami/containers/issues
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.02
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.02 INFO  ==> ** Starting Kafka setup **
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.09 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.10 INFO  ==> Initializing Kafka...
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.11 INFO  ==> No injected configuration files found, creating default config files
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.29 INFO  ==> Initializing KRaft...
bitnami-kafka-kraft-kafka-1  | kafka 12:15:04.30 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
bitnami-kafka-kraft-kafka-1  | kafka 12:15:05.84 INFO  ==> Generated Kafka cluster ID 'QBlrEVIjSUOYpc3yCWX9DA'
bitnami-kafka-kraft-kafka-1  | kafka 12:15:05.84 INFO  ==> Formatting storage directories to add metadata...
bitnami-kafka-kraft-kafka-1 exited with code 1
```

As you can see, we get multiple `INFO` and `WARN` logs, but no `ERROR` log with extra details on why container has finished with non-zero exit code.

My guess is that the container fails because `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP` contains `CONNECTIONS_FROM_HOST:PLAINTEXT`. It might not be recognized as a valid value by the scripts provided by Bitnami for Kafka. However, when looking at [libkafka.sh](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh) it seems that we should expect some extra error details before the container exits

### Additional information

The unusual `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP` and `KAFKA_CFG_ADVERTISED_LISTENERS` values from the `docker-compose.yaml` file were introduce in my configuration in order to setup [UI for Apache Kafka](https://github.com/provectus/kafka-ui) using Docker, along with Bitnami's Kafka.

My Docker Compose configuration is similar to what _UI for Apache Kafka_ suggests to use in one of their exemplary configurations - like [kafka-ui.yaml](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui.yaml). The only difference is that they use `PLAINTEXT_HOST` in `KAFKA_LISTENER_SECURITY_PROTOCOL_MAP` instead of `CONNECTIONS_FROM_HOST`.

As far as I understand, _UI for Apache Kafka_ needs those specific settings if we have both Kafka and _UI for Apache Kafka_ containers in Docker, but we still want to use Kafka from an application running locally outside of Docker. It seems that it is a similar case to the [Kafka in Docker container with a client running locally](https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/#scenario-4) scenario described on Confluent's blog

**Comment by javsalgar** [comment]
Hi,

Could you launch it with `BITNAMI_DEBUG=true`  in the env vars?

**Comment by falconepl** [comment]
I didn't know that option. Thank you @javsalgar 🙂 So yes - it seems that it's actually an issue with `KAFKA_CFG_ADVERTISED_LISTENERS`, as expected:

```sh
$ docker-compose up --detach; docker-compose logs -f
[+] Running 3/3
 ⠿ Network bitnami-kafka-kraft_default      Created                                                                                                                          0.0s
 ⠿ Volume "bitnami-kafka-kraft_kafka_data"  Created                                                                                                                          0.0s
 ⠿ Container bitnami-kafka-kraft-kafka-1    Started                                                                                                                          0.4s
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.10
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.10 Welcome to the Bitnami kafka container
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.10 Subscribe to project updates by watching https://github.com/bitnami/containers
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.11
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.11 INFO  ==> ** Starting Kafka setup **
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.17 DEBUG ==> Validating settings in KAFKA_* env vars...
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.18 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.19 INFO  ==> Initializing Kafka...
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.20 INFO  ==> No injected configuration files found, creating default config files
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.37 INFO  ==> Initializing KRaft...
bitnami-kafka-kraft-kafka-1  | kafka 11:43:24.37 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
bitnami-kafka-kraft-kafka-1  | kafka 11:43:25.86 INFO  ==> Generated Kafka cluster ID 'ZLT723KeQTOB031KfGZuCw'
bitnami-kafka-kraft-kafka-1  | kafka 11:43:25.86 INFO  ==> Formatting storage directories to add metadata...
bitnami-kafka-kraft-kafka-1  | Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: advertised.listeners listener names must be equal to or a subset of the ones defined in listeners. Found PLAINTEXT,CONNECTIONS_FROM_HOST. The valid options based on the current configuration are PLAINTEXT,CONTROLLER
bitnami-kafka-kraft-kafka-1  | 	at scala.Predef$.require(Predef.scala:281)
bitnami-kafka-kraft-kafka-1  | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2268)
bitnami-kafka-kraft-kafka-1  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2107)
bitnami-kafka-kraft-kafka-1  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1533)
bitnami-kafka-kraft-kafka-1  | 	at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
bitnami-kafka-kraft-kafka-1  | 	at scala.Option.flatMap(Option.scala:271)
bitnami-kafka-kraft-kafka-1  | 	at kafka.tools.StorageTool$.main(StorageTool.scala:41)
bitnami-kafka-kraft-kafka-1  | 	at kafka.tools.StorageTool.main(StorageTool.scala)
bitnami-kafka-kraft-kafka-1 exited with code 1
```

Shouldn't it be a bit less restrictive? It looks like with `PLAINTEXT` and `CONTROLLER` as the only allowed values, it is not possible to set [kafka-ui](https://github.com/provectus/kafka-ui) up with Bitnami Apache Kafka container - assuming that I am not missing something here

**Comment by fmulero** [comment]
The error is suggesting to configure the `CONNECTIONS_FROM_HOST` listener, because you can not advertise a listener that is not configured. Have you try this?

```yaml
services:
  kafka:
    image: docker.io/bitnami/kafka:3.4.0
    hostname: kafka
    ports:
      - "19092:19092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,CONNECTIONS_FROM_HOST://:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://127.0.0.1:19092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
    driver: local
```

For questions/doubts about Kafka configuration please refer to the [upstream project](https://kafka.apache.org/project)
