### ISSUE TITLE
[bitnami/redis-cluster] Need a way to send config options via command line

### ISSUE THREAD

**Issue by LRagji** [bitnami/containers#27524]
### Name and Version

[bitnami/redis-cluster]:latest

### What is the problem this feature will solve?

It will help in not creating config files for changes... and the headache of attaching them via volume mount.
Also, it's a base feature exposed by redis server to pass options via CLI.

### What is the feature you are proposing to solve the problem?

```yaml
  hb-lru-redis:
    image: "redis:latest"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2.5GB
        reservations:
          cpus: '0.25'
          memory: 2GB
    command: redis-server --maxmemory 2000mb --save "" --maxmemory-policy allkeys-lru
```

As you can see with a normal redis image I can pass the cli options like save maxmemory etc without mounting a config file I request something similar.

### What alternatives have you considered?

Added separate config files, but that's too complex to upkeep, mount and maintain
