### ISSUE TITLE
Unable to run a php application

### ISSUE THREAD

**Issue by TheFrankman** [bitnami/containers#27525]
### Name and Version

bitnami/apache:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Create a blank laravel project

Create docker-compose like so : 

```yaml
        app:
        build:
            context: "build"
            dockerfile: Dockerfile
        image: recorder-v2
        privileged: true
        user: root
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        env_file:
            - './.env'
        volumes:
            - './:/app'
    apache:
        image: 'bitnami/apache:latest'
        build:
            context: apache
            dockerfile: Dockerfile
        ports:
            - '80:8080'
            - '443:8443'
        volumes:
            - './:/app'
            - './apache/apache2.conf:/vhosts/my_vhost.conf:ro'
            - './apache/ssl:/certs'
            - './apache/logs:/usr/local/apache2/logs/'
```

example apache config : 

```
#LoadModule php_module /path/to/php/modules/libphp.so
#LoadModule php_module modules/libphp.so

ServerName recorder-v2-local.sharp-stream.com

<VirtualHost *:8080>
    Header set Access-Control-Allow-Origin "*"
    ServerAdmin support@example.com
    ServerName your-server-name.com
    DocumentRoot /app/public

    DirectoryIndex index.php

    <Directory /app/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        RewriteEngine On
        RewriteBase /
        RewriteRule ^(.*)$ public/index.php/$1 [L]
    </Directory>

</VirtualHost>

<VirtualHost *:8443>
    Header set Access-Control-Allow-Origin "*"
    ServerAdmin support@example.com
    ServerName your-server-name.com
    DocumentRoot /app/public

    DirectoryIndex index.php

    <Directory /app/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        RewriteEngine On
        RewriteBase /
        RewriteRule ^(.*)$ public/index.php/$1 [L]
        Require all granted
    </Directory>

   #LoadModule ssl_module modules/mod_ssl.so
   SSLEngine On
   SSLCertificateFile "/certs/mypem.pem"
   SSLCertificateKeyFile "/certs/mypem.pem"
   SSLCertificateChainFile ""/certs/mypem.pem"

</VirtualHost>

```

you get the gist. In any case, mod_php is not installed by default. I've been doing some playing around with the dockerfile but I'm having no luck with it. for example : 

```dockerfile
FROM bitnami/apache

ARG php_version="8.1"

USER 0

RUN apt-get update
RUN apt-get install -y software-properties-common wget gnupg-agent gnupg2

RUN wget https://packages.sury.org/php/apt.gpg
RUN apt-key add apt.gpg

RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list
RUN apt update
RUN apt-get install libapache2-mod-php$php_version
RUN apt install -y php-dev php$php_version-cli php$php_version-cli php$php_version-common php$php_version-mysql php$php_version-sqlite3 php$php_version-xml php$php_version-bcmath php$php_version-mbstring php$php_version-curl php$php_version-zip php$php_version-redis php$php_version-xdebug

USER 1001
```

When I run `httpd -t -D DUMP_MODULES` there is no mod_php.

### What is the expected behavior?

I'm not expecting this to work out of the box but I'm out of ideas. I'm not a sysadmin and my docker knowledge is limited. Is it possible to get some documentation on serving a php application as i'd imagine this is pretty standard for this container.

Maybe I'm missing the point.

### What do you see instead?

My application does not run php, I just see the raw file, which is to be expected as although php is installed i.e. I can do a php -v apache isn't using it.
