### ISSUE TITLE
bitnami/moodle:latest - WSL2 Docker Desktop config.php not found when using named volume

### ISSUE THREAD

**Issue by DerMagereStudent** [bitnami/containers#28135]
### Name and Version

bitnami/moodle:4.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Create and run the following docker-compose.yml. Change the volume path if you want

```yaml
version: '3.8'
services:
  mariadb:
    image: mariadb
    volumes:
      - moodle_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
  moodle:
    image: bitnami/moodle:latest
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodle_app:/bitnami/moodle
      - moodle_data:/bitnami/moodledata
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb

volumes:
  moodle_db:
    driver: local
    driver_opts:
      type: none
      device: "D:\\Docker\\Moodle\\Database"
      o: bind
    name: moodle_db
  moodle_app:
    driver: local
    driver_opts:
      type: none
      device: "D:\\Docker\\Moodle\\Moodle"
      o: bind
    name: moodle_app
  moodle_data:
    driver: local
    driver_opts:
      type: none
      device: "D:\\Docker\\Moodle\\MoodleData"
      o: bind
    name: moodle_data
```

### What is the expected behavior?

I would expect the moodle install script to run and finish successfully as it does when specifying the volume within the service

```yaml
volumes:
      - D:\\Docker\\Moodle\\Moodle:/bitnami/moodle
      - D:\\Docker\\Moodle\\MoodleData:/bitnami/moodledata
```

### What do you see instead?

Instead, I always get an error that the file config.php does not exist:

```
moodle-test-moodle-1   | moodle 16:04:14.05 
moodle-test-moodle-1   | moodle 16:04:14.05 Welcome to the Bitnami moodle container
moodle-test-moodle-1   | moodle 16:04:14.05 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle-test-moodle-1   | moodle 16:04:14.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle-test-moodle-1   | moodle 16:04:14.05 
moodle-test-moodle-1   | moodle 16:04:14.05 INFO  ==> ** Starting Moodle setup **
moodle-test-moodle-1   | realpath: /bitnami/apache/conf: No such file or directory
moodle-test-moodle-1   | moodle 16:04:14.08 INFO  ==> Configuring Apache ServerTokens directive
moodle-test-moodle-1   | moodle 16:04:14.10 INFO  ==> Configuring PHP options
moodle-test-moodle-1   | moodle 16:04:14.10 INFO  ==> Setting PHP expose_php option
moodle-test-moodle-1   | moodle 16:04:14.12 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle-test-moodle-1   | moodle 16:04:14.13 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle-test-moodle-1   | moodle 16:04:14.19 INFO  ==> Restoring persisted Moodle installation
moodle-test-moodle-1   | moodle 16:04:16.25 INFO  ==> Trying to connect to the database server
moodle-test-moodle-1   | grep: /opt/bitnami/moodle/config.php: No such file or directory
moodle-test-moodle-1 exited with code 2
```

This error does also exist when I create a custom Dockerfile where I copy a custom config.php into the specified location:

```Dockerfile
FROM bitnami/moodle:4.1.2

COPY ./container_data/config.php /opt/bitnami/moodle/
```

config.php:
```php
<?php

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'mariadb';
$CFG->dbname    = 'moodle';
$CFG->dbuser    = 'root';
$CFG->dbpass    = 'moodle';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => 3306,
  'dbsocket' => '',
  'dbcollation' => 'utf8mb4_general_ci',
);

if (empty($_SERVER['HTTP_HOST'])) {
  $_SERVER['HTTP_HOST'] = '127.0.0.1:8080';
}
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
  $CFG->wwwroot   = 'https://' . $_SERVER['HTTP_HOST'];
} else {
  $CFG->wwwroot   = 'http://' . $_SERVER['HTTP_HOST'];
}
$CFG->dataroot  = '/bitnami/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 02775;

require_once(__DIR__ . '/lib/setup.php');
```

### Additional information

I need the named volumes at least for the moodle location because I have to copy files into this volume when the image is built. Into the location `/bitnami/moodle/local`.
