### ISSUE TITLE
[bitnami/redis] Configuration with `REDIS_SENTINEL_HOST` fails

### ISSUE THREAD

**Issue by rassie** [bitnami/containers#29020]
### Name and Version

bitnami/redis:7.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create the following `docker-compose.yaml`: 
```yaml
---
version: "2.3"
services:
    redis-master:
        image: "bitnami/redis:latest"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_REPLICATION_MODE=master

    redis-sentinel:
        image: "bitnami/redis-sentinel:latest"
        scale: 3
        environment:
            - REDIS_MASTER_SET=default
            - REDIS_MASTER_PORT_NUMBER=6379
            - REDIS_MASTER_HOST=redis-master

    redis-replica:
        image: "bitnami/redis:latest"
        scale: 3
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_REPLICATION_MODE=replica
            - REDIS_SENTINEL_HOST=redis-sentinel
            - REDIS_SENTINEL_MASTER_NAME=default
```
2. Start services with `docker-compose up`

### What is the expected behavior?

Services start cleanly and a cluster is constructed.

### What do you see instead?

Observe `/opt/bitnami/scripts/libredis.sh: line 265: REDIS_SENTINEL_INFO[1]: unbound variable` in the logs of `redis-replica`.

### Additional information

This problem occurs in the following block in `libredis.sh` (which also appears in `redis-cluster`, which doesn't work together with Sentinel):

```bash
if [[ -n "$REDIS_SENTINEL_HOST" ]]; then
    local -a sentinel_info_command=("redis-cli" "-h" "${REDIS_SENTINEL_HOST}" "-p" "${REDIS_SENTINEL_PORT_NUMBER}")
    is_boolean_yes "$REDIS_TLS_ENABLED" && sentinel_info_command+=("--tls" "--cert" "${REDIS_TLS_CERT_FILE}" "--key" "${REDIS_TLS_KEY_FILE}" "--cacert" "${REDIS_TLS_CA_FILE}")
    sentinel_info_command+=("sentinel" "get-master-addr-by-name" "${REDIS_SENTINEL_MASTER_NAME}")
    read -r -a REDIS_SENTINEL_INFO <<< "$("${sentinel_info_command[@]}")"
    REDIS_MASTER_HOST=${REDIS_SENTINEL_INFO[0]}
    REDIS_MASTER_PORT_NUMBER=${REDIS_SENTINEL_INFO[1]}
fi
```

The line `read -r -a ...` only works if the output of `sentinel_info_command` is separated by spaces, e.g. `127.0.0.1 6379`. Instead, `redis-cli` outputs the IP and the port on separate lines:
```
127.0.0.1
6379
```
Therefore, the array `REDIS_SENTINEL_INFO` is missing its second element. 

A fix could be as simple as fixing the `read` line to look like this, but there are certainly more elegant solutions:
```
read -r -a REDIS_SENTINEL_INFO <<< "$("${sentinel_info_command[@]}" | tr '\n' ' ')"
```
