### ISSUE TITLE
[bitname/redis-cluster] create redis cluster failed using environment REDIS_CLUSTER_ANNOUNCE_IP in a single node

### ISSUE THREAD

**Issue by jeffqiu1989** [bitnami/containers#29382]
### Name and Version

bitname/redis-cluster:7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have created a redis cluster in a single node for testing , this yaml file worked well in a few days ago, but now it failed
I want to connect redis from another host ,so i set these environments prefix with `REDIS_CLUSTER_ANNOUNCE_` 

```yaml
name: cluster
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
      - REDIS_CLUSTER_ANNOUNCE_PORT=7000
      - REDIS_CLUSTER_ANNOUNCE_IP=10.150.36.72 # host ip address
      - REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17000
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005
    ports:
      - 7000:7000
      - 17000:17000

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7001
      - REDIS_CLUSTER_ANNOUNCE_PORT=7001
      - REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17001
      - REDIS_CLUSTER_ANNOUNCE_IP=10.150.36.72
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005
    ports:
      - 7001:7001
      - 17001:17001

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7002
      - REDIS_CLUSTER_ANNOUNCE_PORT=7002
      - REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17002
      - REDIS_CLUSTER_ANNOUNCE_IP=10.150.36.72
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005
    ports:
      - 7002:7002
      - 17002:17002

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7003
      - REDIS_CLUSTER_ANNOUNCE_PORT=7003
      - REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17003
      - REDIS_CLUSTER_ANNOUNCE_IP=10.150.36.72
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005
    ports:
      - 7003:7003
      - 17003:17003

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7004
      - REDIS_CLUSTER_ANNOUNCE_PORT=7004
      - REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17004
      - REDIS_CLUSTER_ANNOUNCE_IP=10.150.36.72
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005
    ports:
      - 7004:7004
      - 17004:17004

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on: 
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_PORT_NUMBER=7005
      - REDIS_CLUSTER_ANNOUNCE_PORT=7005
      - REDIS_CLUSTER_ANNOUNCE_BUS_PORT=17005
      - REDIS_CLUSTER_ANNOUNCE_IP=10.150.36.72
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_NODES=redis-node-0:7000 redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005
      - REDIS_CLUSTER_CREATOR=yes
    ports:
      - 7005:7005
      - 17005:17005

volumes:
  redis-cluster_data-0:
  redis-cluster_data-1:
  redis-cluster_data-2:
  redis-cluster_data-3:
  redis-cluster_data-4:
  redis-cluster_data-5:
```

### What do you see instead?

node 1 logs
```
2023-04-07 10:10:06 cluster-redis-node-1-1  | redis-cluster 02:10:06.12 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
2023-04-07 10:10:06 cluster-redis-node-1-1  | redis-cluster 02:10:06.12 INFO  ==> Initializing Redis
2023-04-07 10:10:06 cluster-redis-node-1-1  | redis-cluster 02:10:06.16 INFO  ==> Setting Redis config file
2023-04-07 10:10:06 cluster-redis-node-1-1  | 
2023-04-07 10:10:06 cluster-redis-node-1-1  | redis-cluster 02:10:06.20 INFO  ==> ** Redis setup finished! **
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:C 07 Apr 2023 02:10:06.218 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:C 07 Apr 2023 02:10:06.218 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:C 07 Apr 2023 02:10:06.218 # Configuration loaded
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.219 * monotonic clock: POSIX clock_gettime
2023-04-07 10:10:05 cluster-redis-node-0-1  | 1:M 07 Apr 2023 02:10:05.943 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
2023-04-07 10:10:05 cluster-redis-node-0-1  | 1:M 07 Apr 2023 02:10:05.943 * Ready to accept connections
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.219 * No cluster configuration found, I'm 9bc1838495b938e25f73447a76d710fea978d946
2023-04-07 10:10:06 cluster-redis-node-0-1  | 1:M 07 Apr 2023 02:10:06.510 # configEpoch set to 1 via CLUSTER SET-CONFIG-EPOCH
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.221 * Running mode=cluster, port=7001.
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.221 # Server initialized
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.223 * Creating AOF base file appendonly.aof.1.base.rdb on server start
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.224 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.224 * Ready to accept connections
2023-04-07 10:10:06 cluster-redis-node-1-1  | 1:M 07 Apr 2023 02:10:06.510 # configEpoch set to 2 via CLUSTER SET-CONFIG-EPOCH
```

node 5 logs
```
cluster-redis-node-5-1  | redis-cluster 02:10:06.34
cluster-redis-node-5-1  | redis-cluster 02:10:06.34 Welcome to the Bitnami redis-cluster container
cluster-redis-node-5-1  | redis-cluster 02:10:06.34 Subscribe to project updates by watching https://github.com/bitnami/containers
cluster-redis-node-5-1  | redis-cluster 02:10:06.34 Submit issues and feature requests at https://github.com/bitnami/containers/issues
cluster-redis-node-5-1  | redis-cluster 02:10:06.35
cluster-redis-node-5-1  | redis-cluster 02:10:06.35 INFO  ==> ** Starting Redis setup **
cluster-redis-node-5-1  | redis-cluster 02:10:06.36 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
cluster-redis-node-5-1  | redis-cluster 02:10:06.36 INFO  ==> Initializing Redis
cluster-redis-node-5-1  | redis-cluster 02:10:06.37 INFO  ==> Setting Redis config file
cluster-redis-node-5-1  |
cluster-redis-node-5-1  | redis-cluster 02:10:06.41 INFO  ==> ** Redis setup finished! **
cluster-redis-node-5-1  | 41:C 07 Apr 2023 02:10:06.424 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cluster-redis-node-5-1  | 41:C 07 Apr 2023 02:10:06.424 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=41, just started
cluster-redis-node-5-1  | 41:C 07 Apr 2023 02:10:06.424 # Configuration loaded
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.424 * monotonic clock: POSIX clock_gettime
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.425 * No cluster configuration found, I'm 72f6c19d2c1401cd70114f7d52e6e7f6a4c58049
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.426 * Running mode=cluster, port=7005.
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.426 # Server initialized
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.428 * Creating AOF base file appendonly.aof.1.base.rdb on server start
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.428 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.428 * Ready to accept connections
cluster-redis-node-5-1  | Waiting 0s before querying node ip addresses
cluster-redis-node-5-1  | 41:M 07 Apr 2023 02:10:06.511 # configEpoch set to 6 via CLUSTER SET-CONFIG-EPOCH
cluster-redis-node-5-1  | >>> Performing hash slots allocation on 6 nodes...
cluster-redis-node-5-1  | Master[0] -> Slots 0 - 5460
cluster-redis-node-5-1  | Master[1] -> Slots 5461 - 10922
cluster-redis-node-5-1  | Master[2] -> Slots 10923 - 16383
cluster-redis-node-5-1  | Adding replica 172.28.0.3:7004 to 172.28.0.2:7000
cluster-redis-node-5-1  | Adding replica 172.28.0.7:7005 to 172.28.0.4:7001
cluster-redis-node-5-1  | Adding replica 172.28.0.6:7003 to 172.28.0.5:7002
cluster-redis-node-5-1  | M: a220694a3c203d4bbee70b0f056ee5a0af13eb06 172.28.0.2:7000
cluster-redis-node-5-1  |    slots:[0-5460] (5461 slots) master
cluster-redis-node-5-1  | M: 9bc1838495b938e25f73447a76d710fea978d946 172.28.0.4:7001
cluster-redis-node-5-1  |    slots:[5461-10922] (5462 slots) master
cluster-redis-node-5-1  | M: 4ef999f8cd10501b6833147fd133ed5d37fb8e19 172.28.0.5:7002
cluster-redis-node-5-1  |    slots:[10923-16383] (5461 slots) master
cluster-redis-node-5-1  | S: 1d267b033547fa2c83461e676619a13c159c197e 172.28.0.6:7003
cluster-redis-node-5-1  |    replicates 4ef999f8cd10501b6833147fd133ed5d37fb8e19
cluster-redis-node-5-1  | S: b00842f9d398a0ee9d256b2da8864a569c8a8384 172.28.0.3:7004
cluster-redis-node-5-1  |    replicates a220694a3c203d4bbee70b0f056ee5a0af13eb06
cluster-redis-node-5-1  | S: 72f6c19d2c1401cd70114f7d52e6e7f6a4c58049 172.28.0.7:7005
cluster-redis-node-5-1  |    replicates 9bc1838495b938e25f73447a76d710fea978d946
cluster-redis-node-5-1  | >>> Nodes configuration updated
cluster-redis-node-5-1  | >>> Assign a different config epoch to each node
cluster-redis-node-5-1  | >>> Sending CLUSTER MEET messages to join the cluster
cluster-redis-node-5-1  | Waiting for the cluster to join
```

It hangs in waiting for the cluster to join

### Additional information

Client: Docker Engine - Community
 Version:           23.0.2
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.19.7
 Git commit:        569dd73
 Built:             Mon Mar 27 16:16:30 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

OS: windows 10 enterprise 21H2
