### ISSUE TITLE
[bitnami/magento:2] Docker Compose fails to start in Windows

### ISSUE THREAD

**Issue by moloni-pt** [bitnami/containers#29992]
### Name and Version

bitnami/magento:2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. I'm using Windows 11 with Docker for Desktop 

3. Using the following docker-compose: 
```yaml
version: '2'
services:
  mariadb:
    container_name: Magento2-DB
    image: docker.io/bitnami/mariadb:10.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    ports:
      - '3370:3306'
    volumes:
      - './Magento2-DB:/bitnami/mariadb'
  magento:
    container_name: Magento2-Web
    image: docker.io/bitnami/magento:2
    mem_limit: 1000000000
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './Magento2-Web:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    container_name: Magento2-Elastic
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - './Magento2-Elastic:/bitnami/elasticsearch/data'
```

4. When I try to run the docker compose command `docker-compose up -d` to start the containers in windows. 

### What is the expected behavior?

The docker should start well and I should be able to access the Magento installation. 
It works when instead of setting the folder paths on my volumes I let it be the default, but then, I cant access my persisted data. 

### What do you see instead?

After 40 minutes of waiting, the Magento docker seems stuck in the command "`persisting magento installation`". 
Everything is created in my windows folder but the docker still seems stuck. 

After stopping the container, when I try to get it back, it exits on the command "`Upgrading database schema`".

All other dockers run well (mysql and elasticsearch).
