### ISSUE TITLE
Running docker bitnami Wordpress, Drupal, Joomla with the same bitnami mariaDB

### ISSUE THREAD

**Issue by plhmk** [bitnami/containers#31077]
### Name and Version

bitnami/wordpress:6 , bitnami/joomla:4, bitnami/drupal:10 , mariadb:10.6:

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Linux Mint 21.1
2. attached file yml
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  drupal:
    image: docker.io/bitnami/drupal:10
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3307
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_drupal
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_drupal
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - '81:8081'
     - '444:8444'

    volumes:
      - 'drupal_data:/bitnami/drupal'
    depends_on:
      - mariadb
  joomla:
    image: docker.io/bitnami/joomla:4
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3308
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_joomla
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '82:8082'
      - '445:8445'

    volumes:
      - 'joomla_data:/bitnami/joomla'
    depends_on:
      - mariadb
  
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  drupal_data:
    driver: local
  joomla_data:
    driver: local
```
3. error on Drupal, Joomla
Could not connect to the database server

### What is the expected behavior?

I expect running WP, Joomla and Drupal connected to the same host mariaDB with 3 different DB, running at the same time
 
### What do you see instead?
```
error on Joomla and Drupal (container exited):
Could not connect to the database server
```
