### ISSUE TITLE
[bitnami/kafka] 3.2 update compatibility

### ISSUE THREAD

**Issue by benitogf** [bitnami/containers#31580]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

using this compose file:

```yml
version: '3.3'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: 'bitnami'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - TZ=Asia/Hong_Kong
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://bitnami:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9094
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/lib/bitnami/kafka:/bitnami/kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Hong_Kong
      - LOGGING_LEVEL_ROOT=error
      - LOGGING_LEVEL_COM_PROVECTUS=error
      - KAFKA_CLUSTERS_0_NAME=bitnami
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=bitnami:9092
```

was working until the recent update, had to rollback to 3.1

it shows no failure logs, just stops the container on startup process 

### What is the expected behavior?

it should work on version 3.2, or maybe have some logs about  the failure 

### What do you see instead?

the container stops with no failure logs

**Comment by javsalgar** [comment]
Hi,

Could you add the env var BITNAMI_DEBUG=true? This may give more insight on the isseu

**Comment by DBarthe** [comment]
We had to rename the  `KAFKA_BROKER_ID` by `KAFKA_CFG_NODE_ID`, looks like a breaking change.

**Comment by javsalgar** [comment]
@benitogf could you confirm that this works for you? We may need to add a note in the README.md

**Comment by benitogf** [comment]
> We had to rename the `KAFKA_BROKER_ID` by `KAFKA_CFG_NODE_ID`, looks like a breaking change.

@DBarthe  @javsalgar yes this worked

```yml
version: '3.3'
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - TZ=Asia/Hong_Kong
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /var/lib/bitnami/kafka:/bitnami/kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Hong_Kong
      - LOGGING_LEVEL_ROOT=error
      - LOGGING_LEVEL_COM_PROVECTUS=error
      - KAFKA_CLUSTERS_0_NAME=bitnami
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=bitnami:9092
```
> We may need to add a note in the README.md

agree 👍 maybe it should include the new sample usage with kraft from here as well: https://github.com/bitnami/containers/pull/31434/files#diff-c2ffb445f96f10e09a6856b45b886e0d1daa0b8bfca24e8444e9e3eeca99a049R4
