### ISSUE TITLE
[bitnami/mariadb] Master delay option on master-slave setup

### ISSUE THREAD

**Issue by Jurajzovinec** [bitnami/containers#31606]
### Name and Version

bitnami:mariadb

### What is the problem this feature will solve?

I am trying to create master-slave db setup for testing of graphQL mutations which are failing on prod environment due to replication lag. 

Is possible to add this ENV variable into container so we can re-create such and environment?
```
MARIADB_MASTER_DELAY
```
```yaml
version: '2'

services:
  mariadb-master:
    image: 'bitnami/mariadb:latest'

    ports:
      - '3306'
    volumes:
      - ./tmp/mariadb:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
    
  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password
      - MARIADB_MASTER_DELAY=3600
      - MARIADB_EXTRA_FLAGS=--read-only=1
 ```

### What is the feature you are proposing to solve the problem?

Unfortunately I am unable to suggest solution

**Comment by javsalgar** [comment]
Hi,

Thanks for opening the ticket! Could you add more details on what setting the MASTER_DELAY variable should change?

**Comment by Jurajzovinec** [comment]
> Hi,
> 
> Thanks for opening the ticket! Could you add more details on what setting the MASTER_DELAY variable should change?

Hi @javsalgar,

Thanks for dedicating your time to this feature request. 
It would be best of you check this [documentation](https://mariadb.com/kb/en/delayed-replication/).

MASTER_DELAY variable should change `SQL_delay` value shown in the output of the command below:
```
docker exec -it replication-lag-bitnami-mariadb-slave-1 mysql -uroot -pmaster_root_password -D my_database -e "USE my_database; SHOW SLAVE STATUS \G;"
```

<img width="551" alt="Screenshot 2023-04-26 at 14 17 27" src="https://user-images.githubusercontent.com/55842933/234572122-140467e1-f6ad-4d1f-b8ee-997bddf31e98.png">

Btw sharing my current workaround:

```yaml
version: '2'

services:
  mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/mariadb:/bitnami/mariadb

    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=cloudtalk
      - MARIADB_PASSWORD=cloudtalk
      - MARIADB_DATABASE=cloudtalk
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password
      - MARIADB_EXTRA_FLAGS=--read-only=1

  mariadb-slave-setup:
    image: 'bitnami/mariadb:latest'
    restart: 'no'
    depends_on:
      - mariadb-slave
    command:
      - bash
      - -c
      - |
        while ! mysqladmin ping -h"mariadb-slave" --silent; do
          sleep 1
        done
        mysql -h mariadb-slave -uroot -pmaster_root_password -e "STOP SLAVE; CHANGE MASTER TO master_delay=10; START SLAVE; RESET MASTER;"
```

The ultimate goal I am looking for is to create an environment that will act like the master-slave db setup with replication lag.
