### ISSUE TITLE
[bitnami/kafka] Container crash 

### ISSUE THREAD

**Issue by polyzos** [bitnami/containers#31789]
### Name and Version

bitnami/kafka:3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a `docker-compose` file as instructed in the docs
```yaml
version: "3.7"
services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
```

but when I modify it to access it from my laptop
```yaml
version: "3.7"
services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
```

the containers just fail with exited code 1

```
kafka  | kafka 06:03:39.80
kafka  | kafka 06:03:39.80 Welcome to the Bitnami kafka container
kafka  | kafka 06:03:39.80 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka  | kafka 06:03:39.80 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka  | kafka 06:03:39.81
kafka  | kafka 06:03:39.81 INFO  ==> ** Starting Kafka setup **
kafka  | kafka 06:03:39.85 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka  | kafka 06:03:39.86 INFO  ==> Initializing Kafka...
kafka  | kafka 06:03:39.87 INFO  ==> No injected configuration files found, creating default config files
kafka  | kafka 06:03:39.96 INFO  ==> Initializing KRaft...
kafka  | kafka 06:03:39.96 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka  | kafka 06:03:40.94 INFO  ==> Generated Kafka cluster ID '6eLg6nd5STGoT01neCYv0Q'
kafka  | kafka 06:03:40.94 INFO  ==> Formatting storage directories to add metadata...
kafka exited with code 1
``` 

### What is the expected behavior?

the container should start

### What do you see instead?

exited code 1

**Comment by polyzos** [comment]
@javsalgar 

```
kafka  | Exception in thread "main" java.lang.IllegalArgumentException: Error creating broker listeners from 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094': No security protocol defined for listener EXTERNAL
kafka  | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:273)
kafka  | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:252)
kafka  | 	at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:2000)
kafka  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1736)
kafka  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1533)
kafka  | 	at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
kafka  | 	at scala.Option.flatMap(Option.scala:271)
kafka  | 	at kafka.tools.StorageTool$.main(StorageTool.scala:41)
kafka  | 	at kafka.tools.StorageTool.main(StorageTool.scala)
kafka  | Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener EXTERNAL
kafka  | 	at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:49)
kafka  | 	at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:596)
kafka  | 	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:73)
kafka  | 	at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:49)
kafka  | 	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:54)
kafka  | 	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:270)
kafka  | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
kafka  | 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
kafka  | 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
kafka  | 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
kafka  | 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
kafka  | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
kafka  | 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
kafka  | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:270)
kafka  | 	... 8 more
kafka exited with code 1
```

**Comment by ccopland94** [comment]
Just wanted to chime in that we are now experiencing the same issue in docker with the following configuration:

```yaml
    zookeeper:
      image: docker.io/bitnami/zookeeper:3.8
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        
    kafka:
      container_name: kafka
      image: docker.io/bitnami/kafka:3.3
      ports:
        - "9093:9093"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
        - zookeeper
```

**Comment by eabasguliyev** [comment]
I have same issue. Did you find anything?

**Comment by LHozzan** [comment]
Similar problem here.
```yaml
...
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
        - name: KAFKA_KRAFT_CLUSTER_ID
          valueFrom:
            secretKeyRef:
              key: kraftid
              name: REDACTED
        - name: KAFKA_CFG_PROCESS_ROLES
          value: controller,broker
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 0@inst-kafka-0:9093,1@inst-kafka-1:9093,2@inst-kafka-2:9093
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093
        - name: KAFKA_CFG_LOG_DIRS
          value: /kafka/data
        - name: BROKER_ID_COMMAND
          value: hostname | awk -F'-' '{print $NF}'
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1G -Xms1G
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_INITIAL_BROKER_REGISTRATION_TIMEOUT_MS
          value: "240000"
        image: bitnami/kafka:3.4.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/bitnami/kafka/bin/kafka-server-stop.sh
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: listener
          timeoutSeconds: 5
        name: kafka
        ports:
        - containerPort: 9092
          name: listener
          protocol: TCP
        - containerPort: 9093
          name: controller
          protocol: TCP
        readinessProbe:
          failureThreshold: 24
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: listener
          timeoutSeconds: 3
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kafka
          name: kafka-data
...
```
After investigation I discovered, that problems start with revision `3.4.0-debian-11-r22`. Previous image revision `3.4.0-debian-11-r21` is working for us.

So, workaround is pinpoint image version to `3.4.0-debian-11-r21`, until problem will be solved.

Hope that helps.

**Comment by polyzos** [comment]
@LHozzan any quick way I can tweak the image or i will have to build it from scratch?

**Comment by LHozzan** [comment]
@polyzos We using Kubernetes, I am not sure, but I think it should be something like this:
```yaml
version: "3.7"
services:
  kafka:
    image: docker.io/bitnami/kafka:3.4.0-debian-11-r21 ### <<< change image here
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
```

**Comment by amkartashov** [comment]
have similar issue after upgrading from `3.3.2-debian-11-r63` to `3.3.2-debian-11-r64`. All of the sudden, Kafka wants to start in Kraft mode. Logs with debug:

```
kafka 11:04:34.32
kafka 11:04:34.32 Welcome to the Bitnami kafka container
kafka 11:04:34.33 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 11:04:34.33 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 11:04:34.33
kafka 11:04:34.33 INFO  ==> ** Starting Kafka setup **
kafka 11:04:34.37 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 11:04:34.37 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka 11:04:34.38 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 11:04:34.38 INFO  ==> Initializing Kafka...
kafka 11:04:34.39 INFO  ==> No injected configuration files found, creating default config files
kafka 11:04:34.73 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
kafka 11:04:34.73 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
kafka 11:04:34.73 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 11:04:34.74 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 11:04:34.74 INFO  ==> Initializing KRaft...
kafka 11:04:34.74 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka 11:04:35.94 INFO  ==> Generated Kafka cluster ID 'KAdCWPqoRfWwiu3MbKeaew'
kafka 11:04:35.94 INFO  ==> Formatting storage directories to add metadata...
Exception in thread "main" org.apache.kafka.common.config.ConfigException: You must set `node.id` to the same value as `broker.id`.
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2068)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2063)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1494)
        at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
        at scala.Option.flatMap(Option.scala:283)
        at kafka.tools.StorageTool$.main(StorageTool.scala:41)
        at kafka.tools.StorageTool.main(StorageTool.scala)
```

**Comment by OneCricketeer** [comment]
Hi all. Spent the weekend debugging this myself. 

## Image pining / reverting to previous behavior

For those that **aren't** pinning the `-debian-11-r..` tags, and instead using `latest` or just `:3.x`... Kraft mode is **now the default**.  If you still have Zookeeper service, it isn't being used and you must add a new env-var to continue using it - `KAFKA_ENABLE_KRAFT=false`. Read the `README` for more information. 

This was changed within the last few weeks, and is why you should always pin your Docker tags to consistent versions that won't change beneath you. 

## Using Kraft

The latest `docker-compose.yml` in this repo starts on its own with `process.roles=controller,broker`. If you are starting fresh, then use this. 

## Listener changes

To open the container to be accessed from the host, you must add `CONTROLLER` listener

```yaml
# service name == kafka
ports:
  - 9092:9092
environment:
  KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://:9093
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
```

This resolves to `kafka:29092` within the Compose network and `localhost:9092` from the host. 

Note: I use `PLAINTEXT_HOST` instead of `EXTERNAL`. The scripts included with this container have custom logic for listeners called `INTERNAL`, `CLIENT`, `EXTERNAL`, and now `CONTROLLER`. These names mean nothing to Kafka, so should probably be avoided in your own configs.  

## Additional details

The Kafka documentation covers what settings are **required** for Kraft. This includes

- `node.id` (replaces `broker.id` ; must be unique on every Kafka host)
- `controller.quorum.voters` (Must be the same on every Kafka host)
- `controller.listener.names` (Must be defined on the Kraft controllers)
- `listener.security.protocol.map` (Must define a security mapping for the `controller.listener.names`)

Unfortunately, the scripts that start with this container try to "be smart" and pre-configure many of these attributes.

**Comment by norens** [comment]
I found out that Bitnami Kafka now defaults to KRaft mode, and completely ignores Zookeeper unless explicitly told not to. The solution is to disable KRaft and stick to Zookeeper by adding this line:

`KAFKA_ENABLE_KRAFT: "no"`

Final working config:

```yaml
kafka:
  image: bitnami/kafka:3.6.1 # Important: pin to a known working version
  container_name: kafka
  ports:
    - "9092:9092"
  environment:
    KAFKA_ENABLE_KRAFT: "no"
    KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
    KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  depends_on:
    - zookeeper
```
