### ISSUE TITLE
[bitnami/kafka] Kafka config via ENV no longer accepts empty values

### ISSUE THREAD

**Issue by setl-git-admin** [bitnami/containers#32224]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Docker file : 

```
version: "3.7"

services:

  kafka1:
    container_name: kafka1
    hostname: broker1.kafka.setl
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "kafka_1_data:/bitnami"
      - "../kafka_ca/broker-cert/kafka.broker0.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "../kafka_ca/broker-cert/kafka.broker0.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_INITIAL_BROKER_REGISTRATION_TIMEOUT_MS: 240000
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      # uuidgen | tr -d '-' | base64 | cut -b 1-22
      KAFKA_KRAFT_CLUSTER_ID: QjIxODVGQ0M0REU4NEI2RD
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SSL,EXTERNAL:SSL,CONTROLLER:SSL
      KAFKA_CFG_LISTENERS: BROKER://:9093,EXTERNAL://:9092,CONTROLLER://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://broker1.kafka.setl:9093,EXTERNAL://broker1.kafka.setl:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@broker1.kafka.setl:9095
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_CFG_TLS_CLIENT_AUTH: required
      KAFKA_CFG_TLS_TYPE: JKS
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: password
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: password
      KAFKA_CFG_SSL_KEY_PASSWORD: masquerade
      KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL: SSL

volumes:
  kafka_1_data:
    driver: local
```

### What is the expected behavior?

I expect the server.properties ssl.endpoint.identification.algorithm to be set to an empty string.

### What do you see instead?

the server.properties ssl.endpoint.identification.algorithm is not set, the broker uses the default (HTTPS)

### Additional information

this section in the libkafka.sh script has been changed, as of 24/04/2023, to disallow the setting of empty values.
This means that the ssl.endpoint.identification.algorithm can not be set to an empty string which is a valid (and necessary) setting : 

```
kafka_configure_from_environment_variables() {
    # List of special cases to apply to the variables
    local -r exception_regexps=(
        "s/sasl.ssl/sasl_ssl/g"
        "s/sasl.plaintext/sasl_plaintext/g"
    )
    # Map environment variables to config properties
    for var in "${!KAFKA_CFG_@}"; do
        key="$(echo "$var" | sed -e 's/^KAFKA_CFG_//g' -e 's/_/\./g' | tr '[:upper:]' '[:lower:]')"

        # Exception for the camel case in this environment variable
        [[ "$var" == "KAFKA_CFG_ZOOKEEPER_CLIENTCNXNSOCKET" ]] && key="zookeeper.clientCnxnSocket"

        # Apply exception regexps
        for regex in "${exception_regexps[@]}"; do
            key="$(echo "$key" | sed "$regex")"
        done

        value="${!var}"
        if [[ -n "$value" ]]; then
            kafka_server_conf_set "$key" "$value"
        fi
    done
}
```
