### ISSUE TITLE
mkdir: cannot create directory '/opt/bitnami/nginx/conf/bitnami': Read-only file system

### ISSUE THREAD

**Issue by jgournet** [bitnami/containers#32670]
### Name and Version

bitnami/nginx

### What architecture are you using?

amd64

### What steps will reproduce the bug?

values.yaml file:
```
extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: nginx-test-conf
      namespace: kube-system
    data:
      nginx.conf: |
        server {
          my config here - this is NOT a valid config, I know :)
        }


extraVolumeMounts:
  - name: nginx-conf
    mountPath: /opt/bitnami/nginx/conf/
  - mountPath: /tmp
    name: tmp-volume

extraVolumes:
  - name: nginx-conf
    configMap:
      name: nginx-test-conf
      items:
        - key: nginx.conf
          path: nginx.conf
  - name: tmp-volume
    emptyDir: {}
```

Installing helm chart with the above config:
```
helm install my-release -f /tmp/values.yaml -n kube-system oci://registry-1.docker.io/bitnamicharts/nginx
```
=> we get the error from title

### What is the expected behavior?

Same behavior as this:
```
helm install my-release -f /tmp/values.yaml --set image.tag=1.23.3-debian-11-r26 -n kube-system oci://registry-1.docker.io/bitnamicharts/nginx
```
ie: things work
(ok, in this case, my nginx config is wrong, so we get a proper "server directive is not allowed here" :) )

### What do you see instead?

```
mkdir: cannot create directory '/opt/bitnami/nginx/conf/bitnami': Read-only file system
```

### Additional information

You might ask "why are you doing this ??"
This is because we want to add "stream" blocks, so we write our own full config.

It was working well, until this was introduced:
File: /opt/bitnami/scripts/nginx/setup.sh
```
# Regenerate SSL certs (without a passphrase)
ensure_dir_exists "${NGINX_CONF_DIR}/bitnami/certs"
if [[ ! -f "${NGINX_CONF_DIR}/bitnami/certs/server.crt" ]]; then
    SSL_KEY_FILE="${NGINX_CONF_DIR}/bitnami/certs/server.key"
[...]
```
this "ensure_dir_exists" fails in our case, as NGINX_CONF_DIR is indeed a read-only FS as it comes from the config map.

=>
Could you see if you can do a fix for this ?
(or maybe let me know how I can add stream server blocks a bit more properly than overwriting the whole config)
