### ISSUE TITLE
[bitnami/spark] Unable to run pyspark interactive shell

### ISSUE THREAD

**Issue by jonatronblah** [bitnami/containers#32710]
### Name and Version

bitnami/spark:3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Forgive me as I am very new to spark, but could not solve this issue with google.
Using the following docker compose file:

```yaml
version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
```

Attempting to run pyspark interactive shell with the following command: ./bin/pyspark

### What is the expected behavior?

Expect the pyspark interactive shell to run.

### What do you see instead?

Always receive the following error: "Error: pyspark does not support any application options."

### Additional information

I can submit pyspark jobs successfully, and activate the scala interactive shell just fine. Thanks for any help.
