### ISSUE TITLE
[bitnami/kafka] `KAFKA_CFG_NODE_ID:` unbound variable error

### ISSUE THREAD

**Issue by LHozzan** [bitnami/containers#33271]
### Name and Version

bitnami/kafka:3.4.0-debian-11-r28

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I attempt to run Kafka cluster in Kraft mode with variables:

```yaml
        - name: BITNAMI_DEBUG
          value: "true"
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
        - name: KAFKA_KRAFT_CLUSTER_ID
          valueFrom:
            secretKeyRef:
              key: kraftid
              name: kafka-kraft-id
        - name: KAFKA_CFG_PROCESS_ROLES
          value: controller,broker
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093
        - name: KAFKA_CFG_LOG_DIRS
          value: /kafka/data
        - name: BROKER_ID_COMMAND
          value: hostname | awk -F'-' '{print $NF}'
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1G -Xms1G
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: SSL
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,CONTROLLER:SSL
        - name: KAFKA_TLS_TYPE
          value: PEM
        - name: KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL
          value: SSL
        - name: KAFKA_TLS_TRUSTSTORE_FILE
          value: /kafka/certs/cacert.pem
        - name: KAFKA_CFG_SSL_KEYSTORE_TYPE
          value: PEM
        - name: KAFKA_CFG_SSL_TRUSTSTORE_LOCATION
          value: /kafka/certs/cacert.pem
        - name: KAFKA_CFG_SSL_TRUSTSTORE_TYPE
          value: PEM
```

It seems, that problem is variable `BROKER_ID_COMMAND`. In scripts I cannot find it, where is execute to obtain current broker ID.

### What is the expected behavior?

Kafka instances start without any problems.

### What do you see instead?
```
kafka 14:39:41.05 
kafka 14:39:41.05 Welcome to the Bitnami kafka container
kafka 14:39:41.05 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 14:39:41.06 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 14:39:41.06 
kafka 14:39:41.06 INFO  ==> ** Starting Kafka setup **
kafka 14:39:41.09 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 14:39:41.09 ERROR ==> KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller
/opt/bitnami/scripts/libkafka.sh: line 258: KAFKA_CFG_NODE_ID: unbound variable
```
### Additional information

The problem not exist in `3.4.0-debian-11-r21`, but in `3.4.0-debian-11-r22` the problem starts.

**Comment by OneCricketeer** [comment]
Referring to the Kafka documentation, `broker.id` `is no longer used for Kraft. It must be replaced with `node.id`

**Comment by LHozzan** [comment]
Hello.

@OneCricketeer thank you for feedback.

As you can see, this is part of our statefulset, from my sand box. Here, we really not set `broker.id`, but we set it dynamically via variable `BROKER_ID_COMMAND`. It seems, that support of the variable was ended and not have follower.

If I change `BROKER_ID_COMMAND` to `NODE_ID_COMMAND`, I am facing to the different problem:

```
kafka 07:47:16.24 
kafka 07:47:16.24 Welcome to the Bitnami kafka container
kafka 07:47:16.24 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 07:47:16.24 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 07:47:16.24 
kafka 07:47:16.24 INFO  ==> ** Starting Kafka setup **
kafka 07:47:16.27 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 07:47:16.27 ERROR ==> KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller
/opt/bitnami/scripts/libkafka.sh: line 258: KAFKA_CFG_NODE_ID: unbound variable
```

As you can see, we using KRaft by default, but OK, good point, after r22 we can omit the variable.

Let me summarize my curious: How to replace function in `BROKER_ID_COMMAND` in r22 and higher ?

**Comment by OneCricketeer** [comment]
I don't know if there is a replacement. You can find the source code for the scripts in this repo

**Comment by LHozzan** [comment]
Yop, you have right, I can really help my self :).

So, variable [`BROKER_ID_COMMAND`](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/kafka/setup.sh#L20-L28) really exist in image and it seems, that is executed. Value from it is passed to `KAFKA_CFG_BROKER_ID`, which as you wrote early, isnt exist anymore.

But variable [`KAFKA_CFG_NODE_ID`](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.3/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L244) exist and is used.

From my perspective, this is bug and solution should looks like:
- rename `BROKER_ID_COMMAND` to `NODE_ID_COMMAND`
- rename `KAFKA_CFG_BROKER_ID` to `KAFKA_CFG_NODE_ID`
... in mentioned `setup.sh` script.

@mdhont What do you think? May I prepare PR for the change? Maybe in some README will be the change mentioned as well.

**Comment by mdhont** [comment]
Yes, at first sight it looks ok. Could you please create a PR? Please note that any changes need to be tested and reviewed internally so it might still be rejected or changes can be requested.

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR. The team will review it and provide feedback. Once merged the PR, this issue will be automatically closed.

**Comment by LHozzan** [comment]
@carrodher or @jotamartos any news about my PR? Your bot doing great job to sending reminders :).

**Comment by carrodher** [comment]
The latest comment still apply:
> Sorry for the delay here @LHozzan. We are reviewing other issues with the Bitnami Kafka container and we want to come up a solution that is valid in all cases. Will update the ticket when we have more information.

We are doing some major refactors in Kafka with Kraft mode, we will update the different issues/PRs once completed

**Comment by LHozzan** [comment]
> The latest comment still apply:

Thank you, but it is possible tell your bot to let this case opened, until will be fixed? Or it is possible to hold the issue opened without placing any comments?

Thank you!

**Comment by mdhont** [comment]
Unfortunately not. However, we are internally tracking the case so you can be sure it won't be forgotten.

**Comment by LHozzan** [comment]
OK, I understand, the solution will not be provided soon :).

The another solution (without touching to the image) is possible directly in Kubernetes. Looks like:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    (...)
  labels:
    (...)
  name: kafka-cluster
  namespace: kaf-dev
spec:
  podManagementPolicy: Parallel
    (...)
    spec:
      (...)
      containers:
      - name: kafka
        image: bitnami/kafka:3.4.1-debian-11-r2
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        (...)
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        (...)
        command:
        - /bin/bash
        args:
        - -ec
        - |
          export KAFKA_CFG_NODE_ID="$(echo "$MY_POD_NAME" | grep -o -E '[0-9]*$')"
          /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
        (...)
```

Magic here is:
- get PodName from Statefulset to the environmental variable (variable name `MY_POD_NAME`; in our case pods name it looks like `kafka-inst-0, kafka-inst-1, kafka-inst-2, ... kafka-inst-33`, so value should be `0, 1, 2, ... 33`)
- "eval" the command before "entrypoint" script is running (`echo "$MY_POD_NAME" | grep -o -E '[0-9]*$'`)
- and have the value available for the machinery inside the image (`export KAFKA_CFG_NODE_ID`)

I have tested with current image release and it is working fine. I believe, that same approach is applicable for another Kafka image versions/releases ..., BUT I not have spare time to play with it.

@mdhont If you really dont forget to me, please be so kind and place comment here. I will waiting for the solution from you to dismantle the workaround. Meantime I let here the notes, how to evade the bug inside in the image.
