### ISSUE TITLE
[bitnami/wordpress-nginx] Deploying wordpress  as root user in a docker-compose env producing 502 Bad Gateway on nginx

### ISSUE THREAD

**Issue by aliykh** [bitnami/containers#33308]
### Name and Version

bitnami/wordpress-nginx:6.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using MAC and Running docker-compose command 
2. 
  ```
wp-db:
    image: docker.io/bitnami/mariadb:10.6
    restart: unless-stopped
    environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_USER=wordpress
        - MARIADB_PASSWORD=wordpress_psw
        - MARIADB_DATABASE=wordpress
        - MARIADB_ROOT_PASSWORD=root_psw
    ports:
        - "3306:3306"

  wordpress:
    image: bitnami/wordpress-nginx:6.2.0
    user: root
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - wp-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=wp-db
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress_psw
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_USERNAME=user
      - WORDPRESS_PASSWORD=password
```
3. Run docker-compose up -d
4. Starts successfully, **however** when I access localhost/wp-admin/ it is producing 502 bad gateway error on nginx

### What is the expected behavior?

When I run the wordpress server contain as root user, I expect everything to run as expected in a root user env. 

### What do you see instead?

When I try to access http://localhost/wp-admin/ I see this kinda error page 
<img width="1133" alt="image" src="https://github.com/bitnami/containers/assets/22681649/44ab3a88-d394-4df0-84f5-04f9a2e3df07">

and error on nginx side: 

`2023-05-10 01:46:29 2023/05/09 20:46:29 [crit] 376#376: *5 connect() to unix:/opt/bitnami/php/var/run/www.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.48.5, server: _, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "wordpress", referrer: "http://localhost/wp-admin/post.php?post=521280&action=edit"`

I think www.sock which will be created when the server request is made is being created by daemon user and that's why there is a permission conflict. 

and the main question here, how can I run this wordpress server as root user without any permission issues?
