### ISSUE TITLE
Start failing mongodb 6 on my Apple silicon (m1) mac 

### ISSUE THREAD

**Issue by imalik8088** [bitnami/containers#33409]
### Name and Version

docker.io/bitnami/mongodb:6.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

This is how my docker-compose file looks like:
```yaml
version: "3.7"

services:
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - "27017:27017"
```

### What is the expected behavior?

Should run without any issues because same image with version 4 does work on my system without any issues.

### What do you see instead?

```
mongodb 08:35:46.40
mongodb 08:35:46.42 Welcome to the Bitnami mongodb container
mongodb 08:35:46.44 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 08:35:46.46 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 08:35:46.48
mongodb 08:35:46.50 INFO  ==> ** Starting MongoDB setup **
mongodb 08:35:46.63 INFO  ==> Validating settings in MONGODB_* env vars...
```

### Additional information

I want to start mongodb in version 6 but its stucking on my Apple Silicon (M1) mac
