### ISSUE TITLE
[bitnami/parse] reverse proxy settings for parse-server

### ISSUE THREAD

**Issue by 3x3cut0r** [bitnami/containers#3393]
### Name and Version

bitnami/parse

### What steps will reproduce the bug?

I am running a docker-compose.yml of the bitnami parse, parse-dashboard and mongodb containers behind a reverse proxy.
the containers starting well without errors.
i setup a reverse proxy with nginx on my docker host. the proxy is also working fine for hundreds of containers.
i can successfully reach the parse-dashboard but after i login i get a white page.
with the google chrome dev tools i can see the folowing error:
`Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.`

my question now. what did i wrong? how can i prevent this error?
i also try the official docker images from parseplatform ... same thing.

can anyone provide a working configuration and what else i need to know and configure to get the parse-dashboard working behind a reverse proxy?

thank you

### What do you see instead?

a white page after login to the parse-dashboard.

### Additional information

my docker-compose.yml:
```
version: "3.9"

# https://github.com/parse-community/parse-server
services:
  # https://hub.docker.com/r/bitnami/parse
    parse-server:
        container_name: parse-server
        image: bitnami/parse:5
        restart: unless-stopped
        ports:
            - "1337:1337"
        networks:
            parse:
                ipv4_address: 10.24.37.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            PARSE_ENABLE_HTTPS: 'no'
            PARSE_BIND_HOST: 'parse-server'
            PARSE_HOST: 'parse-server'
            PARSE_PORT_NUMBER: '1337'
            PARSE_APP_ID: 'project1'
            PARSE_MASTER_KEY: '*****'
            PARSE_APP_NAME: 'project1'
            PARSE_MOUNT_PATH: '/parse'
            PARSE_ENABLE_CLOUD_CODE: 'no'
            PARSE_DATABASE_HOST: 'parse-mongo'
            PARSE_DATABASE_PORT_NUMBER: '27017'
            PARSE_DATABASE_USER: 'parse'
            PARSE_DATABASE_NAME: 'parse'
            PARSE_DATABASE_PASSWORD: '*****'
        volumes:
            - parse-server-conf:/bitnami
        depends_on:
            - parse-mongo

  # https://hub.docker.com/r/bitnami/parse-dashboard
    parse-dashboard:
        container_name: parse-dashboard
        image: bitnami/parse-dashboard:latest
        restart: unless-stopped
        ports:
            - "4040:4040"
        networks:
            parse:
                ipv4_address: 10.24.37.3
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            PARSE_DASHBOARD_ENABLE_HTTPS: 'no'
            PARSE_DASHBOARD_EXTERNAL_HTTP_PORT_NUMBER: '80'
            PARSE_DASHBOARD_EXTERNAL_HTTPS_PORT_NUMBER: '80'
            PARSE_DASHBOARD_PARSE_HOST: 'parse-server'
            PARSE_DASHBOARD_PORT_NUMBER: '4040'
            PARSE_DASHBOARD_PARSE_PORT_NUMBER: '1337'
            PARSE_DASHBOARD_PARSE_APP_ID: 'project1'
            PARSE_DASHBOARD_PARSE_APP_NAME: 'project1'
            PARSE_DASHBOARD_PARSE_MASTER_KEY: '*****'
            PARSE_DASHBOARD_PARSE_MOUNT_PATH: '/parse'
            PARSE_DASHBOARD_PARSE_PROTOCOL: 'http'
            PARSE_DASHBOARD_USERNAME: 'admin'
            PARSE_DASHBOARD_PASSWORD: '*****'
        volumes:
            - parse-dashboard-conf:/bitnami
        depends_on:
            - parse-server

  # https://hub.docker.com/r/bitnami/mongodb
    parse-mongo:
        container_name: parse-mongo
        image: bitnami/mongodb:5.0
        restart: unless-stopped
        networks:
            parse:
                ipv4_address: 10.24.37.4
      # ports:
      #     - 27017:27017
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
            MONGODB_DATABASE: 'parse'
            MONGODB_USERNAME: 'parse'
            MONGODB_PASSWORD: '*****'
        volumes:
            - parse-mongo-data:/bitnami

networks:
    parse:
        name: parse
        ipam:
            driver: default
            config:
                - subnet: "10.24.37.0/24"
                  gateway: 10.24.37.1

volumes:
    parse-server-conf:
        name: parse-server-conf
    parse-dashboard-conf:
        name: parse-dashboard-conf
    parse-mongo-data:
        name: parse-mongo-data

```
