### ISSUE TITLE
[bitnami/redis-cluster] Set enviroment variable based on criteria

### ISSUE THREAD

**Issue by miberecz** [bitnami/containers#34413]
### Name and Version

redis-cluster:7.0 or redis-cluster:6.2

### What is the problem this feature will solve?

There isnt a problem really, its more of a question.

### What is the feature you are proposing to solve the problem?

I realize its a strange request. 
I'm running the redis-cluster image in a Docker Swarm environment, and I would like to set the `REDIS_CLUSTER_CREATOR=yes` only for one container, but do all the 6 (or more) nodes in one service. Right now its not possible, either I pass this variable to the service or not, if I pass it it will affect all nodes.

What I'm trying to do, is somehow only set the variable if a certain hostname matches, but probably I do not understand properly how these images work.

Let me show in code:

```yaml
version: '3.9'

services:
  nodes:
    image: docker.io/bitnami/redis-cluster:7.0
    hostname: redis-{{.Task.Slot}}
    volumes:
      - /data/redis-{{.Task.Slot}}:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-1 redis-2 redis-3 redis-4 redis-5 redis-6
    command: bash -c 'if [[ "$HOSTNAME" == "redis-6" ]]; then export REDIS_CLUSTER_CREATOR=yes; fi && /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh'
    ports:
      - '6379'
    deploy:
      mode: replicated
      replicas: 6
```
Obviously, it does not work, my hacked in variable does not get exported.

I do not ask to implement such a thing, I just want to know if I can achieve this with some kind of workaround on my own.

### What alternatives have you considered?

Yes, I know, I can just create another service for the 6th node and set the variable there. It just would make my setup cleaner.
