### ISSUE TITLE
pgbouncer DNS lookup failed after upgrading to Docker Enginer 24

### ISSUE THREAD

**Issue by tyteen4a03** [bitnami/containers#34531]
### Name and Version

bitnami/pgbouncer:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is our config (I have not tried creating a minimal reproduction yet)

```yaml
    postgres:
        image: postgres:15
        restart: always
        command: >
            -c password_encryption=scram-sha-256
            -c hba_file=/var/lib/postgresql/pg_hba.conf
            -c shared_preload_libraries=pg_stat_statements
            -c track_activity_query_size=8192
            -c pg_stat_statements.track=ALL
            -c pg_stat_statements.max=10000
            -c track_io_timing=on
        expose:
            - "5432"
        ports:
            - "127.0.0.1:6432:5432"
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
        volumes:
            - "postgres_data:/var/lib/postgresql/data/"
            - "./pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro"

    pgbouncer:
        image: bitnami/pgbouncer:latest
        restart: always
        depends_on:
            - postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRESQL_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRESQL_DATABASE=ourdb
            - POSTGRESQL_HOST=postgres
            - PGBOUNCER_PORT=5432
 ```

### What do you see instead?

I started getting this error: `pgbouncer-1  | 2023-05-19 02:03:23.437 UTC [1] WARNING DNS lookup failed: postgres: result=0` when upgrading my Docker Engine (Ubuntu 22.04) to 24.0.

Downgrading to 23.0.6 fixed it for me.
