### ISSUE TITLE
RabbitMQ seg faults on M1 Macs

### ISSUE THREAD

**Issue by renatojf** [bitnami/containers#3589]
### Name and Version

bitnami/rabbitmq:3.9.22

### What steps will reproduce the bug?

1. Use a Mac with M1 chip
2. Add rabbitMQ to any compose file and `compose up`

```
rabbitmq:
    platform: linux/amd64
    image: bitnami/rabbitmq:3.9.22
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
```

3. Watch the seg fault

```
rabbitmq 08:31:23.71
rabbitmq 08:31:23.76 Welcome to the Bitnami rabbitmq container
rabbitmq 08:31:23.79 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 08:31:23.83 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 08:31:23.86
rabbitmq 08:31:23.89 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 08:31:24.05 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 08:31:24.32 INFO  ==> Initializing RabbitMQ...
rabbitmq 08:31:24.59 INFO  ==> Generating random cookie
rabbitmq 08:31:24.98 INFO  ==> Starting RabbitMQ in background...
/opt/bitnami/scripts/libos.sh: line 336:   149 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   244 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   291 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   388 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   435 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   482 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   580 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   627 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   674 Segmentation fault      "$@" > /dev/null 2>&1
/opt/bitnami/scripts/libos.sh: line 336:   772 Segmentation fault      "$@" > /dev/null 2>&1
```

### What is the expected behavior?

No segfaults.

### What do you see instead?

Unhealthy container and crash
