### ISSUE TITLE
[bitnami/matomo] 'Could not open input file: /opt/bitnami/matomo/console' - Error after latest Update of Matomo

### ISSUE THREAD

**Issue by masterwishx** [bitnami/containers#36032]
### Name and Version

bitnami/matomo:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

After updated to latest version i cant start conainer in Unraid (Linux x64)

![image](https://github.com/bitnami/containers/assets/28630321/b04ed7ad-cb85-4b2c-a50c-64a5a11a180d)

### What is the expected behavior?

.

### What do you see instead?

.

### Additional information

.

**Comment by javsalgar** [comment]
Hi,

Do you have a docker-compose.yml that triggers the issue?

**Comment by masterwishx** [comment]
im running in docker in Unraid ...

![image](https://github.com/bitnami/containers/assets/28630321/cd149258-2736-4268-bb42-6e497e59454f)
![image](https://github.com/bitnami/containers/assets/28630321/6abd1ac6-650d-4049-bb08-b68ae86d0470)

**Comment by masterwishx** [comment]
@javsalgar can it be becose linuxserver Mariadb updated to 10.11.3 from 10.6.13 ?

**Comment by yayitazale** [comment]
Same issue here. Latest tag for linuxserver MariaDB points to [10.11.3](https://hub.docker.com/r/linuxserver/mariadb/tags). Is there any compatibility issue?

**Comment by masterwishx** [comment]
@javsalgar  i changed back to  " bitnami/matomo:4.14.2-debian-11-r15 " - same issue
but "bitnami/matomo:4.14.2-debian-11-r12 is " is Working !

**Comment by javsalgar** [comment]
Hi,

So, could you let us know the exact steps to reproduce the issue? That would be helpful for us to understand what is happening

**Comment by masterwishx** [comment]
@javsalgar
im using Unraid Docker latest version of bitnami/Matomo + MariaDB ([linuxserver/mariadb](https://hub.docker.com/r/linuxserver/mariadb/)

bitnami/matomo:4.14.2-debian-11-r14+ are not working maybe becose  linuxserver Mariadb updated to 10.11.3 from 10.6.13
some days ago ...

so i goes back to version bitnami/matomo:4.14.2-debian-11-r13 are working fine but later versions are not .

**Comment by javsalgar** [comment]
Hi,

I believe that the issue lies here

https://github.com/bitnami/containers/commit/92fd80d9c0ca77da7fe8e980ec0984a727ebc229

Could you try setting the env var `MATOMO_DATA_TO_PERSIST=config/config.ini.php misc plugins js` in your docker-compose?

**Comment by ITspirit** [comment]
> Hi,
> 
> I believe that the issue lies here
> 
> [92fd80d](https://github.com/bitnami/containers/commit/92fd80d9c0ca77da7fe8e980ec0984a727ebc229)
> 
> Could you try setting the env var `MATOMO_DATA_TO_PERSIST=config/config.ini.php misc plugins js` in your docker-compose?

Have the same issue at the momemtn. Settings this in docker-composer the container starts, but i will get 500 only on UI

In docker Logs i get then:

[05-Jun-2023 07:56:26 UTC] PHP Fatal error:  Access level to Piwik\Plugins\UsersManager\API::confirmCurrentUserPassword() must be protected (as in class Piwik\Plugin\API) or weaker in /bitnami/matomo/plugins/UsersManager/API.php on line 1486
192.168.16.2 - - [05/Jun/2023:07:56:25 +0000] "GET / HTTP/1.1" 500 -

**Comment by masterwishx** [comment]
> Could you try setting the env var `MATOMO_DATA_TO_PERSIST=config/config.ini.php misc plugins js` in your docker-compose?

Yes its Working with latest version , but maybe you can fix this inside (Matomo persistence configuration (bitnami/matomo/4/debian-11/rootfs/opt/bitnami/scripts/matomo-env.sh) ) 
to work without this env in container  ?

**Comment by bbrala** [comment]
Using the helm chart we also have the same issue. It wil not start.

![image](https://github.com/bitnami/containers/assets/3294970/f019e560-41ff-4e0d-8ce5-a7d0d029485e)

Helm chart version: 1.1.4

**Comment by bbrala** [comment]
I've tried to change `MATOMO_DATA_TO_PERSIST` on acceptance, and that seems to work. Should i change this on production also? Feel like there is an error in the migration path to that new variable, so would prefer not to have to change this in production. Not sure what the sideeffects might be.

**Comment by rafariossaa** [comment]
Hi,
  I was trying to reproduce this issue by using this `docker-compose.yaml`:
```
version: "2"
services:
  mariadb:
    # image: docker.io/bitnami/mariadb:10.6
    image: docker.io/bitnami/mariadb:10.11.3
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_ROOT_PASSWORD=bitnami
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - "./mariadb_data:/bitnami/mariadb"
  matomo:
    # image: docker.io/bitnami/matomo:4.14.2-debian-11-r12
    image: docker.io/bitnami/matomo:4.14.2-debian-11-r16
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - MATOMO_DATABASE_PASSWORD=bitnami
      - MATOMO_PASSWORD=patata
    volumes:
      - "./matomo_data:/bitnami/matomo"
    depends_on:
      - mariadb
```
  I did several tests, I started using the lower version of the mariadb *AND* matomo, and checked upgrading only mariadb, or only matomo, or both at the same time, but I could not reproduce the issue.
  The only way I could reproduce it was:
- Start with: `docker-compose up`
- Stop it: `docker-compose down`
- Remove the files in `matomo_data`: `rm -rf matomo_data/*`
- Start it again: `docker-compse up`

In this case, what happens is that it is detecting that `matomo_data` is not empty and it is trying to recover the persisted data. The issue doing this is that there is a file `matomo_data/.spdx-matomo.spdx` that is not delete with the above `rm` command.

Could you check if this is your case ?
Could you check the content of the volume ? The errors comes when trying to run: `php /opt/bitnami/matomo/console core:update --yes`  in [this](https://github.com/bitnami/containers/blob/ff039e7b2bae770deeafbc820175012a9aa62e46/bitnami/matomo/4/debian-11/rootfs/opt/bitnami/scripts/libmatomo.sh#L230) line, but there is nothing in `/opt/bitnami/matomo`
