### ISSUE TITLE
[bitnami/kafka] TLS Kafka cluster won't start due to authentication error

### ISSUE THREAD

**Issue by emeraldhieu** [bitnami/containers#36188]
### Name and Version

docker.io/bitnami/kafka:3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to create two TLS-enabled K-draft kafka brokers. I've followed [this section](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#security): create 2 different pairs of truststore and keystore.

```yml
version: '3.5'

services:

  kafka-0:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
      - "9093"
    networks:
      - infra
    volumes:
      - "kafka0-data:/bitnami"
      - "./tls/kafka-0/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
      - "./tls/kafka-0/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
    environment:
      BITNAMI_DEBUG: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0:9093,1@kafka-1:9093"
      KAFKA_CFG_NODE_ID: 0
      KAFKA_KRAFT_CLUSTER_ID: "qYoMEZXcS_SKP2PzAl8-WA"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:SSL,CONTROLLER:SSL"
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: "/opt/bitnami/kafka/config/certs/kafka.keystore.jks"
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: haveaniceday
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: "/opt/bitnami/kafka/config/certs/kafka.truststore.jks"
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: haveaniceday

  kafka-1:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
      - "9093"
    volumes:
      - "kafka1-data:/bitnami"
      - "./tls/kafka-1/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
      - "./tls/kafka-1/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
    networks:
      - infra
    environment:
      BITNAMI_DEBUG: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0:9093,1@kafka-1:9093"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: "qYoMEZXcS_SKP2PzAl8-WA"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:SSL,CONTROLLER:SSL"
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: "/opt/bitnami/kafka/config/certs/kafka.keystore.jks"
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: haveaniceday
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: "/opt/bitnami/kafka/config/certs/kafka.truststore.jks"
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: haveaniceday

volumes:
  kafka0-data:
  kafka1-data:

networks:
  infra:
    driver: bridge
```

File structure
```sh
.
├── README.md
├── docker-compose.yml
└── tls
    ├── kafka-0
    │   ├── kafka.keystore.jks
    │   └── kafka.truststore.jks
    └── kafka-1
        ├── kafka.keystore.jks
        └── kafka.truststore.jks
```

### What is the expected behavior?

Kafka brokers start successfully with no error.

### What do you see instead?

Kafka brokers won't start.

Errors
```sh
kafka-quorum-kafka-1-1  | [2023-06-02 18:44:56,572] ERROR [kafka-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=kafka.raft.KafkaNetworkChannel$$Lambda$670/0x00000008014876f0@7fde4260, destination=0, correlationId=9, clientId=raft-client-1, createdTimeMs=1685731496130, requestBuilder=VoteRequestData(clusterId='qYoMEZXcS_SKP2PzAl8-WA', topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=2, candidateId=1, lastOffsetEpoch=0, lastOffset=0)])])) (kafka.raft.RaftSendThread)
kafka-quorum-kafka-1-1  | [2023-06-02 18:44:56,573] ERROR Request OutboundRequest(correlationId=9, data=VoteRequestData(clusterId='qYoMEZXcS_SKP2PzAl8-WA', topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=2, candidateId=1, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1685731496130, destinationId=0) failed due to authentication error (kafka.raft.KafkaNetworkChannel)
kafka-quorum-kafka-1-1  | org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
kafka-quorum-kafka-1-1  | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
kafka-quorum-kafka-1-1  | 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:435)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:523)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:373)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:293)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka-quorum-kafka-1-1  | 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
kafka-quorum-kafka-1-1  | 	at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:74)
kafka-quorum-kafka-1-1  | 	at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:94)
kafka-quorum-kafka-1-1  | 	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka-quorum-kafka-1-1  | Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
kafka-quorum-kafka-1-1  | 	... 19 more
kafka-quorum-kafka-1-1  | Caused by: java.security.cert.CertPathValidatorException: signature check failed
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
kafka-quorum-kafka-1-1  | 	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
kafka-quorum-kafka-1-1  | 	... 24 more
kafka-quorum-kafka-1-1  | Caused by: java.security.SignatureException: Signature does not match.
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:422)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)
kafka-quorum-kafka-1-1  | 	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
kafka-quorum-kafka-1-1  | 	... 29 more
kafka-quorum-kafka-1-1  | [2023-06-02 18:44:56,575] ERROR [RaftManager nodeId=1] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=9, data=VoteResponseData(errorCode=13, topics=[]), sourceId=0) (org.apache.kafka.raft.KafkaRaftClient)
```

### Additional information

If I set `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS` to either `0@kafka-0:9093` or `1@kafka-1:9093` for kafka-0 and kafka-1 respectively, the kafka brokers start successfully. **The TLS works seperately for each**.
