### ISSUE TITLE
SuiteCRM docker image email enabling is failing

### ISSUE THREAD

**Issue by lazyest** [bitnami/containers#36431]
### Name and Version

bitnami/suitecrm:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploying it with docker-compose with this kind of variables
```yaml
  suitecrm:
    image: docker.io/bitnami/suitecrm
    restart: always
    environment:
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=${APP_PASSWORD}
      - SUITECRM_EMAIL=mail@fromme.com
      - SUITECRM_SMTP_HOST=smtp.sendgrid.net
      - SUITECRM_SMTP_PORT=587
      - SUITECRM_SMTP_USER=apikey
      - SUITECRM_SMTP_PASSWORD=${apikey}
      - SUITECRM_SMTP_PROTOCOL=tls
      - SUITECRM_SMTP_NOTIFY_NAME="my favorite suitecrm"
      - SUITECRM_SMTP_NOTIFY_ADDRESS=mail@fromme.com
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
```

### What is the expected behavior?

should create email setting with curl request inside container

### What do you see instead?
```
suitecrm_1          | suitecrm 10:49:42.76 INFO  ==> Configuring the HTTP port
suitecrm_1          | suitecrm 10:49:42.77 INFO  ==> Configuring Apache ServerTokens directive
suitecrm_1          | suitecrm 10:49:42.79 INFO  ==> Configuring PHP options
suitecrm_1          | suitecrm 10:49:42.80 INFO  ==> Setting PHP expose_php option
suitecrm_1          | suitecrm 10:49:42.80 INFO  ==> Setting PHP output_buffering option
suitecrm_1          | suitecrm 10:49:42.82 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
suitecrm_1          | suitecrm 10:49:42.88 INFO  ==> Ensuring SuiteCRM directories exist
suitecrm_1          | suitecrm 10:49:42.89 INFO  ==> Trying to connect to the database server
suitecrm_1          | suitecrm 10:49:42.91 INFO  ==> Running setup wizard
suitecrm_1          | suitecrm 10:49:50.53 INFO  ==> Starting apache in background
suitecrm_1          | suitecrm 10:49:55.64 INFO  ==> apache started
suitecrm_1          | suitecrm 10:49:55.64 INFO  ==> Configuring SMTP
suitecrm_1          | suitecrm 10:49:56.22 ERROR ==> An error occurred while trying to login to configure SMTP
```

### Additional information

From my point of view there was URL scheme change in 8.x branch of suitecrm leads current deploy logic to brake

After a quick debug I saw URL suffix ?action=Login&module=Users  is now redirecting to #/users/login 
so it should be fixed on https://github.com/bitnami/containers/blob/main/bitnami/suitecrm/8/debian-11/rootfs/opt/bitnami/scripts/libsuitecrm.sh
