### ISSUE TITLE
[bitnami/moodle] realpath: /bitnami/apache/conf: No such file or directory

### ISSUE THREAD

**Issue by Tejeswarreddy-3i** [bitnami/containers#36436]
### Name and Version

bitnami/moodle/4.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
version: '2'
services:
        #  mariadb:
        #    image: docker.io/bitnami/mariadb:10.6
        #    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #      - ALLOW_EMPTY_PASSWORD=yes
      #   - MARIADB_USER=moodle
      #    - MARIADB_PASSWORD=moodle  
      # - MARIADB_DATABASE=bitnami_moodle
      #  - MARIADB_CHARACTER_SET=utf8mb4
      # - MARIADB_COLLATE=utf8mb4_unicode_ci
      #    volumes:
      #  - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.2
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=10.46.2.98
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
        #   depends_on:
        #     - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

### What do you see instead?
```
moodle 12:34:32.44 
moodle 12:34:32.44 Welcome to the Bitnami moodle container
moodle 12:34:32.44 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 12:34:32.44 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle 12:34:32.44 
moodle 12:34:32.45 INFO  ==> ** Starting Moodle setup **
moodle 12:34:32.52 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
....................................++++
..................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
moodle 12:34:33.12 INFO  ==> Configuring Apache ServerTokens directive
moodle 12:34:33.19 INFO  ==> Configuring PHP options
moodle 12:34:33.19 INFO  ==> Setting PHP expose_php option
moodle 12:34:33.21 INFO  ==> Setting PHP output_buffering option
moodle 12:34:33.24 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 12:34:33.26 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 12:34:33.40 INFO  ==> Ensuring Moodle directories exist
moodle 12:34:33.47 INFO  ==> Trying to connect to the database server
moodle 12:34:38.57 INFO  ==> Running Moodle install script
```

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by more-zamani** [comment]
Hi Bitnami Team
I have this problem too.
I created MariaDB successfully and there is `my_database_name` on it without any table. But when I want to run 'moodle' container, it shows this error:

```
moodle 14:51:49.14 
moodle 14:51:49.14 Welcome to the Bitnami moodle container
moodle 14:51:49.15 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 14:51:49.15 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle 14:51:49.23 
moodle 14:51:49.23 INFO  ==> ** Starting Moodle setup **
moodle 14:51:49.25 DEBUG ==> Validating settings in APACHE_* environment variables
moodle 14:51:49.34 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
.....................................++++
................................................................................................................................................................................................++++
e is 65537 (0x010001)
Signature ok 
 subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
moodle 14:51:54.03 INFO  ==> Configuring Apache ServerTokens directive
moodle 14:51:54.03 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
moodle 14:51:54.24 INFO  ==> Configuring PHP options
moodle 14:51:54.25 INFO  ==> Setting PHP expose_php option
moodle 14:51:54.33 INFO  ==> Setting PHP output_buffering option
moodle 14:51:54.53 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 14:51:54.54 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 14:51:54.74 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle 14:51:55.13 INFO  ==> Ensuring Moodle directories exist
moodle 14:51:55.43 INFO  ==> Trying to connect to the database server
moodle 14:51:55.44 DEBUG ==> Executing SQL command: 
 SELECT 1
1
moodle 14:51:55.54 INFO  ==> Running Moodle install script
chroot: cannot change root directory to '/': Operation not permitted
```

How can I resolve this error?

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the platform you are using to run the container?

**Comment by more-zamani** [comment]
Yes. I use native platform https://hamravesh.com/

**Comment by javsalgar** [comment]
Hi,

It seems that there are kernel restrictions in this platform that are not allowing the operation. Could you confirm if the issue happens in another docker platform, for example locally?

**Comment by 24thsaint** [comment]
Hello, I'm having this issue as well just now.

![image](https://github.com/bitnami/containers/assets/8315544/54cf1130-8489-4839-8ada-2e06f9088e2e)

My `docker-compose.yml` looks like this:
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'F:/xampp/htdocs:/bitnami/moodle'
      - 'F:/xampp/htdocs/moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

Name and Version
bitnami/moodle/4.2

What architecture are you using?
```
Edition	Windows 11 Home
Version	22H2
Installed on	‎21 ‎Aug ‎2022
OS build	22621.1928
Experience	Windows Feature Experience Pack 1000.22644.1000.0
```

**Comment by gongomgra** [comment]
Hi @24thsaint,

Thanks for using Bitnami. Can you update the docker-compose by adding the `BITNAMI_DEBUG=true` environment variable to the `moodle` service and try again? That would give you a more detailed information about the issue.  

Additionally, do you know if the Moodle version is the same in your local installation (under XAMPP folder) and in the docker-compose?

**Comment by 24thsaint** [comment]
Hi @gongomgra ,

This has been resolved. Thank you for following up! We were using our own Moodle fork.

For others who are having similar issue, this is how we resolved it:

`docker-compose.yml`
```
version: '2'
services:
  mariadb:
    image: mariadb:10.6
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=usr_moodle
      - MARIADB_DATABASE=db_moodle
      - MARIADB_PASSWORD=pw_moodle
      - MARIADB_ROOT_PASSWORD=pw_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/app/mariadb'
    restart: always
  moodle:
    image: webdevops/php-apache:8.2
    environment:
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256M
      - PHP_DISMOD=cgi_module,zend_extension
    depends_on:
      - mariadb
    volumes:
      - 'F:/xampp/htdocs:/app'
    ports:
      - '8080:80'
      - '8443:443'
    links:
      - mariadb:database # <--- Take note of this link
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - mariadb:database
    environment:
      UPLOAD_LIMIT: 16M
      PMA_HOST: database
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

`config.php`
```
<?php  // Moodle configuration file

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'database'; # <---- IMPORTANT, it should say "database" coming from link in docker-compose.yml
$CFG->dbname    = 'db_moodle';
$CFG->dbuser    = 'usr_moodle';
$CFG->dbpass    = 'pw_moodle';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => '',
  'dbsocket' => '',
  'dbcollation' => 'utf8mb4_unicode_ci',
);

$CFG->wwwroot   = 'http://127.0.0.1:8080';
$CFG->dataroot  = '/app/moodledata';
$CFG->admin     = 'admin';

$CFG->directorypermissions = 0777;

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
```
