### ISSUE TITLE
[bitnami/redis-cluster] cluster node IP's not resolving after stack restart?

### ISSUE THREAD

**Issue by byErikas** [bitnami/containers#36672]
### Name and Version

bitnami/redis-cluster:7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In a docker swarm environment deploy a stack with this config:
```yaml
version: '3.8'

services:

  ## REDIS
  redis-0:
    image: bitnami/redis-cluster:7.0
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_NODES: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
    configs:
      - source: redis_config
        target: /opt/bitnami/redis/mounted-etc/overrides.conf
    secrets:
      - redis_password
    networks:
      - network-stack
    volumes:
      - volume-redis-0:/bitnami/redis/data
      
  redis-1:
    image: bitnami/redis-cluster:7.0
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_NODES: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
    configs:
      - source: redis_config
        target: /opt/bitnami/redis/mounted-etc/overrides.conf
    secrets:
      - redis_password
    networks:
      - network-stack
    volumes:
      - volume-redis-1:/bitnami/redis/data
      
  redis-2:
    image: bitnami/redis-cluster:7.0
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_NODES: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
    configs:
      - source: redis_config
        target: /opt/bitnami/redis/mounted-etc/overrides.conf
    secrets:
      - redis_password
    networks:
      - network-stack
    volumes:
      - volume-redis-2:/bitnami/redis/data
      
  redis-3:
    image: bitnami/redis-cluster:7.0
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_NODES: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
    configs:
      - source: redis_config
        target: /opt/bitnami/redis/mounted-etc/overrides.conf
    secrets:
      - redis_password
    networks:
      - network-stack
    volumes:
      - volume-redis-3:/bitnami/redis/data
      
  redis-4:
    image: bitnami/redis-cluster:7.0
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_NODES: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
    configs:
      - source: redis_config
        target: /opt/bitnami/redis/mounted-etc/overrides.conf
    secrets:
      - redis_password
    networks:
      - network-stack
    volumes:
      - volume-redis-4:/bitnami/redis/data
      
  redis-5:
    image: bitnami/redis-cluster:7.0
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      REDISCLI_AUTH_FILE: /run/secrets/redis_password
      REDIS_NODES: "redis-0 redis-1 redis-2 redis-3 redis-4 redis-5"
      REDIS_CLUSTER_CREATOR: "yes"
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP: 30
    configs:
      - source: redis_cluster_env
        target: /opt/bitnami/scripts/redis-cluster-env.sh
      - source: redis_config
        target: /opt/bitnami/redis/mounted-etc/overrides.conf
    secrets:
      - redis_password
    networks:
      - network-stack
    volumes:
      - volume-redis-5:/bitnami/redis/data
      
## END OF SERVICES ----------------------
## CONFIGS / SECRETS / VOLUMES / NETWORKS
configs:
  redis_cluster_env:
    external: true
    name: web_vast-redis-cluster-env
  redis_config:
    external: true
    name: web_vast-redis_config

secrets:
  redis_password:
    external: true
    name: web_vast-redis_password

volumes:
  volume-redis-0:
    name: web_vast-redis-0
  volume-redis-1:
    name: web_vast-redis-1
  volume-redis-2:
    name: web_vast-redis-2
  volume-redis-3:
    name: web_vast-redis-3
  volume-redis-4:
    name: web_vast-redis-4
  volume-redis-5:
    name: web_vast-redis-5

networks:
  network-stack:
    driver: overlay
    name: web_vast-local
```

After the cluster ir running and fully set up - shut it down, and then restart it.

### What is the expected behavior?

I'd expect that once the restart happens the IP's for the nodes master/slave address would get updated, as after the restart node IP's are dynamic, and have changed, yet the node is trying to reach an old address, or as the log attached below shows - an IP that doesn't even seem to have ever existed?

```
Changing old IP 10.0.30.17 by the new one 10.0.31.17
Changing old IP 10.0.30.21 by the new one 10.0.31.9
Changing old IP 10.0.30.2 by the new one 10.0.31.5
Changing old IP 10.0.30.9 by the new one 10.0.31.13
Changing old IP 10.0.30.11 by the new one 10.0.31.7
Changing old IP 10.0.30.7 by the new one 10.0.31.2
```
Yet the logs show a connection to:
```
1:S 06 Jun 2023 08:31:26.421 * Connecting to MASTER 10.0.30.22:6379
```

### What do you see instead?

This is the output from a node, after it has been restarted:

```
redis-cluster 08:31:11.09 
redis-cluster 08:31:11.09 Welcome to the Bitnami redis-cluster container
redis-cluster 08:31:11.09 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 08:31:11.10 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 08:31:11.10 
redis-cluster 08:31:11.10 INFO  ==> ** Starting Redis setup **
redis-cluster 08:31:11.13 INFO  ==> Initializing Redis
redis-cluster 08:31:11.15 INFO  ==> Setting Redis config file
Changing old IP 10.0.30.17 by the new one 10.0.31.17
Changing old IP 10.0.30.21 by the new one 10.0.31.9
Changing old IP 10.0.30.2 by the new one 10.0.31.5
Changing old IP 10.0.30.9 by the new one 10.0.31.13
Changing old IP 10.0.30.11 by the new one 10.0.31.7
Changing old IP 10.0.30.7 by the new one 10.0.31.2
redis-cluster 08:31:26.38 INFO  ==> ** Redis setup finished! **
1:C 06 Jun 2023 08:31:26.418 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Jun 2023 08:31:26.418 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 06 Jun 2023 08:31:26.418 # Configuration loaded
1:M 06 Jun 2023 08:31:26.419 * monotonic clock: POSIX clock_gettime
1:M 06 Jun 2023 08:31:26.419 * Node configuration loaded, I'm 667f60d470026bc1b7197c8bec4c93a4b94e0a04
1:M 06 Jun 2023 08:31:26.420 * Running mode=cluster, port=6379.
1:M 06 Jun 2023 08:31:26.420 # Server initialized
1:M 06 Jun 2023 08:31:26.420 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Jun 2023 08:31:26.420 * Reading RDB base file on AOF loading...
1:M 06 Jun 2023 08:31:26.420 * Loading RDB produced by version 7.0.11
1:M 06 Jun 2023 08:31:26.420 * RDB age 137 seconds
1:M 06 Jun 2023 08:31:26.420 * RDB memory usage when created 1.74 Mb
1:M 06 Jun 2023 08:31:26.420 * RDB is base AOF
1:M 06 Jun 2023 08:31:26.420 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 06 Jun 2023 08:31:26.420 * DB loaded from base file appendonly.aof.2.base.rdb: 0.000 seconds
1:M 06 Jun 2023 08:31:26.420 * DB loaded from append only file: 0.000 seconds
1:M 06 Jun 2023 08:31:26.420 * Opening AOF incr file appendonly.aof.2.incr.aof on server start
1:M 06 Jun 2023 08:31:26.420 * Ready to accept connections
1:S 06 Jun 2023 08:31:26.421 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
1:S 06 Jun 2023 08:31:26.421 * Connecting to MASTER 10.0.30.22:6379
1:S 06 Jun 2023 08:31:26.421 * MASTER <-> REPLICA sync started
1:S 06 Jun 2023 08:31:26.421 # Cluster state changed: ok
1:S 06 Jun 2023 08:31:44.370 # Cluster state changed: fail
1:S 06 Jun 2023 08:32:27.606 # Timeout connecting to the MASTER...
1:S 06 Jun 2023 08:32:27.606 * Reconnecting to MASTER 10.0.30.22:6379 after failure
1:S 06 Jun 2023 08:32:27.606 * MASTER <-> REPLICA sync started
```

### Additional information

The whole stack is running in a docker swarm environment

I am using a minor adjustment on the node creator service `redis-5`, 
that can be seen in the compose, `redis_cluster_env`, the contents are that of a #35992, as that gives me a chance to set `REDISCLI_AUTH` via a secret.

This is the logs of the cluster creator node `redis-5` on it's first run, when everything seems to run fine:
```
redis-cluster 08:28:16.66 
redis-cluster 08:28:16.66 Welcome to the Bitnami redis-cluster container
redis-cluster 08:28:16.66 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 08:28:16.66 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 08:28:16.66 
redis-cluster 08:28:16.67 INFO  ==> ** Starting Redis setup **
redis-cluster 08:28:16.70 INFO  ==> Initializing Redis
redis-cluster 08:28:16.72 INFO  ==> Setting Redis config file
Storing map with hostnames and IPs
redis-cluster 08:28:32.06 INFO  ==> ** Redis setup finished! **
139:C 06 Jun 2023 08:28:32.105 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
139:C 06 Jun 2023 08:28:32.105 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=139, just started
139:C 06 Jun 2023 08:28:32.105 # Configuration loaded
139:M 06 Jun 2023 08:28:32.106 * monotonic clock: POSIX clock_gettime
139:M 06 Jun 2023 08:28:32.106 * No cluster configuration found, I'm 667f60d470026bc1b7197c8bec4c93a4b94e0a04
139:M 06 Jun 2023 08:28:32.108 * Running mode=cluster, port=6379.
139:M 06 Jun 2023 08:28:32.108 # Server initialized
139:M 06 Jun 2023 08:28:32.108 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
139:M 06 Jun 2023 08:28:32.109 * Creating AOF base file appendonly.aof.1.base.rdb on server start
139:M 06 Jun 2023 08:28:32.110 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
139:M 06 Jun 2023 08:28:32.110 * Ready to accept connections
Waiting 30s before querying node ip addresses
139:M 06 Jun 2023 08:29:02.320 # configEpoch set to 6 via CLUSTER SET-CONFIG-EPOCH
139:M 06 Jun 2023 08:29:02.465 # Address updated for node ab0a8315744a1f5a2e15bc7ed8a7fc33e1f57d80, now 10.0.30.18:6379
>>> Performing hash slots allocation on 6 nodes...
Master[0] -> Slots 0 - 5460
Master[1] -> Slots 5461 - 10922
Master[2] -> Slots 10923 - 16383
Adding replica 10.0.30.11:6379 to 10.0.30.17:6379
Adding replica 10.0.30.7:6379 to 10.0.30.21:6379
Adding replica 10.0.30.9:6379 to 10.0.30.2:6379
M: ab0a8315744a1f5a2e15bc7ed8a7fc33e1f57d80 10.0.30.17:6379
   slots:[0-5460] (5461 slots) master
M: 63958a03d53e7e997477da6318ca2b8b084825b1 10.0.30.21:6379
   slots:[5461-10922] (5462 slots) master
M: ea1498378c941f2f6376eec67661383447197672 10.0.30.2:6379
   slots:[10923-16383] (5461 slots) master
S: 6494fd1eac64fe0b2a63c552ecd1b8042cc4bb20 10.0.30.9:6379
   replicates ea1498378c941f2f6376eec67661383447197672
S: 432a5ed5aee529a400b61c1bbdf1da477b7e314b 10.0.30.11:6379
   replicates ab0a8315744a1f5a2e15bc7ed8a7fc33e1f57d80
S: 667f60d470026bc1b7197c8bec4c93a4b94e0a04 10.0.30.7:6379
   replicates 63958a03d53e7e997477da6318ca2b8b084825b1
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join
.139:S 06 Jun 2023 08:29:04.326 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
139:S 06 Jun 2023 08:29:04.326 * Connecting to MASTER 10.0.30.22:6379
139:S 06 Jun 2023 08:29:04.326 * MASTER <-> REPLICA sync started
139:S 06 Jun 2023 08:29:04.327 # Cluster state changed: ok
139:S 06 Jun 2023 08:29:04.327 * Non blocking connect for SYNC fired the event.
139:S 06 Jun 2023 08:29:04.327 * Master replied to PING, replication can continue...
139:S 06 Jun 2023 08:29:04.327 * Trying a partial resynchronization (request a41927973dd068da57b14712b4137d4a8ead9cfb:1).
>>> Performing Cluster Check (using node 10.0.30.17:6379)
M: ab0a8315744a1f5a2e15bc7ed8a7fc33e1f57d80 10.0.30.17:6379
   slots:[0-5460] (5461 slots) master
   1 additional replica(s)
S: 667f60d470026bc1b7197c8bec4c93a4b94e0a04 10.0.30.8:6379
   slots: (0 slots) slave
   replicates 63958a03d53e7e997477da6318ca2b8b084825b1
M: ea1498378c941f2f6376eec67661383447197672 10.0.30.3:6379
   slots:[10923-16383] (5461 slots) master
   1 additional replica(s)
S: 432a5ed5aee529a400b61c1bbdf1da477b7e314b 10.0.30.12:6379
   slots: (0 slots) slave
   replicates ab0a8315744a1f5a2e15bc7ed8a7fc33e1f57d80
S: 6494fd1eac64fe0b2a63c552ecd1b8042cc4bb20 10.0.30.10:6379
   slots: (0 slots) slave
   replicates ea1498378c941f2f6376eec67661383447197672
M: 63958a03d53e7e997477da6318ca2b8b084825b1 10.0.30.22:6379
   slots:[5461-10922] (5462 slots) master
   1 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
Cluster correctly created
redis-server "${ARGS[@]}"
139:S 06 Jun 2023 08:29:09.480 * Full resync from master: 99f008f3aa93a5ac760c522ec67d92b618b95a5f:14
139:S 06 Jun 2023 08:29:09.481 * MASTER <-> REPLICA sync: receiving streamed RDB from master with EOF to disk
139:S 06 Jun 2023 08:29:09.481 * Discarding previously cached master state.
139:S 06 Jun 2023 08:29:09.481 * MASTER <-> REPLICA sync: Flushing old data
139:S 06 Jun 2023 08:29:09.481 * MASTER <-> REPLICA sync: Loading DB in memory
139:S 06 Jun 2023 08:29:09.482 * Loading RDB produced by version 7.0.11
139:S 06 Jun 2023 08:29:09.482 * RDB age 0 seconds
139:S 06 Jun 2023 08:29:09.482 * RDB memory usage when created 1.83 Mb
139:S 06 Jun 2023 08:29:09.482 * Done loading RDB, keys loaded: 0, keys expired: 0.
139:S 06 Jun 2023 08:29:09.482 * MASTER <-> REPLICA sync: Finished with success
139:S 06 Jun 2023 08:29:09.482 * Creating AOF incr file temp-appendonly.aof.incr on background rewrite
139:S 06 Jun 2023 08:29:09.483 * Background append only file rewriting started by pid 256
256:C 06 Jun 2023 08:29:09.484 * Successfully created the temporary AOF base file temp-rewriteaof-bg-256.aof
256:C 06 Jun 2023 08:29:09.485 * Fork CoW for AOF rewrite: current 0 MB, peak 0 MB, average 0 MB
139:S 06 Jun 2023 08:29:09.529 * Background AOF rewrite terminated with success
139:S 06 Jun 2023 08:29:09.529 * Successfully renamed the temporary AOF base file temp-rewriteaof-bg-256.aof into appendonly.aof.2.base.rdb
139:S 06 Jun 2023 08:29:09.529 * Successfully renamed the temporary AOF incr file temp-appendonly.aof.incr into appendonly.aof.2.incr.aof
139:S 06 Jun 2023 08:29:09.530 * Removing the history file appendonly.aof.1.incr.aof in the background
139:S 06 Jun 2023 08:29:09.530 * Removing the history file appendonly.aof.1.base.rdb in the background
139:S 06 Jun 2023 08:29:09.531 * Background AOF rewrite finished successfully
```

Is this a configuration issue? Am I possibly missing some environment variables?
