### ISSUE TITLE
[bitnami/redmine] : Add Custom configuration.yml

### ISSUE THREAD

**Issue by diogomurta** [bitnami/containers#36749]
### Name and Version

bitnami/redmine

### What is the problem this feature will solve?

Possibility for "customPostInitScripts" to run even after the container restart. Currently, it only runs on the first boot.

### What is the feature you are proposing to solve the problem?

Customized settings from the "configuration.yml" file. Currently, in all versions, it is not possible to enter SMTP configs like this:
```yaml
mail_delivery:
     delivery_method: :smtp
     smtp_settings:
       address: smtp-relay.example.com
       port: "25"
       domain: "example.com"
```
