### ISSUE TITLE
bitnami/postgresql-repmgr - can't edit postgresql.conf

### ISSUE THREAD

**Issue by snoby** [bitnami/containers#36746]
### Name and Version

bitnami/postgresql-repmgr 15.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.) with an existing implementation where pg-2 has been setup and a config has been edited, setup pg-1 from a blank slate.
2.) when pg-1 starts  it will not stay running where  the postgresql.conf can be up and edited to match the conf in pg-2.  

I've attempted to go in and hand edit the postgresql.conf file in the {data_dir}/conf/postgresql.conf file however this seems to be over written on each restart.  ( the data_dir is mounted to '/bitnami/postgresql/'}

### What is the expected behavior?

even if the container can't continue there has to be some way for me to pass in a custom postgresql.conf file.  At the moment that file seems to be generated with host specific values at least in the connection string.

### What do you see instead?

boot is aborted because the standby config doesn't match the master config.

```
Jun 07 10:21:33 prod-pg-1 postgres[28515]: 2023-06-07 14:21:33.991 GMT [202] LOG:  entering standby mode
Jun 07 10:21:33 prod-pg-1 postgres[28515]: 2023-06-07 14:21:33.994 GMT [202] FATAL:  recovery aborted because of insufficient parameter settings
Jun 07 10:21:33 prod-pg-1 postgres[28515]: 2023-06-07 14:21:33.994 GMT [202] DETAIL:  max_connections = 100 is a lower setting than on the primary server, where its value was 2700.
Jun 07 10:21:33 prod-pg-1 postgres[28515]: 2023-06-07 14:21:33.994 GMT [202] HINT:  You can restart the server after making the necessary configuration changes.
```

### Additional information

I've noticed that sometimes (even with the same configuration) the volume mount to '/bitnami/repmgr/conf/'  is not populated with a config to edit even when running.

**Comment by snoby** [comment]
i would add that by manually adding into the env 
` --env POSTGRESQL_MAX_CONNECTIONS=2700`
which matches the master, i can start the slave, however the postgresql.conf still is not available to be edited.  It is not mounted in 
`/bitnami/repmgr/conf/`

I've followed these steps perfectly
https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/README.md#configuration-file

`  -v /etc/postgres/running/:/bitnami/repmgr/conf/  \`
however the conf file is never available to be edited

**Comment by joancafom** [comment]
Hi @snoby 

Thanks for creating the issue! Could you please add a detailed list of the steps you are following in order to try and reproduce the issue on my side? If you are using docker-compose (which assume you don't, based on your shared code), I would also be nice if you could attach the `docker-compose.yml` file 😁

**Comment by snoby** [comment]
> Hi @snoby
> 
> Thanks for creating the issue! Could you please add a detailed list of the steps you are following in order to try and reproduce the issue on my side? If you are using docker-compose (which assume you don't, based on your shared code), I would also be nice if you could attach the `docker-compose.yml` file 😁

I believe the issue is that their is some situation where the container gets in a state where the postgresql.conf is not mounted to be "edited".  The instructions sort of make sense but after much trial and error i got it working and i can now edit the postgresql.conf file with my ansible playbooks.  

basically you have to have your docker run command have these volume mounts
```
   -v {{ POSTGRES_INIT_SCRIPTS_DIR }}/:/docker-entrypoint-initdb.d/ \
   -v {{ POSTGRES_ADDITIONAL_CONFIG_DIR }}/:/bitnami/postgresql/conf/conf.d/  \
   -v {{ POSTGRES_RUNNING_CONFIG_DIR }}/:/bitnami/repmgr/conf/  \
   -v {{ POSTGRES_REFERENCE_MGR_CONFIG_DIR }}/:/opt/bitnami/repmgr/conf/  \
   -v {{ POSTGRES_REFERENCE_PSQ_CONFIG_DIR }}/:/opt/bitnami/postgresql/conf/  \
   ```
   then when you want to edit and update the postgresql.conf file you basically do these two steps
   ```yaml
     ansible.builtin.copy:
    src: "{{ POSTGRES_REFERENCE_PSQ_CONFIG_DIR }}/postgresql.conf"
    dest: "{{ POSTGRES_RUNNING_CONFIG_DIR }}/postgresql.conf"
    mode: '0777'
    remote_src: yes
  tags: tweaks
  ```
  
  Then run your changes 
  ```yaml
  - name: Fix up running posgresql  config file
  lineinfile:
    path: "{{ POSTGRES_RUNNING_CONFIG_DIR }}/postgresql.conf"
    regexp: "{{item.From}}"
    line: "{{item.To}}"
    state: present
  loop:
    - {From: '^#max_connections.+$', To: 'max_connections = 500'}
  ```
   
   
   So we can close the ticket, but for the next soul that gets stuck on not being able to mount and edit the postgresql.conf file, use the above as a reference.
