### ISSUE TITLE
Bitnami kafka cluster brokers fail to start

### ISSUE THREAD

**Issue by plegault3397** [bitnami/containers#37032]
### Name and Version

bitnami/kafka:2.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Windows 11 
Docker version 24.0.2, build cb74dfc
bitnami/kafka:2.7.0
yml file:
```yaml
version: '2'
services:

#Zookeeper Service.
#Image Tag: bitnami/zookeeper:3.6.2

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper

#Kafka Service
#Image Tag: bitnami/kafka:2.7.0

  kafka1:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9092:9092'
      - '29092:29092'
      
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker1
    
    depends_on:
      - "zookeeper"
      
  kafka2:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9093:9093'
      - '29093:29093'
      
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29093,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:29093,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker2
    
    depends_on:
      - "zookeeper"
    
  kafka3:
    image: 'bitnami/kafka:latest'
    restart: "no"
    ports:
      - '9094:9094'
      - '29094:29094'
      
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29094,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:29094,EXTERNAL://localhost:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    container_name: kafka-broker3
    
    depends_on:
      - "zookeeper"
      
#KafDrop UI for management
#Image Tag: obsidiandynamics/kafdrop:3.27.0

  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    restart: "no"
    ports:
      - 9001:9000
    
    environment:
      - KAFKA_BROKERCONNECT=kafka1:29092,kafka2:29093,kafka3:29094
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    
    container_name: kafdrop
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"
```

### What is the expected behavior?

This worked when I was running on windows 10.
Now I have re-installed Windows 11.

zookeeper and brokers start up without any issues.

### What do you see instead?

Zookeeper starts fine

Brokers start and immediately exit without any errors
