### ISSUE TITLE
Launching Kafka specifing data volume fails

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/containers#37205]
### Name and Version

bitnami/kafka 22.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

This is my docker-compose file

```yaml
version: '3.8'

services:
  broker-1:
    container_name: 'broker-1'
    image: bitnami/kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka:/bitnami/kafka/data/:rw
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=A370i42nQuCtnpFN-7I41Q
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker-1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
```

### What is the expected behavior?

I followed the documentation, and as stated I'm supposed to create a bind mount to /bitnami/kafka/data

### What do you see instead?

When I launch the file I get to this point and the container exits with code 1

```
broker-1  | kafka 17:43:29.91 
broker-1  | kafka 17:43:29.91 Welcome to the Bitnami kafka container
broker-1  | kafka 17:43:29.91 Subscribe to project updates by watching https://github.com/bitnami/containers
broker-1  | kafka 17:43:29.91 Submit issues and feature requests at https://github.com/bitnami/containers/issues
broker-1  | kafka 17:43:29.91 
broker-1  | kafka 17:43:29.91 INFO  ==> ** Starting Kafka setup **
broker-1  | kafka 17:43:29.99 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
broker-1  | kafka 17:43:30.01 INFO  ==> Initializing Kafka...
broker-1  | kafka 17:43:30.03 INFO  ==> No injected configuration files found, creating default config files
broker-1  | kafka 17:43:30.39 INFO  ==> Initializing KRaft...
broker-1  | kafka 17:43:30.40 INFO  ==> Formatting storage directories to add metadata...
broker-1 exited with code 1

```

**Comment by carrodher** [comment]
Could you point us to the documentation you followed?

**Comment by ETisREAL** [comment]
Hi,

I folloewd the instructions on your dockerhub page:  https://hub.docker.com/r/bitnami/kafka

In particuar:
### Persisting your data
```
kafka:
  ...
  volumes:
    - /path/to/kafka-persistence:/bitnami/kafka
  ...
```

**Comment by jotamartos** [comment]
Hi, 

This seems to be a permissions issue. I just tested this docker-compose.yml file 

```
version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "./kafka:/bitnami/kafka"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
```

and used `./kafka` as folder to persist the data. I created this folder with these commands 

```
mkdir ./kafka
sudo chown 1001:1001 ./kafka
```

There is a note in the README file that mentions this 

> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID `1001`.
