### ISSUE TITLE
moodle can't start if delete env ALLOW_EMPTY_PASSWORD=yes

### ISSUE THREAD

**Issue by qiaofeng1227** [bitnami/containers#37308]
### Name and Version

bitnami/moodle:4.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. when I use this docker-compose.yml, it it works fine
```yaml
version: "3.8"

services:
     
  moodle:
    image: docker.io/bitnami/moodle:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    environment:
      - MOODLE_DATABASE_HOST=${APP_NAME}-db
      - MOODLE_DATABASE_PORT_NUMBER=${APP_DB_MARIADB_PORT}
      - MOODLE_DATABASE_USER=${APP_DB_MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MOODLE_DATABASE_NAME=${APP_DB_MARIADB_NAME}
      - MOODLE_USERNAME=${APP_USER}
      - MOODLE_PASSWORD=${APP_PASSWORD}
    ports:
      - '${APP_HTTP_PORT}:8080'
    env_file:
      - .env
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

  mariadb:
    image: docker.io/bitnami/mariadb:${APP_DB_MARIADB_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${APP_DB_MARIADB_USER}
      - MARIADB_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MARIADB_DATABASE=${APP_DB_MARIADB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - ${APP_DB_MARIADB_PORT}:3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
```
2.  when I delete env `ALLOW_EMPTY_PASSWORD=yes`, it does not work.

```yaml
version: "3.8"

services:
     
  moodle:
    image: docker.io/bitnami/moodle:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    environment:
      - MOODLE_DATABASE_HOST=${APP_NAME}-db
      - MOODLE_DATABASE_PORT_NUMBER=${APP_DB_MARIADB_PORT}
      - MOODLE_DATABASE_USER=${APP_DB_MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MOODLE_DATABASE_NAME=${APP_DB_MARIADB_NAME}
      - MOODLE_USERNAME=${APP_USER}
      - MOODLE_PASSWORD=${APP_PASSWORD}
    ports:
      - '${APP_HTTP_PORT}:8080'
    env_file:
      - .env
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

  mariadb:
    image: docker.io/bitnami/mariadb:${APP_DB_MARIADB_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${APP_DB_MARIADB_USER}
      - MARIADB_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MARIADB_DATABASE=${APP_DB_MARIADB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - ${APP_DB_MARIADB_PORT}:3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
```

### What is the expected behavior?

I can‘t accesss moodle web page 

### What do you see instead?

3. moodle logs as following:
```
moodle 01:53:45.37 Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 01:53:45.37 Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle 01:53:45.37 
moodle 01:53:45.37 INFO  ==> ** Starting Moodle setup **
realpath: /bitnami/apache/conf: No such file or directory
moodle 01:53:45.40 INFO  ==> Configuring Apache ServerTokens directive
moodle 01:53:45.43 INFO  ==> Configuring PHP options
moodle 01:53:45.43 INFO  ==> Setting PHP opcache.enable option
moodle 01:53:45.44 INFO  ==> Setting PHP expose_php option
moodle 01:53:45.45 INFO  ==> Setting PHP max_execution_time option
moodle 01:53:45.46 INFO  ==> Setting PHP max_input_time option
moodle 01:53:45.46 INFO  ==> Setting PHP memory_limit option
moodle 01:53:45.47 INFO  ==> Setting PHP post_max_size option
moodle 01:53:45.48 INFO  ==> Setting PHP upload_max_filesize option
moodle 01:53:45.49 INFO  ==> Setting PHP output_buffering option
moodle 01:53:45.51 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 01:53:45.52 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 01:53:45.55 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
moodle 01:53:45.59 INFO  ==> Ensuring Moodle directories exist
moodle 01:53:45.62 INFO  ==> Trying to connect to the database server
moodle 01:55:58.82 ERROR ==> Could not connect to the database

```
4. docker status as following:
```
root@iZbp10mtbz0wjsmf4s7528Z:/data/apps/moodle# docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                          PORTS                                                                                                             NAMES
cea907711884   bitnami/moodle:4.2                "/opt/bitnami/script…"   6 minutes ago    Up 2 minutes                    8443/tcp, 0.0.0.0:9001->8080/tcp, :::9001->8080/tcp                                                               moodle
a138166f1a4c   bitnami/mariadb:10.6              "/opt/bitnami/script…"   6 minutes ago    Restarting (1) 42 seconds ago                                                                                                                     moodle-db

```

**Comment by qiaofeng1227** [comment]
[# ALLOW_EMPTY_PASSWORD is recommended only for development. ](https://github.com/bitnami/containers/blob/main/bitnami/moodle/docker-compose.yml).  


Can you give me an example of docker composite. yml in a production environment?

**Comment by dgomezleon** [comment]
Hello @qiaofeng1227 ,

From [MariaDB README.md](https://github.com/bitnami/containers/tree/main/bitnami/mariadb#setting-the-root-password-on-first-run):

```
**Warning** The `MARIADB_ROOT_USER` user is always created with remote access. It's suggested that the `MARIADB_ROOT_PASSWORD` env variable is always specified to set a password for the `MARIADB_ROOT_USER` user. In case you want to allow the `MARIADB_ROOT_USER` user to access the database without a password set the \
environment variable `ALLOW_EMPTY_PASSWORD=yes`. **This is recommended only for development**.

### Allowing empty passwords

By default the MariaDB image expects all the available passwords to be set. In order to allow empty passwords, it is necessary to set the `ALLOW_EMPTY_PASSWORD=yes` env variable. This env variable is only recommended for testing or development purposes. We strongly recommend specifying the `MARIADB_ROOT_PASSWORD` fo\
r any other scenario.
```

I hope it helps

**Comment by qiaofeng1227** [comment]
thanks very much, it it works fine by edit like this:
```
# refer to: https://github.com/bitnami/bitnami-docker-moodle
# image: https://hub.docker.com/r/bitnami/moodle

version: "3.8"

services:
     
  moodle:
    image: docker.io/bitnami/moodle:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_DATABASE_HOST=${APP_NAME}-db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${APP_DB_MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MOODLE_DATABASE_NAME=${APP_DB_MARIADB_NAME}
      - MOODLE_USERNAME=${APP_USER}
      - MOODLE_PASSWORD=${APP_PASSWORD}
    ports:
      - '${APP_HTTP_PORT}:8080'
    env_file:
      - .env
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

  mariadb:
    image: docker.io/bitnami/mariadb:${APP_DB_MARIADB_VERSION}
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${APP_DB_MARIADB_USER}
      - MARIADB_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${APP_DB_MARIADB_PASSWORD}
      - MARIADB_DATABASE=${APP_DB_MARIADB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - ${APP_DB_MARIADB_PORT}:3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:

networks:
  default:
    name: ${APP_NETWORK}
    external: true

```
