### ISSUE TITLE
[bitnami/openldap] Does not accept symlinks for certificate files

### ISSUE THREAD

**Issue by melissaboiko** [bitnami/containers#3732]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

Certificate files which are symlinks (for example, the ones managed by Letsencrypt certbot) are rejected by the validation scripts.

That's probably because they're testing with bash `[ -f ]`, which only accepts regular files.

To reproduce, point LDAP_TLS_CERT_FILE to a symlink.  For example, if `/path/to/certs/certs.pem` on the host is the symlink:

```yaml
services:
  openldap:
    # [...]
    environment:
      # [...]
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/certs/cert.pem
      - LDAP_TLS_KEY_FILE=/certs/privkey.pem
      - LDAP_TLS_CA_FILE=/certs/ca-certificates.crt
      - LDAP_TLS_DH_PARAMS_FILE=/certs/ssl-dhparams.pem
      # [...]
    volumes:
      - /path/to/certs:/certs

```

### What do you see instead?

```bash
$ docker-compose up
openldap_1  |  14:58:34.01 INFO  ==> \
    ** Starting LDAP setup **
openldap_1  |  14:58:34.04 INFO  ==> \
    Validating settings in LDAP_* env vars
openldap_1  |  14:58:34.04 ERROR ==> \
    The X.509 certificate file in the specified path /certs/fullchain.pem does not exist
openldap_1  |  14:58:34.04 ERROR ==> \
    The private key file in the specified path /certs/privkey.pem does not exist

$ ls /path/to/certs/fullchain.pem /path/to/certs/privkey.pem
/path/to/certs/fullchain.pem /path/to/certs/privkey.pem
$
```

If the certificates are replaced by copies rather than symlinks, the problem disappears.
