### ISSUE TITLE
[bitnami/redis-cluster] Cluster no longer allows having no password for the default user

### ISSUE THREAD

**Issue by ewilliamson-patreon** [bitnami/containers#37757]
### Name and Version

bitnami/redis-cluster:6.2.12-debian-11-r19 (the most recent 7.0 as well)

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1.) set up a redis-cluster using `ALLOW_EMPTY_PASSWORD`
```yaml
version: '2'
services:

  redis-cluster-1:
    image: docker.io/bitnami/redis-cluster:6.2.12-debian-11-r19
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3 redis-cluster-4 redis-cluster-5

  redis-cluster-2:
    image: docker.io/bitnami/redis-cluster:6.2.12-debian-11-r19
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3 redis-cluster-4 redis-cluster-5

  redis-cluster-3:
    image: docker.io/bitnami/redis-cluster:6.2.12-debian-11-r19
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3 redis-cluster-4 redis-cluster-5

  redis-cluster-4:
    image: docker.io/bitnami/redis-cluster:6.2.12-debian-11-r19
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3 redis-cluster-4 redis-cluster-5

  redis-cluster-5:
    image: docker.io/bitnami/redis-cluster:6.2.12-debian-11-r19
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3 redis-cluster-4 redis-cluster-5

  redis-cluster-0:
    image: docker.io/bitnami/redis-cluster:6.2.12-debian-11-r19
    depends_on:
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3
      - redis-cluster-4
      - redis-cluster-5
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_NODES: redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3 redis-cluster-4 redis-cluster-5
      REDIS_CLUSTER_CREATOR: yes
      BITNAMI_DEBUG: 1
```

2.) run `docker compose up`

### What is the expected behavior?

The cluster should successfully boot up (this is what happens when we swap out the image for `bitnami/redis-cluster:6.2.12-debian-11-r18`)

### What do you see instead?

The cluster fails to boot up with auth errors
```
binami-redis-cluster-redis-cluster-0-1  | AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
binami-redis-cluster-redis-cluster-0-1  | Node redis-cluster-0 not ready, waiting for all the nodes to be ready...
```

### Additional information

I expect it is changed due to https://github.com/bitnami/containers/pull/35992 . I think the inclusion of `export REDISCLI_AUTH="${REDISCLI_AUTH:-}"` which will define the variable `REDISCLI_AUTH` as the empty string if it is not defined.

I believe the empty string is read by the redis cli [here](https://github.com/redis/redis/blob/unstable/src/redis-cli.c#L2973-L2975) and treated as auth instead of no auth (which having it undefined would do)

I can make a change that will only export that variable if it is defined (as opposed to exporting the empty string) if we think that is the best approach to still support "ALLOW_EMPTY_PASSWORD"
