### ISSUE TITLE
[bitnami/openresty] module 'jwt' not found

### ISSUE THREAD

**Issue by neelsingh98** [bitnami/containers#37802]
### Name and Version

bitnami/openresty

### What architecture are you using?

arm64

### What steps will reproduce the bug?

i am not able to run the openresty nginx, below is my docker-compose file
inside my lua folder i have 'jwt.lua' and 'remove-alb.lua'

version: "3"
```
services:
  router:
    image: bitnami/openresty:latest
    volumes:
      - ./spa.conf:/opt/bitnami/openresty/nginx/conf/server_blocks/spa.conf:ro
      - ./nginx.conf:/opt/bitnami/openresty/nginx/conf/nginx.conf:ro
      - ./lua:/opt/bitnami/openresty/nginx/lua/
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - default

networks:
  ? default
```

### What is the expected behavior?

i want when i run my container it should take me to the specified landing page but instead giving the the 500 internal server error

### What do you see instead?

![image](https://github.com/bitnami/containers/assets/109542602/31caa3e6-7d90-4157-93e4-5fe51f9c7232)
i see this error that module 'jwt' not found
