### ISSUE TITLE
[bitnami][container][postgresql] 

### ISSUE THREAD

**Issue by moutyque** [bitnami/containers#38265]
### Name and Version

bitnami/postgresql:14.8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Following the documentation: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#creating-a-database-user-on-first-run
I wrote this docker file
```yaml
version: '2.1'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:14.8.0
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"
volumes:
  postgresql_data:
    driver: local
```

Laucnh it: `docket compose up -d`
Try to connect to the postgre container in CLI: `psql -h localhost -p 5432 -U my_user -d my_database`

Got the following log:
```
2023-06-20T17:42:07.463725476Z 2023-06-20 17:42:07.463 GMT [283] DETAIL:  Role "my_user" does not exist.
```
And I cannot connect with my_user

### What is the expected behavior?

Can connect with my_user and my_password

### What do you see instead?
```
2023-06-20 17:41:52.617 GMT [282] DETAIL:  Role "my_user" does not exist.
2023-06-20T17:41:52.618104872Z 	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2023-06-20T17:42:07.463670061Z 2023-06-20 17:42:07.463 GMT [283] FATAL:  password authentication failed for user "my_user"
```
### Additional information

I guess the creation of the user define with the variable POSTGRESQL_USERNAME is not working.
Using default posgres user works fine but I wanted to use a dedicated user.
How can I achieve that?

Thx
