### ISSUE TITLE
Ability to check that PGBouncer is Ready

### ISSUE THREAD

**Issue by jlevertov** [bitnami/containers#38425]
### Name and Version

bitnami/pgbouncer:1.19.1

### What is the problem this feature will solve?

I am using this image in Kubernetes, and I would like the ability to add Readiness/Liveness probes to determine that the service is ready to accept connection from the application.

### What is the feature you are proposing to solve the problem?

Add an HTTP API or a script which I will be able to run as a `postInit` script which will help me determine that the service is up and ready

### What alternatives have you considered?

* Writing a small SQL script like `select 1;` But there is no PSQL in the container so I don't have any way to run it

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by derhuerst** [comment]
I'm using the following configuring in a Docker-Compose-based project, and I'm sure it can be adapted to Kubernetes markup:

```
    healthcheck:
      # pgbouncer exposes a `pgbouncer` "meta database", providing an interface for statistics and to administer the instance. We use it here to check if pgbouncer is working properly.
      test: 'env PGPASSWORD="$$POSTGRESQL_PASSWORD" psql -p 6432 -U "$$POSTGRESQL_USERNAME" pgbouncer -b -c "SHOW USERS" >/dev/null'
      interval: 5s
      timeout: 5s
      retries: 6
```

It would be much more helpful though if **the `bitnami/pgbouncer` image provided this out-of-the-box**, using a `HEALTHCHECK` directive in the Dockerfile.
