### ISSUE TITLE
[bitnami/mongodb] Can't run MongoDB container as root

### ISSUE THREAD

**Issue by ThallesP** [bitnami/containers#38804]
### Name and Version

bitnami/mongodb:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run the following docker-compose file:

```yaml
version: "3.8"
services:
  mongodb:
    image: bitnami/mongodb:latest
    user: root
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=test123
      - MONGODB_REPLICA_SET_KEY=test123
```

### What is the expected behavior?

It should be able to run as root, according to your [docs](https://docs.bitnami.com/tutorials/work-with-non-root-containers/)

### What do you see instead?

When trying to run it as `root`, it exists with `exit code 2`. No errors in output.
Without running as root, it works perfectly.

![image](https://github.com/bitnami/containers/assets/76017384/641d58b6-393c-44de-8570-abde64b43a85)

### Additional information

When getting a shell into the container and trying to execute the `/opt/bitnami/scripts/mongodb/run.sh` directly, I get the error below:

![image](https://github.com/bitnami/containers/assets/76017384/80f9fe09-d7c4-4589-9ce7-a711747e17e8)
