### ISSUE TITLE
[bitnami/minio] SNSD situation: change MINIO_DATA_DIR not affected

### ISSUE THREAD

**Issue by haojingcn** [bitnami/containers#39426]
### Name and Version

bitnami/minio 12.1.10

### What architecture are you using?

amd64

#### environment
x86: arch
kubernetes: v1.19.15
minio chart: 12.6.5

#### config
minio-values.yaml
```yaml
---
persistence:
  enabled: false
  mountPath: "/data-minio"
ingress:
  enabled: true
auth:
  rootUser: "admin"
  rootPassword: "xxxx"
mode: standalone
```

#### run
```
helm repo add my-repo https://charts.bitnami.com/bitnami
helm install my-minio -f minio-values.yaml my-repo/minio
kubectl exec -it my-minio-7c7957679c-dmqnr -- bash
```

#### error
minio is not use /data-minio, still use /data

### What is the expected behavior?

use /data-minio, instead of /data

### What do you see instead?

![image](https://github.com/bitnami/containers/assets/3139872/41bc6a00-9578-420b-be53-5e0ff085ea54)
