### ISSUE TITLE
[bitnami/airflow] AttributeError: module 'airflow.providers.apache.pinot.hooks.pinot' has no attribute 'PinotHook'

### ISSUE THREAD

**Issue by kaoutaar** [bitnami/containers#40214]
### Name and Version

bitnami/airflow:2.6.2-debian-11-r6

### What architecture are you using?

None

### What steps will reproduce the bug?

i am trying to run a minimal setup of airfllow with localexecutor, the dockercompose looks like this 

```yaml
postgresql:
    image: 'bitnami/postgresql:15.3.0'
    container_name: postgresql
    restart: on-failure
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    networks:
      - appnet


  airflow:
    image: airflow_glue
    build:
      context: AIRFLOW
      dockerfile: dockerfile
    container_name: airflow
    restart: on-failure
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=LocalExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=admin
      - AIRFLOW_USERNAME=admin
    ports:
      - '8080:8080' #airflow ui
```

### What do you see instead?

```
WARNING - Exception when importing 'airflow.providers.apache.pinot.hooks.pinot.PinotHook' from 'apache-airflow-providers-apache-pinot' package
airflow     | Traceback (most recent call last):
airflow     |   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 39, in import_string
airflow     |     return getattr(module, class_name)
airflow     | AttributeError: module 'airflow.providers.apache.pinot.hooks.pinot' has no attribute 'PinotHook'
airflow     |
airflow     | During handling of the above exception, another exception occurred:
airflow     |
airflow     | Traceback (most recent call last):
airflow     |   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/providers_manager.py", line 284, in _sanity_check
airflow     |     imported_class = import_string(class_name)
airflow     |   File "/opt/bitnami/airflow/venv/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 41, in import_string
airflow     |     raise ImportError(f'Module "{module_path}" does not define a "{class_name}" attribute/class')
airflow     | ImportError: Module "airflow.providers.apache.pinot.hooks.pinot" does not define a "PinotHook" attribute/class
```

### Additional information

additional question: how to run airflow scheduler automatically when the container is up?
