### ISSUE TITLE
[bitnami/minio] Items from local folder not showing up in minio console

### ISSUE THREAD

**Issue by corico44** [bitnami/containers#4038]
### Name and Version

bitnami/minio:latest

### What steps will reproduce the bug?

I am trying to have a bucket created in Minio client using a local folder inside my Macbook.

Hereby my steps:

I have written a docker-compose file to run Minio client:
```
version: "2.0"
services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ~/test_data:/data
```
Inside the local folder test_data, there is a folder named test_bucket that contains 1 text file: question_list.txt

When I login to Minio console in localhost:9001, I managed to see a bucket created named `test_bucket`, but the bucket does not have any file.

To double-check if the volume is mounted correctly, I looked inside the running container with `docker exec -it test-minio-1 /bin/bash` and I could find the question_list.txt `/data/test_bucket/ `inside the container.

I don't know why the question_list.txt is not showing up in Minio client.

### What is the expected behavior?

I expect the question_list.txt from local_folder will show up in the bucket inside Minio client.

### What do you see instead?

I see an empty bucket, with the message: This location is empty, please try uploading a new file.

### Additional information

This is a follow up to issue bitnami/bitnami-docker-minio#65 by user @aindraju
