### ISSUE TITLE
[bitnami/openldap] 2.6.4 and later do not start in Kubernetes (using the same deployment as 2.6.3)

### ISSUE THREAD

**Issue by johanneskastl** [bitnami/containers#40841]
### Name and Version

bitnami/openldap 2.6.4 and 2.6.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I created a helm chart for openldap that uses the bitnami openldap image.
https://github.com/johanneskastl/openldap-bitnami-helm-chart/

I am running 2.6.3 and everything works.

I upgrade the image tag to 2.6.4 and get an error (see below) and the pod does never start.

I upgrade to the 2.6.5 image tag and get the same error.

I use the 2.6.3 tag and everything is working again.

### What is the expected behavior?

The pod starts successfully.

### What do you see instead?

This is the log from the Kubernetes pod:

```
 12:30:48.80 INFO  ==> ** Starting LDAP setup **
/opt/bitnami/scripts/openldap/setup.sh: line 82: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
/opt/bitnami/scripts/openldap/setup.sh: line 83: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
 12:30:48.81 INFO  ==> Validating settings in LDAP_* env vars
 12:30:48.82 INFO  ==> Initializing OpenLDAP...
 12:30:48.82 DEBUG ==> Ensuring expected directories/files exist...
 12:30:48.83 INFO  ==> Using persisted data
 12:30:48.84 INFO  ==> ** LDAP setup finished! **

/opt/bitnami/scripts/openldap/run.sh: line 82: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
/opt/bitnami/scripts/openldap/run.sh: line 83: /opt/bitnami/openldap/sbin/slappasswd: Operation not permitted
 12:30:48.85 INFO  ==> ** Starting slapd **
/opt/bitnami/scripts/openldap/run.sh: line 34: /opt/bitnami/openldap/sbin/slapd: Operation not permitted
```

**Comment by johanneskastl** [comment]
I already tried to explicitly set the LDAP and LDAPS port variables to unprivileged ports.
I also tried adding the CAP_NET_BIND capability (as the chart drops all capabilities).

The error is still the same.

**Comment by luoyan35714** [comment]
I get the same issue on OpenShift.

**Comment by johanneskastl** [comment]
> Hi, what if you don't drop all the capabilities? Just for testing purposes. Is the error still there?

The deployment that is being created by my helm chart already does that:

```yaml
      containers:
[...]
        securityContext:
          capabilities:
            drop:                             
            - ALL
```

**Comment by andresbono** [comment]
My proposal (only for testing purposes) was to remove that block that limits the capabilities. Another thing that you can try is to explicitly add the following capability: `NET_BIND_SERVICE`. You mentioned it in a previous comment, but just to doublecheck there was not a typo when you first tried (`NET_BIND_SERVICE` vs `CAP_NET_BIND`). This would be the `values.yaml`:

```yaml
securityContext:
  capabilities:
    drop:
    - ALL
    add:
    - NET_BIND_SERVICE
```

**Comment by johanneskastl** [comment]
Aaaah, looks like that did the trick. Thanks for your help!

@luoyan35714  Can you please confirm this also solves the issue for you?

**Comment by luoyan35714** [comment]
@johanneskastl it works for me, thanks a lot!

**Comment by jandusek4** [comment]
I came across this when trying with latest openldap 2.6.7 and the issue is still there. Why is the new security capability NET_BIND_SERVICE needed from 2.6.3 onwards?

**Comment by toffentoffen** [comment]
This might be relates to a change in Openshift's SecurityContextConstraints: https://access.redhat.com/solutions/6975936
> OpenShift 4.11 introduced the "restricted-v2" SCC in place of the "restricted" SCC known from previous versions. This change was made to adjust security to the current [Pod security standards](https://access.redhat.com/bounce/?externalURL=https%3A%2F%2Fkubernetes.io%2Fdocs%2Fconcepts%2Fsecurity%2Fpod-security-standards%2F).
>
> The new "restricted-v2" SCC drops "ALL" capabilities from a container (compared to the "restricted" SCC that dropped only a subset), and as a result of this, workloads created in OpenShift 4.11 might fail for a lack of permissions to perform certain operations.

**Comment by Deepakganigerupgrad** [comment]
any update?

**Comment by jandusek4** [comment]
I successfully use this security context on OCP 4.12 and 4.14

```
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
 ```
