### ISSUE TITLE
[bitnami/keycloak] Provide image for Keycloak 22

### ISSUE THREAD

**Issue by dalbani** [bitnami/containers#41059]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Keycloak 22 has been released on July 11th, bringing several new features and lots of bug fixes.
No Bitnami container image is available at the moment though.

I'm not aware of the process by which new major (or even minor) versions of the Bitnami container images get committed to the repository. All I can see is that `bitnami-bot` does all the job 😄 
So ignore this request if I missed something obvious.

### What is the feature you are proposing to solve the problem?

Provide a image for Keycloak 22.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but new major versions like this one require some manual work on our side.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by caiaga** [comment]
@carrodher thanks for the efforts! 
I can see a new 22.0.1 tagged docker image has been released: https://hub.docker.com/layers/bitnami/keycloak/22.0.1-debian-11-r0/images/sha256-0fb2ca0eeec85e62bd8ee6abb22845eace7800d79d5e1480bf495ed471d07e34?context=explore 

Does this imply this github issue is resolved, or are there any concerns / outstanding validation runs? The helm charts still seem to point to 21 and haven't been updated quite yet (https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L97). 
Any additional details would be highly appreciated!

FYI @dalbani

**Comment by Sevyls** [comment]
Are there any relevant upgrade instructions for 16.x ?

**Comment by javsalgar** [comment]
Hi @Sevyls 

As soon as the chart is updated, if there are necessary upgrade instructions you will find them in the "Upgrade" in the README.md file.

**Comment by Sevyls** [comment]
> Hi @Sevyls
> 
> As soon as the chart is updated, if there are necessary upgrade instructions you will find them in the "Upgrade" in the README.md file.

Thanks, but as @caiaga also pointed out, the chart is already available in 16.x. As I ran into Upgrade Problems from 14.x to 15.x the Readme wasn't updated at the time I tried to upgrade but some days later. 

So this time I tried to check if there are any comments in die Readme, but their absence for this new version 16.x does not confirm or deny this at the moment.

**Comment by chrisdrobison** [comment]
I upgraded and didn't run into any issues.

**Comment by pkeuter** [comment]
One thing I noticed that is not working correctly is the metrics-spi library which is currently at 3.0.0 but looking at [this](https://github.com/aerogear/keycloak-metrics-spi/issues/168) issue, the library needs to be updated to 4.0.0. I would have loved to create a PR but I have no clue where those stacksmith images reside (or if they are even publicly modifyable)

**Comment by javsalgar** [comment]
Thank you so much for reporting! I will notify the team.

**Comment by Jojoooo1** [comment]
tried to upgrade to helm chart 16.0.1 and runned into the following issue:

```
INFO ==> Validating settings in KEYCLOAK_* env vars...
/opt/bitnami/scripts/libvalidations.sh: line 245: return: : numeric argument required
```

```
2023-08-02 22:19:51,749 ERROR [org.infinispan.CLUSTER] (jgroups-5,keycloak-1-25915) ISPN000475: Error processing response for request 2 from keycloak-0-13727: java.io.EOFException
	at org.infinispan.marshall.core.AbstractBytesObjectInput.checkPosLength(AbstractBytesObjectInput.java:261)
```

**Comment by javsalgar** [comment]
Hi,

Could you share the environment variables you set in your installation?

**Comment by carrodher** [comment]
> One thing I noticed that is not working correctly is the metrics-spi library which is currently at 3.0.0 but looking at [this](https://github.com/aerogear/keycloak-metrics-spi/issues/168) issue, the library needs to be updated to 4.0.0. I would have loved to create a PR but I have no clue where those stacksmith images reside (or if they are even publicly modifiable)

Thanks for letting us know, the container image released after this PR https://github.com/bitnami/containers/pull/43234 is bundling metrics-spi 4.0.0. You can give a try to this new container using the `22.0.1-debian-11-r4` immutable tag or any of the rolling tags pointing to it i.e `22`, `22.0.1`, `latest`, etc

**Comment by pkeuter** [comment]
Thanks @carrodher, that was quickly fixed! I've tried it and it seems to work well 🎉

**Comment by Jojoooo1** [comment]
> Hi,
> 
> Could you share the environment variables you set in your installation?

here is my config @javsalgar 

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    chart: keycloak
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 15.1.2
    helm:
      parameters:

        - name: resources.requests.cpu
          value: "512m"
        - name: resources.requests.memory
          value: "3Gi"
        - name: resources.limits.memory
          value: "3Gi"

        ## Configuration ##
        - name: extraEnvVars[0].name
          value: "JAVA_OPTS"
        - name: extraEnvVars[0].value
          value: "-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=75.0 -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.err.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/urandom"
        
        ## Mode ##
        - name: production
          value: "true"
        - name: proxy
          value: "edge"
        
        ## Replica ##
        - name: pdb.create
          value: "true"
        
         ## Autoscaling ##
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "2"
        - name: autoscaling.maxReplicas
          value: "4"
        - name: autoscaling.targetMemory
          value: "85"

        # Metrics / Monitoring
        - name: metrics.enabled
          value: "true"
        - name: metrics.serviceMonitor.enabled
          value: "true"
        - name: metrics.serviceMonitor.namespace
          value: "keycloak"

        ## Credentials ##
        - name: auth.adminUser
          value: "admin"
        - name: auth.existingSecret
          value: keycloak-secrets
        - name: extraEnvVarsSecret
          value: keycloak-secrets

        ## Database ##
        - name: postgresql.enabled
          value: "false"
        - name: externalDatabase.user
          value: "xxxxxxx"
        - name: externalDatabase.database
          value: "keycloak"
        - name: externalDatabase.existingSecret
          value: "keycloak-secrets"

         ## Networking ##
        - name: service.type
          value: "ClusterIP"
        - name: httpRelativePath
          value: "/auth/"

        - name: initContainers
          value: |
            - name: download-kc-plugins
              image: alpine:3.15.0
              command:
                - sh
              args:
                - -c
                - |
                  wget https://github.com/aerogear/keycloak-metrics-spi/releases/download/3.0.0/keycloak-metrics-spi-3.0.0.jar -O /providers/keycloak-metrics-spi.jar
                  chmod +x /providers/keycloak-metrics-spi.jar
                  touch /providers/keycloak-metrics-spi.jar.dodeploy

        - name: extraVolumeMounts
          value: |
            - name: providers
              mountPath: /opt/bitnami/keycloak/providers

        - name: extraVolumes
          value: |
            - name: providers
              emptyDir: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak

```
