### ISSUE TITLE
bitnami/postgresql-repmgr - can't edit postgresql.conf

### ISSUE THREAD

**Issue by DmitryevichD** [bitnami/containers#41227]
### Name and Version

bitnami/postgresql-repmgr 15.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Reopen [bug](https://github.com/bitnami/containers/issues/36746)

I can't edit next config files:
- postgresql.conf
- pg_hba.conf

### What do you see instead?

I want to apply changes to postgresql.conf pg_hba.conf using docker-compose.yml

**Comment by carrodher** [comment]
Could you please provide more info about how are you trying to do that? It could be nice if you can share the _docker-compose.yaml_ so we can reproduce the issue

**Comment by DmitryevichD** [comment]
sure
<details><summary>docker-compose.yml</summary>

```
version: '3.9'
services:
  postgressql-slave:
    image: docker.io/bitnami/postgresql-repmgr:15
    container_name: postgres-slave
    restart: always
    network_mode: 'host'
    volumes:
      - /data/docker/postgres/data:/bitnami/postgresql
      - ./conf/pg_hba.conf:/opt/bitnami/repmgr/conf/pg_hba.conf
      - ./conf/postgresql.conf:/opt/bitnami/repmgr/conf/postgresql.conf
    environment:
      - POSTGRESQL_USERNAME=ps
      - POSTGRESQL_PASSWORD=ps
      - POSTGRESQL_DATABASE=ps
      - POSTGRESQL_POSTGRES_PASSWORD=ps
      - REPMGR_PASSWORD=ps
      - REPMGR_PRIMARY_HOST=qa-db-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=qa-db-0,qa-db-1:5432
      - REPMGR_NODE_NAME=qa-db-1
      - REPMGR_NODE_NETWORK_NAME=qa-db-1
      - REPMGR_PORT_NUMBER=5432
```  

</details>


0. I run compose that create base configs postgresql.conf, pg_hba.conf etc
1. I need change something at the pg_hba.conf or postgresql.conf and I go by path and tuning them
2. For apply my setting I should restart my container. I exec docker-compose stop\start or down\up and my tuning is disappears
