### ISSUE TITLE
Kafka with kraft mode not working

### ISSUE THREAD

**Issue by rathee1x** [bitnami/containers#41393]
### Name and Version

bitnami/kafka:3.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Container is exiting againa nd again and it says cannot assign requested address(port) to EXTERNAL listener,  the mentioned ports are not in use but still getting this issue. 

```yaml
version: '2.1'
services:
  kafka:
    image: ${REPO_URL}:9002/bitnami/kafka:3.5.0
    hostname: kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      BITNAMI_DEBUG: "yes"
      TZ: ${DOCKER_TZ}
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ADVERTISED_HOST_NAME: ${CURRENT_SERVER_IP}
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_KRAFT_CLUSTER_ID: "fMCL8kv1SWm87L_Md-I2hg"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_LISTENERS: CONTROLLER://kafka:9093, INTERNAL://kafka:9094, EXTERNAL://${CURRENT_SERVER_IP}:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9094, EXTERNAL://${CURRENT_SERVER_IP}:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - ./kafka/data:/bitnami/kafka
```

### What do you see instead?

[]([](![image](https://github.com/bitnami/containers/assets/41962780/1f520f3d-793f-447c-b531-e7822c814440)))
[kafka-error.txt](https://github.com/bitnami/containers/files/12078758/kafka-error.txt)
