### ISSUE TITLE
[bitnami/kafka] Cannot create directory '/bitnami/kafka/config': Permission denied

### ISSUE THREAD

**Issue by sairaghavak** [bitnami/containers#41422]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using `docker-compose.yml` to spin up a kafka contiainer based on bitnami's kafka image without zookeeper

Here is the specific service excerpt from docker-compose

```yml
kafka-container:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - type: volume
        source: kafka-data
        target: /bitnami/kafka
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=abcde
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_AUTO.CREATE.TOPICS.ENABLE=false
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-container:9092
      - KAFKA_CFG_ADVERTISED_HOST_NAME=kafka-container
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-container:9092
```

The docker contianer keeps restarting and when I checked the container logs it says
> cannot create directory '/bitnami/kafka/config': Permission denied

Does the user inside the container has admin permissions, not sure, any pointers would help.

### What is the expected behavior?

Container should be running smoothly

### What do you see instead?
```
kafka 16:38:36.12 INFO  ==> ** Starting Kafka setup **
kafka 16:38:36.17 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka 16:38:36.17 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 16:38:36.18 INFO  ==> Initializing Kafka...
kafka 16:38:36.19 INFO  ==> No injected configuration files found, creating default config files
kafka 16:38:36.33 INFO  ==> Initializing KRaft...
kafka 16:38:36.34 INFO  ==> Formatting storage directories to add metadata...

> cannot create directory '/bitnami/kafka/config': Permission denied
```
### Additional information

Looks like the user in the container doesn't have permission

**Comment by OneCricketeer** [comment]
Related https://github.com/bitnami/containers/issues/41393#issuecomment-1641529842

**Comment by javsalgar** [comment]
Hi,

It seems that the permissions of the volume are not enough for the non-root container. How did you create the volume? Is it a bind-mount?

**Comment by sairaghavak** [comment]
No, **it's not a bind mount**, it's a named volume
specified at the top level of docker-compose file

```yml
volumes:
  kafka-data:
```
I think you are referring to Bind mount [From Bitnami's containers/bitnami/kafka/README.md](https://github.com/bitnami/containers/tree/main/bitnami/kafka#persisting-your-data)

**Comment by OneCricketeer** [comment]
[I've been able to use named volumes perfectly fine](https://github.com/OneCricketeer/apache-kafka-connect-docker/blob/master/docker-compose.yml#L35) 

I suggest not using latest tags, though, since issues with those images aren't repeatable as new commits are made to the repo

**Comment by sairaghavak** [comment]
This issue is resolved after using specific tag i.e., `bitnami/kafka:3.4.1` instead of `latest`

**Comment by migruiz4** [comment]
Hi @sairaghavak, 

We have released a new major version of the `bitnami/kafka` image including major changes, could you please confirm if your issue persists?

**Comment by wxywizard** [comment]
I'm having the same problem with this.
May I ask how you solved it?

**Comment by migruiz4** [comment]
Hi @wxywizard,

Could you please share the docker-compose you used in your deployment?

**Comment by wxywizard** [comment]
> Hi @wxywizard,
> 
> Could you please share the docker-compose you used in your deployment?

sure, Something like this
```shell
  kafka-broker:
    container_name: kafka-broker
    <<: *kafka-common
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./cluster-data/kafka-broker:/bitnami/kafka"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 4
      KAFKA_CFG_BROKER_ID: 4
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_LISTENERS: BROKER://:9095  # kafka监听地址
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://94.100.26.223:9095   # TODO 外网访问填写域名或主机IP -- 让客户端能够监听消息  （ host.docker.internal：自动识别主机IP，在Windows或Mac上运行Docker有效 ）
    ports:
      - "9095:9095"
    networks:
      kafka:
        ipv4_address: 172.22.6.33
```

**Comment by wxywizard** [comment]
> Hi @wxywizard,
> 
> Could you please share the docker-compose you used in your deployment?

sure, something like this
```
  kafka-broker:
    container_name: kafka-broker
    <<: *kafka-common
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./cluster-data/kafka-broker:/bitnami/kafka"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 4
      KAFKA_CFG_BROKER_ID: 4
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_LISTENERS: BROKER://:9095  # kafka监听地址
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://host.docker.internal:9095   
    ports:
      - "9095:9095"
    networks:
      kafka:
        ipv4_address: 172.22.6.33
```
