### ISSUE TITLE
[bitnami/postgresql] container crashes when starting for the first time if you use a custom pg_hba.conf

### ISSUE THREAD

**Issue by sss-ng** [bitnami/containers#41431]
### Name and Version

bitnami/postgres:15.3.0, 15.0, 14.0, 13.0, 12.0 (probably others too)

### What architecture are you using?

arm64

### What steps will reproduce the bug?

The goal is to be able to use a custom `pg_hba.conf` when doing a `docker-compose up` for the first time. However, it seems that this is not possible for version 15.3, 15.0, 14.0, 13.0, 12.0, etc.
Maybe this is by design? I'm not a postgres expert, but it seems like something you should be able to do. 

Here is my setup:

`./docker-compose.yml`:
  
```yml
---
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15.3.0
    ports:
      - 5432:5432
    volumes:
      - "./pg_hba.conf:/bitnami/postgresql/conf/pg_hba.conf"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DATABASE: mydb
      POSTGRES_POSTGRES_PASSWORD: root      ### Note, I tried it with and without this line
```

`./pg_hba.conf`:
Note: this is the same as the one that the scripts generate if there is none given
```
host     all             all             0.0.0.0/0               md5
host     all             all             ::/0                    md5
local    all             all                                     md5
host     all             all        127.0.0.1/32                 md5
host     all             all        ::1/128                      md5
```

The attempt:
```
bill@comp:/tmp/bitnami$ docker-compose down -v # just to make sure we are starting fresh
bill@comp:/tmp/bitnami$ sudo chmod 777 pg_hba.conf
bill@comp:/tmp/bitnami$ docker-compose up

[+] Building 0.0s (0/0)                                                                                  
[+] Running 2/2
 ✔ Network bitnami_default         Created                                                          0.0s 
 ✔ Container bitnami-postgresql-1  Created                                                          0.1s 
Attaching to bitnami-postgresql-1
bitnami-postgresql-1  | postgresql 22:16:21.27 
bitnami-postgresql-1  | postgresql 22:16:21.28 Welcome to the Bitnami postgresql container
bitnami-postgresql-1  | postgresql 22:16:21.28 Subscribe to project updates by watching https://github.com/bitnami/containers
bitnami-postgresql-1  | postgresql 22:16:21.28 Submit issues and feature requests at https://github.com/bitnami/containers/issues
bitnami-postgresql-1  | postgresql 22:16:21.29 
bitnami-postgresql-1  | postgresql 22:16:21.30 INFO  ==> ** Starting PostgreSQL setup **
bitnami-postgresql-1  | postgresql 22:16:21.33 INFO  ==> Validating settings in POSTGRESQL_* env vars..
bitnami-postgresql-1  | postgresql 22:16:21.34 INFO  ==> Loading custom pre-init scripts...
bitnami-postgresql-1  | postgresql 22:16:21.35 INFO  ==> Initializing PostgreSQL database...
bitnami-postgresql-1  | postgresql 22:16:21.36 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
bitnami-postgresql-1  | postgresql 22:16:22.14 INFO  ==> Starting PostgreSQL in background...
bitnami-postgresql-1  | postgresql 22:16:22.30 INFO  ==> Stopping PostgreSQL...
bitnami-postgresql-1  | waiting for server to shut down.... done
bitnami-postgresql-1  | server stopped
bitnami-postgresql-1 exited with code 2
```

### What is the expected behavior?

The container should come up configured with the given `pg_hba.conf`

### Additional information

I exec-ed into the container, and I think one of the scripts is failing because it's asking the user to enter a password. Steps to see that below. It doesnt do that if I dont mount a `pg_hba.conf`

```
bill@comp:/tmp/bitnami$ docker exec -it bitnami-postgresql-1 bash

I have no name!@348e48dc59f1:/$ /opt/bitnami/scripts/postgresql/entrypoint.sh /opt/bitnami/scripts/postgresql/run.sh 
postgresql 22:33:35.50 
postgresql 22:33:35.51 Welcome to the Bitnami postgresql container
postgresql 22:33:35.51 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 22:33:35.52 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 22:33:35.52 
postgresql 22:33:35.55 INFO  ==> ** Starting PostgreSQL setup **
postgresql 22:33:35.57 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 22:33:35.58 INFO  ==> Loading custom pre-init scripts...
postgresql 22:33:35.59 INFO  ==> Initializing PostgreSQL database...
postgresql 22:33:35.60 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 22:33:36.48 INFO  ==> Starting PostgreSQL in background...
Password for user postgres: 
```

To do this, I override the entrypoint with a sleep:
```yml 
---
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15.3.0
    entrypoint: ["sleep"]
    command: ["600"]
    ports:
      - 5432:5432
    volumes:
      - "./pg_hba.conf:/bitnami/postgresql/conf/pg_hba.conf"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DATABASE: mydb
      # POSTGRES_POSTGRES_PASSWORD: root
```
