### ISSUE TITLE
[bitnami/kafka] kafka_jaas.conf is not generated

### ISSUE THREAD

**Issue by Rablet** [bitnami/containers#41457]
### Name and Version

bitnami/kafka:3.5

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Create docker_compose.yaml with the following information:
```
version: "2"

services:
  kafka-0:
    image: bitnami/kafka:3.5
    hostname: kafka.example.com
    ports:
      - ":9094"
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093, EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://kafka.example.com:63796
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CERTIFICATE_PASSWORD=<password>
      - KAFKA_TLS_TYPE=JKS
      - KAFKA_CLIENT_USERS=myuser
      - KAFKA_CLIENT_PASSWORDS=mypassword
    volumes:
      - kafka_data:/bitnami/kafka
      - "./kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "./kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
volumes:
  kafka_data:
    driver: local
```
2. Run the container with `docker compose up`

### What is the expected behavior?

The container should successfully start and kafka_jaas.conf should be generated

### What do you see instead?

There is a log item indicating that the file is being generated:
`kafka_jaas_bug-kafka-0-1  | kafka 10:02:58.73 INFO  ==> Generating JAAS authentication file`
However, it does not appear to be as the container stops with the following error:
```
kafka_jaas_bug-kafka-0-1  | java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)
kafka_jaas_bug-kafka-0-1  |     at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:139)
kafka_jaas_bug-kafka-0-1  |     at java.base/sun.security.provider.ConfigFile.<init>(ConfigFile.java:104)
kafka_jaas_bug-kafka-0-1  |     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
kafka_jaas_bug-kafka-0-1  |     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
kafka_jaas_bug-kafka-0-1  |     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
kafka_jaas_bug-kafka-0-1  |     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
kafka_jaas_bug-kafka-0-1  |     at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
kafka_jaas_bug-kafka-0-1  |     at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
kafka_jaas_bug-kafka-0-1  |     at java.base/java.lang.Class.newInstance(Class.java:645)
kafka_jaas_bug-kafka-0-1  |     at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:258)
kafka_jaas_bug-kafka-0-1  |     at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:249)
kafka_jaas_bug-kafka-0-1  |     at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
kafka_jaas_bug-kafka-0-1  |     at java.base/javax.security.auth.login.Configuration.getConfiguration(Configuration.java:248)
kafka_jaas_bug-kafka-0-1  |     at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
kafka_jaas_bug-kafka-0-1  |     at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:103)
kafka_jaas_bug-kafka-0-1  |     at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:74)
kafka_jaas_bug-kafka-0-1  |     at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:143)
kafka_jaas_bug-kafka-0-1  |     at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.Processor.<init>(SocketServer.scala:973)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.Acceptor.newProcessor(SocketServer.scala:879)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:849)
kafka_jaas_bug-kafka-0-1  |     at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.Acceptor.addProcessors(SocketServer.scala:848)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:523)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:251)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.SocketServer.$anonfun$new$31(SocketServer.scala:175)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.SocketServer.$anonfun$new$31$adapted(SocketServer.scala:175)
kafka_jaas_bug-kafka-0-1  |     at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_jaas_bug-kafka-0-1  |     at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_jaas_bug-kafka-0-1  |     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_jaas_bug-kafka-0-1  |     at kafka.network.SocketServer.<init>(SocketServer.scala:175)
kafka_jaas_bug-kafka-0-1  |     at kafka.server.BrokerServer.startup(BrokerServer.scala:237)
kafka_jaas_bug-kafka-0-1  |     at kafka.server.KafkaRaftServer.$anonfun$startup$2(KafkaRaftServer.scala:96)
kafka_jaas_bug-kafka-0-1  |     at kafka.server.KafkaRaftServer.$anonfun$startup$2$adapted(KafkaRaftServer.scala:96)
kafka_jaas_bug-kafka-0-1  |     at scala.Option.foreach(Option.scala:407)
kafka_jaas_bug-kafka-0-1  |     at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:96)
kafka_jaas_bug-kafka-0-1  |     at kafka.Kafka$.main(Kafka.scala:113)
kafka_jaas_bug-kafka-0-1  |     at kafka.Kafka.main(Kafka.scala)
kafka_jaas_bug-kafka-0-1  | Caused by: java.io.IOException: /opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)
kafka_jaas_bug-kafka-0-1  |     at java.base/sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:669)
kafka_jaas_bug-kafka-0-1  |     at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:265)
kafka_jaas_bug-kafka-0-1  |     at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
kafka_jaas_bug-kafka-0-1  |     ... 37 more
kafka_jaas_bug-kafka-0-1  | [2023-07-20 10:03:02,685] INFO [BrokerServer id=1] Transition from STARTED to SHUTTING_DOWN (kafka.server.BrokerServer)
```
