### ISSUE TITLE
[bitnami/jasperreports] Service cannot startup when use persistence  store

### ISSUE THREAD

**Issue by beshe** [bitnami/containers#42400]
### Name and Version

bitnami/jasperreports:8.2.0

### What architecture are you using?

amd64, RHEL7.9

### What steps will reproduce the bug?

1. below is the docker-compose.

```yaml
version: '2'
services:
  mariadb:
    image: bitnami/mariadb:10.9.7
    restart: always
    environment:
      MARIADB_DATABASE: bitnami_jasperreports
      MARIADB_USER: bn_jasperreports
      MARIADB_PASSWORD: xxxxx
    volumes:
      - /appdata/jsr-mariadb:/bitnami/mariadb
  jasperreports:
    image: bitnami/jasperreports:8.2.0
    restart: always
    environment:
      JASPERREPORTS_DATABASE_HOST: mariadb
      JASPERREPORTS_DATABASE_PORT_NUMBER: 3306
      JASPERREPORTS_DATABASE_NAME: bitnami_jasperreports
      JASPERREPORTS_DATABASE_USER: bn_jasperreports
      JASPERREPORTS_DATABASE_PASSWORD: xxxxx
    volumes:
      - /appdata/jsr-data:/bitnami/jasperreports
    depends_on:
      - mariadb
```
2. when using `docker-compose up` to start up the service, the app keeps restarting and throwing the exception:

```
7/26/2023 1:50:24 PMjasperreports 05:50:24.37 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
7/26/2023 1:50:24 PMjasperreports 05:50:24.39 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
7/26/2023 1:50:24 PMjasperreports 05:50:24.45 INFO  ==> Configuring port numbers
7/26/2023 1:50:24 PMjasperreports 05:50:24.49 INFO  ==> Persisted webapps detected
7/26/2023 1:50:24 PMjasperreports 05:50:24.54 INFO  ==> Restoring persisted JasperReports installation
7/26/2023 1:50:24 PMrealpath: /bitnami/jasperreports/buildomatic/conf_source/db/mysql/db.template.properties: No such file or directory
```

### What is the expected behavior?

Service should be run successfully and the data would be stored on a local disk.
