### ISSUE TITLE
[bitnami/keycloak] Bitnami Keycloak with Bitnami Postgresql trouble

### ISSUE THREAD

**Issue by EE1234EE** [bitnami/containers#42424]
### Name and Version

bitnami/keycloak, postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello,

I created following docker-compose.yaml file and the error I receive is:

cannot resolve host "postgresql": lookup postgresql on 10.96.0.10:53: no such host

but of course the real error comes from postgresql:
```
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```
As you guys can see the docker-compose file is not that difficult but not luck at all.

```
version: '3.9'
services:
  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=edwin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_DATABASE_SCHEMA=public
    depends_on:
      - db
    networks:
      - keycloak_network
  
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=password
    volumes:
      - ./data:/bitnami/postgresql/data
    networks:
      - keycloak_network

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge
```

If I use following docker-compose file:

```
version: '3.9'
services:
  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_USER=edwin
      - KEYCLOAK_PASSWORD=password
      - DB_ADDR=db
      - DB_VENDOR=POSTGRES
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_SCHEMA=public
    depends_on:
      - db
    networks:
      - keycloak_network
  
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - keycloak_network

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge
```

everything starts wonderful but I'll always redirected to sorry page not found, even if I enter localhost:8090, the browser redirects me immediately to sorry page not found keycloak page. Has someone an idea what I'm doing wrong?

### What is the expected behavior?

Running Keycloak, latest version with latest postgresql.

### What do you see instead?

keycloak error: 
cannot resolve host "postgresql": lookup postgresql on 10.96.0.10:53: no such host

**postgresql error: (error source)**
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied

**Comment by jotamartos** [comment]
Hi @EE1234EE,

I just edited the default docker-compose file we include in the repo and added the env vars you set

```
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=keycloak
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=password
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - keycloak_network

  keycloak:
    image: docker.io/bitnami/keycloak:21
    environment:
      - KEYCLOAK_ADMIN_USER=edwin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password
      - KEYCLOAK_DATABASE_SCHEMA=public
    depends_on:
      - postgresql
    ports:
      - "80:8080"
    networks:
      - keycloak_network

volumes:
  postgresql_data:
    driver: local

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge
```

The container was launched properly 

```
keycloak-keycloak-1    | 2023-08-01 07:33:51,483 INFO  [io.quarkus] (main) Keycloak 21.1.2 on JVM (powered by Quarkus 2.13.8.Final) started in 7.055s. Listening on: http://0.0.0.0:8080
keycloak-keycloak-1    | 2023-08-01 07:33:51,483 INFO  [io.quarkus] (main) Profile dev activated.
keycloak-keycloak-1    | 2023-08-01 07:33:51,483 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, vertx]
keycloak-keycloak-1    | 2023-08-01 07:33:51,571 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'edwin' to realm 'master'
keycloak-keycloak-1    | 2023-08-01 07:33:51,573 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

and I could access the application using edwin/password as set in the compose file. 

![Screenshot 2023-08-01 at 09 39 07](https://github.com/bitnami/containers/assets/8791635/5b4971ba-f371-4b1a-ab75-9561e1c91ca6)

Can you try using the docker-compose.yml file I just posted above to see if there is any error in the one you are using? 

Thanks
