### ISSUE TITLE
[bitnami/gitea] Gitea container is aborting "An error occurred while installing Gitea"

### ISSUE THREAD

**Issue by Norrodar** [bitnami/containers#42856]
### Name and Version

bitnami/gitea:1.20.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I trying to start and deploy gitea thru portainer stacks on my Synology NAS, using this yaml:
```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_gitea
      - POSTGRESQL_USERNAME=bn_gitea
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  gitea:
    image: docker.io/bitnami/gitea:1
    volumes:
      - '/volume2/docker/gitea/gitea_data:/bitnami/gitea'
    environment:
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=bitnami_gitea
      - GITEA_DATABASE_USERNAME=bn_gitea
      - GITEA_DATABASE_PASSWORD=bitnami1
    ports:
      - '3001:3000'
      - '2222:2222'
volumes:
  postgresql_data:
    driver: local
  gitea_data:
    driver: local
```

The gitea container is stopping right after it's started.
The folder "/volume2/docker/gitea/gitea_data" has R/W rights for everyone (just to be sure that this isn't a problem).

### What do you see instead?

I'm getting this log:

```
gitea 11:51:58.77 
gitea 11:51:58.77 Welcome to the Bitnami gitea container
gitea 11:51:58.77 Subscribe to project updates by watching https://github.com/bitnami/containers
gitea 11:51:58.78 Submit issues and feature requests at https://github.com/bitnami/containers/issues
gitea 11:51:58.78 
gitea 11:51:59.48 INFO  ==> Configuring libnss_wrapper
gitea 11:51:59.69 INFO  ==> ** Starting Gitea setup **
gitea 11:52:00.01 INFO  ==> Waiting for database connection...
gitea 11:52:05.09 INFO  ==> Initializing Gitea...
gitea 11:52:12.07 INFO  ==> Running Gitea installation wizard
gitea 11:52:12.14 INFO  ==> Starting Gitea in background
gitea 11:52:17.21 INFO  ==> Gitea started successfully
gitea 11:52:17.81 ERROR ==> An error occurred while installing Gitea
```
