### ISSUE TITLE
Sentinel cannot communicate between redis master on mac

### ISSUE THREAD

**Issue by YoHanGLoot** [bitnami/containers#4296]
### Name and Version

bitnami/redis-sentinel:latest

### What steps will reproduce the bug?

Docker compose file:
```yaml
version: "2"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    networks:
      - app-tier
    ports:
      - "6379"
  redis-slave:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - "6379"
    depends_on:
      - redis
    networks:
      - app-tier
  redis-sentinel:
    image: "bitnami/redis-sentinel:latest"
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-slave
    ports:
      - "26379-26381:26379"
    networks:
      - app-tier

```

python file:
```python
from redis.sentinel import Sentinel
sentinel = Sentinel([('localhost', 26379)], socket_timeout=1)
sentinel.discover_master("mymaster")
master = sentinel.master_for('mymaster')
master.set('dddsssss', 'pp')
```

### What do you see instead?

```bash
redis.exceptions.TimeoutError: Timeout connecting to server
```

### Additional information

I am running m1 mac. however, it is also faulty on intel macs

**Comment by javsalgar** [comment]
Hi,

Could you provide the logs of the installation and try entering the container with docker exec and check the sentinel state?

**Comment by vojty** [comment]
I had the same problem, I was missing `REDIS_MASTER_HOST`
```
  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    ports:
      - "26379:26379"
    networks:
      - app-tier
    depends_on:
      - redis
```
Note that if you are using docker volumes then the configuration file is persisted and just adding the env variable won't help unless you re-create those volumes.
