### ISSUE TITLE
[bitnami/kafka] container stops

### ISSUE THREAD

**Issue by halkar** [bitnami/containers#4315]
### Name and Version

bitnami/kafka:2.8.1-debian-10-r239

### What steps will reproduce the bug?

My problem is identical to https://github.com/bitnami/bitnami-docker-kafka/issues/252
Machine - Mac Book Pro M1 (Silicon).
Kafka container stops while starting.
I'm using `testcontainers-go` to run Kafka container locally.
```go
	request := testcontainers.ContainerRequest{
		Image:        image,
		ExposedPorts: []string{port + ":" + port},
		Env: map[string]string{
			"KAFKA_CFG_BROKER_ID":                        "1",
			"KAFKA_CFG_LISTENERS":                        "CONTROLLER://:9093,PLAINTEXT://:" + port,
			"KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP":   "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT",
			"KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR": "1",
			"KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE":        "true",
			"KAFKA_ENABLE_KRAFT":                         "yes",
			"KAFKA_CFG_PROCESS_ROLES":                    "broker,controller",
			"KAFKA_CFG_CONTROLLER_QUORUM_VOTERS":         "1@127.0.0.1:9093",
			"KAFKA_CFG_CONTROLLER_LISTENER_NAMES":        "CONTROLLER",
			"KAFKA_BROKER_ID":                            "1",
			"ALLOW_PLAINTEXT_LISTENER":                   "yes",
			"BITNAMI_DEBUG":                              "true",
			"KAFKA_CFG_ADVERTISED_LISTENERS":             "PLAINTEXT://" + host + ":" + port,
			"KAFKA_CFG_DELETE_TOPIC_ENABLE":              "true",
		},
		// https://github.com/testcontainers/testcontainers-go/issues/279
		SkipReaper: true,
		WaitingFor: wait.ForLog("Kafka Server started").
			WithPollInterval(time.Millisecond * 100).
			WithStartupTimeout(time.Minute * 5),
	}
```
I've tried bitnami/kafka:latest. No changes.

### What is the expected behavior?

Kafka container starts as expected.

### What do you see instead?

Kafka container stops during start.

### Additional information

Logs
```
kafka 13:14:09.70 
kafka 13:14:09.70 Welcome to the Bitnami kafka container
kafka 13:14:09.70 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 13:14:09.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 13:14:09.71 
kafka 13:14:09.71 INFO  ==> ** Starting Kafka setup **
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_BROKER_ID Must match what is set in KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_CONTROLLER_QUORUM_VOTERS must match brokers set with KAFKA_CFG_BROKER_ID
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_PROCESS_ROLES must include 'controller' for KRaft
kafka 13:14:09.75 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka 13:14:09.77 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 13:14:09.78 INFO  ==> Initializing Kafka...
kafka 13:14:09.78 INFO  ==> No injected configuration files found, creating default config files
kafka 13:14:09.94 INFO  ==> Initializing KRaft...
kafka 13:14:09.95 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka 13:14:11.50 INFO  ==> Generated Kafka cluster ID 'yYisgVl9SBqvRloSuvqgKw'
kafka 13:14:11.51 INFO  ==> Formatting storage directories to add metadata...
```
Adding `BITNAMI_DEBUG` doesn't help. No errors in the logs.

**Comment by rafariossaa** [comment]
Hi,
  I think this is most probably due to you are running it in a M1 processor. Some AMD64 assets have problems in M1 architecture.

**Comment by halkar** [comment]
@rafariossaa it happens 1/10 times. So it's not a permanent problem.

**Comment by halkar** [comment]
@rafariossaa anything else you need to investigate?

**Comment by mario-bros** [comment]
i experiencing the same issue with this docker setup :

`version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    - KAFKA_CFG_BROKER_ID=1

volumes:
  kafka_data:
    driver: local`

**Comment by mario-bros** [comment]
im experiencing the same issue using this docker-compose setup :


```
i experiencing the same issue with this docker setup :

```
version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    - KAFKA_CFG_BROKER_ID=1

volumes:
  kafka_data:
    driver: local
```

**Comment by mario-bros** [comment]
im experiencing the same issue using this docker setup :



i experiencing the same issue with this docker setup :

```
version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    - KAFKA_CFG_BROKER_ID=1

volumes:
  kafka_data:
    driver: local
```

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay.
  @mario-bros are you using a M1 processor too ? 
  @halkar Could you try in an non M1 computer ?

**Comment by halkar** [comment]
@rafariossaa it doesn't look like the issue exists on amd64 machines. At least, I've never seen this behaviour in our CI/CD pipeline.

**Comment by halkar** [comment]
@rafariossaa looks like we've had this issue in our CI/CD pipeline (amd64 machines). At least we had similar symptoms when the container fails to start in ~5 minutes.

**Comment by rafariossaa** [comment]
@halkar could you share your docker-compose file or the configuration you are using ?

**Comment by halkar** [comment]
The config is above, in my initial post. We are not using docker-compose in this case. It's all in testcontainers.

**Comment by mario-bros** [comment]
yes  @rafariossaa , im using M1 processor, maybe kafka latest should be build with `buildx` args when doing the `build`

**Comment by rafariossaa** [comment]
M1 architecture is known to have issue when running AMD64 images.
Please, take a look to this: https://github.com/bitnami/charts/issues/7305

**Comment by halkar** [comment]
> M1 architecture is known to have issue when running AMD64 images. Please, take a look to this: [bitnami/charts#7305](https://github.com/bitnami/charts/issues/7305)

@rafariossaa Sorry, but our CI/CD is amd64, and I have the same problem.

**Comment by xwi88** [comment]
Maybe some issues releated the config item: **KAFKA_CFG_INTER_BROKER_LISTENER_NAME**.

Replace

```yml
- KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
- KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
- KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
- KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
```

to 

```yml
- KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
- KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
- KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
```

can startup normally, but not we want.

**Comment by minhtranes** [comment]
I have the same issue with docker compose 

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by fmulero** [comment]
Could you set `BITNAMI_DEBUG=yes`, change the entry point to `/bin/sleep inifinity` log into the container and the run `/opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh` ?

For instance, with this configuration:
```yaml
version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    # setting entrypoint
    entrypoint: /bin/sleep infinity
    environment:
    - BITNAMI_DEBUG=yes
    # Your config below
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    - KAFKA_CFG_BROKER_ID=1

volumes:
  kafka_data:
    driver: local
```

Once it is running, log into the container and run `/opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh`: 
```
$ docker-compose exec kafka bash
I have no name!@f089b5de5179:/$ /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
kafka 11:19:56.93 
kafka 11:19:56.93 Welcome to the Bitnami kafka container
kafka 11:19:56.93 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 11:19:56.94 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 11:19:56.94 
kafka 11:19:56.94 INFO  ==> ** Starting Kafka setup **
kafka 11:19:56.99 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 11:19:56.99 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
kafka 11:19:57.00 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 11:19:57.01 INFO  ==> Initializing Kafka...
kafka 11:19:57.01 INFO  ==> No injected configuration files found, creating default config files
kafka 11:19:57.16 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 11:19:57.16 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 11:19:57.16 INFO  ==> Configuring Kafka for external client communications with PLAINTEXT authentication.
kafka 11:19:57.16 WARN  ==> External client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 11:19:57.17 INFO  ==> Initializing KRaft...
kafka 11:19:57.18 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka 11:19:58.49 INFO  ==> Generated Kafka cluster ID 'oWwg78ElQoq3SEWlFSav6g'
kafka 11:19:58.49 INFO  ==> Formatting storage directories to add metadata...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: controller.listener.names must contain at least one value appearing in the 'listeners' configuration when running the KRaft controller role
        at scala.Predef$.require(Predef.scala:281)
        at kafka.server.KafkaConfig.validateControllerListenerExistsForKRaftController$1(KafkaConfig.scala:2122)
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2182)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2063)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1494)
        at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:41)
        at scala.Option.flatMap(Option.scala:271)
        at kafka.tools.StorageTool$.main(StorageTool.scala:41)
        at kafka.tools.StorageTool.main(StorageTool.scala)
I have no name!@f089b5de5179:/$ 
```

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

**Comment by OneCricketeer** [comment]
@fmulero your example doesn't match OP, which does include `KAFKA_CFG_LISTENERS` with `CONTROLLER` listener defined

**Comment by fmulero** [comment]
Hi Jordan.

I think this `docker-compose.yml` fits with the original case:
```yaml
version: "3"
services:
  kafka:
    image: bitnami/kafka:2.8.1-debian-10-r239
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    #entrypoint: /bin/sleep infinity
    environment:
    - BITNAMI_DEBUG=yes
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker,controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    - KAFKA_CFG_BROKER_ID=1
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_DELETE_TOPIC_ENABLE=true

volumes:
  kafka_data:
    driver: local
```
I tried to reproduce the issue with a clean deployment several times but I wasn't able to do it. If you find any other clue, please share it.

**Comment by OneCricketeer** [comment]
IMO, I would not use KRaft on Kafka 2.8.1. There have been several releases since then, and it is finally production ready as of 3.3.1, so I suggest upgrading the image being used.

**Comment by anatolii-lehkyi-poc** [comment]
> Hope this is helpful - I was able to get the README's internal/external client example running by adding a controller listener and updating the quorum voters.
> 
> ```
>   kafka:
>     image: 'bitnami/kafka:latest'
>     ports:
>       - '9093:9093'
>     volumes:
>       - kafkadata:/bitnami/kafka
>     environment:
>       - KAFKA_ENABLE_KRAFT=yes
>       - KAFKA_CFG_PROCESS_ROLES=broker,controller
>       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
>       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
>       - KAFKA_CFG_LISTENERS=CONTROLLER://:9094,CLIENT://:9092,EXTERNAL://:9093
>       - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://127.0.0.1:9093
>       - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
>       - KAFKA_CFG_BROKER_ID=1
>       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9094
>       - ALLOW_PLAINTEXT_LISTENER=yes
> ```

Helped me! Thanks a lot!

**Comment by xwi88** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
***@***.***

电话：18311190877

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by euonymos** [comment]
@fmulero I wish `BITNAMI_DEBUG=yes` be mentioned [here](https://hub.docker.com/r/bitnami/kafka)

**Comment by pharazon** [comment]
For me setting BITNAMI_DEBUG=yes helped to get the error message out:
kafka_1  | Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Each listener must have a different port, listeners: PLAINTEXT://:9092,CONTROLLER://:9093,CLIENT://:9092,EXTERNAL://:9093

so there are two listeners on the same port. The README.md is a bit confusing.

**Comment by fmulero** [comment]
KRaft is enabled by default since https://github.com/bitnami/containers/pull/31113. In that mode  KAFKA_KRAFT_CLUSTER_ID is mandatory and it should be the same in all cluster members.

**Comment by Vortex375** [comment]
I am facing the same issue. As soon as I configure more that 1 listener via `KAFKA_CFG_ADVERTISED_LISTENERS`, e.g.

```
KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT://kafka:9092
```

Then the container just silently exits with exit code 1 during startup:
```
kafka-docker-compose-kafka-1    | kafka 09:44:42.73 
kafka-docker-compose-kafka-1    | kafka 09:44:42.73 Welcome to the Bitnami kafka container
kafka-docker-compose-kafka-1    | kafka 09:44:42.73 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka-docker-compose-kafka-1    | kafka 09:44:42.73 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka-docker-compose-kafka-1    | kafka 09:44:42.73 
kafka-docker-compose-kafka-1    | kafka 09:44:42.73 INFO  ==> ** Starting Kafka setup **
kafka-docker-compose-kafka-1    | kafka 09:44:42.79 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka-docker-compose-kafka-1    | kafka 09:44:42.80 INFO  ==> Initializing Kafka...
kafka-docker-compose-kafka-1    | kafka 09:44:42.81 INFO  ==> No injected configuration files found, creating default config files
kafka-docker-compose-kafka-1    | kafka 09:44:42.91 INFO  ==> Initializing KRaft...
kafka-docker-compose-kafka-1    | kafka 09:44:42.91 INFO  ==> Formatting storage directories to add metadata...
kafka-docker-compose-kafka-1 exited with code 1
```

Configuring only 1 listener fixes the issue. However, I need to configure 2 listeners to make Kafka available on both localhost (for development) and the internal docker network.

**Comment by Vortex375** [comment]
I finally got it to work, but only using zookeeper and setting `KAFKA_ENABLE_KRAFT=no`. With "KRAFT" enabled, container always exits on startup.

In case it is helpful to anyone, here is my docker-compose file:
```
version: "3.8"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.2
    depends_on:
      - zookeeper
    ports:
      - 9092:29092
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:9092
```

**Comment by carlchan** [comment]
Got mine working after setting BITNAMI_DEBUG and seeing the kafka cluster ID was invalid.
needs to be a shortened BASE64 UUID.

Generate a valid one via:

`cat /proc/sys/kernel/random/uuid | tr -d '-' | base64 | cut -b 1-22
`

**Comment by Vortex375** [comment]
Sounds like something that should be fixed? Looks like the "default" cluster id generation is not working as expected.

**Comment by emeraldhieu** [comment]
I've got the same issue. I tried the configuration at https://github.com/bitnami/containers/tree/main/bitnami/kafka#setting-up-an-apache-kafka-cluster.

The container doesn't start. The log doesn't show any any error.
```
[~]$ docker logs kafka-playground-kafka-0-1
kafka 08:36:44.58 
kafka 08:36:44.58 Welcome to the Bitnami kafka container
kafka 08:36:44.59 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 08:36:44.59 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 08:36:44.59 
kafka 08:36:44.60 INFO  ==> ** Starting Kafka setup **
kafka 08:36:44.71 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 08:36:44.73 INFO  ==> Initializing Kafka...
kafka 08:36:44.74 INFO  ==> No injected configuration files found, creating default config files
kafka 08:36:44.99 INFO  ==> Initializing KRaft...
kafka 08:36:44.99 INFO  ==> Formatting storage directories to add metadata...
```

**Comment by Tanguy00** [comment]
[amd64 ; Manjaro 22 ; 6.1 LTS kernel] 

Same issue with this (simple) docker-compose.yml:
```yaml
version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    container_name: kafka
    networks:
      - net_kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

volumes:
  kafka_data:
    driver: local

networks:
  net_kafka:
```

Any idea?
