### ISSUE TITLE
[bitnami/cassandra] Docker Container not apply env variable changes to container

### ISSUE THREAD

**Issue by 0bon** [bitnami/containers#43255]
### Name and Version

bitnami/cassandra:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Fedora Latest

I am trying to create a container with the specified variables, but none of them take effect. The user is not created, instead the default cassandra:cassandra is created. The init script does not run the DB initialization

 docker-compose file:
```
version: '2'

services:
  cassandra:
    image: bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
      - './init:/docker-entrypoint-initdb.d'
    environment:
      - 'CASSANDRA_SEEDS=cassandra'
      - 'CASSANDRA_PASSWORD_SEEDER=yes'
      - 'CASSANDRA_USER=xyz'
      - 'CASSANDRA_PASSWORD=123'
volumes:
  cassandra_data:
    driver: local

```

./init/setup.cql
```
CREATE KEYSPACE IF NOT EXISTS idcontext
    WITH replication = {
        'class': 'SimpleStrategy',
        'replication_factor' : 1
    };

CREATE KEYSPACE IF NOT EXISTS idcontext_snapshots
    WITH replication = {
        'class': 'SimpleStrategy',
        'replication_factor' : 1
    };

CREATE KEYSPACE IF NOT EXISTS akka_projections
   WITH REPLICATION = {
      'class' : 'SimpleStrategy',
      'replication_factor' : 1
   };

CREATE USER testuser WITH PASSWORD '123' SUPERUSER;
GRANT ALL PERMISSIONS ON KEYSPACE idcontext TO testuser;
GRANT ALL PERMISSIONS ON KEYSPACE idcontext_snapshots TO testuser;
GRANT ALL PERMISSIONS ON KEYSPACE akka_projections TO testuser;

```
[bitnami-cass-log.txt](https://github.com/bitnami/containers/files/12247647/bitnami-cass-log.txt)

### What do you see instead?

n/a
