### ISSUE TITLE
[supabase] Repack Supabase's distribution of Gotrue

### ISSUE THREAD

**Issue by stevefan1999-personal** [bitnami/containers#43328]
### Name and Version

bitnami/supabase:0.3.14

### What is the problem this feature will solve?

https://github.com/bitnami/charts/issues/16988#issuecomment-1588613968

### What is the feature you are proposing to solve the problem?

Pack `supabase-gotrue` by https://github.com/supabase/gotrue. Then the upstream chart will use that image instead

### What alternatives have you considered?

Right now, using the Supabase's Gotrue Docker image works.
```yaml
auth:
  image:
    repository: supabase/gotrue
    tag: v2.91.0
```
