### ISSUE TITLE
Kafka fails to start with latest 3.3.2 revision when listening on both plaintext and TLS

### ISSUE THREAD

**Issue by arushi315** [bitnami/containers#43322]
### Name and Version

bitnami/kafka:3.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Starting Kafks 3.3.2 with plaintext and TLS listeners, Zookeeper 3.6.3 using docker compose:

```yaml
version: '3.9'
services:
  uem-kafka:
    image: harbor-repo.vmware.com/tac-photon/kafka:3.3.2
    hostname: tls.kafka.service.consul
    user: "1001"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - /kafka/TLS/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - /kafka/TLS/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks
    environment:
      - BITNAMI_DEBUG=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,INSIDE_SSL:SSL,OUTSIDE_SSL:SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE_SSL
      - KAFKA_CFG_SECURITY_INTER_BROEKR_PROTOCOL=SSL
      - "KAFKA_CFG_LISTENERS=INSIDE://${GIT_COMMIT_ID}uem-kafka-1:9094,OUTSIDE://${GIT_COMMIT_ID}uem-kafka-1:9092,INSIDE_ssl://tls.kafka.service.consul:9096,OUTSIDE_ssl://tls.kafka.service.consul:9093"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://${GIT_COMMIT_ID}uem-kafka-1:9094,OUTSIDE://${GIT_COMMIT_ID}uem-kafka-1:9092,INSIDE_ssl://tls.kafka.service.consul:9096,OUTSIDE_ssl://tls.kafka.service.consul:9093"
      - JMX_PORT=9999
      - "KAFKA_JMX_OPTS=-javaagent:/opt/vmware/kafka/jolokia-jvm-1.6.2-agent.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=9999"
      - KAFKA_ENABLE_KRAFT=false
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_CFG_LOG_ROLL_HOURS=48
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=**
      - KAFKA_CFG_SSL_KEY_PASSWORD=**
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=JKS
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=**
      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=JKS
    depends_on:
      - zookeeper

  zookeeper:
    image: harbor-repo.vmware.com/tac-photon/zookeeper:3.6.3
    container_name: zookeeper
    ports:
      - '2181:2181'
    user: "1001"
    environment:
     - ZOO_SERVER_ID=0
     - ZOO_HEAP_SIZE=100
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_4LW_COMMANDS_WHITELIST="*"
     - ZOO_SERVERS=0.0.0.0:2888:3888
```

### What is the expected behavior?

Last week when I was deploying Kafka locally with both plaintext and TLS listeners, it worked fine and it still works fine with revision **3.3.2-photon-3-r170** but with the latest revision **3.3.2-photon-3-r176**  kafka fails to start.

Here are the logs when Kafka fails to start:
```
2023-08-01 16:48:31 kafka 21:48:31.82 
2023-08-01 16:48:31 kafka 21:48:31.82 Welcome to the Bitnami kafka container
2023-08-01 16:48:31 kafka 21:48:31.82 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-08-01 16:48:31 kafka 21:48:31.83 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-08-01 16:48:31 kafka 21:48:31.83 
2023-08-01 16:48:31 kafka 21:48:31.83 INFO  ==> ** Starting Kafka setup **
2023-08-01 16:48:31 kafka 21:48:31.96 DEBUG ==> Validating settings in KAFKA_* env vars...
2023-08-01 16:48:31 kafka 21:48:31.96 WARN  ==> The KAFKA_ZOOKEEPER_PROTOCOL environment variable does not configure SASL and/or SSL, this setting is not recommended for production environments.
2023-08-01 16:48:32 kafka 21:48:32.02 WARN  ==> Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.
2023-08-01 16:48:32 kafka 21:48:32.06 INFO  ==> Initializing Kafka...
2023-08-01 16:48:32 kafka 21:48:32.06 INFO  ==> No injected configuration files found, creating default config files
```
I do not see any error here but the container just exists.

Can someone shed some light as to what changed between these two revisions? and if you notice that we are providing a wrong configuration then please let us know.

### What do you see instead?

Consistent Kafka 3.3.2 revisions and kafka should not fail to start.
