### ISSUE TITLE
Kafka new update is broken

### ISSUE THREAD

**Issue by ferasawadi** [bitnami/containers#43516]
### Name and Version

bitnami/kafka

### What architecture are you using?

AWS EKS

### What steps will reproduce the bug?
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka-streams-dev
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka-streams-dev
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: kafka-container
          image: bitnami/kafka:3.5.1-debian-11-r6
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: BITNAMI_DEBUG
              value: "yes"
            - name: KAFKA_ENABLE_KRAFT
              value: "false"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@$kafka-0:9093"

          volumeMounts:
            - name: kafka-data-replicas
              mountPath: /bitnami/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data-replicas
        namespace: kafka-streams-dev
      spec:
        storageClassName: efs-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```
### What is the expected behavior?

Running KAfka

### What do you see instead?
```
16:05:03.16 kafka
16:05:03.16 Welcome to the Bitnami kafka containerkafka
16:05:03.16 Subscribe to project updates by watching https://github.com/bitnami/containerskafka
16:05:03.16 Submit issues and feature requests at https://github.com/bitnami/containers/issueskafka
16:05:03.16 kafka
16:05:03.16 INFO  ==> ** Starting Kafka setup **kafka
16:05:03.20 DEBUG ==> Validating settings in KAFKA_* env vars...kafka
16:05:03.20 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.kafka
16:05:03.21 INFO  ==> Initializing Kafka...kafka
16:05:03.21 INFO  ==> No injected configuration files found, creating default config fileskafka
16:05:03.34 INFO  ==> ** Kafka setup finished! **kafka
16:05:03.36 INFO  ==> ** Starting Kafka **
[2023-08-0416:05:04,112] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2023-08-0416:05:04,574] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2023-08-0416:05:04,696] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)kafka.common.InconsistentNodeIdException: Configured node.id `0` doesn't match stored node.id `1' in meta.properties. If you moved your data, make sure your configured controller.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
	a kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:163)
	a kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
	a kafka.Kafka$.buildServer(Kafka.scala:83)
	a kafka.Kafka$.main(Kafka.scala:91)
	a kafka.Kafka.main(Kafka.scala)
```
### Additional information

I used to have a working version but now all is broken

**Comment by UndeadBaneGitHub** [comment]
Seconded that: the new release is plagued with issues.

Running with the following env variables:
```
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
```
Produces:
```
kafka  | kafka 22:34:17.76 
kafka  | kafka 22:34:17.76 Welcome to the Bitnami kafka container
kafka  | kafka 22:34:17.76 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka  | kafka 22:34:17.76 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka  | kafka 22:34:17.77 
kafka  | kafka 22:34:17.77 INFO  ==> ** Starting Kafka setup **
kafka  | kafka 22:34:17.81 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka  | kafka 22:34:17.82 INFO  ==> Initializing Kafka...
kafka  | kafka 22:34:17.82 INFO  ==> No injected configuration files found, creating default config files
kafka  | kafka 22:34:17.95 INFO  ==> ** Kafka setup finished! **
kafka  | 
kafka  | 
kafka  | kafka 22:34:17.96 INFO  ==> ** Starting Kafka **
kafka  | [2023-08-04 22:34:18,675] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka  | [2023-08-04 22:34:19,079] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
kafka  | [2023-08-04 22:34:19,115] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka  | org.apache.kafka.common.config.ConfigException: You must set `node.id` to the same value as `broker.id`.
kafka  | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2068)
kafka  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2063)
kafka  | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1495)
kafka  | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1418)
kafka  | 	at kafka.Kafka$.buildServer(Kafka.scala:67)
kafka  | 	at kafka.Kafka$.main(Kafka.scala:87)
kafka  | 	at kafka.Kafka.main(Kafka.scala)
```

When I explicitly set an extra `KAFKA_CFG_BROKER_ID=0`, then the output changes to:
```
kafka  | kafka 22:35:07.40 
kafka  | kafka 22:35:07.40 Welcome to the Bitnami kafka container
kafka  | kafka 22:35:07.40 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka  | kafka 22:35:07.40 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka  | kafka 22:35:07.41 
kafka  | kafka 22:35:07.41 INFO  ==> ** Starting Kafka setup **
kafka  | kafka 22:35:07.45 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka  | kafka 22:35:07.46 INFO  ==> Initializing Kafka...
kafka  | kafka 22:35:07.47 INFO  ==> No injected configuration files found, creating default config files
kafka  | kafka 22:35:07.59 INFO  ==> ** Kafka setup finished! **
kafka  | 
kafka  | 
kafka  | kafka 22:35:07.60 INFO  ==> ** Starting Kafka **
kafka  | [2023-08-04 22:35:08,328] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka  | [2023-08-04 22:35:08,758] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
kafka  | [2023-08-04 22:35:08,841] WARN No meta.properties file under dir /bitnami/kafka/data/meta.properties (kafka.server.BrokerMetadataCheckpoint)
kafka  | [2023-08-04 22:35:08,842] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka  | org.apache.kafka.common.KafkaException: No `meta.properties` found in /bitnami/kafka/data (have you run `kafka-storage.sh` to format the directory?)
kafka  | 	at kafka.server.BrokerMetadataCheckpoint$.$anonfun$getBrokerMetadataAndOfflineDirs$2(BrokerMetadataCheckpoint.scala:172)
kafka  | 	at scala.collection.Iterator.foreach(Iterator.scala:943)
kafka  | 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
kafka  | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
kafka  | 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
kafka  | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
kafka  | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
kafka  | 	at kafka.server.BrokerMetadataCheckpoint$.getBrokerMetadataAndOfflineDirs(BrokerMetadataCheckpoint.scala:161)
kafka  | 	at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:186)
kafka  | 	at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:63)
kafka  | 	at kafka.Kafka$.buildServer(Kafka.scala:79)
kafka  | 	at kafka.Kafka$.main(Kafka.scala:87)
kafka  | 	at kafka.Kafka.main(Kafka.scala)
```

**Comment by AntonOfTheWoods** [comment]
3.4 is also broken

**Comment by ferasawadi** [comment]
this code seems to be working but cant have more than one replica

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzn-products-dev
  namespace: muzn-software-dev
  labels:
    app: muzn-products-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: muzn-products-dev
  template:
    metadata:
      labels:
        app: muzn-products-dev
    spec:
      containers:
        - name: muzn-products-dev
          image: 420977297619.dkr.ecr.me-south-1.amazonaws.com/muzn-backend-svc-repo-dev:muzn-ai-products-integration-ms-dev-8
          ports:
            - containerPort: 20006
          env:
            - name: MYSQL_DATABASE
              value: "products_dataLake"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials-dev
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials-dev
                  key: password
            - name: DATABASE_HOST
              value: "products-mysql-server-svc-dev.dbs-space-dev.svc.cluster.local"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-0.kafka-svc.kafka-streams-dev.svc.cluster.local:9092"
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: stripe-api-key-dev

```

**Comment by AntonOfTheWoods** [comment]
Mine won't start all with any of the new versions in docker compose, even for a single node.

**Comment by ferasawadi** [comment]
@AntonOfTheWoods it works for me in Kubernetes EKS cluster

**Comment by ferasawadi** [comment]
after days of testing the code the follwoing yaml file works 

env is EKS Cluster

```yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-server
  namespace: kafka-streams-dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      containers:
        - name: kafka-server
          image: bitnami/kafka:3.5.1-debian-11-r6
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_KRaft_CLUSTER_ID
              value: "muzn-kafka-cluster"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 200m
      volumes:
        - name: kafka-server-data
          persistentVolumeClaim:
            claimName: kafka-server-data
  selector:
    matchLabels:
      app: kafka-server
  serviceName: kafka-server
  volumeClaimTemplates:
    - metadata:
        name: kafka-server-data
        namespace: kafka-streams-dev
      spec:
        storageClassName: efs-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi

```
