### ISSUE TITLE
postgresql-repmgr running under a normal user fails with '/opt/bitnami/postgresql/conf' permission denied

### ISSUE THREAD

**Issue by hulb** [bitnami/containers#43966]
### Name and Version

bitnami/postgresql-repmgr:15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

use these docker compose file:
```
services:
  pg-0:
    image: bitnami/postgresql-repmgr:15.2.0
    user: 1000:1000
    volumes:
    - ./postgres:/bitnami/postgresql
    environment:
    - POSTGRESQL_POSTGRES_PASSWORD=netis
    - POSTGRESQL_USERNAME=xxx
    - POSTGRESQL_PASSWORD=xxx
    - POSTGRESQL_DATABASE=xx
    - REPMGR_PASSWORD=xx
    - REPMGR_PRIMARY_HOST=192.168.0.11
    - REPMGR_PRIMARY_PORT=5432
    - REPMGR_PARTNER_NODES=192.168.0.11:5432,192.168.0.13:5432
    - REPMGR_NODE_NAME=pg-0
    - REPMGR_NODE_NETWORK_NAME=192.168.0.11
    - REPMGR_PORT_NUMBER=5432
```

then  `docker compose up`

### What is the expected behavior?

container startup normally

### What do you see instead?

```
erhai-pg-0-1  | postgresql-repmgr 02:46:35.64 
erhai-pg-0-1  | postgresql-repmgr 02:46:35.65 Welcome to the Bitnami postgresql-repmgr container
erhai-pg-0-1  | postgresql-repmgr 02:46:35.65 Subscribe to project updates by watching https://github.com/bitnami/containers
erhai-pg-0-1  | postgresql-repmgr 02:46:35.65 Submit issues and feature requests at https://github.com/bitnami/containers/issues
erhai-pg-0-1  | postgresql-repmgr 02:46:35.65 
erhai-pg-0-1  | postgresql-repmgr 02:46:35.67 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
erhai-pg-0-1  | postgresql-repmgr 02:46:35.69 INFO  ==> Validating settings in REPMGR_* env vars...
erhai-pg-0-1  | postgresql-repmgr 02:46:35.69 INFO  ==> Validating settings in POSTGRESQL_* env vars..
erhai-pg-0-1  | postgresql-repmgr 02:46:35.69 INFO  ==> Querying all partner nodes for common upstream node...
erhai-pg-0-1  | postgresql-repmgr 02:46:35.76 INFO  ==> There are no nodes with primary role. Assuming the primary role...
erhai-pg-0-1  | postgresql-repmgr 02:46:35.77 INFO  ==> Preparing PostgreSQL configuration...
erhai-pg-0-1  | postgresql-repmgr 02:46:35.78 INFO  ==> postgresql.conf file not detected. Generating it...
erhai-pg-0-1  | cp: cannot create regular file '/opt/bitnami/postgresql/conf/postgresql.conf': Permission denied
erhai-pg-0-1 exited with code 1
```

### Additional information

I get into the container by `docker run` and it seems that the `/opt/bitnami/postgresql` has owner of `root:root`. If I run container by specifying a non-root user, it wouldn't have access to this path.
```
$ docker run --user 1001:1001 --rm --entrypoint ''  -it  bitnami/postgresql-repmgr:15 bash
I have no name!@549f780e8a27:/$ whoami
whoami: cannot find name for user ID 1001
I have no name!@549f780e8a27:/$ id -u
1001
I have no name!@549f780e8a27:/$ ls -alh /opt/bitnami/postgresql/
total 28K
drwxr-xr-x. 10 root root  143 Mar 28 14:50 .
drwxrwxr-x.  7 root root  115 Mar 28 14:50 ..
drwxr-xr-x.  2 root root 4.0K Mar 16 22:43 bin
drwxrwxr-x.  3 root root   20 Mar 28 14:50 conf
drwxr-xr-x.  9 root root 4.0K Mar 16 22:43 include
drwxr-xr-x.  6 root root 4.0K Mar 16 22:43 lib
drwxr-xr-x.  2 root root  265 Mar 16 22:43 licenses
drwxrwxr-x.  2 root root   28 Mar 28 14:50 logs
drwxr-xr-x. 10 root root 4.0K Mar 16 22:43 share
-rw-r--r--.  1 root root 5.4K Mar 16 22:31 .spdx-postgresql-repmgr.json
drwxrwxr-x.  2 root root    6 Mar 28 14:50 tmp
I have no name!@549f780e8a27:/$ touch /opt/bitnami/postgresql/conf/test.conf
touch: cannot touch '/opt/bitnami/postgresql/conf/test.conf': Permission denied
I have no name!@549f780e8a27:/$ 
```
how can I  use a non-root to start?
