### ISSUE TITLE
[bitnami/wordpress] Some device cannot run bitnami Wordpress container, since the permission issue.

### ISSUE THREAD

**Issue by StanleyHsu36** [bitnami/containers#44149]
### Name and Version

bitnami/wordpress:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Setup container user as 999:999 (admin of the host device)
mount host volume for /bitnami/wordpress, and /certs, and all these folders owners are 999:999
but the same docker compose configuration works on some amd64 devices, but it failed on other amd64 and arm64 devices.
I don't what's the different.
```yaml
    wordpress:
        container_name: WordPressDocker
        image: bitnami/wordpress:latest
        user: "999:999"
        depends_on:
            - wp-db
        ports:
            - "23480:8080"
            - "23443:8443"
        volumes:
            - "${HOST_FOLDER}/wp-data:/bitnami/wordpress:rw"
            - "${HOST_FOLDER}/certs:/certs:rw"
        environment:
            WORDPRESS_UID: 999
            WORDPRESS_GID: 999
            APACHE_HTTP_PORT_NUMBER: 8080
            APACHE_HTTPS_PORT_NUMBER: 8443
```

### What is the expected behavior?

The followings are the log from the workable device.
```
wordpress 13:41:37.82 Welcome to the Bitnami wordpress container
wordpress 13:41:37.82 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 13:41:37.82 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 13:41:37.82 
wordpress 13:41:37.83 INFO  ==> ** Starting WordPress setup **
wordpress 13:41:38.10 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
............++++
..................................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key
wordpress 13:41:39.26 INFO  ==> Mounting certificates files from '/certs'
realpath: /bitnami/apache/conf: No such file or directory
wordpress 13:41:39.29 INFO  ==> Configuring the HTTP port
wordpress 13:41:39.33 INFO  ==> Configuring the HTTPS port
wordpress 13:41:39.33 INFO  ==> Configuring Apache ServerTokens directive
```
### What do you see instead?

The followings are the log from the failed device.
```
Welcome to the Bitnami wordpress container
wordpress 13:19:22.47 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 13:19:22.47 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 13:19:22.47 
wordpress 13:19:22.48 INFO  ==> ** Starting WordPress setup **
wordpress 13:19:22.50 WARN  ==> The Apache configuration file '/opt/bitnami/apache/conf/httpd.conf' is not writable. Configurations based on environment variables will not be applied.
mkdir: cannot create directory '/opt/bitnami/apache/conf/bitnami/certs': Permission denied
```
