### ISSUE TITLE
Client fails with SSL handshake error with latest revision of bitnami kafka 3.5.1 

### ISSUE THREAD

**Issue by arushi315** [bitnami/containers#44218]
### Name and Version

bitnami/kafka:3.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Starting Kafka 3.5.1 with plaintext and TLS listeners, Zookeeper 3.6.3 using docker compose:

```yaml
version: '3.9'
services:
  uem-kafka:
    image: harbor-repo.vmware.com/vac_vmware_it/containers/photon-3/kafka:3.5.1
    hostname: tls.kafka.service.consul
    user: "1001"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - /kafka/TLS/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - /kafka/TLS/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks
    environment:
      - BITNAMI_DEBUG=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,INSIDE_SSL:SSL,OUTSIDE_SSL:SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE_SSL
      - KAFKA_CFG_SECURITY_INTER_BROEKR_PROTOCOL=SSL
      - "KAFKA_CFG_LISTENERS=INSIDE://uem-kafka-1:9094,OUTSIDE://uem-kafka-1:9092,INSIDE_ssl://tls.kafka.service.consul:9096,OUTSIDE_ssl://tls.kafka.service.consul:9093"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://uem-kafka-1:9094,OUTSIDE://uem-kafka-1:9092,INSIDE_ssl://tls.kafka.service.consul:9096,OUTSIDE_ssl://tls.kafka.service.consul:9093"
      - JMX_PORT=9999
      - "KAFKA_JMX_OPTS=-javaagent:/opt/vmware/kafka/jolokia-jvm-1.6.2-agent.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=9999"
      - KAFKA_ENABLE_KRAFT=false
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_CFG_LOG_ROLL_HOURS=48
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=**
      - KAFKA_CFG_SSL_KEY_PASSWORD=**
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=JKS
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=**
      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=JKS
    depends_on:
      - zookeeper

  zookeeper:
    image: harbor-repo.vmware.com/tac-photon/zookeeper:3.6.3
    container_name: zookeeper
    ports:
      - '2181:2181'
    user: "1001"
    environment:
     - ZOO_SERVER_ID=0
     - ZOO_HEAP_SIZE=100
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_4LW_COMMANDS_WHITELIST="*"
     - ZOO_SERVERS=0.0.0.0:2888:3888
```

### What do you see instead?

Team, 
I am doing a POC for our setup on Kafka 3.5.1 with plaintext and TLS enabled. Kafka and Zookeeper services start successfully with the latest revision. 
I am running cli command to list topics to verify if I am able to connect as a client on TLS. Verified on plaintext as well on port 9092 and the command works fine. 

For TLS, the client connects fine if I am starting kafka with revision `harbor-repo.vmware.com/tac-photon/kafka:3.5.1-photon-3-r1` but fails if I use the latest revision `harbor-repo.vmware.com/vac_vmware_it/containers/photon-3/kafka:3.5.1-photon-3-r16`. 

Here is the command that I am running: 
```
docker run -it --rm --network=<> -v /kafka/TLS/TLS-TEST/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks -v /kafka/TLS/secret.properties:/opt/bitnami/kafka/config/secret.properties harbor-repo.vmware.com/vac_vmware_it/containers/photon-3/kafka:3.5.1 /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server tls.kafka.service.consul:9093 --command-config /opt/bitnami/kafka/config/secret.properties


> cat secret.properties
security.protocol=SSL
ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.truststore.password=xx
```

Here is the error that I see with `3.5.1-photon-3-r16`:
```
[2023-08-10 16:51:28,168] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (tls.kafka.service.consul/192.168.32.3:9093) failed authentication due to: Failed to process post-handshake messages (org.apache.kafka.clients.NetworkClient)
[2023-08-10 16:51:28,169] WARN [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.SslAuthenticationException: Failed to process post-handshake messages
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:576)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:84)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base/java.lang.Thread.run(Thread.java:833)
Error while executing topic command : Failed to process post-handshake messages
[2023-08-10 16:51:28,173] ERROR org.apache.kafka.common.errors.SslAuthenticationException: Failed to process post-handshake messages
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:576)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:84)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base/java.lang.Thread.run(Thread.java:833)
 (kafka.admin.TopicCommand$)
```

Please review and share insight on what changed between the two versions? 
Guide if there is any misconfiguration on our end. 

Thank you!

**Comment by migruiz4** [comment]
Hi @arushi315,

Could you please provide more information about how you generated your certificates?

The error message 'Received fatal alert: bad_certificate' probably means that your client failed to verify the Kafka hostname he is connected to with the hostname found in the certificate.

In my case, I generated the Kafka server certificate with `CN=tls.kafka.service.consul` and was able to connect the client.

Additionally, after TLS verification succeeded, with the current configuration your client would fail to communicate because now by default `SSL` security protocol configures mTLS (`listener.name.inside_ssl.ssl.client.auth=required`).

**Comment by arushi315** [comment]
Hi @migruiz4  
Thank you for your response. 
We have a self-signed CA, I generated the TLS certificate from that and when calling the CLI client, I am passing the truststore with intermediate CA. 

Also, as I mentioned the same setup works fine when I use the revision `3.5.1-photon-3-r1` but fails with `3.5.1-photon-3-r16`. 
Did the default setting changed between these two revisions? 

Since I am not doing the mTLS, let me update the property and I will keep you posted.

**Comment by migruiz4** [comment]
Hi @arushi315,

The message `Received fatal alert: bad_certificate` most probably means an error with the certificate attributes and/or Subject Alternative Names.

By default, Kafka Clients are configured to verify the hostname of the Kafka server matches the Server Common Name (CN) and/or Subject Alt Names (SAN) matches the server it is connecting to.

For example, if you configure a Kafka server with certificate attribute `CN=kakfa.example.com` but your clients connect via `localhost`, the SSL host will fail.

To solve this issue, there are two solutions:
- The unsafe solution would be to disable client SSL endpoint identification by setting `ssl.endpoint.identification.algorithm=` on the client properties.
- The safe solution, and the one I'd recommend, is to configure your certificates with the CN/SAN your clients will use to connect.

**Comment by arushi315** [comment]
Thanks @migruiz4 for sharing the script. 
I do not think hostname mapping is the issue here since with my cli command I am passing the hostname as the bootstrap server:
```
docker run -it --rm --network=<> -v /kafka/TLS/TLS-TEST/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks -v /kafka/TLS/secret.properties:/opt/bitnami/kafka/config/secret.properties harbor-repo.vmware.com/vac_vmware_it/containers/photon-3/kafka:3.5.1 /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server tls.kafka.service.consul:9093 --command-config /opt/bitnami/kafka/config/secret.properties
```

Also I did try with setting KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM as empty:
`KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=`
Note: It will not set to empty in revision `3.5.1-photon-3-r1` due to https://github.com/bitnami/containers/pull/42309 but can be empty in revision `3.5.1-photon-3-r16`
Even with empty it does not work and I get the same error on client. Also to highlight again, the same client command with same kafka setup works with `3.5.1-photon-3-r1` and not with `3.5.1-photon-3-r16`. 

I enabled Java debug SSL logs and I see the following error: 
```
2023-08-14 14:32:24 javax.net.ssl|ERROR|73|data-plane-kafka-network-thread-0-ListenerName(OUTSIDE_SSL)-SSL-10|2023-08-14 19:32:24.094 GMT|TransportContext.java:370|Fatal (BAD_CERTIFICATE): Empty client certificate chain (
2023-08-14 14:32:24 "throwable" : {
2023-08-14 14:32:24   javax.net.ssl.SSLHandshakeException: Empty client certificate chain
```

So looks like it is expecting mutual TLS. Can you confirm if this setting changed between the two revisions?

**Comment by arushi315** [comment]
@migruiz4 
Note that I am intentionally not doing mTLS here and also when the kafka starts I can see the property `ssl.client.auth = none`. 
So again would like to understand what changed between the two revisions w.r.t mTLS?

**Comment by arushi315** [comment]
By passing the keystore to the client I can make it work but again I am not looking to do mutual TLS at the moment and as per my understanding kafka should not even look for client certificate with `ssl.client.auth = none`. 
Note it is set to none in both the revisions but seems like something else in the latest revisions have changed.

**Comment by arushi315** [comment]
Hi @migruiz4 
Do you have any update on this?

**Comment by migruiz4** [comment]
Hi @arushi315,

I have detected an issue in the `bitnami/kafka` image that affects the `ssl.client.auth` setting.

At the moment, the setting `listener.name.<listener_name>.ssl.client.auth=required` is being configured for all clients using SSL listener security protocol.

https://github.com/bitnami/containers/blob/76bc756889957c1792d4f6d5dd3bf993058da511/bitnami/kafka/3.5/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L973-L982

I'm currently working on a fix for it which should be released soon.

**Comment by arushi315** [comment]
Great, thanks @migruiz4 for looking into this and keep us posted on the fixed release. 
Also, since this issue was not there in the first revision of 3.5.1, can you share the ticket where this change was introduced just so we can understand it better.

**Comment by migruiz4** [comment]
Hi @arushi315,

The latest version of `bitnami/kafka` now include this change (https://github.com/bitnami/containers/pull/45362) that should fix this issue.

The new logic includes the following changes:
- Fixes an issue where `KAFKA_TLS_CLIENT_AUTH` which configures `ssl.client.auth` was being ignored.
- Replaces `KAFKA_TLS_CONTROLLER_AUTH` and `KAFKA_TLS_INTER_BROKER_AUTH` with dynamic env `KAFKA_TLS_<LISTENER_NAME>_CLIENT_AUTH`. This env variable is used to set Kafka setting `listener.name.<listener_name>.ssl.client.auth`.
- `listener.name.<listener_name>.ssl.client.auth` do no longer have a default value and won't be configured unless `KAFKA_TLS_<LISTENER_NAME>_CLIENT_AUTH` is set.

To fix your issue, could you please try updating to the latest version of the image and let us know if it resolves it?
If you continue having issues with client authentication, try adding the env variable `KAFKA_TLS_CLIENT_AUTH=none` to set the value of Kafka's `ssl.client.auth`.

**Comment by arushi315** [comment]
Hi @migruiz4 
By setting `KAFKA_TLS_CLIENT_AUTH=none` the client is able to talk to Kafka broker (only one-way TLS handshake is happening) and without the setting the default value for `ssl.client.auth` is `required`. Is this expected?

**Comment by migruiz4** [comment]
Hi @arushi315,

That is indeed expected behavior. Previous versions of the image only configured SSL settings when the listener was named 'CLIENT' and its security protocol was `SSL/SASL_SSL`.

The new version detects any listener using `SSL/SASL_SSL` and configures SSL accordingly, including `ssl.client.auth` which defaults to required.

To disable mTLS it has to be set to `KAFKA_TLS_CLIENT_AUTH=none`.

**Comment by Vikash08Mishra** [comment]
hey @migruiz4 
Seems settings to update trust store type and key store type isn't getting recognized now ?

     -KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,INSIDE_SSL:SSL,OUTSIDE_SSL:SSL
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE_SSL
    - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SSL
    - KAFKA_CFG_LISTENERS=INSIDE://kafka1:9094,OUTSIDE://kafka1:9092,INSIDE_SSL://b1.kafka.service.consul:9093,OUTSIDE_SSL://b1.kafka.service.consul:9096
    - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://kafka1:9094,OUTSIDE://localhost:9092,INSIDE_SSL://b1.kafka.service.consul:9093,OUTSIDE_SSL://localhost:9096
    - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PEM
    - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.pem
    - KAFKA_CFG_SSL_KEYSTORE_TYPE=PEM
    - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.pem
    - KAFKA_CFG_SSL_KEYSTORE_KEY=/opt/bitnami/kafka/config/certs/privatekey.pem
    - KAFKA_CFG_KAFKA_TLS_CLIENT_AUTH=none

But I see below error in logs when starting kafka and it exits post that

kafka1     | kafka 10:46:39.21 ERROR ==> In order to configure the TLS encryption for Kafka with JKS certs you must mount your kafka.keystore.jks and kafka.truststore.jks certs to the /bitnami/kafka/config/certs directory.
kafka1 exited with code 1

As you can see, I have clearly set KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PEM and KAFKA_CFG_SSL_KEYSTORE_TYPE=PEM

**Comment by Vikash08Mishra** [comment]
Also should it be ssl.client.auth=none instead of tls.client.auth=none you suggested earlier? because I don't see any setting named tls.client.auth in Apache Kafka. For clarity, Is bitnami internally mapping tls.client.auth to ssl.client.auth ?

**Comment by migruiz4** [comment]
Hi @Vikash08Mishra,

`KAFKA_CFG_*` are settings mapped directly to Kafka `server.properties`, while the bitnami/image has its own settings.

You don't need to provide some settings using `KAFKA_CFG_*` because they are covered by image settings validated prior to the container execution.

Some examples from the settings you have shared:
- `KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PEM` -> `KAFKA_TLS_TYPE=JKS`
- `KAFKA_CFG_SSL_TRUSTSTORE_LOCATION`, `KAFKA_CFG_SSL_KEYSTORE_LOCATION`, `KAFKA_CFG_SSL_KEYSTORE_KEY` -> Not needed, by default, certs are configured to be located at `/opt/bitnami/kafka/config/certs/kafka.keystore.pem`, `kafka.keystore.key` and `kafka.truststore.pem`. Filenames can not be customized at the moment. 
- `KAFKA_CFG_KAFKA_TLS_CLIENT_AUTH` -> `KAFKA_TLS_CLIENT_AUTH`.
```

**Note**: On the other hand, in case you would like to entirely omit the container logic for validation and configuration (`kafka_validate` and `kafka_initialize`), you could create your own `server.properties` and mount it at `/opt/bitnami/kafka/config/server.properties`. Please notice that this will also cause the `KAFKA_CFG_*` settings to be ignored.

**Comment by migruiz4** [comment]
> Also should it be ssl.client.auth=none instead of tls.client.auth=none you suggested earlier? because I don't see any setting named tls.client.auth in Apache Kafka. For clarity, Is bitnami internally mapping tls.client.auth to ssl.client.auth ?

Kafka setting is `ssl.client.auth` which is configured using the container env variable `KAFKA_TLS_CLIENT_AUTH` (do not be confused with `KAFKA_CFG_SSL_CLIENT_AUTH`, which would be the dynamic env var used to map `ssl.client.auth` into Kafka server.properties).

In this case, the built-in env variable `KAFKA_TLS_CLIENT_AUTH` takes preference over dynamic env variables such as `KAFKA_CFG_SSL_CLIENT_AUTH`.

**Comment by Vikash08Mishra** [comment]
@migruiz4 all of above makes things very unclear w.r.t end user, where Bitnami is maintaining its own custom settings which doesn't exist in Kafka and throws error despite relevant Kafka settings provide.
This is what I see documented in Bitnami docker image documentation [here](https://hub.docker.com/r/bitnami/kafka/#!) : "any environment variable beginning with KAFKA_CFG_ will be mapped to its corresponding Apache Kafka key."

Consider below example:
If I Provide `KAFKA_CFG_SSL_KEYSTORE_TYPE=PEM `and `KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PEM`, I do see corresponding values getting set in broker configuration. But still, it mandatory to additionally provide: `KAFKA_TLS_TYPE=PEM` which is a pure Bitnami property, Absence of `KAFKA_TLS_TYPE=PEM` throws below error despite `KAFKA_CFG_SSL_KEYSTORE_TYPE=PEM `and `KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PEM`, why is that so?
 `ERROR ==> In order to configure the TLS encryption for Kafka with JKS certs you must mount your kafka.keystore.jks and kafka.truststore.jks certs to the /bitnami/kafka/config/certs directory.`
 
 If Kafka configuration is provided via KAFKA_CFG_ then Bitnami image should not throw validation error.

**Comment by migruiz4** [comment]
Hi @Vikash08Mishra,

Since your use case relies a lot on setting `KAFKA_CFG_*`, I think that maybe this other approach would fit better your use case:

It is possible to skip the `kafka_validate` and `kafka_initialize` steps and rely entirely on manually provided settings by mounting your own `server.properties` at `/opt/bitnami/kafka/config/server.properties` or at `/bitnami/kafka/config/server.properties`.

https://github.com/bitnami/containers/blob/c8bc165b9cb46debdbfa8996602049d90a31a5d7/bitnami/kafka/3.5/debian-11/rootfs/opt/bitnami/scripts/kafka/setup.sh#L39-L51

Although this has a downside, all settings have to be provided in the mounted configuration file, and `KAFKA_CFG_*` will be omitted. 

Configuration settings that require running additional commands, such as KRaft storage initialization or SCRAM users in either Zookeeper or KRaft mode can be configured, as well as execution of init scripts.

**Comment by toondaey** [comment]
Hello, I've been having this same issue using a PEM format, self-signed certificate. And although, this is just for local testing, I've not been able to debug this. Hoping to get some help. Here's my docker service setup specifically for kafka...

```yaml
// ... blah blah other docker service blah blah blah
  zookeeper:
    image: bitnami/zookeeper:3.9.0
    container_name: zookeeper
    ports:
      - 2181:2181
      - 3181:3181
    volumes:
      - zookeeper_data:/bitnami
      - ./certs/zookeeper-keypair.pem:/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.pem
      - ./certs/ca.crt:/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.pem
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_ENABLE=true
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.pem
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.pem
      - ZOO_TLS_PORT_NUMBER=3181
    networks:
      - net
  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    ports:
      - 9071:9071
      - 9083:9083
      - 9093:9093
      - 9096:9096
      - 9097:9097
    volumes:
      - kafka_data:/bitnami
      - ./config/kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
      - ./certs/ca.crt:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro
      # - ./certs/ca.crt:/opt/bitnami/kafka/config/certs/zookeeper.truststore.pem:ro
      - ./certs/kafka.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro
      - ./certs/kafka.crt:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro
      - ./certs/kafka-zoo.key:/opt/bitnami/kafka/config/certs/zookeeper.keystore.key
      - ./certs/kafka-zoo.crt:/opt/bitnami/kafka/config/certs/zookeeper.keystore.pem
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:3181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,SASL_PLAIN:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9071,EXTERNAL://:9093,SASL_PLAIN://:9096,SASL_SSL://:9097
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9071,EXTERNAL://localhost:9093,SASL_PLAIN://localhost:9096,SASL_SSL://localhost:9097
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=admin-secret
      - KAFKA_CLIENT_LISTENER_NAME=SASL_SSL
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_TLS_CLIENT_AUTH=required
      - KAFKA_CLIENT_SASL_MECHANISM=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_TLS_SASL_SSL_CLIENT_AUTH=required
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
      - KAFKA_ZOOKEEPER_TLS_TYPE=PEM
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_FILE=/opt/bitnami/kafka/config/certs/kafka.truststore.pem
      - KAFKA_TLS_TRUSTSTORE_FILE=/opt/bitnami/kafka/config/certs/kafka.truststore.pem
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_SSL
      - KAFKA_TLS_TYPE=PEM
    depends_on:
      - zookeeper
// ... blah blah other docker service blah blah blah
```

Below is how I generated my certificates:
``` bash
openssl req -new -x509 -nodes -out certs/ca.crt -keyout certs/ca.key -subj "/CN=root-ca"

# For zookeeper
openssl genrsa -passout pass:randompassword -des3 -out certs/zookeeper.key 2048
openssl rsa -in certs/zookeeper.key -passin pass:randompassword -out certs/zookeeper.key
openssl req -new -nodes -key certs/zookeeper.key -out certs/zookeeper.csr -subj "/CN=zookeeper"
openssl x509 -req -in certs/zookeeper.csr -days 365 -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial -out certs/zookeeper.crt
rm certs/zookeeper.csr

cat certs/zookeeper.{key,crt} > certs/zookeeper-keypair.pem

# For kafka
openssl genrsa -passout pass:randompassword -des3 -out certs/kafka.key 2048
openssl rsa -in certs/kafka.key -passin pass:randompassword -out certs/kafka.key
openssl req -new -nodes -key certs/kafka.key -out certs/kafka.csr -subj "/CN=kafka"
openssl x509 -req -in certs/kafka.csr -days 365 -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial -out certs/kafka.crt
rm certs/kafka.csr
cp certs/kafka.crt certs/kafka-zoo.crt
cp certs/kafka.key certs/kafka-zoo.key
```

I had to resort to using PEM because the client is a rust source code. I'm not sure why but I keep getting this every single time. I know it's an issue with the common name so I'm a little lost here:
```
[2023-08-27 05:40:43,375] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1001] Failed authentication with /172.19.0.1 (channelId=172.19.0.3:9097-172.19.0.1:59858-0) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

**PS**: I'm running all these on an M1 mac
