### ISSUE TITLE
Docker Bitnami Pgpool not running, when primary database goes down

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [bitnami/containers#44294]
### Name and Version

bitnami/pgpool:4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using the Docker bitnami pgpool for replication and failover with postgresql rpmgr images.
**I have 3 nodes**. 1 manager node and two worker node . Primary database of postgresql rpmgr run on one worker node . sencondary database of postgresql rpmgr run on another worker node. pgpool is running on the manager node . I am setting the docker node label option for that . Now the Replication is working fine . but when the primary database Pc goes down , the secondary database becomes as primary . but at this time  pgpool not running and always restarting

### What is the expected behavior?

when Primary database goes down, pgpool keeps running

### What do you see instead?

when Primary database goes down, pgpool not running

### Additional information
```yaml
version: '3.8'
services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-1,pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_CONNECT_TIMEOUT=2
      - REPMGR_RECONNECT_ATTEMPTS=1
      - REPMGR_RECONNECT_INTERVAL=2
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    deploy:
      placement:
        constraints: [node.labels.type == node1]
  pg-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_CONNECT_TIMEOUT=2
      - REPMGR_RECONNECT_ATTEMPTS=1
      - REPMGR_RECONNECT_INTERVAL=2
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    deploy:
      placement:
        constraints: [node.labels.type == node2]


pgpool:
    image: bitnami/pgpool:4
    ports:
      - 5000:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=repmgr
      - PGPOOL_SR_CHECK_PASSWORD=repmgrpassword
      - PGPOOL_SR_CHECK_PERIOD=5
      - PGPOOL_HEALTH_CHECK_PERIOD=3
      - PGPOOL_HEALTH_CHECK_RETRY_DELAY=2
      - PGPOOL_HEALTH_CHECK_MAX_RETRIES=1
      - PGPOOL_HEALTH_CHECK_TIMEOUT=2
      - PGPOOL_MAX_POOL=32
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=customuser
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=custompassword
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 2
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
```
