### ISSUE TITLE
[bitnami/redis-cluster] Unable to configure Redis Cluster docker mac m1

### ISSUE THREAD

**Issue by matihullah** [bitnami/containers#45848]
### Name and Version

bitnami/redis-cluster:7.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I encountered an issue while attempting to connect to a Redis Cluster on a MacBook m1.  Configure the Redis Cluster connection settings mentioned below:
```yaml
name: cluster
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-cluster'
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-cluster'
  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-cluster'
  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-cluster'
  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-cluster'
  redis-cluster:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    ports:
      - '6380:6379'
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=true'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-cluster'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
```
![Screenshot 2023-08-23 at 12 03 14](https://github.com/bitnami/containers/assets/44584466/757a79c1-d64c-4e35-8967-1039ea40b4f0)

1. Open a terminal.
2. Run the following command `redis-cli -c -p 6380` to connect to the Redis CLI
3. Attempt to set a key using the command `set test1 some_value`
4. After some time, an "Operation timed out" error may be displayed in the terminal

### What is the expected behavior?

After successfully establishing a connection to the Redis cluster, I am capable of both setting and retrieving the key and value

### What do you see instead?

<img width="600" alt="Screenshot 2023-08-23 at 11 55 17" src="https://github.com/bitnami/containers/assets/44584466/95608608-e8b6-4b84-9900-287cf210de61">

**Comment by javsalgar** [comment]
Hi,

The issue is because you are accessing from outside the cluster, but in the case of Redis Cluster all nodes need to be externally accessible or to access from inside the cluster.

**Comment by matihullah** [comment]
I set up port mapping in Docker, and when I access the cluster from inside the container, it works fine. Just to add, this exact setup works perfectly on a Linux machine.

**Comment by javsalgar** [comment]
Hi,

This has to do with how Docker for Mac is implemented, which is different from Docker for Linux.

**Comment by matihullah** [comment]
Do you have any ideas or suggestions on how to properly configure and use it on a Mac?

**Comment by javsalgar** [comment]
I would check with the Docker for Mac devs to see if there is a way to externally expose the container network just like it happens with Linux

**Comment by ngoanpv** [comment]
Hi @javsalgar , could you pls tell the progress of the Docker for Mac? I have the issue for Mac too

**Comment by javsalgar** [comment]
I'm afraid that the network feature must be checked with the docker for mac devs

**Comment by citcon-aoyansheng** [comment]
It's a great project. I have the issue too. @javsalgar

**Comment by pbstriker38** [comment]
I found a solution. It does require docker desktop `>= 4.29.0` and the host networking beta feature to be enabled.

![image](https://github.com/bitnami/containers/assets/5264240/c359147b-e3ca-4c24-8664-5218468922e8)


```yaml
x-redis-cluster-base: &redis-cluster-base
  image: docker.io/bitnami/redis-cluster:7.2
  network_mode: host

services:
    redis-cluster-0:
        container_name: redis-cluster-0
        <<: *redis-cluster-base
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384'
            - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
            - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
            - 'REDIS_PORT_NUMBER=6379'

    redis-cluster-1:
        container_name: redis-cluster-1
        <<: *redis-cluster-base
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384'
            - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
            - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
            - 'REDIS_PORT_NUMBER=6380'

    redis-cluster-2:
        container_name: redis-cluster-2
        <<: *redis-cluster-base
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384'
            - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
            - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
            - 'REDIS_PORT_NUMBER=6381'

    redis-cluster-3:
        container_name: redis-cluster-3
        <<: *redis-cluster-base
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384'
            - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
            - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
            - 'REDIS_PORT_NUMBER=6382'

    redis-cluster-4:
        container_name: redis-cluster-4
        <<: *redis-cluster-base
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384'
            - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
            - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
            - 'REDIS_PORT_NUMBER=6383'

    redis-cluster-5:
        container_name: redis-cluster-5
        <<: *redis-cluster-base
        depends_on:
            - redis-cluster-0
            - redis-cluster-1
            - redis-cluster-2
            - redis-cluster-3
            - redis-cluster-4
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384'
            - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
            - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
            - 'REDIS_PORT_NUMBER=6384'
            - 'REDIS_CLUSTER_REPLICAS=1'
            - 'REDIS_CLUSTER_CREATOR=yes'
```

**Comment by citcon-aoyansheng** [comment]
@pbstriker38 great
![image](https://github.com/bitnami/containers/assets/96765372/faefa2bb-4a08-4865-9c37-e942aa874641)
This option requires you to log in, which is lost every time you start the docker desktop application. It isn't enjoyable. 
Based on bitnami docker image, I use another solution and then internally execute the custom shell script to create the cluster. So far, it is working fine for me. Even without docker, I was able to switch to shell scripts alone.

**Comment by pbstriker38** [comment]
@citcon-aoyansheng 
Yeah. I'm worried that the need to be logged in is going to become a major annoyance to my team. Would you mind sharing your solution?

**Comment by pbstriker38** [comment]
@citcon-aoyansheng 
I figured out a better way that avoids the need for host networking. This does rely on a client that prioritizes the hostname over the ip in the cluster slots response. Luckily the client we are using does.

```yaml
x-redis-cluster-base: &redis-cluster-base
  image: docker.io/bitnami/redis-cluster:7.2

services:
    redis-cluster-0:
        container_name: redis-cluster-0
        <<: *redis-cluster-base
        ports:
            - 6379:6379
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=redis-cluster-0:6379 redis-cluster-1:6380 redis-cluster-2:6381 redis-cluster-3:6382 redis-cluster-4:6383 redis-cluster-5:6384'
            - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=localhost'
            - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'

    redis-cluster-1:
        container_name: redis-cluster-1
        <<: *redis-cluster-base
        ports:
            - 6380:6380
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=redis-cluster-0:6379 redis-cluster-1:6380 redis-cluster-2:6381 redis-cluster-3:6382 redis-cluster-4:6383 redis-cluster-5:6384'
            - 'REDIS_PORT_NUMBER=6380'
            - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=localhost'
            - 'REDIS_CLUSTER_ANNOUNCE_PORT=6380'
            - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'

    redis-cluster-2:
        container_name: redis-cluster-2
        <<: *redis-cluster-base
        ports:
            - 6381:6381
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=redis-cluster-0:6379 redis-cluster-1:6380 redis-cluster-2:6381 redis-cluster-3:6382 redis-cluster-4:6383 redis-cluster-5:6384'
            - 'REDIS_PORT_NUMBER=6381'
            - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=localhost'
            - 'REDIS_CLUSTER_ANNOUNCE_PORT=6381'
            - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'

    redis-cluster-3:
        container_name: redis-cluster-3
        <<: *redis-cluster-base
        ports:
            - 6382:6382
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=redis-cluster-0:6379 redis-cluster-1:6380 redis-cluster-2:6381 redis-cluster-3:6382 redis-cluster-4:6383 redis-cluster-5:6384'
            - 'REDIS_PORT_NUMBER=6382'
            - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=localhost'
            - 'REDIS_CLUSTER_ANNOUNCE_PORT=6382'
            - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'

    redis-cluster-4:
        container_name: redis-cluster-4
        <<: *redis-cluster-base
        ports:
            - 6383:6383
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=redis-cluster-0:6379 redis-cluster-1:6380 redis-cluster-2:6381 redis-cluster-3:6382 redis-cluster-4:6383 redis-cluster-5:6384'
            - 'REDIS_PORT_NUMBER=6383'
            - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=localhost'
            - 'REDIS_CLUSTER_ANNOUNCE_PORT=6383'
            - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'

    redis-cluster-5:
        container_name: redis-cluster-5
        <<: *redis-cluster-base
        ports:
            - 6384:6384
        depends_on:
            - redis-cluster-0
            - redis-cluster-1
            - redis-cluster-2
            - redis-cluster-3
            - redis-cluster-4
        environment:
            - 'ALLOW_EMPTY_PASSWORD=yes'
            - 'REDIS_NODES=redis-cluster-0:6379 redis-cluster-1:6380 redis-cluster-2:6381 redis-cluster-3:6382 redis-cluster-4:6383 redis-cluster-5:6384'
            - 'REDIS_PORT_NUMBER=6384'
            - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=localhost'
            - 'REDIS_CLUSTER_ANNOUNCE_PORT=6384'
            - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
            - 'REDIS_CLUSTER_REPLICAS=1'
            - 'REDIS_CLUSTER_CREATOR=yes'
```
