### ISSUE TITLE
[bitnami/redis-cluster] docker swarm high high availability test

### ISSUE THREAD

**Issue by mingijo-tatum** [bitnami/containers#46383]
### Name and Version

docker.io/bitnami/redis-cluster:7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Configure the docker swarm redis cluster via the docker-compose file below, and delete the redis servers.

### What is the expected behavior?

Cluster containers that are connected should be able to connect normally even if one dies.

### What do you see instead?

```
version: '3'
networks:
  tatum_network:
    name: tatum_network
    driver: overlay
    external: true
services:
  redis_cluster_1:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster1_data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redisPassword'
      - 'REDIS_NODES=redis_cluster_1 redis_cluster_2 redis_cluster_3'
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,DEBUG,SAVE'
    networks:
      - tatum_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database==1
  redis_cluster_2:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster2_data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redisPassword'
      - 'REDIS_NODES=redis_cluster_1 redis_cluster_2 redis_cluster_3'
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,DEBUG,SAVE'
    networks:
      - tatum_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database==1
  redis_cluster_3:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster3_data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redisPassword'
      - 'REDIS_NODES=redis_cluster_1 redis_cluster_2 redis_cluster_3'
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,DEBUG,SAVE'
    networks:
      - tatum_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database==2

  redis_cluster_4:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis_cluster3_data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redisPassword'
      - 'REDIS_NODES=redis_cluster_1 redis_cluster_2 redis_cluster_3 redis_cluster_4'
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,DEBUG,SAVE'
      - 'REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=30'
      - 'REDIS_CLUSTER_DNS_LOOKUP_RETRIES=30'
      - 'REDISCLI_AUTH=redisPassword'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_CLUSTER_CREATOR=yes'
    networks:
      - tatum_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.management==1
volumes:
  redis_cluster1_data:
    external: true
  redis_cluster2_data:
    external: true
  redis_cluster3_data:
    external: true
  redis_cluster4_data:
    external: true
```
I'm using redis-cluster, which can be deployed from this form of docker swram.
```
const { createCluster } = require('redis');

const main = async () => {
  const cluster = createCluster({
    rootNodes: [
      {
        url: 'redis://redis_cluster_1:6379',
      },
      {
        url: 'redis://redis_cluster_2:6379',
      },
      {
        url: 'redis://redis_cluster_3:6379',
      },      
      {
        url: 'redis://redis_cluster_4:6379',
      },
    ],
    defaults: {
      "password": "redisPassword"
    },

  });

  cluster.on('error', (err) => console.log('Redis Cluster Error', err));

  try {
    await cluster.connect();

    const value = await cluster.get('testtest');

    console.log('Value:', value);
  } catch (error) {
    console.error('Error:', error);
  }
};

main()
```
With this type of code, you can run connection tests and use the

![image](https://github.com/bitnami/containers/assets/77369435/a1a249dc-f5d2-42ba-8aa9-6ffafdcea278)
Killing a connected cluster container or service will cause the 
You'll get an error as shown in the photo above.
To get back on track, restart the docker service or container and run the 
Restart that code and it should work fine.
The direction I want to go is to restart the code and maintain the connection without restarting the docker service or container.
