### ISSUE TITLE
phpbb install

### ISSUE THREAD

**Issue by Francois3362** [bitnami/containers#46587]
### Name and Version

bitnami/phpbb:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Start this docker compose on a Synology Nas: 
```yaml
version: '3.9'

services:
  phpbb-db:
    container_name: phpbb-db
    hostname: phpbb-db
    image: mariadb:latest
    volumes:
      - /volume1/docker/phpbb/mariadb_data:/var/lib/mysql:rw
    environment:
      - MARIADB_ROOT_PASSWORD=phpbbadminpass
      - MARIADB_USER=bn_phpbb
      - MARIADB_PASSWORD=bn_pass
      - MARIADB_DATABASE=bn_phpbb
    restart: on-failure:5

  phpbb:
    container_name: phpbb
    hostname: phpbb
    image: docker.io/bitnami/phpbb:latest
    depends_on:
      - phpbb-db
    volumes:
      - /volume1/docker/phpbb/phpbb_data:/bitnami/phpbb:rw
    ports:
      - 7080:8080
      - 7443:8443
    environment:
      - PHPBB_DATABASE_HOST=phpbb-db
      - PHPBB_DATABASE_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=bn_phpbb
      - PHPBB_DATABASE_PASSWORD=bn_pass
      - PHPBB_DATABASE_NAME=bn_phpbb
    restart: on-failure:5
```

I have this Logs on phpbb container: 
```
phpbb 20:01:05.50 
phpbb 20:01:05.50 Welcome to the Bitnami phpbb container
phpbb 20:01:05.50 Subscribe to project updates by watching https://github.com/bitnami/containers
phpbb 20:01:05.50 Submit issues and feature requests at https://github.com/bitnami/containers/issues
phpbb 20:01:05.50 
phpbb 20:01:05.50 INFO  ==> ** Starting phpBB setup **
realpath: /bitnami/apache/conf: No such file or directory
phpbb 20:01:05.52 INFO  ==> Configuring Apache ServerTokens directive
phpbb 20:01:05.53 INFO  ==> Configuring PHP options
phpbb 20:01:05.53 INFO  ==> Setting PHP expose_php option
phpbb 20:01:05.54 INFO  ==> Setting PHP output_buffering option
phpbb 20:01:05.58 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
phpbb 20:01:05.82 INFO  ==> Ensuring phpBB directories exist
phpbb 20:01:05.82 INFO  ==> Trying to connect to the database server
phpbb 20:01:05.83 INFO  ==> Creating configuration file for installation
phpbb 20:01:07.20 INFO  ==> Starting apache in background
phpbb 20:01:12.29 INFO  ==> apache started
phpbb 20:01:12.29 INFO  ==> Running installation wizard
phpbb 20:05:48.41 ERROR ==> phpBB failed to install
phpbb 20:05:48.41 INFO  ==> Stopping apache
phpbb 20:05:49.43 INFO  ==> apache stopped
phpbb 20:05:49.43 INFO  ==> Persisting phpBB installation
cp: cannot create directory '/bitnami/phpbb/store': Permission denied
```
I have things in `/volume1/docker/phpbb/mariadb_data` from the DB
I have nothing in `/volume1/docker/phpbb/phpbb_data` from phpBB

### Additional information

I use portainer on Synology DS923+
and... thanks a lot! :)
