### ISSUE TITLE
Gitea cannot access asset files

### ISSUE THREAD

**Issue by TomFaulkner** [bitnami/containers#46585]
### Name and Version

bitnami/gitea:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On a new setup. The volume mount directory is empty and accessible:

`drwxr-xr-x  2 root root   2 Aug 29 16:10 gitea`

```yaml
  gitea:
    image: bitnami/gitea:latest
    container_name: gitea
    volumes:
      - "/nyu/gitea:/bitnami/gitea"
    environment:
      GITEA_ADMIN_USER: tom127
      GITEA_ADMIN_PASSWORD: "password123"
      GITEA_ADMIN_EMAIL: "giteaadmin@example.org"
      GITEA_HTTP_PORT: 3000
      GITEA_SSH_LISTEN_PORT: 2222
      GITEA_DATABASE_TYPE: postgres
      GITEA_DATABASE_HOST: gitea_db
      GITEA_DATABASE_NAME: gitea
      BITNAMI_DEBUG: "true"
    ports:
      - 3000:3000
      - 2222:2222

  gitea_db:
    image: postgres
    container_name: gitea_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
```

### What is the expected behavior?

Gitea should start successfully

### What do you see instead?

```
gitea                 | gitea 20:18:23.45 INFO  ==> Configuring libnss_wrapper
gitea                 | gitea 20:18:23.46 INFO  ==> ** Starting Gitea setup **
gitea                 | gitea 20:18:23.49 DEBUG ==> Validating settings in GITEA_* environment variables...
gitea                 | gitea 20:18:23.49 INFO  ==> Waiting for database connection...
gitea                 | gitea 20:18:23.51 INFO  ==> Initializing Gitea...
gitea                 | gitea 20:18:23.53 DEBUG ==> Setting APP_NAME to 'Gitea: Git with a cup of tea' in Gitea configuration
gitea                 | gitea 20:18:23.55 DEBUG ==> Setting RUN_USER to 'gitea' in Gitea configuration
gitea                 | gitea 20:18:23.56 DEBUG ==> Setting RUN_MODE to 'prod' in Gitea configuration
gitea                 | gitea 20:18:23.57 DEBUG ==> Setting database.DB_TYPE to 'postgres' in Gitea configuration
gitea                 | gitea 20:18:23.58 DEBUG ==> Setting database.HOST to 'gitea_db:5432' in Gitea configuration
gitea                 | gitea 20:18:23.58 DEBUG ==> Setting database.NAME to 'gitea' in Gitea configuration
gitea                 | gitea 20:18:23.59 DEBUG ==> Setting database.USER to 'bn_gitea' in Gitea configuration
gitea                 | gitea 20:18:23.60 DEBUG ==> Setting database.PASSWD to 'example' in Gitea configuration
gitea                 | gitea 20:18:23.61 DEBUG ==> Setting database.SSL_MODE to 'disable' in Gitea configuration
gitea                 | gitea 20:18:23.62 DEBUG ==> Setting server.DOMAIN to 'localhost' in Gitea configuration
gitea                 | gitea 20:18:23.63 DEBUG ==> Setting server.PROTOCOL to 'http' in Gitea configuration
gitea                 | gitea 20:18:23.64 DEBUG ==> Setting server.ROOT_URL to 'http://localhost:3000' in Gitea configuration
gitea                 | gitea 20:18:23.65 DEBUG ==> Setting server.SSH_DOMAIN to 'localhost' in Gitea configuration
gitea                 | gitea 20:18:23.66 DEBUG ==> Setting server.SSH_PORT to '2222' in Gitea configuration
gitea                 | gitea 20:18:23.67 DEBUG ==> Setting server.SSH_LISTEN_PORT to '2222' in Gitea configuration
gitea                 | gitea 20:18:23.68 DEBUG ==> Setting server.HTTP_PORT to '3000' in Gitea configuration
gitea                 | gitea 20:18:23.69 DEBUG ==> Setting log.ROOT_PATH to '/opt/bitnami/gitea/tmp/log' in Gitea configuration
gitea                 | gitea 20:18:23.70 DEBUG ==> Setting repository.ROOT to '/opt/bitnami/gitea/data/git/repositories' in Gitea configuration
gitea                 | gitea 20:18:23.71 DEBUG ==> Setting security.PASSWORD_HASH_ALGO to 'pbkdf2' in Gitea configuration
gitea                 | gitea 20:18:23.72 DEBUG ==> Setting mailer.ENABLED to 'false' in Gitea configuration
gitea                 | gitea 20:18:23.73 INFO  ==> Running Gitea installation wizard
gitea                 | gitea 20:18:23.74 INFO  ==> Starting Gitea in background
gitea                 | gitea 20:18:28.75 DEBUG ==> Checking that /opt/bitnami/gitea/tmp/log/boot.log log file contains entry "Starting new Web server"
gitea                 | gitea 20:18:28.76 DEBUG ==> Found entry "Starting new Web server" in /opt/bitnami/gitea/tmp/log/boot.log
gitea                 | gitea 20:18:28.76 INFO  ==> Gitea started successfully
gitea                 | gitea 20:18:28.76 DEBUG ==> Getting cookies
gitea                 | gitea 20:18:28.79 DEBUG ==> Install
gitea                 | gitea 20:18:28.84 ERROR ==> An error occurred while installing Gitea
gitea                 | gitea 20:18:28.85 DEBUG ==> Curl output: <!DOCTYPE html>

... a bunch of html...

<script src="/assets/js/index.js?v=1.20.3" onerror="alert('Failed to load asset files from ' + this.src + '. Please make sure the asset files can be accessed.')"></script>

gitea exited with code 1
```

**Comment by rafariossaa** [comment]
Hi,
  I create the volume directories and used this docker-compose:
```
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_gitea
      - POSTGRESQL_USERNAME=bn_gitea
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  gitea:
    image: docker.io/bitnami/gitea:1
    volumes:
      - './gitea_data:/bitnami/gitea'
    environment:
      - GITEA_ADMIN_USER=tom127
      - GITEA_ADMIN_PASSWORD=password123
      - GITEA_ADMIN_EMAIL=giteaadmin@example.org
      - GITEA_HTTP_PORT=3000
      - GITEA_SSH_LISTEN_PORT=2222
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=bitnami_gitea
      - GITEA_DATABASE_USERNAME=bn_gitea
      - GITEA_DATABASE_PASSWORD=bitnami1
    ports:
      - '3000:3000'
      - '2222:2222'
```

```
...

gitea_1       | 2023/09/06 10:06:35 cmd/web.go:223:runWeb() [I] Starting Gitea on PID: 1
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:148:serveInstalled() [I] Gitea version: 1.20.3 built with GNU Make 4.3, go1.20.7 : bindata
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:149:serveInstalled() [I] App path: /opt/bitnami/gitea/bin/gitea
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:150:serveInstalled() [I] Work path: /opt/bitnami/gitea
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:151:serveInstalled() [I] Custom path: /opt/bitnami/gitea/custom
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:152:serveInstalled() [I] Config file: /opt/bitnami/gitea/custom/conf/app.ini
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:153:serveInstalled() [I] Run mode: prod
gitea_1       | 2023/09/06 10:06:35 cmd/web.go:154:serveInstalled() [I] Prepare to run web server
gitea_1       | 2023/09/06 10:06:35 routers/init.go:112:InitWebInstalled() [I] Git version: 2.30.2, Wire Protocol Version 2 Enabled (home: /opt/bitnami/gitea/data/home)
gitea_1       | 2023/09/06 10:06:35 ...les/setting/cache.go:75:loadCacheFrom() [I] Cache Service Enabled
gitea_1       | 2023/09/06 10:06:35 ...les/setting/cache.go:90:loadCacheFrom() [I] Last Commit Cache Service Enabled
gitea_1       | 2023/09/06 10:06:35 ...s/setting/session.go:74:loadSessionFrom() [I] Session Service Enabled
...

gitea_1       | 2023/09/06 10:06:40 ...s/graceful/server.go:62:NewServer() [I] Starting new SSH server: tcp::2222 on PID: 1
gitea_1       | 2023/09/06 10:06:40 cmd/web.go:285:listen() [I] Listen: http://0.0.0.0:3000
gitea_1       | 2023/09/06 10:06:40 cmd/web.go:289:listen() [I] AppURL(ROOT_URL): http://localhost:3000/
gitea_1       | 2023/09/06 10:06:40 ...s/graceful/server.go:62:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 
...
```
  Could you give it a try ?
