### ISSUE TITLE
Moodle Bitnami problems with Mac M1 ARM architecture

### ISSUE THREAD

**Issue by giliomeejg** [bitnami/containers#4679]
### Name and Version

bitnami/moodle:3.11.9-debian-11-r2

### What steps will reproduce the bug?

1. Mac M1 Max
2. docker-compose.yml
```yaml
version: "3.8"
services:
  moodle:
    container_name: moodle_web
    build: .
    image: "docker.io/bitnami/moodle:3.11.9-debian-11-r2"
    platform: linux/amd64 # for mac m1
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - APACHE_HTTPS_PORT_NUMBER=443
      - MOODLE_WWWROOT=http://localhost:8080
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=host.docker.internal
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=secret
      - MOODLE_SKIP_BOOTSTRAP=yes
      - MOODLE_SMTP_PROTOCOL=tls
      - BITNAMI_DEBUG=true
      - PHP_POST_MAX_SIZE=512M
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - MOODLE_CRON_MINUTES=-1
    volumes:
      - "/path-to/moodle:/bitnami/moodle:delegated"
      - "/path-to/moodledata:/bitnami/moodledata:delegated"
```
3. docker-compose up
4. 
```
moodle_web  | moodle 07:38:09.94 INFO  ==> ** Starting Apache **
moodle_web  | [Wed Aug 31 07:38:10.079334 2022] [core:emerg] [pid 1] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex
moodle_web  | (95)Operation not supported: could not create accept mutex
moodle_web  | AH00015: Unable to open logs
```

### What is the expected behavior?

Expecting for the system to boot up, given the:
```
platform: linux/amd64 # for mac m1
```
setting in the docker-compose.yml

### What do you see instead?

Seeing the mentioned error:
```
moodle_web  | moodle 07:38:09.94 INFO  ==> ** Starting Apache **
moodle_web  | [Wed Aug 31 07:38:10.079334 2022] [core:emerg] [pid 1] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex
moodle_web  | (95)Operation not supported: could not create accept mutex
moodle_web  | AH00015: Unable to open logs
```
