### ISSUE TITLE
[bitnami/elasticsearch] readiness/liveness probe not working if "restEncryption: false" in values.yaml

### ISSUE THREAD

**Issue by rabbagliettiandrea** [bitnami/containers#47078]
### Name and Version

bitnami/elasticsearch:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm upgrade --install --wait --wait-for-jobs --values values.yaml --version 19.10.8 $release_name elasticsearch/elasticsearch`

values.yaml:
```yaml
security:
  enabled: true
  elasticPassword: "{{ service.attrs_elasticsearch.password }}"
  tls:
    autoGenerated: true
    restEncryption: false
    verificationMode: none
```

### What is the expected behavior?

The readiness and liveness probes should work correctly regardless of the "restEncryption" setting. When "restEncryption" is set to "false," Elasticsearch should still be responsive to these probes, indicating its health status.

### What do you see instead?

Currently, when "restEncryption" is set to "false," the readiness and liveness probes appear to always fail. This behavior is inconsistent with the expected functionality.

### Additional information

The bug lies here: https://github.com/bitnami/containers/blob/cf811facba3bb35964a72fe81af0937b66920ab5/bitnami/elasticsearch/8/debian-11/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L913C1-L914C1

since the condition at L913 will fail and that way the curl command would not report basic auth, returning 401 instead of 2xx
