### ISSUE TITLE
[bitnami/suitecrm] SuiteCRM 8.x mail configuration not working

### ISSUE THREAD

**Issue by tldev-de** [bitnami/containers#47482]
### Name and Version

bitnami/suitecrm:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start a fresh docker compose stack with this config:

```yaml
version: "2"

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=suitecrm
      - MYSQL_ROOT_PASSWORD=suitecrm
    volumes:
      - db_data:/var/lib/mysql

  suitecrm:
    image: docker.io/bitnami/suitecrm:8
    restart: unless-stopped
    environment:
      - SUITECRM_DATABASE_HOST=db
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_NAME=suitecrm
      - SUITECRM_DATABASE_USER=suitecrm
      - SUITECRM_DATABASE_PASSWORD=suitecrm
      - SUITECRM_USERNAME=admin@example.org
      - SUITECRM_PASSWORD=ooj6jah3XXXXeiS7
      - SUITECRM_EMAIL=noreply@XXX.XXX
      - SUITECRM_SMTP_HOST=mail.XXX.XXX
      - SUITECRM_SMTP_PORT=587
      - SUITECRM_SMTP_USER=noreply@XXX.XXX
      - SUITECRM_SMTP_PASSWORD=XXXXXXXXXXX
      - SUITECRM_SMTP_PROTOCOL=tls
      - SUITECRM_SMTP_NOTIFY_NAME=suitecrm
      - SUITECRM_SMTP_NOTIFY_ADDRESS=noreply@XXX.XXX
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'data:/bitnami/suitecrm'
    depends_on:
      - db

volumes:
  db_data:
  data:
```

### What is the expected behavior?

SuiteCRM should start and configure SMTP

### What do you see instead?

there is an error configuring SMTP in the application

```
suitecrm-suitecrm-1  | suitecrm 09:29:49.30 INFO  ==> Running setup wizard
suitecrm-suitecrm-1  | suitecrm 09:29:55.61 INFO  ==> Starting apache in background
suitecrm-suitecrm-1  | suitecrm 09:30:00.73 INFO  ==> apache started
suitecrm-suitecrm-1  | suitecrm 09:30:00.73 INFO  ==> Configuring SMTP
suitecrm-suitecrm-1  | suitecrm 09:30:01.11 ERROR ==> An error occurred while trying to login to configure SMTP
suitecrm-suitecrm-1 exited with code 1
```
