### ISSUE TITLE
bitnami/suitecrm

### ISSUE THREAD

**Issue by joho1968** [bitnami/containers#47484]
### Name and Version

bitnami/suitecrm:8.3.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have successfully deployed `bitnami/suitecrm:8.3.0`, by specifically mentioning the tag in the `docker-compose.yml` file.

Now I want to upgrade to the 8.3.1 tag, but no matter what I do, looking inside the container, I'm still at 8.3.0.

I have removed containers, images, and everything else I can think of, and "re-deployed", but I'm still stuck on 8.3.0 according to the "About" screen in SuiteCRM.

### What is the expected behavior?

I would expect `bitnami/suitecrm:8.3.1` to actually actuate 8.3.1.

### What do you see instead?

`bitnami/suitecrm:8.3.0`

### Additional information

I'm obviously doing something wrong, I mean, surely `bitnami/suitecrm:8.3.1` contains 8.3.1 of SuiteCRM ...

**Comment by corico44** [comment]
Hello @joho1968,

Could you provide me with the docker-compose that you use to launch version 8.3.1, please?

**Comment by joho1968** [comment]
`docker compose up -d`

in a directory containing docker-compose.yml that looks like this:

```
# Copyright VMware, Inc.                                                                                                            
# SPDX-License-Identifier: APACHE-2.0                                                                                               
                                                                                                                                    
version: '2'                                                                                                                        
services:                                                                                                                           
  mariadb:                                                                                                                          
    image: docker.io/bitnami/mariadb:10.6                                                                                           
    environment:                                                                                                                    
      # ALLOW_EMPTY_PASSWORD is recommended only for development.                                                                   
      - ALLOW_EMPTY_PASSWORD=yes                                                                                                    
      - MARIADB_USER=bn_suitecrm                                                                                                    
      - MARIADB_DATABASE=bitnami_suitecrm                                                                                           
      - MARIADB_PASSWORD=bitnami123                                                                                                 
    volumes:                                                                                                                        
      - 'mariadb_data:/bitnami/mariadb'                                                                                             
  suitecrm:                                                                                                                         
    image: docker.io/bitnami/suitecrm:8.3.1                                                                                         
    ports:                                                                                                                          
      - target: 80                                                                                                                  
        published: 8080                                                                                                             
        protocol: tcp                                                                                                               
        mode: host                                                                                                                  
    environment:                                                                                                                    
      - DISABLE_SSL=true                                                                                                            
      - APACHE_HTTP_PORT_NUMBER=80                                                                                                  
      - APACHE_HTTPS_PORT_NUMBER=                                                                                                   
      - SUITECRM_USERNAME=crmadmin                                                                                                  
      - SUITECRM_PASSWORD=12345678                                                                                                  
      - SUITECRM_HOST=localhost                                                                                                     
      - SUITECRM_ENABLE_HTTPS=no                                                                                                    
      - SUITECRM_EXTERNAL_HTTP_PORT_NUMBER=888                                                                                      
      - SUITECRM_EXTERNAL_HTTPS_PORT_NUMBER=443                                                                                     
      - SUITECRM_DATABASE_HOST=mariadb                                                                                              
      - SUITECRM_DATABASE_PORT_NUMBER=3306                                                                                          
      - SUITECRM_DATABASE_USER=bn_suitecrm                                                                                          
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm                                                                                     
      - SUITECRM_DATABASE_PASSWORD=bitnami123                                                                                       
      # ALLOW_EMPTY_PASSWORD is recommended only for development.                                                                   
      - ALLOW_EMPTY_PASSWORD=yes                                                                                                    
    volumes:                                                                                                                        
      - 'suitecrm_data:/bitnami/suitecrm'                                                                                           
    depends_on:                                                                                                                     
      - mariadb                                                                                                                     
volumes:                                                                                                                            
  mariadb_data:                                                                                                                     
    driver: local                                                                                                                   
  suitecrm_data:                                                                                                                    
    driver: local
```

I had it at 8.3.0, and wanted 8.3.1 / 8.4.0, and simply changed the tag name. But I'm obviously not up to speed on Docker. Now, when I removed everything completely, images, containers, etc, and then went to get 8.3.1, that works.
