### ISSUE TITLE
[bitnami/memcached] Memcached not starting on unix socket

### ISSUE THREAD

**Issue by mmosierteamvelocity** [bitnami/containers#47853]
### Name and Version

bitnami/memcached docker image

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
- name: memcached
          image: bitnami/memcached:latest
          command:
          - run.sh 
          - -s /tmp/memcached/memcached.socket
          imagePullPolicy: Always
          securityContext: 
              allowPrivilegeEscalation: false
              capabilities:
                drop: 
                  - ALL
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"  
          volumeMounts: 
          - name: memcached
            mountPath: /tmp/memcached    
          ports:
          - containerPort: 11211
```

### What is the expected behavior?

Pod to start with listening unix socket 

### What do you see instead?

Crashloop backoff
