### ISSUE TITLE
[bitnami/moodle] Unable to upload a SCORM package file in Moodle

### ISSUE THREAD

**Issue by markattyne** [bitnami/containers#48157]
### Name and Version

bitnami/moodle:4.2

### What architecture are you using?

None

### What steps will reproduce the bug?

**STEP 1: Start a container using the following docker-compose.yml:**
```
version: '3.5'
services:

  moodle:
    container_name: moodle
    image: docker.io/bitnami/moodle:4.2
    environment:
      MOODLE_HOST: **[OMITTED]**
      MOODLE_USERNAME: 'admin'
      MOODLE_PASSWORD: 'adminpass'
      MOODLE_EMAIL: 'me@here.com'
      MOODLE_SITE_NAME: 'Moodle'
      MOODLE_DATABASE_TYPE: 'mysqli'
      MOODLE_DATABASE_HOST: **[OMITTED]**
      MOODLE_DATABASE_PORT_NUMBER: '3306'
      MOODLE_DATABASE_NAME: 'moodle'
      MOODLE_DATABASE_USER: **[OMITTED]**
      MOODLE_DATABASE_PASSWORD: **[OMITTED]**
      MYSQL_CLIENT_FLAVOR: 'mysql'
      MYSQL_CLIENT_DATABASE_HOST: **[OMITTED]**
      MYSQL_CLIENT_DATABASE_PORT_NUMBER: '3306'
      MYSQL_CLIENT_DATABASE_ROOT_USER: **[OMITTED]**
      MYSQL_CLIENT_DATABASE_ROOT_PASSWORD: **[OMITTED]**
      MYSQL_CLIENT_CREATE_DATABASE_NAME: 'moodle'
      PHP_POST_MAX_SIZE: '2048M'
      PHP_UPLOAD_MAX_FILESIZE: '2048M'
    hostname: **[OMITTED]**
    expose:
      - '8080'
    restart: unless-stopped
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    networks:
      - caddy

  caddy:
    container_name: caddy
    image: private/my-caddy:latest
    ports:
      - 80:80
      - 443:443
    environment:
      MOODLE_HOST: **[OMITTED]**
      MOODLE_ADDRESS: 'http://moodle:8080'
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy

volumes:
  moodle_data:
  moodledata_data:
  caddy_data:
  caddy_config:

networks:
  caddy:
    name: caddy
```
**Step 2: Open Moodle, create a course, click "Add Activity", select "SCORM Package".**

Step 3: Drag and drop the SCORM .zip file into the "Package file" field.

Please note that the SCORM package is approx 300MB,  Caddy does not have an upload limit set, and Moodle's upload limit is set to 2048M via the docker-compose.yml file.

### What is the expected behavior?

The SCORM package should be imported properly and the content should be added to the course.

### What do you see instead?

Sometimes the upload progress bar reaches approx 50% and hangs. Other times, the upload progress bar will reach 100%, show an error message about the connection to the server, and my browser's developer console will show a 413 response status.

### Additional information

I have been trying to fix this issue for almost 10 hours. Any help that you could give would be greatly appreciated.

**Comment by javsalgar** [comment]
Hi,

Do you have a SCORM package that we can use to reproduce the issue?

**Comment by markattyne** [comment]
Hi @javsalgar ,

Thank you for your help. Here is a link to the file: [https://drive.google.com/file/d/1wSETD-sDfX76AJB6w15rC6NQysgxmMl7/view?usp=sharing](https://drive.google.com/file/d/1wSETD-sDfX76AJB6w15rC6NQysgxmMl7/view?usp=sharing)

**Comment by jotamartos** [comment]
Hi @markattyne,

I just tried to reproduce the issue but couldn't do so. I launched a fresh Moodle/MariaDB docker-compose with thew updated values for PHP_UPLOAD_MAX_FILESIZE and PHP_POST_MAX_SIZE

```
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_UPLOAD_MAX_FILESIZE=2048M
      - PHP_POST_MAX_SIZE=2048M
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

>Note: This is the default docker-compose file you can find in the repo but changing the env vars I mentioned above

After that, I created a course and added the SCORM package to one of its sections

![Screenshot 2023-09-19 at 12 12 30](https://github.com/bitnami/containers/assets/8791635/3b99e793-45d7-47c8-b11a-f237f0cf2fd9)

The package was uploaded without problems and listed in the course too

![Screenshot 2023-09-19 at 12 13 04](https://github.com/bitnami/containers/assets/8791635/04348a38-dad6-42c6-8a3a-f6d5d79bc194)

Please try reproducing the issue with the docker-compose I pasted. Then you can try with your deployment but without using caddy.
