### ISSUE TITLE
[bitnami/kafka] log.flush doesn't seem to work

### ISSUE THREAD

**Issue by toondaey** [bitnami/containers#48181]
### Name and Version

bitnami/kafka:3.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Kubernetes deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - image: bitnami/kafka:3.5.1
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: 'yes'
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,SECURE:SASL_PLAINTEXT,INTERNAL_SECURE:SASL_PLAINTEXT
        - name: KAFKA_CFG_LISTENERS
          value: CONTROLLER://:8000,PLAINTEXT://:9071,EXTERNAL://:9093,SECURE://:9096,INTERNAL_SECURE://:9098
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.example.com:9071,EXTERNAL://localhost:9093,SECURE://kafka.example.com:9096,INTERNAL_SECURE://localhost:9098
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: controller,broker
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@localhost:8000
        - name: KAFKA_CLIENT_LISTENER_NAME
          value: EXTERNAL
        - name: KAFKA_CFG_SASL_ENABLED_MECHANISMS
          value: PLAIN
        - name: KAFKA_CFG_LOG_RETENTION_BYTES
          value: '1073741824'
        - name: KAFKA_CFG_LOG_RETENTION_MINUTES
          value: '30'
        - name: KAFKA_CLIENT_USERS
          value: user
        - name: KAFKA_CLIENT_PASSWORDS
          value: pa$$w0rd1
        - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
          value: '100'
#        - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MS
#          value: 3000
        ports:
        - containerPort: 9096
          name: sasl-plain
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
```

### What is the expected behavior?

I'm fairly new to deploying kafka however, I wanted to use this as a simple test deployment. This does work however, it constantly has to restart because the pod runs out of memory frequently hence restarts. I'm trying to make sure that the memory is flushed to disk but I can't seem to get it to work. I've tried both `log.flush.interval.messages` and `log.flush.interval.ms` independently and together to no avail.

As observed, I'm using Kraft mode and I've noticed that it has it's own `server.properties` which I've tried modifying manually and still nothing. Please assist.

### What do you see instead?

A constantly restarting pod.
