### ISSUE TITLE
kraft mode create topic exception

### ISSUE THREAD

**Issue by whoadmin** [bitnami/containers#48490]
### Name and Version

bitnami/kafka:3.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. my docker-compose.yaml
```yaml
version: "kafka"

networks:
  kakfaBridge:
    driver: bridge

services:
  kafka1:
    image: bitnami/kafka:3.4
    networks:
      - kakfaBridge
    ports:
      - "29092:29092"
    volumes:
      - "kafka1_data:/data/kafka"
    environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:29093
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:29093
       - KAFKA_BROKER_ID=0
       - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWd
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:29093,2@kafka2:29095,3@kafka3:29097
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_CFG_NODE_ID=0
  kafka2:
    image: bitnami/kafka:3.4
    networks:
      - kakfaBridge
    ports:
      - "29094:29094"
    volumes:
      - "kafka2_data:/data/kafka"
    environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:29094,CONTROLLER://:29095
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:29095
       - KAFKA_BROKER_ID=2
       - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWd
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:29093,2@kafka2:29095,3@kafka3:29097
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_CFG_NODE_ID=2
  kafka3:
    image: bitnami/kafka:3.4
    networks:
      - kakfaBridge
    ports:
      - "29096:29096"
    environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:29096,CONTROLLER://:29097
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:29097
       - KAFKA_BROKER_ID=3
       - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWd
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:29093,2@kafka2:29095,3@kafka3:29097
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_CFG_NODE_ID=3
volumes:
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local
```
2.create topic success
<img width="1477" alt="image" src="https://github.com/bitnami/containers/assets/13013247/fffbd9da-8210-44ec-a57a-175e55ecda69">
3.topic list error
<img width="1289" alt="image" src="https://github.com/bitnami/containers/assets/13013247/d2162e5d-96e4-414e-9c7a-efa373bed59b">

### What is the expected behavior?

topic list or describe run command success

### What do you see instead?

Error while executing the topic command: The broker does not support METADATA
```
[2023-09-14 01:39:02,426] ERROR org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support METADATA
 (kafka.admin.TopicCommand$)
```
