### ISSUE TITLE
Petition to bring back curl for bitnami/kubectl images

### ISSUE THREAD

**Issue by krodyrobi** [bitnami/containers#48638]
### Name and Version

bitnami/kubectl:1.27.*

### What is the problem this feature will solve?

Currently bitnami/kubectl is the go to docker image when dealing with k8s jobs.

These jobs usually deal with interacting with the cluster, some text parsing features, crypto support AND out of cluster communication in case configs/secrets need to be computed based on an api, for the first 3 the image works well but the last one recently got pulled out

Already asked in #13820

### What is the feature you are proposing to solve the problem?

Add curl back within the image, it does not increase the artifact size that much and having a hardened image in one place instead of many custom ones is less error prone.

### What alternatives have you considered?

No image that is as up to date as the bitnami repository contains a mixture of kubectl, openssl, jq and curl

Closest I could find is https://hub.docker.com/r/appuio/oc/ but it lags on updates and bundles kubectl variants specific for their clusters and is more than 3 times larger while missing openssl utilitaries..

**Comment by EronWright** [comment]
An alternative that contains `kubectl`, `curl`, and more: [alpine/k8s ](https://hub.docker.com/r/alpine/k8s)

**Comment by krodyrobi** [comment]
Does not contain openssl unfortunatelly, but feels more appropiate than appuio/oc

**Comment by joancafom** [comment]
As commented in #13820, the main reason behind removing `curl` was the amount of packages it adds to the system and the increased update cadence derived from CVEs 💔 . If we find that there is a substantial amount of users that use `kubectl` in conjunction with `curl` we would consider re-adding it back

**Comment by joancafom** [comment]
This thread can be used as such. Reacting with a 👍 to the original issue should be enough to give us an idea of the importance.

**Comment by michalgazda** [comment]
It has just 7 👍 as of now, including mine, however, would love to make it happen as it is hard to find good alternative.

**Comment by akinmail** [comment]
@michalgazda why not just make your own docker image yourself driving from this bitnami image and add curl if you want

**Comment by Letme** [comment]
@akinmail Because then you need to push it somewhere and maintain it each time bitnami updates the image. Thats the whole luxury of bitnami - I only need to bump the container version and I get all the latest and greatest, not that I have to repush, maintain, etc.

**Comment by thesuperzapper** [comment]
For those who need to work around this strange removal of `curl`, you can just use the [`bitnami/os-shell`](https://hub.docker.com/r/bitnami/os-shell) image instead with an `init-container` to copy the `kubectl` binary from the [`bitnami/kubectl`](https://hub.docker.com/r/bitnami/kubectl).

__WARNING:__ this WONT work with other way around (copying the `curl` binary), because `curl` has other dependencies beyond the binary itself.

Here is an  example of a Deployment which does this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-with-curl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-with-curl
  template:
    metadata:
      labels:
        app: kubectl-with-curl
    spec:
      initContainers:
        - name: copy-kubectl
          image: bitnami/kubectl:1.30.0-debian-12-r3
          command:
            - "/bin/sh"
            - "-c"
          args:
            - |
              echo "copying 'kubectl' binary to shared volume...";
              cp -f "$(which kubectl)" /shared-bin/kubectl;
          volumeMounts:
            - name: shared-bin
              mountPath: "/shared-bin/"
      containers:
        - name: main
          image: bitnami/os-shell:12-debian-12-r20
          command:
            - "/bin/sh"
            - "-c"
          args:
            - |
              ## to break the infinite loop when we receive SIGTERM
              trap "exit 0" TERM;

              ## keep the container running (so people can `kubectl exec -it` into it)
              while true; do
                echo "I am alive...";
                sleep 30;
              done
          volumeMounts:
            - name: shared-bin
              mountPath: "/usr/local/bin/kubectl"
              subPath: "kubectl"
      volumes:
        - name: shared-bin
          emptyDir: {}
```
