### ISSUE TITLE
[bitnami/postgresql-repmgr] v16 - Unrecognized configuration parameter "promote_trigger_file" in file "/opt/bitnami/postgresql/conf/postgresql.conf"

### ISSUE THREAD

**Issue by buraketmen** [bitnami/containers#50114]
### Name and Version

bitnami/postgresql-repmgr:16

### What architecture are you using?

None

### What steps will reproduce the bug?

- Environment

Docker 24.0.6
Windows 10

- Configuration

```
services:
  pg-0:
    hostname: pg-0
    image: docker.io/bitnami/postgresql-repmgr:16
    volumes:
      - "pg-0-storage:/bitnami/postgresql"
    networks:
      - pg-net
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      REPMGR_PASSWORD: ${POSTGRES_PASSWORD}
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_PRIMARY_PORT: 5432
      REPMGR_PARTNER_NODES: pg-0:5432,pg-1:5432
      REPMGR_NODE_NAME: pg-0
      REPMGR_NODE_NETWORK_NAME: pg-0
      REPMGR_PORT_NUMBER: 5432
      BITNAMI_DEBUG: "true"
  pg-1:
    hostname: pg-1
    image: docker.io/bitnami/postgresql-repmgr:16
    volumes:
      - "pg-1-storage:/bitnami/postgresql"
    networks:
      - pg-net
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      REPMGR_PASSWORD: ${POSTGRES_PASSWORD}
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_PRIMARY_PORT: 5432
      REPMGR_PARTNER_NODES: pg-0:5432,pg-1:5432
      REPMGR_NODE_NAME: pg-1
      REPMGR_NODE_NETWORK_NAME: pg-1
      REPMGR_PORT_NUMBER: 5432
      BITNAMI_DEBUG: "true"
```

"When I deployed with Docker Swarm, the container was closing without giving an error message unless BITNAMI_DEBUG was set to 'true'. When I looked in DEBUG mode, I realized that it was exiting with the following error. I'm not experiencing the same problem for 'bitnami/postgresql-repmgr:15'

```
2023-09-27 11:30:49 postgresql-repmgr 11:30:49.39 INFO  ==> Starting PostgreSQL in background...
2023-09-27 11:30:49 waiting for server to start....2023-09-27 08:30:49.407 GMT [208] LOG:  unrecognized configuration parameter "promote_trigger_file" in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 822
2023-09-27 11:30:49 2023-09-27 08:30:49.407 GMT [208] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
2023-09-27 11:30:49 pg_ctl: could not start server
2023-09-27 11:30:49 Examine the log output.
2023-09-27 11:30:49  stopped waiting
```

### What is the expected behavior?

Default configuration file is expected to work.

### What do you see instead?

`Unrecognized configuration parameter "promote_trigger_file" in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 822`
