### ISSUE TITLE
[bitnami/wordpress] Container does not start with Docker rootless

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [bitnami/containers#50295]
### Name and Version

bitnami/wordpress:6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Host: AMD64 GNU/Linux Debian 11
2. Docker version: 20.10, Docker Compose version: v2.9.0
3. Create the following `compose.yaml`
```yaml
services:
  database:
    image: docker.io/bitnami/mariadb:11.0
    ports:
      - "127.0.0.1:3306:3306/tcp"
    environment:
      MARIADB_MASTER_PORT_NUMBER: 3306
      MARIADB_ROOT_PASSWORD: mariadb_root_pass
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress_user
      MARIADB_PASSWORD: wordpress_pass

  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:8443:8443/tcp"
    depends_on:
      - database
    environment:
      WORDPRESS_USERNAME: test
      WORDPRESS_PASSWORD: test_pass
      WORDPRESS_DATABASE_HOST: database
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_USER: wordpress_user
      WORDPRESS_DATABASE_PASSWORD: wordpress_pass

```
4. Execute `docker compose up`.

### What is the expected behavior?

The Docker containers start up and Wordpress site is available in http://localhost:8080.

### What do you see instead?

Docker container for Wordpress site fails to start up. It seems that initialization scripts cannot remove files inside the folder `/opt/bitnami/wordpress/wp-content` due to permission errors. The command `id` inside the container returns `uid=1001 gid=0(root) groups=0(root)`. 1001 is the user id on host that launches the `docker compose` command.

### Additional information

Wordpress Docker container log:

```Text
wordpress 14:12:11.31 
wordpress 14:12:11.31 Welcome to the Bitnami wordpress container
wordpress 14:12:11.31 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 14:12:11.31 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 14:12:11.31 
wordpress 14:12:11.31 INFO  ==> ** Starting WordPress setup **
wordpress 14:12:11.32 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
....................................................................++++
..........................++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
wordpress 14:12:11.58 INFO  ==> Configuring Apache ServerTokens directive
wordpress 14:12:11.59 INFO  ==> Configuring PHP options
wordpress 14:12:11.59 INFO  ==> Setting PHP expose_php option
wordpress 14:12:11.60 INFO  ==> Setting PHP output_buffering option
wordpress 14:12:11.91 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 14:12:12.20 INFO  ==> Ensuring WordPress directories exist
wordpress 14:12:12.20 INFO  ==> Trying to connect to the database server
wordpress 14:12:17.22 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 14:12:17.78 INFO  ==> Installing WordPress
wordpress 14:12:18.95 INFO  ==> Persisting WordPress installation
rm: cannot remove '/opt/bitnami/wordpress/wp-content/plugins/jetpack/extensions/blocks/cookie-consent': Directory not empty
rm: cannot remove '/opt/bitnami/wordpress/wp-content/plugins/jetpack/src': Directory not empty
```
