### ISSUE TITLE
airflow-scheduler and airflow-worker can not connct to  webserver

### ISSUE THREAD

**Issue by kwang1971** [bitnami/containers#50336]
### Name and Version

bitnami/airflow:2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

use the following docker-compose.yml to perssiting data to host directory.
```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:15'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - D:/projects/airflow/bitnamiImage/PersistingSolution/postgresql-persistence:/bitnami/postgresql
  redis:
    image: 'bitnami/redis:7.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - D:/projects/airflow/bitnamiImage/PersistingSolution/redis-persistence:/bitnami
  airflow-worker:
    image: bitnami/airflow-worker:2
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
  airflow-scheduler:
    image: bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
  airflow:
    image: bitnami/airflow:2
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8080:8080'
```

### What is the expected behavior?

system run successfully

### What do you see instead?

schedule
```
airflow-scheduler 23:40:53.28
airflow-scheduler 23:40:53.29 Welcome to the Bitnami airflow-scheduler container
airflow-scheduler 23:40:53.29 Subscribe to project updates by watching https://github.com/bitnami/containers
airflow-scheduler 23:40:53.29 Submit issues and feature requests at https://github.com/bitnami/containers/issues
airflow-scheduler 23:40:53.29
airflow-scheduler 23:40:53.30 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-scheduler 23:40:53.31 INFO  ==> ** Starting Airflow setup **
airflow-scheduler 23:40:53.33 INFO  ==> No injected configuration file found. Creating default config file
airflow-scheduler 23:40:54.33 INFO  ==> Configuring Airflow database
airflow-scheduler 23:40:54.35 INFO  ==> Configuring Celery Executor
airflow-scheduler 23:40:54.36 INFO  ==> Trying to connect to the database server
airflow-scheduler 23:40:55.55 INFO  ==> Waiting for Airflow Webserver to be up
```

worker
```
irflow-worker 23:44:29.50 Welcome to the Bitnami airflow-worker container
airflow-worker 23:44:29.50 Subscribe to project updates by watching https://github.com/bitnami/containers
airflow-worker 23:44:29.50 Submit issues and feature requests at https://github.com/bitnami/containers/issues
airflow-worker 23:44:29.50 
airflow-worker 23:44:29.51 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-worker 23:44:29.51 INFO  ==> ** Starting Airflow setup **
airflow-worker 23:44:29.53 INFO  ==> No injected configuration file found. Creating default config file
airflow-worker 23:44:30.56 INFO  ==> Configuring Airflow database
airflow-worker 23:44:30.59 INFO  ==> Configuring Celery Executor
airflow-worker 23:44:30.61 INFO  ==> Trying to connect to the database server
airflow-worker 23:44:31.75 INFO  ==> Waiting for Airflow Webserver to be up
```
