### ISSUE TITLE
[bitnami/openldap] Enable overlays

### ISSUE THREAD

**Issue by joshuacox** [bitnami/containers#50524]
### Name and Version

bitname/openldap:2.6.6

### What is the problem this feature will solve?

The documentation points to adding dynlist like so:

```
       overlay dynlist
       dynlist-attrset nisMailAlias labeledURI
```

to slapd.conf  However there is no slapd.conf in the bitnami container. as we are using /bitnami/openldap/slapd.d

The [documentation](https://www.openldap.org/doc/admin26/guide.html#Converting%20old%20style%20%7B%7Bslapd.conf%7D%7D(5)%20file%20to%20%7B%7Bcn=config%7D%7D%20format) points to doing something like this to convert:

````
slaptest -f /usr/local/etc/openldap/slapd.conf -F /usr/local/etc/openldap/slapd.d
````

But again I don't have a slapd.conf file to convert, or is there a base file I can use for this purpose? or is there a way to merge in an overlay?

### What is the feature you are proposing to solve the problem?

Just an explanation of how to add in an overlay would be fantastic.  Potentially adding it to the documentaiton.  Or maybe even an environment variable:

```
LDAP_EXTRA_OVERLAYS=dynlist
```

I would imagine most would need configuration lines as well, like:

```
LDAP_EXTRA_OVERLAYS_CONFIG=dynlist-attrset nisMailAlias labeledURI
```

or something similar.

### What alternatives have you considered?

just mapping in a directory and trying to slaptest a config that I might be able to ldifs out of.

```
docker exec openldap slaptest -f /slaptest/slapd.conf -F /slaptest/slapd.d                                              
overlay "dynlist" not found
/slaptest/slapd.conf: line 1: <overlay> handler exited with 1!
slaptest: bad configuration directory!
```
with some tweaking I might be able to hack together a solution.

minimal slapd.conf (EDIT: now it works, but I am uncertain what all I need to extract from it)

```
include /opt/bitnami/openldap/etc/schema/core.schema
include /opt/bitnami/openldap/etc/schema/cosine.schema
include /opt/bitnami/openldap/etc/schema/dyngroup.schema
include /opt/bitnami/openldap/etc/schema/inetorgperson.schema
modulepath /opt/bitnami/openldap/lib/openldap
moduleload dynlist
overlay dynlist
dynlist-attrset groupOfURLs labeledURI member
```

so *now* I can get a slapcat:

```
docker exec openldap slapcat -n0 -F /slaptest/slapd.d
```

It certainly is a lot of data, should I just be diffing that and slapcat on a slapd.conf of:

```
include /opt/bitnami/openldap/etc/schema/core.schema
include /opt/bitnami/openldap/etc/schema/cosine.schema
include /opt/bitnami/openldap/etc/schema/inetorgperson.schema
```

**Comment by joshuacox** [comment]
so I have successfully turned a few configlines into around 60 ldif lines:

```
dn: cn=schema,cn=config
cn: schema
objectClass: olcSchemaConfig
olcAttributeTypes: ( 1.2.840.113556.1.2.102 NAME 'memberOf' D
 he entry belongs to' EQUALITY distinguishedNameMatch SYNTAX
 115.121.1.12 NO-USER-MODIFICATION USAGE dSAOperation X-ORIGI
 ted Administrator' )
olcAttributeTypes: ( OLcfgOvAt:8.1 NAME ( 'olcDynListAttrSet'
  DESC 'Dynamic list: <group objectClass>, <URL attributeDesc
  attributeDescription>' EQUALITY caseIgnoreMatch SYNTAX OMsD
 ORDERED 'VALUES' )

dn: cn=schema,cn=config
cn: schema
objectClass: olcSchemaConfig
olcObjectClasses: ( OLcfgOvOc:8.1 NAME ( 'olcDynListConfig' '
  DESC 'Dynamic list configuration' SUP olcOverlayConfig STRU
 ListAttrSet )

dn: cn={4}dyngroup,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: {4}dyngroup
olcObjectIdentifier: {0}NetscapeRoot 2.16.840.1.113730
olcObjectIdentifier: {1}NetscapeLDAP NetscapeRoot:3
olcObjectIdentifier: {2}NetscapeLDAPattributeType NetscapeLDA
olcObjectIdentifier: {3}NetscapeLDAPobjectClass NetscapeLDAP:
olcObjectIdentifier: {4}OpenLDAPExp11 1.3.6.1.4.1.4203.666.11
olcObjectIdentifier: {5}DynGroupBase OpenLDAPExp11:8
olcObjectIdentifier: {6}DynGroupAttr DynGroupBase:1
olcObjectIdentifier: {7}DynGroupOC DynGroupBase:2
olcAttributeTypes: {0}( NetscapeLDAPattributeType:198 NAME 'm
 dentifies an URL associated with each member of a group. Any
 URL can be used.' SUP labeledURI )
olcAttributeTypes: {1}( DynGroupAttr:1 NAME 'dgIdentity' DESC
  when processing the memberURL' SUP distinguishedName SINGLE
olcAttributeTypes: {2}( DynGroupAttr:2 NAME 'dgAuthz' DESC 'O
 tion rules that determine who is allowed to assume the dgIde
 uthzMatch SYNTAX 1.3.6.1.4.1.4203.666.2.7 X-ORDERED 'VALUES'
olcAttributeTypes: {3}( DynGroupAttr:3 NAME 'dgMemberOf' DESC
 entry belongs to' EQUALITY distinguishedNameMatch SYNTAX 1.3
 .121.1.12 )
olcObjectClasses: {0}( NetscapeLDAPobjectClass:33 NAME 'group
 TRUCTURAL MUST cn MAY ( memberURL $ businessCategory $ descr
  owner $ seeAlso ) )
olcObjectClasses: {1}( DynGroupOC:1 NAME 'dgIdentityAux' SUP
  ( dgIdentity $ dgAuthz ) )
structuralObjectClass: olcSchemaConfig

dn: olcOverlay={0}dynlist,olcDatabase={-1}frontend,cn=config
objectClass: olcOverlayConfig
objectClass: olcDynListConfig
olcOverlay: {0}dynlist
olcDynListAttrSet: {0}groupOfURLs labeledURI member
olcDynListAttrSet: {1}groupOfURLs memberURL member+memberOf@g
structuralObjectClass: olcDynListConfig
```

However, placing this in /ldifs does not seem to have the desired effect.  And honestly, this seems to be the wrong approach. i.e. to take two lines of very easy to understand config and turn them into some archaic block of 60 lines of ldif.  I seem to be handing the next person who looks at these configs a major headache.

**Comment by joshuacox** [comment]
perhaps it requires to be ran as schema? appending to /schema/custom.ldif (which had an ldapPublicKey definition in there) and changing the modify to adds

```
dn: cn=ldapPublicKey,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: openssh-lpk-openldap
olcAttributeTypes: ( 1.3.6.1.4.1.24552.500.1.1.1.13 NAME 'sshPublicKey' DES
 C 'MANDATORY: OpenSSH Public key' EQUALITY octetStringMatch SYNTAX 1.3.6.1.4.
 1.1466.115.121.1.40 )
olcObjectClasses: ( 1.3.6.1.4.1.24552.500.1.1.2.0 NAME 'ldapPublicKey' DESC
  'MANDATORY: OpenSSH LPK objectclass' SUP top AUXILIARY MUST ( sshPublicKey $
  uid ) )

dn: cn=module,cn=config
cn: module 
objectClass: olcModuleList
olcModulePath: /opt/bitnami/openldap/lib/openldap
olcModuleLoad: memberof
olcModuleLoad: dynlist
olcModuleLoad: refint
olcModuleLoad: argon2

dn: cn=schema,cn=config
cn: schema
objectClass: olcSchemaConfig
olcAttributeTypes: ( 1.2.840.113556.1.2.102 NAME 'memberOf' D
 he entry belongs to' EQUALITY distinguishedNameMatch SYNTAX
 115.121.1.12 NO-USER-MODIFICATION USAGE dSAOperation X-ORIGI
 ted Administrator' )
olcAttributeTypes: ( OLcfgOvAt:8.1 NAME ( 'olcDynListAttrSet'
  DESC 'Dynamic list: <group objectClass>, <URL attributeDesc
  attributeDescription>' EQUALITY caseIgnoreMatch SYNTAX OMsD
 ORDERED 'VALUES' )
olcObjectClasses: ( OLcfgOvOc:8.1 NAME ( 'olcDynListConfig' '
  DESC 'Dynamic list configuration' SUP olcOverlayConfig STRU
 ListAttrSet )

dn: cn={4}dyngroup,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: {4}dyngroup
olcObjectIdentifier: {0}NetscapeRoot 2.16.840.1.113730
olcObjectIdentifier: {1}NetscapeLDAP NetscapeRoot:3
olcObjectIdentifier: {2}NetscapeLDAPattributeType NetscapeLDA
olcObjectIdentifier: {3}NetscapeLDAPobjectClass NetscapeLDAP:
olcObjectIdentifier: {4}OpenLDAPExp11 1.3.6.1.4.1.4203.666.11
olcObjectIdentifier: {5}DynGroupBase OpenLDAPExp11:8
olcObjectIdentifier: {6}DynGroupAttr DynGroupBase:1
olcObjectIdentifier: {7}DynGroupOC DynGroupBase:2
olcAttributeTypes: {0}( NetscapeLDAPattributeType:198 NAME 'm
 dentifies an URL associated with each member of a group. Any
 URL can be used.' SUP labeledURI )
olcAttributeTypes: {1}( DynGroupAttr:1 NAME 'dgIdentity' DESC
  when processing the memberURL' SUP distinguishedName SINGLE
olcAttributeTypes: {2}( DynGroupAttr:2 NAME 'dgAuthz' DESC 'O
 tion rules that determine who is allowed to assume the dgIde
 uthzMatch SYNTAX 1.3.6.1.4.1.4203.666.2.7 X-ORDERED 'VALUES'
olcAttributeTypes: {3}( DynGroupAttr:3 NAME 'dgMemberOf' DESC
 entry belongs to' EQUALITY distinguishedNameMatch SYNTAX 1.3
 .121.1.12 )
olcObjectClasses: {0}( NetscapeLDAPobjectClass:33 NAME 'group
 TRUCTURAL MUST cn MAY ( memberURL $ businessCategory $ descr
  owner $ seeAlso ) )
olcObjectClasses: {1}( DynGroupOC:1 NAME 'dgIdentityAux' SUP
  ( dgIdentity $ dgAuthz ) )
structuralObjectClass: olcSchemaConfig

dn: olcOverlay={0}dynlist,olcDatabase={-1}frontend,cn=config
objectClass: olcOverlayConfig
objectClass: olcDynListConfig
olcOverlay: {0}dynlist
olcDynListAttrSet: {0}groupOfURLs labeledURI member
olcDynListAttrSet: {1}groupOfURLs memberURL member+memberOf@g
structuralObjectClass: olcDynListConfig
```

does not seem to be working either.

**Comment by joshuacox** [comment]
Minimally I have tried having just two files in /shemas

````
dn: cn=module,cn=config
cn: module 
objectClass: olcModuleList
olcModulePath: /opt/bitnami/openldap/lib/openldap
olcModuleLoad: dynlist
olcModuleLoad: argon2
```
and
```
dn: olcOverlay={0}dynlist,olcDatabase={-1}frontend,cn=config
objectClass: olcOverlayConfig
objectClass: olcDynListConfig
olcOverlay: {0}dynlist
olcDynListAttrSet: {0}groupOfURLs memberURL member+memberOf@groupOfNames
```

at this point I can cause the openldap instance to crash by requesting a memberof attribute:

```
docker exec openldap ldapsearch -H ldap://localhost:1389 -x -LLL -s sub -b "dc=example,dc=net" "cn=customuser" uid
dn: cn=customuser,ou=users,dc=example,dc=net
uid: customuser
```

^returns fine, But this one crashes the server:

```
docker exec openldap ldapsearch -H ldap://localhost:1389 -x -LLL -s sub -b "dc=example,dc=net" "cn=customuser" uid memberOf
ldap_result: Can't contact LDAP server (-1)
```

the logs have nothing useful to say about why it died:

```
6519f2ee.2bb6b2b4 0x7fba23fff700 conn=1003 fd=12 ACCEPT from IP=127.0.0.1:36686 (IP=0.0.0.0:1389)
6519f2ee.2bb70fb4 0x7fba237fe700 conn=1003 op=0 BIND dn="" method=128
6519f2ee.2bb77d0f 0x7fba237fe700 conn=1003 op=0 RESULT tag=97 err=0 qtime=0.000006 etime=0.000037 text=
6519f2ee.2bb8fb7c 0x7fba23fff700 conn=1003 op=1 SRCH base="dc=example,dc=net" scope=2 deref=0 filter="(cn=customuser)"
6519f2ee.2bb91cd0 0x7fba23fff700 conn=1003 op=1 SRCH attr=uid
6519f2ee.2bbe22f8 0x7fba23fff700 conn=1003 op=1 SEARCH RESULT tag=101 err=0 qtime=0.000003 etime=0.000356 nentries=1 text=
6519f2ee.2bbe9f18 0x7fba23fff700 conn=1003 op=2 UNBIND
6519f2ee.2bbf2203 0x7fba23fff700 conn=1003 fd=12 closed
6519f2fa.13988926 0x7fba237fe700 conn=1004 fd=12 ACCEPT from IP=127.0.0.1:51926 (IP=0.0.0.0:1389)
6519f2fa.139968ca 0x7fba23fff700 conn=1004 op=0 BIND dn="" method=128
6519f2fa.139a0394 0x7fba23fff700 conn=1004 op=0 RESULT tag=97 err=0 qtime=0.000005 etime=0.000047 text=
6519f2fa.139b1475 0x7fba237fe700 conn=1004 op=1 SRCH base="dc=example,dc=net" scope=2 deref=0 filter="(cn=customuser)"
6519f2fa.139b5522 0x7fba237fe700 conn=1004 op=1 SRCH attr=uid memberOf
```

my docker-compose.yml at this point was:

```
version: "3"
networks:
  openldapnet:
    external: false
services:
  openldap:
    image: openldap_whc:latest
    container_name: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=customuser
      - LDAP_PASSWORDS=custompassword
      - LDAP_ROOT=dc=example,dc=net
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=net
      - LDAP_CUSTOM_SCHEMA_FILE=/schema/custom.ldif
      - LDAP_CUSTOM_SCHEMA_DIR=/custom_schemas
      - LDAP_EXTRA_SCHEMAS=collective,corba,cosine,dsee,duaconf,dyngroup,inetorgperson,java,misc,namedobject,nis,openldap,pmi
      - BITNAMI_DEBUG=true
      #- LDAP_EXTRA_SCHEMAS=collective,corba,core,cosine,dsee,duaconf,dyngroup,inetorgperson,java,misc,msuser,namedobject,nis,openldap,pmi
    restart: always
    networks:
      - openldapnet
    ports:
      - 389:1389
      - 636:1636
    volumes: 
      - ./openldap_whc/schema:/schema
      - ./openldap_whc/schemas:/custom_schemas
      - ./openldap_whc/ldiff:/ldiff
      - ./openldap_whc/ldifs:/ldifs
        #- ./openldap_data:/bitnami/openldap
      - ./slaptest:/slaptest
      #- ./openldap_whc/schemas:/schemas

  phpldapadmin:
    ports:
      - 80:80
      - 443:443
    container_name: phpldapadmin
    networks:
      - openldapnet
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://openldap:1389
    image: osixia/phpldapadmin:0.9.0
```

**Comment by joshuacox** [comment]
I have made an example repo for demonstration purposes:

https://github.com/joshuacox/openldap-overlay-dynlist

**Comment by jonnoss1** [comment]
Hi @joshuacox ,

I recently had a [similar requirement](https://github.com/bitnami/containers/issues/48256) to use an overlay, Sync Provider, not enabled OOTB.
After some digging I found the cn=module backend was only created when a supported overlay, pprovider, was enabled.
Following this approach I extended  `libopenldap.sh` to support both Sync Provider and Access Logging overlays.
I've tested a similar extention for the Dynamic Lists overlay that deploys perfectly.

Happy to create a PR for this if that approach would work?

**Comment by joshuacox** [comment]
@jonnoss1 I'd be very happy to test a PR!  tyvm

**Comment by jonnoss1** [comment]
Hi @joshuacox,

I've pushed the changes [here](https://github.com/jonnoss1/containers/tree/main/bitnami/openldap).
You can test by building an image based on the README.md steps then running with the new image and these additional  environment options in your above docker-compose.

```
      - LDAP_ENABLE_DYNLIST=yes
      - LDAP_DYNLIST_ATTRSETS=groupOfURLs labeledURI member,groupOfURLs memberURL memberOf
```

**Comment by joshuacox** [comment]
@jonnoss1 awesome on actually implementing the environment variables.   I do seem to be getting the same crashing situation when I implement:

```
- LDAP_DYNLIST_ATTRSETS=groupOfURLs memberURL member+memberOf@groupOfNames
```

which I got directly from the man page `man slapo-dynlist`

```
docker exec openldap ldapsearch -H ldap://localhost:1389 -LLL -x -s sub -b "dc=example,dc=net" "cn=customuser" uid memberof
ldap_result: Can't contact LDAP server (-1)
```

but uid alone returns just fine:

```
docker exec openldap ldapsearch -H ldap://localhost:1389 -LLL -x -s sub -b "dc=example,dc=net" "cn=customuser" uid
dn: cn=customuser,ou=users,dc=example,dc=net
uid: customuser
```

**Comment by jonnoss1** [comment]
Hi @joshuacox ,

What schema are you using to add `memberOf` ?
I find it in the `msuser` schema file but get the following error when loading both `dyngroup` and `msuser`:

`config error processing cn={5}msuser,cn=schema,cn=config: olcAttributeTypes: Duplicate attributeType: "MSADat2:102"`

**Comment by joshuacox** [comment]
I believe I'm getting it by using dyngroup:  `LDAP_EXTRA_SCHEMAS=cosine,dyngroup,inetorgperson,nis`

Here is my full docker-compose.yml:

```
version: "3"
networks:
  openldapnet:
    external: false
services:
  openldap:
    #image: bitnami/openldap:2.6.6
    image: jonnos/openldap:test 
    container_name: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=customuser
      - LDAP_PASSWORDS=custompassword
      - LDAP_ROOT=dc=example,dc=net
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=net
      - LDAP_EXTRA_SCHEMAS=cosine,dyngroup,inetorgperson,nis
      - BITNAMI_DEBUG=true
      - LDAP_ENABLE_DYNLIST=yes
      - LDAP_DYNLIST_ATTRSETS=groupOfURLs memberURL member+memberOf@groupOfNames
        # groupOfURLs labeledURI member,groupOfURLs memberURL memberOf
      #- LDAP_CUSTOM_SCHEMA_FILE=/schema/custom.ldif
      #- LDAP_CUSTOM_SCHEMA_DIR=/custom_schemas
      #- LDAP_EXTRA_SCHEMAS=collective,corba,cosine,dsee,duaconf,dyngroup,inetorgperson,java,misc,namedobject,nis,openldap,pmi
      #- LDAP_EXTRA_SCHEMAS=collective,corba,core,cosine,dsee,duaconf,dyngroup,inetorgperson,java,misc,msuser,namedobject,nis,openldap,pmi
    restart: always
    networks:
      - openldapnet
    ports:
      - 389:1389
      - 636:1636
    volumes: 
      #- ./schema:/schema
      #- ./schemas:/schemas
      #- ./ldifs:/ldifs
      - ./slaptest:/slaptest
      #- ./data:/bitnami/openldap

  phpldapadmin:
    ports:
      - 80:80
      - 443:443
    container_name: phpldapadmin
    networks:
      - openldapnet
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://openldap:1389
    image: osixia/phpldapadmin:0.9.0
```
