### ISSUE TITLE
Gitea - Data Disspears After Resetart

### ISSUE THREAD

**Issue by TheFloatingBrain** [bitnami/containers#50538]
### Name and Version

bitnami/gitea:1.19.4

### What architecture are you using?

None

### What steps will reproduce the bug?

0. I use podman compose on this config file (modified from another [issue](https://github.com/bitnami/containers/issues/46585): 
```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

networks:
  professional-website-network:
    driver: bridge

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    volumes:
      - './postgresql_data:/bitnami/gitea:Z'
    environment:
      - POSTGRESQL_DATABASE=bitnami_gitea
      - POSTGRESQL_USERNAME=bn_gitea
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
    networks: 
      - professional-website-network
  gitea:
    image: docker.io/bitnami/gitea:latest
    volumes:
      - './gitea_data:/bitnami/gitea:Z'
    environment:
      - GITEA_ADMIN_USER=tom127
      - GITEA_ADMIN_PASSWORD=password123
      - GITEA_ADMIN_EMAIL=giteaadmin@example.org
      - GITEA_HTTP_PORT=3000
      - GITEA_SSH_LISTEN_PORT=2222
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=bitnami_gitea
      - GITEA_DATABASE_USERNAME=bn_gitea
      - GITEA_DATABASE_PASSWORD=bitnami1
    ports:
      - '3000:3000'
      - '2222:2222'
    networks: 
      - professional-website-network
```
1. I ran `podman-compose up`
2. I ran `podman-compose down` (which `podman rm`'s the containers)
3. I ran `podman-compose up`

### What is the expected behavior?

There is not much data too look at but I can see the default user create (`tom127`) when running gitea (`podman-compose up`). I expect that if both containers map to the same volume, I should be able to delete running  containers (`podman-compose down`), then map a second one with the same image/config on to the volume (`podman-compose up`), and the data should persist (`tom127` should still be there). This seems to be implied by the [documentation](https://github.com/bitnami/containers/blob/main/bitnami/gitea/README.md#maintenance) on how to perform an image upgrade

### What do you see instead?

After running `podman-compose down` then `up` the user `tom127` is missing.

### Additional information

I noticed nothing seems to go into my `postgresql_data` volume, it may be due to that?
