### ISSUE TITLE
[bitnami/discourse] Change default port 80

### ISSUE THREAD

**Issue by pierluigi-linardi** [bitnami/containers#50727]
### Name and Version

bitnami/discourse:3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to launch containers with exposed port other than 80 using this docker-compose.yml:
https://github.com/bitnami/containers/blob/main/bitnami/discourse/docker-compose.yml

I set this in the file
```yaml
discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      - '8011:3000'
```
      
I also set this variable:
`- DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER=8011`

The application loads correctly but some icons are not found, in the console I have this:
![image](https://github.com/bitnami/containers/assets/15787703/5287ff80-ae3f-4309-abc7-77f352fbeb3b)

The correct address should be this:
http://[my-domain:8011/svg-sprite/my-domain/svg-1-17ece0a9b21632685f973d1eba5bf674c7bfd373.js](http://my-domain:8011/svg-sprite/my-domain/svg-1-17ece0a9b21632685f973d1eba5bf674c7bfd373.js)
Am I missing something in the configuration?

**Comment by rafariossaa** [comment]
Hi,
  I used the following docker-compose.yaml:
```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      - '8011:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER=8011
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
  sidekiq:
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=www.example.com
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```
and, as I have no domains, I added it to my `/etc/hosts` :
```
...
127.0.0.1 example.com www.example.com
```

And I have not issues browsing: http://www.example.com:8011/

![image](https://github.com/bitnami/containers/assets/11049367/3dd40315-3cf1-4725-ab1a-078bcf343d90)
