### ISSUE TITLE
[bitnami/redis-sentinel] Sentinels cannot resolve redis master host after it's shutdown and doesn't start failover

### ISSUE THREAD

**Issue by g4iner** [bitnami/containers#51638]
### Name and Version

bitnami/redis-sentinel:7.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm starting redis in replication mode (1x master, 1x slave) with 3x sentinels using bitnami images.
Here's the configuration (nearly the same as in the docs, as easy as it can be):
```yaml
version: '2'

services:
  redis:
    image: bitnami/redis:7.2.1
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-network
    ports:
      - '6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    depends_on:
      - redis
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'
    networks:
      - redis-network

  redis-sentinel-1:
    image: bitnami/redis-sentinel:7.2.1
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    environment:
      - REDIS_MASTER_HOST=redis
    networks:
      - redis-network

  redis-sentinel-2:
    image: bitnami/redis-sentinel:7.2.1
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26380:26379'
    environment:
      - REDIS_MASTER_HOST=redis
    networks:
      - redis-network

  redis-sentinel-3:
    image: bitnami/redis-sentinel:latest
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26381:26379'
    environment:
      - REDIS_MASTER_HOST=redis
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
```
Steps to reproduce problem:
1. Start all containers 
2. Stop/kill the 'redis' container
3. 'redis-slave' not becoming master

### What is the expected behavior?

Sentinels should elect 'redis-slave' as new master

### What do you see instead?

After shutting down the master I though the sentinels will promote 'redis-slave' to become new master, but instead I only get errors:
```
2023-10-11 14:44:45 1:X 11 Oct 2023 12:44:45.145 # Failed to resolve hostname 'redis'
2023-10-11 14:44:45 1:X 11 Oct 2023 12:44:45.212 # +tilt #tilt mode entered
```
And when it comes to check replication status on slave:
```console
$ redis-cli info replication
# Replication
role:slave
master_host:redis
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_read_repl_offset:2877
slave_repl_offset:2877
master_link_down_since_seconds:1751
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
```
and logs:
```
2023-10-11 14:53:02 1:S 11 Oct 2023 12:53:02.918 # Error condition on socket for SYNC: Connection refused
2023-10-11 14:53:03 1:S 11 Oct 2023 12:53:03.707 * Connecting to MASTER redis:6379
2023-10-11 14:53:13 1:S 11 Oct 2023 12:53:13.717 # Unable to connect to MASTER: Resource temporarily unavailable
2023-10-11 14:53:14 1:S 11 Oct 2023 12:53:14.721 * Connecting to MASTER redis:6379
```

### Additional information

I tried different images (versions 6.2.13, 7.2.1, latest), using property "REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes" and without it.
Additionally I tried to change property "REDIS_MASTER_HOST" to IP from docker networkand then i see that Sentinels are becoming aware of "+odown master mymaster", but slave doesn't recognize it and sentinels not elect new masters.
How to make it work? The only way the slave becoming new master is by command 'redis-cli failover' on master instance
