### ISSUE TITLE
[bitnami/postgresql] init sql not exec

### ISSUE THREAD

**Issue by louisliu2048** [bitnami/containers#51975]
### Name and Version

bitnami/postgresql:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

ENV: macos M2

```  
master:
    container_name: master
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    volumes:
      - ../db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master  #postgres-connection-mode
      - POSTGRESQL_REPLICATION_USER=state_user #postgres-master-username
      - POSTGRESQL_REPLICATION_PASSWORD=state_password #postgres-master-password
      - POSTGRESQL_USERNAME=master_user #postgresql-master-username
      - POSTGRESQL_PASSWORD=master_password #postgresql-master-password
      - POSTGRESQL_DATABASE=state_db #postgresql-database-to-use
  ```

init_prover_db.sql:
```
CREATE DATABASE prover_db;
\connect prover_db;

CREATE SCHEMA state;

CREATE TABLE state.nodes (hash BYTEA PRIMARY KEY, data BYTEA NOT NULL);
CREATE TABLE state.program (hash BYTEA PRIMARY KEY, data BYTEA NOT NULL);

CREATE USER prover_user with password 'prover_pass';
ALTER DATABASE prover_db OWNER TO prover_user;
ALTER SCHEMA state OWNER TO prover_user;
ALTER SCHEMA public OWNER TO prover_user;
ALTER TABLE state.nodes OWNER TO prover_user;
ALTER TABLE state.program OWNER TO prover_user;
ALTER USER prover_user SET SEARCH_PATH=state;
```

### What is the expected behavior?

create prover_db and add prover_user

### What do you see instead?

```
postgresql 08:29:07.10 INFO  ==> Configuring fsync
postgresql 08:29:07.12 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 08:29:07.33 INFO  ==> Loading custom scripts...
postgresql 08:29:07.33 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 08:29:07.34 INFO  ==> Starting PostgreSQL in background...
postgresql 08:29:07.75 INFO  ==> Enabling remote connections
postgresql 08:29:07.75 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped

postgresql 08:29:07.96 INFO  ==> ** PostgreSQL setup finished! **
postgresql 08:29:07.97 INFO  ==> ** Starting PostgreSQL **
2023-10-19 08:29:07.986 GMT [1] LOG:  pgaudit extension initialized
```

<img width="308" alt="image" src="https://github.com/bitnami/containers/assets/35095310/3e6ee06a-fff8-4fcb-8d00-c642f5a29c5f">
