### ISSUE TITLE
[bitnami/openldap] Unable to authenticate users when using Argon2 or PBKDF2

### ISSUE THREAD

**Issue by unkn0wnAPI** [bitnami/containers#52034]
### Name and Version

bitnami/openldap:2.6.6-debian-11-r59

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create fresh instance of `bitnami/openldap` using `docker-compose`;
```yaml
version: '2'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '389:389'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_PORT_NUMBER=389
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=mypassword123
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,memberof
    volumes:
      - '/mnt/docker/openldap:/bitnami/openldap'
```
2. Generate Argon2 or PBKDF2 hash using `slappasswd`;
```shell
docker exec openldap slappasswd -o module-load=argon2.so -h {ARGON2} -s "mypassword" 
{ARGON2}$argon2i$v=19$m=4096,t=3,p=1$lFqtB7emwf1nLv8/3DMVOQ$ynJ8emXZC7RRXNzI1+yAHQk5Rk4HIvLgL4ZKmKPaqUM
# or
docker exec openldap slappasswd -o module-load=/opt/bitnami/openldap/libexec/openldap/pw-pbkdf2.so -h {PBKDF2-SHA256} -s "mypassword"
{PBKDF2-SHA256}10000$RZkq0xm0VnOjJXZSHppKqw$IG2tbOLuW0xSwEsaS4BycYUKzi9I51HN4V1m/y9GuK8
```
3. Modify userPassword using `ldapmodify`;
```ldif
dn: cn=user01,ou=users,dc=example,dc=com
changetype: modify
replace: userPassword
userPassword: {ARGON2}$argon2i$v=19$m=4096,t=3,p=1$lFqtB7emwf1nLv8/3DMVOQ$ynJ8emXZC7RRXNzI1+yAHQk5Rk4HIvLgL4ZKmKPaqUM
# or if PBKDF2-SHA256 is used
# userPassword: {PBKDF2-SHA256}10000$RZkq0xm0VnOjJXZSHppKqw$IG2tbOLuW0xSwEsaS4BycYUKzi9I51HN4V1m/y9GuK8
```
4. Try to authenticate the user with the password that was used in step 2 using `ldapwhoami`.

### What is the expected behavior?

Users should be able to authenticate using OpenLDAP when using Argon2/PBKDF2 as a password hashing method.
As per #5508, support for both Argon2 and PBKDF2 is present in `bitnami/openldap` since OpenLDAP 2.6 `bitnami/openldap:2.6.3-debian-11-r49`.

### What do you see instead?

The user is unable to authenticate with the OpenLDAP server:
```shell
docker exec openldap ldapwhoami -vvv -D cn=user01,ou=users,dc=example,dc=com -x -w 'mypassword'
ldap_initialize( <DEFAULT> )
ldap_bind: Invalid credentials (49)
```

### Additional information

The user is only able to authenticate when a password is hashed using hashing algorithms other than Argon2 or PBKDF2.
For Example, If I hash userPassword with container default `LDAP_PASSWORD_HASH`:
```shel
docker exec openldap slappasswd -h {SSHA} -s "mypassword"
{SSHA}bvSuOMszAYMK12Iu8/7eK/xD3FzOEp7m
```
The user is able to authenticate using OpenLDAP:
```shell
docker exec openldap ldapwhoami -vvv -D cn=user01,ou=users,dc=example,dc=com -x -w 'mypassword'
ldap_initialize( <DEFAULT> )
dn:cn=user01,ou=users,dc=example,dc=com
Result: Success (0)
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. Looking at the specific case, it is not clear to me that the issue lies in the Bitnami packaging of OpenLDAP or in the OpenLDAP configuration itself. Did you check in the upstream OpenLDAP support forums to see if there's anything missing in the steps you performed?

**Comment by unkn0wnAPI** [comment]
Hi!
Thank you for looking into it, I've looked into the OpenLDAP forum and upstream bug reports and found none that match my problem. Nonetheless, I found a way to load `argon2.so` and `pw-pbkdf2.so` modules, by using `olcModuleLoad` in a custom LDIF schema.
**Example configuration:**
`docker-compose.yml`:
```yaml
version: '2'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '389:389'
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=mypassword123
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,memberof,argon2,pkbf2
    volumes:
      - '/mnt/docker/openldap:/bitnami/openldap'
      - '/mnt/docker/openldap/ldifs/argon2.ldif:/opt/bitnami/openldap/etc/schema/argon2.ldif'
      - '/mnt/docker/openldap/ldifs/pkbf2.ldif:/opt/bitnami/openldap/etc/schema/argon2.ldif'
```
It is important to add **`argon2,pkbf2`** to `LDAP_EXTRA_SCHEMAS`.
`argon2.ldif`:
```ldif
dn: cn=module{1},cn=config
objectClass: olcModuleList
cn: module{1}
olcModulePath: /opt/bitnami/openldap/lib/openldap
olcModuleLoad: argon2.so
```

`pkbf2.ldif`:
```ldif
dn: cn=module{2},cn=config
changeType: add
objectClass: olcModuleList
cn: module{2}
olcModulePath: /opt/bitnami/openldap/libexec/openldap
olcModuleLoad: pw-pbkdf2.so
```
After adding said LDIF schemas, users are now able to authenticate with the OpenLDAP server.
Marking the issue as resolved.
