### ISSUE TITLE
PRESTASHOP_HOST not work

### ISSUE THREAD

**Issue by lmanliang** [bitnami/containers#52035]
### Name and Version

[bitnami/prestashop]

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. PRESTASHOP_HOST
2. PRESTASHOP_HOST not working
3. docker start or restart
4. the every start or restart container

apache_vhost host env value is always "example.com"
so aways run the 00_status-vhost.conf not prestashop-vhost.conf

### What is the expected behavior?

set PRESTASHOP_HOST
see the http://my-domain

### What do you see instead?

see the http://my-domain
redirect the http://localhost

### Additional information

run this container, has run the apache-env.sh

PRESTASHOP_HOST is set host
but apache-env.sh "not" has get the this var.

**Comment by fmulero** [comment]
Hi @lmanliang, thanks for using our containers.

Sorry but I don't fully understand your issue. Could you share an example and the expected behaviour? For instance, I deployed this docker-compose
```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:8
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=www.fmulero.com
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

And after that I ran several `curl`s commands without issues:
```console
$ curl -kI https://www.fmulero.com
HTTP/1.1 200 OK
Date: Mon, 23 Oct 2023 09:28:28 GMT
Server: Apache
...
$ curl -I http://www.fmulero.com
HTTP/1.1 200 OK
Date: Mon, 23 Oct 2023 09:31:12 GMT
Server: Apache
...
```

NOTE: www.fmulero.com points to my localhost
