### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by danh8012** [bitnami/containers#52132]
### Name and Version

bitnami/zookeeper:3.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I don't know why that error is displayed. how to fix it? My docker-compose file
```yaml
version: '3.9'

networks:
  kafkaNet:
    driver: bridge

services:
  zoo1:
    image: bitnami/zookeeper:3.9
    networks:
      - kafkaNet
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_LOG_LEVEL=WARN
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_SERVERS=0.0.0.0:2888:3888 zoo2:2888:3888 zoo3:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
    volumes:
      - zoo1_data:/bitnami
  
  zoo2:
    image: bitnami/zookeeper:3.9
    networks:
      - kafkaNet
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:      
      - ZOO_SERVER_ID=2
      - ZOO_LOG_LEVEL=WARN
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_SERVERS=zoo1:2888:3888 0.0.0.0:2888:3888 zoo3:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
    volumes:
      - zoo2_data:/bitnami
  
  zoo3:
    image: bitnami/zookeeper:3.9
    networks:
      - kafkaNet
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_LOG_LEVEL=WARN
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_SERVERS=zoo1:2888:3888 zoo2:2888:3888 0.0.0.0:2888:3888
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user1,user2
      - ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      - ZOO_CLIENT_USER=user1
      - ZOO_CLIENT_PASSWORD=pass4user1
    volumes:
      - zoo3_data:/bitnami

volumes:
  zoo1_data:
    driver: local
  zoo2_data:
    driver: local
  zoo3_data:
    driver: local
```

### What do you see instead?

```
my-kafka-zoo3-1  | 2023-10-25 08:59:12,483 [myid:3] - WARN  [main:o.e.j.s.ConstraintSecurityHandler@759] - ServletContext@o.e.j.s.ServletContextHandler@63f259c3{/,null,STARTING} has uncovered http methods for path: /*
my-kafka-zoo1-1  | 2023-10-25 08:59:12,517 [myid:1] - WARN  [main:o.e.j.s.h.ContextHandler@1662] - o.e.j.s.ServletContextHandler@63f259c3{/,null,STOPPED} contextPath ends with /*
my-kafka-zoo1-1  | 2023-10-25 08:59:12,519 [myid:1] - WARN  [main:o.e.j.s.h.ContextHandler@1673] - Empty contextPath
my-kafka-zoo2-1  | 2023-10-25 08:59:12,531 [myid:] - WARN  [QuorumConnectionThread-[myid=2]-1:o.a.z.s.q.QuorumCnxManager@401] - Cannot open channel to 1 at election address zoo1/172.29.0.4:3888
my-kafka-zoo2-1  | java.net.ConnectException: Connection refused (Connection refused)
my-kafka-zoo2-1  | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
my-kafka-zoo2-1  | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
my-kafka-zoo2-1  | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
my-kafka-zoo2-1  | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
my-kafka-zoo2-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
my-kafka-zoo2-1  | 	at java.base/java.net.Socket.connect(Socket.java:609)
my-kafka-zoo2-1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:384)
my-kafka-zoo2-1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:458)
my-kafka-zoo2-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
my-kafka-zoo2-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
my-kafka-zoo2-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
my-kafka-zoo3-1  | 2023-10-25 08:59:12,544 [myid:] - WARN  [QuorumConnectionThread-[myid=3]-2:o.a.z.s.q.QuorumCnxManager@401] - Cannot open channel to 1 at election address zoo1/172.29.0.4:3888
my-kafka-zoo3-1  | java.net.ConnectException: Connection refused (Connection refused)
my-kafka-zoo3-1  | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
my-kafka-zoo3-1  | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
my-kafka-zoo3-1  | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
my-kafka-zoo3-1  | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
my-kafka-zoo3-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
my-kafka-zoo3-1  | 	at java.base/java.net.Socket.connect(Socket.java:609)
my-kafka-zoo3-1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:384)
my-kafka-zoo3-1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:458)
my-kafka-zoo3-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
my-kafka-zoo3-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
my-kafka-zoo3-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
my-kafka-zoo2-1  | 2023-10-25 08:59:12,549 [myid:] - WARN  [QuorumConnectionThread-[myid=2]-3:o.a.z.s.q.QuorumCnxManager@401] - Cannot open channel to 1 at election address zoo1/172.29.0.4:3888
my-kafka-zoo2-1  | java.net.ConnectException: Connection refused (Connection refused)
my-kafka-zoo2-1  | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
my-kafka-zoo2-1  | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
my-kafka-zoo2-1  | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
my-kafka-zoo2-1  | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
my-kafka-zoo2-1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
my-kafka-zoo2-1  | 	at java.base/java.net.Socket.connect(Socket.java:609)
my-kafka-zoo2-1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:384)
my-kafka-zoo2-1  | 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:458)
my-kafka-zoo2-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
my-kafka-zoo2-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
my-kafka-zoo2-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```
