### ISSUE TITLE
Kraft Cluster cannot run Scram mode

### ISSUE THREAD

**Issue by ktpktr0** [bitnami/containers#52253]
### Name and Version

bitnami/kakfa:3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I tried running Scram using Kraft standalone, but when I was running Kraft cluster mode, it couldn't work. The following is an error
```
[2023-10-31 06:04:14,582] INFO [RaftManager id=2] Re-elect as candidate after election backoff has completed (org.apache.kafka.raft.KafkaRaftClient)
[2023-10-31 06:04:14,584] ERROR [ControllerApis nodeId=2] Unexpected error handling request RequestHeader(apiKey=VOTE, apiVersion=0, clientId=raft-client-0, correlationId=1713, headerVersion=2) -- VoteRequestData(clusterId='abcdefghijklmnopqrstug', topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=85, candidateId=0, lastOffsetEpoch=72, lastOffset=584)])]) with context RequestContext(header=RequestHeader(apiKey=VOTE, apiVersion=0, clientId=raft-client-0, correlationId=1713, headerVersion=2), connectionId='172.20.0.4:9093-172.20.0.3:42692-0', clientAddress=/172.20.0.3, principal=User:ANONYMOUS, listenerName=ListenerName(CONTROLLER), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=apache-kafka-java, softwareVersion=3.6.0), fromPrivilegedListener=false, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@45f97b92]) (kafka.server.ControllerApis)
^Corg.apache.kafka.common.errors.AuthorizerNotReadyException
```

This is the running configuration

1. Single machine
```
# Client authentication, other non authentication
docker run --rm -it \
-e BITNAMI_DEBUG=yes \
-e KAFKA_NODE_ID=1 \
-e KAFKA_PROCESS_ROLES=controller,broker \
-e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
-e KAFKA_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,BROKER://:9091 \
-e KAFKA_ADVERTISED_LISTENERS=CLIENT://:9092,BROKER://:9091 \
-e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:SASL_PLAINTEXT \
-e KAFKA_INTER_BROKER_LISTENER_NAME=BROKER \
-e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512,PLAIN \
-e KAFKA_SECURITY_INTER_BROKER_PROTOCOL=BROKER \
-e KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN \
-e KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN \
-e KAFKA_CLIENT_USERS=admin,kafkabroker1 \
-e KAFKA_CLIENT_PASSWORDS=admin-secret,kafkabroker1-secret \
-e KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer \
-e KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true \
-e KAFKA_CFG_SUPER_USERS=User:admin \
--name kafka bitnami/kafka:3.6

=====================================================================
# All role authentication
docker run --rm -it \
-e BITNAMI_DEBUG=yes \
-e KAFKA_NODE_ID=1 \
-e KAFKA_PROCESS_ROLES=controller,broker \
-e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
-e KAFKA_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,BROKER://:9091 \
-e KAFKA_ADVERTISED_LISTENERS=CLIENT://:9092,BROKER://:9091 \
-e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT \
-e KAFKA_INTER_BROKER_LISTENER_NAME=BROKER \
-e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512 \
-e KAFKA_SECURITY_INTER_BROKER_PROTOCOL=BROKER \
-e KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-512 \
-e KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=SCRAM-SHA-512 \
-e KAFKA_CLIENT_USERS=admin,kafkabroker1 \
-e KAFKA_CLIENT_PASSWORDS=admin-secret,kafkabroker1-secret \
-e KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer \
-e KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true \
-e KAFKA_CFG_SUPER_USERS=User:admin \
--name kafka bitnami/kafka:3.6

====================================================================
# Broker role not authenticated, other authentication
docker run --rm -it \
-e BITNAMI_DEBUG=yes \
-e KAFKA_NODE_ID=1 \
-e KAFKA_PROCESS_ROLES=controller,broker \
-e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
-e KAFKA_LISTENERS=SASL_PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT://:9091 \
-e KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9092,PLAINTEXT://:9091 \
-e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT \
-e KAFKA_INTER_SASL_PLAINTEXT_LISTENER_NAME=PLAINTEXT \
-e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
-e KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512 \
-e KAFKA_SECURITY_INTER_SASL_PLAINTEXT_PROTOCOL=PLAINTEXT \
-e KAFKA_CFG_SASL_MECHANISM_INTER_SASL_PLAINTEXT_PROTOCOL=PLAIN \
-e KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=SCRAM-SHA-512 \
-e KAFKA_CLIENT_USERS=admin,kafkabroker1 \
-e KAFKA_CLIENT_PASSWORDS=admin-secret,kafkabroker1-secret \
-e KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer \
-e KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true \
-e KAFKA_CFG_SUPER_USERS=User:admin \
--name kafka bitnami/kafka:3.6
```

2. Cluster
```
version: "2"

services:
  kafka-0:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,BROKER://:9091 
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://:9092,BROKER://:9091 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:SASL_PLAINTEXT 
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512,PLAIN
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=BROKER
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CLIENT_USERS=admin,kafkabroker1
      - KAFKA_CLIENT_PASSWORDS=admin-secret,kafkabroker1-secret
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      - KAFKA_CFG_SUPER_USERS=User:admin
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    volumes:
      - kafka_0_data:/bitnami/kafka

  kafka-1:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,BROKER://:9091 
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://:9092,BROKER://:9091 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:SASL_PLAINTEXT 
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512,PLAIN 
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=BROKER 
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN 
      - KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN 
      - KAFKA_CLIENT_USERS=admin,kafkabroker1 
      - KAFKA_CLIENT_PASSWORDS=admin-secret,kafkabroker1-secret 
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer 
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true 
      - KAFKA_CFG_SUPER_USERS=User:admin 
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    volumes:
      - kafka_1_data:/bitnami/kafka

  kafka-2:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,BROKER://:9091 
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://:9092,BROKER://:9091 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,CLIENT:SASL_PLAINTEXT 
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512,PLAIN 
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=BROKER 
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN 
      - KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN 
      - KAFKA_CLIENT_USERS=admin,kafkabroker1 
      - KAFKA_CLIENT_PASSWORDS=admin-secret,kafkabroker1-secret 
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer 
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true 
      - KAFKA_CFG_SUPER_USERS=User:admin 
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2        
    volumes:
      - kafka_2_data:/bitnami/kafka

volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
```

When I ran the Kraft cluster in host mode, after multiple tests, it worked normally and I think I found the cause of the error.

If a cluster without Sasl configuration restarts all nodes simultaneously after adding users and configuring Sasl, the above error will occur, and any subsequent modifications to the configuration will not have any effect; If a node restarts one by one, it can function normally

### What is the expected behavior?

Kraft cluster can function normally using Sasl configuration

### What do you see instead?

not
