### ISSUE TITLE
[bitnami/redis-sentinel] Master going down in redis-sentinel after a while

### ISSUE THREAD

**Issue by YoHanGLoot** [bitnami/containers#52263]
### Name and Version

bitnami/redis-sentinel:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Run the docker compose below:

```yaml
version: "3.1"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
      - REDIS_MASTER_SET=mymaster
    ports:
      - "6379:6379"
  redis-sentinel:
    image: "bitnami/redis-sentinel:latest"
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_SENTINEL_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
    ports:
      - "26379:26379"
```

### What is the expected behavior?

master is up all the time

### What do you see instead?

After a while, it gives `+sdown master mymaster 127.0.0.1 6379`

### Additional information

I have to have 127.0.0.1 in the docker compose due to otherwise `redis-py` giving out connection refused due to it returning the docker host internal address.
