### ISSUE TITLE
mkdir: cannot create directory '/bitnami/kafka': Permission denied

### ISSUE THREAD

**Issue by ip75** [bitnami/containers#52630]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. WSL, Windows 11
```console
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```
docker:
```console
$ docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
2. docker-compose.yml  
```yaml
 kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - 9092:9092
    volumes:
      - ./kafka/data:/bitnami
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - ppp_network
```

container creates `data` directory itself and then have no access there:

```
$ l kafka
total 12K
drwxrwxrwx 3 ip   ip   4.0K Nov  9 20:04 .
drwxr-xr-x 6 ip   ip   4.0K Nov 10 11:56 ..
drwxr-xr-x 3 root root 4.0K Nov 10 11:56 data
```


3. `docker compose up kafka`


### What is the expected behavior?

kafka started ok

### What do you see instead?

```console
$ docker compose up kafka
[+] Running 1/1
 ✔ Container local-kafka-1  Recreated                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0.1s
Attaching to local-kafka-1
local-kafka-1  | kafka 17:04:43.56
local-kafka-1  | kafka 17:04:43.56 Welcome to the Bitnami kafka container
local-kafka-1  | kafka 17:04:43.57 Subscribe to project updates by watching https://github.com/bitnami/containers
local-kafka-1  | kafka 17:04:43.57 Submit issues and feature requests at https://github.com/bitnami/containers/issues
local-kafka-1  | kafka 17:04:43.57
local-kafka-1  | kafka 17:04:43.57 INFO  ==> ** Starting Kafka setup **
local-kafka-1  | mkdir: cannot create directory '/bitnami/kafka': Permission denied
local-kafka-1 exited with code 1
```

### Additional information

no comments
