### ISSUE TITLE
LDAP_TLS_VERIFY_CLIENT should be document in README

### ISSUE THREAD

**Issue by royoan** [bitnami/containers#52968]
### Name and Version

binami/openldap

### What architecture are you using?

None

### What steps will reproduce the bug?

If enable TLS, the ldaps need verify client certificate by default. So when you connect to service, It always show connect lost.

I think  it's necessary to document the LDAP_TLS_VERIFY_CLIENT in readme file. Because the value is 'yes' default.
As out-of-box feature, we should set it 'never' or 'try' as default and indicate it in readme file.

Below is my docker-compose.yaml:
```yaml
services:
  ldap:
    image: bitnami/openldap:2.5.16
    ports:
      - "10389:1389"
      - "10636:1636"
    environment:
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=xx
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_PASSWORD=xx
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/common.pem
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/common.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/IssuingCA.crt
    volumes:
      - /opt/data/openldap/ldap-volumn/certs:/opt/bitnami/openldap/certs
      - /opt/data/openldap/ldap-volumn/bitnami_openldap:/bitnami/openldap
```
