### ISSUE TITLE
[bitnami/discourse] Silent exit after DB population

### ISSUE THREAD

**Issue by zapbulon** [bitnami/containers#52988]
### Name and Version

bitnami/discourse:3 [latest]

### What architecture are you using?

None

### What steps will reproduce the bug?

1. On an ubuntu machine where I run also other dockerized applications I tried starting Discourse via `docker compose`
2. I use a redis and postgres instance running on another machine in a private network and Redis has no password because of that
3. This is the config: 
```yaml
  discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      - '50110:3000'
    volumes:
      - '${HOME_DIR}/discourse:/bitnami/discourse'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_ENABLE_HTTPS=yes
      - DISCOURSE_USERNAME=...
      - DISCOURSE_PASSWORD=...
      - DISCOURSE_HOST=...
      - DISCOURSE_DATABASE_HOST=10.0.1.2
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=...
      - DISCOURSE_DATABASE_NAME=...
      - DISCOURSE_DATABASE_PASSWORD=...
      - DISCOURSE_REDIS_HOST=10.0.1.2
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_SMTP_HOST=...
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=...
      - DISCOURSE_SMTP_PASSWORD=...

  sidekiq:
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - '${HOME_DIR}/sidekiq:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=...
      - DISCOURSE_DATABASE_HOST=10.0.1.2
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=...
      - DISCOURSE_DATABASE_NAME=...
      - DISCOURSE_DATABASE_PASSWORD=...
      - DISCOURSE_REDIS_HOST=10.0.1.2
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_SMTP_HOST=...
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=...
      - DISCOURSE_SMTP_PASSWORD=...
```      
4. When the containers start the discourse one gets to "Populating database" and exits. There are 29 tables in the DB. 

How do I debug / troubleshoot this?

### What do you see instead?
```
discourse 10:45:17.60 INFO  ==> Welcome to the Bitnami discourse container
discourse 10:45:17.61 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 10:45:17.61 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 10:45:17.62 INFO  ==> 
discourse 10:45:17.65 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 10:45:17.70 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
discourse 10:45:17.71 INFO  ==> Creating Discourse configuration file
discourse 10:45:17.78 INFO  ==> Enabling SMTP
discourse 10:45:17.84 INFO  ==> Ensuring Discourse directories exist
discourse 10:45:17.89 INFO  ==> Trying to connect to the database server
discourse 10:45:17.97 INFO  ==> Populating database
```
