### ISSUE TITLE
[bitnami/mastodon] Mounting a custom theme breaks

### ISSUE THREAD

**Issue by sneko** [bitnami/containers#53024]
### Name and Version

bitnami/mastodon:4.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Modify the Bitnami `docker-compose.yaml` with an extra volume to have something like:
```yaml
  mastodon:
    image: docker.io/bitnami/mastodon:4
    ports:
      - 80:3000
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
      - './variables.scss:/opt/mastodon/app/javascript/styles/variables.scss'
```

(`variables.scss` being an empty file)

And using `docker-compose up` will break after 1 minute, the last log being `Precompiling assets` without any other information.

_I simplified the example by using an empty find in the specific `/opt/mastodon/app/javascript/styles/` but it's the same when mounting a real theme with for example the folder `/opt/mastodon/app/javascript/styles/custom-theme`, the importer `/opt/mastodon/app/javascript/styles/custom-theme.scss` and by modifying `/opt/mastodon/config/themes.yml` accordingly._

Thank you,

### What do you see instead?

-
