### ISSUE TITLE
[bitnami/rabbitmq] 'User can only log in via localhost' error on management interface for guest user, even using localhost.

### ISSUE THREAD

**Issue by inseroaj** [bitnami/containers#53114]
### Name and Version

bitnami/rabbitmq:3.12.9

### What architecture are you using?

None

### What steps will reproduce the bug?

With this compose file:
```yaml
  rabbitmq:
    image: 'bitnami/rabbitmq:3.12.9'
    container_name: my-rabbitmq
    environment:
      RABBITMQ_ERL_COOKIE: 'securestring'
      RABBITMQ_USERNAME: 'guest'
      RABBITMQ_PASSWORD: 'guest'
      RABBITMQ_VHOST: '/'
      RABBITMQ_PLUGINS: "rabbitmq_management"
    ports:
      - '15672:15672'
      - '5671:5671'
```

Try to authenticate with the 'guest' user on the management interface on 'http://localhost:15672'.

### What is the expected behavior?

Succesfully authenticated

### What do you see instead?

The error 'User can only log in via localhost' is returned.

### Additional information

Using the same configuration, with the `rabbitmq:3.12.9-management` image, authentication works as expected.
