### ISSUE TITLE
cluster creator container needs to be killed on shutdown

### ISSUE THREAD

**Issue by kamulos** [bitnami/containers#53144]
### Name and Version

bitnami/redis-cluster:7.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

<details>
<summary>This is my config</summary>

```yaml
version: "3.1"
services:
  redis-0:
    image: bitnami/redis-cluster:7.2
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
    environment:
      REDIS_PASSWORD: password
      REDISCLI_AUTH: password
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_NODES: redis-0 redis-1 redis-2 redis-3 redis-4 redis-5
      REDIS_CLUSTER_CREATOR: yes
  redis-1:
    image: bitnami/redis-cluster:7.2
    environment:
      REDIS_PASSWORD: password
      REDIS_NODES: redis-0 redis-1 redis-2 redis-3 redis-4 redis-5
  redis-2:
    image: bitnami/redis-cluster:7.2
    environment:
      REDIS_PASSWORD: password
      REDIS_NODES: redis-0 redis-1 redis-2 redis-3 redis-4 redis-5
  redis-3:
    image: bitnami/redis-cluster:7.2
    environment:
      REDIS_PASSWORD: password
      REDIS_NODES: redis-0 redis-1 redis-2 redis-3 redis-4 redis-5
  redis-4:
    image: bitnami/redis-cluster:7.2
    environment:
      REDIS_PASSWORD: password
      REDIS_NODES: redis-0 redis-1 redis-2 redis-3 redis-4 redis-5
  redis-5:
    image: bitnami/redis-cluster:7.2
    environment:
      REDIS_PASSWORD: password
      REDIS_NODES: redis-0 redis-1 redis-2 redis-3 redis-4 redis-5
```

</details>

Just run it with `docker compose up --build`, wait for it to be initialized and then terminate it using strg+c.

### What is the expected behavior?

All containers terminate quickly and do not need to be killed by docker.

### What do you see instead?

The cluster creator container takes 10s for me and then is forcefully killed by docker. All other containers terminate nicely.
