### ISSUE TITLE
Adding custom themes doesn't work

### ISSUE THREAD

**Issue by andriy-simonov** [bitnami/containers#53224]
### Name and Version

bitnami/keycloak:22.0.5-debian-11-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In this environment with this configurationt:
```yaml
services:
  ...
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    container_name: keycloak
    restart: always
    env_file:
      - .env
    ports:
      - '172.17.0.1:8080:8080'
    environment:
        - KEYCLOAK_DATABASE_NAME=...
        - KEYCLOAK_DATABASE_USER=...
        - KEYCLOAK_DATABASE_PASSWORD=...
        - KEYCLOAK_DATABASE_SCHEMA=public
        - PROXY_ADDRESS_FORWARDING=true
        - KEYCLOAK_PRODUCTION=true
        - KEYCLOAK_PROXY=edge
        - KEYCLOAK_EXTRA_ARGS=--auto-build --db=postgres
        - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
        - JGROUPS_DISCOVERY_EXTERNAL_IP=...
        - KEYCLOAK_CREATE_ADMIN_USER=true
```
mount a theme to the `/opt/bitnami/keycloak/themes` directory as described in the _Adding custom themes_ part of the documentation:
```yaml
services:
  ...
  keycloak:
    volumes:
      - ./mytheme:/opt/bitnami/keycloak/themes/mytheme
```
the theme name _mytheme_ is expected to appear in the _Realm settings -> Themes -> Login theme_ dropdown.

It seems that the issue is similar to https://github.com/bitnami/containers/issues/4761 because the `/opt/bitnami/keycloak/themes/mytheme` directory is created but with `root:root` user and group.

### What is the expected behavior?

I can select the newly added theme from the Realm settings -> Themes -> Login theme dropdown.

### What do you see instead?

Default keycloak themes

### Additional information

The issue may be similar to https://github.com/bitnami/containers/issues/4761 because the `/opt/bitnami/keycloak/themes/mytheme` directory is created but it's owned by `root:root`.
