### ISSUE TITLE
zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/users/ after update 3.1.2 to 3.6.0

### ISSUE THREAD

**Issue by flashick** [bitnami/containers#53361]
### Name and Version

bitnami/kafka:3.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

3 nodes with this docker-compose:
```
version: "2"
  
services:
  kafka:
    restart: unless-stopped
    image: "bitnami/kafka:3.6.0"
    container_name: kafka
    environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2181,zookeeper-january-3:2181
	  - KAFKA_BROKER_ID=3
	  - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
	  - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
	  - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-3:9092,CLIENT://kafka-3:9093
	  - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
	  - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
	  - KAFKA_CFG_SECURITY_PROTOCOL=SASL_PLAINTEXT
	  - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
	  - KAFKA_CLIENT_USERS=user_kafka
	  - KAFKA_CLIENT_PASSWORDS=user_kafka_password
	  - KAFKA_ZOOKEEPER_USER=zoo-user
	  - KAFKA_ZOOKEEPER_PASSWORD=zoo-pass
	  - KAFKA_ZOOKEEPER_PROTOCOL=SASL
    volumes:
      - /data/kafka:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
```
With that config kafka starts normally.

Now I change the version to 3.6.0 or 3.5.1 in docker-compose.yml and do:
```
docker-compose down
docker compose up -d
```

### What is the expected behavior?

New version kafka launches

### What do you see instead?

Container restarts with this error:
```
[2023-12-04 10:32:39,743] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/users/user_kafka
```

### Additional information

I want to upgrade to a new version (one broker at a time) to stop using the zookeeper. 
The bitnami documentation (https://github.com/bitnami/containers/tree/main/bitnami/kafka) says to just use a new image, but kafka documentation(https://kafka.apache.org/36/documentation/streams/upgrade-guide) says additional steps need to be taken.
