### ISSUE TITLE
[bitnami/openldap] Add custom schemas

### ISSUE THREAD

**Issue by Ericacti** [bitnami/containers#53665]
### Name and Version

bitnami/openldap

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello,
I wanted to run an LDAP server within the container and add custom schema.

I created a directory "openldap_schema" with all the schema file on my PC.

docker-compose.yml :
```yaml
version: '3'

services:
  openldap:
    image: bitnami/openldap:latest
    restart: unless-stopped
    container_name: openldap
    ports:
      - '1389:1389'
    environment:
      LDAP_LOGLEVEL: -1
      LDAP_ROOT: dc=test,dc=com
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_ADMIN_ENABLED: true
      LDAP_CONFIG_ADMIN_USERNAME: config
      LDAP_CONFIG_ADMIN_PASSWORD: config
      LDAP_EXTRA_SCHEMAS: cosine,test,dyngroup_cgi,inetorgperson,qmail_cgi,core
      LDAP_CUSTOM_SCHEMA_DIR: /custom-schemas
      BITNAMI_DEBUG: true
    networks:
      - my-network
    volumes:
      - type: bind
        source: openldap_data
        target: /bitnami/openldap
      - type: bind
        source: openldap_schema
        target: /custom-schemas

volumes:
  openldap_data:
  openldap_schema:

networks:
  my-network:
    driver: bridge
```
### What is the expected behavior?

I am expecting the default openldap configuration with custom schema files added to the container.

### What do you see instead?

When I ran the container, no custom schema files were added to the config LDAP.
