### ISSUE TITLE
[bitnami/schema-registry] can't setup in SSL

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/containers#53688]
### Name and Version

bitnami/schema-registry:7.2.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have this configuration in my docker-compose file
```yaml
  schema-registry:
    image: bitnami/schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:29092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081,https://0.0.0.0:8082
      # # For SSL connection with Kafka
      # SCHEMA_REGISTRY_KAFKA_KEYSTORE_PASSWORD: Password to access the keystore. Default: empty value.
      # SCHEMA_REGISTRY_KAFKA_KEY_PASSWORD: Password to be able to used ssl secured kafka broker with Schema Registry. Default: empty value.
      # SCHEMA_REGISTRY_KAFKA_TRUSTSTORE_PASSWORD: Password to access the truststore. Default: empty value.
      # # For dev env
      - SCHEMA_REGISTRY_DEBUG=true
      # # For Clients TLS
      - SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=/opt/bitnami/schema-registry/certs/keystore.jks # ssl.truststore.location
      - SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=keystore
      # - SCHEMA_REGISTRY_SSL_KEY_PASSWORD=schema
      - SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/schema-registry/certs/keystore.jks
      - SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=keystore
      - SCHEMA_REGISTRY_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=none
      - SCHEMA_REGISTRY_CLIENT_AUTHENTICATION=REQUESTED # Valid options: NONE, REQUESTED, or REQUIRED.
    volumes:
      - ./keystore.jks:/opt/bitnami/schema-registry/certs/keystore.jks:ro
      - ./truststore.jks:/opt/bitnami/schema-registry/certs/truststore.jks:ro
    networks:
      - kafka-strimzi-local
```
however at startup I am getting this error: 
```
ERROR ==> In order to configure HTTPS access, you must mount your ssl.keystore.jks (and optionally the ssl.truststore.jks) to the /opt/bitnami/schema-registry/certs directory.
```

How is it possible, since I am literally mounting those files in the specified directory as you can see in the docker-compose file? (plus, I've actually checked in the container and they are there as expected).

Could it be a naming issue?

Besides, is it only JKS that is supported?

### Additional information

Moreover, I think the wildcard env variables are not getting picked up, for instance, the 

`SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION`

is resulting in an empty field in the logs:
```
2023-12-09 13:02:10     ssl.truststore.location = 
2023-12-09 13:02:10     ssl.truststore.password = [hidden]
```
