### ISSUE TITLE
mongodb mistakenly replica set config

### ISSUE THREAD

**Issue by NormanTrinh** [bitnami/containers#53703]
### Name and Version

bitnami/mongodb:5.0.23

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using docker compose, these are the setups:
```yaml
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0.23
    container_name: mongo1
    user: root
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=password123

      # set replica
      - MONGODB_ADVERTISED_HOSTNAME=mongo1
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=abcdefghijklmno

    volumes:
      - './app_data/mongo_master_data:/bitnami/mongodb'

  mongodb-secondary1:
    image: docker.io/bitnami/mongodb:5.0.23
    container_name: mongo2
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo2
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=abcdefghijklmno

  mongodb-secondary2:
    image: docker.io/bitnami/mongodb:5.0.23
    container_name: mongo3
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo3
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=abcdefghijklmno
```

### What is the expected behavior?

When i access to mongo1 with the following command:
```
mongosh --host mongo1:27017 -u root -p password123 admin

rs.status();
```
I want it show the log like this (I want the output is `syncSourceHost: 'mongo1:27017'` in all SECONDARY nodes):
```
rs0 [direct: primary] test> rs.status()
{
  set: 'rs0',
  date: ISODate('2023-12-10T10:24:10.701Z'),
  myState: 1,
  term: Long('2'),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long('2000'),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastCommittedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    appliedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    durableOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z')
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1702203815, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'electionTimeout',
    lastElectionDate: ISODate('2023-12-10T10:20:45.542Z'),
    electionTerm: Long('2'),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 0, i: 0 }), t: Long('-1') },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1702203641, i: 15 }), t: Long('1') },
    numVotesNeeded: 1,
    priorityAtElection: 5,
    electionTimeoutMillis: Long('10000'),
    newTermStartDate: ISODate('2023-12-10T10:20:45.547Z'),
    wMajorityWriteAvailabilityDate: ISODate('2023-12-10T10:20:45.554Z')
  },
  members: [
    {
      _id: 0,
      name: 'mongo1:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 206,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1702203645, i: 1 }),
      electionDate: ISODate('2023-12-10T10:20:45.000Z'),
      configVersion: 6,
      configTerm: 2,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'mongo2:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 135,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.226Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.222Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo1:27017',
      syncSourceId: 2,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    },
    {
      _id: 2,
      name: 'mongo3:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 163,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.229Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.134Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo1:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1702203845, i: 1 }),
    signature: {
      hash: Binary.createFromBase64('xUdtHhUsMFjQ/Sy/VWjKogFQ29A=', 0),
      keyId: Long('7310908969227124742')
    }
  },
  operationTime: Timestamp({ t: 1702203845, i: 1 })
}
```

### What do you see instead?
You can see in SECONDARY node, mongo2 will sync from mongo3, mongo3 will sync from mongo1 if i'm using the setup above!!!
```
rs0 [direct: primary] test> rs.status()
{
  set: 'rs0',
  date: ISODate('2023-12-10T10:24:10.701Z'),
  myState: 1,
  term: Long('2'),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long('2000'),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastCommittedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    appliedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    durableOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z')
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1702203815, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'electionTimeout',
    lastElectionDate: ISODate('2023-12-10T10:20:45.542Z'),
    electionTerm: Long('2'),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 0, i: 0 }), t: Long('-1') },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1702203641, i: 15 }), t: Long('1') },
    numVotesNeeded: 1,
    priorityAtElection: 5,
    electionTimeoutMillis: Long('10000'),
    newTermStartDate: ISODate('2023-12-10T10:20:45.547Z'),
    wMajorityWriteAvailabilityDate: ISODate('2023-12-10T10:20:45.554Z')
  },
  members: [
    {
      _id: 0,
      name: 'mongo1:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 206,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1702203645, i: 1 }),
      electionDate: ISODate('2023-12-10T10:20:45.000Z'),
      configVersion: 6,
      configTerm: 2,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'mongo2:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 135,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.226Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.222Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo3:27017',
      syncSourceId: 2,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    },
    {
      _id: 2,
      name: 'mongo3:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 163,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.229Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.134Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo1:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1702203845, i: 1 }),
    signature: {
      hash: Binary.createFromBase64('xUdtHhUsMFjQ/Sy/VWjKogFQ29A=', 0),
      keyId: Long('7310908969227124742')
    }
  },
  operationTime: Timestamp({ t: 1702203845, i: 1 })
}
```
