### ISSUE TITLE
[bitnami/mongodb] - can't add a new database and user to existing ones

### ISSUE THREAD

**Issue by MaciekLeks** [bitnami/containers#53708]
### Name and Version

bitnami/mongodb 14.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Under `auth` create one or two users:
```yaml
auth:
  databases:
  - db1
  - db2
  usernames:
  - u1
  - u2
  existingSecret: k8s-secret-name
```
3.  Apply your manifests to the cluster and check if it works. You should see users u1, u2, and of course, the root user, along with the databases related to them.
4. No, add a new database and user, for example:
```yaml
auth:
  databases:
  - db1
  - db2
  - db3
  usernames:
  - u1
  - u2
  - u3
  existingSecret: updated-k8s-secret-name
```
5. Redeploy it.
6. Can you see `u3`and it's database?

### Are you using any custom parameters or values?

Yes.

### What is the expected behavior?

I should see user, database and it's role.

### What do you see instead?

I see no changes since the bootsrap deployment.

### Additional information

I use terraform helm_release resource to install bitnami/mongodb.
