### ISSUE TITLE
[bitnami/openldap] Unable to login to openldap database

### ISSUE THREAD

**Issue by Ericacti** [bitnami/containers#53815]
### Name and Version

nitnami/openldap:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i run a container bitnami/openldap with and UI (LAM, phpldapdmin,..) and i am unable to login openldap database.

the docker-compose file is :
```yaml
version: '3'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    restart: always
    hostname: serveur-ldap
    ports:
      - "389:389"
    environment:
      LDAP_ROOT: "dc=example,dc=org"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_DN: "cn=admin,dc=example,dc=org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_ADD_SCHEMAS: "yes"
    volumes:
      - type: bind
        source: openldap_data
        target: /bitnami/openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    hostname: serveur-web
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

volumes:
  openldap_data:
```

### What do you see instead?

i am unable to login to openldap database since the http://localhost:8080 with the message :
"unable to connect to ldap server openldap"
"Failed to authentificate to server"
