### ISSUE TITLE
opensearch_security.openid.base_redirect_url is not working

### ISSUE THREAD

**Issue by vohryanin** [bitnami/containers#53847]
### Name and Version

bitnami/opensearch-dashboards:2.11.0-debian-11-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploying bitnami/opensearch and bitnami/opensearch-dashboards charts with openid backend:
```yaml
opensearch-securiry/config.yml: |
openid_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: openid
              challenge: false
              config:
                subject_key: preferred_username
                roles_key: roles
                openid_connect_url: https://lkk-prod-gitlab.gkh.local:9443/.well-known/openid-configuration
                openid_connect_idp:
                  enable_ssl: true
                  verify_hostnames: false
                  trust_all: true    
                  pemtrustedcas_filepath: "/opt/bitnami/opensearch/config/gitlab-ca.crt"

  opensearch_dashboards.yml: |
    opensearch.hosts: ['https://localhost:9200']
    opensearch.ssl.verificationMode: none
    opensearch.username: kibanaserver
    opensearch.password: kibanaserver
    opensearch.requestHeadersWhitelist: [authorization, securitytenant]
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.preferred: [Private, Global]
    opensearch_security.readonly_mode.roles: [kibana_read_only]
    # Use this setting if you are running opensearch-dashboards without https
    opensearch_security.cookie.secure: false
    path:
      data: /bitnami/opensearch-dashboards/data
    pid:
      file: /opt/bitnami/opensearch-dashboards/tmp/opensearch-dashboards.pid
    server:
      host: 0.0.0.0
      port: 5601
    opensearch:
      hosts: https://elasticsearch:9200
      username: kibanaserver
      password: kibanaserver

    # Settings that enable multiple option authentication in the sign-in window #
    opensearch_security.auth.multiple_auth_enabled: true
    opensearch_security.auth.type: ["basicauth","openid"]
    
    # Basic authentication customization #
    #opensearch_security.ui.basicauth.login.brandimage: <path/to/OSlogo.png>
    #opensearch_security.ui.basicauth.login.showbrandimage: true
    
    # OIDC auth customization and start settings #
    opensearch_security.ui.openid.login.buttonname: Log in via Gitlab
    #opensearch_security.ui.openid.login.brandimage: <path/to/brand-logo.png>
    #opensearch_security.ui.openid.login.showbrandimage: true
    
    opensearch_security.openid.base_redirect_url: "http://opensearch-dashboards.lkk-monitoring-prod-cloud.gkh.local"
    
    
    #
    opensearch_security.openid.connect_url: "https://lkk-prod-gitlab.gkh.local:9443/.well-known/openid-configuration"
    opensearch_security.openid.client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    opensearch_security.openid.client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    opensearch_security.openid.scope: "openid profile email address phone groups"
    opensearch_security.openid.root_ca: /opt/bitnami/opensearch-dashboards/config/certs/gitlab-ca.crt
```
    
Gitlab's app is created. The callback URL of the app is https://opensearch-dashboards.lkk-monitoring-prod-cloud.gkh.local
GitLab CE 14.10 is used.

### What is the expected behavior?

Successful auth via SSO Gitlab

### What do you see instead?

![image](https://github.com/bitnami/containers/assets/38198927/bf5ef2c6-b5e9-4869-9ec8-f47538b96b9a)
