### ISSUE TITLE
[bitnami/openldap] bootstap openldap and suffix

### ISSUE THREAD

**Issue by Ericacti** [bitnami/containers#53958]
### Name and Version

bitnami/openldap

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to use an openldap container with an UI (LAM) using this file (docker-compose.yml):
version: '3'
```yaml
services:
  openldap:
    image: bitnami/openldap:latest
    restart: unless-stopped
    container_name: openldap
    hostname: serveur-ldap
    domainname: "dc=test,dc=com"
    ports:
      - '389:389'
    environment:
      LDAP_PORT_NUMBER: "389"
      LDAP_LOGLEVEL: -1
      LDAP_ROOT: "dc=test,dc=com"
      LDAP_ADMIN_DN: "cn=admin,dc=test,dc=com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_ADD_SCHEMAS: "no"
      LDAP_CUSTOM_SCHEMA_DIR: /ldif-schemas
      #LDAP_SKIP_DEFAULT_TREE: yes
      #LDAP_CUSTOM_LDIF_DIR: /ldif-init
      BITNAMI_DEBUG: true
    networks:
      - my-network
    volumes:
      - type: bind
        source: openldap_data
        target: /bitnami/openldap
      - type: bind
        source: openldap_schema
        target: /ldif-schemas
      - type: bind
        source: openldap_init
        target: /ldif-init

  ldap-account-manager:
    image: ldapaccountmanager/lam:latest
    restart: unless-stopped
    container_name: lam
    hostname: ldap-account-manager
    ports:
      - "8080:80"
    environment:
      LAM_PASSWORD: "admin"
      LAM_LANG: "en_US"
      LDAP_SERVER: "ldap://serveur-ldap:389"
      LDAP_DOMAIN: "test.com"
      LDAP_BASE_DN: "dc=test,dc=com"
      LDAP_USER: "cn=admin,dc=test,dc=com"
      DEBUG: "true"
    networks:
      - my-network

volumes:
  openldap_data:
  openldap_schema:
  openldap_init:
  lamconfig:

networks:
  my-network:
    driver: bridge
```
### What is the expected behavior?

i can authenticate using LDAP credentials and UI client (LAM)

### What do you see instead?

when i test my authenticate using LDAP credentials and UI client (LAM), i ve got this message:
```
The following suffixes are missing in LDAP. LAM can create them for you.You can setup the LDAP suffixes for all account types in your LAM server profile on tab "Account types".
dc=test,dc=com
```
