### ISSUE TITLE
Wordpress plugin request url error

### ISSUE THREAD

**Issue by tonycody** [bitnami/containers#54027]
### Name and Version

bitnami/wordpress:6.4.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

[onenav.zip](https://github.com/bitnami/containers/files/13734187/onenav.zip)
When I install this plugin, the console shows that requesting the plugin related url is incorrect.
![image](https://github.com/bitnami/containers/assets/6773121/0375ae1b-9353-4a06-9779-e7a9d648ccd2)

### What do you see instead?

```shell
#incorrect
http://localhost/wp-content/themes/onenav/bitnami/wordpress/wp-content/themes/onenav/inc/framework/assets/css/style.min.css?ver=2.2.8
#correct
http://localhost/wp-content/themes/onenav/inc/framework/assets/css/style.min.css?ver=2.2.8
#
```

**Comment by carrodher** [comment]
Could you please provide more info about the process followed to install the plugin? Are you using the `WORDPRESS_PLUGINS` env. variable?

`WORDPRESS_PLUGINS`: List of WordPress plugins to install and activate, separated via commas. Can also be set to all to activate all currently installed plugins, or none to skip. Default: none

**Comment by tonycody** [comment]
> 您能否提供有关安装插件所遵循的过程的更多信息？您是否正在使用 env.变量？`WORDPRESS_PLUGINS`
> 
> `WORDPRESS_PLUGINS`：要安装和激活的 WordPress 插件列表，用逗号分隔。也可以设置为 all 以激活所有当前安装的插件，或设置为 none 以跳过。默认值：无

```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'
services:
  mariadb:
    image: bitnami/mariadb:11.2.2
    volumes:
      - bitnami_mariadb_data:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    networks:
      bitnami_wordpress_default:
        ipv4_address: 192.169.32.11
  wordpress:
    image: bitnami/wordpress-nginx:6.4.2
   ports:
     - '80:8080'
     - '443:8443'
    volumes:
      - bitnami_wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    networks:
      bitnami_wordpress_default:
        ipv4_address: 192.169.32.12
networks:
  bitnami_wordpress_default:
    ipam:
      driver: default
      config:
        - subnet: 192.169.32.0/24
volumes:
  bitnami_mariadb_data:
    driver: local
  bitnami_wordpress_data:
    driver: local
```

[onenav.zip](https://github.com/bitnami/containers/files/13747241/onenav.zip)

You verify this with docker compose above, and install this onenav.zip themed plugin after starting the container to find out!
