### ISSUE TITLE
[bitnami/kafka][zookeeper to kraft migration] Error 'BROKER_ID_NOT_REGISTERED' when updating broker to act as controller + broker

### ISSUE THREAD

**Issue by manojrkrish** [bitnami/containers#54066]
### Name and Version

bitnami/kafka:3.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Please find the issue and steps to reproduce the issue as below,

#### Issue
When we try to migrate kafka from zookeeper to kraft we are seeing error `BROKER_ID_NOT_REGISTERED` in the instance which is updated to controller + broker role.

#### Steps
We are trying migrate test setup with `2 broker + 1 zookeeper` to `1 broker + 1 (controller + broker)` in the below steps. Please follow the below steps to reproduce the issue using docker-compose. 

1. Create local docker volumes to replicate migration scenario and use the volumes to mount into kafka and zookeeper containers.
```
> docker volume create zk_data
> docker volume create kafka_data_0
> docker volume create kafka_data_1
```
2. Start `2 broker + 1 zookeeper` containers with `docker-compose -f <config_file> up` using below configuration.
```yaml
version: '3.9'
services:
  kafka-0:
    image: bitnami/kafka:3.6.1
    user: "1001"
    hostname: kafka-0
    ports:
      - '9092:9092'
    volumes:
      - kafka_data_0:/bitnami
    environment:
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-0:9092"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092"
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_CFG_LOG_ROLL_HOURS=48
    depends_on:
      - zookeeper

  kafka-1:
    image: bitnami/kafka:3.6.1
    user: "1001"
    hostname: kafka-1
    ports:
      - '9097:9097'
    volumes:
      - kafka_data_1:/bitnami
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-1:9092"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092"
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_CFG_LOG_ROLL_HOURS=48
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper
    ports:
      - '2181:2181'
    user: "1001"
    volumes:
      - zk_data:/bitnami
    environment:
     - ZOO_SERVER_ID=0
     - ZOO_HEAP_SIZE=100
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_4LW_COMMANDS_WHITELIST="*"
     - ZOO_SERVERS=0.0.0.0:2888:3888

volumes:
  kafka_data_0:
    external: true
    name: kafka_data_0
  kafka_data_1:
    external: true
    name: kafka_data_1
  zk_data:
    external: true
    name: zk_data
```
3. Once the containers up and kafka is ready, get cluster.id from the kafka instance data used to set `KAFKA_KRAFT_CLUSTER_ID`.
```
docker run -it --rm --net=host -v kafka_data_0:/bitnami bitnami/kafka:3.6.1 /bin/bash -c 'cat /bitnami/kafka/data/meta.properties'
```
4. Exit the docker-compose command or bring down containers using `docker-compose -f <config_file> down`
5.  Start migrating to kraft by updating one of the broker to (controller + broker) `1 broker + 1 (broker + controller) + 1 zookeeper` containers with `docker-compose -f <config_file> up` using below configuration.
```yaml
version: '3.9'
services:
  kafka-0:
    image: bitnami/kafka:3.6.1
    user: "1001"
    hostname: kafka-0
    ports:
      - '9092:9092'
    volumes:
      - kafka_data_0:/bitnami
    environment:
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-0:9092"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092"
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_CFG_LOG_ROLL_HOURS=48
      - KAFKA_KRAFT_CLUSTER_ID=rg9uuoefTmayyvwnEltzMQ
    depends_on:
      - zookeeper

  kafka-1:
    image: bitnami/kafka:3.6.1
    user: "1001"
    hostname: kafka-1
    ports:
      - '9097:9097'
    volumes:
      - kafka_data_1:/bitnami
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9097
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ZOOKEEPER_METADATA_MIGRATION_ENABLE=true
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9097"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092"
      - KAFKA_CFG_LOG_RETENTION_HOURS=72
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_CFG_LOG_ROLL_HOURS=48
      - KAFKA_KRAFT_CLUSTER_ID=rg9uuoefTmayyvwnEltzMQ
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper
    ports:
      - '2181:2181'
    user: "1001"
    volumes:
      - zk_data:/bitnami
    environment:
     - ZOO_SERVER_ID=0
     - ZOO_HEAP_SIZE=100
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_4LW_COMMANDS_WHITELIST="*"
     - ZOO_SERVERS=0.0.0.0:2888:3888

volumes:
  kafka_data_0:
    external: true
    name: kafka_data_0
  kafka_data_1:
    external: true
    name: kafka_data_1
  zk_data:
    external: true
    name: zk_data
```
6. Kraft migration results in error with `BROKER_ID_NOT_REGISTERED` and eventually shutdown the broker.

### What is the expected behavior?

Expectation is that controller successfully migrates all metadata from zookeeper and update the broker to `controller + broker` role.

We want to migrate existing set of brokers to act as both controller and broker without introducing any additional nodes/instances in our production setup. 

### What do you see instead?

Kraft migration results in error with `BROKER_ID_NOT_REGISTERED` and eventually shutdown the broker.
```
[2023-12-22 11:16:30,136] INFO [KRaftMigrationDriver id=1] No brokers are known to KRaft, waiting for brokers to register. (org.apache.kafka.metadata.migration.KRaftMigrationDriver)
[2023-12-22 11:16:30,137] INFO [GroupCoordinator 1]: Starting up. (kafka.coordinator.group.GroupCoordinator)
[2023-12-22 11:16:30,146] INFO [GroupCoordinator 1]: Startup complete. (kafka.coordinator.group.GroupCoordinator)
[2023-12-22 11:16:30,148] INFO [TransactionCoordinator id=1] Starting up (kafka.coordinator.transaction.TransactionCoordinator)
[2023-12-22 11:16:30,151] INFO [TxnMarkerSenderThread-1]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
[2023-12-22 11:16:30,153] INFO [TransactionCoordinator id=1] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
[2023-12-22 11:16:30,157] INFO [BrokerMetadataPublisher id=1] Updating metadata.version to 14 at offset OffsetAndEpoch(offset=6, epoch=1). (kafka.server.metadata.BrokerMetadataPublisher)
[2023-12-22 11:16:30,394] INFO [QuorumController id=1] registerBroker: event failed with BrokerIdNotRegisteredException in 366 microseconds. (org.apache.kafka.controller.QuorumController)
[2023-12-22 11:16:30,396] INFO [BrokerLifecycleManager id=1] Unable to register broker 1 because the controller returned error BROKER_ID_NOT_REGISTERED (kafka.server.BrokerLifecycleMan
      ager)
```

#### Note
[Migrating from Zookeeper mode to KRaft mode](https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#migrating-from-zookeeper-mode-to-kraft-mode) seems to be working, however we want to migrate existing set of brokers to `controller + broker` role without without introducing any additional nodes/instances in our production setup.
