### ISSUE TITLE
Redmine Container will not connect to database and exits with code 1

### ISSUE THREAD

**Issue by max1e6** [bitnami/containers#54298]
### Name and Version

bitnami/redmine:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Downloaded the docker-compose.yml file using the curl commnd in the readme.md. Editted docker-compose.yml to use latest redmine image. ran docker-compose up.

I have also replaced the redmine container with a generic Ubuntu container and installed mysql-client tools I was able to connect to the mariadb database without issue, which makes me suspect that there is an issue in the redmine container.

### What is the expected behavior?

I expect that the both the mariadb and the redmine container would be created. The database iniitialized and redmine setup to start waiting for new connections

### What do you see instead?

The redmine container is exiting with code 1.

### Additional information
```
redmine-mariadb-1  | 2023-12-28 19:43:05 0 [Note] Recovering after a crash using tc.log
redmine-mariadb-1  | 2023-12-28 19:43:05 0 [Note] Starting table crash recovery...
redmine-mariadb-1  | 2023-12-28 19:43:05 0 [Note] Crash table recovery finished.
redmine-redmine-1  | redmine 19:43:05.57 INFO  ==>
redmine-redmine-1  | redmine 19:43:05.57 INFO  ==> Welcome to the Bitnami redmine container
redmine-redmine-1  | redmine 19:43:05.57 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine-redmine-1  | redmine 19:43:05.57 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/is                         sues
redmine-redmine-1  | redmine 19:43:05.57 INFO  ==>
redmine-redmine-1  | redmine 19:43:05.58 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine-redmine-1  | redmine 19:43:05.59 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine-redmine-1  | redmine 19:43:05.78 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons,                          do not use this flag in a production environment.
redmine-redmine-1  | redmine 19:43:05.94 INFO  ==> Ensuring Redmine directories exist
redmine-mariadb-1  | 2023-12-28 19:43:06 0 [Note] DDL_LOG: Crash recovery executed 1 entries
redmine-mariadb-1  | 2023-12-28 19:43:06 0 [Note] Server socket created on IP: '127.0.0.1'.
redmine-mariadb-1  | 2023-12-28 19:43:06 0 [Warning] 'user' entry 'root@a9591dcd4f8e' ignored in --skip-name-resolve mode.
redmine-mariadb-1  | 2023-12-28 19:43:06 0 [Warning] 'proxies_priv' entry '@% root@a9591dcd4f8e' ignored in --skip-name-resolve m                         ode.
redmine-mariadb-1  | 2023-12-28 19:43:06 0 [Note] mysqld: Event Scheduler: Loaded 0 events
redmine-redmine-1  | redmine 19:43:06.33 INFO  ==> Trying to connect to the database server
redmine-mariadb-1  | 2023-12-28 19:43:06 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
redmine-mariadb-1  | Version: '11.2.2-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
redmine-redmine-1  | redmine 19:44:06.69 ERROR ==> Could not connect to the database
redmine-redmine-1 exited with code 1
```

**Comment by carrodher** [comment]
Are you able to reproduce the issue by using the docker-compose present in this repository without any modification?

**Comment by andreiropotica** [comment]
> Are you able to reproduce the issue by using the docker-compose present in this repository without any modification?

hello, I have the same issue, yes with the default docker-compose.yml file
```

# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```
