### ISSUE TITLE
Kafka topics become clogged

### ISSUE THREAD

**Issue by LordMilutin** [bitnami/containers#54401]
### Name and Version

bitnami/kafka:3.6.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I have set up the Kafka via docker-compose:

```yaml
version: '2'
services:
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6.0
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://192.168.1.80:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - ./data:/bitnami/kafka
    deploy:
      resources:
        limits:
          memory: 4G    
```

And everything worked fine up until one point where the topics won't receive/send messages from my app. 
When I specify a new non-existing topic in my app, it creates it, and it works normally for a few days until it clogs again, and I have to either create another new topic or remove persistent data and restart kafka so that it becomes like factory default settings. 

Is there any additional configuration besides this one in docker-compose? 

### What do you see instead?

Topics are clogged, they won't send/receive messages.
