### ISSUE TITLE
[bitnami/wordpress] What is the development workflow ?

### ISSUE THREAD

**Issue by FractalMind** [bitnami/containers#54469]
### Name and Version

docker.io/bitnami/wordpress:6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Here's my docker-compose.yml

```yaml
version: '3'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress

  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '7777:8080'
      - '7443:8443'
    volumes:
      - ./wordpress-data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_PASSWORD=admin
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=admin
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

As you can see I have mounted ./wordpress-data:/bitnami/wordpress
So I can edit the code and store it in Git. But because of the mount the site is very slow see: https://stackoverflow.com/a/56408694

### What do you see instead?

How can I have the stored code inside the container with being mounted to be ready for Production?

Thank you for your time
