### ISSUE TITLE
[bitnami/apisix] module 'resty.apisix.patch' not found (apisix-3.7.0-0-linux-${OS_ARCH}-debian-11.tar.gz/openresty/luajit/share/lua/5.1/apisix/init.lua)

### ISSUE THREAD

**Issue by rlaflamme** [bitnami/containers#54529]
### Name and Version

bitnami/apisix:2.2.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Environment: OKD 4.14 on Proxmox 8.1.3

See tests 1-4  from the other section.
Also you will need to add some "traces" in the file init.lua to get the stack trace

I add some traces showing the initialization of the map variable ***apisix_base_flags***

The code:

```
local ok, apisix_base_flags = pcall(require, "resty.apisix.patch")
core.log.info("####### apisix_base_flags = ", apisix_base_flags)
core.log.info("####### ok = ", ok)
if not ok then
    core.log.info("####### It's not ok = ", ok)
    apisix_base_flags = {}
    core.log.info("####### UPDATED : apisix_base_flags = ", core.json.encode(apisix_base_flags))
end
```

The logs:

```
2024/01/09 04:06:31 [info] 1#1: [lua] core.lua:26: use config_provider: etcd
2024/01/09 04:06:31 [info] 1#1: [lua] init.lua:27: use discovery: kubernetes
2024/01/09 04:06:31 [info] 1#1: [lua] init.lua:72: ####### apisix_base_flags = module 'resty.apisix.patch' not found:
	no field package.preload['resty.apisix.patch']
	no file '/usr/local/apisix//deps/share/lua/5.1/resty/apisix/patch.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/resty/apisix/patch/init.lua'
	no file '/usr/local/apisix/resty/apisix/patch.lua'
	no file '/usr/local/apisix/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch.ljbc'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch/init.ljbc'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch.ljbc'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch/init.ljbc'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch/init.lua'
	no file './resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/luajit-2.1.0-beta3/resty/apisix/patch.lua'
	no file '/usr/local/share/lua/5.1/resty/apisix/patch.lua'
	no file '/usr/local/share/lua/5.1/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/lua/5.1/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/lua/5.1/resty/apisix/patch/init.lua'
	no file './resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/luajit-2.1.0-beta3/resty/apisix/patch.lua'
	no file '/usr/local/share/lua/5.1/resty/apisix/patch.lua'
	no file '/usr/local/share/lua/5.1/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/lua/5.1/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/lua/5.1/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch.ljbc'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch/init.ljbc'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch.ljbc'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch/init.ljbc'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch/init.lua'
	no file './resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/luajit-2.1.0-beta3/resty/apisix/patch.lua'
	no file '/usr/local/share/lua/5.1/resty/apisix/patch.lua'
	no file '/usr/local/share/lua/5.1/resty/apisix/patch/init.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/lua/5.1/resty/apisix/patch.lua'
	no file '/opt/bitnami/apisix/openresty/luajit/share/lua/5.1/resty/apisix/patch/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty/apisix/patch.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/resty/apisix/patch.so'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty/apisix/patch.so'
	no file '/opt/bitnami/apisix/openresty/lualib/resty/apisix/patch.so'
	no file './resty/apisix/patch.so'
	no file '/usr/local/lib/lua/5.1/resty/apisix/patch.so'
	no file '/opt/bitnami/apisix/openresty/luajit/lib/lua/5.1/resty/apisix/patch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty/apisix/patch.so'
	no file '/usr/local/lib/lua/5.1/resty/apisix/patch.so'
	no file '/opt/bitnami/apisix/openresty/luajit/lib/lua/5.1/resty/apisix/patch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/resty.so'
	no file '/opt/bitnami/apisix/openresty/site/lualib/resty.so'
	no file '/opt/bitnami/apisix/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/opt/bitnami/apisix/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	n
2024/01/09 04:06:31 [info] 1#1: [lua] init.lua:73: ####### ok = false
2024/01/09 04:06:31 [info] 1#1: [lua] init.lua:75: ####### It's not ok = false
2024/01/09 04:06:31 [info] 1#1: [lua] init.lua:77: ####### UPDATED : apisix_base_flags = {}
```

I have been able to get it work ... with some little "cheat" int the file init.lua. at line 384

First the issue is the evaluation of this line of code
```
(line 353):
  local function verify_https_client(ctx)
... 
(line 382)

    local matched_ssl = ctx.matched_ssl
    if matched_ssl.value.client and apisix_ssl.support_client_verification() then
---
original code:
        local verified = apisix_base_flags.client_cert_verified_in_handshake
cheat code:
        ---  local verified = apisix_base_flags.client_cert_verified_in_handshake
        local verified = true
---
        if not verified then
            -- vanilla OpenResty requires to check the verification result
            local res = ctx.var.ssl_client_verify
            if res ~= "SUCCESS" then
                if res == "NONE" then
                    core.log.error("client certificate was not present")
                else
                    core.log.error("client certificate verification is not passed: ", res)
                end

                return false
            end
        end
```
In the original code
local verified = apisix_base_flags.client_cert_verified_in_handshake
```
is always evaluated to ***false*** because the value of the map variable  ***apisix_base_flags*** is empty.
So it appears to be the issue.

```

The image used in the chart:
```
## Bitnami APISIX image
## ref: https://hub.docker.com/r/bitnami/apisix/tags/
## @param image.registry [default: REGISTRY_NAME] APISIX image registry
## @param image.repository [default: REPOSITORY_NAME/apisix] APISIX image repository
## @skip image.tag APISIX image tag (immutable tags are recommended)
## @param image.digest APISIX image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
## @param image.pullPolicy APISIX image pull policy
## @param image.pullSecrets APISIX image pull secrets
## @param image.debug Enable APISIX image debug mode
##
image:
  registry: docker.io
  repository: bitnami/apisix
  tag: 3.7.0-debian-11-r2
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##

```

### What is the expected behavior?

I can test successfully the skip mtls with the "cheat code"
Test 1:  test using uri ***/uuid*** with client certificates: expected: 200, (skip_mtls_uri_regex == /anything.*)

```
[root@okd4-cli apisix]# curl -v https://admin.apisix.dev/uuid --cacert t/certs/mtls_ca.crt --cert t/certs/mtls_client.crt --key t/certs/mtls_client.key
* processing: https://admin.apisix.dev/uuid
*   Trying 10.10.1.50:443...
* Connected to admin.apisix.dev (10.10.1.50) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=cn; ST=GuangDong; L=ZhuHai; CN=admin.apisix.dev; OU=ops
*  start date: Dec  1 10:17:24 2022 GMT
*  expire date: Aug 18 10:17:24 2042 GMT
*  issuer: C=cn; ST=GuangDong; L=ZhuHai; CN=ca.apisix.dev; OU=ops
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: admin.apisix.dev]
* h2 [:path: /uuid]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET /uuid HTTP/2
> Host: admin.apisix.dev
> User-Agent: curl/8.2.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< content-type: application/json
< content-length: 53
< date: Tue, 09 Jan 2024 03:39:54 GMT
< access-control-allow-origin: *
< access-control-allow-credentials: true
< server: APISIX/3.7.0
<
{
  "uuid": "046cd8b1-07d8-4df5-b82b-98bed5f91cb7"
}
* Connection #0 to host admin.apisix.dev left intact

```
Test 2:  test using uri ***/uuid*** without providing client certificates: expected: 400, (skip_mtls_uri_regex == /anything.*)
```
[root@okd4-cli apisix]# curl -v https://admin.apisix.dev/uuid --cacert t/certs/mtls_ca.crt
* processing: https://admin.apisix.dev/uuid
*   Trying 10.10.1.50:443...
* Connected to admin.apisix.dev (10.10.1.50) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=cn; ST=GuangDong; L=ZhuHai; CN=admin.apisix.dev; OU=ops
*  start date: Dec  1 10:17:24 2022 GMT
*  expire date: Aug 18 10:17:24 2042 GMT
*  issuer: C=cn; ST=GuangDong; L=ZhuHai; CN=ca.apisix.dev; OU=ops
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: admin.apisix.dev]
* h2 [:path: /uuid]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET /uuid HTTP/2
> Host: admin.apisix.dev
> User-Agent: curl/8.2.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 400
< date: Tue, 09 Jan 2024 03:40:38 GMT
< content-type: text/html; charset=utf-8
< content-length: 154
< server: APISIX/3.7.0
<
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>openresty</center>
</body>
</html>
* Connection #0 to host admin.apisix.dev left intact
```

Test 3:  test using uri ***/anything/all*** without providing client certificates, expected: 200, (skip_mtls_uri_regex == /anything.*)
```
[root@okd4-cli apisix]# curl -v https://admin.apisix.dev/anything/all --cacert t/certs/mtls_ca.crt
* processing: https://admin.apisix.dev/anything/all
*   Trying 10.10.1.50:443...
* Connected to admin.apisix.dev (10.10.1.50) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=cn; ST=GuangDong; L=ZhuHai; CN=admin.apisix.dev; OU=ops
*  start date: Dec  1 10:17:24 2022 GMT
*  expire date: Aug 18 10:17:24 2042 GMT
*  issuer: C=cn; ST=GuangDong; L=ZhuHai; CN=ca.apisix.dev; OU=ops
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: admin.apisix.dev]
* h2 [:path: /anything/all]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET /anything/all HTTP/2
> Host: admin.apisix.dev
> User-Agent: curl/8.2.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< content-type: application/json
< content-length: 411
< date: Tue, 09 Jan 2024 03:45:56 GMT
< access-control-allow-origin: *
< access-control-allow-credentials: true
< server: APISIX/3.7.0
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "admin.apisix.dev",
    "User-Agent": "curl/8.2.1",
    "X-Amzn-Trace-Id": "Root=1-659cc174-4aa6ecb178570cdc13e6d578",
    "X-Forwarded-Host": "admin.apisix.dev"
  },
  "json": null,
  "method": "GET",
  "origin": "10.128.2.1, 74.57.230.36",
  "url": "http://admin.apisix.dev/anything/all"
}
* Connection #0 to host admin.apisix.dev left intact

```

Test 4:  test using uri ***/anything/all*** with client certificates, expected: 200, (skip_mtls_uri_regex == /anything.*)
```
[root@okd4-cli apisix]# curl -v https://admin.apisix.dev/anything/all --cacert t/certs/mtls_ca.crt --cert t/certs/mtls_client.crt --key t/certs/mtls_client.key
* processing: https://admin.apisix.dev/anything/all
*   Trying 10.10.1.50:443...
* Connected to admin.apisix.dev (10.10.1.50) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=cn; ST=GuangDong; L=ZhuHai; CN=admin.apisix.dev; OU=ops
*  start date: Dec  1 10:17:24 2022 GMT
*  expire date: Aug 18 10:17:24 2042 GMT
*  issuer: C=cn; ST=GuangDong; L=ZhuHai; CN=ca.apisix.dev; OU=ops
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: admin.apisix.dev]
* h2 [:path: /anything/all]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET /anything/all HTTP/2
> Host: admin.apisix.dev
> User-Agent: curl/8.2.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< content-type: application/json
< content-length: 411
< date: Tue, 09 Jan 2024 03:46:50 GMT
< access-control-allow-origin: *
< access-control-allow-credentials: true
< server: APISIX/3.7.0
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "admin.apisix.dev",
    "User-Agent": "curl/8.2.1",
    "X-Amzn-Trace-Id": "Root=1-659cc1aa-6e76ce050bd4dd2c70d1fbf6",
    "X-Forwarded-Host": "admin.apisix.dev"
  },
  "json": null,
  "method": "GET",
  "origin": "10.128.2.1, 74.57.230.36",
  "url": "http://admin.apisix.dev/anything/all"
}
* Connection #0 to host admin.apisix.dev left intact
```

The image used in the chart:
```
## Bitnami APISIX image
## ref: https://hub.docker.com/r/bitnami/apisix/tags/
## @param image.registry [default: REGISTRY_NAME] APISIX image registry
## @param image.repository [default: REPOSITORY_NAME/apisix] APISIX image repository
## @skip image.tag APISIX image tag (immutable tags are recommended)
## @param image.digest APISIX image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
## @param image.pullPolicy APISIX image pull policy
## @param image.pullSecrets APISIX image pull secrets
## @param image.debug Enable APISIX image debug mode
##
image:
  registry: docker.io
  repository: bitnami/apisix
  tag: 3.7.0-debian-11-r2
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##

```

### What do you see instead?

Always get HTTP error 400 on test #3 (skip mtls_uri_regex) should return HTTP 200

The module breaks the feature documented [here](https://apisix.apache.org/docs/apisix/next/tutorials/client-to-apisix-mtls/#mtls-bypass-based-on-regular-expression-matching-against-uri).  
Otherwise, this feature works well outside a k8s cluster (standalone) as document [here](https://apisix.apache.org/docs/apisix/getting-started/README)
