### ISSUE TITLE
[bitnami/rabbitmq] rabbitmq healthcheck : ./healthcheck.sh: line 29: $1: unbound variable

### ISSUE THREAD

**Issue by leshalv** [bitnami/containers#54750]
### Name and Version

bitnami/rabbitmq:3.12

### What architecture are you using?

None

### What steps will reproduce the bug?

Run the container and execute the healthcheck.sh

### What do you see instead?

<img width="645" alt="image" src="https://github.com/bitnami/containers/assets/30397655/44fcf0b1-817f-4a85-ab2b-4a0b27bb21e2">

**Comment by leshalv** [comment]
I configured it like this in docker compose and it doesn't seem to work well

```
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/rabbitmq/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 15s
```
