### ISSUE TITLE
[bitnami/openldap] Same regression again: Prevents configuring custom LDIFs with LDAP_REQUIRE_TLS=yes

### ISSUE THREAD

**Issue by cfryanr** [bitnami/containers#54819]
### Name and Version

bitnami/openldap:2.6.6

### What architecture are you using?

None

### What steps will reproduce the bug?

The issue that was previously reported in https://github.com/bitnami/containers/issues/49575 and previously fixed by https://github.com/bitnami/containers/commit/d4db99ac353fe7b8d4b8be21569abfed99fd856d#diff-e3475f86379af4ff39cb9b913e41c53d0d63afab71771af1d7fcc4f4cb08b2fb has recently regressed again, caused by https://github.com/bitnami/containers/commit/9f6278e4abadcf4ff63eb42310739646e1ed1485.

It seems like the author of https://github.com/bitnami/containers/commit/9f6278e4abadcf4ff63eb42310739646e1ed1485 purposefully reverted the original fix for this issue. I don't know why. This causes the original bug to happen again.

### What is the expected behavior?

You should be able to use `LDAP_CUSTOM_LDIF_DIR` with `LDAP_REQUIRE_TLS=yes`.

### What do you see instead?

It is impossible to use these flags together now. The container will die. Here is the tail of the log.

```
[38;5;6m [38;5;5m19:18:41.09 [0m[38;5;2mINFO [0m ==> Loading custom LDIF files...
[38;5;6m [38;5;5m19:18:41.10 [0m[38;5;3mWARN [0m ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
65a6d691.07095c22 0x7f0557fd5700 conn=1007 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
65a6d691.070bc0af 0x7f0557fd5700 conn=1007 op=0 BIND dn="cn=admin,dc=pinniped,dc=dev" method=128
65a6d691.070c9a09 0x7f0557fd5700 conn=1007 op=0 RESULT tag=97 err=13 qtime=0.000013 etime=0.000099 text=TLS confidentiality required
ldap_bind: Confidentiality required (13)
	additional info: TLS confidentiality required
65a6d691.071101b4 0x7f0557fd5700 conn=1007 op=1 UNBIND
65a6d691.0711f08e 0x7f0557fd5700 conn=1007 fd=12 closed
65a6d691.07870048 0x7f05587d6700 daemon: shutdown requested and initiated.
65a6d691.078df262 0x7f05587d6700 slapd shutdown: waiting for 0 operations/tasks to finish
65a6d691.07a4d55f 0x7f0598d7f740 slapd stopped.

```

### Additional information

Are there integration tests for this container image? It would be nice if this did not regress again.

**Comment by jp-gouin** [comment]
Hi, 
My issue is that if the `ldif` of the user is wrong, it prevents the `openldap` from being initialised completely. 
Without the `tls` configuration the `openldap` is unusable. 

Here is what I state in the PR 
## Benefits
Using this [helm chart](https://github.com/jp-gouin/helm-openldap), this change fixes a replication issue.
This chart allows users to spin up Openldap in K8S in a high availability mode. In a multi-node scenario, the first one starts without issue, other ones are in a race condition when setting up the tree (ldap_create_tree) and ldif ldap_add_custom_ldifs) due to the replication. This is an expected behaviour and once the replication kicks in all nodes are running.

By doing the TLS initialisation at the end of ldap_initialize() the TLS is not properly configured when Openldap restart.

**Comment by zerowebcorp** [comment]
bitnami/openldap:2.6.6 breaks default tree and replication.
bitnami/openldap:2.6.5 works fine. 

@jp-gouin  Curious have you tested the helm chart with 2.6.6 from a fresh installation? 

I was testing 2.6.6 in a docker environment with docker-compose. I extracted the replication configuration from your ConfigMap https://github.com/jp-gouin/helm-openldap/blob/master/templates/configmap-replication-acls.yaml 

docker-compose 

```
version: "3.8"
services:
  openldap:
    image: bitnami/openldap:2.6.6
    container_name: openldap
    hostname: %hostname%
    deploy:
      restart_policy:
        condition: any
    volumes:
      - /home/devops/openldap/certs:/opt/bitnami/openldap/certs
      - /home/devops/openldap/data:/bitnami/openldap
      - /home/devops/openldap/ldifs/syncprov.ldif:/opt/bitnami/openldap/etc/schema/syncprov.ldif
      - /home/devops/openldap/ldifs/serverid.ldif:/opt/bitnami/openldap/etc/schema/serverid.ldif
      - /home/devops/openldap/ldifs/csyncprov.ldif:/opt/bitnami/openldap/etc/schema/csyncprov.ldif
      - /home/devops/openldap/ldifs/rep.ldif:/opt/bitnami/openldap/etc/schema/rep.ldif
      - /home/devops/openldap/ldifs/bsyncprov.ldif:/opt/bitnami/openldap/etc/schema/bsyncprov.ldif
      - /home/devops/openldap/ldifs/brep.ldif:/opt/bitnami/openldap/etc/schema/brep.ldif
      - /home/devops/openldap/ldifs/acls.ldif:/opt/bitnami/openldap/etc/schema/acls.ldif
    environment:
      - LDAP_ADMIN_PASSWORD=pass
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_PASSWORD=pass
      - BITNAMI_DEBUG=true
      - LDAP_REQUIRE_TLS=no
      - LDAPTLS_REQCERT=never
      - TLS_REQCERT=never
      - LDAP_TLS_REQCERT=never
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=admin
      - LDAP_ENABLE_TLS=yes
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,syncprov,serverid,csyncprov,rep,bsyncprov,brep,acls
      - LDAP_LOGLEVEL=256
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_SKIP_DEFAULT_TREE=no
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/ca.crt
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/tls.crt
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/tls.key
    ports:
      - "1389:1389"
      - "1636:1636"
```

Issues
1. It isn't creating the default tree
2. replication isn't working.

![image](https://github.com/bitnami/containers/assets/914305/eee9c8fd-040b-41dc-b342-2789b84a5824)

The same docker compose and ldif works with 2.6.5.
