### ISSUE TITLE
[bitnami/openldap] Default tree is not being created when passing LDAP_EXTRA_SCHEMAS

### ISSUE THREAD

**Issue by zerowebcorp** [bitnami/containers#54839]
### Name and Version

bitnami/openldap:2.6.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the image with the following environment variables and additional ldif for replication, 

``` 
version: "3.8"
services:
  openldap:
    image: bitnami/openldap:2.6.6
    container_name: openldap
    hostname: openldap1
    deploy:
      restart_policy:
        condition: any
    volumes:
      - /home/devops/openldap/certs:/opt/bitnami/openldap/certs
      - /home/devops/openldap/data:/bitnami/openldap
      - /home/devops/openldap/ldifs/syncprov.ldif:/opt/bitnami/openldap/etc/schema/syncprov.ldif
      - /home/devops/openldap/ldifs/serverid.ldif:/opt/bitnami/openldap/etc/schema/serverid.ldif
      - /home/devops/openldap/ldifs/csyncprov.ldif:/opt/bitnami/openldap/etc/schema/csyncprov.ldif
      - /home/devops/openldap/ldifs/rep.ldif:/opt/bitnami/openldap/etc/schema/rep.ldif
      - /home/devops/openldap/ldifs/bsyncprov.ldif:/opt/bitnami/openldap/etc/schema/bsyncprov.ldif
      - /home/devops/openldap/ldifs/brep.ldif:/opt/bitnami/openldap/etc/schema/brep.ldif
      - /home/devops/openldap/ldifs/acls.ldif:/opt/bitnami/openldap/etc/schema/acls.ldif
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ENABLE_SYNCPROV=no
      - LDAP_LDAPS_PORT_NUMBER=636
      - BITNAMI_DEBUG=true
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=admin
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/tls.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/tls.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/ca.crt
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,syncprov,serverid,csyncprov,rep,bsyncprov,brep,acls
      - LDAP_LOGLEVEL=256
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_SKIP_DEFAULT_TREE=no
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD={pass}
      - LDAP_CONFIG_ADMIN_PASSWORD={pass}
      - LDAPTLS_REQCER=never
      - LDAP_TLS_ENFORCE=false
    ports:
      - "389:389"
```

When running the container, with LDAP_EXTRA_SCHEMAS added, default tree is not being created. 

### What is the expected behavior?

Default tree should be created because we are passing LDAP_SKIP_DEFAULT_TREE=no

### What do you see instead?

It is skipping default tree.
