### ISSUE TITLE
[bitnami/redmine] docker exits without detailed logs

### ISSUE THREAD

**Issue by nightmeteora** [bitnami/containers#54830]
### Name and Version

bitnami/redmine:5.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I backup the persistence folder ,remove redmine and mariadb containers and build a brand new clean redmine service by `docker-compose up -d` command, stop the service and restore the persistence folder. after run `docker-compose up -d` , the redmine docker exits very soon. but `docker-compose logs redmine`  did not give any useful logs , no errors, no reasons.

### What do you see instead?

here is output of `docker ps -a`

```logs
ONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS                     PORTS      NAMES
5026c8dbdda8   bitnami/redmine:5.1.1   "/opt/bitnami/script…"   8 minutes ago   Exited (1) 3 seconds ago              redmine_redmine_1
f90403a518b4   bitnami/mariadb:11.1    "/opt/bitnami/script…"   8 minutes ago   Up 9 seconds               3306/tcp   redmine_mariadb_1
```
here is the output of `docker-compose logs redmine`

```logs
redmine_1  | redmine 08:32:02.48 INFO  ==> Welcome to the Bitnami redmine container
redmine_1  | redmine 08:32:02.48 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine_1  | redmine 08:32:02.48 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine_1  | redmine 08:32:02.49 INFO  ==>
redmine_1  | redmine 08:32:02.50 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine_1  | redmine 08:32:02.51 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 08:32:02.57 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 08:32:02.61 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 08:32:07.68 INFO  ==> Executing database migrations
```

### Additional information

the method to backup/restop persistence  may not be proper way, the question is no logs show detailed error/info why redmine service exit after `docker-compose up -d`

**Comment by javsalgar** [comment]
Hi,

Could you add the `BITNAMI_DEBUG=true` environment variable? This should provide more information on the issue

**Comment by nightmeteora** [comment]
thank @javsalgar for kind reply. however, the issue persists.  could you please let me know if I did anything wrong or if I need to do some more steps?


snippets of docker-compose.yml
```yml
  redmine:
    image: docker.io/bitnami/redmine:5.1.1
    ports:
      - '80:3000'
    volumes:
      # - 'redmine_data:/bitnami/redmine'
      - '/home/xxxxxxx/redmine/redmine_persistence:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=xxxxx
      - REDMINE_DATABASE_NAME=xxxxxx
      - REDMINE_DATABASE_PASSWORD=xxxxxxx
      - BITNAMI_DEBUG=true
  ```

output of `docker-compose logs redmine` after `docker-compose restart` was invoked.
```logs
redmine_1  | redmine 05:45:01.18 INFO  ==>
redmine_1  | redmine 05:45:01.18 INFO  ==> Welcome to the Bitnami redmine container
redmine_1  | redmine 05:45:01.18 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine_1  | redmine 05:45:01.18 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine_1  | redmine 05:45:01.18 INFO  ==>
redmine_1  | redmine 05:45:01.19 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine_1  | redmine 05:45:01.19 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 05:45:01.22 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 05:45:01.24 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 05:45:07.32 INFO  ==> Executing database migrations
```
