### ISSUE TITLE
[bitnami/openldap] Unable to deploy OpenLDAP

### ISSUE THREAD

**Issue by mailliwal** [bitnami/containers#54878]
### Name and Version

```
bitnami/openldap:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

version: "2"
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - /var/lib/docker/volumes/openldap2:/bitnami/openldap
    networks:
      ldap_net:
        ipv4_address: 172.18.0.10
networks:
  ldap_net:
    external: true
    name: ldap_network
```

### What do you see instead?
```
openldap2-openldap-1  |  14:40:00.79 INFO  ==> ** Starting LDAP setup **
openldap2-openldap-1  |  14:40:00.91 INFO  ==> Validating settings in LDAP_* env vars
openldap2-openldap-1  |  14:40:00.97 INFO  ==> Initializing OpenLDAP...
openldap2-openldap-1  | mkdir: cannot create directory '/bitnami/openldap/data': Permission denied
openldap2-openldap-1 exited with code 1
```
### Additional information

May I know how to solve permission denied ?

Thanks
