### ISSUE TITLE
Load Redis module like RedisSearch

### ISSUE THREAD

**Issue by nemo83** [bitnami/containers#5504]
### Name and Version

bitnami/redis:latest

### What is the problem this feature will solve?

It will allow the bitnami Kubernetes Helm Redis chart to offer FT.SEARCH capabilities, in particular HNSW indexes query

### What is the feature you are proposing to solve the problem?

Add modules in the image as well as cusomising entrypoint/cmd scripts to load such modules

### What alternatives have you considered?

I was thinking to use redis-stack but there are no helm charts for that.

**Comment by carrodher** [comment]
Thanks for the suggestion, I just created an internal task to evaluate this feature. Due to the team capacity and other priorities we are working on, I can't provide an ETA for this evaluation. Because of that, I'm moving this issue to `On hold` and we'll update it once we have more news.

As usual, the Bitnami team will be happy to review any contribution via PRs and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by hussam-qasem** [comment]
Until an official response is provided, you can use a custom image. Example `Dockerfile`:

```Dockerfile
FROM docker.io/redislabs/redisearch:latest as builder

FROM docker.io/bitnami/redis:6.2.10
COPY --from=builder /usr/lib/redis/modules/redisearch.so /usr/lib/redis/modules/redisearch.so

CMD ["/run.sh", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
```

**Comment by hussam-qasem** [comment]
If you're using [Bitnami Helm chart for Redis](https://github.com/bitnami/charts/tree/main/bitnami/redis/) to deploy on Kubernetes, you can bypass creating custom images, by utilizing an [Init Container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to copy the [RediSearch module](https://github.com/RediSearch/RediSearch/releases) from the [RedisSearch Docker image](https://hub.docker.com/r/redislabs/redisearch/). For example:

```yaml
master:
  initContainers:
   - name: copy-redisearch-module
     image: docker.io/redislabs/redisearch:latest
     command: ['sh', '-c', 'cp /usr/lib/redis/modules/redisearch.so /modules && cp /usr/lib/redis/modules/rejson.so /modules']
     securityContext:
       runAsUser: 0
     volumeMounts:
       - name: redis-modules
         mountPath: /modules
  extraVolumes:
    - name: redis-modules
      emptyDir: {}
  extraVolumeMounts:
    - name: redis-modules
      mountPath: /usr/lib/redis/modules
  extraFlags: ["--loadmodule", "/usr/lib/redis/modules/redisearch.so", "--loadmodule", "/usr/lib/redis/modules/rejson.so"]
  # configuration: |-
  #   loadmodule /usr/lib/redis/modules/redisearch.so
  #   loadmodule /usr/lib/redis/modules/rejson.so

```
