### ISSUE TITLE
[bitnami/openldap] "Samba: Domain" greyed-out

### ISSUE THREAD

**Issue by mailliwal** [bitnami/containers#55171]
### Name and Version

bitname/openldap:2.6

### What architecture are you using?

None

### What steps will reproduce the bug?

```yaml
version: "2"
services:
  openldap:
    image: bitnami/openldap:2.6
    container_name: openldap
    hostname: openldap
    ports:
      - 389:1389
      - 636:1636
    volumes:
      - /var/lib/docker/volumes/openldap:/bitnami/openldap
      - /var/lib/docker/volumes/openldap/certs:/opt/bitnami/openldap/certs
    restart: always
    environment:
      - LDAP_ROOT='dc=home,dc=lab'
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/wildcard.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/wildcard.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/ca.crt
      - LDAP_TLS_DH_PARAMS_FILE=/opt/bitnami/openldap/certs/dhparam.pem
    env_file: .env
    networks:
      ldap_net:
        ipv4_address: 172.18.0.10
networks:
  ldap_net:
    external: true
    name: ldap_network
```

### What do you see instead?

Hi,

Unavailable to add "Samba:Domain", it's greyed-out.

**"ObjectClasses in XML dont exist in LDAP server"**

May I know how to solve it ?

Thanks
