### ISSUE TITLE
[bitnami/minio] Launch script as soon as minio is up

### ISSUE THREAD

**Issue by Zer0NimO-web** [bitnami/containers#55358]
### Name and Version

bitnami:minio

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Dockerfile : 
 ```yaml
FROM bitnami/minio
COPY build/dockerfiles/minio/init-data.sh /docker-entrypoint/init-data.sh
RUN chmod +x /docker-entrypoint/init-data.sh
```
 
 docker-compose.yml
 ```yaml
 s3:
    restart: always
    build:
      context: ../..
      dockerfile: ./build/dockerfiles/minio/Dockerfile
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: d-local
    networks:
      - d-network
    volumes:
      - ../../s3:/bitnami/minio/data/
    command: ["./docker-entrypoint/init-data.sh"]
 ```

### What is the expected behavior?

I expect the script to be launched when minio is up and running.

### What do you see instead?

The container is still running but i cannot reach http://localhost:9001 anymore.
My local minio server seems down.

### Additional information

As soon as i retire the command property from the service in docker-compose.yml it works perfectly fine.
Same behaviour with the entrypoint property.
I can't figure out a way to play a custom script when the container start.
