### ISSUE TITLE
Bitnami matomo DBip database download failure

### ISSUE THREAD

**Issue by jainhitesh9998** [bitnami/containers#56444]
### Name and Version

bitnami/matomo 4.16.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Environment: EKS with efs attached, below is the efs config

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: matomo-efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  provisioningMode: efs-ap
  fileSystemId: 
  directoryPerms: "777"
  basePath: "/matomo_dynamic_provisioned" # optional
  subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  ensureUniqueDirectory: "true" # optional
  uid: "1001"
  gid: "0"
```
2. Reproduction Steps: 

-  Install matomo using helm charts with using this efs as volume provider, ( we installed 2 replicas of matomo sharing the same volume
- Setup GeoIP db and use the download option present (https://matomo.org/faq/how-to/setting-up-accurate-visitors-geolocation/) 
-  the .gz file gets downloaded by it times out while gunzip operation and then i have to manually delete the entry to get the option again. 

workaround:
- this operation never succeeded, manually adding mmdb file in the misc folder for geolocation works.

Other scenarios tested:
A single replica setup with ebs backed storage works properly for this scenario.

### What is the expected behavior?

No

### What do you see instead?

The operation timed out after 30s, there were forum discussions to edit the timeout config to 0 so it can run longer, but be didn't see any issues while using ebs so didn't perform this change on the production cluster.
