### ISSUE TITLE
[bitnami/kafka] Healthcheck uses KAFKA_HEAP_OPTS

### ISSUE THREAD

**Issue by serut** [bitnami/containers#56544]
### Name and Version

bitnami/kafka:3.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I've OOM on the healthcheck of Kafka container : 
```json
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": true,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2024-02-07T02:44:26.433758449Z",
            "FinishedAt": "2024-02-07T09:59:47.062914954Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 1,
                "Log": [
                    {
                        "Start": "2024-02-07T10:58:50.627061665+01:00",
                        "End": "2024-02-07T10:58:54.024116601+01:00",
                        "ExitCode": 0,
                        "Output": "Cluster ID: abcdefghijklmnopqrstug\n"
                    },
                    {
                        "Start": "2024-02-07T10:59:04.025932968+01:00",
                        "End": "2024-02-07T10:59:07.226737588+01:00",
                        "ExitCode": 0,
                        "Output": "Cluster ID: abcdefghijklmnopqrstug\n"
                    },
                    {
                        "Start": "2024-02-07T10:59:17.228531406+01:00",
                        "End": "2024-02-07T10:59:20.608769941+01:00",
                        "ExitCode": 0,
                        "Output": "Cluster ID: abcdefghijklmnopqrstug\n"
                    },
                    {
                        "Start": "2024-02-07T10:59:30.610299159+01:00",
                        "End": "2024-02-07T10:59:33.928822102+01:00",
                        "ExitCode": 0,
                        "Output": "Cluster ID: abcdefghijklmnopqrstug\n"
                    },
                    {
                        "Start": "2024-02-07T10:59:43.929545212+01:00",
                        "End": "2024-02-07T10:59:46.699016865+01:00",
                        "ExitCode": 137,
                        "Output": ""
                    }
                ]
            }

```

So I tried to increase the heap space memory. But I see the healcheck uses the same amount of heap space, which is not expected

1. deploy kafka as this (healthcheck + env KAFKA_HEAP_OPTS defined)
```
  rs-kafka:
    image: bitnami/kafka:3.6.0
    user: "3050:1050"
    hostname: rs-kafka-{{.Task.Slot}}
    read_only: true
    networks:
      - test
    healthcheck:
      test: ["CMD", "kafka-cluster.sh", "cluster-id", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 15s
    volumes:
      - type: tmpfs
        target: /opt/bitnami/kafka/config/
      - type: tmpfs
        target: /bitnami/kafka
      - type: tmpfs
        target: /tmp
    environment:
      - "ALLOW_PLAINTEXT_LISTENER=True"
      - "ALLOW_ANONYMOUS_LOGIN=True"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
      - "KAFKA_CFG_CONTROLLER_QUORUM_VOTERS={{.Task.Slot}}@rs-kafka-{{.Task.Slot}}:9093"
      - "KAFKA_CFG_NODE_ID={{.Task.Slot}}"
      - "KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv"
      - "KAFKA_CFG_PROCESS_ROLES=controller,broker"
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      - "KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER"
      - "KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=True"
      - "KAFKA_HEAP_OPTS=-Xmx1050m -Xms1050m"
    deploy:
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 0
        window: 0s
      replicas: 1
      resources:
        limits:
            cpus: '1'
            memory: 3g
            pids: 100000
        reservations:
            cpus: '0.5'
            memory: 512M
```

2. Check the healthcheck command executed
```
I have no name!@rs-kafka-1:/$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
[ this is the server]
3050         1  6.3  1.9 8000048 402192 ?      Ssl  14:40   0:35 /opt/bitnami/java/bin/java -Xmx1050m -Xms1050m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Dcom.sun.management.jmxremot
3050     16867  0.6  0.0   4140  2068 pts/0    Ss   14:50   0:00 bash
[ this is the healthcheck]
3050     16883  126  0.3 3972436 64724 ?       Ssl  14:50   0:01 /opt/bitnami/java/bin/java -Xmx1050m -Xms1050m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Dcom.sun.management.jmxremot
3050     17266  0.0  0.0   6740  1528 pts/0    R+   14:50   0:00 ps aux
```
3. The healcheck uses `-Xmx1050m -Xms1050m` but this property should only be used by the server

### What is the expected behavior?

The file /opt/bitnami/kafka/bin//kafka-run-class.sh should not use the same `VENV KAFKA_HEAP_OPTS` as the service uses.
