### ISSUE TITLE
[bitnami/kibana] Kibana Image missing `KIBANA_PASSWORD` Environment Variable

### ISSUE THREAD

**Issue by ArkShocer** [bitnami/containers#58181]
### Name and Version

bitnami:kibana:10.9.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Setup ArgoCD
2. Setup HashiCorp Vault
3. Configure an ArgoCD AppSet
4. Create a Vault Secret
5. Configure a Vault ACL Policy with a role binded to it + the correct secret
6. Configure the Vault Role to for the kibana service account and the correct namespaces
7. Set the following configs in the values file

 ```yaml
fullnameOverride: kibana

automountServiceAccountToken: true
serviceAccount:
    automountServiceAccountToken: true

podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "Your_Vault_Role"
    vault.hashicorp.com/agent-inject-default-template: "json"
    vault.hashicorp.com/agent-inject-secret-kibana: "kv/example/kibana"
    vault.hashicorp.com/agent-inject-template-env.sh: |
        {{`{{- with secret "kv/example/kibana" -}}
        export KIBANA_PASSWORD="{{ .Data.data.password }}"
        {{- end -}}`}}

command:
    [
        "/bin/sh",
        "-c",
        "source /vault/secrets/env.sh && /opt/bitnami/scripts/kibana/entrypoint.sh ",
    ]

persistence:
    enabled: true
    storageClass: "managed-csi"

extraConfiguration:
    "xpack.security.authc.providers":
        basic.basic1:
            order: 0
        anonymous.anonymous1:
            order: 1
            credentials:
                username: "test"
                password: "admin@123"

ingress:
    enabled: true
    pathType: ImplementationSpecific
    hostname: kibana-testing.test.example.com
    path: /
    ingressClassName: "nginx"
elasticsearch:
    hosts:
        - elasticsearch.testing.svc.cluster.local
    ## @param elasticsearch.port Elasticsearch port
    ##
    port: "9200"
    security:
        auth:
            enabled: true
            createSystemUser: true
            elasticsearchPasswordSecret: "elasticsearch"
        tls:
            enabled: true
            verificationMode: "none"
```

### What is the expected behavior?

I want to set [kibanaPassword](https://github.com/bitnami/charts/blob/f9351469b1191ecbdeeef58d878b5621a840f864/bitnami/kibana/values.yaml#L790) via hashicorp vault side car injection on Environment Variables but I'm unable to do so with the current container image. I can see that the env exists in the [kibana-env.sh](https://github.com/bitnami/containers/blob/6d8c5a2ab011eecf5aef570c3b3218ce8cb5ef22/bitnami/kibana/8/debian-11/rootfs/opt/bitnami/scripts/kibana-env.sh#L43) but when used in pod annotations it doesn't work. I don't want to set the kibana password with a string in the values file nor as a local k8s secret. I'm using kibana with elasticsearch from bitnami and in there all env variables worked perfectly with vault side car injection.

### What do you see instead?

I get the error message below from the argocd ui which requires me to set a kibana password.

```yaml
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = `helm template . --name-template test-infra-kibana --namespace pre-testing --kube-version 1.26 --values <path to cached source>/testing/infra/kibana/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (kibana/templates/secret.yaml:19:22): A Kibana password is required! Use --debug flag to render out invalid YAML
```

 tld: `A Kibana password is required!`
