### ISSUE TITLE
The WARN log seems incorrect

### ISSUE THREAD

**Issue by jiak94** [bitnami/containers#6172]
### Name and Version

bitnami/kafka:3.2.0

### What steps will reproduce the bug?

1. docker-compose look like this:

```yaml
kafka:
    network_mode: host
    image: bitnami/kafka:3.2.0
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=V5t6x-LERXi-eUBdy_vacg
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M

```

2. execute `docker compose up kafka`

### What is the expected behavior?

No Warning Log

### What do you see instead?

I receive these logs from the console

```
docker-kafka-1  | kafka 04:34:27.11 WARN  ==> KAFKA_CFG_BROKER_ID Must match what is set in KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
docker-kafka-1  | kafka 04:34:27.11 WARN  ==> KAFKA_CFG_CONTROLLER_QUORUM_VOTERS must match brokers set with KAFKA_CFG_BROKER_ID
docker-kafka-1  | kafka 04:34:27.11 WARN  ==> KAFKA_CFG_PROCESS_ROLES must include 'controller' for KRaft
docker-kafka-1  | kafka 04:34:27.11 WARN  ==> KAFKA_CFG_LISTENERS must include a listener for CONTROLLER
docker-kafka-1  | kafka 04:34:27.11 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
```
I understand that the last warning is correct, but others warnings are not correct
