### ISSUE TITLE
OpenLDAP image on Kubernetes 1.28, crashes when bootstrapping olcPasswordHash

### ISSUE THREAD

**Issue by sbordeyne** [bitnami/containers#62796]
### Name and Version

bitnami/openldap:2.6.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Host is running debian 12
2. Kubernetes 1.28 running with kubeadm
3. Deploying OpenLDAP with kustomize, manifests are below. For brevity, I'm omitting cert-manager and nfs-provisionner setups. They work fine on their own
4. On startup, the pod creates the data, crashes, and then runs OpenLDAP without creating the database in full. Since there is data in the PVC, the next restart just assumes that everything went correctly, and thus starts slapd, but the LDAP db is empty
5. Running `source /opt/bitnami/openldap/libopenldap.sh  && eval $(ldap_env) && ldap_create_tree` works and forces the tree to be created.

Manifests:

```yaml
# manifests/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-ca
  namespace: openldap
spec:
  isCA: true
  commonName: ldap-ca
  secretName: root-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ldap-issuer
  namespace: openldap
spec:
  ca:
    secretName: root-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
  namespace: openldap
spec:
  dnsNames:
  - ldap.slfhst.io
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ldap-issuer
  secretName: openldap-tls
  usages:
  - digital signature
  - key encipherment
```

```yaml
# manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  openldap
    spec:
      containers:
      - name:  openldap
        image:  openldap
        securityContext:
          allowPrivilegeEscalation: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: BITNAMI_DEBUG
            value: "true"
        envFrom:
          - configMapRef:
              name:  config
          - secretRef:
              name: openldap-secrets
        ports:
        - containerPort:  1339
          name:  openldap
        - containerPort:  1636
          name:  openldaps
        volumeMounts:
        - name: tls
          mountPath: /container/service/slapd/assets/certs/tls.ca.crt
          subPath: ca.crt
          readOnly: true
        - name: tls
          mountPath: /container/service/slapd/assets/certs/tls.crt
          subPath: tls.crt
          readOnly: true
        - name: tls
          mountPath: /container/service/slapd/assets/certs/tls.key
          subPath: tls.key
          readOnly: true
        - name: data
          mountPath: /bitnami
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      volumes:
        - name: tls
          secret:
            secretName: openldap-tls
        - name: data
          persistentVolumeClaim:
            claimName: openldap-pvc
      restartPolicy: Always
```

```yaml
# manifests/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name:  openldap
```

```yaml
# manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  selector:
    app.kubernetes.io/name: openldap
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: openldap
    protocol: TCP
    port: 1389
    targetPort: 1389
  - name: openldaps
    protocol: TCP
    port: 1636
    targetPort: 1636
```

```yaml
# manifests/persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/namespace.yaml
- manifests/persistent-volume-claim.yaml
- manifests/certificate.yaml
- manifests/deployment.yaml
- manifests/service.yaml

commonLabels:
  app.kubernetes.io/name: openldap
  app.kubernetes.io/instance: openldap
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: openldap
  app.kubernetes.io/part-of: slfhst
  app.kubernetes.io/version: 2.6.7

namespace: openldap

configMapGenerator:
- name: config
  options:
    disableNameSuffixHash: true
  literals:
  # Base options
  - LDAP_PORT_NUMBER=1389
  - LDAP_ROOT=dc=slfhst,dc=io
  - LDAP_ADMIN_USERNAME=admin
  - LDAP_CONFIG_ADMIN_ENABLED=yes
  - LDAP_CONFIG_ADMIN_USERNAME=config
  - LDAP_LOGLEVEL=256
  - LDAP_PASSWORD_HASH=SSHA
  - LDAP_USERS=readonly
  - LDAP_USER_DC=users
  - LDAP_GROUP=readers
  # Access log options
  - LDAP_ENABLE_ACCESSLOG=yes
  - LDAP_ACCESSLOG_ADMIN_USERNAME=admin
  - LDAP_ACCESSLOG_DB=cn=accesslog
  - LDAP_ACCESSLOG_LOGSUCCESS=yes
  # TLS options
  - LDAP_ENABLE_TLS=yes
  - LDAP_REQUIRE_TLS=no
  - LDAP_LDAPS_PORT_NUMBER=1636
  - LDAP_TLS_CERT_FILE=/container/service/slapd/assets/certs/tls.crt
  - LDAP_TLS_KEY_FILE=/container/service/slapd/assets/certs/tls.key
  - LDAP_TLS_CA_FILE=/container/service/slapd/assets/certs/tls.ca.crt

secretGenerator:
- name: openldap-secrets
  env: .env

images:
- name: openldap
  newName: bitnami/openldap
  newTag: 2.6.7
```

the .env file (with different secrets)
```sh
LDAP_ADMIN_PASSWORD=adminpassword
LDAP_CONFIG_ADMIN_PASSWORD=configpassword
LDAP_ACCESSLOG_ADMIN_PASSWORD=accesslogpassword
LDAP_PASSWORDS=readonlypassword
```

### What is the expected behavior?

- Pod should not have to restart to run the service
- olcPasswordHash step should work properly
- Bootstrap step should probably hold a state of the steps it performed, in case an issue arises during the bootstrap phase.

### What do you see instead?

Here are the logs from the first startup of the pod. Note the error 

```
text=<olcPasswordHash> no valid hashes found
ldap_modify: Other (e.g., implementation specific) error (80)
        additional info: <olcPasswordHash> no valid hashes found
modifying entry "olcDatabase={-1}frontend,cn=config"
```

Instead of proceeding, the slapd service stops completely, and the step afterwards (initializing the ldap db) doesn't get run (or setting up the access logs)

On the next restart, since the bootstrap doesn't know better, the setup phase is skipped, using persisted data. This data though is an empty ldap db, an additional check would be appreciated to make sure that all steps of the bootstrap script were run. This is also an issue if, for instance, access logs want to be enabled at a later point. Besides going into the pod, sourcing the lib and running the command manually, the pod will not take the new configuration into account.

Full logs :

```
[nas@nas-master kubernetes (⎈|main:openldap)]$ k logs openldap-6b984769f5-vg7rv 
 20:28:45.23 INFO  ==> ** Starting LDAP setup **
 20:28:45.59 INFO  ==> Validating settings in LDAP_* env vars
 20:28:45.69 INFO  ==> Initializing OpenLDAP...
 20:28:45.69 DEBUG ==> Ensuring expected directories/files exist...
 20:28:45.91 INFO  ==> Creating LDAP online configuration
 20:28:45.99 INFO  ==> Creating slapd.ldif
 20:28:46.69 INFO  ==> Starting OpenLDAP server in background
65d50b7e.2f52eb7d 0x7fa444417740 @(#) $OpenLDAP: slapd 2.6.7 (Feb  7 2024 17:05:27) $
        @b7c3a617935e:/bitnami/blacksmith-sandox/openldap-2.6.7/servers/slapd
65d50b7f.0a4a21c7 0x7fa444417740 slapd starting
[nas@nas-master kubernetes (⎈|main:openldap)]$ k logs openldap-6b984769f5-vg7rv -f
 20:28:45.23 INFO  ==> ** Starting LDAP setup **
 20:28:45.59 INFO  ==> Validating settings in LDAP_* env vars
 20:28:45.69 INFO  ==> Initializing OpenLDAP...
 20:28:45.69 DEBUG ==> Ensuring expected directories/files exist...
 20:28:45.91 INFO  ==> Creating LDAP online configuration
 20:28:45.99 INFO  ==> Creating slapd.ldif
 20:28:46.69 INFO  ==> Starting OpenLDAP server in background
65d50b7e.2f52eb7d 0x7fa444417740 @(#) $OpenLDAP: slapd 2.6.7 (Feb  7 2024 17:05:27) $
        @b7c3a617935e:/bitnami/blacksmith-sandox/openldap-2.6.7/servers/slapd
65d50b7f.0a4a21c7 0x7fa444417740 slapd starting
 20:28:47.70 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
65d50b7f.2ab6c614 0x7fa40372e700 conn=1000 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
65d50b7f.2ab8923a 0x7fa40372e700 conn=1000 op=0 BIND dn="" method=163
65d50b7f.2ab9929a 0x7fa40372e700 conn=1000 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
65d50b7f.2ab9d109 0x7fa40372e700 conn=1000 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
65d50b7f.2aba3144 0x7fa40372e700 conn=1000 op=0 RESULT tag=97 err=0 qtime=0.000006 etime=0.000125 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
65d50b7f.2abc6673 0x7fa402f2d700 conn=1000 op=1 MOD dn="olcDatabase={2}mdb,cn=config"
65d50b7f.2abcdc24 0x7fa402f2d700 conn=1000 op=1 MOD attr=olcSuffix
65d50b7f.326c49c0 0x7fa402f2d700 conn=1000 op=1 RESULT tag=103 err=0 qtime=0.000012 etime=0.128998 text=
65d50b7f.326f0e0b 0x7fa40372e700 conn=1000 op=2 MOD dn="olcDatabase={2}mdb,cn=config"
65d50b7f.3270bd58 0x7fa40372e700 conn=1000 op=2 MOD attr=olcRootDN
65d50b7f.365bf988 0x7fa40372e700 conn=1000 op=2 RESULT tag=103 err=0 qtime=0.000030 etime=0.065903 text=
65d50b7f.365f1357 0x7fa402f2d700 conn=1000 op=3 MOD dn="olcDatabase={2}mdb,cn=config"
65d50b7f.365fab2f 0x7fa402f2d700 conn=1000 op=3 MOD attr=olcRootPW
65d50b7f.3af4fe3b 0x7fa402f2d700 conn=1000 op=3 RESULT tag=103 err=0 qtime=0.000014 etime=0.076963 text=
65d50b7f.3af80bac 0x7fa40372e700 conn=1000 op=4 MOD dn="olcDatabase={1}monitor,cn=config"
65d50b7f.3af8e597 0x7fa40372e700 conn=1000 op=4 MOD attr=olcAccess
65d50b80.03433988 0x7fa40372e700 conn=1000 op=4 RESULT tag=103 err=0 qtime=0.000059 etime=0.065476 text=
65d50b80.034a5c05 0x7fa402f2d700 conn=1000 op=5 MOD dn="olcDatabase={0}config,cn=config"
65d50b80.034bf7ec 0x7fa402f2d700 conn=1000 op=5 MOD attr=olcRootDN
65d50b80.0c481183 0x7fa402f2d700 conn=1000 op=5 RESULT tag=103 err=0 qtime=0.000037 etime=0.150918 text=
65d50b80.0c4f25eb 0x7fa40372e700 conn=1000 op=6 MOD dn="olcDatabase={0}config,cn=config"
65d50b80.0c50bf9f 0x7fa40372e700 conn=1000 op=6 MOD attr=olcRootPW
65d50b80.145d76ea 0x7fa40372e700 conn=1000 op=6 RESULT tag=103 err=0 qtime=0.000034 etime=0.135234 text=
65d50b80.14658735 0x7fa402f2d700 conn=1000 op=7 UNBIND
65d50b80.1466b7ff 0x7fa402f2d700 conn=1000 fd=12 closed
 20:28:48.34 INFO  ==> Adding LDAP extra schemas
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

modifying entry "olcDatabase={0}config,cn=config"

modifying entry "olcDatabase={0}config,cn=config"

65d50b80.176c549f 0x7fa40372e700 conn=1001 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
SASL/EXTERNAL authentication started
65d50b80.177a8caa 0x7fa402f2d700 conn=1001 op=0 BIND dn="" method=163
65d50b80.177e885f 0x7fa402f2d700 conn=1001 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
65d50b80.17816539 0x7fa402f2d700 conn=1001 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
65d50b80.17846c65 0x7fa402f2d700 conn=1001 op=0 RESULT tag=97 err=0 qtime=0.000030 etime=0.000685 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
65d50b80.1799e3b3 0x7fa40372e700 conn=1001 op=1 ADD dn="cn=cosine,cn=schema,cn=config"
65d50b80.21a74d48 0x7fa40372e700 conn=1001 op=1 RESULT tag=105 err=0 qtime=0.000029 etime=0.168808 text=
65d50b80.21a8feea 0x7fa402f2d700 conn=1001 op=2 UNBIND
65d50b80.21aa6ce3 0x7fa402f2d700 conn=1001 fd=12 closed
adding new entry "cn=cosine,cn=schema,cn=config"

SASL/EXTERNAL authentication started
65d50b80.2209441f 0x7fa40372e700 conn=1002 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
65d50b80.220a6c1f 0x7fa402f2d700 conn=1002 op=0 BIND dn="" method=163
65d50b80.220b9d0d 0x7fa402f2d700 conn=1002 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
65d50b80.220c5db9 0x7fa402f2d700 conn=1002 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
65d50b80.220da449 0x7fa402f2d700 conn=1002 op=0 RESULT tag=97 err=0 qtime=0.000012 etime=0.000227 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
65d50b80.22141a0c 0x7fa40372e700 conn=1002 op=1 ADD dn="cn=inetorgperson,cn=schema,cn=config"
65d50b80.2645d358 0x7fa40372e700 conn=1002 op=1 RESULT tag=105 err=0 qtime=0.000014 etime=0.070401 text=
65d50b80.26483024 0x7fa402f2d700 conn=1002 op=2 UNBIND
65d50b80.26496fdd 0x7fa402f2d700 conn=1002 fd=12 closed
adding new entry "cn=inetorgperson,cn=schema,cn=config"

SASL/EXTERNAL authentication started
65d50b80.26b7adbe 0x7fa40372e700 conn=1003 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
65d50b80.26baaf7c 0x7fa402f2d700 conn=1003 op=0 BIND dn="" method=163
65d50b80.26bbbabf 0x7fa402f2d700 conn=1003 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
65d50b80.26bc432d 0x7fa402f2d700 conn=1003 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
65d50b80.26bce7d2 0x7fa402f2d700 conn=1003 op=0 RESULT tag=97 err=0 qtime=0.000018 etime=0.000168 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
65d50b80.26c51faf 0x7fa40372e700 conn=1003 op=1 ADD dn="cn=nis,cn=schema,cn=config"
65d50b80.2f39f18b 0x7fa40372e700 conn=1003 op=1 RESULT tag=105 err=0 qtime=0.000016 etime=0.141913 text=
65d50b80.2f4062de 0x7fa402f2d700 conn=1003 op=2 UNBIND
65d50b80.2f452b19 0x7fa40372e700 conn=1003 fd=12 closed
adding new entry "cn=nis,cn=schema,cn=config"

 20:28:48.80 INFO  ==> Configuring LDAP olcPasswordHash
SASL/EXTERNAL authentication started
65d50b80.3b82f4b0 0x7fa402f2d700 conn=1004 fd=12 ACCEPT from PATH=/opt/bitnami/openldap/var/run/ldapi (PATH=/opt/bitnami/openldap/var/run/ldapi)
65d50b80.3b85959c 0x7fa40372e700 conn=1004 op=0 BIND dn="" method=163
65d50b80.3b87b9bb 0x7fa40372e700 conn=1004 op=0 BIND authcid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth"
65d50b80.3b88ea89 0x7fa40372e700 conn=1004 op=0 BIND dn="gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth" mech=EXTERNAL bind_ssf=0 ssf=71
65d50b80.3b910cf2 0x7fa40372e700 conn=1004 op=0 RESULT tag=97 err=0 qtime=0.000027 etime=0.000783 text=
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
65d50b80.3b95109a 0x7fa402f2d700 conn=1004 op=1 MOD dn="olcDatabase={-1}frontend,cn=config"
65d50b80.3b966bfa 0x7fa402f2d700 conn=1004 op=1 MOD attr=olcPasswordHash
65d50b81.00011c38 0x7fa402f2d700 olcPasswordHash: value #0: <olcPasswordHash> scheme not available (SSHA)
65d50b81.0002111a 0x7fa402f2d700 olcPasswordHash: value #0: <olcPasswordHash> no valid hashes found
65d50b81.0559d11c 0x7fa402f2d700 conn=1004 op=1 RESULT tag=103 err=80 qtime=0.000016 etime=0.090184 text=<olcPasswordHash> no valid hashes found
ldap_modify: Other (e.g., implementation specific) error (80)
        additional info: <olcPasswordHash> no valid hashes found
modifying entry "olcDatabase={-1}frontend,cn=config"

65d50b81.055b9def 0x7fa40372e700 conn=1004 op=2 UNBIND
65d50b81.055c518e 0x7fa40372e700 conn=1004 fd=12 closed
65d50b81.05acc3a7 0x7fa403f2f700 daemon: shutdown requested and initiated.
65d50b81.05afd7d8 0x7fa403f2f700 slapd shutdown: waiting for 0 operations/tasks to finish
65d50b81.05d33dad 0x7fa444417740 slapd stopped.
```
