### ISSUE TITLE
SSL Handshake Failed Error Encountered

### ISSUE THREAD

**Issue by zeeshan018** [bitnami/containers#63223]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?
```yaml
version: '2'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka.example.com
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://kafka.example.com:9092
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=controller_user
      - KAFKA_INTER_BROKER_PASSWORD=controller_password
      - KAFKA_CERTIFICATE_PASSWORD=1q2w3e4r
      - KAFKA_TLS_TYPE=JKS # or PEM
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=""
    volumes:
      # Both .jks and .pem files are supported
      # - './kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
      # - './kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
      # - './kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
      - './keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
```
### What is the expected behavior?
```
[2024-02-21 20:48:26,804] INFO Kafka version: 3.6.0 (org.apache.kafka.common.utils.AppInfoParser)
kafka2-kafka-1  | [2024-02-21 20:48:26,804] INFO Kafka commitId: 60e845626d8a465a (org.apache.kafka.common.utils.AppInfoParser)
kafka2-kafka-1  | [2024-02-21 20:48:26,804] INFO Kafka startTimeMs: 1708548506802 (org.apache.kafka.common.utils.AppInfoParser)
kafka2-kafka-1  | [2024-02-21 20:48:26,806] INFO [KafkaRaftServer nodeId=0] Kafka Server started (kafka.server.KafkaRaftServer)
kafka2-kafka-1  | [2024-02-21 20:55:00,839] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:39186-0) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
kafka2-kafka-1  | [2024-02-21 20:55:01,296] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:39198-0) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
kafka2-kafka-1  | [2024-02-21 20:55:01,465] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:39200-0) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
kafka2-kafka-1  | [2024-02-21 20:55:01,735] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:39214-1) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
kafka2-kafka-1  | [2024-02-21 20:55:02,328] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:39216-1) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
kafka2-kafka-1  | [2024-02-21 20:55:03,304] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:47144-1) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
kafka2-kafka-1  | [2024-02-21 20:55:04,436] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9092-127.0.0.1:47158-2) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

### What do you see instead?
```
"Kafka Console Producer Fails to Connect Despite Kafka Running: Disconnection from Bootstrap Broker 127.0.0.1:9092"

Error:
[2024-02-21 20:55:01,190] WARN [Producer clientId=console-producer] Bootstrap broker 127.0.0.1:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```
