### ISSUE TITLE
[bitnami/mongo] Pod keeps restarting in OpenShift  

### ISSUE THREAD

**Issue by grvuolo** [bitnami/containers#63463]
### Name and Version

bitnami/mongo:5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In OpenShift on IBM Cloud (ROKS) 4.13.28
2. running:
helm install velocity-mongo bitnami/mongodb --set containerSecurityContext.runAsUser=1000980000,podSecurityContext.fsGroup=1000980000,auth.rootPassword=password --set image.tag=5.0 --set global.storageClass=ibmc-file-gold-gid

3. deployment yaml:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: velocity-mongo
    meta.helm.sh/release-namespace: ibm-ucv
  name: velocity-mongo-mongodb
  namespace: ibm-ucv
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: velocity-mongo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/version: 7.0.5
    helm.sh/chart: mongodb-14.11.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: velocity-mongo
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: velocity-mongo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/version: 7.0.5
        helm.sh/chart: mongodb-14.11.1
    spec:
      restartPolicy: Always
      serviceAccountName: velocity-mongo-mongodb
      schedulerName: default-scheduler
      enableServiceLinks: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: mongodb
                    app.kubernetes.io/instance: velocity-mongo
                    app.kubernetes.io/name: mongodb
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000980000
        fsGroupChangePolicy: Always
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - /bitnami/scripts/readiness-probe.sh
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          name: mongodb
          livenessProbe:
            exec:
              command:
                - /bitnami/scripts/ping-mongodb.sh
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: MONGODB_ROOT_USER
              value: root
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velocity-mongo-mongodb
                  key: mongodb-root-password
            - name: ALLOW_EMPTY_PASSWORD
              value: 'no'
            - name: MONGODB_SYSTEM_LOG_VERBOSITY
              value: '0'
            - name: MONGODB_DISABLE_SYSTEM_LOG
              value: 'no'
            - name: MONGODB_DISABLE_JAVASCRIPT
              value: 'no'
            - name: MONGODB_ENABLE_JOURNAL
              value: 'yes'
            - name: MONGODB_PORT_NUMBER
              value: '27017'
            - name: MONGODB_ENABLE_IPV6
              value: 'no'
            - name: MONGODB_ENABLE_DIRECTORY_PER_DB
              value: 'no'
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsUser: 1000980000
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
            - name: common-scripts
              mountPath: /bitnami/scripts
          terminationMessagePolicy: File
          image: 'docker.io/bitnami/mongodb:5.0'
      automountServiceAccountToken: false
      serviceAccount: velocity-mongo-mongodb
      volumes:
        - name: common-scripts
          configMap:
            name: velocity-mongo-mongodb-common-scripts
            defaultMode: 360
        - name: datadir
          persistentVolumeClaim:
            claimName: velocity-mongo-mongodb
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

### What is the expected behavior?

MongoDB  Pod to be running in 1/1

### What do you see instead?

MongoDB Pod restarting constantly and in 0/1 state

Attached logs 
[velocity-mongo-mongodb-78c4fb57c8-zm5mx-mongodb.log](https://github.com/bitnami/containers/files/14450657/velocity-mongo-mongodb-78c4fb57c8-zm5mx-mongodb.log)
