### ISSUE TITLE
[bitnami/kafka] Hostname verification is not being run

### ISSUE THREAD

**Issue by mrabey** [bitnami/containers#63488]
### Name and Version

bitnami/kafka:3.6.0-debian-11-r3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deployed Kafka w/ Kraft support to an Ubuntu docker image hosted on a Kubernetes cluster.  We use your Helm Chart to deploy the Kafka server to our Kubernetes cluster.  I have configured the server to use required mTLS communications on client, external, inter-broker, and controller communications.  Currently using JKS as the certificate structure and the certificates are confirmed to be configured correctly.

Configuration settings used on the server are as follows:
```
- authorizerClassName: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
- allowEveryoneIfNoAclFound: false
- auth.[clientProtocol, externalClientProtocol, interBrokerProtocol, controllerProtocol]: mtls
- auth.tls.type: jks
- auth.tls.endpointIdentificationAlgorithm: https
- allowPlaintextListeners: false
- extraEnvVars:
   - KAFKA_CFG_SSL_CLIENT_AUTH: required
   - KAFKA_CFG_SECURITY_PROTOCOL: ssl
   - KAFKA_CFG_SSL_ENABLED_PROTOCOLS: TLSv1.2, TLSv1.3
   - KAFKA_CFG_SSL_PRINCIPAL_MAPPING_RULES: "RULE:^.*[Cc][Nn]=([a-zA-Z0-9]*),.*$/$1/L,RULE:^.*[Cc][Nn]=(.*),[Oo]=.*,.*$/$1/L,RULE:^.*[Cc][Nn]=([a-zA-Z0-9._-]*)$/$1/L"
```
Configuration of a test client includes the following in the command config file:
```
- security.protocol=SSL
- ssl.endpoint.identification.algorithm=https
- ssl.[truststore, keystore].type=JKS
- ssl.[truststore, keystore].location=/etc/ssl/[truststore, keystore].jks
- ssl.[truststore, keystore].password="password used for both"
- ssl.key.password="password used for private key encryption"
```
The client leaf certificate has the following configuration:
- The common name (CN) is the identifier used by the ACL Authorizer which is simply the name of the service itself (dummy-service in this example)
- The subject alternative name (SAN) has one DNS entry with an intentionally incorrect FQDN (in this case, dummy-service.namespaceDoesntExist.svc.cluster.local)
- The certificate is signed by the same CA that signed the Kafka server certificate

The ACLs have been created for each user and are working as expected.  I created the topic `dummy-service-topic` granting producer and consumer operations for the `dummy-service` principal `User:dummy-service`.  I also created a group `dummy-service-group` granting READ+DESCRIBE operations to the `dummy-service` principal `User:dummy-service`.

### What is the expected behavior?

When the `dummy-service` with the incorrect SAN attempts to connect to the Kafka server, I expect the connection to be rejected because the FQDN `dummy-service.namespaceDoesntExist.svc.cluster.local` does not exist in our Kubernetes cluster.  The namespace `namespaceDoesntExist` is just that: a non-existent namespace.

### What do you see instead?

The `dummy-service` with a bad SAN entry is able to connect and produce to and consume from the topic I've set up via ACLs.

When running the following, it is able to connect:
`kafka-console-producer.sh --bootstrap-server kafka-0.kafka-headless.kafka-test.svc.cluster.local:9092 --producer.config /tmp/command.config --topic dummy-service-topic
`
With that run, I'm given a prompt that allows me to produce messages.

After producing messages onto the cluster, I then run the following to consume the messages:
`kafka-console-consumer.sh --bootstrap-server kafka-0.kafka-headless.kafka-test.svc.cluster.local:9092 --consumer.config /tmp/command.config --topic dummy-service-topic --group dummy-service-group --from-beginning
`

As mentioned, the `dummy-service` is able to connect as a consumer to the `dummy-service-topic` topic using the `dummy-service-group` group and see any messages I produced in the previous command execution.

### Additional information

All certificates are created using the step-ca hosted service within our AWS cloud environment.  The step-ca root and intermediate certificates are trusted on both the Kafka server and the clients.  Being that they're not truly "Trusted" certificates (i.e. not distributed in OS/Browsers as "Trusted 3rd Party CA certificates"), I'm curious if this is the reason why hostname verification is not properly being used to ensure that `dummy-service.namespaceDoesntExist.svc.cluster.local` is rejected properly.
