### ISSUE TITLE
Docker-compose for Kafka: Unable to set JAAS Config

### ISSUE THREAD

**Issue by stammaja** [bitnami/containers#63505]
### Name and Version

bitnami/kafka:3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When starting docker-compose.yaml with any of the options noted below:
1.
```yaml
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CFG_LISTENERS=LISTENER_PLAINTEXT://:9091,LISTENERSASLEXTERNAL://:9092,LISTENER_CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_PLAINTEXT://localhost:9091,LISTENERSASLEXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_PLAINTEXT:PLAINTEXT,LISTENERSASLEXTERNAL:SASL_PLAINTEXT,LISTENER_CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=LISTENER_CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_PLAINTEXT
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf"
      - BITNAMI_DEBUG=true
    volumes:
      - ./kafka/kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
    networks:
      - kafka-net
```
```
listenersaslexternal.KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
    serviceName="kafka"
    username="admin"
    password="adminsecret123"
    user_local="local_kafka_pw";
};
```
This version breaks with 

> Error: Could not find or load main class '-Djava.security.auth.login.config=.opt.bitnami.kafka.config.kafka_jaas.conf'
> 2024-03-04T09:38:07.605241644Z Caused by: java.lang.ClassNotFoundException: '-Djava.security.auth.login.config=.opt.bitnami.kafka.config.kafka_jaas.conf'

2. `KAFKA_CFG_OPTS` instead of `KAFKA_OPTS`
3. `KafkaServer` instead of `listenersaslexternal.KafkaServer`
4. `- KAFKA_LISTENER_NAME_LISTENERSASLEXTERNAL_PLAIN_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="kafka" username="admin" password="adminsecret123" user_local="local_kafka_pw";`

instead of using `kafka_jaas.config`

Options 2,3,4 behave like there was no variable set, cat /opt/bitnami/kafka/config/server.properties
gives result
`listener.name.listenersaslexternal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_user="bitnami";

### What is the expected behavior?

There is a way to set the listener's jaas config without mounting the whole `server.properties` file

### What do you see instead?

In any of the tested scenarios, cat /opt/bitnami/kafka/config/server.properties
gives result
`listener.name.listenersaslexternal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_user="bitnami";`

The application gets 'Authentication failed: Invalid username or password'

### Additional information

Only option which works is:
```yaml
    volumes:
      - ./kafka/config/server.properties:/opt/bitnami/kafka/config/server.properties
```
with
`listener.name.listenersaslexternal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="kafka" username="admin" password="adminsecret123" user_local="local_kafka_pw";`
