### ISSUE TITLE
[bitnami/redis] Setting the server password on first run

### ISSUE THREAD

**Issue by dominikkrulak** [bitnami/containers#6365]
### Name and Version

bitnami/redis:7.0.4-debian-11-r16

### What steps will reproduce the bug?

Upgrading the image from an older version and it seems that the current redis image can't create password for default user.

Passing the `REDIS_PASSWORD` environment variable when running the image for the first time should set the Redis(R) server password to the value of REDIS_PASSWORD (or the content of the file specified in REDIS_PASSWORD_FILE).

```
services:
  redis:
  ...
    environment:
      - REDIS_PASSWORD=password123
  ...
```

### What do you see instead?

When I `auth password123` in CLI I get

`"ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?"`

### Additional information

What I could:

- set environment variable `REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl` 
- create _users.acl_ file with following content `user default on >password123 ~* &* +@all`
- uncoment `aclfile` in _redis.config_ file and set it to `aclfile /opt/bitnami/redis/mounted-etc/users.acl`

That would create the password for default user and solve my application connection issue.

**Comment by fmulero** [comment]
Hi @dominikkrulak

I am trying to reproduce your issue but I haven't got luck. These are the steps and result I've got
```console
fmulero:/ $ docker run --name redis --rm -d -e REDIS_PASSWORD=password123 bitnami/redis:7.0.4-debian-11-r16
0b5416dfe5945e3e4272c21f803bd68a72fcc0c5e231988425602201c71d55d6
fmulero:/ $ docker exec -it redis bash
I have no name!@0b5416dfe594:/$ redis-cli 
127.0.0.1:6379> auth password123
OK
127.0.0.1:6379> 
```
Am I doing something wrong? Did I miss any step?

**Comment by dominikkrulak** [comment]
Hello @fmulero 

Thank you for the respond!
Thing is that I running it using `docker-compose` command.

I tried, retried, pruned `builder` cache but I always get
`"ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?"`

I was able to build the image using `docker` command successfully though.

Maybe I post my _docker-compose.yml_ file here:
```
version: '3.8'
    services:
    redis:
        env_file: .env
        build: ./docker-images/redis/7.0
        image: redis:7.0.4
        container_name: ${SERVICE_REDIS_CONTAINER_NAME}
        hostname: ${SERVICE_REDIS_HOSTNAME}
        networks:
            - backend
        ports:
            - "${SERVICE_REDIS_CONTAINER_PORT}:${SERVICE_REDIS_CONTAINER_PORT}"
        volumes:
            # Redis volume
            - type: volume
              source: craft-redis-7
              target: /bitnami/redis/data
            # Redis configuration files
            - type: bind
              source: ./docker-images/redis/7.0/config/redis.conf
              target: /opt/bitnami/redis/mounted-etc/redis.conf
#            - type: bind
#              source: ./docker-images/redis/config/users.acl
#              target: /opt/bitnami/redis/mounted-etc/users.acl
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            # - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PASSWORD=${SERVICE_REDIS_PASSWORD}
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
            #- REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
        restart: unless-stopped
```
