### ISSUE TITLE
[bitnami/elasticsearch] Support configuration of S3 repository

### ISSUE THREAD

**Issue by sephiroth-j** [bitnami/containers#63727]
### Name and Version

bitnami/elasticsearch:8

### What is the problem this feature will solve?

I'm using [bitnami/elasticsearch](https://artifacthub.io/packages/helm/bitnami/elasticsearch) Helm chart and I want to configure [an S3 snapshot repository](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html).

### What is the feature you are proposing to solve the problem?

- Allow to add `s3.client.default.access_key` and `s3.client.default.secret_key` to the Elasticsearch keystore.
- Allows the configuration of `bucket`, `path_style_access`, `region`, `endpoint` and `protocol` in a similar way to `path.repo` for [filesystem repositories](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-filesystem-repository.html).

**Comment by javsalgar** [comment]
Hi!

Thank you so much for he feature request. I will forward it to the team but we cannot guarantee an ETA as it is not a critical feature. However, if you want to speed up the process, you can submit a PR and the team will check it.

**Comment by sephiroth-j** [comment]
Hello,

I was able to implement this with the available possibilities and would therefore like to share my approach with others. I think this makes the feature request obsolete. I had not checked carefully enough in advance whether and how it might already be possible.

To configure the S3 client, two things are necessary:

1. store the keys in the keystore
2. set the endpoint and other parameters

For the keys: provide the keys as an environment variable and place a separate init script (not executable, must end with `.sh`) in `ELASTICSEARCH_INITSCRIPTS_DIR`. The script can then call the [`elasticsearch_set_key_value`](https://github.com/bitnami/containers/blob/af7781265f48ae0e4013528ece5010f91d8964ac/bitnami/elasticsearch/8/debian-12/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L134-L144) function to set the entries.

**example init script**
```sh
elasticsearch_set_key_value "s3.client.default.access_key" "${S3_ACCESSKEY}"
elasticsearch_set_key_value "s3.client.default.secret_key" "${S3_SECRETKEY}"
```

For the remaining parameters: place a file `my_${DB_FLAVOR}.yml` under `${DB_CONF_DIR}` with the corresponding content. This file is then processed by [`elasticsearch_custom_configuration`](https://github.com/bitnami/containers/blob/af7781265f48ae0e4013528ece5010f91d8964ac/bitnami/elasticsearch/8/debian-12/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L548-L555) and merged with the generated configuration file. Entries from `my_${DB_FLAVOR}.yml` can overwrite the others.

**example `my_${DB_FLAVOR}.yml`**
```yaml
s3:
  client:
    default:
      endpoint: "my.host.domain.tld:port"
      region: "my-region"
      path_style_access: true
```

For Helm, you can use `extraEnvVars` to set additional environment variables, `extraConfig` to define the content of `my_${DB_FLAVOR}.yml` and use `initScripts` to add custom init scripts.

**example Helm values**
```yaml
extraEnvVars:
  - name: S3_ACCESSKEY
    valueFrom:
      secretKeyRef:
        name: my-s3-keys
        key: access-key
  - name: S3_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: my-s3-keys
        key: secret-key
extraConfig:
  s3:
    client:
      default:
        endpoint: "my.host.domain.tld:port"
        region: "my-region"
        path_style_access: true
initScripts:
  configure-s3-client.sh: |
    elasticsearch_set_key_value "s3.client.default.access_key" "${S3_ACCESSKEY}"
    elasticsearch_set_key_value "s3.client.default.secret_key" "${S3_SECRETKEY}"
```
