### ISSUE TITLE
Exited with code 1

### ISSUE THREAD

**Issue by Justman100** [bitnami/containers#63808]
### Name and Version

bitnami/discourse:3.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

With this `docker-compose`:

```yaml
services:
  discourse:
    image: bitnami/discourse:3.2.0
    ports:
      - 5222:5222
    environment:
      DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER: 5222
      DISCOURSE_EXTERNAL_HTTPS_PORT_NUMBER: 5322
      DISCOURSE_HOST: <HOST>
      DISCOURSE_PORT_NUMBER: 5534
      DISCOURSE_SITE_NAME: Test
      DISCOURSE_ENV: production
      DISCOURSE_USERNAME: admin
      DISCOURSE_PASSWORD: 1234567890
      DISCOURSE_EMAIL: admin@admin.admin
      DISCOURSE_FIRST_NAME: <NAME>
      DISCOURSE_LAST_NAME: <NAME>
      DISCOURSE_DATABASE_HOST: postgres
      DISCOURSE_DATABASE_PORT_NUMBER: 5432
      DISCOURSE_DATABASE_NAME: discourse
      DISCOURSE_DATABASE_USER: justman10000
      DISCOURSE_DATABASE_PASSWORD: <MY_PASSWORD>
      DISCOURSE_DEFAULT_REDIS_HOST: redis
      ALLOW_EMPTY_PASSWORD: true
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: justman10000
      POSTGRES_PASSWORD: <MY_PASSWORD>
      POSTGRES_DB: discourse
  redis:
    image: redis:7.2.4
```

### What do you see instead?
```
discourse-1 ==> 
discourse-1 ==> [1mWelcome to the Bitnami discourse container[0m
discourse-1 ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
discourse-1 ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
discourse-1 ==> 
discourse-1 ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse-1 ==> You set the environment variable ALLOW_EMPTY_PASSWORD=true. For safety reasons, do not use this flag in a production environment.
discourse-1 ==> Creating Discourse configuration file
discourse-1 ==> Ensuring Discourse directories exist
discourse-1 ==> Trying to connect to the database server
discourse-1 ==> Populating database
discourse-1 ==> Creating admin user
discourse-1 exited with code 1
```
