### ISSUE TITLE
[bitnami/mongodb] arbiter crashloop when upgrading mongodb to chart 15.0.0+

### ISSUE THREAD

**Issue by rodolfoyanke** [bitnami/containers#63885]
### Name and Version

bitnami/mongodb:15.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm running kubernetes GKE version 1.27.11-gke.1118000

Steps:

1. install mongodb with the following params using chart 14.13.0

``` 
//helm install mydb -f mydb-dev.yaml bitnami/mongodb --version 14.13.0

auth:
  rootUser: mydb
  rootPassword: mydb
  usernames:
    - mydb
  passwords:
    - mydb
  databases:
    - mydb
architecture: replicaset
replicaCount: 1
global:
  storageClass: standard
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
resources:
  requests:
    memory: 256Mi
    cpu: 150m
extraFlags:
  - "--wiredTigerCacheSizeGB=1.0"
  
```  
  2 - after mongo and arbiter are healthy, upgrade to version 15.0.0:
           helm upgrade mydb -f mydb-dev.yaml bitnami/mongodb --version 15.0.0
  
  3 - the arbiter will crashloop with the following error in the logs:
            mkdir: cannot create directory '/bitnami/mongodb/data/db': Read-only file system

### What is the expected behavior?

The arbiter should start successfully. 

### What do you see instead?

Crashloop with the error:
   mkdir: cannot create directory '/bitnami/mongodb/data/db': Read-only file system

### Additional information

At first I thought it was something related to mongodb version 7.0.7 (chart 15.0.1) but it happens for mongodb 7.0.6 chart 15.0.0. The exact arbiter image is: docker.io/bitnami/mongodb:7.0.6-debian-12-r0

If I rollback to version 14.13.0(mongo 7.0.6) it works fine again, even though the arbiter image is exactly the same as above. I tried a clean install using version 15.0.0 and it doesn't work as well.

Forgive me in case of any misconfiguration from my side, just trying to upgrade and get rid of this issue.
Thank you in advance
