### ISSUE TITLE
[bitnami/kafka] Kafka kraft with TLS fails on 3.5 but works on 3.5.1

### ISSUE THREAD

**Issue by kalbhor** [bitnami/containers#63989]
### Name and Version

bitnami/kafka:3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using image bitnami/kafka:3.5 and docker compose

Docker compose configuration:
```yaml
version: "3"

services:
  kafka:
    image: bitnami/kafka:3.5
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_TLS_TYPE=PEM
      - KAFKA_SSL_KEYSTORE_TYPE=PEM
      - KAFKA_SSL_TRUSTSTORE_TYPE=PEM

      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_ENABLE_KRAFT=yes

      - KAFKA_MESSAGE_MAX_BYTES=100000000
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,EXTERNAL:SSL
      - KAFKA_CFG_LISTENERS=CONTROLLER://:8095,EXTERNAL://:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:8095
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://127.0.0.1:9092
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
      - ./certs:/bitnami/kafka/config/certs
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    restart: unless-stopped
volumes:
  kafka_data:
```

### What is the expected behavior?

Expected behavior is that the broker + controller should start successfully. I am able to run the same compose file with `3.5.1` and `3.7`. It seems to fail for `3.5` and `3.6`. 

### What do you see instead?

This seems to be the main exception. I can provide the entire log if needed.
```
kafka_1  | [2024-03-22 07:50:03,870] INFO [BrokerServer id=1] Transition from STARTING to STARTED (kafka.server.BrokerServer)
kafka_1  | [2024-03-22 07:50:03,872] ERROR [BrokerServer id=1] Fatal error during broker startup. Prepare to shutdown (kafka.server.BrokerServer)
kafka_1  | org.apache.kafka.common.config.ConfigException: Invalid value javax.net.ssl.SSLHandshakeException: No available authentication scheme for configuration A client SSLEngine created with the provided settings can't connect to a server SSLEngine created with those settings.
kafka_1  |      at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:102)
kafka_1  |      at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:73)
kafka_1  |      at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
kafka_1  |      at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:107)
kafka_1  |      at kafka.network.Processor.<init>(SocketServer.scala:973)
kafka_1  |      at kafka.network.Acceptor.newProcessor(SocketServer.scala:879)
kafka_1  |      at kafka.network.Acceptor.$anonfun$addProcessors$1(SocketServer.scala:849)
kafka_1  |      at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
kafka_1  |      at kafka.network.Acceptor.addProcessors(SocketServer.scala:848)
kafka_1  |      at kafka.network.DataPlaneAcceptor.configure(SocketServer.scala:523)
kafka_1  |      at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:251)
kafka_1  |      at kafka.network.SocketServer.$anonfun$new$31(SocketServer.scala:175)
kafka_1  |      at kafka.network.SocketServer.$anonfun$new$31$adapted(SocketServer.scala:175)
kafka_1  |      at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1  |      at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1  |      at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1  |      at kafka.network.SocketServer.<init>(SocketServer.scala:175)
kafka_1  |      at kafka.server.BrokerServer.startup(BrokerServer.scala:237)
kafka_1  |      at kafka.server.KafkaRaftServer.$anonfun$startup$2(KafkaRaftServer.scala:96)
kafka_1  |      at kafka.server.KafkaRaftServer.$anonfun$startup$2$adapted(KafkaRaftServer.scala:96)
kafka_1  |      at scala.Option.foreach(Option.scala:407)
kafka_1  |      at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:96)
kafka_1  |      at kafka.Kafka$.main(Kafka.scala:113)
kafka_1  |      at kafka.Kafka.main(Kafka.scala)
```

### Additional information

The PEM key files seem to be correct since they work with the other version (`3.7` and `3.5.1`)

**Comment by kalbhor** [comment]
@fevisera Were you able to check this out? I felt this was critical to resolve because version upgrades shouldn't ideally break fundamentals like cert handling

**Comment by kalbhor** [comment]
Sorry for the delayed response. I tested with `3.5.2` and it did not work but works for `3.6.2`

**Comment by migruiz4** [comment]
Hi @kalbhor,

I'm sorry but I have been unable to reproduce your issue, either using JKS or PEM certificates.
It is possible that your issue could be caused by some faulty env variables in your docker-compose, which I have corrected below.

Here are the docker-compose files I used, both using JKS and PEM certificates. I also included the script I used to generate the certificates:
- **Using JKS**
   docker-compose.yaml
     ```yaml
      version: "3"
    
      services:
        kafka:
          image: bitnami/kafka:3.5
          environment:
            - BITNAMI_DEBUG=true
    
            # - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
            - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
            
            #- KAFKA_TLS_TYPE=PEM
            #- KAFKA_SSL_KEYSTORE_TYPE=PEM
            #- KAFKA_SSL_TRUSTSTORE_TYPE=PEM
            - KAFKA_TLS_TYPE=JKS
            # Not needed in KRaft mode
            # - KAFKA_BROKER_ID=1
            - KAFKA_CFG_NODE_ID=1
            - ALLOW_PLAINTEXT_LISTENER=no
            # Deprecated
            # - KAFKA_ENABLE_KRAFT=yes 
      
            # - KAFKA_MESSAGE_MAX_BYTES=100000000
            - KAFKA_CFG_MESSAGE_MAX_BYTES=100000000
            
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,EXTERNAL:SSL
            - KAFKA_CFG_LISTENERS=CONTROLLER://:8095,EXTERNAL://:9092
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:8095
            - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://127.0.0.1:9092
          ports:
            - "127.0.0.1:9092:9092"
          volumes:
            - kafka_data:/bitnami/kafka
            - ./certs:/bitnami/kafka/config/certs
          ulimits:
            nofile:
              soft: 1000000
              hard: 1000000
          restart: unless-stopped
      volumes:
        kafka_data:
     ```
   gen-certs.sh
     ```bash
     #!/bin/bash
  
    rm -rf certs
    mkdir certs
    # Root CA
    echo "Creating CA certificate and key"
    openssl req -new -x509 -keyout certs/ca.key -out certs/ca.crt -days 365 -subj "/CN=Sample CA/OU=US/O=US/ST=US/C=US" -passout pass:my_pass
    
    echo "Creating Truststore"
    keytool -keystore certs/kafka.truststore.jks -alias CARoot -import -file certs/ca.crt -storepass my_pass -keypass my_pass -noprompt
    
    # Node certs
    
    echo "Creating node key"
    keytool -keystore certs/kafka.keystore.jks -alias kafka -validity 365 -genkey -keyalg RSA -dname "cn=kafka, ou=US, o=US, c=US" -storepass my_pass -keypass my_pass
    echo "Creating certificate sign request"
    keytool -keystore certs/kafka.keystore.jks -alias kafka -certreq -file certs/tls.srl -storepass my_pass -keypass my_pass
    echo "Signing certificate request using self-signed CA"
    openssl x509 -req -CA certs/ca.crt -CAkey certs/ca.key \
        -in certs/tls.srl -out certs/tls.crt \
        -days 365 -CAcreateserial \
        -passin pass:my_pass
    echo "Adding Ca certificate to the keystore"
    keytool -keystore certs/kafka.keystore.jks -alias CARoot -import -file certs/ca.crt -storepass my_pass -keypass my_pass -noprompt
    echo "Adding signed certificate"
    keytool -keystore certs/kafka.keystore.jks -alias kafka -import -file certs/tls.crt -storepass my_pass -keypass my_pass -noprompt
    
    # Cleanup
    rm certs/tls.crt certs/tls.srl certs/ca.srl
     ```
- **Using PEM**
   docker-compose.yaml
     ```yaml
     version: "3"
  
     services:
        kafka:
          image: bitnami/kafka:3.5
          environment:
            - BITNAMI_DEBUG=true
    
            # - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
            - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
            
            - KAFKA_TLS_TYPE=PEM
            # These envs do no exist
            #- KAFKA_SSL_KEYSTORE_TYPE=PEM
            #- KAFKA_SSL_TRUSTSTORE_TYPE=PEM
            
            # Not needed in KRaft mode
            # - KAFKA_BROKER_ID=1
            - KAFKA_CFG_NODE_ID=1
            - ALLOW_PLAINTEXT_LISTENER=no
            # Deprecated
            # - KAFKA_ENABLE_KRAFT=yes 
      
            # - KAFKA_MESSAGE_MAX_BYTES=100000000
            - KAFKA_CFG_MESSAGE_MAX_BYTES=100000000
            
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=EXTERNAL
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SSL,EXTERNAL:SSL
            - KAFKA_CFG_LISTENERS=CONTROLLER://:8095,EXTERNAL://:9092
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:8095
            - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://127.0.0.1:9092
          ports:
            - "127.0.0.1:9092:9092"
          volumes:
            - kafka_data:/bitnami/kafka
            - ./certs:/bitnami/kafka/config/certs
          ulimits:
            nofile:
              soft: 1000000
              hard: 1000000
          restart: unless-stopped
      volumes:
        kafka_data:
     ```
   gen-certs.sh
     ```bash
     #!/bin/bash
  
    rm -rf certs
    mkdir certs
    # Root CA
    openssl genrsa -out certs/ca.key 2048
    openssl req -new -x509 -sha256 \
            -subj "/CN=Test-CA" \
            -key certs/ca.key -out certs/ca.crt
    # Node cert
    openssl genrsa -out certs/node-key-temp.pem 2048
    openssl pkcs8 -inform PEM -outform PEM -in certs/node-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out certs/tls.key
    
    openssl req -new \
            -subj "/CN=kafka" \
            -key certs/tls.key -out certs/tls.csr
    openssl x509 -req -in certs/tls.csr -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial -sha256 -out certs/tls.crt
    # Cleanup
    rm certs/*-temp.pem
    rm certs/*.csr
    rm certs/*.srl
    # Rename
    mv certs/tls.crt certs/kafka.keystore.pem
    mv certs/tls.key certs/kafka.keystore.key
    mv certs/ca.crt certs/kafka.truststore.pem
     ```
