### ISSUE TITLE
[bitnami/redmine] [docker-compose] Bitnami is not starting with external database passed via environment variables 

### ISSUE THREAD

**Issue by gandhisagar** [bitnami/containers#64091]
### Name and Version

bitnami/redmine:5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Docker-compose for postgresql. I  want to use same postgres for multiple projects hence deployed postgresql seperately.

```yaml
version: '3'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: MASKED_USERNAME
      POSTGRES_PASSWORD:  MASKED_PASSWORD
    volumes:
      - /vmware/cache/database/postgresql:/var/lib/postgresql/data
```

I am able to  access the postgres using psql from any machine using VM Ip.

Redmine docker compose 
```yaml
version: '3'

services:
  redmine:
    image: bitnami/redmine:5
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: "yes"
      REDMINE_DB_HOST: "MASKED_IP"
      REDMINE_DB_PORT_NUMBER: "5432"
      REDMINE_DB_DATABASE: "bitnami_redmine"
      REDMINE_DB_USERNAME: "MASKED_USERNAME"
      REDMINE_DB_PASSWORD: "MASKED_PASSWORD"
    volumes:
      - /vmware/cache/redmine/plugins:/bitnami/redmine/plugins
```

Any help is appreciated.

### What is the expected behavior?

Server should come up when database is accessible.

### What do you see instead?

docker-compose logs

```
redmine_1  | redmine 18:33:15.32 INFO  ==> Welcome to the Bitnami redmine container
redmine_1  | redmine 18:33:15.32 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine_1  | redmine 18:33:15.33 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine_1  | redmine 18:33:15.33 INFO  ==>
redmine_1  | redmine 18:33:15.33 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine_1  | redmine 18:33:15.34 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 18:33:15.36 WARN  ==> The environment variable REDMINE_DB_POSTGRES is set. This configuration will be deprecated soon. Please set REDMINE_DATABASE_TYPE=postgresql to avoid errors in the future.
redmine_1  | redmine 18:33:15.37 WARN  ==> Hostname yes could not be resolved, this could lead to connection issues
redmine_1  | redmine 18:33:15.38 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 18:33:15.41 INFO  ==> Trying to connect to the database server
redmine_1  | Error: open /opt/bitnami/redmine/config/database.yml: no such file or directory
redmine_1  | redmine 18:34:16.07 INFO  ==>
redmine_1  | redmine 18:34:16.07 INFO  ==> Welcome to the Bitnami redmine container
redmine_1  | redmine 18:34:16.07 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine_1  | redmine 18:34:16.07 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine_1  | redmine 18:34:16.07 INFO  ==>
redmine_1  | redmine 18:34:16.08 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine_1  | redmine 18:34:16.08 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 18:34:16.11 WARN  ==> The environment variable REDMINE_DB_POSTGRES is set. This configuration will be deprecated soon. Please set REDMINE_DATABASE_TYPE=postgresql to avoid errors in the future.
redmine_1  | redmine 18:34:16.11 WARN  ==> Hostname yes could not be resolved, this could lead to connection issues
redmine_1  | redmine 18:34:16.12 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 18:34:16.16 INFO  ==> Trying to connect to the database server
redmine_1  | Error: open /opt/bitnami/redmine/config/database.yml: no such file or directory
```

I tried to create database.yml and mount it but then it said 

```
redmine_1  | redmine 18:11:24.93 INFO  ==> Welcome to the Bitnami redmine container
redmine_1  | redmine 18:11:24.93 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redmine_1  | redmine 18:11:24.93 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine_1  | redmine 18:11:24.93 INFO  ==>
redmine_1  | redmine 18:11:24.94 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine_1  | redmine 18:11:24.94 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 18:11:24.96 WARN  ==> The environment variable REDMINE_DB_POSTGRES is set. This configuration will be deprecated soon. Please set REDMINE_DATABASE_TYPE=postgresql to avoid errors in the future.
redmine_1  | redmine 18:11:24.97 WARN  ==> Hostname yes could not be resolved, this could lead to connection issues
redmine_1  | redmine 18:11:24.98 INFO  ==> Restoring persisted Redmine installation
redmine_1  | rm: cannot remove '/opt/bitnami/redmine/config/database.yml': Device or resource busy
```

### Additional information

uname -a
`Linux sjc-ubu-nsb-084 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

docker info
```
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 3
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 4.15.0-213-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.41GiB
 Name: sjc-ubu-nsb-084
 ID: a8081d89-035c-4d6d-adc3-e25c4d5e5ab2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://127.0.0.1:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARNING: No swap limit support
WARNING: No cpuset support
```

docker-compose version
```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```
