### ISSUE TITLE
custom pgbouncer.ini failed

### ISSUE THREAD

**Issue by zfallahnejad** [bitnami/containers#64100]
### Name and Version

bitnami/pgbouncer:1.22.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm having a postgresql service which contains two database: 'rasa' and 'mofid'.
Here is the db service in my docker compose file:
```
  db:
    restart: always
    image: bitnami/postgresql:11.9.0
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: "${DB_USER:-admin}"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
      POSTGRESQL_DATABASE: "${DB_DATABASE:-rasa}"
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "replicator"
      POSTGRESQL_REPLICATION_PASSWORD: "${REPLICA_DB_PASSWORD}"
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: "local"
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 1
```

When I use the following config for pgbouncer, I can connect to mofid database successfully.
```
  pgbouncer:
    image: bitnami/pgbouncer:1.22.1
    restart: always
    ports:
      - '6432:6432'
    environment:
      POSTGRESQL_USERNAME: "admin"
      POSTGRESQL_HOST: "db"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
      POSTGRESQL_DATABASE: "mofid"
      PGBOUNCER_AUTH_TYPE: "md5"
      PGBOUNCER_DATABASE: "mofid"
```

But I have two databases and I want to be able to connect both of them, so I wrote the following `pgbouncer.ini` file:
```
[databases]
mofid=host=db port=5432 dbname=mofid
rasa=host=db port=5432 dbname=rasa

[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
unix_socket_dir=/tmp/
unix_socket_mode=0777
auth_file=/opt/bitnami/pgbouncer/conf/userlists.txt
auth_type=md5
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
admin_users=admin
client_tls_sslmode=disable
server_tls_sslmode=disable
ignore_startup_parameters=extra_float_digits
stats_period=60
server_fast_close=0
```

### What is the expected behavior?

I want to be able to connect both databases which I have in a single postgresql service.

### What do you see instead?

When I use the following config for pgbouncer, It keeps restarting and throws an error.
```
  pgbouncer:
    image: bitnami/pgbouncer:1.22.1
    restart: always
    ports:
      - '6432:6432'
    environment:
      POSTGRESQL_USERNAME: "admin"
      POSTGRESQL_HOST: "db"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
      PGBOUNCER_AUTH_TYPE: "md5"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/opt/bitnami/pgbouncer/conf/pgbouncer.ini
```
Error:
```
rm: cannot remove '/opt/bitnami/pgbouncer/conf/pgbouncer.ini': Device or resource busy
```

![image](https://github.com/bitnami/containers/assets/5528548/aad9c79b-58a7-48d3-acf1-ee84f81cfd32)

I tried other paths for this file:
./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini 
./pgbouncer/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
But it ignored them.  

Without a pgbouncer.ini file or POSTGRESQL_DATABASE and PGBOUNCER_DATABASE, It doesn't know neither of my databases and automatically create a pgbouncer.ini file like this:

![image](https://github.com/bitnami/containers/assets/5528548/7f2947c9-c27d-473e-a8fb-fb28938243e2)

If I use it to connect to one of my database like `mofid`, It throw the following error:
```
closing because: no such database: mofid
```

**Comment by zfallahnejad** [comment]
Sorry for raising this issue. I solved the problem. I should use the following config:
```
  pgbouncer:
    image: docker.mofid.dev/bitnami/pgbouncer:1.22.1
    restart: always
    ports:
      - '6432:6432'
    environment:
      POSTGRESQL_USERNAME: "admin"
      POSTGRESQL_HOST: "db"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
      PGBOUNCER_AUTH_TYPE: "md5"
    volumes:
      - ./pgbouncer/:/bitnami/pgbouncer/conf/
```
Make sure to run the following command before this:
```
sudo chown 1001:1001 pgbouncer
```
