### ISSUE TITLE
[bitnami/spark] Problem with python code to creation of parquet file

### ISSUE THREAD

**Issue by kayvansol** [bitnami/containers#64632]
### Name and Version

bitnami/spark

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I test below python code with docker compose and bitnami image and the result was the same fault in creation of *.parquert file:

csv read **success**:

![readsuccess](https://global.discourse-cdn.com/business6/uploads/kubernetes/original/2X/1/1b6899684f17a61bbcb0bb76fdfa3fbc813cd473.png)

parquet file creation **failure**:

![parquetErr](https://github.com/bitnami/charts/assets/53554624/55c08625-5adf-4030-ba09-09a967e80fb2)

docker-compose.yml :
```yaml
version: '3.6'

services:

  spark:
    container_name: spark
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark   
    ports:
      - 127.0.0.1:8081:8080
    

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
```

docker run :
```
docker-compose up --scale spark-worker=2
```

ctp.py :
```python
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("WritingParquet").getOrCreate()

df = spark.read.option("header", True).csv("csv/file.csv")

df.show()

df.write.mode('overwrite').parquet("a.parquet")
```

spark submit :
```
./bin/spark-submit --class org.apache.spark.examples.SparkPi --master spark://35368355157f:7077 csv/ctp.py
```

please help me 👍

### What do you see instead?

creation of a.parquet folder  **without**  *.parquet file
