### ISSUE TITLE
[bitnami/moodle] realpath: /bitnami/apache/conf: No such file or directory

### ISSUE THREAD

**Issue by RafaelH31** [bitnami/containers#64950]
### Name and Version

bitnami/moodle/4.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - C:/srv/Configs/Databases/Moodle:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle

  moodle:
    image: bitnami/moodle:latest
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mysql
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - C:/srv/Configs/Moodle:/bitnami/moodle
      - C:/srv/Configs/MoodleData:/bitnami/moodledata
    depends_on:
      - mysql
    links:
      - mysql:mysql

```

### What do you see instead?
```
2024-04-06 19:09:52 moodle 22:09:52.38 INFO  ==> 
2024-04-06 19:09:52 moodle 22:09:52.39 INFO  ==> Welcome to the Bitnami moodle container
2024-04-06 19:09:52 moodle 22:09:52.39 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
2024-04-06 19:09:52 moodle 22:09:52.39 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-04-06 19:09:52 moodle 22:09:52.39 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
2024-04-06 19:09:52 moodle 22:09:52.39 INFO  ==> 
2024-04-06 19:09:52 moodle 22:09:52.39 INFO  ==> ** Starting Moodle setup **
2024-04-06 19:09:52 moodle 22:09:52.43 INFO  ==> Generating sample certificates
2024-04-06 19:09:53 Certificate request self-signature ok
2024-04-06 19:09:53 subject=CN = example.com
2024-04-06 19:09:53 realpath: /bitnami/apache/conf: No such file or directory
2024-04-06 19:09:53 moodle 22:09:53.19 INFO  ==> Configuring Apache ServerTokens directive
2024-04-06 19:09:53 moodle 22:09:53.22 INFO  ==> Configuring PHP options
2024-04-06 19:09:53 moodle 22:09:53.22 INFO  ==> Setting PHP expose_php option
2024-04-06 19:09:53 moodle 22:09:53.23 INFO  ==> Setting PHP output_buffering option
2024-04-06 19:09:53 moodle 22:09:53.25 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
2024-04-06 19:09:53 moodle 22:09:53.25 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
2024-04-06 19:09:53 moodle 22:09:53.35 INFO  ==> Ensuring Moodle directories exist
2024-04-06 19:09:53 moodle 22:09:53.38 INFO  ==> Trying to connect to the database server
2024-04-06 19:10:13 moodle 22:10:13.61 INFO  ==> Running Moodle install script
```

**Comment by javsalgar** [comment]
Hi,

Could you launch the moodle container with `BITNAMI_DEBUG=true` as an env var? This should provide more insight on the issue.

**Comment by longester** [comment]
if I change the  volumes:
      - type: bind
        source: /srv/Configs/Moodle
        target: /bitnami/moodle
      - type: bind
        source: /mnt/Storage/Moodle/MoodleData
        target: /bitnami/moodledata
this error will be shown.

**Comment by javsalgar** [comment]
Hi, 

Is this happening on a fresh installation? Did you run it with BITNAMI_DEBUG=true?

**Comment by longester** [comment]
> Hi,
> 
> Is this happening on a fresh installation? Did you run it with BITNAMI_DEBUG=true?
debian@debian:~$ docker run -d --name moodle \
  -p 8080:8080 \
  -p 8443:8443 \
  -e MOODLE_DATABASE_HOST=mariadb \
  -e MOODLE_DATABASE_PORT_NUMBER=3306 \
  -e MOODLE_DATABASE_USER=moodle \
  -e MOODLE_DATABASE_PASSWORD=moodlepassword \
  -e MOODLE_DATABASE_NAME=moodledb \
  -e BITNAMI_DEBUG=true \
  --network moodle-network \
  --volume moodle_data:/bitnami/moodle \
  bitnami/moodle:latest
a26bed9f2104ea1b1fd1b812071ed85710d6c02776d99092a2b0a25de0024cd9
debian@debian:~$ docker logs moodle
moodle 16:15:50.40 INFO  ==> 
moodle 16:15:50.40 INFO  ==> Welcome to the Bitnami moodle container
moodle 16:15:50.41 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 16:15:50.41 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle 16:15:50.41 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
moodle 16:15:50.41 INFO  ==> 
moodle 16:15:50.41 INFO  ==> ** Starting Moodle setup **
moodle 16:15:50.44 DEBUG ==> Validating settings in APACHE_* environment variables
moodle 16:15:50.47 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
moodle 16:15:50.48 INFO  ==> Generating sample certificates
Certificate request self-signature ok
subject=CN = example.com
realpath: /bitnami/apache/conf: No such file or directory
moodle 16:15:53.90 INFO  ==> Configuring Apache ServerTokens directive
moodle 16:15:53.91 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
moodle 16:15:53.95 INFO  ==> Configuring PHP options
moodle 16:15:53.96 INFO  ==> Setting PHP expose_php option
moodle 16:15:53.98 INFO  ==> Setting PHP output_buffering option
moodle 16:15:54.01 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 16:15:54.02 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 16:15:54.08 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle 16:15:54.17 INFO  ==> Ensuring Moodle directories exist
moodle 16:15:54.20 INFO  ==> Trying to connect to the database server
moodle 16:15:54.21 DEBUG ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2005 (HY000): Unknown server host 'mariadb' (-5)
moodle 16:15:59.23 DEBUG ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2005 (HY000): Unknown server host 'mariadb' (-5)
moodle 16:16:04.25 DEBUG ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2005 (HY000): Unknown server host 'mariadb' (-5)
moodle 16:16:09.27 DEBUG ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2005 (HY000): Unknown server host 'mariadb' (-5)
debian@debian:~$

**Comment by taufiqpsumarna** [comment]
```
services:
  moodle:
    image: docker.io/bitnami/moodle:4.5
    environment:
      - MOODLE_HOST=quiz.idstar.co.id
      - MOODLE_REVERSEPROXY=true
      - MOODLE_SSLPROXY=true
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=XXXXX
      - MOODLE_DATABASE_NAME=moodledb
      - BITNAMI_DEBUG=true
    volumes:
      - './path/to/host/moodle:/bitnami/moodle'
      - './path/to/host/moodledata:/bitnami/moodledata'
```

This is my docker-compose.yml files Issue `realpath: /bitnami/apache/conf: No such file or directory` it caused by permission issue you can fix this by changing your moodle and moodledata folder owner and permissions

```
# Fix ownership to Bitnami's default user (daemon)
sudo chown -R daemon:daemon ./path/to/host/moodle
sudo chown -R daemon:daemon ./path/to/host/moodledata

# Set proper permissions for Moodle files
sudo find ./path/to/host/moodle -type d -exec chmod 755 {} \;
sudo find ./path/to/host/moodle -type f -exec chmod 644 {} \;

# Set write permissions for Moodle data folder and mariadb
sudo chmod -R 770 ./data/moodledata
sudo chmod -R 777 ./data/mariadb
```

You should see this logs in your moodle container and congrats your moodle instance is running

![Image](https://github.com/user-attachments/assets/37729365-2bdd-438f-a11c-0b2f0193be33)

**Comment by taufiqpsumarna** [comment]
```yaml
services:
  moodle:
    image: docker.io/bitnami/moodle:4.5
    environment:
      - MOODLE_HOST=XXXXX
      - MOODLE_REVERSEPROXY=true
      - MOODLE_SSLPROXY=true
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=XXXXX
      - MOODLE_DATABASE_NAME=moodledb
      - BITNAMI_DEBUG=true
    volumes:
      - './path/to/host/moodle:/bitnami/moodle'
      - './path/to/host/moodledata:/bitnami/moodledata'
```

This is my docker-compose.yml files Issue `realpath: /bitnami/apache/conf: No such file or directory` it caused by permission issue you can fix this by changing your moodle and moodledata folder owner and permissions

```console
# Fix ownership to Bitnami's default user (daemon)
sudo chown -R daemon:daemon ./path/to/host/moodle
sudo chown -R daemon:daemon ./path/to/host/moodledata

# Set proper permissions for Moodle files
sudo find ./path/to/host/moodle -type d -exec chmod 755 {} \;
sudo find ./path/to/host/moodle -type f -exec chmod 644 {} \;

# Set write permissions for Moodle data folder and mariadb
sudo chmod -R 770 ./data/moodledata
sudo chmod -R 777 ./data/mariadb
```

You should see this logs in your moodle container and congrats your moodle instance is running

![Image](https://github.com/user-attachments/assets/37729365-2bdd-438f-a11c-0b2f0193be33)
