### ISSUE TITLE
[bitnami/minio] Getting an "Insufficient Storage" error when using approx. 35Gb/500Gb

### ISSUE THREAD

**Issue by Mo0rBy** [bitnami/containers#65107]
### Name and Version

bitnami/minio:2024.2.6-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy MinIO using the Helm chart to a cluster with persistence enabled and using a custom directory path as the dataDir within the container:
```yaml
...
    persistence:
      enabled: true
      storageClass: "myStorageClass"
      size: "500Gi"
      mountPath: "/data"
...
    extraEnvVars:
      - name: MINIO_DATA_DIR
        value: "/data"
...
```
Create the storageClass as well:
```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: myStorageClass
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-*********
  directoryPerms: "755"
  basePath: "/minio/data"
  uid: "1001"
  gid: "1001"
```
(I am using an EFS on AWS, but I don't think this matters too much)
2. Store some stuff in MinIO to use up the storage.
3. When you get to approx. 35Gb/40Gb, you should start getting errors stating that the server does not have sufficient storage.

### What is the expected behavior?

Because I have mounted a 500Gb directory, I would expect that I could store up to 500Gb of data.

### What do you see instead?

I have SSHed into my deployed MinIO container and found these results using `df` and `lsblk`:
```
I have no name!@minio-86d9d8c76c-9qbrd:/opt/bitnami/minio-client$ df
Filesystem            1K-blocks      Used        Available Use% Mounted on
overlay                41930732  30250096         11680636  73% /
tmpfs                     65536         0            65536   0% /dev
tmpfs                   8090368         0          8090368   0% /sys/fs/cgroup
127.0.0.1:/    9007199254739968 396052480 9007198858687488   1% /data          ## This is my dataDir
/dev/nvme0n1p1         41930732  30250096         11680636  73% /certs
shm                       65536         0            65536   0% /dev/shm
tmpfs                    524288        12           524276   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                   8090368         0          8090368   0% /proc/acpi
tmpfs                   8090368         0          8090368   0% /sys/firmware
```

Here is the result of `lsblk`. I think this is where my problem is.
Here I can only see the default `/bitnami/minio/data` directory and it is 40Gb.
```
I have no name!@minio-86d9d8c76c-9qbrd:/opt/bitnami/minio-client$ lsblk
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  40G  0 disk
|-nvme0n1p1   259:1    0  40G  0 part /bitnami/minio/data
`-nvme0n1p128 259:2    0   1M  0 part
```

However, I can see my data is being stored correctly inside the `/data` directory (which is what is defined in my Helm chart values/container envVars)
```yaml
    extraEnvVars:
      - name: MINIO_DATA_DIR
        value: "/data"
```
```
I have no name!@minio-86d9d8c76c-9qbrd:/data$ ls
automation-tests  releases
```
![Screenshot 2024-04-12 at 12 17 14](https://github.com/bitnami/containers/assets/88185573/bfda094d-0f20-41ef-b985-e0edfba92c01)

### Additional information

I think I might just need to perform some provisioning to correctly mount the 500Gb storageclass volume, but should this be done when the container initialises? 
I'm not sure if this is correct as I have the volume mounted with Kubernetes, so does it work differently?
And, I can see that data is being stored in the correct location. Why is MinIO stating that it is running out of storage when:
1. The `/data` directory has much more room available
2. The `/bitnami/minio/data` directory has nothing inside it, so even if MinIO is looking at this, it shouldn't be saying it has ran out of storage.
