### ISSUE TITLE
[bitnami/prestashop] Doesnt work with traefik

### ISSUE THREAD

**Issue by BettyNutz** [bitnami/containers#65132]
### Name and Version

bitnami/prestashop

### What architecture are you using?

amd64

### What steps will reproduce the bug?

config and run traefik with docker compose and wildcard ssl certs. - works with all other containers (eg plausable)
config and run bitnami prestshop - works with no ssl and no traefik
add traefik labels to ps compose
get 404 when adding url to firefox
or Gateway Timeout when accessing (https://phpmyadmin.example.com/)

### What is the expected behavior?

Presatshop runs website with tls letsencrypt certs behind traefik reverse proxy

### What do you see instead?

get 404 or bad gateway when accessing ps url as main domain (not subdomain (which also does not work)- 

Note: i actually show tls

### Additional information

Hope someone can help - ive been stuck on this for weeks now

**Comment by BettyNutz** [comment]
```
services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=AzfrZEby2PKyyH59P
      - MARIADB_DATABASE=prestashop_2024
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=gyeGjEZ92obHWg#Y#d7
    volumes:
      - /home/user1/bitnami/mariadb:/bitnami/mariadb
    networks:
      - prestashop-net

  prestashop:
    container_name: prestashop
    image: docker.io/bitnami/prestashop:latest
    environment:
      - PRESTASHOP_HOST=example.com
      - PRESTASHOP_TIMEZONE=Asia/Singapore
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=user1
      - PRESTASHOP_DATABASE_NAME=prestashop_2024
      - PRESTASHOP_DATABASE_PASSWORD=gyeGjEZ92obHWg#Y#d7
      - PRESTASHOP_FIRST_NAME=Bob
      - PRESTASHOP_LAST_NAME=Davis
      - PS_DEV_MODE=0
      - PS_DEMO_MODE=0
      - PS_FOLDER_ADMIN=admin076vwy4oc6vwy324
      - PRESTASHOP_PASSWORD=customer_support@example.com
      - PRESTASHOP_EMAIL=customer_support@example.com
      - PHP_UPLOAD_MAX_FILESIZE=0M
      - PHP_MEMORY_LIMIT=512M
      - ALLOW_EMPTY_PASSWORD=no
      - PRESTASHOP_SMTP_HOST=smtp.ipage.com
      - PRESTASHOP_SMTP_PORT=587
      - PRESTASHOP_SMTP_USER=email@example.com
      - PRESTASHOP_SMTP_PASSWORD=rdwKO1Xzq83HbFJ2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prestashop.rule=Host(`example.com`)" #This sets prestashop as the main domain
      - "traefik.http.routers.prestashop.entrypoints=websecure"
      - "traefik.http.routers.prestashop.tls.certresolver=myresolver"
    volumes:
      - /home/user1/bitnami/prestashop:/bitnami/prestashop
    depends_on:
      - mariadb
    networks:
      - prestashop-net
      - web

  phpmyadmin:
    container_name: myphpadmin
    image: phpmyadmin/phpmyadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.example.com`)" #This sets phpmyadmin as a subdomain
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
    networks:
      - prestashop-net
      - web

networks:
  prestashop-net:
    external: true
  web:
    external: true

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local

```
