### ISSUE TITLE
[bitnami/php-fpm] nginx & php-fpm images with podman compose - nginx container crashes on start

### ISSUE THREAD

**Issue by trymeouteh** [bitnami/containers#65285]
### Name and Version

docker.io/bitnami/php-fpm:8.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install Podman (I am using Podman 4.8.2)
2. Use podman compose to create containers

compose.yml
```
version: '3'
services:
    nginx:
        image: docker.io/bitnami/nginx
        volumes:
            - ./nginx.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
            - .:/app/
        ports:
            - 8080:8080
        networks:
            - app-tier
        depends_on:
            - phpfpm
    phpfpm:
        image: docker.io/bitnami/php-fpm
        volumes:
            - .:/app/
        networks:
            - app-tier
networks:
  app-tier:
    driver: bridge
```

nginx.conf

```
server {
    server_name localhost;
    listen 8080;
    
    root /app/www/public;

    index index.php index.html index.htm;
    autoindex on;

    location ~ \.php$ {
        fastcgi_pass phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
} 
```

### What is the expected behavior?

To have both the nginx and phpfpm container in the podman compose to run without any issues

### What do you see instead?

This is the error I get from the nginx container that causes the container to crash when it starts.
```
nginx 03:15:56.00 INFO  ==> ** Starting NGINX **
2024/04/19 03:15:56 [emerg] 1#1: host not found in upstream "phpfpm" in /opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:19
nginx: [emerg] host not found in upstream "phpfpm" in /opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:19
```

### Additional information

I am using podman cli 4.8.2 with podman desktop on Manjaro. I am trying to create a nginx container with phpfpm using the bitnami images from docker.io. I followed the instructions bitnami/nginx image and got it working with my own nginx configuration file. However I did follow the instructions to make bitnami/php-fpm work with bitnami/nginx and I cannot get it to work with podman compose.

Something to do with the nginx.conf file with the PHP configuration? However I did make sure it fastcgi_pass phpfpm:9000;

To my understanding it is due to Podman's use of networks. The nginx container is unable to communicate to the phpfpm container. I have fiddle around with the network setup in the compose file but setting the two containers to share the host network which did allow the nginx container to start up and stay running but when I go to a PHP page in my browser on localhost:8080, it will not load the PHP web page.

What am I doing wrong?
