### ISSUE TITLE
moodle with external db don't connect

### ISSUE THREAD

**Issue by Trujo-Dilar** [bitnami/containers#65656]
### Name and Version

bitnami/moodle:4.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

With docker-compose:
in docker-compose.yml
```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:4.3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_SITE_NAME=elearning.granadasalud.es
      - MOODLE_LANG=es
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=10.107.xxx.xxx
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=grdbelearning
      - MOODLE_DATABASE_PASSWORD=XXXXXXXXXX
      - MOODLE_DATABASE_NAME=provincial
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - /mnt/moodle/moodle:/bitnami/moodle
      - /mnt/moodle/moodledata:/bitnami/moodledata
```
It always fails to connect to the database.

### What is the expected behavior?

It will connect

### What do you see instead?
```
moodle_1  | moodle 09:48:46.35 ERROR ==> Could not connect to the database
```

### Additional information

if I enter in docker with:
```
docker exec -it 1c6265998b6f /bin/bash
# ps aux
/opt/bitnami/mysql/bin/mysql -N -u bn_moodle bitnami_moodle -h mariadb -P 3306 --connect-timeout=5
```
is likely don't accept the environment but the environment is good because:
```
# echo    $MOODLE_DATABASE_HOST
10.107.xxx.xxx
# echo    $MOODLE_DATABASE_USER
grdbelearning
```
and so on.

If I make a first rum with mariadb docker and I change data in:
```
/mnt/moodle/moodle/config.php
$CFG->dbtype    = 'mariadb';
$CFG->dblibrary = 'native';
$CFG->dbhost    = '10.107.xxx.xxx';
$CFG->dbname    = 'provincial';
$CFG->dbuser    = 'grdbelearning';
$CFG->dbpass    = 'XXXXXXXXX';
```
it works fine.
