### ISSUE TITLE
[bitnami/odoo] Docker containers does not work if docker compose persistance volumes are specified

### ISSUE THREAD

**Issue by sergueikp** [bitnami/containers#65799]
### Name and Version

bitnami/odoo 17.0.20240405, bitnami/odoo 16.0.20240315, bitnami/odoo 15.0.20240410, bitnami/odoo 14.0.20231110

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On Ubuntu 22.04
create a docker-compose.yml like the one below and run it with `docker-compose up -d`:
```yaml
version: '3'

networks:
  odoo17-network:
    name: odoo17-network
    driver: bridge
    
services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.2.0
    container_name: odoo17-postgresql
    networks:
      - odoo17-network
    restart: always
    user: root
    volumes:
      - /home/serguei/docker_persistance/postgresql:/bitnami/postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo
  odoo:
    image: docker.io/bitnami/odoo:17.0.20240405
    container_name: odoo17
    networks:
      - odoo17-network
    restart: always
    ports:
      - '80:8069'
    volumes:
      - /home/serguei/docker_persistance/bitnami/odoo:/bitnami/odoo
      - /home/serguei/docker_persistance/opt/bitnami/odoo/odoo/addons:/opt/bitnami/odoo/odoo/addons
      - /home/serguei/docker_persistance/opt/bitnami/python/lib/python3.11/:/opt/bitnami/python/lib/python3.11
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
      - ODOO_SMTP_HOST=smtp.gmail.com
      - ODOO_SMTP_PORT_NUMBER=587
      - ODOO_SMTP_USER=your_email@gmail.com
      - ODOO_SMTP_PASSWORD=your_password
```
### What is the expected behavior?

Specified Persistence folders should be accessible on the local machine and should not be empty:
```
      - /home/serguei/docker_persistance/opt/bitnami/odoo/odoo/addons:/opt/bitnami/odoo/odoo/addons
      - /home/serguei/docker_persistance/opt/bitnami/python/lib/python3.11/:/opt/bitnami/python/lib/python3.11
```
The Odoo application should work and be accessible through the web browser.

### What do you see instead?

Specified persistence folders are empty on the local machine.
The Odoo application is not accessible through the browser (the application does not run). 

### Additional information

We need to make persistent volumes and have access to any folder and file especially to `/opt/bitnami/odoo/odoo/addons`, `/python`, `/apache` on the local machine.
