### ISSUE TITLE
[bitnami/postgresql] unable to generate local authentication configuration

### ISSUE THREAD

**Issue by mecampbellsoup** [bitnami/containers#66230]
### Name and Version

bitnami/postgresql:16.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Use the `bitnami/postgresql` Helm chart, version `15.2.9`, which installs PG 16.2.0.

### What is the expected behavior?

Postgres container should initialize.

### What do you see instead?

ERROR:

```
cloud-console-postgresql-0 postgresql postgresql 18:55:19.41 DEBUG ==> Ensuring expected directories/files exist...
cloud-console-postgresql-0 postgresql postgresql 18:55:19.52 INFO  ==> pg_hba.conf file not detected. Generating it...
cloud-console-postgresql-0 postgresql postgresql 18:55:19.60 INFO  ==> Generating local authentication configuration
cloud-console-postgresql-0 postgresql popen failure: Cannot allocate memory
cloud-console-postgresql-0 postgresql initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/opt/bitnami/postgresql/bin/initdb"
- cloud-console-postgresql-0 › postgresql
```

**Comment by javsalgar** [comment]
Hi!

Did you try changing the resource requests to see if that fixes the issue. Which is the Kubernetes platform you are using?

**Comment by mecampbellsoup** [comment]
> Hi!
> 
> Did you try changing the resource requests to see if that fixes the issue. Which is the Kubernetes platform you are using?

I did try bumping the resource requests but got the same result.

We are using an old k8s distro, `1.20.15`.

**Comment by jotamartos** [comment]
Hi @mecampbellsoup,

I just tried to reproduce the issue and deployed a fresh Bitnami PostgreSQL chart using the default parameters and everything worked as expected. I installed the same version you mentioned 

```
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Running   0          103s
```

```
[38;5;6mpostgresql [38;5;5m15:05:36.38 [0m[38;5;2mINFO [0m ==> 
[38;5;6mpostgresql [38;5;5m15:05:36.47 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami postgresql container[0m
[38;5;6mpostgresql [38;5;5m15:05:36.47 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mpostgresql [38;5;5m15:05:36.47 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mpostgresql [38;5;5m15:05:36.47 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[38;5;6mpostgresql [38;5;5m15:05:36.48 [0m[38;5;2mINFO [0m ==> 
[38;5;6mpostgresql [38;5;5m15:05:36.67 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL setup **
[38;5;6mpostgresql [38;5;5m15:05:36.87 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql [38;5;5m15:05:36.88 [0m[38;5;2mINFO [0m ==> Loading custom pre-init scripts...
[38;5;6mpostgresql [38;5;5m15:05:36.97 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m15:05:37.07 [0m[38;5;2mINFO [0m ==> pg_hba.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m15:05:37.08 [0m[38;5;2mINFO [0m ==> Generating local authentication configuration
[38;5;6mpostgresql [38;5;5m15:05:43.01 [0m[38;5;2mINFO [0m ==> Starting PostgreSQL in background...
[38;5;6mpostgresql [38;5;5m15:05:43.57 [0m[38;5;2mINFO [0m ==> Changing password of postgres
[38;5;6mpostgresql [38;5;5m15:05:43.98 [0m[38;5;2mINFO [0m ==> Configuring replication parameters
[38;5;6mpostgresql [38;5;5m15:05:44.28 [0m[38;5;2mINFO [0m ==> Configuring synchronous_replication
[38;5;6mpostgresql [38;5;5m15:05:44.28 [0m[38;5;2mINFO [0m ==> Configuring fsync
[38;5;6mpostgresql [38;5;5m15:05:44.77 [0m[38;5;2mINFO [0m ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
[38;5;6mpostgresql [38;5;5m15:05:44.98 [0m[38;5;2mINFO [0m ==> Loading custom scripts...
[38;5;6mpostgresql [38;5;5m15:05:44.99 [0m[38;5;2mINFO [0m ==> Enabling remote connections
[38;5;6mpostgresql [38;5;5m15:05:45.08 [0m[38;5;2mINFO [0m ==> ** PostgreSQL setup finished! **

[38;5;6mpostgresql [38;5;5m15:05:45.27 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL **
2024-05-10 15:05:45.386 GMT [1] LOG:  pgaudit extension initialized
2024-05-10 15:05:45.479 GMT [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-05-10 15:05:45.480 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-05-10 15:05:45.480 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2024-05-10 15:05:45.507 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-05-10 15:05:45.572 GMT [130] LOG:  database system was shut down at 2024-05-10 15:05:44 GMT
2024-05-10 15:05:45.588 GMT [1] LOG:  database system is ready to accept connections
```

My cluster version is this one 

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-gke.1589018
```

>We are using an old k8s distro, 1.20.15.

Please use a supported version of Kubernetes to deploy the chart 

https://kubernetes.io/releases/

**Comment by mecampbellsoup** [comment]
Hi @jotamartos! Thanks for taking the time to help investigate this issue with me 😄 

> > We are using an old k8s distro, 1.20.15.
> 
> Please use a supported version of Kubernetes to deploy the chart
> 
> [kubernetes.io/releases](https://kubernetes.io/releases/)

So, I'm assuming that this isn't terribly relevant since the PG server process is what's erroring/crashing, but do you have any theories as to why k8s version might matter? Rather, I suspect the issue is with our configuration somewhere.

Here is the full `StatefulSet` spec, do you see anything that stands out as maybe problematic, and do you mind trying to run this in your env?

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: cloud-console
    meta.helm.sh/release-namespace: cloud-console
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: cloud-console
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.3.0
    helm.sh/chart: postgresql-15.2.11
    skaffold.dev/run-id: 08a688f7-a52c-4ceb-9a8c-c07f400aaba5
  name: cloud-console-postgresql
  namespace: cloud-console
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: cloud-console
      app.kubernetes.io/name: postgresql
  serviceName: cloud-console-postgresql-hl
  template:
    metadata:
      annotations:
        checksum/extended-configuration: d04da2e2227c932ae7fd3e880a16cf0dedd25537e5c7f02454115d6d4862e131
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: cloud-console
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 16.3.0
        helm.sh/chart: postgresql-15.2.11
        skaffold.dev/run-id: 08a688f7-a52c-4ceb-9a8c-c07f400aaba5
      name: cloud-console-postgresql
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: primary
                  app.kubernetes.io/instance: cloud-console
                  app.kubernetes.io/name: postgresql
              topologyKey: kubernetes.io/hostname
            weight: 1
      automountServiceAccountToken: false
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: POSTGRESQL_VOLUME_DIR
          value: /bitnami/postgresql
        - name: PGDATA
          value: /bitnami/postgresql/data
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: postgres-role-postgres
        - name: POSTGRES_DATABASE
          value: cloud-console
        - name: POSTGRESQL_ENABLE_LDAP
          value: "no"
        - name: POSTGRESQL_ENABLE_TLS
          value: "no"
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "false"
        - name: POSTGRESQL_LOG_CONNECTIONS
          value: "false"
        - name: POSTGRESQL_LOG_DISCONNECTIONS
          value: "false"
        - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
          value: "off"
        - name: POSTGRESQL_CLIENT_MIN_MESSAGES
          value: error
        - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
          value: pgaudit
        image: docker.io/bitnami/postgresql:16.3.0-debian-12-r3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -d "dbname=cloud-console" -h 127.0.0.1
              -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: postgresql
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - |
              exec pg_isready -U "postgres" -d "dbname=cloud-console" -h 127.0.0.1 -p 5432
              [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          failureThreshold: 6
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: 1Gi
            memory: 192Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /opt/bitnami/postgresql/conf
          name: empty-dir
          subPath: app-conf-dir
        - mountPath: /opt/bitnami/postgresql/tmp
          name: empty-dir
          subPath: app-tmp-dir
        - mountPath: /bitnami/postgresql/conf/conf.d/
          name: postgresql-extended-config
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /bitnami/postgresql
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      serviceAccount: cloud-console-postgresql
      serviceAccountName: cloud-console-postgresql
      terminationGracePeriodSeconds: 30
      volumes:
      - name: empty-dir
      - configMap:
          defaultMode: 420
          name: cloud-console-postgresql-extended-configuration
        name: postgresql-extended-config
      - emptyDir:
          medium: Memory
        name: dshm
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: block
      volumeMode: Filesystem
    status:
      phase: Pending
```
