### ISSUE TITLE
[bitnami/kafka] Cannot connect externally to docker container using port 9092

### ISSUE THREAD

**Issue by l0gicgate** [bitnami/containers#66487]
### Name and Version

bitnami/kafka:3.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?
I am able to setup an external listener via `localhost:9094` as per the examples and connect externally with Kadeck.

However, I want to be able to connect via `localhost:9092` as we are in the process of replacing our usage of the old wurstmeister/kafka image which is no longer being maintained.

All our configurations use port 9092 and it would be breaking change in too many places to fix this.

Can someone explain why this config does not let me connect via 9092 but does via 9094?

Here you can see I've setup 2 different listeners for external connections:
- `EXTERNAL://localhost:9092` - Unable to connect externally via `localhost:9092`
- `OUTSIDE://localhost:9094` - Able to connect externally via `localhost:9094`

Use the following service in a docker-compose.yaml file to reproduce:
```yaml
services:
  kafka:
    image: docker.io/bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:29092,CONTROLLER://:9093,EXTERNAL://:9092,OUTSIDE://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092,OUTSIDE://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    restart: always
```

### What is the expected behavior?

Being able to connect externally via `localhost:9092` instead of having to use `localhost:9094`

This is the output of kcat connecting via port 9092 when run multiple times. I can list topics, but cannot connect a consumer to it or use Kadeck to connect.
![CleanShot 2024-05-08 at 18 30 16@2x](https://github.com/bitnami/containers/assets/6510935/546a4bd8-5400-49d8-8ffe-cb6249738115)

### What do you see instead?

I cannot connect via port 9092 as expected
