### ISSUE TITLE
[bitnami/spark] Unable to open/explore 'Application Detail UI' via port 4040

### ISSUE THREAD

**Issue by vladyslavyaloveha** [bitnami/containers#67124]
### Name and Version

bitnami/spark:3.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Use next docker-compose.yaml example:
```
  spark-master:
    image: "bitnami/spark:3.5.1"
    container_name: spark-master
    ports:
      - "8082:8080/tcp"
      - "7077:7077/tcp"
      - "4040:4040/tcp"
    environment:
      SPARK_USER: spark
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_MODE: master

  spark-worker-1:
    image: "bitnami/spark:3.5.1"
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081/tcp"
      - "4041:4040/tcp"
    environment:
      SPARK_USER: spark
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
```

2. Up containers via docker-compose up --build
3. Pass any script for calculation

### What is the expected behavior?

Expected behavior: ability to explore UI during tasks execution via http://localhost:4040/ (since it is exposed).

### What do you see instead?

http://localhost:4040/  is unreachable
