### ISSUE TITLE
Unable to set schema compatibility level to forward_transitive

### ISSUE THREAD

**Issue by paveldanichev** [bitnami/containers#67127]
### Name and Version

bitnami/schema-registry:7.6.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Start container of `bitnami/schema-registry:7.6.1` with the environment variable  `SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL=forward_transitive`
This option is documented here: https://hub.docker.com/r/bitnami/schema-registry/

I use docker-compose. This is the basic setup (part of the YAML file):
```yaml
  schema-registry:
    image: bitnami/schema-registry:7.6.1
    container_name: schema-registry
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - type: bind
        source: /home/ubuntu/Documents/kafka/schema-registry-data
        target: /bitnami
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_DEBUG=true
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL=forward_transitive
    networks:
      - kafka-network
```

### What is the expected behavior?

The container should start.
The default compatibility level as returned by `curl localhost:8081/config` should be `forward_transitive`.

### What do you see instead?

The container exits promptly after starting.
Docker logs contain this error:
```
schema-registry 09:13:35.41 INFO  ==> ** Starting Schema Registry setup **
schema-registry 09:13:35.42 INFO  ==> Validating settings in SCHEMA_REGISTRY_* env vars
schema-registry 09:13:35.43 ERROR ==> The allowed values for SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL are: none, backward, forward or full
```

### Additional information

In addition to `forward_transitive` not included as one of the legal values for `SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL`, which looks like it is handled here: https://github.com/bitnami/containers/blob/913d85fcaf8b8e7a7a719a6a0bb5bd2aff179928/bitnami/schema-registry/7.6/debian-12/rootfs/opt/bitnami/scripts/libschemaregistry.sh#L182

according to https://docs.confluent.io/platform/current/schema-registry/installation/config.html
the parameter `avro.compatibility.level` is deprecated and should be replaced by `schema.compatibility.level`.
