### ISSUE TITLE
[bitnami/redis-cluster] After changing portmapping, redis-cluster doesnot work

### ISSUE THREAD

**Issue by bryanxtong** [bitnami/containers#67138]
### Name and Version

bitnami/redis-cluster:7.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

With different port mapping, It gives different results and when using all the default redis port 6379 for container, It is working but It doesnot work when using different redis port in different containers, please refer to attached for full files which includes the correct and wrong file, the only difference is the port mapping.

---It is working----
```
version: '3'
services:
  redis-node-0:
    user: root
    container_name: redis-node-0
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - ./redis_data-0:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.71.4'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6379'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16379'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.2
.....
```

---Not working---
```
version: '3'
services:
  redis-node-0:
    user: root
    container_name: redis-node-0
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 6380:6380
      - 16380:16380
    volumes:
      - ./redis_data-0:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_PORT_NUMBER=6380'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.71.4'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6380'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16380'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.2
....
```
The error is as below
```
redis-node-5  | Node redis-node-0 not ready, waiting for all the nodes to be ready...
redis-node-5  | Could not connect to Redis at redis-node-0:6385: Connection refused
redis-node-5  | Node redis-node-0 not ready, waiting for all the nodes to be ready...
redis-node-5  | Could not connect to Redis at redis-node-0:6385: Connection refused
redis-node-5  | Node redis-node-0 not ready, waiting for all the nodes to be ready...
redis-node-5  | Could not connect to Redis at redis-node-0:6385: Connection refused
redis-node-5  | Node redis-node-0 not ready, waiting for all the nodes to be ready...
redis-node-5  | Could not connect to Redis at redis-node-0:6385: Connection refused
redis-node-5  | Node redis-node-0 not ready, waiting for all the nodes to be ready...
```

### What do you see instead?

It should create redis cluster successfully whatever port mapping we are using
