### ISSUE TITLE
cannot create regular file '/bitnami/redis-sentinel/conf/sentinel.conf

### ISSUE THREAD

**Issue by antoniolobefaro** [bitnami/containers#67146]
### Name and Version

bitnami/redis-sentinel:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm trying to deploy Redis HA with sentinel in a docker swarm with 3 nodes.
with this docker-compose 

```yaml
version: '3.8'

networks:
  redis-nw:
    external: true

services:
  redis-master:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - redis-nw
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=7cBEcwf6mV36Rx3S
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb --min-replicas-to-write 3
    volumes:
      - 'redis-master-volume:/bitnami'
    deploy:
      mode: replicated
      replicas: 1

  redis-slave:
    image: 'redis:latest'
    networks:
      - redis-nw
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-slave-volume:/bitnami'
    environment:
      - REDIS_REPLICATION_MODE=replica
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=7cBEcwf6mV36Rx3S
      - REDIS_PASSWORD=7cBEcwf6mV36Rx3S
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb --min-replicas-to-write 3
    deploy:
      mode: replicated
      replicas: 2

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    networks:
      - redis-nw
    ports:
      - '26379:26379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-sentinel-volume:/bitnami'
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER=redis-master
      - REDIS_MASTER_PASSWORD=7cBEcwf6mV36Rx3S
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    deploy:
      mode: replicated
      replicas: 3

volumes:
  redis-master-volume:
    driver: local
  redis-slave-volume:
    driver: local
  redis-sentinel-volume:
    driver: local
```

sentinel containers fail. In the service logs the error that I found is 

```
cp: cannot create regular file '/bitnami/redis-sentinel/conf/sentinel.conf': No such file or directory
```
### What is the expected behavior?

everything run
