### ISSUE TITLE
Setup of MongoDB ReplicaSet with Helm Chart

### ISSUE THREAD

**Issue by Neniel** [bitnami/containers#67186]
### Name and Version

bitnami/mongodb:15.4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run the command below:
```
helm create test1 
```

2. Add the dependency to the Chart.yml file:
```yml
dependencies:
  - name: mongodb
    version: "15.4.5"
    repository: "https://charts.bitnami.com/bitnami"
```

3. Add these values to values.yml
```yml
mongodb:
  architecture: replicaset
  replicaCount: 3
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
    autoDiscovery:
      enabled: true
  serviceAccount:
    create: true
  automountServiceAccountToken: true
  rbac:
    create: true
  auth:
    enabled: false
  initdbScripts:
    setup_replicaset_script.js : |
      rs.add("test-mongodb-0-external.default.svc.cluster.local:27017")
      rs.add("test-mongodb-1-external.default.svc.cluster.local:27017")
      rs.add("test-mongodb-2-external.default.svc.cluster.local:27017")
```

4. Run the commands below to update, build and install the chart
```
helm dependency update test1 
helm dependency build test1
helm install test test1
```

5. You should see 3 services when running:
```
kubectl get svc
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
kubernetes                      ClusterIP      10.96.0.1        <none>        443/TCP           9m18s
test-mongodb-0-external         LoadBalancer   10.100.247.35    127.0.0.1     27017:30500/TCP   6m8s
test-mongodb-1-external         LoadBalancer   10.99.206.165    127.0.0.1     27017:32335/TCP   6m8s
test-mongodb-2-external         LoadBalancer   10.105.153.201   127.0.0.1     27017:31631/TCP   6m8s
test-mongodb-arbiter-headless   ClusterIP      None             <none>        27017/TCP         6m8s
test-mongodb-headless           ClusterIP      None             <none>        27017/TCP         6m8s
test-test2                      ClusterIP      10.97.241.91     <none>        80/TCP            6m8s
```

6. You should see 2 pods of test-mongodb-0 and test-mongodb-1 when running (is test-mongodb-2 is missing?)
```
kubectl get po
NAME                        READY   STATUS    RESTARTS        AGE
test-mongodb-0              1/1     Running   0               6m30s
test-mongodb-1              0/1     Running   0               6m19s
test-mongodb-arbiter-0      1/1     Running   1 (5m47s ago)   6m30s
test-test2-8d464978-bzzpm   1/1     Running   0               6m30s
```

7. Get into the pod test-mongodb-0 with `kubectl exec -i pod/test-mongodb-0 -- bash`
8. Run `mongosh` and then run the `rs.status()` command. You should see that only that pod is part of the RS

9. Get into the pod test-mongodb-1 with `kubectl exec -i pod/test-mongodb-1 -- bash`
10. Run `mongosh` and then run the `rs.status()` command. You should see an error that says: `MongoServerError[NotYetInitialized]: no replset config has been received`

### What is the expected behavior?

Replica set of 3 members should be created.

### What do you see instead?

A replica set of 3 members cannot be initialized
