### ISSUE TITLE
[bitnami/minio] How to build a MINIO distributed cluster with limited resources

### ISSUE THREAD

**Issue by hznuyyh** [bitnami/containers#67194]
### Name and Version

bitnami/minio:2024.3.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I wanted to build a distributed MINIO cluster, but my machine resources were limited, with only 3 physical machines available.

MInIO requires a minimum of 4 available nodes, how can I configure it to be deployed on 3 machines

The IP addresses of my three machines are 172.18.0.181, 172.18.0.182 and 172.18.0.183 respectively

I use DockerCompose for deployment, and here is my Compose example、

```
version: '2'

services:
  minio-1:
    container_name: "minio-1"
    image: minio:2024.3.10
    restart: "always"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio-1/data:/bitnami/minio/data'
      - './certs:/certs'
    environment:
      - BITNAMI_DEBUG=true
      - TZ=Asia/Shanghai
      - MINIO_DATA_DIR=/bitnami/minio/data
      - MINIO_ROOT_USER=xxxxxxxx
      - MINIO_ROOT_PASSWORD=xxxxxxxx
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_SCHEME=https
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=172.18.0.181:9000/bitnami/minio/data,172.18.0.181:9100/bitnami/minio/data,172.18.0.182:9000/bitnami/minio/data,172.18.0.182:9100/bitnami/minio/data,172.18.0.183:9000/bitnami/minio/data,172.18.0.183:9100/bitnami/minio/data

  minio-2:
    container_name: "minio-2"
    image: minio:2024.3.10
    restart: "always"
    ports:
      - '9100:9000'
      - '9101:9001'
    volumes:
      - './minio-2/data:/bitnami/minio/data'
      - './certs:/certs'
    environment:
      - BITNAMI_DEBUG=true
      - TZ=Asia/Shanghai
      - MINIO_DATA_DIR=/bitnami/minio/data
      - MINIO_ROOT_USER=xxxxxxxx
      - MINIO_ROOT_PASSWORD=xxxxxxxx
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_SCHEME=https
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=172.18.0.181:9000/bitnami/minio/data,172.18.0.181:9100/bitnami/minio/data,172.18.0.182:9000/bitnami/minio/data,172.18.0.182:9100/bitnami/minio/data,172.18.0.183:9000/bitnami/minio/data,172.18.0.183:9100/bitnami/minio/data

```

Here is the docker log 
```
 15:07:02.89 INFO  ==> 
 15:07:02.89 INFO  ==> Welcome to the Bitnami minio container
 15:07:02.89 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 15:07:02.90 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 15:07:02.90 INFO  ==> 
 15:07:02.90 INFO  ==> ** Starting MinIO setup **
minio 15:07:02.92 DEBUG ==> Validating settings in MINIO_* env vars..
minio 15:07:03.03 INFO  ==> Starting MinIO in background...

API: SYSTEM()
Time: 07:07:04 UTC 05/22/2024
Error: WARNING: Expected number of all hosts (6) to be remote +1 (6) (*errors.errorString)
       7: internal/logger/logger.go:260:logger.LogIf()
       6: cmd/peer-rest-client.go:631:cmd.newPeerRestClients()
       5: cmd/notification.go:1163:cmd.NewNotificationSys()
       4: cmd/server-main.go:383:cmd.initAllSubsystems()
       3: cmd/server-main.go:708:cmd.serverMain.func4()
       2: cmd/server-main.go:495:cmd.bootstrapTrace()
       1: cmd/server-main.go:707:cmd.serverMain()
ERROR Unable to configure server grid RPC services: grid: local host not found
minio 15:07:13.14 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 15:07:18.29 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 15:07:23.45 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 15:07:28.58 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 15:07:33.73 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 15:07:38.88 INFO  ==> Adding local Minio host to 'mc' configuration...
```

### What do you see instead?

Nothing

**Comment by hznuyyh** [comment]
I have solved the above problems, but now I have encountered a new problem, and after my modification, my Compose file is as follows
```
version: '2'

services:
  minio:
    hostname: "minio.example.net"
    container_name: "minio"
    image: minio:2024.3.10
    restart: "always"
    network_mode: host
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio-0/data:/bitnami/minio/data/0'
      - './minio-1/data:/bitnami/minio/data/1'
      - './certs:/certs'
    environment:
      - BITNAMI_DEBUG=true
      - MINIO_DATA_DIR=/bitnami/minio/data
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_SCHEME=https
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_SKIP_CLIENT=yes
      - MINIO_DISTRIBUTED_NODES=x.x.x.x/bitnami/minio/data/{0...1},x.x.x.x/bitnami/minio/data/{0...1},x.x.x.x/bitnami/minio/data/{0...1}
```

Now I can start the MinIO cluster on 3 machines
```
Waiting for a minimum of 1 drives to come online (elapsed 1s)

Waiting for all MinIO sub-systems to be initialize...
Automatically configured API requests per node based on available memory on the system: 160
All MinIO sub-systems initialized successfully in 18.695776ms
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.2024-03-10T02-53-48Z (go1.21.8 linux/amd64)

API: https://localhost:9000 
WebUI: https://x.x.x.x.:9001 https://10.0.50.1:9001 https://10.200.200.1:9001 https://10.201.0.1:9001 https://127.0.0.1:9001                       

Docs: https://min.io/docs/minio/linux/index.html
Status:         6 Online, 0 Offline. 
```
And I was able to create buckets and upload objects from https://127.0.0.1:9001, 
but I ran into a new problem.
The created Bucket can be seen on each machine, but the uploaded Object will only appear on one machine
just like this
```
Here is Machine One
.
├── certs
│   ├── CAs
│   │   └── public.crt
│   ├── certgen-linux-amd64
│   ├── private.key
│   └── public.crt
├── docker-compose.yaml
├── minio-0
│   └── data
│       └── 0522
│           └── WechatIMG2.jpeg
│               ├── c954c36c-1183-49e9-9e9c-5cf5f50e7679
│               │   └── part.1
│               └── xl.meta
└── minio-1
    └── data
        └── 0522
            └── WechatIMG2.jpeg
                ├── c954c36c-1183-49e9-9e9c-5cf5f50e7679
                │   └── part.1
                └── xl.meta

```
```
Here is machine 2 and 3
.
├── certs
│   ├── CAs
│   │   └── public.crt
│   ├── certgen-linux-amd64
│   ├── private.key
│   └── public.crt
├── docker-compose.yaml
├── minio-0
│   └── data
│       └── 0522
└── minio-1
    └── data
        └── 0522
```

As you can see, on machine 1, bucket 0522 has the object WechatImg, but there is only one empty bucket on machine 2/3

Can someone tell me how to solve this problem?

Because once machine 1 goes down, I will lose WechatImg. I need to automatically create a copy of the object so that it exists on 2/3 of the machine
