### ISSUE TITLE
[bitnami/valkey] constant 200m CPU usage with absolutely no traffic

### ISSUE THREAD

**Issue by mkyc** [bitnami/containers#67209]
### Name and Version

bitnami/valkey:7.2.5-debian-12-r4

### What architecture are you using?

None

### What steps will reproduce the bug?

- install valkey `0.2.0` like described [here](https://artifacthub.io/packages/helm/bitnami/valkey)
- use following values file: 
  ```yaml
  global:
    valkey:
      password: "password"
  
  architecture: standalone
  
  master:
    resources:
      requests:
        cpu: 300m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 50Mi
  
  image:
    debug: true
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ```

### What is the expected behavior?

valkey pod uses (near) 0 CPU when on fresh start with no connections and no nothing. 

### What do you see instead?

`valkey-master-0` container uses 200m of CPU all the time with no connections, no data, no nothing.

**Comment by javsalgar** [comment]
Hi,

Could you check if disabling the readiness/liveness probes changes the CPU usage? Just to spot if that's where the CPU usage comes from. If not, it may be something related to Valkey itself, not the Bitnami packaging of Valkey. My advice in that case would be to check with the upstream Valkey developers.

**Comment by mkyc** [comment]
Oh, you're right. I can confirm that when values yaml is: 

```yaml
global:
  valkey:
    password: "password"

architecture: standalone

auth:
  password: "password"

master:
  resources:
    requests:
      cpu: 300m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 50Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

image:
  debug: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

```

so probes are disabled then CPU is near 0.
