### ISSUE TITLE
[bitnami/kafka] class not found: kafka.admin.TopicCommand

### ISSUE THREAD

**Issue by syc87** [bitnami/containers#67218]
### Name and Version

bitnami/kafka:3.6.1, 3.6.2, 3.7.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```
services:
  kafka1:
    image: bitnami/kafka:3.6.2
    container_name: kafka1
    restart: always
    user: root
    ports:
     - '59092:59092'
    environment:
     - TZ=Asia/Shanghai
     - KAFKA_ENABLE_KRAFT=yes
     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXTSASL://:59092
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXTSASL:SASL_PLAINTEXT
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXTSASL://XXX.YYY:59092
     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXTSASL
     - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
     - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
     - KAFKA_CFG_NODE_ID=1
     - KAFKA_CFG_BROKER_ID=1
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
     - ALLOW_PLAINTEXT_LISTENER=yes
     - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
    volumes:
     - /data/kafka1:/bitnami/kafka
```

### What do you see instead?

Arm64 Newer versions >= 3.6.1:   ClassNotFoundException: kafka.admin.TopicCommand
Arm64 Older versions <= 3.6.0：works well;
Amd64 All versions: works well;
