### ISSUE TITLE
[bitnami/mediawiki] Redirect without domain name

### ISSUE THREAD

**Issue by Ducatel** [bitnami/containers#67210]
### Name and Version

bitnami/mediawiki:1.41.1-debian-12-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. On k8s cluster deploy random mariadb statufulset +  service like

<details>
  <summary>MariaDB full config</summary>

```yaml
# MariaDB
apiVersion: v1
kind: Service
metadata:
  namespace: wiki
  name: mariadb-service
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb-port
  clusterIP: None
  selector:
    app: mariadb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: wiki
  name: mariadb-sfs
spec:
  serviceName: "mariadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:10.11
        ports:
        - containerPort: 3306
          name: mariadb-port
        env:
         - name: MYSQL_DATABASE
           value: "wiki"
         - name: "MYSQL_USER"
           value: "u_wiki"
         - name: MYSQL_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: wiki-db-user-password
         - name: MARIADB_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        volumeMounts:
        - name: wiki-maraiadb-datadir
          mountPath: /var/lib/mysql/
  volumeClaimTemplates:
    - metadata:
        name: wiki-maraiadb-datadir
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
---
```
</details>

2. On the same cluster create ingress, service, pvc, and deployement with image `bitnami/mediawiki:1.41.1-debian-12-r8`

<details>
  <summary>Mediawiki full config</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-ingress
  namespace: wiki
spec:
  tls:
  - hosts:
    - wiki.mydomain.com
    secretName: https-certificate
  rules:
  - host: wiki.mydomain.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: wiki-svc
            port:
              number: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: wiki-svc
  namespace: wiki
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: wiki

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-dir
  namespace: wiki
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-deployment
  namespace: wiki
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1001:1001 /bitnami/mediawiki"]
        volumeMounts:
        - name: wiki-dir
          mountPath: /bitnami/mediawiki
      containers:
      - name: mediawiki
        image: bitnami/mediawiki:1.41.1-debian-12-r8
        resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: MEDIAWIKI_DATABASE_HOST
            value: "mariadb-service.wiki.svc.cluster.local"
          - name: MEDIAWIKI_DATABASE_USER
            value: "u_wiki"
          - name: MEDIAWIKI_DATABASE_NAME
            value: "wiki"
          - name: MEDIAWIKI_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: wiki-db-user-password
          - name: MEDIAWIKI_WIKI_NAME
            value: "MYwiki"
          - name: MEDIAWIKI_HOST
            value: "wiki.mydomain.com"
          - name: MEDIAWIKI_WIKI_PREFIX
            value: "/"
        volumeMounts:
        - name: wiki-dir
          mountPath: /bitnami/mediawiki
      securityContext:
        fsGroup: 1001
      volumes:
        - name: wiki-dir
          persistentVolumeClaim:
            claimName: wiki-dir
```
</details>

The useful part is mostly this one

```yaml
 - name: MEDIAWIKI_DATABASE_HOST
    value: "mariadb-service.wiki.svc.cluster.local"
  - name: MEDIAWIKI_DATABASE_USER
    value: "my_wiki"
  - name: MEDIAWIKI_DATABASE_NAME
    value: "wiki"
  - name: MEDIAWIKI_DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mariadb-secret
        key: wiki-db-user-password
  - name: MEDIAWIKI_WIKI_NAME
    value: "MY wiki"
  - name: MEDIAWIKI_HOST
    value: "wiki.mydomain.com"
  - name: MEDIAWIKI_WIKI_PREFIX
    value: "/"
```

### What is the expected behavior?

When accessing the root domain like `https://wiki.mydomain.com` displays the home page of the wiki.
Same if direct access to  `https://wiki.mydomain.com/index.php/Main_Page` 

### What do you see instead?

When access to:
*  `https://wiki.mydomain.com` redirected to `https://main_page/` with this log
```
10.xxxx.xxxx.xxx - - [22/May/2024:14:32:46 +0000] "GET / HTTP/1.1" 301 -
```

* `https://wiki.mydomain.com/index.php/Main_Page`  face an error 500 with this log
```
[Wed May 22 14:31:28.157678 2024] [core:error] [pid 279] [client 10.42.11.187:59368] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
2024-05-22T16:31:28.157918342+02:00 10.42.11.187 - - [22/May/2024:14:31:28 +0000] "GET /index.php/Main_Page HTTP/1.1" 500 528
```

### Additional information

The behavior was a little bit different before #64097 
Previously when access to `https://wiki.mydomain.com/index.php/Main_Page` the page was loaded but all links in the page was broken.

So maybe I don't understand how the env variables must be set, or there is some error on redirection config /rewrite rules.

Thanks in advance for your help
