### ISSUE TITLE
[bitnami/kafka] kafka data not persisted

### ISSUE THREAD

**Issue by barmaxence** [bitnami/containers#67212]
### Name and Version

bitnami/kafka:3.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```yml
kafka-broker:
    container_name: "kafka-broker"
    environment:
        KAFKA_CFG_NODE_ID: 1
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092'
        KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
        KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:29093'
        KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka-broker:29092,CONTROLLER://kafka-broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
        KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_CFG_LOG_DIRS: '/tmp/kraft-combined-logs'
        KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
        KAFKA_CFG_LOG_RETENTION_HOURS: 24
        KAFKA_KRAFT_CLUSTER_ID: 'xxx'
    healthcheck:
        test: kafka-topics.sh --bootstrap-server kafka-broker:29092 --list
    image: 'bitnami/kafka:3.6.1'
    networks:
        kafka:
    restart: 'unless-stopped'
```

```bash
kafka-topics.sh --bootstrap-server kafka-broker:29092 --topic topic1 --create --if-not-exists
kafka-topics.sh --bootstrap-server kafka-broker:29092 --topic topic2 --create --if-not-exists
```

### What is the expected behavior?

See some data in `/bitnami/kafka/data` and/or `/bitnami/kafka/config`

### What do you see instead?

Nothing

### Additional information

Even if I produce/consume some messages on the topics etc... I never obtain any data in `/bitnami/kafka` (`/data` `/config`) so it's useless to mount this volume to persist data from docker container since there is no data.

Except that, the broker is working as expected, no error in logs
