### ISSUE TITLE
[bitnami/dokuwiki] Dokuwiki container doesn't work

### ISSUE THREAD

**Issue by rmetcalf9** [bitnami/containers#67346]
### Name and Version

bitnami/dokuwiki:20240206.1.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

My compose file:
```yaml
version: "3.1"

##Ref https://hub.docker.com/r/bitnami/dokuwiki

services:
  dokuwikimain:
    image: bitnami/dokuwiki:20240206.1.0
    deploy:
      placement:
        constraints:
          - node.labels.datastore004 == true
      restart_policy:
        condition: on-failure
        delay: 6s
    environment:
      - BITNAMI_DEBUG=true
      - DOKUWIKI_USERNAME="dokuwikisuperuser"
      - DOKUWIKI_FULL_NAME="Robert Metcalf"
      - DOKUWIKI_EMAIL="rmetcalf9+dokuwikisuperuser@gmail.com"
      - DOKUWIKI_PASSWORD="XXX"
      - DOKUWIKI_WIKI_NAME="Roberts General Wiki"
    networks:
      - main_net

networks:
  main_net:
    external: true
```

Output:
```
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.03 INFO  ==> 
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.03 INFO  ==> Welcome to the Bitnami dokuwiki container
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.04 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.04 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.04 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.04 INFO  ==> 
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.04 INFO  ==> ** Starting DokuWiki setup **
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.07 DEBUG ==> Validating settings in APACHE_* environment variables
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.08 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:55.09 INFO  ==> Generating sample certificates
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | Certificate request self-signature ok
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | subject=CN = example.com
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | realpath: /bitnami/apache/conf: No such file or directory
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.35 INFO  ==> Configuring Apache ServerTokens directive
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.35 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.38 INFO  ==> Configuring PHP options
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.39 INFO  ==> Setting PHP expose_php option
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.40 INFO  ==> Setting PHP output_buffering option
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.45 DEBUG ==> Validating settings in DOKUWIKI_* environment variables...
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.52 INFO  ==> Configuring file permissions for DokuWiki
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:44:56.52 INFO  ==> Starting apache in background
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:45:01.68 INFO  ==> apache started
dokuwikimain_dokuwikimain.1.mm1dota4iu7p@metcaac8v2    | dokuwiki 07:45:01.87 ERROR ==> An error occurred while installing DokuWiki
```
The container is endlessly restarting

### What is the expected behavior?

I have taken out my volume to see if that was the issue but there is no difference.
I expect the container to start and be healthy

### What do you see instead?

The container quits and constantly restarts
