### ISSUE TITLE
[bitnami/scylladb] ScyllaDB stuck on "Checking that it started up correctly"

### ISSUE THREAD

**Issue by yngfoxx** [bitnami/containers#67359]
### Name and Version

bitnami/scylladb:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a scylladb docker compose file using bitnami image
```yaml
services:
    scylladb-node1:
        image: bitnami/scylladb:latest
        environment:
        - SCYLLADB_CLUSTER_NAME=scylladb-cluster
        - SCYLLADB_SEEDS=scylladb-node1,scylladb-node2
        - SCYLLADB_PASSWORD_SEEDER=yes
        - SCYLLADB_PASSWORD=password123

    scylladb-node2:
        image: bitnami/scylladb:latest
        environment:
        - SCYLLADB_CLUSTER_NAME=scylladb-cluster
        - SCYLLADB_SEEDS=scylladb-node1,scylladb-node2
        - SCYLLADB_PASSWORD=password123
```

### What is the expected behavior?

Run and allow external connection

### What do you see instead?

on both nodes.

![image](https://github.com/bitnami/containers/assets/47150226/342b8640-50bc-42ab-a30c-86b93aa3cad5)
