### ISSUE TITLE
[bitnami/postgrest] Support PostgREST v12

### ISSUE THREAD

**Issue by GavinColwell** [bitnami/containers#67683]
### Name and Version

bitnami/postgrest

### What is the problem this feature will solve?

[PostgREST v12](https://github.com/PostgREST/postgrest/blob/main/CHANGELOG.md#1200---2023-12-01) adds many new features such as aggregation functions (`count`, `sum`, `avg`, etc.) as well as several bugfixes

### What is the feature you are proposing to solve the problem?

adding a `containers/bitnami/postgrest/12` folder that holds the PostgREST v12 config as there are a couple of potentially [changes](https://github.com/PostgREST/postgrest/blob/v12/CHANGELOG.md#changed) that may be incompatible with v11 which is used now

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Postgrest is used mainly for the supabase helm chart, it would be important to first check if this is compatible with the solution.

**Comment by n0rmanc** [comment]
Update Postgrest to latest version it works fine for me.

supabase chart values.yaml

```
rest:
  image:
    registry: public.ecr.aws
    repository: supabase/postgrest
    tag: v12.0.1
  extraEnvVars:
    # enable db aggreates for postgrest
    - name: PGRST_DB_AGGREGATES_ENABLED
      value: 'TRUE'
```
