### ISSUE TITLE
[bitnami/moodle] realpath: /bitnami/apache/conf: No such file or directory 

### ISSUE THREAD

**Issue by longester** [bitnami/containers#67724]
### Name and Version

[bitnami/moodle] realpath: /bitnami/apache/conf: No such file or directory 
Linux debian 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```yaml
name: sharp_todd
services:
  mariadb:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 29985M
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /srv/Configs/Databases/Moodle
        target: /var/lib/mysql
    ports: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
    hostname: ""
  moodle:
    cpu_shares: 90
    command: []
    depends_on:
      mariadb:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 29985M
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_USER=root
      - PGID=100
      - PUID=998
    image: bitnami/moodle:latest
    links:
      - mariadb:mariadb
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 8443
        published: "8443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /srv/Configs/Moodle
        target: /bitnami/moodle
      - type: bind
        **source: /mnt/Storage/Moodle/MoodleData**
        target: /bitnami/moodledata
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
    hostname: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: ""
  index: /
  is_uncontrolled: false
  port_map: "8080"
  scheme: http
  store_app_id: sharp_todd
  title:
    custom: Moodle
```

### What is the expected behavior?

no error

### What do you see instead?
```
moodle 12:14:20.62 INFO  ==> Welcome to the Bitnami moodle container
moodle 12:14:20.62 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 12:14:20.62 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle 12:14:20.63 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
moodle 12:14:20.63 INFO  ==> 
moodle 12:14:20.63 INFO  ==> ** Starting Moodle setup **
**realpath: /bitnami/apache/conf: No such file or directory**
moodle 12:14:20.68 INFO  ==> Configuring Apache ServerTokens directive
moodle 12:14:20.71 INFO  ==> Configuring PHP options
moodle 12:14:20.72 INFO  ==> Setting PHP expose_php option
moodle 12:14:20.73 INFO  ==> Setting PHP output_buffering option
moodle 12:14:20.75 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle 12:14:20.76 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle 12:14:20.87 INFO  ==> Ensuring Moodle directories exist
moodle 12:14:20.95 INFO  ==> Trying to connect to the database server
moodle 12:14:21.02 INFO  ==> Running Moodle install script
```
