### ISSUE TITLE
[bitnami/openldap] Document a method to load cn=config LDIF files

### ISSUE THREAD

**Issue by zombiepigdragon** [bitnami/containers#67727]
### Name and Version

bitnami/openldap:2.6.8

### What is the problem this feature will solve?

At the moment, the documentation (README.md) for the OpenLDAP container states that "You can **not** set configuration for e.g. `cn=config` in those files" when describing `LDAP_CUSTOM_LDIF_DIR`. While this does appear to be the case, it does not provide a way forward for actually loading configuration changes at container creation time. In particular, I can not find an "easy" way to set ACLs.

### What is the feature you are proposing to solve the problem?

It would be useful if there was a solution documented in the README or nearby for doing this.

### What alternatives have you considered?

I have done a non-exhaustive search for relevant information, and come up dry. This may be blamed on my inexperience with Docker "at scale" or my inexperience with OpenLDAP if I missed anything significant, but as of yet I have found very little relevant information on the subject. I had hoped that [this search](https://github.com/bitnami/containers/issues?q=is%3Aissue+openldap+acl) would find the results I need, but I didn't find an answer there. #13891 seems like a hint, but "adapt this to your needs **and run ldapmodify**" (emphasis mine) is the extent of the instructions provided while it's also the step I need clarified- where do I run it? Is there no directory that it could run from?
My existing solution from before I switched to running OpenLDAP in Docker simply made all of its initializing changes with `slapadd` on a stopped database, which doesn't seem like an ideal solution here.

**Comment by zombiepigdragon** [comment]
Using custom configuration shell scripts works! For reference, here's (the generalized to remove application-specific information) version of the script I placed in `/docker-entrypoint-initdb.d/`:
```bash
#!/usr/bin/env bash
set -eu
. /opt/bitnami/scripts/libopenldap.sh

trap ldap_stop EXIT
ldap_start_bg

ldif_path=/tmp/acl.ldif

# FIXME: These permissions are horrible and insecure!
cat <<EOF >"$ldif_path"
dn: olcDatabase={2}mdb,cn=config
changetype: modify
replace: olcAccess
olcAccess: to * by users write by anonymous read
EOF
ldapmodify -a -Y EXTERNAL -H "ldapi:///" -f "$ldif_path"
rm "$ldif_path"
```
I also switched to using the same approach for populating the initial tree (still using the default variables from the image, along with some additional application-required structure), but the required ldapmodify syntax differs:
```bash
ldapmodify -a -x -D "${LDAP_ADMIN_DN}" -W -H "ldapi:///" -f "$ldif_path" <<<"${LDAP_ADMIN_PASSWORD}"
```
Finally, the relevant section of my `compose.yml` file:
```yaml
services:
  openldap:
    image: bitnami/openldap:2.6.8
    ports:
      - "9999:1389"
    environment:
      LDAP_CONFIGURE_PPOLICY: true
      LDAP_PPOLICY_HASH_CLEARTEXT: true
      LDAP_SKIP_DEFAULT_TREE: "yes"
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/builtin_admin_password
      LDAP_ADMIN_USERNAME: builtin_administrator 
      LDAP_ROOT: dc=example,dc=com
    secrets:
      - builtin_admin_password
    volumes:
      - ldap_data:/bitnami/openldap
      - ./Docker/ldap_init_scripts/:/docker-entrypoint-initdb.d/:ro
```
I'm going to close the issue at this time since the documentation I was looking for exists online in this comment, but I do think it would be useful to be more explicit about this in the README for the image to make it easier for other people that need the information to find it.

**Comment by boesr** [comment]
Although this is closed I would like to add something. There is no need to adjust the docker-entrypoint script.

I created the following acl file:

```text
dn: olcDatabase={2}mdb,cn=config
changetype: modify
replace: olcAccess
olcAccess: to attrs=userPassword
  by dn.exact="cn=admin,dc=example,dc=com" write
  by anonymous auth
  by * none
olcAccess: to *
  by dn.exact="cn=admin,dc=example,dc=com" write
  by dn.regex="bind\..+" read
  by anonymous auth
  by self read
  by * none
  ``` 
  
  and mapped it into the container via the following docker-compose

```yaml
services:
  openldap:
    container_name: openldap
    image: bitnami/openldap:2.6.8-debian-12-r4
    ports:
      - '389:389'
      - '636:636'
    environment:
      BITNAMI_DEBUG: true
      LDAP_LDAPS_PORT_NUMBER: 636
      LDAP_PORT_NUMBER: 389
      LDAP_ALLOW_ANON_BINDING: no
      LDAP_ROOT: ${LDAP_ROOT:-dc=example,dc=com}
      LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME:-admin}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-hello}
      LDAP_EXTRA_SCHEMAS: cosine,inetorgperson,argon2,ldapPublicKey,memberof,lastBind,acl
      LDAP_CUSTOM_SCHEMA_DIR: /custom-schemas
    volumes:
     # some additional mappings for other schemas
      - './openldap/ldifs/acl.ldif:/opt/bitnami/openldap/etc/schema/acl.ldif'
     env_file:
      - .env
volumes:
  openldap_data:
```

The ACLs get applied and are working without problems. I think it's a cleaner solution because it separates the ACL / custom config from the init script.
