### ISSUE TITLE
ETCDCTL_API=2 not working

### ISSUE THREAD

**Issue by jocafi** [bitnami/containers#67840]
### Name and Version

docker.io/bitnami/etcd:3.5.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

To reproduce the error, deploy the docker containers below on any swarm environment:

First, create the network:
`docker network create --driver overlay net-postgres`

```yaml
services:
  etcd1:
    image: docker.io/bitnami/etcd:3.5.13
    hostname: 'etcd1'
    networks:
      - net-postgres
    environment:
      #https://github.com/bitnami/containers/tree/main/bitnami/etcd
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCDCTL_API=2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  ## Add the curl service
  # curl http://etcd1:2379/v2/keys/message -XPUT -d value="Hello world"
  curl:
    image: curlimages/curl:latest
    hostname: 'curl'
    command: tail -f /dev/null
    networks:
      - net-postgres

networks:
  net-postgres:
    external: true
```
Enter into the 'curl' container. For example:
```
docker exec -it baf4e89159d0 sh
```

Show the version:
```console
$ curl -L http://etcd1:2379/version
{"etcdserver":"3.5.13","etcdcluster":"3.5.0"}
```
Try some v2 commands described at https://etcd.io/docs/v2.3/api/
Example:
```console
$ curl http://etcd1:2379/v2/keys/message -XPUT -d value="Hello world"
404 page not found
```
Here is also  another example of how to reproduce the error:
https://github.com/zalando/spilo/issues/995

### What is the expected behavior?

When using the option ETCDCTL_API=2, the etcd server should be compatible with the v2 API as described at 
https://hub.docker.com/r/bitnami/etcd  and https://etcd.io/docs/v2.3/api/

### What do you see instead?

I get HTTP-Status 404:
404 page not found
