### ISSUE TITLE
cannot change "user defined functions enabled" flag from docker-compose

### ISSUE THREAD

**Issue by mr-git** [bitnami/containers#67851]
### Name and Version

bitnami/cassandra:4.1.5

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. on macOS
2. `docker-cpmpose.yaml`:
```
services:
  cassandra:
    image: "bitnami/cassandra:4.1.5"
    ports: ["9042:9042"]
    environment:
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: true
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CFG_ENV_user_defined_functions_enabled: true
      CASSANDRA_CFG_YAML_user_defined_functions_enabled: true
```

### What is the expected behavior?

User defined functions are enabled

### What do you see instead?

in Cassandra logs during startup: `user_defined_functions_enabled=false; `

### Additional information

With `docker-compose.yaml`:
```
    image: "bitnami/cassandra:3.11.12" # have to match with image in `init` service
    environment:
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: true
```
The user defined functions were enabled
