### ISSUE TITLE
[bitnami/discourse] Issue with discourse-calendar plugin

### ISSUE THREAD

**Issue by FrostScent** [bitnami/containers#67939]
### Name and Version

bitnami/discourse:3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. with the compose file below.
```yaml
version: '3.8'

services:
  postgresql:
    image: 'bitnami/postgresql:16'
    ...
    
  redis:
    image: 'bitnami/redis:7.0'
    ...
    
  discourse:
    image: 'bitnami/discourse:3'
    environment:
     ...
  
  sidekiq:
    image: 'bitnami/discourse:3'
    environment:
    ...
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
```

2. install `discourse-calendar` plugin.

https://github.com/discourse/discourse-calendar

followed the below instructions.

https://docs.bitnami.com/aws/apps/discourse/configuration/install-plugins/

and also tried to copy GitHub repository to the plugin folder of the Docker volume and restarting it.

### What is the expected behavior?

The service should start normally.

### What do you see instead?

The service is not running with the error log below.

![image](https://github.com/bitnami/containers/assets/97640852/235d6f35-5620-4625-9658-1fb8015c4f13)
