### ISSUE TITLE
[bitnami/magento] no stylesheet

### ISSUE THREAD

**Issue by itnavigate** [bitnami/containers#67943]
### Name and Version

bitnami/magento 2.4.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Environment:
ubuntu 22.04
```
$ uname -a
Linux myhost 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ docker -v
Docker version 26.1.2, build 211e74b
```

Config:
```
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=${MAGENTO_HOST_URL}
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=${DB_USER}
      - MAGENTO_DATABASE_NAME=${DB_NAME}
      - MAGENTO_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_ADMIN_URL_PREFIX=${MAGENTO_ADMIN_URL_PREFIX}
      - MAGENTO_USERNAME=${MAGENTO_USERNAME}
      - MAGENTO_PASSWORD=${MAGENTO_PASSWORD}
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
```

Run:
```
$ docker compose up -d
[+] Running 7/7
 ⠿ Network magento-test_default              Created               0.1s
 ⠿ Volume "magento-test_elasticsearch_data"  Created        0.0s
 ⠿ Volume "magento-test_mariadb_data"        Created         0.0s
 ⠿ Volume "magento-test_magento_data"        Created        0.0s
 ⠿ Container magento-test-elasticsearch-1    Started            0.8s
 ⠿ Container magento-test-mariadb-1          Started            1.0s
 ⠿ Container magento-test-magento-1          Started           1.4s
$
```

wait for a bit...

### What is the expected behavior?

I expect to see the login page with a modal login dialog box, stylesheet applied.

### What do you see instead?

I do not get a stylesheet on the admin page :-(

![image](https://github.com/bitnami/containers/assets/1689824/348b4161-48b7-46f7-bb2b-a03a964f6ff9)

### Additional information

This was working last week. I tried installing Orson Theme, but this seemed to break my install (test env only) so I deleted all containers and volumes, and started from scratch, and I have this issue :-(

**Comment by itnavigate** [comment]
Pulled 2.4.6 and it worked

**Comment by itnavigate** [comment]
I do get this error, but I think it is unrelated:
```
magento-elasticsearch-1  | [2024-06-18T07:50:00,730][ERROR][o.e.i.g.GeoIpDownloader  ] [56a8dbef99c6] exception during geoip databases update
magento-elasticsearch-1  | org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
magento-elasticsearch-1  |      at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:137) ~[ingest-geoip-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:284) [ingest-geoip-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:100) [ingest-geoip-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:46) [ingest-geoip-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.22.jar:7.17.22]
magento-elasticsearch-1  |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
magento-elasticsearch-1  |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
magento-elasticsearch-1  |      at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by javsalgar** [comment]
Hi,

Could you see the errors of the browser inspector console?

**Comment by itnavigate** [comment]
Damn.

Firstly: Traefik is running to enable SSL.
Logs... Errors.....
```
Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure element 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/images/magento-logo.svg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.htmlUnderstand this warning
5[Report Only] Refused to load the stylesheet '<URL>' because it violates the following Content Security Policy directive: "style-src *.adobe.com unsafe-inline assets.braintreegateway.com *.aptrinsic.com fonts.googleapis.com 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
Understand this error
5Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.Understand this error
5[Report Only] Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src assets.adobedtm.com amcglobal.sc.omtrdc.net dpm.demdex.net cm.everesttech.net *.adobe.com widgets.magentocommerce.com data: <URL> <URL> googleads.g.doubleclick.net <URL> bid.g.doubleclick.net analytics.google.com <URL> *.ftcdn.net *.behance.net t.paypal.com <URL> <URL> fpdbs.paypal.com fpdbs.sandbox.paypal.com *.vimeocdn.com i.ytimg.com *.youtube.com validator.swagger.io <URL> b.stats.paypal.com dub.stats.paypal.com assets.braintreegateway.com c.paypal.com checkout.paypal.com *.paypal.com *.aptrinsic.com storage.googleapis.com data: 'self' 'unsafe-inline'".
Understand this error
d2f_admin/:1 [Report Only] Refused to load the script 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/requirejs/require.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com *.adobe.com www.googleadservices.com www.google-analytics.com googleads.g.doubleclick.net analytics.google.com www.googletagmanager.com *.newrelic.com *.nr-data.net geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.paypal.com www.sandbox.paypal.com www.paypalobjects.com t.paypal.com s.ytimg.com www.googleapis.com vimeo.com www.vimeo.com *.vimeocdn.com *.youtube.com https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ js.braintreegateway.com assets.braintreegateway.com c.paypal.com pay.google.com api.braintreegateway.com api.sandbox.braintreegateway.com client-analytics.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.paypal.com songbirdstag.cardinalcommerce.com *.aptrinsic.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
Understand this error
d2f_admin/:1 Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure script 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/requirejs/require.js'. This request has been blocked; the content must be served over HTTPS.Understand this error
d2f_admin/:1 [Report Only] Refused to load the script 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com *.adobe.com www.googleadservices.com www.google-analytics.com googleads.g.doubleclick.net analytics.google.com www.googletagmanager.com *.newrelic.com *.nr-data.net geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.paypal.com www.sandbox.paypal.com www.paypalobjects.com t.paypal.com s.ytimg.com www.googleapis.com vimeo.com www.vimeo.com *.vimeocdn.com *.youtube.com https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ js.braintreegateway.com assets.braintreegateway.com c.paypal.com pay.google.com api.braintreegateway.com api.sandbox.braintreegateway.com client-analytics.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.paypal.com songbirdstag.cardinalcommerce.com *.aptrinsic.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
Understand this error
d2f_admin/:1 Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure script 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.js'. This request has been blocked; the content must be served over HTTPS.Understand this error
d2f_admin/:1 [Report Only] Refused to load the script 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/requirejs-config.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com *.adobe.com www.googleadservices.com www.google-analytics.com googleads.g.doubleclick.net analytics.google.com www.googletagmanager.com *.newrelic.com *.nr-data.net geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.paypal.com www.sandbox.paypal.com www.paypalobjects.com t.paypal.com s.ytimg.com www.googleapis.com vimeo.com www.vimeo.com *.vimeocdn.com *.youtube.com https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ js.braintreegateway.com assets.braintreegateway.com c.paypal.com pay.google.com api.braintreegateway.com api.sandbox.braintreegateway.com client-analytics.braintreegateway.com client-analytics.sandbox.braintreegateway.com *.paypal.com songbirdstag.cardinalcommerce.com *.aptrinsic.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
Understand this error
d2f_admin/:1 Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure script 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/requirejs-config.js'. This request has been blocked; the content must be served over HTTPS.Understand this error
d2f_admin/:33 Uncaught TypeError: require is not a function
    at d2f_admin/:33:1
(anonymous) @ d2f_admin/:33Understand this error
d2f_admin/:80 Uncaught TypeError: require.config is not a function
    at d2f_admin/:80:30
(anonymous) @ d2f_admin/:80Understand this error
d2f_admin/:150 Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure element 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/images/magento-logo.svg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.htmlUnderstand this warning
d2f_admin/:1 Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure favicon 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/Magento_Theme/favicon.ico'. This request has been blocked; the content must be served over HTTPS.Understand this error
d2f_admin/:1 Mixed Content: The page at 'https://magento.my_domain.tld/d2f_admin/' was loaded over HTTPS, but requested an insecure favicon 'http://magento.my_domain.tld/static/version1718698802/adminhtml/Magento/backend/en_US/Magento_Theme/favicon.ico'. This request has been blocked; the content must be served over HTTPS.Understand this error
```

**Comment by itnavigate** [comment]
> Pulled 2.4.6 and it worked

Hmm... Not to confident in this statement now, as 2.4.6 is not working now :-/

**Comment by itnavigate** [comment]
Yep, works with http://magento....
I'm working backwards to see if Traefik or haproxy are interfering. My haproxy hasn't changed in the last few months, but Traerfik may have changed last week.

**Comment by itnavigate** [comment]
OK. So I'm confident that neither Traefik nor haproxy are causing the issue. I have removed them both from the system, and the error still occurs.
I can disable "Insecure content" checking (Chrome) or "Disable Protection" (Firefox) for my site, which isn't an option when we get to production.

What I don't understand is why this started recently.

Hmm.. I'm now running with this setup in my `docker-compose.yml`
```
  magento:
    image: docker.io/bitnami/magento:2
    # ports:
    #   - '80:8080'
    #   - '443:8443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magento.rule=Host(`${MAGENTO_HOST_URL}`)"
      - "traefik.http.routers.magento.entrypoints=websecure"
      - "traefik.http.routers.magento.tls.certresolver=letsencrypt"
    environment:
      - MAGENTO_HOST=${MAGENTO_HOST_URL}
      - MAGENTO_ENABLE_HTTPS=yes
      - MAGENTO_ENABLE_ADMIN_HTTPS=yes
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=${DB_USER}
      - MAGENTO_DATABASE_NAME=${DB_NAME}
      - MAGENTO_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=no
      - MAGENTO_ADMIN_URL_PREFIX=${MAGENTO_ADMIN_URL_PREFIX}
      - MAGENTO_USERNAME=${MAGENTO_USERNAME}
      - MAGENTO_PASSWORD=${MAGENTO_PASSWORD}
      - MAGENTO_EMAIL=${MAGENTO_EMAIL}
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
```

And all is working as expected.

Main change that impacts on this issue is the *_HTTPS lines in the environment section (changed from "no" to "yes" 
```
      - MAGENTO_ENABLE_HTTPS=yes
      - MAGENTO_ENABLE_ADMIN_HTTPS=yes
```

Obviously I mis-configured this over the weekend, and didn't document my change.

Thanks @javsalgar for your time on this.

I'm closing this as "user error".
