### ISSUE TITLE
[bitnami/php-fpm] Failing to load manually added extensions

### ISSUE THREAD

**Issue by Phatkone** [bitnami/containers#67940]
### Name and Version

bitnami/php-fpm

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. docker compose  with the following volumes mapped:
```
version: '3.6'
services:
  phpfpm_site:
    pull_policy: always
    container_name: phpfpm_rzapt
    image: "bitnami/php-fpm:latest"
    hostname: "fqdn"
    restart: unless-stopped
    volumes:
      - "/var/www/html/site:/app"
      - "/etc/site/php_pdo_sqlsrv.so:/opt/bitnami/php/lib/php/extensions/pdo_sqlsrv.so:rw"
      - "/etc/site/extensions.ini:/opt/bitnami/php/etc/conf.d/extensions.ini"a
    environment:
      TZ: "TZ/TZ"
      PUID: "33"
      PGID: "33"
    networks:
      "network":
        ipv4_address: "IP"
        
networks:
  "network":
    name: "network"
    external: true
```
2. extensions.ini contents:
```
 extension=pdo_sqlsrv
```

3. docker compose up -d

### What is the expected behavior?

module to be loaded into PHP

### What do you see instead?

Container log:
```
[18-Jun-2024 04:00:20] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv' (tried: /opt/bitnami/php/lib/php/extensions/pdo_sqlsrv (/opt/bitnami/php/lib/php/extensions/pdo_sqlsrv: cannot open shared object file: No such file or directory), /opt/bitnami/php/lib/php/extensions/pdo_sqlsrv.so (/opt/bitnami/php/lib/php/extensions/pdo_sqlsrv.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
When entering the docker shell and listing the dir its searching, the file is present:
```
root@rzapt:/app# ls -la /opt/bitnami/php/lib/php/extensions/
total 7092
drwxr-xr-x 1 root root    4096 Jun 18 04:00 .
drwxr-xr-x 1 root root    4096 Jun 17 20:48 ..
-rwxr-xr-x 1 root root  134600 Jun 17 20:38 apcu.so
-rwxr-xr-x 1 root root  532480 Jun 17 20:38 imagick.so
-rwxr-xr-x 1 root root   68264 Jun 17 20:38 maxminddb.so
-rwxr-xr-x 1 root root  200368 Jun 17 20:38 memcached.so
-rwxr-xr-x 1 root root 3640744 Jun 17 20:38 mongodb.so
-rwxr-xr-x 1 root root 1971760 Jun 17 20:38 opcache.so
-rwxr-xr-x 1 root root   68640 Jun 17 20:38 pdo_dblib.so
-rwxr-xr-x 1 root root   68672 Jun 17 20:38 pdo_pgsql.so
-rwxr-xr-x 1 root root  419640 Jun 12 20:45 pdo_sqlsrv.so  <---- file it says isn't found
-rwxr-xr-x 1 root root  134872 Jun 17 20:38 pgsql.so
```
### Additional information

verified that phpfpm docker is running 8.3.8 version of php.
downloaded the linux 8.3 pdo_sqlsrv package
