### ISSUE TITLE
401 when logging into Harbor from docker client

### ISSUE THREAD

**Issue by MayhemBill** [bitnami/containers#6878]
### Name and Version

bitname/harbor

### What steps will reproduce the bug?

Create docker stack using instructions

Sign in to docker registry

Error

### What is the expected behavior?

being able to sign into, and upload docker images

### What do you see instead?

401 unauthorized

### Additional information

the exact docker compose file I am using, with passwords filtered (I hope)
```
version: '2'

services:
  registry:
    image: docker.io/bitnami/harbor-registry:2
    environment:
      - REGISTRY_HTTP_SECRET=SuperSecurePassword
    volumes:
      - /mnt/development/harbor/registry_data:/storage
      - /mnt/development/harbor/config/registry/:/etc/registry/:ro
    restart: always
  registryctl:
    image: docker.io/bitnami/harbor-registryctl:2
    environment:
      - CORE_SECRET=SuperSecurePassword
      - JOBSERVICE_SECRET=SuperSecurePassword
      - REGISTRY_HTTP_SECRET=SuperSecurePassword
    volumes:
      - /mnt/development/harbor/registry_data:/storage
      - /mnt/development/harbor/config/registry/:/etc/registry/:ro
      - /mnt/development/harbor/config/registryctl/config.yml:/etc/registryctl/config.yml:ro
    restart: always
  postgresql:
    image: docker.io/bitnami/postgresql:13
    container_name: harbor-db
    environment:
      - POSTGRESQL_PASSWORD=SuperSecurePassword
      - POSTGRESQL_DATABASE=registry
    volumes:
      - /mnt/development/harbor/postgresql_data:/bitnami/postgresql
    restart: always
  core:
    image: docker.io/bitnami/harbor-core:2
    container_name: harbor-core
    depends_on:
      - registry
      - chartmuseum
    environment:
      - CORE_KEY=SuperSecurePassword
      - _REDIS_URL_CORE=redis://redis:6379/0
      - SYNC_REGISTRY=false
      - CHART_CACHE_DRIVER=redis
      - _REDIS_URL_REG=redis://redis:6379/1
      - PORT=8080
      - LOG_LEVEL=info
      - EXT_ENDPOINT=https://harbor.myhm.space
      - DATABASE_TYPE=postgresql
      - REGISTRY_CONTROLLER_URL=http://registryctl:8080
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=SuperSecurePassword
      - POSTGRESQL_SSLMODE=disable
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://core:8080/service/token
      - HARBOR_ADMIN_PASSWORD=SuperSecurePassword
      - CORE_SECRET=SuperSecurePassword
      - JOBSERVICE_SECRET=SuperSecurePassword
      - ADMIRAL_URL=
      - WITH_NOTARY=False
      - WITH_CHARTMUSEUM=True
      - CHART_REPOSITORY_URL=http://chartmuseum:8080
      - CORE_URL=http://core:8080
      - JOBSERVICE_URL=http://jobservice:8080
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - REGISTRY_CREDENTIAL_USERNAME=mayhem
      - REGISTRY_CREDENTIAL_PASSWORD=SuperSecurePassword
      - READ_ONLY=false
      - RELOAD_KEY=
    volumes:
      - /mnt/development/harbor/core_data:/data
      - /mnt/development/harbor/config/core/app.conf:/etc/core/app.conf:ro
      - /mnt/development/harbor/config/core/private_key.pem:/etc/core/private_key.pem:ro
    restart: always
  portal:
    image: docker.io/bitnami/harbor-portal:2
    container_name: harbor-portal
    depends_on:
      - core
    restart: always
  jobservice:
    image: docker.io/bitnami/harbor-jobservice:2
    container_name: harbor-jobservice
    depends_on:
      - redis
      - core
    environment:
      - CORE_SECRET=SuperSecurePassword
      - JOBSERVICE_SECRET=SuperSecurePassword
      - CORE_URL=http://core:8080
      - REGISTRY_CONTROLLER_URL=http://registryctl:8080
      - REGISTRY_CREDENTIAL_USERNAME=mayhem
      - REGISTRY_CREDENTIAL_PASSWORD=SuperSecurePassword
    volumes:
      - /mnt/development/harbor/jobservice_data:/var/log/jobs
      - /mnt/development/harbor/config/jobservice/config.yml:/etc/jobservice/config.yml:ro
    restart: always
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
  harbor-nginx:
    image: docker.io/bitnami/nginx:1.23
    container_name: nginx
    volumes:
      - /mnt/development/harbor/config/proxy/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    ports:
      - '80:8080'
    depends_on:
      - postgresql
      - registry
      - core
      - portal
    restart: always
  chartmuseum:
    container_name: chartmuseum
    image: docker.io/bitnami/chartmuseum:0
    environment:
      - CACHE=redis
      - CACHE_REDIS_ADDR=redis:6379
      - CACHE_REDIS_DB=1
      - DEPTH=1
      - PORT=8080
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/bitnami/data
      - ALLOW_OVERWRITE=true
      - INDEX_LIMIT=0
    volumes:
      - /mnt/development/harbor/chartmuseum_data:/bitnami/data
    restart: always
```
