### ISSUE TITLE
phpmyadmin 5.2.1 docker image started download php file when accessing to /

### ISSUE THREAD

**Issue by guitarrapc** [bitnami/containers#68901]
### Name and Version

bitnami/phpmyadmin:5.2.1-debian-12-r32

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Place following compose.yaml

```yaml
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=phpmyadmin
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=secret
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.1-debian-12-r32
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - PHPMYADMIN_ALLOW_ARBITRARY_SERVER=true
```

2. Run `docker compose up`
3. Open guest browse (private browse) and put `localhost:8080` to url address bar
4. You will find `download` file is downloaded instead of showing phpmyadmin login page.

### What is the expected behavior?

phpMyAdmin page should be shown when accessing to root url like `http://localhost:8080`.

### What do you see instead?

Accessing to `http://localhost:8080` download `download` file instead of showing top page. If you put `http://localhost:8080/index.php` then successfully show top page.

#### Who will affect?

Currently bitnami/phpmyadmin:5.2.1 is point to bitnami/phpmyadmin:5.2.1-debian-12-r32, so that users who cleaed host cached image `bitnami/phpmyadmin:5.2.1` encount this issue.

I've confirm both arm64 and amd64 image have same issue.

#### Workaround

Use `bitnami/phpmyadmin:5.2.1-debian-12-r31` instead of `bitnami/phpmyadmin:5.2.1` or `bitnami/phpmyadmin:5.2.1-debian-12-r32`.

#### Content-Type

When accessing with `bitnami/phpmyadmin:5.2.1-debian-12-r31` image,. top pages is `Content-Type:
text/html; charset=utf-8`, however `bitnami/phpmyadmin:5.2.1-debian-12-r32` image top pages is `Content-Type: application/x-httpd-php`.

bitnami/phpmyadmin:5.2.1-debian-12-r31

![image](https://github.com/bitnami/containers/assets/3856350/8aead996-dcc7-4a01-91ee-d9f92e44b6e9)

bitnami/phpmyadmin:5.2.1-debian-12-r32

![image](https://github.com/bitnami/containers/assets/3856350/0489994f-0581-490a-978a-463ed95d33d2)
