### ISSUE TITLE
[bitnami/odoo] Odoo Addons

### ISSUE THREAD

**Issue by moctarjallo** [bitnami/containers#69248]
### Describe your issue as much as you can

how to configure adding extra-addons on the odoo image ?

**Comment by rafariossaa** [comment]
Hi,
  Not sure what you want to achieve.
  Do you mean adding an addon to a running Odoo, or do yo mean adding an addon and creating a new image with the addon added ?

**Comment by moctarjallo** [comment]
I suspect that the solution lies under the _extraVolumes_ and _extraVolumesMounts_ but we probably need more documentation on how to use those variables, maybe with a commented example at least ?

**Comment by rafariossaa** [comment]
- For development: 

For the chart you would need to provide in the `extraVolumes` a volume declaration as indicated [here](https://kubernetes.io/docs/concepts/storage/volumes/). Specific sintax chages depending on the kind of volume you use.
Then, you would need where to mount that volume using `extraVolumesMounts', the sintax will be the same as in any other `volumeMount` section.

For the container you could use `-v` docker parameter, or the service's volume section and in general section, if you use docker compose.

- For delivering:
You could create a image based on this one and adding the required files, or you could create a initialization script a locate it on `/docker-entrypoint-init.d` [directory](https://github.com/bitnami/containers/blob/08b6288f46d2e8e6b0b6c4a47c2d8aa3b369701e/bitnami/odoo/17/debian-12/rootfs/post-init.sh#L12).

**Comment by moctarjallo** [comment]
Hello thanks for your response and time.

Here's what i have done so far: (in the **values.yaml** file)

  ```
## @param extraVolumes Optionally specify extra list of additional volumes for Odoo pods
  ##
  extraVolumes:
    - name: odoo-addons
      hostPath:
        path: /data/odoo/addons
  ## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for Odoo container(s)
  ##
  extraVolumeMounts:
    - name: odoo-addons
      mountPath: /opt/bitnami/odoo/addons
```

And this is the result after running ```helm install ...```:

```
NAME                    READY   STATUS             RESTARTS      AGE
odoo-5f948b98b4-jjzs6   0/1     CrashLoopBackOff   5 (35s ago)   11m
odoo-postgresql-0       1/1     Running            0             11m
```

I don't know if people have used this chart before, but i think the most important thing in using Odoo is to be able to add custom modules quickly and so there should have been a clear and concise example on how to do that after building this chart. Otherwise it is just a standalone software, very less useful. On the other hand, this chart would be very powerful if we had that at least !
