### ISSUE TITLE
[bitnami/openldap] customSchemaFiles not loading module during startup

### ISSUE THREAD

**Issue by wwjnufc** [bitnami/containers#69669]
### Name and Version

bitnami/openldap:2.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In value file, add the following block
```
customSchemaFiles:
  00-argon2-setup.ldif: |-
    dn: cn=module{0},cn=config
    changetype: modify
    add: olcModuleLoad
    olcModuleLoad: /opt/bitnami/openldap/lib/openldap/argon2.so

    dn: olcDatabase={-1}frontend,cn=config
    changetype: modify
    add: olcPasswordHash
    olcPasswordHash: {ARGON2}
```
2.  Verified that ldif is created
![image](https://github.com/user-attachments/assets/12ccdff0-15ef-462c-9153-5c565606b1dc)
3. However, when i run `ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config -LLL -Q '(objectClass=olcModuleList)' olcModuleLoad` it doesn't appear as module loaded.
4. Manually running the ldif will load the module `ldapmodify -Y EXTERNAL -H ldapi:/// -f /opt/bitnami/openldap/etc/schema/00-argon2-setup.ldif`
![image](https://github.com/user-attachments/assets/f945d4fe-160b-4236-b104-6777b422563f)

### What is the expected behavior?

The ldif defined in customSchemaFiles should be executed during OpenLDAP startup

### What do you see instead?

The ldif is doesn't appear to be triggered at all

### Additional information

dit root(k8s: minikube) $ minikube version
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d

dit root(k8s: minikube) $ docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~20.04.1

dit root(k8s: minikube) $ helm version
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}
