### ISSUE TITLE
[bitnami/zookeeper] Failed with: ls: cannot access '/bitnami/zookeeper/data': Operation not permitted

### ISSUE THREAD

**Issue by CharkeyQK** [bitnami/containers#69826]
### Name and Version

bitnami/zookeeper:13.4.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using `bitnami/zookeeper:13.4.8` with volumePermissions.enabled=true.
2. startup failed with error: `ls: cannot access '/bitnami/zookeeper/data'`

### What do you see instead?

1. set `privileged=true` and `allowPrivilegeEscalation=true`, zookeeper can startup normally.
2. other options at podSecurityContext and containerSecurityContext remain the same as default.

### Additional information

Kubernetes v1.23.4-r0

**Comment by javsalgar** [comment]
Hi,

Could you provide more details on your Kubernetes installation? We are unable to reproduce the issue

**Comment by CharkeyQK** [comment]
> Hi,
> 
> Could you provide more details on your Kubernetes installation? We are unable to reproduce the issue

The Kubernetes was a cluster of [CTYUN](https://www.ctyun.cn/document/10083472). version: v1.23.4-r0

First, deploy with `diagnosticMode.enabled=false` and `volumePermissions.enabled=true`.
Failed.
Then try with `diagnosticMode.enabled=true` and `volumePermissions.enabled=true` .
Update and redeploy zk.
Enter zookeeper container:
```
I have no name!@zookeeper-0:/$ ls /bitnami/zookeeper/data/
ls: cannot access '/bitnami/zookeeper/data/': Operation not permitted
I have no name!@zookeeper-0:/$ 
I have no name!@zookeeper-0:/$ cat /bitnami/zookeeper/data/myid 
1
```

One more thing, I have a sidecars set:
```
sidecars:
  - name: volume-permissions-checker
    image: 'registry.cn-gdgz1.ctyun.cn/dstp/os-shell:12-debian-12-r24'
    imagePullPolicy: IfNotPresent
    command:
      - sleep
    args:
      - infinity
    resources:
      limits:
        cpu: 150m
        ephemeral-storage: 2Gi
        memory: 192Mi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi
    securityContext:
      runAsUser: 0
      seLinuxOptions: { }
    volumeMounts:
      - mountPath: /bitnami/zookeeper
        name: data
```

 enter volume-permissions-checker container:
```
# step1
root@zookeeper-0:/# ls -la
total 60
...
drwxrwsrwx   4 1001 1001 4096 Jul 26 07:22 bitnami
...

#step2
root@zookeeper-0:/bitnami# ls -la
total 12
drwxr-xr-x 3 root root 4096 Jul 26 07:39 .
drwxr-xr-x 1 root root 4096 Jul 26 07:39 ..
drwxrwsrwx 4 1001 1001 4096 Jul 26 07:22 zookeeper

#step3
root@zookeeper-0:/bitnami/zookeeper# ls -la
total 28
drwxrwsrwx 4 1001 1001  4096 Jul 26 07:22 .
drwxr-xr-x 3 root root  4096 Jul 26 07:39 ..
drwxrwsr-x 2 1001 1001  4096 Jul 26 07:22 data
drwxrws--- 2 1001 1001 16384 Jul 26 07:19 lost+found

#step4
root@zookeeper-0:/bitnami/zookeeper/data# ls -la
total 12
drwxrwsr-x 2 1001 1001 4096 Jul 26 07:22 .
drwxrwsrwx 4 1001 1001 4096 Jul 26 07:22 ..
-rw-rw-r-- 1 1001 1001    2 Jul 26 07:23 myid
```

That's all appearance of my issue.

how can I diagnosis, Thanks for the help~
