### ISSUE TITLE
wordpress-nginx image is missing mysql_ensure_user_exists and mariadb_ensure_user_exists functions

### ISSUE THREAD

**Issue by timofey-drozhzhin** [bitnami/containers#70391]
### Name and Version

bitnami/wordpress-nginx:6.6.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Run `docker compose up`

```yaml
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6.6.1
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_wordpress
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

This is the original docker-compose.yml, with `MYSQL_CLIENT_CREATE_DATABASE_USER` variable added. 

### What is the expected behavior?

It should start WordPress

### What do you see instead?

`mariadb_ensure_user_exists()` and `mysql_ensure_user_exists()` functions not found.

### Additional information

[wordpress-nginx/6/debian-12/rootfs/opt/bitnami/scripts/libmysqlclient.sh](https://github.com/bitnami/containers/blob/b38c5260328eb9d4e5188a58443e930fe7da7736/bitnami/wordpress-nginx/6/debian-12/rootfs/opt/bitnami/scripts/libmysqlclient.sh) on line 706:
```
"${DB_FLAVOR}"_ensure_user_exists "${flags[@]}"
```
You can see that either `mariadb_ensure_user_exists()` and `mysql_ensure_user_exists()` are being called. However, those functions do not exist.

The last commit (#68885) removed the mysql_ensure_user_exists() function.
