### ISSUE TITLE
Error in libmysqlclient.sh: mysql_ensure_user_exists: command not found

### ISSUE THREAD

**Issue by rstml** [bitnami/containers#70390]
### Name and Version

bitnami/wordpress-nginx:6.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run wordpress-nginx using the following docker compose file:

```
version: '2'
services:
  mysqldb:
    image: docker.io/bitnami/mysql:8.0.39
    volumes:
      - 'mariadb_data:/bitnami/mysql'
    environment:
      - MYSQL_ROOT_USER=bn_root
      - MYSQL_ROOT_PASSWORD=bitnami_root
      - MYSQL_ENABLE_SSL=yes
    networks:
      - app-tier
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6.6.0
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - app-tier
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mysqldb
    environment:
      - BITNAMI_DEBUG=true
      - WORDPRESS_DATABASE_HOST=mysqldb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami_wordpress
      - WORDPRESS_ENABLE_DATABASE_SSL=yes
      - WORDPRESS_ENABLE_HTTPS=yes
      - WORDPRESS_ENABLE_REVERSE_PROXY=yes
      - MYSQL_CLIENT_FLAVOR=mysql
      - MYSQL_CLIENT_ENABLE_SSL=yes
      - MYSQL_CLIENT_DATABASE_HOST=mysqldb
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_USER=bn_root
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=bitnami_root
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami_wordpress
      - NGINX_HTTP_PORT_NUMBER = 8080
      - NGINX_HTTPS_PORT_NUMBER = ""

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  app-tier:
    driver: bridge
```

### What is the expected behavior?

Container start normally. It seems that the error was introduced with changes starting from bitnami/wordpress-nginx:6.5.5. Containers prior to that work as expected.

### What do you see instead?

When initialising Wordpress setup, I get the error below:

```
wordpress 23:50:44.88 INFO  ==> Creating database user bn_wordpress
/opt/bitnami/scripts/libmysqlclient.sh: line 706: mysql_ensure_user_exists: command not found
```
