### ISSUE TITLE
[bitnami/wordpress-nginx] 6.6.1 is not compatible with bitnami/mariadb:11.0.4

### ISSUE THREAD

**Issue by timofey-drozhzhin** [bitnami/containers#70392]
### Name and Version

bitnami/wordpress-nginx:6.6.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Create `compose.yaml` with the following:
```yaml
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ROOT_USER=root
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_PASSWORD=password
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6.6.1
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - WORDPRESS_AUTO_UPDATE_LEVEL=none
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - BITNAMI_DEBUG=true
      - MYSQL_CLIENT_DATABASE_HOST=mariadb
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=password
      - MYSQL_CLIENT_DATABASE_ROOT_USER=root
      - MYSQL_CLIENT_CREATE_DATABASE_CHARACTER_SET=utf8mb4
      - MYSQL_CLIENT_CREATE_DATABASE_COLLATE=utf8mb4_unicode_ci
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_wordpress
      - MYSQL_CLIENT_ENABLE_SSL=false
      - MYSQL_CLIENT_ENABLE_SSL_WRAPPER=false
      - MYSQL_CLIENT_FLAVOR=mysql
      - WORDPRESS_VERIFY_DATABASE_SSL=false
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

Then start the instance
```
docker compose down -v
docker compose up
```

### What is the expected behavior?

Expecting WordPress to Start

### What do you see instead?

```
wordpress-1  | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
wordpress-1  | wordpress 03:05:11.16 DEBUG ==> Executing SQL command:
wordpress-1  | SELECT 1
wordpress-1  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
```

<img width="1399" alt="Screenshot 2024-07-27 at 10 05 30 PM" src="https://github.com/user-attachments/assets/4434bb2d-27aa-490f-aa9e-8b5145f3d346">

### Additional information

Running the same compose.yaml file with `bitnami/wordpress-nginx:6.6.0` works fine.

This issue may be related to #70007
