### ISSUE TITLE
bitnami/minio   MINIO_HTTP_TRACE

### ISSUE THREAD

**Issue by lwj185392793** [bitnami/containers#70455]
### Name and Version

bitnami/minio:latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The HTTP log file specified at the environment variable MINIO_HTTP_TRACE is not writable by current user "0"

### What do you see instead?

I have removed the root and using root is not working. I noticed that the default log directory in the container has a minio-http.rog file
```
root@22282656bdbe:/opt/bitnami/minio/log# ls -l
total 0
lrwxrwxrwx 1 minio root 11 Feb 21 12:38 minio-http.log -> /dev/stdout
```
### Additional information
```yaml
services:
  minio:
    image: bitnami/minio:latest
    user: root
    volumes:
      - ./data:/bitnami/minio/data
    environment:
      - MONIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=S[QZObtPR4yGTBoYabrH
      - MINIO_SCHEME=http
      - BITNAMI_DEBUG=true
      - MINIO_SKIP_CLIENT=yes
      - MINIO_HTTP_TRACE=/opt/bitnami/minio/log/minio.log
    ports:
      - 9102:9000
      - 9101:9001
    restart: always
    privileged: true
```
