### ISSUE TITLE
how to make upgrade=NONE working 

### ISSUE THREAD

**Issue by wenzhep** [bitnami/containers#70506]
### Name and Version

bitnami_mysql:8.0.29-debian-10-r20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use helm to install mysql successfully and use it for a long time.
And recently I cannot access the mysql
and I found that when mysql start it will go to upgrade checking first.
at that stage there is an error happend
[logs (2).txt](https://github.com/user-attachments/files/16466621/logs.2.txt)

And it seems the upgrade=NONE can skip the upgrade, but when it does not work 
when I set it up in the env. with the MYSQL_EXTRA_FLAGS
```yaml
- env:
    - name: BITNAMI_DEBUG
      value: 'true'
    - name: MYSQL_EXTRA_FLAGS
      value: '--upgrade=NONE'
```
how to make it work?

### What is the expected behavior?

the MySQL should start and skip the upgrade.

### What do you see instead?

mysql cannot start
