### ISSUE TITLE
Problems starting up discourse with docker compose(exit with code 1)

### ISSUE THREAD

**Issue by anyu-svg** [bitnami/containers#70553]
### Name and Version

bitnami/discourse:3

### What architecture are you using?

None

#### OS and docker version

 4core 16GRAM

```console
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

demo@test2:~$ uname -a
Linux test2 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# 4core 16GRAM
```
```console
$ docker version
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:01 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:01 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
## `the docker-compose.yml` file and `.env`

`docker-compose.yml`

```yaml
# image: https://hub.docker.com/r/bitnami/discourse
# compose: https://github.com/bitnami/containers/blob/main/bitnami/discourse/docker-compose.yml

version: '3.8'
services:
  discourse:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    env_file: .env
    ports:
      - '$W9_HTTP_PORT_SET:$W9_HTTP_PORT'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    environment:
      - DISCOURSE_USERNAME=$W9_LOGIN_USER
      - DISCOURSE_PASSWORD=$W9_POWER_PASSWORD
      - POSTGRESQL_CLIENT_POSTGRES_USER=discourse
      - POSTGRESQL_CLIENT_POSTGRES_PASSWORD=$W9_RCODE
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
    depends_on:
      - postgresql
      - redis
  
  sidekiq:
    image: $W9_REPO:$W9_VERSION
    env_file: .env
    container_name: $W9_ID-sidekiq
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh

  postgresql:
    image: docker.io/bitnami/postgresql:16
    container_name: $W9_ID-postgresql
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=discourse
      - POSTGRESQL_USERNAME=discourse
      - POSTGRESQL_PASSWORD=$W9_RCODE

  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: $W9_ID-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'


networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```

the `.env` file, the password information (This container runs on machines that are open to the public and can display password information.)

```
W9_POWER_PASSWORD='!r70eNjzw9orWeu8'
W9_REPO=docker.io/bitnami/discourse
W9_VERSION='3'
W9_DIST='community'

#### --  Not allowed to edit below environments when recreate app based on existing data  -- ####
W9_ID='discourse_8297s'
W9_HTTP_PORT=3000
W9_HTTP_PORT_SET='9333'
W9_LOGIN_USER=admin
W9_LOGIN_PASSWORD=$W9_POWER_PASSWORD
W9_DB_EXPOSE="postgresql"
W9_RCODE='5O7bD4DKnXFSn'
# This URL must use domain, discourse don't allowed IP access
W9_URL='discourse.test2.websoft9.cn'
W9_URL_REPLACE=true
W9_NETWORK=websoft9
#### --------------------------------------------------------------------------------------- ####
BITNAMI_DEBUG=true
DISCOURSE_HOST=$W9_URL
ALLOW_EMPTY_PASSWORD=no

# You can set SMTP after installation
DISCOURSE_SMTP_HOST=smtp.gmail.com
DISCOURSE_SMTP_PORT=587
DISCOURSE_SMTP_USER=your_email@gmail.com
DISCOURSE_SMTP_PASSWORD=your_password
DISCOURSE_SMTP_PROTOCOL=tls

DISCOURSE_DATABASE_HOST=$W9_ID-postgresql
DISCOURSE_DATABASE_PORT_NUMBER=5432
DISCOURSE_DATABASE_USER=discourse
DISCOURSE_DATABASE_NAME=discourse
DISCOURSE_DATABASE_PASSWORD=$W9_RCODE

DISCOURSE_REDIS_HOST=$W9_ID-redis
DISCOURSE_REDIS_PORT_NUMBER=6379
W9_APP_NAME='discourse'
```

when using the command `docker compose up -d`, the error occurred.

### What is the expected behavior?

the discourse  container should run normal.
the correct log( Once, both containers (discoure and sidekiq) exited (exit with code 1), then I restarted the service and it worked, but I can't reproduce the operation.):
```
discourse 01:57:57.54 INFO  ==> Welcome to the Bitnami discourse container
discourse 01:57:57.54 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 01:57:57.54 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 01:57:57.54 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 01:57:57.54 INFO  ==> 
discourse 01:57:57.55 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 01:57:57.56 INFO  ==> Trying to connect to the database server
discourse 01:58:02.61 INFO  ==> Creating database discourse
discourse 01:58:02.72 WARN  ==> The DISCOURSE_REDIS_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environments.
discourse 01:58:02.73 INFO  ==> Creating Discourse configuration file
discourse 01:58:02.76 INFO  ==> Enabling SMTP
discourse 01:58:02.78 INFO  ==> Ensuring Discourse directories exist
discourse 01:58:02.78 INFO  ==> Trying to connect to the database server
discourse 01:58:02.81 INFO  ==> Populating database
discourse 01:58:25.66 INFO  ==> Creating admin user
discourse 01:58:30.24 INFO  ==> Persisting Discourse installation
discourse 01:58:30.64 INFO  ==> Precompiling assets, this may take some time...
discourse 02:01:03.54 INFO  ==> ** Discourse setup finished! **
discourse 02:01:03.56 INFO  ==> ** Starting Discourse **
=============== Phusion Passenger(R) Standalone web server started ===============
PID file: /opt/bitnami/discourse/passenger.3000.pid
Log file: /opt/bitnami/discourse/log/passenger.3000.log
Environment: production
Accessible via: http://0.0.0.0:3000/
You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
[ N 2024-08-05 02:01:07.5660 921/T6 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
Started HEAD "/" for 127.0.0.1 at 2024-08-05 02:01:14 +0000
Processing by ListController#latest as HTML
  Rendered list/list.erb within layouts/crawler (Duration: 8.9ms | Allocations: 11214)
  Rendered layout layouts/crawler.html.erb (Duration: 79.1ms | Allocations: 53130)
Completed 200 OK in 376ms (Views: 82.7ms | ActiveRecord: 0.0ms | Allocations: 273490)
Started GET "/" for 175.0.226.108 at 2024-08-05 02:01:15 +0000
Processing by ListController#latest as HTML
Deprecation notice: `SiteSetting.min_trust_to_create_tag` has been deprecated. Please use `SiteSetting.create_tag_allowed_groups` instead. (removal in Discourse 3.3) 
At /opt/bitnami/discourse/lib/guardian/tag_guardian.rb:12:in `can_create_tag?`
  Rendered list/list.erb within layouts/application (Duration: 1.2ms | Allocations: 930)
  Rendered layout layouts/application.html.erb (Duration: 806.0ms | Allocations: 114872)
Completed 200 OK in 924ms (Views: 806.9ms | ActiveRecord: 0.0ms | Allocations: 179368)
Started GET "/opensearch.xml" for 175.0.226.108 at 2024-08-05 02:01:19 +0000
Processing by MetadataController#opensearch as XML
  Rendered metadata/opensearch.xml.erb (Duration: 4.8ms | Allocations: 308)
Completed 200 OK in 13ms (Views: 10.0ms | ActiveRecord: 0.0ms | Allocations: 1477)
```

### What do you see instead?

the discourse container exits with code 1.
the error log:
It throws an error,  `Error: Cannot find module './lib/corepack.cjs'`, but I don't know how to solve this problem. 
```
discourse 05:58:05.13 INFO  ==> 
discourse 05:58:05.14 INFO  ==> Welcome to the Bitnami discourse container
discourse 05:58:05.14 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 05:58:05.14 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 05:58:05.14 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 05:58:05.14 INFO  ==> 
discourse 05:58:05.16 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 05:58:05.17 INFO  ==> Trying to connect to the database server
 ?column? 
----------

1
(1 row)
discourse 05:58:05.19 INFO  ==> Creating database discourse
CREATE EXTENSION
CREATE EXTENSION
discourse 05:58:05.29 DEBUG ==> Validating settings in DISCOURSE_* environment variables...
discourse 05:58:05.32 WARN  ==> The DISCOURSE_REDIS_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow a blank password. This is only recommended for development environments.
discourse 05:58:05.33 INFO  ==> Creating Discourse configuration file
discourse 05:58:05.33 DEBUG ==> Setting hostname to 'discourse.test2.websoft9.cn' in Discourse configuration
discourse 05:58:05.34 DEBUG ==> Setting db_host to 'discourse_9ootw-postgresql' in Discourse configuration
discourse 05:58:05.34 DEBUG ==> Setting db_port to '5432' in Discourse configuration
discourse 05:58:05.34 DEBUG ==> Setting db_username to 'discourse' in Discourse configuration
discourse 05:58:05.35 DEBUG ==> Setting db_password to 'vSGpb9CwlYQ4W' in Discourse configuration
discourse 05:58:05.35 DEBUG ==> Setting db_name to 'discourse' in Discourse configuration
discourse 05:58:05.36 DEBUG ==> Setting db_backup_host to 'discourse_9ootw-postgresql' in Discourse configuration
discourse 05:58:05.36 DEBUG ==> Setting db_backup_port to '5432' in Discourse configuration
discourse 05:58:05.37 DEBUG ==> Setting redis_host to 'discourse_9ootw-redis' in Discourse configuration
discourse 05:58:05.37 DEBUG ==> Setting redis_port to '6379' in Discourse configuration
discourse 05:58:05.37 DEBUG ==> Setting redis_password to '' in Discourse configuration
discourse 05:58:05.38 INFO  ==> Enabling SMTP
discourse 05:58:05.38 DEBUG ==> Setting smtp_address to 'smtp.gmail.com' in Discourse configuration
discourse 05:58:05.38 DEBUG ==> Setting smtp_port to '587' in Discourse configuration
discourse 05:58:05.39 DEBUG ==> Setting smtp_user_name to 'your_email@gmail.com' in Discourse configuration
discourse 05:58:05.40 DEBUG ==> Setting smtp_password to 'your_password' in Discourse configuration
discourse 05:58:05.40 DEBUG ==> Setting smtp_enable_start_tls to 'true' in Discourse configuration
discourse 05:58:05.41 DEBUG ==> Setting smtp_authentication to 'login' in Discourse configuration
discourse 05:58:05.45 INFO  ==> Restoring persisted Discourse installation
discourse 05:58:05.56 INFO  ==> Trying to connect to the database server
 ?column? 
----------

1
(1 row)
discourse 05:58:05.58 INFO  ==> Running database migrations
discourse 05:58:11.99 INFO  ==> Precompiling assets, this may take some time...
node:internal/modules/cjs/loader:1143

  throw err;
  ^
Error: Cannot find module './lib/corepack.cjs'
Require stack:
- /opt/bitnami/node/lib/node_modules/yarn/yarn.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/yarn/yarn.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/bitnami/node/lib/node_modules/yarn/yarn.js' ]
}
Node.js v18.20.4
```
