### ISSUE TITLE
[bitnami/etcd] bug: healthcheck will failed when startup etcd with one-way tls authentication

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/containers#70554]
### Name and Version

bitnami/etcd: 3.5.15

### What architecture are you using?

None

### What steps will reproduce the bug?

1. container.env
```
ALLOW_NONE_AUTHENTICATION = "yes"
ETCD_LISTEN_CLIENT_URLS = "https://0.0.0.0:2379"
ETCD_ADVERTISE_CLIENT_URLS = "https://etcd:2379"
ETCD_CERT_FILE = "/certs/tls.crt"
ETCD_KEY_FILE = "/certs/tls.key"
```
2. compose.yaml
```yaml
services:
  etcd:
    image: docker.io/bitnami/etcd:3.5.15`
    restart: unless-stopped
    env_file: ./container.env
    #ports: [2379,2380]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    volumes:
      - etcd_data:/bitnami/etcd/data
      - ./certs:/certs
```
3. startup etcd and go into the container
4. run /opt/bitnami/scripts/etcd/healthcheck.sh will fail
![image](https://github.com/user-attachments/assets/b45e3fb9-ce6d-4d96-a903-bafc20f27898)

### What is the expected behavior?

healthcheck.sh should still succeed when startup etcd with one-way tls authentication

### What do you see instead?

/opt/bitnami/scripts/etcd/healthcheck.sh failed

### Additional information

1. when startup etcd with two-way tls authentication, healthcheck.sh no problem
container.env
```
ALLOW_NONE_AUTHENTICATION = "yes"
ETCD_LISTEN_CLIENT_URLS = "https://0.0.0.0:2379"
ETCD_ADVERTISE_CLIENT_URLS = "https://etcd:2379"
ETCD_CERT_FILE = "/certs/tls.crt"
ETCD_KEY_FILE = "/certs/tls.key"
ETCD_TRUSTED_CA_FILE = "/certs/ca.crt"
```
2. but when startup ectd with one-way tls authentication, healthcheck.sh will fail
as not configured ETCD_TRUSTED_CA_FILE, so when running healthcheck.sh, this script runs as a client to connect the etcd server, if not skip the tls verification, and it will try to find a CA file to verify the server certs, but now there is no such CA file, so will fail
3. just need to allow healthcheck.sh always skip tls verify, modify libetcd.sh like 
![image](https://github.com/user-attachments/assets/4b00e854-b2ec-4c09-a55d-3a025a3bcda7)
as when running script healthcheck.sh, it just runs as a client, so we should allow it to skip tls verification

4. related bitnami/etcd helm chart issue: https://github.com/bitnami/charts/issues/27109
