### ISSUE TITLE
rm: cannot remove '/opt/bitnami/suitecrm/public/legacy/Api/V8/OAuth2/public.key': Device or resource busy

### ISSUE THREAD

**Issue by TomCalde** [bitnami/containers#70592]
### Name and Version

bitnami/suitecrm:8.6

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm using Docker Compose to run bitnami/suitecrm:8.6:

```yaml
services:
  suitecrm:
    <<: *suitecrm_base
    ports:
      - '${SUITECRM_HOST_PORT:-10080}:${SUITECRM_GUEST_PORT:-8080}'
    environment:
      BITNAMI_DEBUG: true
      SUITECRM_DATABASE_HOST: ${SUITECRM_DATABASE_HOST}
      SUITECRM_DATABASE_PORT_NUMBER: ${SUITECRM_DATABASE_PORT_NUMBER}
      SUITECRM_DATABASE_USER: ${STACK_ROOT_USER}
      SUITECRM_DATABASE_NAME: ${SUITECRM_DATABASE_NAME}
      SUITECRM_DATABASE_PASSWORD: ${STACK_ROOT_PASSPHRASE}
    volumes:
      - ./config/suitecrm/private.key:/bitnami/suitecrm/public/legacy/Api/V8/OAuth2/private.key
      - ./config/suitecrm/public.key:/bitnami/suitecrm/public/legacy/Api/V8/OAuth2/public.key
```
      

### What do you see instead?

I'm receiving the following error: rm: cannot remove '/opt/bitnami/suitecrm/public/legacy/Api/V8/OAuth2/private.key': Device or resource busy and rm: cannot remove '/opt/bitnami/suitecrm/public/legacy/Api/V8/OAuth2/public.key': Device or resource busy

![image](https://github.com/user-attachments/assets/a82d25cd-ac3b-4f25-92ae-858312a6accb)
