### ISSUE TITLE
[bitnami/phpbb] Failed to install phpBB 3.3.12

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [bitnami/containers#70601]
### Name and Version

bitnami/phpbb 3.3.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Here's my `docker-compose.yml`

```yaml
services:

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: mariadb-phpbb-test
    restart: unless-stopped
    environment:
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=$MARIADB_DATABASE
    volumes:
      - '/path/to/mariadb:/bitnami/mariadb'

  phpbb:
    image: docker.io/bitnami/phpbb:3
    container_name: phpbb-test
    restart: unless-stopped
    ports:
      - '9080:8080'
      - '9443:8443'
    environment:
      ## phpBB Site Configuration
      - PHPBB_USERNAME=$PHPBB_USERNAME
      - PHPBB_PASSWORD=$PHPBB_PASSWORD
      ## Database Configuration
      - PHPBB_DATABASE_HOST=mariadb
      - PHPBB_DATABASE_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=$MARIADB_USER
      - PHPBB_DATABASE_PASSWORD=$MARIADB_PASSWORD
      - PHPBB_DATABASE_NAME=$MARIADB_DATABASE
      ## SMTP Configuration
      - PHPBB_SMTP_HOST=$PHPBB_SMTP_HOST
      - PHPBB_SMTP_PORT=$PHPBB_SMTP_PORT
      - PHPBB_SMTP_USER=$PHPBB_SMTP_USER
      - PHPBB_SMTP_PASSWORD=$PHPBB_SMTP_PASSWORD
      - PHPBB_SMTP_PROTOCOL=$PHPBB_SMTP_PROTOCOL
    volumes:
      - '/path/to/phpbb:/bitnami/phpbb'
    depends_on:
      - mariadb
```

Other environment variables are defined in `.env`
Mounted volumes have UID of `1001` and `rwx` permission both for mariadb and phpbb

### What do you see instead?

Here's the log message

```
phpbb-test  | phpbb 08:25:11.42 INFO  ==>
phpbb-test  | phpbb 08:25:11.42 INFO  ==> Welcome to the Bitnami phpbb container
phpbb-test  | phpbb 08:25:11.42 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
phpbb-test  | phpbb 08:25:11.42 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
phpbb-test  | phpbb 08:25:11.42 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
phpbb-test  | phpbb 08:25:11.42 INFO  ==>
phpbb-test  | phpbb 08:25:11.43 INFO  ==> ** Starting phpBB setup **
phpbb-test  | phpbb 08:25:11.44 INFO  ==> Generating sample certificates
phpbb-test  | Certificate request self-signature ok
phpbb-test  | subject=CN = example.com
phpbb-test  | realpath: /bitnami/apache/conf: No such file or directory
phpbb-test  | phpbb 08:25:13.30 INFO  ==> Configuring Apache ServerTokens directive
phpbb-test  | phpbb 08:25:13.31 INFO  ==> Configuring PHP options
phpbb-test  | phpbb 08:25:13.31 INFO  ==> Setting PHP expose_php option
phpbb-test  | phpbb 08:25:13.32 INFO  ==> Setting PHP output_buffering option
phpbb-test  | phpbb 08:25:13.33 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
phpbb-test  | phpbb 08:25:13.37 INFO  ==> Ensuring phpBB directories exist
phpbb-test  | phpbb 08:25:13.37 INFO  ==> Trying to connect to the database server
phpbb-test  | phpbb 08:25:13.38 INFO  ==> Creating configuration file for installation
phpbb-test  | phpbb 08:25:13.76 INFO  ==> Configuring SMTP credentials
phpbb-test  | phpbb 08:25:13.90 INFO  ==> Starting apache in background
phpbb-test  | phpbb 08:25:18.97 INFO  ==> apache started
phpbb-test  | phpbb 08:25:18.97 INFO  ==> Running installation wizard
phpbb-test  | phpbb 08:30:18.57 ERROR ==> phpBB failed to install
phpbb-test  | phpbb 08:30:18.57 INFO  ==> Stopping apache
phpbb-test  | phpbb 08:30:19.59 INFO  ==> apache stopped
phpbb-test  | phpbb 08:30:19.59 INFO  ==> Persisting phpBB installation
phpbb-test  | phpbb 08:30:19.74 INFO  ==> Removing installation files
phpbb-test  | phpbb 08:30:19.75 INFO  ==> ** phpBB setup finished! **
phpbb-test  |
phpbb-test  | phpbb 08:30:19.76 INFO  ==> ** Starting Apache **
phpbb-test  | [Tue Aug 06 08:30:19.817890 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Unix) OpenSSL/3.0.13 configured -- resuming normal operations
phpbb-test  | [Tue Aug 06 08:30:19.817921 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

log says it failed to install phpBB but gives no further information. Is there any debug setting that I can set to gather more information?
```
phpbb-test  | phpbb 08:30:18.57 ERROR ==> phpBB failed to install`
```

### Additional information

https://github.com/bitnami/containers/issues/46587 describes similar problem as mine

EDIT 2024-08-07
I have another phpBB instance running on the same machine with same configuration except the ports. I created an instance on another machine and it works. I don't see why having two instances on the same machine doesn't work though.
