### ISSUE TITLE
[bitnami/postgresql-repmgr] Follower is not using currect primary port for `basebackup` 

### ISSUE THREAD

**Issue by mhkarimi1383** [bitnami/containers#70877]
### Name and Version

bitnami/postgresql-repmgr:16.4.0-debian-12-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set envs like below

    ```yaml
      POSTGRESQL_PORT_NUMBER: 44817
      POSTGRESQL_MASTER_PORT_NUMBER: 44817
      REPMGR_PORT_NUMBER: 44817
      REPMGR_PRIMARY_PORT: 44817
    ```
2. Set `network_mode` to `host`
3. Configure docker compose on 3 different nodes
4. Run `docker compose up -d`

### What is the expected behavior?

Use correct port number

### What do you see instead?

Using wrong port number (`5432`)

By setting `BITNAMI_DEBUG=true` you will notice the problem

### Additional information

Also I can Confirm that `16.1.0-debian-11-r11` is ok I think something is wrong with repmgr version `5.4`
