### ISSUE TITLE
[bitnami/java] Default work directory is /, not /app

### ISSUE THREAD

**Issue by 9t8** [bitnami/containers#70899]
### Name and Version

bitnami/java:11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker-compose.yml`:
```yml
services:
  java:
    image: bitnami/java:11
    command: "pwd"
    volumes:
      - .:/app
```

### What is the expected behavior?

```
java_1  | /app
```

### What do you see instead?

```
java_1  | /
```
