### ISSUE TITLE
Taskmanager cannot connect Jobmanager 

### ISSUE THREAD

**Issue by Splatoon3-bing** [bitnami/containers#71057]
### Name and Version

bitnami/flink:1.17.1

### What is the problem this feature will solve?

cluster-standalone used to test the local job in distribute

### What is the feature you are proposing to solve the problem?

actually, i don't know, 

### What alternatives have you considered?

This is my docker-compose.yml :

services:
  jobmanager:
    image: bitnami/flink:1.17.1
    ports:
      - "8081:8081"# 映射8081端口，以便可以从宿主机访问JobManager的Web UI
      - "6123:6123"
    environment:
      FLINK_MODE: jobmanager
      FLINK_PROPERTIES: "rest.bind-address: 0.0.0.0"
    networks:
      flink-net:
        ipv4_address: 192.168.10.101

  taskmanager:
    image: bitnami/flink:1.17.1
    ports:
      - "6121:6121"
      - "6122:6122"
      - "22:22"
    environment:
      FLINK_MODE: taskmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: 192.168.10.101
        rest.bind-address: 0.0.0.0

    networks:
      flink-net:
        ipv4_address: 192.168.10.102

networks:
  flink-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24 # use docker-compose up -d to run the container cluster

**Comment by Horstage** [comment]
Setting the bind-host to 0.0.0.0 worked for me.

```yaml
services:
  flink-jobmanager:
    image: bitnami/flink:1.17.1
    ports:
      - "8081:8081"
    expose:
      - "6123"
    environment:
      FLINK_MODE: jobmanager
      FLINK_CFG_REST_PORT: 8081
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        rest.bind-address: 0.0.0.0
        jobmanager.bind-host: 0.0.0.0
  
  flink-taskmanager:
    image: bitnami/flink:1.17.1
    depends_on:
      - flink-jobmanager
    environment:
      FLINK_MODE: taskmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.bind-host: 0.0.0.0
```
I'm just learning Flink but haven't seen this in any tutorial so far...
