### ISSUE TITLE
[bitnami/postgrest] Postgrest container not connecting to DB with correctly set DB_* env variables

### ISSUE THREAD

**Issue by Kerruba** [bitnami/containers#71678]
### Name and Version

bitnami/potgrest:latest ([11.2.2](https://hub.docker.com/layers/bitnami/postgrest/11.2.2/images/sha256-f5b8d9b7177cf1378db5739e1ccc79dc91a5e3da3889a84cac9038dd05170d37?context=explore))

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I'm deploying the latest potgrest image in Kubernetes using this manifest for testing purposes:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: bitnami/postgrest:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: my-postgres.databases.svc.cluster.local
            - name: DB_NAME
              value: mydb
            - name: DB_PASSWORD
              value: *****
```
Postgres is up and running and exposed via a service in the same namespace as PostgREST, and I'm able to access it with regular psql within k8s and also from my local machine by portforwarding the port 5432.

When the Pod starts, it tells me is not able to connect to the database:
```
{"code":"PGRST000","details":"connection to server on socket \"/var/run/postgresql/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n","hint":null,"message":"Database connection error. Retrying the connection."}
```
2. I attached it to the container and I couldn't find a configuration file for PostgREST, so I created one using the example configuration found on their site and started postgrest with that configuration, and it worked.

3. Checking the README, I've tried to manually add the `PGRST_DB_URI` env variable to the deployment 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: bitnami/postgrest:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: my-postgres.databases.svc.cluster.local
            - name: DB_NAME
              value: mydb
            - name: DB_PASSWORD
              value: *****
            - name: PGRST_DB_URI
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)
```
The container is now starting correctly and the application can connect to the database.

### What is the expected behavior?

By using the env variables listed in the README.md as customizable I would be able to connect to the database correctly

### What do you see instead?

I get the connection error
```
{"code":"PGRST000","details":"connection to server on socket \"/var/run/postgresql/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n","hint":null,"message":"Database connection error. Retrying the connection."}
```
and the only way of fixing this is by using the `PGRST_DB_URI` which I thought was read-only and not supposed to be changed
