### ISSUE TITLE
[Discourse] How to execute with persistent data

### ISSUE THREAD

**Issue by audricd** [bitnami/containers#71730]
### Describe your issue as much as you can

I am (trying) to follow the steps here: https://hub.docker.com/r/bitnami/discourse (with persistent image steps) but unfortunately the website is not showing me anything at all [enter image description here](https://i.sstatic.net/vDDqvao7.png)

The exact steps I have followed are:
- I created a docker-compose.yml as such: [enter image description here](https://i.sstatic.net/eqT9AxvI.png)
- create network [enter image description here](https://i.sstatic.net/2fxlOYPM.png)
- create and run volumes [enter image description here](https://i.sstatic.net/MBf8kZjp.png)
- docker compose up -d: [enter image description here](https://i.sstatic.net/8Pw4MoTK.png)

I was expecting to see the Discourse interface at that URL

(cross-post with https://stackoverflow.com/staging-ground/78927380)

**Comment by gongomgra** [comment]
Hi @audricd,

thanks for using Bitnami. Can you share the `docker-compose` file you used in plain text? Use three backsticks to surround it for highlighting

-> three backsticks
your docker-compose file
-> three backsticks

Discourse takes a bit to start. Did you see any error when running `docker-compose logs -f`? 

In case you are sharing more images, please paste them directly in your message instead of adding links to external services so it is easier to check them and also they will be kept in your message for the future.

**Comment by audricd** [comment]
Hello @gongomgra , thank you very much for your reply.

Absolutely, here is my docker-compose:


```
audricd@fedifrikis01:~$ cat docker-compose.yml
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - '/home/audricd/postgresql:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=xxxxxxxxxx
      - POSTGRESQL_DATABASE=xxxxxxxxx
  redis:
    image: docker.io/bitnami/redis:7.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/audricd/redis:/bitnami/redis'
  discourse:
    image: docker.io/bitnami/discourse:3
    ports:
      - '80:3000'
    volumes:
      - '/home/audricd/discourse:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - DISCOURSE_HOST=xxxxxxx
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=xxxxxx
      - DISCOURSE_DATABASE_NAME=xxxxx
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=xxxxxxx
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=xxxxxxxx
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - DISCOURSE_SMTP_HOST=xxxxxxx
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=xxxxxxx
      - DISCOURSE_SMTP_PASSWORD=xxxxxxx
      - DISCOURSE_SMTP_PROTOCOL=tls
      - DISCOURSE_PASSWORD=xxxxxx
  sidekiq:
    image: docker.io/bitnami/discourse:3
    depends_on:
      - discourse
    volumes:
      - '/home/audricd/discourse:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=xxxxxxxx
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=xxxxxxx
      - DISCOURSE_DATABASE_NAME=xxxxxx
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - DISCOURSE_SMTP_HOST=xxxxxxx
      - DISCOURSE_SMTP_PORT=587
      - DISCOURSE_SMTP_USER=xxxxxxx
      - DISCOURSE_SMTP_PASSWORD=xxxxx
      - DISCOURSE_SMTP_PROTOCOL=tls
#volumes:
#  postgresql_data:
#    driver: local
#  redis_data:
#    driver: local
#  discourse_data:
#    driver: local
#  sidekiq_data:
#    driver: local
```


and docker compose logs -f

```
audricd@fedifrikis01:~$ docker compose logs -f
postgresql-1  | postgresql 09:57:43.06 INFO  ==> 
postgresql-1  | postgresql 09:57:43.07 INFO  ==> Welcome to the Bitnami postgresql container
postgresql-1  | postgresql 09:57:43.08 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-1  | postgresql 09:57:43.08 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-1  | postgresql 09:57:43.08 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql-1  | postgresql 09:57:43.09 INFO  ==> 
postgresql-1  | postgresql 09:57:43.13 INFO  ==> ** Starting PostgreSQL setup **
postgresql-1  | postgresql 09:57:43.17 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-1  | postgresql 09:57:43.18 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
postgresql-1  | postgresql 09:57:43.18 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
postgresql-1  | postgresql 10:33:35.80 INFO  ==> 
postgresql-1  | postgresql 10:33:35.80 INFO  ==> Welcome to the Bitnami postgresql container
postgresql-1  | postgresql 10:33:35.81 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-1  | postgresql 10:33:35.81 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-1  | postgresql 10:33:35.82 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql-1  | postgresql 10:33:35.82 INFO  ==> 
postgresql-1  | postgresql 10:33:35.85 INFO  ==> ** Starting PostgreSQL setup **
postgresql-1  | postgresql 10:33:35.88 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-1  | postgresql 10:33:35.88 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
postgresql-1  | postgresql 10:33:35.89 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
redis-1       | redis 09:57:43.06 INFO  ==> 
redis-1       | redis 09:57:43.07 INFO  ==> Welcome to the Bitnami redis container
redis-1       | redis 09:57:43.08 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis-1       | redis 09:57:43.08 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-1       | redis 09:57:43.08 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
redis-1       | redis 09:57:43.09 INFO  ==> 
redis-1       | redis 09:57:43.10 INFO  ==> ** Starting Redis setup **
redis-1       | redis 09:57:43.13 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis-1       | redis 09:57:43.14 INFO  ==> Initializing Redis
redis-1       | mkdir: cannot create directory '/bitnami/redis/data': Permission denied
redis-1       | redis 10:33:35.78 INFO  ==> 
redis-1       | redis 10:33:35.78 INFO  ==> Welcome to the Bitnami redis container
redis-1       | redis 10:33:35.78 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis-1       | redis 10:33:35.79 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-1       | redis 10:33:35.79 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
redis-1       | redis 10:33:35.80 INFO  ==> 
redis-1       | redis 10:33:35.80 INFO  ==> ** Starting Redis setup **
redis-1       | redis 10:33:35.83 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis-1       | redis 10:33:35.84 INFO  ==> Initializing Redis
redis-1       | mkdir: cannot create directory '/bitnami/redis/data': Permission denied
sidekiq-1     | discourse 10:33:36.37 INFO  ==> 
sidekiq-1     | discourse 10:33:36.37 INFO  ==> Welcome to the Bitnami discourse container
sidekiq-1     | discourse 10:33:36.38 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
sidekiq-1     | discourse 10:33:36.38 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
sidekiq-1     | discourse 10:33:36.38 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
sidekiq-1     | discourse 10:33:36.38 INFO  ==> 
sidekiq-1     | discourse 10:33:36.45 WARN  ==> Hostname postgresql could not be resolved, this could lead to connection issues
sidekiq-1     | discourse 10:33:36.46 WARN  ==> Hostname redis could not be resolved, this could lead to connection issues
sidekiq-1     | discourse 10:33:36.47 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
sidekiq-1     | discourse 10:33:36.47 INFO  ==> Creating Discourse configuration file
sidekiq-1     | discourse 10:33:36.58 INFO  ==> Enabling SMTP
sidekiq-1     | discourse 10:33:36.67 INFO  ==> Ensuring Sidekiq directories exist
sidekiq-1     | discourse 10:33:36.70 INFO  ==> Trying to connect to the database server
sidekiq-1     | discourse 10:34:37.06 ERROR ==> Could not connect to the database
discourse-1   | discourse 09:57:43.41 INFO  ==> 
discourse-1   | discourse 09:57:43.42 INFO  ==> Welcome to the Bitnami discourse container
discourse-1   | discourse 09:57:43.42 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse-1   | discourse 09:57:43.43 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse-1   | discourse 09:57:43.43 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse-1   | discourse 09:57:43.44 INFO  ==> 
discourse-1   | discourse 09:57:43.45 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse-1   | discourse 09:57:43.45 ERROR ==> The POSTGRESQL_CLIENT_POSTGRES_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
discourse-1   | discourse 10:33:36.11 INFO  ==> 
discourse-1   | discourse 10:33:36.11 INFO  ==> Welcome to the Bitnami discourse container
discourse-1   | discourse 10:33:36.11 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse-1   | discourse 10:33:36.11 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse-1   | discourse 10:33:36.12 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse-1   | discourse 10:33:36.12 INFO  ==> 
discourse-1   | discourse 10:33:36.13 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse-1   | discourse 10:33:36.14 ERROR ==> The POSTGRESQL_CLIENT_POSTGRES_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```
