### ISSUE TITLE
[bitnami/postgresql-repmgr] postgresql-repmgr:16.4.0 modifying the port number does not work in hosts net mode

### ISSUE THREAD

**Issue by jaedenzhu** [bitnami/containers#72051]
### Name and Version

bitnami/postgresql-repmgr:16.4.0

### What architecture are you using?

amd64

### 1. In this compose file
```yaml
services:
  pgsql-2:
    container_name: pgsql-2
    hostname: pgsql-2
    image: bitnami/postgresql-repmgr:16.4.0
    volumes:
      - ./data:/bitnami/postgresql/data
      - ./conf:/bitnami/repmgr/conf
    environment:
      - TZ=Asia/Shanghai
      - POSTGRESQL_POSTGRES_PASSWORD=***
      - POSTGRESQL_USERNAME=zdsz
      - POSTGRESQL_PASSWORD=***
      - POSTGRESQL_DATABASE=yzl
      - POSTGRESQL_PORT_NUMBER=5431
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=***
      - REPMGR_PORT_NUMBER=5431
      - REPMGR_PRIMARY_HOST=pgsql-1
      - REPMGR_PRIMARY_PORT=5431
      - REPMGR_PARTNER_NODES=pgsql-1:5431,pgsql-2:5431
      - REPMGR_NODE_NAME=pgsql-2
      - REPMGR_NODE_NETWORK_NAME=pgsql-2
      - BITNAMI_DEBUG=true
    extra_hosts:
      - "pgsql-1:100.100.128.11"
      - "pgsql-2:100.100.128.12"
    restart: always
    network_mode: host
    command: bash -c 'rm -rf /tmp/repmgrd.pid && /opt/bitnami/scripts/postgresql-repmgr/run.sh'
```
### 2. output log
there's another node named pgsql-1 running, then up this node...
```sh
pgsql-2  | postgresql-repmgr 22:28:58.35 INFO  ==> 
pgsql-2  | postgresql-repmgr 22:28:58.35 INFO  ==> Welcome to the Bitnami postgresql-repmgr container
pgsql-2  | postgresql-repmgr 22:28:58.35 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
pgsql-2  | postgresql-repmgr 22:28:58.36 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgsql-2  | postgresql-repmgr 22:28:58.36 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
pgsql-2  | postgresql-repmgr 22:28:58.36 INFO  ==> 
pgsql-2  | postgresql-repmgr 22:28:58.36 DEBUG ==> Copying files from /opt/bitnami/postgresql/conf.default to /opt/bitnami/postgresql/conf
pgsql-2  | postgresql-repmgr 22:28:58.36 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
pgsql-2  | postgresql-repmgr 22:28:58.37 INFO  ==> Validating settings in REPMGR_* env vars...
pgsql-2  | postgresql-repmgr 22:28:58.38 INFO  ==> Validating settings in POSTGRESQL_* env vars..
pgsql-2  | postgresql-repmgr 22:28:58.38 INFO  ==> Querying all partner nodes for common upstream node...
pgsql-2  | postgresql-repmgr 22:28:58.38 DEBUG ==> Checking node 'pgsql-1:5431'...
pgsql-2  | postgresql-repmgr 22:28:58.41 DEBUG ==> Pretending primary role node - 'pgsql-1:5431'
pgsql-2  | postgresql-repmgr 22:28:58.41 DEBUG ==> Pretending primary set to 'pgsql-1:5431'!
pgsql-2  | postgresql-repmgr 22:28:58.41 DEBUG ==> Checking node 'pgsql-2:5431'...
pgsql-2  | psql: error: connection to server at "pgsql-2" (100.100.128.12), port 5431 failed: Connection refused
pgsql-2  | 	Is the server running on that host and accepting TCP/IP connections?
pgsql-2  | postgresql-repmgr 22:28:58.41 DEBUG ==> Skipping: failed to get primary from the node 'pgsql-2:5431'!
pgsql-2  | postgresql-repmgr 22:28:58.41 INFO  ==> Auto-detected primary node: 'pgsql-1:5431'
pgsql-2  | postgresql-repmgr 22:28:58.42 DEBUG ==> Primary node: 'pgsql-1:5431'
pgsql-2  | postgresql-repmgr 22:28:58.42 INFO  ==> Node configured as standby
pgsql-2  | postgresql-repmgr 22:28:58.42 INFO  ==> Preparing PostgreSQL configuration...
pgsql-2  | postgresql-repmgr 22:28:58.42 DEBUG ==> User injected custom configuration detected!
pgsql-2  | postgresql-repmgr 22:28:58.42 DEBUG ==> Injecting a new pg_hba.conf file...
pgsql-2  | postgresql-repmgr 22:28:58.43 INFO  ==> Preparing repmgr configuration...
pgsql-2  | postgresql-repmgr 22:28:58.43 DEBUG ==> Node ID: '1002', Rol: 'standby', Primary Node: 'pgsql-1:5431'
pgsql-2  | postgresql-repmgr 22:28:58.43 INFO  ==> Initializing Repmgr...
pgsql-2  | postgresql-repmgr 22:28:58.43 INFO  ==> Waiting for primary node...
pgsql-2  | postgresql-repmgr 22:28:58.44 DEBUG ==> Wait for schema repmgr.repmgr on 'pgsql-1:5431', will try 6 times with 10 delay seconds (TIMEOUT=60)
pgsql-2  | postgresql-repmgr 22:28:58.45 DEBUG ==> Schema repmgr.repmgr exists!
pgsql-2  | postgresql-repmgr 22:28:58.45 INFO  ==> Rejoining node...
pgsql-2  | postgresql-repmgr 22:28:58.45 INFO  ==> Cloning data from primary node...
pgsql-2  | WARNING: following problems with command line parameters detected:
pgsql-2  |   -D/--pgdata will be ignored if a repmgr configuration file is provided
pgsql-2  | NOTICE: destination directory "/bitnami/postgresql/data" provided
pgsql-2  | NOTICE: checking for available walsenders on the source node (2 required)
pgsql-2  | NOTICE: checking replication connections can be made to the source server (2 required)
pgsql-2  | WARNING: data checksums are not enabled and "wal_log_hints" is "off"
pgsql-2  | DETAIL: pg_rewind requires "wal_log_hints" to be enabled
pgsql-2  | NOTICE: starting backup (using pg_basebackup)...
pgsql-2  | pg_basebackup: error: connection to server at "pgsql-1" (100.100.128.11), port 5432 failed: Connection refused
pgsql-2  | 	Is the server running on that host and accepting TCP/IP connections?
pgsql-2  | NOTICE: replication slot "repmgr_slot_1002" deleted on node -1
pgsql-2  | ERROR: unable to take a base backup of the source server
pgsql-2  | HINT: data directory ("/bitnami/postgresql/data") may need to be cleaned up manually
pgsql-2 exited with code 14
```
### 3.find out the bug
it seems pg_basebackup runed a restore progarm but use wrong port 5432.
and in my compose file env, i use port 5431, but it doesn't work

### What is the expected behavior?

two nodes are running master-slave replication healthy

### What do you see instead?

```sh
pg_basebackup: error: connection to server at "pgsql-1" (100.100.128.11), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```
