### ISSUE TITLE
[bitnami/discourse] docker.io/bitnami/discourse  gets stuck on the connecting to db phase

### ISSUE THREAD

**Issue by tp1050** [bitnami/containers#72338]
### Name and Version

docker.io/bitnami/discourse:lsest

### What architecture are you using?

None

### What steps will reproduce the bug?

1.
   1.1 Linux 6.8.0-41-generic #41-Ubuntu GNU/Linux
   1.2  Docker version 27.2.0, build 3ab4256
   1.3 I run npm, wordpress etc all some dockerized some not all using the mariadb and redis containers attached to a shared network iso_out and iso_in
 
2. this is the docker-compose
   version: '3'
```
services:
  frm:
    image: docker.io/bitnami/discourse
    ports:
      - "55080:80"
      - "55443:443"
      - "53000:3000"
    environment:
      - DISCOURSE_ENABLE_HTTPS=yes
      - DISCOURSE_HOST=frm
      - DISCOURSE_DEVELOPER_EMAILS=your_email@example.com
      - DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER=80
      - DISCOURSE_EXTERNAL_HTTPS_PORT_NUMBER=443


      - DISCOURSE_REDIS_HOST=redis_1
      - DISCOURSE_REDIS_USERNAME=discourse1
      - DISCOURSE_REDIS_PASSWORD=password

      - DISCOURSE_DATABASE_HOST=mariadb_1
      - DISCOURSE_DATABASE_NAME=discourse1
      - DISCOURSE_DATABASE_USERNAME=discourse1
      - DISCOURSE_DATABASE_PASSWORD=password
      - DISCOURSE_DATABASE_PORT_NUMBER=3306

      - DISCOURSE_USERNAME=discourse1
      - DISCOURSE_USER_PASSWORD=password

      - PGID=1000
      - UID=1000
    volumes:
      - discourse-data:/var/www/discourse
      - discourse-logs:/var/log/discourse
    networks:
      - iso_in
      - iso_out

volumes:
  discourse-data:
  discourse-logs:

networks:
  iso_in:
    external: true
  iso_out:
    external: true
```

### What is the expected behavior?

docker-compose up -d  should just fire things up without an issue, since every component works on its own.

### What do you see instead?
```
discourse 09:52:07.16 INFO  ==> 
discourse 09:52:07.16 INFO  ==> Welcome to the Bitnami discourse container
discourse 09:52:07.16 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 09:52:07.17 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 09:52:07.17 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 09:52:07.17 INFO  ==> 
discourse 09:52:07.17 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 09:52:07.19 INFO  ==> Creating Discourse configuration file
discourse 09:52:07.21 INFO  ==> Ensuring Discourse directories exist
discourse 09:52:07.21 INFO  ==> Trying to connect to the database server
discourse 09:53:07.28 ERROR ==> Could not connect to the database
```
