### ISSUE TITLE
 No Authorizer is configured issue 

### ISSUE THREAD

**Issue by ariyaee1367** [bitnami/containers#72449]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I want active acl on my kafka cluster, but I have No Authorizer is configured error 

### What is the expected behavior?

I can write acl without error. 

### What do you see instead?

 No Authorizer is configured...

### Additional information

Here is my docker-compose. What's to do for active acl in my Kafka container? 
```yaml
version: '3'

services:
  kafka:
    image: 'bitnami/kafka'
    container_name: kafka
    network_mode: host
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181,CLIENT://0.0.0.0:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
      - KAFKA_CFG_AUTHORIZER_CLASS=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      - KAFKA_SUPER_USERS=User:admin
        # - KAFKA_JAAS_CONFIG=file:/opt/bitnami/kafka/config/kafka_jaas.conf
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN ##
      - KAFKA_LOG4J_LOGGERS=org.apache.kafka=DEBUG,org.apache.zookeeper=DEBUG
    volumes:
      - ./kafka:/opt/bitnami/
```
