### ISSUE TITLE
add healthcheck to postgres 

### ISSUE THREAD

**Issue by olivierdalang** [bitnami/containers#72745]
### Name and Version

bitnami/postgresql:15 (and of course other versions too)

### What is the problem this feature will solve?

Making sure the postgres container is properly started before other services relying on it start by making it possible to use the depends_on/condition/service_healthy directive in docker-compose

### What is the feature you are proposing to solve the problem?

Adding HEALTHCHECK directives in the dockerfile with some reasonable defaults.
Here I use something like this (docker-compose):
```yaml
services:
  ...
  postgres:
    image: bitnami/postgresql:15
    ...
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 6
      start_period: 1s
```

### What alternatives have you considered?

Adding them manually in my docker-compose / kubernetes configs - of course doable
