### ISSUE TITLE
Install script crash with MOODLE_USERNAME and MOODLE_PASSWORD set

### ISSUE THREAD

**Issue by celliern** [bitnami/containers#72747]
### Name and Version

docker.io/bitnami/moodle:4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

with the following compose file :

```yaml
name: "moodle"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - "mariadb_data:/bitnami/mariadb"
  moodle:
    image: docker.io/bitnami/moodle:4.4
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin

    volumes:
      - "moodle_data:/bitnami/moodle"
      - "moodledata_data:/bitnami/moodledata"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

The moodle container exit on the "Running Moodle install script" step, but removing the two lines

- MOODLE_USERNAME=admin
- MOODLE_PASSWORD=admin

make it work as expected.

### What is the expected behavior?

The container should run the installation script and then go to the next step (Persisting Moodle installation)

```
moodle-1   | moodle 10:11:22.65 INFO  ==> Running Moodle install script
moodle-1   | moodle 10:12:37.38 INFO  ==> Persisting Moodle installation
moodle-1   | moodle 10:12:47.86 INFO  ==> ** Moodle setup finished! **
moodle-1   | 
moodle-1   | moodle 10:12:47.86 INFO  ==> ** Starting cron **
moodle-1   | moodle 10:12:47.88 INFO  ==> ** Starting Apache **
```

### What do you see instead?

```
moodle-1   | moodle  INFO  ==> Running Moodle install script
moodle-1 exited with code 1
```

**Comment by Otus9051** [comment]
Same issue here. This seems to be a problem with 4.4, 4.3, 4.2.

**Comment by Otus9051** [comment]
Upon enabling BITNAMI_DEBUG variable, it is seen that it corresponds to a database unicode error.

```
Attaching to moodle-1
moodle-1  | moodle 16:54:41.34 INFO  ==> 
moodle-1  | moodle 16:54:41.34 INFO  ==> Welcome to the Bitnami moodle container
moodle-1  | moodle 16:54:41.35 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle-1  | moodle 16:54:41.35 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle-1  | moodle 16:54:41.35 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
moodle-1  | moodle 16:54:41.35 INFO  ==> 
moodle-1  | moodle 16:54:41.35 INFO  ==> ** Starting Moodle setup **
moodle-1  | moodle 16:54:41.38 DEBUG ==> Validating settings in APACHE_* environment variables
moodle-1  | moodle 16:54:41.42 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
moodle-1  | moodle 16:54:41.43 INFO  ==> Generating sample certificates
moodle-1  | Certificate request self-signature ok
moodle-1  | subject=CN = example.com
moodle-1  | realpath: /bitnami/apache/conf: No such file or directory
moodle-1  | moodle 16:54:42.79 INFO  ==> Configuring Apache ServerTokens directive
moodle-1  | moodle 16:54:42.80 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
moodle-1  | moodle 16:54:42.84 INFO  ==> Configuring PHP options
moodle-1  | moodle 16:54:42.85 INFO  ==> Setting PHP expose_php option
moodle-1  | moodle 16:54:42.87 INFO  ==> Setting PHP output_buffering option
moodle-1  | moodle 16:54:42.90 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle-1  | moodle 16:54:42.91 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle-1  | moodle 16:54:42.97 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle-1  | moodle 16:54:43.06 INFO  ==> Ensuring Moodle directories exist
moodle-1  | moodle 16:54:43.09 INFO  ==> Trying to connect to the database server
moodle-1  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle-1  | moodle 16:54:43.12 DEBUG ==> Executing SQL command:
moodle-1  | SELECT 1
moodle-1  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle-1  | 1
moodle-1  | moodle 16:54:43.14 INFO  ==> Running Moodle install script
moodle-1  |                                  .-..-.       
moodle-1  |    _____                         | || |       
moodle-1  |   /____/-.---_  .---.  .---.  .-.| || | .---. 
moodle-1  |   | |  _   _  |/  _  \/  _  \/  _  || |/  __ \
moodle-1  |   * | | | | | || |_| || |_| || |_| || || |___/
moodle-1  |     |_| |_| |_|\_____/\_____/\_____||_|\_____)
moodle-1  | 
moodle-1  | Moodle 4.4.3 (Build: 20240902) command line installation program
moodle-1  | == Environment ==
moodle-1  | !! unicode !!
moodle-1  | [System] must be installed and enabled - It is required that you store all your data in Unicode format (UTF-8). New
moodle-1  | installations must be performed into databases that have their default
moodle-1  | character set as Unicode. If you are upgrading, you should perform the
moodle-1  | UTF-8 migration process (see the Admin page).
moodle-1  | 
moodle-1  | 
moodle-1 exited with code 1
```

The database is however, already unicode.
Upon re-run,

```
Attaching to moodle-1
moodle-1  | moodle 16:55:09.67 INFO  ==> 
moodle-1  | moodle 16:55:09.67 INFO  ==> Welcome to the Bitnami moodle container
moodle-1  | moodle 16:55:09.68 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle-1  | moodle 16:55:09.68 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
moodle-1  | moodle 16:55:09.68 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
moodle-1  | moodle 16:55:09.68 INFO  ==> 
moodle-1  | moodle 16:55:09.68 INFO  ==> ** Starting Moodle setup **
moodle-1  | moodle 16:55:09.71 DEBUG ==> Validating settings in APACHE_* environment variables
moodle-1  | moodle 16:55:09.73 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
moodle-1  | realpath: /bitnami/apache/conf: No such file or directory
moodle-1  | moodle 16:55:09.75 INFO  ==> Configuring Apache ServerTokens directive
moodle-1  | moodle 16:55:09.75 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
moodle-1  | moodle 16:55:09.80 INFO  ==> Configuring PHP options
moodle-1  | moodle 16:55:09.81 INFO  ==> Setting PHP expose_php option
moodle-1  | moodle 16:55:09.83 INFO  ==> Setting PHP output_buffering option
moodle-1  | moodle 16:55:09.86 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle-1  | moodle 16:55:09.87 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle-1  | moodle 16:55:09.93 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle-1  | moodle 16:55:10.03 INFO  ==> Ensuring Moodle directories exist
moodle-1  | moodle 16:55:10.07 INFO  ==> Trying to connect to the database server
moodle-1  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle-1  | moodle 16:55:10.09 DEBUG ==> Executing SQL command:
moodle-1  | SELECT 1
moodle-1  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle-1  | 1
moodle-1  | moodle 16:55:10.11 INFO  ==> Running Moodle install script
moodle-1  | The configuration file config.php already exists. Please use admin/cli/install_database.php to install Moodle for this site.
moodle-1  | 
moodle-1 exited with code 1
```

This is clearly a lack of documentation and maintenance by Bitnami on the Moodle Image.
If you can't do something, leave it be.

**Comment by celliern** [comment]
For the last version we have a moodle running if we remove the variables, that's a bit weird that we have different behavior..
Thank you for the insight on the version number, if we have trouble running the image we will downgrade an older version

**Comment by dgomezleon** [comment]
Hi @celliern ,

The error I can see is:

```
Error, incorrect value "admin" for "adminpass"
```

Using the `docker-compose` below worked for me:

```
name: "moodle"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - BITNAMI_DEBUG=true
    volumes:
      - "mariadb_data:/bitnami/mariadb"
  moodle:
    image: docker.io/bitnami/moodle:4.4
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpass
      - BITNAMI_DEBUG=true
    volumes:
      - "moodle_data:/bitnami/moodle"
      - "moodledata_data:/bitnami/moodledata"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
```

I hope it helps

**Comment by FoxntaU** [comment]
I'm experiencing the same issue on my Windows PC works, but it fails on Ubuntu.  
moodle_1 | moodle 02:36:42.18 INFO ==> Running Moodle install script  
app_moodle_1 exited with code 1.

**Comment by dgomezleon** [comment]
Hi @FoxntaU ,

Could you share how you are executing it? Have you been able to take a look at my last message?

**Comment by alisamie97** [comment]
Hi everyone
I have this docker compose file ready and face the same issue when I run `docker compose up` command

```
services:
  mariadb:
    image: mariadb:11.6.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodle
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    environment:
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 2048K
      PMA_HOST: mariadb
      PMA_USER: moodle
      PMA_PASSWORD: moodle
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - mariadb
  moodle:
    image: bitnami/moodle:4.4.4
    # restart: always
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_DATABASE_NAME: moodle
      MOODLE_USERNAME: moodle
      MOODLE_PASSWORD: moodle
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 8081:80
    depends_on:
      - mariadb
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata

volumes:
  mariadb_data:
```

**Comment by efinal** [comment]
- MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpass

add these two lines make it work

**Comment by kevinveenbirkenbach** [comment]
I still get this error:

```bash
moodle  | moodle 12:09:55.34 INFO  ==> Running Moodle install script
moodle  |                                  .-..-.       
moodle  |    _____                         | || |       
moodle  |   /____/-.---_  .---.  .---.  .-.| || | .---. 
moodle  |   | |  _   _  |/  _  \/  _  \/  _  || |/  __ \
moodle  |   * | | | | | || |_| || |_| || |_| || || |___/
moodle  |     |_| |_| |_|\_____/\_____/\_____||_|\_____)
moodle  | 
moodle  | Moodle 5.0 (Build: 20250414) command line installation program
moodle  | == Environment ==
moodle  | !! unicode !!
moodle  | [System] must be installed and enabled - All data must be stored in Unicode format (UTF-8). For new installations,
moodle  | the database must have UTF-8 as default character set. If you are
moodle  | upgrading, you need to follow the UTF-8 migration process.
moodle  | 
moodle  | 
moodle  | moodle 12:09:56.79 INFO  ==> 
moodle  | moodle 12:09:56.79 INFO  ==> Welcome to the Bitnami moodle container
moodle  | moodle 12:09:56.79 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle  | moodle 12:09:56.80 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
moodle  | moodle 12:09:56.80 INFO  ==> 
moodle  | moodle 12:09:56.81 INFO  ==> ** Starting Moodle setup **
moodle  | moodle 12:09:56.84 DEBUG ==> Validating settings in APACHE_* environment variables
moodle  | moodle 12:09:56.85 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
moodle  | realpath: /bitnami/apache/conf: No such file or directory
moodle  | moodle 12:09:56.86 INFO  ==> Configuring Apache ServerTokens directive
moodle  | moodle 12:09:56.86 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
moodle  | moodle 12:09:56.89 INFO  ==> Configuring PHP options
moodle  | moodle 12:09:56.90 INFO  ==> Setting PHP expose_php option
moodle  | moodle 12:09:56.91 INFO  ==> Setting PHP output_buffering option
moodle  | moodle 12:09:56.94 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle  | moodle 12:09:56.94 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle  | moodle 12:09:56.98 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle  | moodle 12:09:57.03 INFO  ==> Ensuring Moodle directories exist
moodle  | moodle 12:09:57.04 INFO  ==> Trying to connect to the database server
moodle  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle  | moodle 12:09:57.05 DEBUG ==> Executing SQL command:
moodle  | SELECT 1
moodle  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle  | 1
moodle  | moodle 12:09:57.06 INFO  ==> Running Moodle install script
moodle  | The configuration file config.php already exists. Please use admin/cli/install_database.php to install Moodle for this site.
moodle  |
```

It doesn't make a difference if I set

  - MOODLE_USERNAME=admin
  - MOODLE_PASSWORD=adminpass

or not. 

My config:

docker-compose.yml:
``` 
services:

# This template needs to be included in docker-compose.yml, which depend on a mariadb database

  moodle:
    container_name: moodle
    build:
      context: .
      dockerfile: Dockerfile
    image: moodle_custom
    ports:
      - 127.0.0.1:8026:8080
# Base for docker services
    restart: unless-stopped
    env_file:
      - "/opt/docker/moodle/.env/env"
    logging:
      driver: journald


    volumes:
      - 'moodle:/bitnami/moodle'
      - 'data:/bitnami/moodledata'
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET / HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q 'HTTP/1.1'"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      central_mariadb:
      default:


volumes:

  moodle:
  data:

networks:
  central_mariadb:
    external: true
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.102.32/28
```

Dockerfile:
```
FROM bitnami/moodle:latest
```
 .env/env 
```
MOODLE_DATABASE_HOST=central-mariadb
##MOODLE_DATABASE_PORT_NUMBER=3306
MOODLE_DATABASE_USER=moodle
MOODLE_DATABASE_NAME=moodle
MOODLE_DATABASE_PASSWORD=examplepassword
#ALLOW_EMPTY_PASSWORD=no
#MOODLE_SITE_NAME="Global Learning Academy on cymais.cloud"
#MOODLE_SSLPROXY=yes
#MOODLE_REVERSE_PROXY=yes
MOODLE_USERNAME=admin
MOODLE_PASSWORD=adminpass
#MOODLE_EMAIL=administrator@cymais.cloud
BITNAMI_DEBUG=true
#MOODLE_SKIP_INSTALL=true
```

Setup with: 
https://github.com/kevinveenbirkenbach/cymais/tree/master/roles/docker-moodle

I appreciate any help!
