### ISSUE TITLE
Readme on mount custom config is wrong

### ISSUE THREAD

**Issue by manuschillerdev** [bitnami/containers#7306]
### Name and Version

bitnami/mariadb:10

### What steps will reproduce the bug?

Go to https://github.com/bitnami/containers/tree/main/bitnami/mariadb#configuration-file and read how to mount a custom config file.

create a custom conf file `my_custom.cnf`
```
[mysqld]
max_allowed_packet=32M
```

create a `docker-compose.yaml` file:

```yaml
version: "3"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10
    volumes:
      - "mariadb_data:/bitnami/mariadb"
      - ./my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro

    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpass
      - MARIADB_ROOT_PASSWORD=dbrootpass
      - MARIADB_DATABASE=db
    ports:
      - 3306:3306

volumes:
  mariadb_data:
    driver: local
```

run `docker compose up`

### What is the expected behavior?

Expected: I expect the configuration to get respected - or the documentation should be right on the mountable path.

chaning the path to `/bitnami/mariadb/conf/my_custom.cnf:ro` - which apparently gets symlinked to `/bitnami/mariadb/conf/` fixes the issue for me.

```diff
-      - ./my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
+      - ./my_custom.cnf:/bitnami/mariadb/conf/my_custom.cnf:ro
```

### What do you see instead?
```
test-mariadb-1  | Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/mariadb/conf' -> '/opt/bitnami/mariadb/conf'
```
