### ISSUE TITLE
[bitnami/mysql] The mysql container cannot initialize two or more databases when it is started.

### ISSUE THREAD

**Issue by linwanlong** [bitnami/containers#73417]
### Name and Version

bitnami/mysql:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```
mysql:
    image: bitnami/mysql:latest
    environment:
      MYSQL_DATABASE: lwl1,lwl2
```
1. Initializing the database using environment variables failed

### What is the expected behavior?

Multiple initialized databases can be generated through environment variables

### What do you see instead?

![image](https://github.com/user-attachments/assets/149e9738-df9b-4c01-92de-a797e5db5ff9)
Only one database is generated

### Additional information

It is hoped that multiple database libraries can be initialized through environment variables
