### ISSUE TITLE
Redmine README.md ports wrong？

### ISSUE THREAD

**Issue by thomascatlee** [bitnami/containers#74771]
### Name and Version

containers/bitnami/redmine/README.md

### What architecture are you using?

amd64

### What steps will reproduce the bug?

the ports in README are 8080 and 8443, but I could not connect these two ports
```
docker run -d --name redmine \
  **-p 8080:8080 -p 8443:8443** \
  --env ALLOW_EMPTY_PASSWORD=yes \
  --env REDMINE_DATABASE_USER=bn_redmine \
  --env REDMINE_DATABASE_PASSWORD=bitnami \
  --env REDMINE_DATABASE_NAME=bitnami_redmine \
  --network redmine-network \
  --volume redmine_data:/bitnami/redmine \
  bitnami/redmine:latest
```

and in docker-compose.yml the port is 3000
```yaml
 redmine:
    image: docker.io/bitnami/redmine:5
    **ports:
      - '80:3000'**
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
```

### What do you see instead?

Is there something mismatched?
