### ISSUE TITLE
[bitnami/wordpress] wordpress smtp:/usr/sbin/sendmail: not found

### ISSUE THREAD

**Issue by MikeK184** [bitnami/containers#74971]
### Name and Version

 bitnami/wordpress:6.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi, I've deployed WordPress using docker-compose and traefik, end realized that the server can't send emails out. I thought this might be because the default PHP mail function is somehow not allowed in the bitnami package, and even after trying to add AWS SES, within the logs, I receive the same error when trying to send out a testmail `/usr/sbin/sendmail: not found`

This is my docker-compose.yaml:

```yaml
version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
    volumes:
      - mariadb_data:/bitnami/mariadb

  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_USER
      - WORDPRESS_DATABASE_PASSWORD
      - WORDPRESS_DATABASE_NAME
      - WORDPRESS_USERNAME
      - WORDPRESS_PASSWORD
      - WORDPRESS_SMTP_HOST
      - WORDPRESS_SMTP_PORT
      - WORDPRESS_SMTP_USER
      - WORDPRESS_SMTP_PASSWORD
      - WORDPRESS_SMTP_PROTOCOL
    volumes:
      - wordpress_data:/bitnami/wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`XXX`)"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.tls.certresolver=tlsChallenge"

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    container_name: phpmyadmin
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_default
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER
      - PMA_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`XXX`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=https"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=tlsChallenge"
      - "traefik.http.routers.phpmyadmin.middlewares=ipwhitelist@docker"
      - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=XXX/32"

networks:
  traefik_default:
    external: true

volumes:
  mariadb_data:
  wordpress_data:
```

Since I use Portainer to deploy/manage my docker deployments I have it fill out the env variables, but those would be the values I tried to set:

```
WORDPRESS_SMTP_HOST=email-smtp.eu-central-1.amazonaws.com
WORDPRESS_SMTP_PORT=587
WORDPRESS_SMTP_USER=XXX
WORDPRESS_SMTP_PASSWORD=XXX
WORDPRESS_SMTP_PROTOCOL=tls
```

But even before & after adding these env variables, within the container, I see the following error when WordPress is trying to send out a mail: `sh: 1: /usr/sbin/sendmail: not found`

I'm not entirely sure what I can do to debug this further, so any tips would be highly appreciated!

### What do you see instead?

An email is being sent.
