### ISSUE TITLE
Docker image: bitnami/mysql:5.7.43 cannot be started on ARM architecture.

### ISSUE THREAD

**Issue by Ceramist** [bitnami/containers#75212]
### Name and Version

bitnami/mysql:5.7.43

### What architecture are you using?

arm64(Apple M3 Max)

### What steps will reproduce the bug?

Run mysql using the docker compose script: 
```yml
networks:
  choyea:
    external: true
    driver: bridge

services:
  mysql:
    image: bitnami/mysql:5.7.43
    restart: always
    privileged: true
    mem_limit: 1g
    ports:
      - "3306:3306"
    container_name: mysql
    hostname: mysql
    volumes:
      - ./data:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=Choyea@2025
      - TZ=Asia/Shanghai
    networks:
      - choyea
   ```

### What is the expected behavior?

MySQL can run normally without exception.

### What do you see instead?

I noticed that the container keeps restarting, and the following log repeatedly appears in a loop:
```log
mysql 13:04:53.00 
mysql 13:04:53.00 Welcome to the Bitnami mysql container
mysql 13:04:53.00 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 13:04:53.00 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 13:04:53.00 
mysql 13:04:53.00 INFO  ==> ** Starting MySQL setup **
mysql 13:04:53.01 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 13:04:53.02 INFO  ==> Initializing mysql database
mysql 13:04:53.02 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 13:04:53.03 INFO  ==> Setting slow_query_log option
mysql 13:04:53.03 INFO  ==> Setting long_query_time option
mysql 13:04:53.04 INFO  ==> Installing database
/opt/bitnami/scripts/libos.sh: line 346:    43 Killed                  "$@" > /dev/null 2>&1
mysql 13:05:53.73 
mysql 13:05:53.73 Welcome to the Bitnami mysql container
mysql 13:05:53.73 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 13:05:53.74 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 13:05:53.74 
mysql 13:05:53.74 INFO  ==> ** Starting MySQL setup **
mysql 13:05:53.75 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 13:05:53.75 INFO  ==> Initializing mysql database
mysql 13:05:53.75 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 13:05:53.76 INFO  ==> Setting slow_query_log option
mysql 13:05:53.77 INFO  ==> Setting long_query_time option
mysql 13:05:53.77 INFO  ==> Installing database
/opt/bitnami/scripts/libos.sh: line 346:    43 Killed                  "$@" > /dev/null 2>&1
```

### Additional information

I do not understand what is the problem caused by this circular log, hope to get some support, thank you very much
