### ISSUE TITLE
[bitnami/kafka] How to define healthcheck for kafka container

### ISSUE THREAD

**Issue by apachler** [bitnami/containers#75323]
### Name and Version

 bitnami/kafka:3.7

### What is the problem this feature will solve?

I am using 3 instances of Kafka controlled by 3 instances of Zookeeper.

It seems the following healthcheck is not working if used in docker compose.
```yaml
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 30s
```

Since i am not very familiar with Kafka I just wanted to know what healthcheck command should be used.

### What is the feature you are proposing to solve the problem?

Container image maintainers should provide a working healthcheck command.
