### ISSUE TITLE
error while loading shared libraries: libtinfo.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by azicen** [bitnami/containers#75548]
### Name and Version

bitnami/postgresql:17.2.0, bitnami/postgresql-repmgr:17.2.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Encountering an error while starting containers with the following docker compose.

```yaml
services:
  pg-0:
    image: bitnami/postgresql:17.2.0
    # image: bitnami/postgresql-repmgr:17.2.0
    container_name: pg-0
    hostname: pg-0
    environment:
      TZ: Asia/Shanghai
      POSTGRESQL_PASSWORD: custompassword
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_NODE_NETWORK_NAME: pg-0
      REPMGR_NODE_NAME: pg-0
      REPMGR_PARTNER_NODES: pg-0
    ports:
      - 5432:5432
```

### What is the expected behavior?

startup container

### What do you see instead?

When starting the container, it exits immediately with only one line of error.

```console
$ docker logs pg-0
/bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

### Additional information

Tried using bash or sh, but the problem still occurs.
```console
$ docker run --rm -it bitnami/postgresql:17.2.0 /bin/bash
/bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
$ docker run --rm -it bitnami/postgresql:17.2.0 /bin/sh
/bin/bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

`bitnami/minideb:bookworm` available.
```console
$ docker run --rm -it bitnami/minideb:bookworm /bin/bash
$ uname -a
Linux e42d0b4550be 6.6.50-Lemon1151 #1 SMP Sun Sep  8 22:06:39 EDT 2024 aarch64 GNU/Linux
```

docker info:
```console
$ docker info
Client: Docker Engine - Community
 Version:    25.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 27
 Server Version: 25.0.5
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.50-Lemon1151
 Operating System: Armbian 24.11.2 bookworm
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 3.763GiB
 Name: armnas
 ID: 5a2092dd-4e91-4b21-a9f8-6782248247d2
 Docker Root Dir: /srv/dev-disk-by-uuid-*/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  *
 Live Restore Enabled: false
 ```
 
 
Some operating system information.
 ```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Armbian 24.11.2 bookworm
Release:        12
Codename:       bookworm

$ uname -a
Linux armnas 6.6.50-Lemon1151 #1 SMP Sun Sep  8 22:06:39 EDT 2024 aarch64 GNU/Linux

$ lscpu
Architecture:             aarch64
  CPU op-mode(s):         32-bit, 64-bit
  Byte Order:             Little Endian
CPU(s):                   6
  On-line CPU(s) list:    0-5
Vendor ID:                ARM
  Model name:             Cortex-A53
    Model:                4
    Thread(s) per core:   1
    Core(s) per socket:   4
    Socket(s):            1
    Stepping:             r0p4
    CPU(s) scaling MHz:   64%
    CPU max MHz:          1416.0000
    CPU min MHz:          408.0000
    BogoMIPS:             48.00
    Flags:                fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
  Model name:             Cortex-A72
    Model:                2
    Thread(s) per core:   1
    Core(s) per socket:   2
    Socket(s):            1
    Stepping:             r0p2
    CPU(s) scaling MHz:   45%
    CPU max MHz:          1800.0000
    CPU min MHz:          408.0000
    BogoMIPS:             48.00
    Flags:                fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
Caches (sum of all):      
  L1d:                    192 KiB (6 instances)
  L1i:                    224 KiB (6 instances)
  L2:                     1.5 MiB (2 instances)
Vulnerabilities:          
  Gather data sampling:   Not affected
  Itlb multihit:          Not affected
  L1tf:                   Not affected
  Mds:                    Not affected
  Meltdown:               Not affected
  Mmio stale data:        Not affected
  Reg file data sampling: Not affected
  Retbleed:               Not affected
  Spec rstack overflow:   Not affected
  Spec store bypass:      Vulnerable
  Spectre v1:             Mitigation; __user pointer sanitization
  Spectre v2:             Vulnerable
  Srbds:                  Not affected
  Tsx async abort:        Not affected
 ```

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by azicen** [comment]
Recently, upon retrying the use of this container, it was found that by specifying the uid as 0, which means using the root user, the container successfully started.

The following `docker compose` successfully starts the containers.
```yaml
services:
  pg-0:
    image: bitnami/postgresql:17.2.0
    # image: bitnami/postgresql-repmgr:17.2.0
    container_name: pg-0
    hostname: pg-0
    user: 0:0
    environment:
      TZ: Asia/Shanghai
      POSTGRESQL_PASSWORD: custompassword
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: pg-0
      REPMGR_NODE_NETWORK_NAME: pg-0
      REPMGR_NODE_NAME: pg-0
      REPMGR_PARTNER_NODES: pg-0
    ports:
      - 5432:5432
```
