### ISSUE TITLE
Initialisation failure - cannot create directory '/bitnami/openldap/data': Permission denied

### ISSUE THREAD

**Issue by zulu64** [bitnami/containers#75715]
### Name and Version

bitnami/openldap:2.6.9

### What architecture are you using?

amd64

### 1. Environment
```console
$ docker --version
Docker version 27.3.1, build ce12230
```
![image](https://github.com/user-attachments/assets/f3d3101a-59bc-4557-be67-c450cc9f7a3e)
### 2. Configuration:
```yaml
services:

  db:
    container_name: openldap_db
    image: bitnami/openldap:2.6.9
    environment:
      PUID: 1000
      PGID: 1000
      LDAP_PORT_NUMBER: 389
      LDAP_ROOT: dc=my,dc=domain,dc=com
      LDAP_ADMIN_USERNAME: ${OPENLDAP_ADMIN_USER_NAME}
      LDAP_ADMIN_PASSWORD: ${OPENLDAP_ADMIN_USER_PASSWORD}
      LDAP_USERS: user1, user2
      LDAP_PASSWORDS: pass1, pass2
      LDAP_USER_DC: users
      LDAP_GROUP: readers
      LDAP_ADD_SCHEMAS: yes
      LDAP_EXTRA_SCHEMAS: cosine, inetorgperson, nis
      LDAP_SKIP_DEFAULT_TREE: no
      LDAP_ALLOW_ANON_BINDING: no
      LDAP_LOGLEVEL: 256
      LDAP_CONFIGURE_PPOLICY: no
      LDAP_ENABLE_TLS: no
      LDAP_ENABLE_PROXYPROTO: yes
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./.templates/entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "./volumes/openldap/data:/bitnami/openldap"
    restart: unless-stopped
    networks:
      vlan30:
        ipv4_address: 10.10.30.20
      network_be:

networks:
  vlan30:
    external: true
  network_be:
    name: openldap_network_be
```
### 3. Execution:
`$ docker compose up -d`
The execution user is pid 1000, gid 1000. The ownership of folders, and "volumes" in particular, are all CHOWN 1000:1000, and CHMOD 770 at this point in time.
Lastly, the "volumes" and ".templates/entrypoint-initdb.d" folders are empty before execution.

### What is the expected behavior?

Initialization completes without error, and service is available.

### What do you see instead?

The docker log reports:
```
 01:26:03.24 INFO  ==> ** Starting LDAP setup **
 01:26:03.30 INFO  ==> Validating settings in LDAP_* env vars
 01:26:03.31 INFO  ==> Initializing OpenLDAP...
mkdir: cannot create directory '/bitnami/openldap/data': Permission denied
```
