### ISSUE TITLE
postgresql-repmgr exited with code 14

### ISSUE THREAD

**Issue by Luban-Yuumi** [bitnami/containers#75738]
### Name and Version

postgresql-repmgr:17.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```yaml
a nodes:
services:
  pg-0:
    image: 'docker.io/bitnami/postgresql-repmgr:17.2.0'
    network_mode: "host"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=192.168.17.62
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=192.168.17.62:5432,192.168.17.63:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=192.168.17.62
      - REPMGR_PORT_NUMBER=5432


b nodes
services:
  pg-1:
    image: 'docker.io/bitnami/postgresql-repmgr:17.2.0'
    network_mode: "host"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=192.168.17.62
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=192.168.17.62:5432,192.168.17.63:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=192.168.17.63
      - REPMGR_PORT_NUMBER=5432
```
Running docker compose up on node A succeeds, but running the same command on node B results in an error.
exited with code 14

### What do you see instead?

![image](https://github.com/user-attachments/assets/8558bdd5-4788-4c04-b3bc-897560571941)
