### ISSUE TITLE
SSL Configured but not work 

### ISSUE THREAD

**Issue by alirezaalj** [bitnami/containers#75759]
### Name and Version

bitnami/pgpool

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. with this docker compose config :
```
services:
  pg-0:
    image: postgres-repmgr-citus:latest
    ports:
      - 5531:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=citus, pgaudit
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-1,pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgrpassword

      - POSTGRESQL_ENABLE_TLS=yes
      - POSTGRESQL_TLS_CERT_FILE=/opt/bitnami/postgresql/certs/server.crt
      - POSTGRESQL_TLS_KEY_FILE=/opt/bitnami/postgresql/certs/server.key
      # - POSTGRESQL_TLS_CA_FILE=/opt/bitnami/postgresql/ssl/rootCA.crt
    volumes:
      - ./certs/postgresql/certs:/opt/bitnami/postgresql/certs
      - ./certs/ssl/rootCA:/opt/bitnami/postgresql/ssl
      - pg0_data:/bitnami/postgresql

  pg-1:
    image: postgres-repmgr-citus:latest
    ports:
      - 5532:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
     - pg-0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=citus, pgaudit
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=repmgrpassword

      - POSTGRESQL_ENABLE_TLS=yes
      - POSTGRESQL_TLS_CERT_FILE=/opt/bitnami/postgresql/certs/server.crt
      - POSTGRESQL_TLS_KEY_FILE=/opt/bitnami/postgresql/certs/server.key
      # - POSTGRESQL_TLS_CA_FILE=/opt/bitnami/postgresql/ssl/rootCA.crt
    volumes:
      - ./certs/postgresql/certs:/opt/bitnami/postgresql/certs
      - ./certs/ssl/rootCA:/opt/bitnami/postgresql/ssl
      - pg1_data:/bitnami/postgresql

  pgpoolc1:
    image: bitnami/pgpool:latest
    ports:
      - 5441:5432
    depends_on:
      - pg-0
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=repmgr
      - PGPOOL_SR_CHECK_PASSWORD=repmgrpassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=none
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=password
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT=no
      - PGPOOL_ENABLE_LOG_CONNECTIONS=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
      
      - PGPOOL_ENABLE_TLS=yes
      - PGPOOL_TLS_CERT_FILE=/opt/bitnami/pgpool/conf/certs/pgpool.crt
      - PGPOOL_TLS_KEY_FILE=/opt/bitnami/pgpool/conf/certs/pgpool.key
      - PGPOOL_TLS_CA_FILE=/opt/bitnami/pgpool/ssl/rootCA.crt

      - PGPOOL_AUTHENTICATION_METHOD=md5
      - PGPOOL_ENABLE_POOL_PASSWD=no
      - PGPOOL_ENABLE_POOL_HBA=yes
      - PGPOOL_USER_HBA_FILE=/opt/bitnami/pgpool/conf/no_hba.conf
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./no_hba_ssl.conf:/opt/bitnami/pgpool/conf/no_hba.conf
      - ./certs/pgpool/certs:/opt/bitnami/pgpool/conf/certs
      - ./certs/ssl/rootCA:/opt/bitnami/pgpool/ssl


volumes:
  pg0_data:
  pg1_data:
```
  
and pool_hba_ssl.conf

```
local    all             all                            trust
hostssl     all             all             0.0.0.0/0               cert
hostssl     all             all             ::/0                    cert
host     all             repmgr       all         trust
hostssl     all             postgres       all         trust
host     all             all                all         trust
```

iv run and try to connect to pgpool with

```
psql "sslmode=require host=127.0.0.1 port=5441 user=postgres dbname=postgres"
```

i get :

```
psql: error: connection to server at "127.0.0.1", port 5441 failed: server does not support SSL, but SSL was required
```

### What is the expected behavior?

i expect to connect with ssl enabled

like:
```

psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1), server 16.4)
WARNING: psql major version 14, server major version 16.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# 
```

### What do you see instead?

```
psql: error: connection to server at "127.0.0.1", port 5441 failed: server does not support SSL, but SSL was required
```
