### ISSUE TITLE
issue upgrading

### ISSUE THREAD

**Issue by killmasta93** [bitnami/containers#75941]
### Name and Version

bitnami/moodle:4.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Changed the docker file to the new version and ran a `docker build`

### What is the expected behavior?

`moodletest-moodle-1 exited with code 1`

### What do you see instead?

the upgrade 

### Additional information

Hi currently having an issue to upgrade moodle

in theory, just changing the docker file to the new version and re-ran a docker rebuild is not upgrading, 

the docker-compose
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3310:3306'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_PASSWORD=bitnami123
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_PASSWORD=moodle123
      - MARIADB_INNODB_BUFFER_POOL_SIZE=512M
      - MARIADB_MAX_ALLOWED_PACKET=64M
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9088:8080'
    environment:
      - PHP_ENABLE_OPCACHE=yes
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami123
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PASSWORD=redispassword
      - MOODLE_REDIS_PORT=6379
    volumes:
      - 'moodle_data:/bitnami/moodle:cached'
      - 'moodledata_data:/bitnami/moodledata:cached'
    depends_on:
      - mariadb

  redis:
    image: redis:alpine
    command: redis-server --requirepass redispassword
    volumes:
      - 'redis_data:/data'

volumes:
  mariadb_data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi4/moodletest/mariadb_data
  moodle_data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi4/moodletest/moodle_data
  moodledata_data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi4/moodletest/moodledata_data
  redis_data:
    driver: local-persist
    driver_opts:
      mountpoint: /scsi4/moodletest/redis_data
```

the docker file
```dockerfile
# Dockerfile for moodle with php-redis
FROM bitnami/moodle:4.5.1

# Install php-redis
RUN install_packages php-redis
```
