### ISSUE TITLE
No way to detect full initialization of the database, healthcheck.sh always returns code 0

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/containers#76241]
### Name and Version

bitnami/mariadb:10.11

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Run mariadb with a lot of sql files which slow down initialization with a compose file like this : 
```yaml
  db:
    image: bitnami/mariadb:10.11
    environment:
      BITNAMI_DEBUG: true
      ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_SKIP_TEST_DB: "yes"
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: bitnami
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
```

2. we expect the container to be ready only when initialization is completed. In the official mariadb image, initialization of the db is executed with the server running with `--skip-networking` flag. In this case, `healthcheck.sh --connect` fails and the container is not in a ready state.
With the bitnami image, the `--skip-networking` flag is not used, which prevents to detect the full initialization of the database

### What is the expected behavior?

`healthcheck.sh --connect` should allow to detect the full initialization of the database

### What do you see instead?

There is no way to detect the real ready state of the database

### Additional information

If this bug is valid and the proposal to use `--skip-networking` during setup is accepted, I am willing to contribute to this, please tell me.
