### ISSUE TITLE
kafka, SSL handshake failed, No subject alternative DNS name matching [host] found

### ISSUE THREAD

**Issue by realwps** [bitnami/containers#76445]
### Name and Version

bitnami/kafka:3.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Everything works with the `KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=`. But this option is not suitable for me.
Please help me understand why the application is swearing at the SAN

```yaml
services:
  kafka:
    container_name: kkt-prod-kafka.test.ru
    hostname: kkt-prod-kafka.test.ru
    image: bitnami/kafka:3.8.0
    ports:
      - "9092:9092"
    networks:
      - kafka
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=8v1GlhapfX30ZzdN
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kkt-prod-kafka.test.ru:9093
      - KAFKA_CFG_LISTENERS=SASL_SSL://kkt-prod-kafka.test.ru:9092, CONTROLLER://kkt-prod-kafka.test.ru:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://kkt-prod-kafka.test.ru:9092
  #    - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SASL_SSL:SASL_SSL, CONTROLLER:SASL_SSL
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=false
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=keystore_pass
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=trustore_pass
      - KAFKA_CONTROLLER_USER=su-kkt-kafka
      - KAFKA_CONTROLLER_PASSWORD=password
      - KAFKA_INTER_BROKER_USER=su-kkt-kafka
      - KAFKA_INTER_BROKER_PASSWORD=password
      - KAFKA_CFG_SUPER_USERS=User:su-kkt-kafka
#      - KAFKA_CFG_SSL_ENABLED_PROTOCOLS=TLSv1.3
#      - KAFKA_CFG_SSL_PROTOCOL=TLSv1.3
    volumes:
      - ./certs2/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./certs2/client.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      - data:/bitnami/kafka
```

I also attached a piece of keystore `keytool -v -list -keystore kafka.keystore.jks`
```
Keystore type: JKS
Keystore provider: SUN
Your keystore contains 2 entries

Alias name: caroot
Creation date: Jan 20, 2025
Entry type: trustedCertEntry

...

Alias name: myalias
Creation date: Jan 20, 2025
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: EMAILADDRESS=*, CN=kkt-prod-kafka.test.ru, O=*, L=*, ST=*, C=*
Issuer: EMAILADDRESS=*, CN=*, O=*, L=*, ST=*, C=*
...
#7: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: kkt-prod-kafka.test.ru kkt-prod-kafka1.test.ru kkt-prod-kafka2.test.ru kkt-prod-kafka3.test.ru
]
...
```

### What is the expected behavior?

kafka will be launched

### What do you see instead?

```
kkt-prod-kafka.test.ru  | [2025-01-20 16:10:43,380] ERROR [NodeToControllerChannelManager id=1 name=registration] Connection to node 1 (kkt-prod-kafka.test.ru/172.18.0.2:9093) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
kkt-prod-kafka.test.ru  | [2025-01-20 16:10:43,381] ERROR [controller-1-to-controller-registration-channel-manager]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=kafka.server.NodeToControllerRequestThread$$Lambda$750/0x00007bd0b04664c8@e35fd68, destination=1, correlationId=1, clientId=1, createdTimeMs=1737378643135, requestBuilder=ControllerRegistrationRequestData(controllerId=1, incarnationId=XoHvgpjFSQar_t0JHYly-g, zkMigrationReady=false, listeners=[Listener(name='CONTROLLER', host='kkt-prod-kafka.test.ru', port=9093, securityProtocol=3)], features=[Feature(name='metadata.version', minSupportedVersion=1, maxSupportedVersion=20)])) (kafka.server.NodeToControllerRequestThread)
kkt-prod-kafka.test.ru  | [2025-01-20 16:10:43,381] ERROR [controller-1-to-controller-registration-channel-manager]: Request ControllerRegistrationRequestData(controllerId=1, incarnationId=XoHvgpjFSQar_t0JHYly-g, zkMigrationReady=false, listeners=[Listener(name='CONTROLLER', host='kkt-prod-kafka.test.ru', port=9093, securityProtocol=3)], features=[Feature(name='metadata.version', minSupportedVersion=1, maxSupportedVersion=20)]) failed due to authentication error with controller. Disconnecting the connection to the stale controller 1 (kafka.server.NodeToControllerRequestThread)
kkt-prod-kafka.test.ru  | org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
kkt-prod-kafka.test.ru  | Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching kkt-prod-kafka.test.ru found.
```
