### ISSUE TITLE
Unable to setup galera cluster

### ISSUE THREAD

**Issue by darkt2** [bitnami/containers#76459]
### Name and Version

bitname/mariadb-galera

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are using a docker environment to setup a galera cluster with 3 nodes:

The compose file is:
```yaml
services:
  galera1:
    hostname: galera1
    volumes:
      - ./data/galera1:/bitnami/mariadb
    env_file:
      - ./.env
    environment:
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
    image: bitnami/mariadb-galera:latest
    user: root
  galera2:
    hostname: galera2
    volumes:
      - ./data/galera2:/bitnami/mariadb
    env_file:
      - ./.env
    image: bitnami/mariadb-galera:latest
    user: root
  galera3:
    hostname: galera3
    volumes:
      - ./data/galera3:/bitnami/mariadb
    env_file:
      - ./.env
    image: bitnami/mariadb-galera:latest
    user: root
networks: {}
```

and the environment file is:
```
MARIADB_GALERA_CLUSTER_NAME=dockgalera
MARIADB_GALERA_MARIABACKUP_USER=caesar
MARIADB_GALERA_MARIABACKUP_PASSWORD=caesar
MARIADB_ROOT_PASSWORD=caesar
MARIADB_REPLICATION_USER=caesarrep
MARIADB_REPLICATION_PASSWORD=caesar
MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera1,galera2,galera3
```
We start the cluster with `docker compose up`

### What is the expected behavior?

I expected the cluster to start and do a bootstrap from this node

### What do you see instead?

Every time we do a clean startup (all datafiles cleaned) The cluster does not start.
The first node stops to work with the following error:
```
2025-01-21  8:34:21 0 [ERROR] WSREP: It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates. To force cluster bootstrap with this node, edit the grastate.dat file manually and set safe_to_bootstrap to 1 .
2025-01-21  8:34:21 0 [ERROR] WSREP: wsrep::connect(gcomm://) failed: 7
2025-01-21  8:34:21 0 [ERROR] Aborting
```
See attached log file

[galera-galera1-1-2025-01-21T08-34-45.log](https://github.com/user-attachments/files/18487371/galera-galera1-1-2025-01-21T08-34-45.log)

[galera-galera1-1-2025-01-21T08-34-45.log](https://github.com/user-attachments/files/18487427/galera-galera1-1-2025-01-21T08-34-45.log)
