### ISSUE TITLE
[bitnami/valkey-cluster] Cluster Setup Not Completing in valkey-cluster

### ISSUE THREAD

**Issue by tomohirohiratsuka** [bitnami/containers#76523]
### Name and Version

bitnami/valkey-cluster:8.0.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Run the `docker-compose.yml` below
2. Observe the logs of the `valkey-cluster` container. It will indicate that the setup is finished, but the node readiness check keeps running without completing.

```yaml
services:
    valkey-node-0:
    container_name: valkey-node-0
    image: docker.io/bitnami/valkey-cluster
    environment:
      - 'VALKEY_PASSWORD=bitnami'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-cluster'
  valkey-node-1:
    container_name: valkey-node-1
    image: docker.io/bitnami/valkey-cluster
    environment:
      - 'VALKEY_PASSWORD=bitnami'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-cluster'
  valkey-node-2:
    container_name: valkey-node-2
    image: docker.io/bitnami/valkey-cluster
    environment:
      - 'VALKEY_PASSWORD=bitnami'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-cluster'
  valkey-node-3:
    container_name: valkey-node-3
    image: docker.io/bitnami/valkey-cluster
    environment:
      - 'VALKEY_PASSWORD=bitnami'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-cluster'
  valkey-node-4:
    container_name: valkey-node-4
    image: docker.io/bitnami/valkey-cluster
    environment:
      - 'VALKEY_PASSWORD=bitnami'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-cluster'
  valkey-cluster:
    container_name: valkey-cluster
    image: docker.io/bitnami/valkey-cluster
    depends_on:
      - valkey-node-0
      - valkey-node-1
      - valkey-node-2
      - valkey-node-3
      - valkey-node-4
    environment:
      - 'VALKEY_PASSWORD=bitnami'
      - 'VALKEYCLI_AUTH=bitnami'
      - 'VALKEY_CLUSTER_REPLICAS=1'
      - 'VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-cluster'
      - 'VALKEY_CLUSTER_CREATOR=yes'
    ports:
      - "6379:6379"
```

### What is the expected behavior?

I expected the `valkey-cluster` container to finish initializing the cluster and then be ready to accept connections, similar to how `bitnami/redis-cluster` behaves. The cluster should be initialized without waiting indefinitely.

### What do you see instead?

```
valkey-node-1   | valkey-cluster 09:41:19.01 INFO  ==> 
valkey-node-1   | valkey-cluster 09:41:19.01 INFO  ==> Welcome to the Bitnami valkey-cluster container
valkey-node-1   | valkey-cluster 09:41:19.02 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
valkey-node-1   | valkey-cluster 09:41:19.02 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
valkey-node-1   | valkey-cluster 09:41:19.02 INFO  ==> 
valkey-node-1   | valkey-cluster 09:41:19.02 INFO  ==> ** Starting Valkey setup **
valkey-node-0   | valkey-cluster 09:41:19.02 INFO  ==> 
valkey-node-0   | valkey-cluster 09:41:19.02 INFO  ==> Welcome to the Bitnami valkey-cluster container
valkey-node-0   | valkey-cluster 09:41:19.02 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
valkey-node-0   | valkey-cluster 09:41:19.02 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
valkey-node-0   | valkey-cluster 09:41:19.02 INFO  ==> 
valkey-node-0   | valkey-cluster 09:41:19.03 INFO  ==> ** Starting Valkey setup **
valkey-node-4   | valkey-cluster 09:41:19.03 INFO  ==> 
valkey-node-3   | valkey-cluster 09:41:19.03 INFO  ==> 
valkey-node-2   | valkey-cluster 09:41:19.03 INFO  ==> 
valkey-node-2   | valkey-cluster 09:41:19.03 INFO  ==> Welcome to the Bitnami valkey-cluster container
valkey-node-1   | valkey-cluster 09:41:19.03 INFO  ==> Initializing Valkey
valkey-node-4   | valkey-cluster 09:41:19.03 INFO  ==> Welcome to the Bitnami valkey-cluster container
valkey-node-3   | valkey-cluster 09:41:19.03 INFO  ==> Welcome to the Bitnami valkey-cluster container
valkey-node-2   | valkey-cluster 09:41:19.03 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
valkey-node-4   | valkey-cluster 09:41:19.03 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
valkey-node-2   | valkey-cluster 09:41:19.03 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
valkey-node-3   | valkey-cluster 09:41:19.03 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
valkey-node-4   | valkey-cluster 09:41:19.03 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
valkey-node-2   | valkey-cluster 09:41:19.03 INFO  ==> 
valkey-node-3   | valkey-cluster 09:41:19.03 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
valkey-node-3   | valkey-cluster 09:41:19.03 INFO  ==> 
valkey-node-4   | valkey-cluster 09:41:19.03 INFO  ==> 
valkey-node-2   | valkey-cluster 09:41:19.04 INFO  ==> ** Starting Valkey setup **
valkey-node-4   | valkey-cluster 09:41:19.04 INFO  ==> ** Starting Valkey setup **
valkey-node-3   | valkey-cluster 09:41:19.04 INFO  ==> ** Starting Valkey setup **
valkey-node-0   | valkey-cluster 09:41:19.04 INFO  ==> Initializing Valkey
valkey-node-1   | valkey-cluster 09:41:19.05 INFO  ==> Setting Valkey config file
valkey-node-2   | valkey-cluster 09:41:19.05 INFO  ==> Initializing Valkey
valkey-node-4   | valkey-cluster 09:41:19.05 INFO  ==> Initializing Valkey
valkey-node-0   | valkey-cluster 09:41:19.05 INFO  ==> Setting Valkey config file
valkey-node-3   | valkey-cluster 09:41:19.05 INFO  ==> Initializing Valkey
valkey-node-2   | valkey-cluster 09:41:19.06 INFO  ==> Setting Valkey config file
valkey-node-4   | valkey-cluster 09:41:19.06 INFO  ==> Setting Valkey config file
valkey-node-3   | valkey-cluster 09:41:19.06 INFO  ==> Setting Valkey config file
valkey-node-1   | Storing map with hostnames and IPs
valkey-node-0   | Storing map with hostnames and IPs
valkey-node-1   | 
valkey-node-1   | valkey-cluster 09:41:19.11 INFO  ==> ** Valkey setup finished! **
valkey-node-0   | 
valkey-node-0   | valkey-cluster 09:41:19.11 INFO  ==> ** Valkey setup finished! **
valkey-node-2   | Storing map with hostnames and IPs
valkey-node-2   | 
valkey-node-2   | valkey-cluster 09:41:19.12 INFO  ==> ** Valkey setup finished! **
valkey-node-1   | 1:C 24 Jan 2025 09:41:19.129 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
valkey-node-1   | 1:C 24 Jan 2025 09:41:19.129 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
valkey-node-1   | 1:C 24 Jan 2025 09:41:19.129 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=1, just started
valkey-node-1   | 1:C 24 Jan 2025 09:41:19.129 * Configuration loaded
valkey-node-0   | 1:C 24 Jan 2025 09:41:19.130 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.130 * monotonic clock: POSIX clock_gettime
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.130 * Running mode=cluster, port=6379.
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.130 * No cluster configuration found, I'm 579210d2b1dc5a616f847dcc441b152af6d4485d
valkey-node-0   | 1:C 24 Jan 2025 09:41:19.130 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
valkey-node-0   | 1:C 24 Jan 2025 09:41:19.130 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=1, just started
valkey-node-0   | 1:C 24 Jan 2025 09:41:19.130 * Configuration loaded
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.131 * monotonic clock: POSIX clock_gettime
valkey-node-4   | Storing map with hostnames and IPs
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.131 * Running mode=cluster, port=6379.
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.131 * No cluster configuration found, I'm 52bf48a9836a8d5cf64a70c6f7b82280a1b6a456
valkey-node-3   | Storing map with hostnames and IPs
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.133 * Server initialized
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.134 * Server initialized
valkey-node-2   | 1:C 24 Jan 2025 09:41:19.136 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.136 * Creating AOF base file appendonly.aof.1.base.rdb on server start
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.136 * Creating AOF base file appendonly.aof.1.base.rdb on server start
valkey-node-2   | 1:C 24 Jan 2025 09:41:19.137 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
valkey-node-2   | 1:C 24 Jan 2025 09:41:19.137 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=1, just started
valkey-node-2   | 1:C 24 Jan 2025 09:41:19.137 * Configuration loaded
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.137 * monotonic clock: POSIX clock_gettime
valkey-node-4   | 
valkey-node-4   | valkey-cluster 09:41:19.13 INFO  ==> ** Valkey setup finished! **
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.138 * Running mode=cluster, port=6379.
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.138 * No cluster configuration found, I'm e48241d44b8c456602e24ac659d4e73433e2dd72
valkey-node-3   | 
valkey-node-3   | valkey-cluster 09:41:19.13 INFO  ==> ** Valkey setup finished! **
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.140 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
valkey-node-0   | 1:M 24 Jan 2025 09:41:19.140 * Ready to accept connections tcp
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.141 * Server initialized
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.140 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
valkey-node-1   | 1:M 24 Jan 2025 09:41:19.140 * Ready to accept connections tcp
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.142 * Creating AOF base file appendonly.aof.1.base.rdb on server start
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.144 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
valkey-node-2   | 1:M 24 Jan 2025 09:41:19.144 * Ready to accept connections tcp
valkey-cluster  | valkey-cluster 09:41:19.14 INFO  ==> 
valkey-cluster  | valkey-cluster 09:41:19.14 INFO  ==> Welcome to the Bitnami valkey-cluster container
valkey-cluster  | valkey-cluster 09:41:19.14 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
valkey-cluster  | valkey-cluster 09:41:19.14 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
valkey-cluster  | valkey-cluster 09:41:19.14 INFO  ==> 
valkey-cluster  | valkey-cluster 09:41:19.15 INFO  ==> ** Starting Valkey setup **
valkey-node-4   | 1:C 24 Jan 2025 09:41:19.151 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
valkey-node-4   | 1:C 24 Jan 2025 09:41:19.152 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
valkey-node-4   | 1:C 24 Jan 2025 09:41:19.152 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=1, just started
valkey-node-4   | 1:C 24 Jan 2025 09:41:19.152 * Configuration loaded
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.152 * monotonic clock: POSIX clock_gettime
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.153 * Running mode=cluster, port=6379.
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.153 * No cluster configuration found, I'm de41f85bfa15b0f9206725971c7bb438d03f482e
valkey-node-3   | 1:C 24 Jan 2025 09:41:19.153 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
valkey-node-3   | 1:C 24 Jan 2025 09:41:19.153 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
valkey-node-3   | 1:C 24 Jan 2025 09:41:19.153 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=1, just started
valkey-node-3   | 1:C 24 Jan 2025 09:41:19.153 * Configuration loaded
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.154 * monotonic clock: POSIX clock_gettime
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.154 * Running mode=cluster, port=6379.
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.154 * No cluster configuration found, I'm f03475a3f707f9ccdc878133288aebbe24041218
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.154 * Server initialized
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.155 * Creating AOF base file appendonly.aof.1.base.rdb on server start
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.156 * Server initialized
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.156 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
valkey-node-4   | 1:M 24 Jan 2025 09:41:19.156 * Ready to accept connections tcp
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.157 * Creating AOF base file appendonly.aof.1.base.rdb on server start
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.160 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
valkey-node-3   | 1:M 24 Jan 2025 09:41:19.160 * Ready to accept connections tcp
valkey-cluster  | valkey-cluster 09:41:19.16 INFO  ==> Initializing Valkey
valkey-cluster  | valkey-cluster 09:41:19.16 INFO  ==> Setting Valkey config file
valkey-cluster  | Storing map with hostnames and IPs
valkey-cluster  | 
valkey-cluster  | valkey-cluster 09:41:19.19 INFO  ==> ** Valkey setup finished! **
valkey-cluster  | Node valkey-node-0 not ready, waiting for all the nodes to be ready...
valkey-cluster  | 119:C 24 Jan 2025 09:41:19.214 # WARNING: Changing databases number from 16 to 1 since we are in cluster mode
valkey-cluster  | 119:C 24 Jan 2025 09:41:19.215 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
valkey-cluster  | 119:C 24 Jan 2025 09:41:19.215 * Valkey version=8.0.2, bits=64, commit=00000000, modified=1, pid=119, just started
valkey-cluster  | 119:C 24 Jan 2025 09:41:19.215 * Configuration loaded
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.215 * monotonic clock: POSIX clock_gettime
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.215 * Running mode=cluster, port=6379.
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.215 * No cluster configuration found, I'm 72104cede65ea56796873d2dc371108ee87cf3e1
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.217 * Server initialized
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.218 * Creating AOF base file appendonly.aof.1.base.rdb on server start
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.219 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
valkey-cluster  | 119:M 24 Jan 2025 09:41:19.219 * Ready to accept connections tcp
valkey-cluster  | Node valkey-node-0 not ready, waiting for all the nodes to be ready...
```

### Additional information

I would appreciate it if you could investigate the issue regarding the node readiness and provide a fix to allow the cluster to initialize successfully.
Thank you.
