### ISSUE TITLE
No admin portal

### ISSUE THREAD

**Issue by marcosmartinezfco** [bitnami/containers#76656]
### Name and Version

bitnami/wordpress:6.7.1-debian-12-r11

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Deploy helm chart using argocd passing this values

```YAML
wordpress:
  mariadb:
    enabled: false

  externalDatabase:
    host: something.us-east-1.rds.amazonaws.com
    user: user
    password: password
    database: name
    port: 3306

  # control whether to use caching mechanism for WP
  wordpressConfigureCache: false

  # memcached configuration, false to use external cache
  memcached:
    enabled: false

  #externalCache:
  #  host: myexternalcachehost
  #  port: 11211

  persistence:
    size: 6Gi

  service:
    # by default wp creates a load balancer service which means paying an extra aws alb
    # if you don't need layer 4 load balancing, you can use ClusterIP
    type: ClusterIP

  ingress:
    enabled: true
    hostname: wordpress.lowcarbon.trade
    ingressClassName: alb
    annotations: {
      "alb.ingress.kubernetes.io/scheme": "internet-facing",
      "alb.ingress.kubernetes.io/target-type": "ip",
      "alb.ingress.kubernetes.io/load-balancer-name": "alb",
      "alb.ingress.kubernetes.io/listen-ports": '[{"HTTP":80},{"HTTPS":443}]',
      "alb.ingress.kubernetes.io/ssl-redirect": "443",
      "alb.ingress.kubernetes.io/group.name": "alb"
    }
```

### What is the expected behavior?

I would expect the website to be deployed without any issue

### What do you see instead?

The blog is deployed and looks healthy in argocd but when loading the website the blog loads without any format. It can load the main file but not the format csv files.

Plus I try to open the `wp-admin` dashboard and I get just a black screen with the same 404 errors

<img width="1509" alt="Image" src="https://github.com/user-attachments/assets/1a5c38f7-5a8c-4086-bb8a-a71616895e05" />

### Additional information

I'm using a rds instance with mariadb as the external database
