### ISSUE TITLE
ELasticsearch container error.

### ISSUE THREAD

**Issue by BenCoughlan15** [bitnami/containers#76720]
### Name and Version

bitnami/elasticsearch:8.17.1

### What architecture are you using?

None

### What steps will reproduce the bug?

```log
elasticsearch 14:43:59.08 INFO  ==>
elasticsearch 14:43:59.08 INFO  ==> Welcome to the Bitnami elasticsearch container
elasticsearch 14:43:59.08 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
elasticsearch 14:43:59.08 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
elasticsearch 14:43:59.08 INFO  ==>
elasticsearch 14:43:59.08 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch 14:43:59.10 WARN  ==> Setting ELASTICSEARCH_IS_DEDICATED_NODE is disabled.
elasticsearch 14:43:59.10 WARN  ==> ELASTICSEARCH_NODE_ROLES will be ignored and Elasticsearch will asume all different roles.
elasticsearch 14:43:59.10 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch 14:43:59.11 INFO  ==> Custom configuration file detected, using it...

elasticsearch 14:43:59.11 INFO  ==> ** Elasticsearch setup finished! **
elasticsearch 14:43:59.12 INFO  ==> ** Starting Elasticsearch **
Picked up JAVA_TOOL_OPTIONS: -Djava.security.egd=file:/dev/./urandom
warning: ignoring JAVA_TOOL_OPTIONS=-Djava.security.egd=file:/dev/./urandom
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.attach not found, required by org.elasticsearch.entitlement

ERROR: Elasticsearch died while starting up, with exit code 1
```

Docker-compose snippet: 
```YAML
  elasticsearch:
    build:
      context: ./tests/search/elasticsearch
      dockerfile: Dockerfile
      tags: [<acmecorp>/elasticsearch]
    command: sh -c "/opt/bitnami/scripts/elasticsearch/entrypoint.sh /opt/bitnami/scripts/elasticsearch/run.sh"
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
      - ./tests/search/elasticsearch/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      - ELASTICSEARCH_HEAP_SIZE=512m
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - JAVA_TOOL_OPTIONS=-Djava.security.egd=file:/dev/./urandom
      - ELASTICSEARCH_STARTUP_SLEEP=10

    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
```

### What is the expected behavior?

 I'd expect container to start, this isn't giving me much to go by. 

### What do you see instead?
```
warning: ignoring JAVA_TOOL_OPTIONS=-Djava.security.egd=file:/dev/./urandom
warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.attach not found, required by org.elasticsearch.entitlement

ERROR: Elasticsearch died while starting up, with exit code 1
```
### Additional information

this happened 2 hours ago, when version: 8.17.1 rolled out
