### ISSUE TITLE
OpenLDAP Pass-through Authentication

### ISSUE THREAD

**Issue by deeztek** [bitnami/containers#76824]
### Name and Version

bitnami/openldap:2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using the following docker-compose.yml file:

```yaml
services:
  openldap:
    image: bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=domain,dc=local
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_USERS=${LDAP_USERS}
      - LDAP_PASSWORDS=${LDAP_PASSWORDS}
       - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,argon2
      - BITNAMI_DEBUG=true
    volumes:
      - openldap_data:/bitnami/openldap
      - ../config/openldap/custom/schema/argon2.ldif:/opt/bitnami/openldap/etc/schema/argon2.ldif
      - ../config/openldap/sasl/slapd.conf:/usr/lib/sasl2/slapd.conf
      - ../config/openldap/sasl/saslauthd.conf:/etc/saslauthd.conf

volumes:
  openldap_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/openldap
```

The contents of slapd.conf are as follows:

```
mech_list: plain
pwcheck_method: saslauthd
saslauthd_path: /var/run/sasl2/mux
```

The contents of saslauthd.conf are as follows:

```
ldap_servers: ldap://192.168.xxx.xxx.xxx
ldap_search_base: OU=Users,DC=domain,DC=tld
ldap_filter: (uid=%u)

ldap_bind_dn: CN=saslauthd,CN=Users,DC=domain,DC=tld
ldap_password: somepassword
```

Added a user that already exists in domain.tld in openldap with the following password:

`{SASL}username@domain.tld`

### What is the expected behavior?

I expect a successful authentication to domain.tld

### What do you see instead?

Instead I get the following error:

```
hermes_openldap_app  | 679ceede.3aa31e0a 0x7f2ff617e6c0 conn=1004 op=1 SRCH attr=uid mail displayName
hermes_openldap_app  | 679ceede.3aa4b816 0x7f2ff617e6c0 conn=1004 op=1 SEARCH RESULT tag=101 err=0 qtime=0.000019 etime=0.000172 nentries=1 text=
hermes_openldap_app  | 679ceede.3aaafd88 0x7f2ff597d6c0 conn=1005 fd=14 ACCEPT from IP=172.16.32.1:47082 (IP=0.0.0.0:1389)
hermes_openldap_app  | 679ceede.3aab8f34 0x7f2ff597d6c0 conn=1005 op=0 BIND dn="cn=username@domain.tld,ou=users,dc=domain,dc=local" method=128
hermes_openldap_app  | 679ceede.3aac9267 0x7f2ff597d6c0 SASL [conn=1005] Failure: cannot connect to saslauthd server: No such file or directory
hermes_openldap_app  | 679ceede.3aad25b9 0x7f2ff597d6c0 conn=1005 op=0 RESULT tag=97 err=49 qtime=0.000005 etime=0.000120 text=
hermes_openldap_app  | 679ceede.3ab0191f 0x7f2ff617e6c0 conn=1005 fd=14 closed (connection lost)
hermes_openldap_app  | 679ceede.3ab3d76a 0x7f2ff597d6c0 conn=1004 fd=13 closed (connection lost)
```

### Additional information

I'm guessing the paths to slapd.conf and saslauthd.conf are probably wrong. I got the config from the openldap admin documentation ([](https://www.openldap.org/doc/admin26/guide.html#Pass-Through%20authentication)https://www.openldap.org/doc/admin26/guide.html#Pass-Through%20authentication), however there is no clear guidance on how to accomplish that with the bitnami openldap container. I would appreciate some help on this.

thanks a lot

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and would like to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

If you have any questions regarding the application, customizing its content, or utilizing technology and infrastructure, we strongly recommend that you consult the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by deeztek** [comment]
As far as I can tell,  saslauthd does not seem to exist in the bitnami openldap container which is required in order to use pass-through authentication. Could someone point me in the right direction on how I could enable that. 

Thanks

**Comment by deeztek** [comment]
I figured out how to get pass-through authentication using remoteauth as well as argon2 password hashing for local auth users. Here's my config for anyone that may find it useful:

**Assumptions:**

**Openldap domain:** local-openldap-domain.local
**Remote AD domain:** ad-domain.tld
**Openldap local authentication user:** mjane
**Openldap remote authentication user:** jsmoe


**Bitnami docker-compose.yml:**

```
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap_app
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=local-openldap-domain,dc=local
      - LDAP_ADMIN_USERNAME=ldap-admin
      - LDAP_ADMIN_PASSWORD=ldap_admin_password
      - LDAP_USERS=some-ldap-user
      - LDAP_PASSWORDS=some_ldap_user_password
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,argon2,remoteauth
      - BITNAMI_DEBUG=true
      - LDAP_LOG_LEVEL=1
    networks:
      openldap_net_ext:
              ipv4_address: 172.16.xxx.xxx
    volumes:
      - openldap_data:/bitnami/openldap
      - ./schema-argon2.ldif:/opt/bitnami/openldap/etc/schema/schema-argon2.ldif
      - ./schema-remoteauth.ldif:/opt/bitnami/openldap/etc/schema/schema-remoteauth.ldif
      - ./custom-argon2.ldif:/custom/custom-argon2.ldif
      - ./custom-remoteauth.ldif:/custom/custom-remoteauth.ldif
```

**schema-argon2.ldif:**

```
dn: cn=module{1},cn=config
objectClass: olcModuleList
cn: module{1}
olcModulePath: /opt/bitnami/openldap/lib/openldap
olcModuleLoad: argon2.so
```

**schema-remoteauth.ldif:**

```
dn: cn=module{2},cn=config
objectClass: olcModuleList
cn: module{1}
olcModulePath: /opt/bitnami/openldap/lib/openldap
olcModuleLoad: remoteauth.so
```

**custom-argon2.ldif:**

```
dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcPasswordHash
olcPasswordHash: {ARGON2}
```

**custom-remoteauth.ldif:**

```
dn: olcOverlay={6}remoteauth,olcDatabase={2}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcRemoteAuthCfg
olcOverlay: {6}remoteauth
olcRemoteAuthDNAttribute: seeAlso
olcRemoteAuthDomainAttribute: associatedDomain
olcRemoteAuthDefaultDomain: ad-domain
olcRemoteAuthMapping: ad-domain dc01.ad-domain.tld
olcRemoteAuthTLS: starttls=no tls_reqcert=never
olcRemoteAuthRetryCount: 3
```

Once the container is up, add the custom-argon2.ldif and the custom-remoteauth.ldif files as follows:

`docker exec openldap_app ldapadd -H ldapi:/// -Y EXTERNAL -f /custom/argon2.ldif` 
`docker exec openldap_app ldapadd -H ldapi:/// -Y EXTERNAL -f /custom/remoteauth.ldif`

For a remoteauth user use the following attributes to create a user in openldap where **associatedDomain** is the **olcRemoteAuthDefaultDomain** in the **custom-remoteauth.ldif** file and  **seeAlso** is the DN of the user in the remote AD domain. I'm guessing it should work with just the username on the remote domain:

```
dn: cn=jsmoe,ou=users,dc=local-openldap-domain,dc=local
objectClass: domainRelatedObject
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
associatedDomain: ad-domain
cn: jsmoe
sn: Smoe
displayName: Joe Smoe
givenName: Joe
mail: jsmoe@domain.tld
seeAlso: cn=Joe Smoe,ou=Users,dc=ad-domain,dc=tld
uid: jsmoe
```

For a local openldap user, use the following attributes to create a user in openldap:

```
dn: cn=mjane,ou=users,dc=local-openldap-domain,dc=local
objectClass: inetOrgPerson
cn: mjane
sn: Jane
displayName: Mary Jane
givenName: Mary
mail: mjane@domain.tld
uid: mjane
userPassword: {ARGON2}$argon2id$v=19$m=7168,t=5,p=1$NaoI0qbKSpD5Hle+WhfncQ$HIWlTiUf02j8+tq
Oattpu2Z9tKyPGXG0YxyrxhmFDFs
```

You can create an ARGON2 password by using the following command:

`docker exec openldap_app slappasswd -o module-load=argon2.so -h {ARGON2} -s "somepassword"`
