### ISSUE TITLE
How to expand minio DISTRIBUTED_MODE

### ISSUE THREAD

**Issue by AEGEGE** [bitnami/containers#7686]
### Name and Version

bitnami/minio:2022.8.22-debian-11-r1

### What steps will reproduce the bug?

The docker startup command is as follows, the initial node is 4
```
docker run -d --restart=always --name minio --network host \
          --ulimit nofile=65536:65536 \
          -v "/etc/localtime":/etc/localtime:ro \
          -v "/data/minio/data":/data \
          -v "/data/minio/hosts":/etc/hosts \
          -v "/data/logs/minio":/opt/logs \
          -e LANG=C.UTF-8 \
          -e MINIO_ROOT_USER=xxxxxxxxxx  \
          -e MINIO_ROOT_PASSWORD=xxxxxxxxxxxxxx  \
          -e MINIO_DISTRIBUTED_MODE_ENABLED=yes \
          -e MINIO_DISTRIBUTED_NODES=minio-1,minio-2,minio-3,minio-4 \
          -e MINIO_SKIP_CLIENT=yes \
          -e MINIO_HTTP_TRACE=/opt/bitnami/minio/log/minio-http.log \
          -e MINIO_PROMETHEUS_AUTH_TYPE="public" 
```

### What is the expected behavior?

I want to expand to 8 nodes, but the following configuration cannot be started
```
docker run -d --restart=always --name minio --network host \
          --ulimit nofile=65536:65536 \
          -v "/etc/localtime":/etc/localtime:ro \
          -v "/data/minio/data":/data \
          -v "/data/minio/hosts":/etc/hosts \
          -v "/data/logs/minio":/opt/logs \
          -e LANG=C.UTF-8 \
          -e MINIO_ROOT_USER=xxxxxxxxxx  \
          -e MINIO_ROOT_PASSWORD=xxxxxxxxxxxxxx  \
          -e MINIO_DISTRIBUTED_MODE_ENABLED=yes \
          -e MINIO_DISTRIBUTED_NODES=minio-1,minio-2,minio-3,minio-4,minio-5,minio-6,minio-7,minio-8 \
          -e MINIO_SKIP_CLIENT=yes \
          -e MINIO_HTTP_TRACE=/opt/bitnami/minio/log/minio-http.log \
          -e MINIO_PROMETHEUS_AUTH_TYPE="public" 
```
### What do you see instead?
```
API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-1:9000 offline temporarily; caused by Post "http://minio-1:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.89:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-4:9000 offline temporarily; caused by Post "http://minio-4:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.57:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-2:9000 offline temporarily; caused by Post "http://minio-2:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.139:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-6:9000 offline temporarily; caused by Post "http://minio-6:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.140:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-7:9000 offline temporarily; caused by Post "http://minio-7:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.159:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-8:9000 offline temporarily; caused by Post "http://minio-8:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.161:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()

API: SYSTEM()
Time: 17:44:21 UTC 09/23/2022
Error: Marking minio-5:9000 offline temporarily; caused by Post "http://minio-5:9000/minio/storage/data/v47/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 10.13.1.112:9000: connect: connection refused (*fmt.wrapError)
       9: internal/logger/logger.go:259:logger.LogIf()
       8: internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()
       7: internal/logger/logonce.go:135:logger.LogOnceIf()
       6: internal/rest/client.go:243:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:526:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:396:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:332:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
ERROR Unable to initialize backend: http://minio-2:9000/data drive is already being used in another erasure deployment. (Number of drives specified: 8 but the number of drives found in the 2nd drive's format.json: 4)
```
### Additional information

Can you guide me where is the configuration problem?

**Comment by jotamartos** [comment]
Hi @AEGEGE,

I just used this docker-compose.yml file to deploy the solution and everything worked as expected

```
version: '2'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio2:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_2_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio3:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_3_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio4:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_4_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio5:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_5_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio6:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_6_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio7:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_7_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8
  minio8:
    image: docker.io/bitnami/minio:2022
    volumes:
      - 'minio_8_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4,minio5,minio6,minio7,minio8

volumes:
  minio_data:
    driver: local
  minio_2_data:
    driver: local
  minio_3_data:
    driver: local
  minio_4_data:
    driver: local
  minio_5_data:
    driver: local
  minio_6_data:
    driver: local
  minio_7_data:
    driver: local
  minio_8_data:
    driver: local
```

<img width="1265" alt="Screen Shot 2022-09-29 at 10 56 20" src="https://user-images.githubusercontent.com/8791635/192988193-61305763-b6ac-45e5-a3df-f2843f3d89a1.png">

Could you please try deploying the solution using it and confirm everything works as expected for you too?

Thanks
