### ISSUE TITLE
[bitnami/mariadb] Persistent volume is NOT used for mariadb datadir

### ISSUE THREAD

**Issue by mrmachine** [bitnami/containers#77051]
### Name and Version

bitnami/mariadb:11

### What architecture are you using?

arm64

### What steps will reproduce the bug?

With this bind mount `./mariadb-11-data:/bitnami/mariadb` my `/bitnami/mariadb` directory is empty even after I created a wordpress database and configured wordpress to use it.

Therefore when I down/up the compose stack which recreates the container, my actual database is lost. Sounds similar to #53505

I searched `/etc/` for `datadir` and found:

```
root@bf76e23b19b0:/etc/mysql# grep -R datadir /etc/mysql/
/etc/mysql/mariadb.conf.d/50-server.cnf:#datadir                 = /var/lib/mysql
```

And this dir is in fact populated with my databases.

So, the configuration is wrong OR the bitnami README/documentation is wrong.

I suspect that this is actually the cause for #53505 and that the user who "solved" the problem by dumping and restoring between major version upgrades was just getting lucky that their container was never destroyed and recreated.

### What is the expected behavior?

Databases should survive container removal and re-creation. Databases should be stored in `/bitnami/mariadb` or at least the docs should tell us which container directory to bind mount for persistent storage.

### What do you see instead?

Databases are lost on container delete and recreate. Databases are not stored in documented persistent volume.

**Comment by mrmachine** [comment]
Surely at the very least a docs fix is needed?

**Comment by mrmachine** [comment]
Bump.

**Comment by mrmachine** [comment]
Bump.

**Comment by juan131** [comment]
Sorry @mrmachine but we it seems this issue got out of our control

The Bitnami MariaDB container should be storing data at `/bitnami/mariadb` as you pointed out **unless** you're using custom configuration overriding the default one so data is stored somewhere else. Could you please share how you're configuring your MariaDB container (env. variables and custom configuration you might be mounting via bind mounts?

**Comment by mrmachine** [comment]
Here's the mariadb service from my `docker-compose.yml` file:

```yaml
  mariadb:
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: ...
      MARIADB_PASSWORD: ...
      MARIADB_USER: ...
    image: mariadb:11
    ports:
      - ${MARIADB_PORT:-3306}
    volumes:
      # - mariadb-data:/bitnami/mariadb  # See: https://github.com/bitnami/containers/issues/77051
      - mariadb-data:/var/lib/mysql
```

I have commented out the bind mount volume that **should** be working and am using a different one that points to the actual location of the mariadb data.
