### ISSUE TITLE
[bitnami/discourse] error during initial asset precompilation 

### ISSUE THREAD

**Issue by artybdrlt** [bitnami/containers#77076]
### Name and Version

bitnami:discourse:3.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I run my docker-compose for launch a discourse bitnami instance, it gets stuck during initial "precompiling assets" and the container ends up rebooting and getting stuck during the same step, over and over again.

Here is my docker compose

```
---
# Template:    discourse
# Image AIO:   no
# Database:    PostgreSQL
# Description: Discourse is a modern forum software for your community.

services:
  postgresql:
    image: docker.io/bitnami/postgresql:${POSTGRESQL_IMAGE_TAG:-16}
    restart: always
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - POSTGRESQL_USERNAME=${DISCOURSE_DATABASE_USER:-bn_discourse}
      - POSTGRESQL_DATABASE=${DISCOURSE_DATABASE_NAME:-bitnami_discourse}
    networks:
      - internal
    labels:
      - "docker-volume-backup.stop-during-backup=discourse_backup"
    cpus: '0.5'
    mem_limit: 512M


  redis:
    image: docker.io/bitnami/redis:${REDIS_IMAGE_TAG:-7.0}
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
    volumes:
      - redis_data:/bitnami/redis
    networks:
      - internal
    cpus: '0.5'
    mem_limit: 256M

  discourse:
    image: docker.io/bitnami/discourse:${DISCOURSE_IMAGE_TAG:-3.1.3}
    restart: always
    volumes:
      - discourse_data:/bitnami/discourse
    depends_on:
      - postgresql
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - BITNAMI_DEBUG=${BITNAMI_DEBUG:-false}
      - DISCOURSE_ENABLE_HTTPS=${DISCOURSE_ENABLE_HTTPS:-yes}
      - DISCOURSE_HOST=${URL}
      - DISCOURSE_USERNAME=${DISCOURSE_USERNAME:-user}
      - DISCOURSE_PASSWORD=${DISCOURSE_PASSWORD:-bitnami123}
      - DISCOURSE_EMAIL=${DISCOURSE_EMAIL:-user@example.com}
      - DISCOURSE_DATABASE_HOST=${DISCOURSE_DATABASE_HOST:-postgresql}
      - DISCOURSE_DATABASE_PORT_NUMBER=${DISCOURSE_DATABASE_PORT_NUMBER:-5432}
      - DISCOURSE_DATABASE_USER=${DISCOURSE_DATABASE_USER:-bn_discourse}
      - DISCOURSE_DATABASE_NAME=${DISCOURSE_DATABASE_NAME:-bitnami_discourse}
      - DISCOURSE_REDIS_HOST=${DISCOURSE_REDIS_HOST:-redis}
      - DISCOURSE_REDIS_PORT_NUMBER=${DISCOURSE_REDIS_PORT_NUMBER:-6379}
      - DISCOURSE_SMTP_HOST=${DISCOURSE_SMTP_HOST:-smtp.gmail.com}
      - DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT:-587}
      - DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER:-your_email@gmail.com}
      - DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD:-your_password}
      - DISCOURSE_SMTP_PROTOCOL=${DISCOURSE_SMTP_PROTOCOL:-tls}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME:-discourse}.rule=Host(`${URL}`)"
      - "traefik.http.routers.${SERVICE_NAME:-discourse}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME:-discourse}.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik-network"
      - "docker-volume-backup.stop-during-backup=discourse_backup"
    networks:
      - internal
      - traefik-network
    cpus: '1'
    mem_limit: 2G

  sidekiq:
    image: docker.io/bitnami/discourse:${DISCOURSE_IMAGE_TAG:-3.1.3}
    restart: always
    depends_on:
      - discourse
    volumes:
      - sidekiq_data:/bitnami/discourse
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - BITNAMI_DEBUG=${BITNAMI_DEBUG:-false}
      - DISCOURSE_HOST=${URL}
      - DISCOURSE_DATABASE_HOST=${DISCOURSE_DATABASE_HOST:-postgresql}
      - DISCOURSE_DATABASE_PORT_NUMBER=${DISCOURSE_DATABASE_PORT_NUMBER:-5432}
      - DISCOURSE_DATABASE_USER=${DISCOURSE_DATABASE_USER:-bn_discourse}
      - DISCOURSE_DATABASE_NAME=${DISCOURSE_DATABASE_NAME:-bitnami_discourse}
      - DISCOURSE_REDIS_HOST=${DISCOURSE_REDIS_HOST:-redis}
      - DISCOURSE_REDIS_PORT_NUMBER=${DISCOURSE_REDIS_PORT_NUMBER:-6379}
      - DISCOURSE_SMTP_HOST=${DISCOURSE_SMTP_HOST:-smtp.gmail.com}
      - DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT:-587}
      - DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER:-your_email@gmail.com}
      - DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD:-your_password}
      - DISCOURSE_SMTP_PROTOCOL=${DISCOURSE_SMTP_PROTOCOL:-tls}
    networks:
      - internal
    labels:
      - "docker-volume-backup.stop-during-backup=discourse_backup"
    cpus: '0.5'
    mem_limit: 1G

  backup-local:
    container_name: ${SERVICE_NAME:-discourse}-backup-local-service
    image: offen/docker-volume-backup:v2
    restart: always
    volumes:
      - postgresql_data:/backup/postgresql_data:ro
      - discourse_data:/backup/discourse_data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BACKUPS_DIR:-/backup}/docker/${SERVICE_NAME:-discourse}:/archive
    environment:
      BACKUP_FILENAME: discourse-local-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_CRON_EXPRESSION: "0 23 * * *"
      BACKUP_RETENTION_DAYS: '5'
      BACKUP_LATEST_SYMLINK: discourse-local-backup-latest.tar.gz
      BACKUP_STOP_DURING_BACKUP_LABEL: discourse_backup

  backup-s3:
    container_name: ${SERVICE_NAME:-discourse}-backup-s3-service
    image: offen/docker-volume-backup:v2
    restart: always
    volumes:
      - postgresql_data:/backup/postgresql_data:ro
      - discourse_data:/backup/discourse_data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      BACKUP_FILENAME: discourse-s3-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_CRON_EXPRESSION: "0 23 * * *"
      BACKUP_RETENTION_DAYS: '30'
      BACKUP_LATEST_SYMLINK: discourse-s3-backup-latest.tar.gz
      BACKUP_STOP_DURING_BACKUP_LABEL: discourse_backup
      AWS_S3_BUCKET_NAME: "XXX"
      AWS_ENDPOINT: "${AWS_ENDPOINT:-XXX}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-XXX}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-XXX}"

networks:
  internal:
  traefik-network:
    external: true

volumes:
  postgresql_data:
  redis_data:
  discourse_data:
  sidekiq_data:
```

Here are the Discourse container logs

```
(1 row)

discourse 11:19:46.54 INFO  ==> Running database migrations
discourse 11:19:50.20 INFO  ==> Precompiling assets, this may take some time...
yarn run v1.22.21
$ /opt/bitnami/discourse/app/assets/javascripts/node_modules/.bin/ember build -prod
- Building
Environment: production
- Building
- building... 
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
[WARN] (broccoli-terser-sourcemap) Minifying "assets/plugins/test/chat_tests.js" took: 20798ms (more than 20,000ms)
[WARN] (broccoli-terser-sourcemap) Minifying "assets/markdown-it-bundle.js" took: 36486ms (more than 20,000ms)
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried to run `npx update-browserslist-db@latest` in `/opt/bitnami/discourse/app/assets/javascripts/node_modules` but the same error message appears nonetheless.

I have also tried running the same docker compose on bitnami/discourse:3.0.3 but I've got the same behavior.

### What is the expected behavior?

Discourse should boot up and run.

### What do you see instead?

Discourse is stuck during initial precompilation of assets.

### Additional information

I used to be able to run this docker compose without an issue. However, I couldn't upgrade Discourse.
