### ISSUE TITLE
[bitnami/etcd] bug: preupgrade will failed when startup etcd with one-way tls authentication

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/containers#78362]
### Name and Version

bitnami/etcd:3.5.18

### What architecture are you using?

None

### What steps will reproduce the bug?

1. container.env
```
ALLOW_NONE_AUTHENTICATION = "yes"
ETCD_LISTEN_CLIENT_URLS = "https://0.0.0.0:2379"
ETCD_ADVERTISE_CLIENT_URLS = "https://etcd:2379"
ETCD_INITIAL_CLUSTER = "etcd=https://etcd:2379"
ETCD_INITIAL_ADVERTISE_PEER_URLS = "https://etcd:2379"
ETCD_NAME = "etcd"
ETCD_CERT_FILE = "/certs/tls.crt"
ETCD_KEY_FILE = "/certs/tls.key"
```
2. compose.yaml
```
services:
  etcd:
    image: docker.io/bitnami/etcd:3.5.18`
    restart: unless-stopped
    env_file: ./container.env
    #ports: [2379,2380]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    volumes:
      - etcd_data:/bitnami/etcd/data
      - ./certs:/certs
```
3. startup etcd and go into the container
4. run /opt/bitnami/scripts/etcd/preupgrade.sh will fail

![Image](https://github.com/user-attachments/assets/eeb96280-f995-4931-9301-279bea118a30)

### What is the expected behavior?

preupgrade.sh should still succeed when startup etcd with one-way tls authentication

### What do you see instead?

/opt/bitnami/scripts/etcd/preupgrade.sh failed

### Additional information

same issue with https://github.com/bitnami/containers/issues/70554

**Comment by chenraoCR** [comment]
@juan131 
in fact, how i found this issue is when i deployed latest bitnami/etcd helm chart, ectd cannot up.
As what u suggested, there are two problems
1. please refer https://github.com/bitnami/charts/issues/27109
the latest bitnami/ectd helm chart 11.0.8, can only support one-way tls authentication, as in the helm chart templates/statefulset.yaml
![Image](https://github.com/user-attachments/assets/b52347c4-6bd1-4b5a-ab9f-37002127cb54)
livenessProb uses httpGet, only support one-way tls authentication
here is my values:
```
auth:
  rbac:
    ## NOTES: only when create=false & allowNoneAuthentication=true, then allow client connect etcd server without authentication
    create: false
    allowNoneAuthentication: true
    existingSecret: "etcd-credentials-secret"
  client:
    secureTransport: true
    existingSecret: "etcd-tls-secret"
    enableAuthentication: false
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    caFilename: ca.crt

replicaCount: 3
```
then livenessProb will failed
![Image](https://github.com/user-attachments/assets/04c8a985-0157-4ad2-83c7-da4b964a46cc)

2. as i mentioned preupgrade will failed when startup etcd with one-way tls authentication, so in the helm chart values.yaml, should set Values.auth.client.caFilename to default "", then the prb job which use script preupgrade.sh will fail as what i mentioned previously

**Comment by chenraoCR** [comment]
@juan131 
1. just follow https://github.com/bitnami/containers/issues/78362#issuecomment-2684556975
there will be issue
1.1 at the begining, the pods will startup, will when describe the pods we will see
![Image](https://github.com/user-attachments/assets/62c905c5-4246-4872-8615-0b758355e18f)
we can see that liveness probe will fail, why it will fail, i explained it already
1.2 wait for a while, we will see pods will restart as liveness probe failed

![Image](https://github.com/user-attachments/assets/739bd90d-4c97-4a6b-a881-94a917be6a14)

![Image](https://github.com/user-attachments/assets/b95019f1-32d8-4a95-a6ff-4c5c8eabb504)
1.3 so all the 3 pods will keep restarting, which means that value.yaml u provided has something wrong

2. then we need to comment out auth.client.caFilename to set it empty as default, which means startup etcd with one-way tls authentication, why? two reasons: the lastest helm chart only support one-way tls  authentication; etcd should also support one-way tls authentication besides two-way tls  authentication
when set auth.client.caFilename to "" and upgrade etcd, u will see etcd-pre-upgrade job will fail


after all, could u please read the related issues and its comments
https://github.com/bitnami/containers/issues/70554
https://github.com/bitnami/charts/issues/27109

**Comment by juan131** [comment]
Hi @chenraoCR 

As you pointed out, setting `auth.client.secureTransport` to `true` implies enabling client-to-server authentication via TLS (please note it's not the same as enabling client transport security with HTTPS) so it means clients must provide their certificates to the server. Therefore, liveness probes must be adapted, I just created a PR to address this.

**Comment by chenraoCR** [comment]
@juan131 

in ectd helm chart, certs in auth.client.existingSecret are not only client certs, but also server certs. so when ectd server startup, it will use those certs as server certs, and when run the scripts in the container like preupgrade.sh or healthcheck.sh, the scripts run as client to communicate with the etcd server, so the scripts use those certs as client certs

https://github.com/bitnami/containers/issues/78362#issuecomment-2696980488 this can work when set helm value file for tls like the following
```
auth:
  client:
    secureTransport: true
    existingSecret: etcd-client-crt
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ca.crt
```
which means the ectd server startup with 2-way tls authentication, in the etcd container, there are not only certs, but also CA, so all the scripts can work normally

but we can also startup etcd with 1-way tls authentication, which means we can set etcd helm value file for tls like this
```
auth:
  client:
    secureTransport: true
    existingSecret: etcd-client-crt
    certFilename: tls.crt
    certKeyFilename: tls.key
    caFilename: ""
```
in this case, etcd pods should also run normally, but in fact cannot, why?
in this case, in etcd container, there will be no CA. so etcd server startup with tls, but no CA, then server side will not check the certs sent from client side, but in the container, when run the scripts, they also have no CA, so in the scripts, we also should skip tls verification, which means need to add flag `--insecure-skip-tls-verify`, otherwise it will throw handshake error.
so we also need to fixup preupgrade.sh for this case
