### ISSUE TITLE
[bitnami/laravel] Can't mount project to a different container's folder

### ISSUE THREAD

**Issue by manuelbosi** [bitnami/containers#7843]
### Name and Version

bitnami/laravel:9.3.8

### What steps will reproduce the bug?

- Use the default [docker-compose.yml](https://raw.githubusercontent.com/bitnami/containers/main/bitnami/laravel/docker-compose.yml) settings
- Under myapp service, change './my-project:/app' to './my-project:/app/backend'
- Run `docker compose up`, will create container and fails running laravel artisan

```
version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
```

### What do you see instead?

```
laravel 17:02:54.89 

laravel 17:02:54.91 Welcome to the Bitnami laravel container

laravel 17:02:54.93 Subscribe to project updates by watching https://github.com/bitnami/containers

laravel 17:02:54.95 Submit issues and feature requests at https://github.com/bitnami/containers/issues

laravel 17:02:54.96 

laravel 17:02:54.98 INFO  ==> ** Running Laravel setup **

laravel 17:02:55.18 INFO  ==> Configuring PHP options

laravel 17:02:55.20 INFO  ==> Setting PHP opcache.enable option

laravel 17:02:55.28 INFO  ==> Setting PHP expose_php option

laravel 17:02:55.48 INFO  ==> Validating settings in LARAVEL_* environment variables...

laravel 17:02:55.59 INFO  ==> An existing project was detected, skipping project creation

laravel 17:03:11.24 INFO  ==> ** Laravel setup finished! **

laravel 17:03:11.31 INFO  ==> ** Starting Laravel project **


Could not open input file: artisan
```
