### ISSUE TITLE
postgresql image not starting because of error in /opt/bitnami/scripts/libpostgresql.sh

### ISSUE THREAD

**Issue by m00thie** [bitnami/containers#78959]
### Name and Version

btinami/postgresql:17.4.0-debian-12-r5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In docker/podman, when var `POSTGRESQL_PERFORM_RESTORE` is not set or set to `false` while docker run/podman run, I see the error 
```
/opt/bitnami/scripts/libpostgresql.sh: line 579: files: readonly variable
```

### What is the expected behavior?

container start without any error

### Additional information

The problem seems to be caused by the `files` variable definition. It is defined as read-only, while in the next instruction, you try to modify it

https://github.com/bitnami/containers/blob/main/bitnami/postgresql/17/debian-12/rootfs/opt/bitnami/scripts/libpostgresql.sh#L572
```bash
postgresql_clean_from_restart() {
    local -r -a files=(
        "$POSTGRESQL_DATA_DIR"/postmaster.pid
        "$POSTGRESQL_DATA_DIR"/standby.signal
    )

    # Enable recovery only when POSTGRESQL_PERFORM_RESTORE feature flag is set
    if ! is_boolean_yes "$POSTGRESQL_PERFORM_RESTORE" ; then
        files+=("$POSTGRESQL_DATA_DIR"/recovery.signal)
    fi
```

**Comment by vcazsdk** [comment]
Same problem for me. All postgres is down after updating to 14.17.0-debian-12-r4, no problem with 14.17.0-debian-12-r3.

**Comment by Chripo72** [comment]
Same here. Setting POSTGRESQL_PERFORM_RESTORE variable to true helps around for the moment.

**Comment by Cobesz** [comment]
> Same problem for me. All postgres is down after updating to 14.17.0-debian-12-r4, no problem with 14.17.0-debian-12-r3.

Also happens with a different tag set. This is my values.yaml:

```yaml
image:
  debug: false
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/postgresql
  tag: 17
kubeVersion: ""
```

Adding this to your values.yaml fixes it:

```yaml
primary:
  extraEnvVars:
    - name: POSTGRESQL_PERFORM_RESTORE
      value: "true"
```

**Comment by tejpalsinh1110** [comment]
I just add `POSTGRESQL_PERFORM_RESTORE=true` and it works for me in php/Symfony/API Platform.

```
db:
    # In production, you may want to use a managed database service
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_PERFORM_RESTORE=true
      - POSTGRESQL_DATABASE=api
      - POSTGRESQL_USERNAME=api-platform
      # You should definitely change the password in production
      - POSTGRESQL_PASSWORD=!ChangeMe!
      - POSTGRESQL_POSTGRES_PASSWORD=!ChangeMe!
```
