### ISSUE TITLE
EAI_AGAIN with latest postgresql:14 image

### ISSUE THREAD

**Issue by sdawes437** [bitnami/containers#78964]
### Name and Version

bitnami/postgresql:14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Use this image as a [service container](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops) in Azure Pipelines and a main container with an image based off the node 18.19 image
- Run a series of SQL scripts against the database, using pg-pool package
- Receive error message below (hostname removed)

```
Error: getaddrinfo EAI_AGAIN ######
    at /__w/1/s/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: ######
}
```

The config from the pipeline yaml file is below, with parts redacted

```yaml
  containers:
    - container: pipeline
      image: ##### (based off node:18.19)
      endpoint: GCR Central

    - container: postgres
      image: bitnami/postgresql:14
      ports:
        - 5432:5432
      env:
        POSTGRESQL_PASSWORD: #####
        POSTGRESQL_USERNAME: #####
        POSTGRESQL_DATABASE: #####
```

The pipeline runs without issue with the config below
```yaml
  containers:
    - container: pipeline
      image: ##### (based off node:18.19)
      endpoint: GCR Central

    - container: postgres
      image: bitnami/postgresql:14.17.0-debian-12-r3
      ports:
        - 5432:5432
      env:
        POSTGRESQL_PASSWORD: ####
        POSTGRESQL_USERNAME: ####
        POSTGRESQL_DATABASE: ####
```
### What is the expected behavior?

All scripts run without issue.

### What do you see instead?

```
Error: getaddrinfo EAI_AGAIN ######
    at /__w/1/s/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: ######
}
```

### Additional information

I can't see any obvious changes in the version change that has caused this issue, however, I have run this multiple times with both postgreql images, to rule out that this is an intermittent issue with Azure Pipelines. The previous version succeeds, while the updated version (i.e. bitnami/postgresql:14.17.0-debian-12-r4) fails.
