### ISSUE TITLE
Cannot start bitnami/sonarqube:latest (25.3.0) after upgrading from 25.2.0

### ISSUE THREAD

**Issue by djaydjay31** [bitnami/containers#78977]
### Name and Version

bitnami/sonarqube:latest (25.3.0)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have a running server on image 25.2.0.

When I upgrade to last version (latest, 25.3.0) with the following docker compose:
```yaml
services:
  sonarqube:
    # image: bitnami/sonarqube:25.2.0
    image: bitnami/sonarqube:latest
    restart: unless-stopped
    hostname: sonarqube.mydomain.com
    container_name: sonarqube
    depends_on:
      - db
    environment:
      - SONARQUBE_DATABASE_HOST=db
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=*******
      - SONARQUBE_DATABASE_PASSWORD=*********
      - SONARQUBE_DATABASE_NAME=sonar
    volumes:
      - /++++++++/sonarqube/sonarqube_data:/bitnami/sonarqube
    ports:
      - "127.0.0.1:9000:9000"
  db:
    image: bitnami/postgresql:15
    restart: unless-stopped
    hostname: postgres_sonar
    container_name: postgres_sonar
    environment:
      POSTGRES_USER: *********
      POSTGRES_PASSWORD: **********
      POSTGRES_DB: sonar
      POSTGRESQL_REPLICATION_USE_PASSFILE: null
    volumes:
      - /++++++++/sonarqube/pg:/bitnami/postgresql
      - /++++++++/sonarqube/pg_data:/bitnami/postgresql/data
```
After upgrading image version to 25.3.0,
I get:
```
fatal exception while booting Elasticsearch
sonarqube       | java.lang.IllegalStateException: Unable to access 'path.home' (/opt/bitnami/sonarqube/elasticsearch/plugins ...)
Elasticsearch is not starting. 
```
Isn't there some path error `/opt/bitnami/sonarqube` that should be `/bitnami/sonarqube`?
Regards

### What is the expected behavior?

Sonarqube should start

### What do you see instead?

Sonarqube is down
