### ISSUE TITLE
AWS SES Configuration Skipped Emails

### ISSUE THREAD

**Issue by kuzeal** [bitnami/containers#78982]
### Name and Version

bitnami/discourse:3.4.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I deployed the helm chart and the containers are running fine. From the UI  of discourse I am attempting to send a test email after logging in as the admin. I have also tried registering as a new user and it produces the same issue.

### What is the expected behavior?

I would like an email to be sent.

### What do you see instead?

When I send a test email or register a new user, I get the following error in the admin email configuration “skipped” section :

554 Transaction failed: Invalid domain name: '127.0.0.1'.

In the logs of the discourse container, I dont see any errors.

When I go to the admin > emails > settings page, the "domain" section is empty:

![Image](https://github.com/user-attachments/assets/57309024-e303-4381-a330-6994125e2c7e)

### Additional information

Sensitive information such as user, password, and the values for the domain have been removed or replaced with example values.

I have configured other services to use SES and those are sending emails properly with the same credentials. So from my Alertmanager service I can currently send emails from alerts@exampledomain.com where `exampledomain.com` is a domain I have verified in SES.

I have ingress enabled and am able to access Discourse online `discourse.subdomain.exampledomain.com`. 

Here are values relating to smtp  and the extraEnvVars I have set for the containers based on [the values here](https://github.com/discourse/discourse_docker/blob/main/samples/standalone.yml#L71). I can provide more if needed but I was thinking that these would be the only ones relevant.

```yaml
smtp:
  enabled: true
  host: "email-smtp.us-west-2.amazonaws.com"
  port: "587"
  user: "XXXXX"
  password: "XXXXX"
  protocol: "tls"
  auth: ""
  existingSecret: ""

sidekiq:
  extraEnvVars:
    - name: DISCOURSE_SMTP_DOMAIN
      value: exampledomain.com
    - name: DISCOURSE_NOTIFICATION_EMAIL
      value: discourse@exampledomain.com

discourse:
  extraEnvVars:
    - name: DISCOURSE_SMTP_DOMAIN
      value: exampledomain.com
    - name: DISCOURSE_NOTIFICATION_EMAIL
      value: discourse@exampledomain.com
```

Is the issue my discourse configuration?
