### ISSUE TITLE
[bitnami/kafka] Healthcheck fails  - container fails to start in Docker Swarm mode

### ISSUE THREAD

**Issue by zivisraelyankelevitz** [bitnami/containers#79134]
### Name and Version

bitnami/kafka:3.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. use Docker init in Swarm Node
2. deploy docker stack with Kafka service:

```yaml
version: '3.7'

x-deploy:
  &default-deploy
  replicas: 1
  update_config:
    parallelism: 1
    delay: 10s
  restart_policy:
    condition: any
    max_attempts: 5
    window: 30m

x-gnss-healthcheck:
  &gnss-healthcheck
  interval: 60s
  timeout: 20s
  retries: 3
  start_period: 30s

services:
  kafka:
    image: bitnami/kafka:3.6.2-debian-12-r12
    networks:
      - net-kafka
    deploy:
      << : *default-deploy
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "101@kafka:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://localhost:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_NODE_ID: 101
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/log
      KAFKA_CFG_METADATA_LOG_DIR: /bitnami/kafka/metadata
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 1

    healthcheck:
      << : *gnss-healthcheck
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/localhost/9092'"]

    volumes:
      - kafka-data:/bitnami
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  kafka-data:

networks:
  net-kafka:
```

3. Starting up the stack including kafka works with healtcheck section removed.
4. put healtcheck section in stack file and redeploy stack
5. Regardless of start_period, the container fails to start and below error is encountered(again and again) until swarm service fails

### What is the expected behavior?

kafka container starts also when healthcheck is in place

### What do you see instead?

the container repeat this log error, again and again, until it fails:
```
ziv_test_kafka.1.3meiqsciqou4   | [2025-03-25 14:55:05,215] WARN [BrokerToControllerChannelManager id=101 name=heartbeat] Error connecting to node kafka:9093 (id: 101 rack: null) (org.apache.kafka.clients.NetworkClient)
ziv_test_kafka.1.3meiqsciqou4   | java.net.UnknownHostException: kafka
ziv_test_kafka.1.3meiqsciqou4   |      at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
ziv_test_kafka.1.3meiqsciqou4   |      at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
ziv_test_kafka.1.3meiqsciqou4   |      at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
ziv_test_kafka.1.3meiqsciqou4   |      at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:122)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.resolveAddresses(ClusterConnectionStates.java:537)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:512)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.server.util.InterBrokerSendThread.sendRequests(InterBrokerSendThread.java:145)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:108)
ziv_test_kafka.1.3meiqsciqou4   |      at kafka.server.BrokerToControllerRequestThread.doWork(BrokerToControllerChannelManager.scala:421)
ziv_test_kafka.1.3meiqsciqou4   |      at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
ziv_test_kafka.1.3meiqsciqou4   | [2025-03-25 14:55:05,265] INFO [broker-101-to-controller-heartbeat-channel-manager]: Recorded new controller, from now on will use node kafka:9093 (id: 101 rack: null) (kafka.server.BrokerToControllerRequestThread)
```

also the following error can be shown:
```
ziv_test_kafka.1.3meiqsciqou4   | [2025-03-25 14:55:05,265] INFO [BrokerLifecycleManager id=101] Unable to register the broker because the RPC got timed out before it could be sent. (kafka.server.BrokerLifecycleManager)
```
### Additional information

no matter which command is used in the healthcheck, kafka container fails to start
i'm using kraft mode
even a simple test against the open port does not work. for example:
```yaml
healthcheck:
  start_period: 60s # Start after 1 minute
  interval: 60s # Check every 60 seconds
  retries: 5
  timeout: 15s
  test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/kafka/9092'"]
```
also, trying to run any relevant kafka script inside the /opt/bitnami/kafka/bin folder fails.
for example:
```yaml
healthcheck:
  start_period: 60s # Start after 1 minute
  interval: 60s # Check every 60 seconds
  retries: 5
  timeout: 15s
  test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092"]
```
