### ISSUE TITLE
[bitnami/suitecrm] Issue deploying container to AWS ECS

### ISSUE THREAD

**Issue by victor-hugo-dc** [bitnami/containers#79212]
### Name and Version

bitnami/suitecrm:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Follow the instructions in AWS Marketplace for Bitnami Container Solution for SuiteCRM
2. Set up a task definition in a cluster using AWS Fargate and also simultaneously set up an RDS database for the mariadb.
3. Set up environment variables.
4. Create a service and select on tasks.

### What is the expected behavior?

I am currently hosting a version of the Docker container for SuiteCRM in my home server and it works like a charm, the only problem is that since I don't have a DNS or certificate for my server, SuiteCRM won't allow API access (HTTPS must be enabled). So, I thought I could solve the problem by hosting on AWS, however that has been presenting it's own issues. It should work just fine like the home server does, basically a fully-functioning SuiteCRM application but that is not what I am getting.

### What do you see instead?

Instead, the task is stalling for some reason. It gets to a certain point and then does not finish connecting to the database / finishing the full SuiteCRM installation. This is the tail of the logs that I see:
```
[suitecrm] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.63 (Unix) OpenSSL/3.0.15 configured -- resuming normal operations
[suitecrm] [core:notice] [pid 1:tid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
[suitecrm] ==> ** Starting Apache **
[suitecrm] ==> ** Starting cron **
[suitecrm] ==> ** SuiteCRM setup finished! **
[suitecrm] ==> Persisting SuiteCRM installation
[suitecrm] ==> apache stopped
[suitecrm] ==> Stopping apache
[suitecrm] ==> Running setup wizard
[suitecrm] ==> apache started
[suitecrm] ==> Starting apache in background
[suitecrm] ==> Trying to connect to the database server
[suitecrm] ==> Ensuring SuiteCRM directories exist
[suitecrm] ==> Validating settings in MYSQL_CLIENT_* env vars
[suitecrm] ==> Setting PHP output_buffering option
[suitecrm] ==> Setting PHP expose_php option
[suitecrm] ==> Configuring PHP options
[suitecrm] ==> Configuring Apache ServerTokens directive
```
and then it just hangs there forever without completing. I am unsure if I am just being ignorant and not knowing how to set this container up in AWS ECS or if there is something wrong, but would appreciate some guidance or maybe some more specific documentation.

### Additional information

The following is the docker-compose file that works for me:
```
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_EXTRA_FLAGS=--innodb_use_native_aio=0
    volumes:
      - mariadb_data:/bitnami/mariadb
    healthcheck:
      test: mysqladmin ping -uroot -p"$${MARIADB_ROOT_PASSWORD}"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - suitecrm-net

  suitecrm:
    image: docker.io/bitnami/suitecrm:8
    container_name: atm-suitecrm
    ports:
      - '8001:8080' # had to run a custom port on my server, not doing this on AWS though
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_USER=${MARIADB_USER}
      - SUITECRM_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - SUITECRM_DATABASE_NAME=${MARIADB_DATABASE}
      - SUITECRM_DATABASE_CREATE_DATABASE=yes
      # Hosting Configuration
      - SUITECRM_HOST=${SUITECRM_HOST}
      - SUITECRM_EXTERNAL_HTTP_PORT_NUMBER=${SUITECRM_EXTERNAL_HTTP_PORT_NUMBER}
      - SUITECRM_ENABLE_HTTPS=no
      # Gmail Email Configuration
      - SUITECRM_SMTP_HOST=${SUITECRM_SMTP_HOST}
      - SUITECRM_SMTP_PORT_NUMBER=${SUITECRM_SMTP_PORT_NUMBER}
      - SUITECRM_SMTP_PROTOCOL=${SUITECRM_SMTP_PROTOCOL}
      - SUITECRM_SMTP_USER=${SUITECRM_SMTP_USER}
      - SUITECRM_SMTP_PASSWORD=${SUITECRM_SMTP_PASSWORD}
      - SUITECRM_SMTP_NOTIFY_ADDRESS=${SUITECRM_SMTP_NOTIFY_ADDRESS}
      - SUITECRM_SMTP_NOTIFY_NAME=${SUITECRM_SMTP_NOTIFY_NAME}
      # Debugging
      - BITNAMI_DEBUG=true
      - SUITECRM_SKIP_INSTALLATION=no
      - SUITECRM_VALIDATE_USER_IP=false
      # Admin Configuration
      - SUITECRM_USERNAME=${SUITECRM_USERNAME}
      - SUITECRM_PASSWORD=${SUITECRM_PASSWORD}
    volumes:
      - suitecrm_data:/bitnami/suitecrm
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - suitecrm-net

volumes:
  mariadb_data:
  suitecrm_data:

networks:
  suitecrm-net:
```
My goal is to get this exact configuration working in an ECS instance.
