### ISSUE TITLE
[bitnami/ebjca] Container stops at "Creating wildfly management user...", no futher logs printed

### ISSUE THREAD

**Issue by TheNighthawk99** [bitnami/containers#79435]
### Name and Version

bitname/ejbca:9.1.1 (latest at the time writing)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello,
I have just created the following stack through Portainer:

```yaml
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - dbvol:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "no"
      MARIADB_USER: ejbca
      MARIADB_DATABASE: ejbca__db
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/root_password
    secrets:
      - db_password
      - root_password
    networks:
      - backend_net
      
  ejbca:
    image: bitnami/ejbca:latest
    depends_on:
      - mariadb
    ports:
      - 8083:8080
      - 8403:8443
      - 8009:8009
    volumes:
      - appvol:/bitnami/wildfly
    environment:
      EJBCA_DATABASE_HOST: mariadb
      EJBCA_DATABASE_NAME: ejbca__db
      EJBCA_DATABASE_USERNAME: ejbca
      EJBCA_DATABASE_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - backend_net
    deploy:
      restart_policy:
        condition: none
        
secrets:
  db_password:
    external: true
  root_password:
    external: true

networks:
  backend_net:
    name: mariadb_backend_network
    external: true

volumes:
  dbvol:
    driver: local
  appvol:
    driver: local
```

MariaDB container has been created successfully, no errors in log.
EJBCA has matters. See below.

### What do you see instead?

EJBCA service/container fails with no reason.
This is the log:

```
ejbca 09:31:33.48 INFO  ==> 
ejbca 09:31:33.48 INFO  ==> Welcome to the Bitnami ejbca container
ejbca 09:31:33.49 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
ejbca 09:31:33.49 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
ejbca 09:31:33.50 INFO  ==> 
ejbca 09:31:33.53 INFO  ==> ** Starting ejbca setup **
ejbca 09:31:33.59 WARN  ==> Skipping export of 'EJBCA_WILDFLY_ADMIN_PASSWORD'. '/opt/bitnami/wildfly/tmp/wildfly_admin.pwd' is not readable.
ejbca 09:31:33.59 INFO  ==> Validating settings in EJBCA_* env vars...
ejbca 09:31:33.60 INFO  ==> Initializing EJBCA...
ejbca 09:31:33.62 INFO  ==> Deploying EJBCA from scratch
ejbca 09:31:48.94 INFO  ==> Creating database tables and indexes
ejbca 09:31:50.34 INFO  ==> Creating wildfly management user...
```

It looks like having issues when creating the wildfly management user, because I get no other text after that.
I cannot investigate furtherly.

### Additional information

Docker version is 28.0.4, it is installed on a virtual machine running Ubuntu Server 22.04LTS.
