### ISSUE TITLE
Moodle: it's container dies after trying to connect via localhost

### ISSUE THREAD

**Issue by TessellateDataScience** [bitnami/containers#80132]
### Name and Version

bitnami/moodle:4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configure .yml:
```yaml
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      #- 'mariadb_data:/bitnami/mariadb'
      - ./mariadb_data:/bitnami/mariadb
  moodle:
    image: docker.io/bitnami/moodle:4.5
    ports:
      - '8080:8080'
      - '8443:8443'
      #- 127.0.0.1:8080:8080
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
volumes:
  moodledata_data:
    driver: local
```
 
3. docker-compose up -d

4. http://localhost:8080

### What do you see instead?

Before connecting:
PORTS:  0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp 
After connection attempt:
PORTS: None

### Additional information

Docker running on Windows 11.
