### ISSUE TITLE
CASSANDRA_STARTUP_CQL does not run it's file

### ISSUE THREAD

**Issue by mcDandy** [bitnami/containers#80443]
### Name and Version

bitnami/cassandra:5.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. create a Dockerfile which copies a .cql file and runs cassandra
2. create a docker-compose.yaml running the docker image with environment variable of `CASSANDRA_STARTUP_CQL` set to desired file.
3. docker compose up
4. wait for cassandra to start

### What is the expected behavior?

I would expact pointing `CASSANDRA_STARTUP_CQL` to a script would run it after start of cassandra.

### What do you see instead?

Cassandra starts. Nothing else happens.

### Additional information

part of docker compose:
```yaml
networks:
  cassandra-net:
    driver: bridge

services:

  cassandra-1:
    build: .  
    container_name: "cassandra-1"
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_SEEDS=cassandra-1,cassandra-4,cassandra-7
      
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator 
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=******
      
      - CASSANDRA_STARTUP_CQL=/init.cql
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    restart:
      on-failure
    # command: /st.sh
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
...
```
part of Dockerfile
```Dockerfile
FROM "bitnami/cassandra:latest"
USER root
RUN apt-get update
RUN apt-get install curl -y
COPY ./script_run/importData.cql init.cql
RUN useradd cassandra
RUN ln -s /opt/bitnami/cassandra /opt/cassandra
RUN chown -R cassandra:cassandra /opt/bitnami/cassandra
RUN curl...
```
