### ISSUE TITLE
[bitnami/kafka] how to support hostname and local

### ISSUE THREAD

**Issue by albert-get** [bitnami/containers#80441]
### Name and Version

bitnami/kafka:3.5.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1,kafka compose conf
```
kafka:
    image: bitnami/kafka:3.5.1
    ports:
      - 19094:9094
    user: root
    restart: always
    volumes:
      - "${DATA_DIR}/components/kafka:/bitnami/kafka"
    environment:
      TZ: Asia/Shanghai
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://lenchif.com:19094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLIENT_USERS: xxxxx
      KAFKA_CLIENT_PASSWORDS: xxxxxx
```
2,use golang github.com/IBM/sarama
```
producer, err := sarama.NewSyncProducer([]string{os.Getenv("KAFKA_ADDR")}, KafkaProducerConfig())
```
3,
```
KAFKA_ADDR=lenchif.com:19094 is success
```
build run with docker KAFKA_ADDR=kafka:9092 , failed
lenchif.com only support ipv6,so docker canot use

### What do you see instead?
```
2025/04/20 08:47:42 kafka: client has run out of available brokers to talk to: dial tcp 172.18.0.3:9092: connect: connection refused
panic: kafka: client has run out of available brokers to talk to: dial tcp 172.18.0.3:9092: connect: connection refused


goroutine 1 [running]:
log.Panicln({0xc000033e68?, 0xa?, 0x0?})
        /Users/harry/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.darwin-arm64/src/log/log.go:446 +0x5a
yuanyou/initial.ProducerClient()
        /Users/harry/Desktop/social/initial/kafka.go:952 +0x9c
main.main()
        /Users/harry/Desktop/social/cmd/backend/main.go:32 +0xea
```
