### ISSUE TITLE
[bitnami/wordpress]: Startup Script Fails with "Permission Denied" on Volume

### ISSUE THREAD

**Issue by MikeK184** [bitnami/containers#80651]
### Name and Version

bitnami/wordpress:6.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using the Bitnami WordPress Docker image (e.g., `bitnami/wordpress:6.8.0`) with Docker Compose and a named volume for persistent data (/bitnami/wordpress), the container fails to correctly initialize permissions during startup, even when `WORDPRESS_RESET_DATA_PERMISSIONS=yes` is set in the environment. This issue was particularly noted when attempting to restore a website backup using the Duplicator Pro plugin.  The root cause appears to be the container startup script's inability to correct permissions on the volume.

### What is the expected behavior?

The container startup script, respecting WORDPRESS_RESET_DATA_PERMISSIONS=yes, should successfully set the necessary permissionson the contents of the /bitnami/wordpress volume mount, allowing WordPress and plugins like Duplicator Pro to function correctly without further manual intervention on the host.

### What do you see instead?

The container startup logs show errors indicating that the script itself lacks permission to modify files within the volume, despite WORDPRESS_RESET_DATA_PERMISSIONS=yes being set. Key log messages include (note the mention of Duplicator Pro's backup directory alongside standard WordPress directories):

```
wordpress | WARN  ==> The WordPress configuration file '/opt/bitnami/wordpress/wp-config.php' is not writable. Configurations based on environment variables will not be applied for this file.
wordpress | ...
wordpress | WARN  ==> Resetting file permissions in persisted volume
wordpress | find: '/bitnami/wordpress/wp-content/plugins': Permission denied
wordpress | find: '/bitnami/wordpress/wp-content/upgrade-temp-backup': Permission denied
wordpress | find: '/bitnami/wordpress/wp-content/uploads': Permission denied
wordpress | find: '/bitnami/wordpress/wp-content/themes': Permission denied
wordpress | find: '/bitnami/wordpress/wp-content/languages': Permission denied
wordpress | find: '/bitnami/wordpress/wp-content/backups-dup-pro': Permission denied # <--- Duplicator Pro directory
wordpress | find: '/bitnami/wordpress/wp-content/upgrade': Permission denied
wordpress | find: '/bitnami/wordpress/wp-content/mu-plugins': Permission denied
```

There were also errors, not sure if this is caused by the initial issue or that the duplicator plugin has an issue:
```log
[Wed Apr 30 07:35:39.981535 2025] [php:error] [pid 293:tid 293] [client 195.181.166.158:50967] PHP Fatal error:  Uncaught Error: Class "Duplicator\\Libs\\WpConfig\\WPConfigTransformerSrc" not found in /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php:1735\nStack trace:\n#0 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php(1695): DUPX_S3_Funcs->obscureWpConfig()\n#1 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php(1634): DUPX_S3_Funcs->wpConfigFinalReport()\n#2 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php(151): DUPX_S3_Funcs->finalReportNotices()\n#3 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.ajax.php(233): DUPX_S3_Funcs->updateWebsite()\n#4 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.ajax.php(110): DUPX_Ctrl_ajax::actions()\n#5 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php(47): DUPX_Ctrl_ajax::controller()\n#6 {main}\n  thrown in /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php on line 1735, referer: https://domain.com/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B1314D253171&step_action=init
[Wed Apr 30 07:35:39.981763 2025] [php:error] [pid 293:tid 293] [client 195.181.166.158:50967] PHP Fatal error:  Uncaught Exception: [PHP ERR][E_ERROR] MSG:Uncaught Error: Class "Duplicator\\Libs\\WpConfig\\WPConfigTransformerSrc" not found in /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php:1735\nStack trace:\n#0 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php(1695): DUPX_S3_Funcs->obscureWpConfig()\n#1 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php(1634): DUPX_S3_Funcs->wpConfigFinalReport()\n#2 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php(151): DUPX_S3_Funcs->finalReportNotices()\n#3 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.ajax.php(233): DUPX_S3_Funcs->updateWebsite()\n#4 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.ajax.php(110): DUPX_Ctrl_ajax::actions()\n#5 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php(47): DUPX_Ctrl_ajax::controller()\n#6 {main}\n  thrown [CODE:1|FILE:/bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/ctrls/classes/class.ctrl.s3.funcs.php|LINE:1735] in /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/src/Utils/Log/Log.php:410\nStack trace:\n#0 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/src/Utils/Log/LogHandler.php(95): Duplicator\\Installer\\Utils\\Log\\Log::error()\n#1 /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/src/Utils/Log/LogHandler.php(257): Duplicator\\Installer\\Utils\\Log\\LogHandler::error()\n#2 [internal function]: Duplicator\\Installer\\Utils\\Log\\LogHandler::shutdown()\n#3 {main}\n  thrown in /bitnami/wordpress/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/src/Utils/Log/Log.php on line 410, referer: https://domain.com/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B&step_action=init
195.181.166.158 - - [30/Apr/2025:07:35:41 +0000] "-" 408 -
195.181.166.158 - - [30/Apr/2025:07:35:45 +0000] "POST /wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B1314D253171&step_action=init HTTP/1.1" 403 261
[Wed Apr 30 07:35:45.084757 2025] [core:crit] [pid 276:tid 276] (13)Permission denied: [client 195.181.166.158:23419] AH00529: /opt/bitnami/wordpress/wp-content/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/opt/bitnami/wordpress/wp-content/' is executable, referer: https://domain.com/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B1314D253171&step_action=init
[Wed Apr 30 07:35:50.186505 2025] [core:crit] [pid 264:tid 264] (13)Permission denied: [client 195.181.166.158:23423] AH00529: /opt/bitnami/wordpress/wp-content/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/opt/bitnami/wordpress/wp-content/' is executable, referer: https://domain.com/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B1314D253171&step_action=init
195.181.166.158 - - [30/Apr/2025:07:35:50 +0000] "POST /wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B1314D253171&step_action=init HTTP/1.1" 403 261
195.181.166.158 - - [30/Apr/2025:07:35:58 +0000] "GET /wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/dup-installer-log__ed979f2-29191950.txt?now=073521 HTTP/1.1" 403 261
[Wed Apr 30 07:35:58.964532 2025] [core:crit] [pid 278:tid 278] (13)Permission denied: [client 195.181.166.158:12711] AH00529: /opt/bitnami/wordpress/wp-content/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/opt/bitnami/wordpress/wp-content/' is executable, referer: https://domain.com/wp-content/backups-dup-pro/imports/dup-installer-200398a-29191950/main.installer.php?ctrl_action=ctrl-step1&ctrl_csrf_token=2F38A18F35C6CF589AE688749E4D2BB4D8EE8F8F00ED9ADFD9D7B1314D253171&step_action=init
```

Checking the volume's mount point on the Docker host (/var/lib/docker/volumes/wordpress_wordpress_data/_data in my case, identified via docker volume inspect) revealed initial ownership/permissions like:

```
$ sudo ls -ld /var/lib/docker/volumes/wordpress_wordpress_data/_data
drwxrwxr-x 4 daemon root 4096 Feb  6 09:31 /var/lib/docker/volumes/wordpress_wordpress_data/_data
```

The issue was resolved by manually changing the ownership and permissions on the Docker host for the volume's mount point:

```
sudo chown -R 1001:1001 /var/lib/docker/volumes/wordpress_wordpress_data/_data
sudo chmod -R u+rwX,g+rX,o+rX /var/lib/docker/volumes/wordpress_wordpress_data/_data
```
After applying these commands on the host and restarting the container, the "Permission denied" errors during startup disappeared, and WordPress operations seem to function correctly.

### Additional information

**Question**
Is this manual intervention (`chown 1001:1001` on the host) the expected procedure when using named volumes with the Bitnami WordPress container? Or should the container's entrypoint script be robust enough to handle the initial permission setup on the volume data, especially when` WORDPRESS_RESET_DATA_PERMISSIONS=yes` is explicitly set, regardless of the initial ownership (like `daemon:root`) assigned by Docker or the host system when the volume is first created? This is particularly relevant when performing operations like site restorations with plugins (e.g., Duplicator Pro) that heavily rely on correct file permissions within` wp-content`.

---

This is my docker-compose.yaml:
```yaml
services:
  wp-mariadb:
    image: bitnami/mariadb:11.4.5
    container_name: wp-mariadb
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - wp_network
      - monitoring
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - mariadb_data:/bitnami/mariadb

  wp-wordpress:
    image: bitnami/wordpress:6.8.0
    container_name: wp-wordpress
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - wp_network
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - WORDPRESS_DATABASE_HOST=wp-mariadb
      - WORDPRESS_DATABASE_USER=${WORDPRESS_DATABASE_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${WORDPRESS_DATABASE_NAME}
      - WORDPRESS_USERNAME=${WORDPRESS_USERNAME}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_SMTP_HOST=${WORDPRESS_SMTP_HOST}
      - WORDPRESS_SMTP_PORT=${WORDPRESS_SMTP_PORT}
      - WORDPRESS_SMTP_USER=${WORDPRESS_SMTP_USER}
      - WORDPRESS_SMTP_PASSWORD=${WORDPRESS_SMTP_PASSWORD}
      - WORDPRESS_SMTP_PROTOCOL=${WORDPRESS_SMTP_PROTOCOL}
      - WORDPRESS_ENABLE_HTTPS=${WORDPRESS_ENABLE_HTTPS}
      - WORDPRESS_SCHEME=${WORDPRESS_SCHEME}
      - WORDPRESS_HTACCESS_OVERRIDE_NONE=${WORDPRESS_HTACCESS_OVERRIDE_NONE}
      - WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=${WORDPRESS_ENABLE_HTACCESS_PERSISTENCE}
      - WORDPRESS_RESET_DATA_PERMISSIONS=${WORDPRESS_RESET_DATA_PERMISSIONS}
    volumes:
      - wordpress_data:/bitnami/wordpress

  # wp-phpmyadmin:
  #   image: bitnami/phpmyadmin:latest
  #   container_name: wp-phpmyadmin
  #   restart: always
  #   security_opt:
  #     - no-new-privileges:true
  #   networks:
  #     - wp_network
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #   environment:
  #     - DATABASE_HOST=wp-mariadb
  #     - DATABASE_PORT_NUMBER=3306

networks:
  wp_network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
```

With the relevant .env variables:
```env
WORDPRESS_ENABLE_HTTPS=yes
WORDPRESS_SCHEME=https
WORDPRESS_HTACCESS_OVERRIDE_NONE=no
WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=yes
WORDPRESS_RESET_DATA_PERMISSIONS=yes
```
