### ISSUE TITLE
[bitnami/scylladb]: Incorrect indentation in scylla.yaml file when encryption enabled

### ISSUE THREAD

**Issue by onebitshort** [bitnami/containers#80659]
### Name and Version

bitnami/scylladb:6.2.3-debian-12-r5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

docker compose up and inspect "/opt/bitnami/scylladb/etc/scylla/scylla.yaml" using the following docker-compose file:

docker-compose.yaml
```yaml
services:
  scylladb: 
    image: bitnami/scylladb:6.2.3-debian-12-r5
    command: [ "/opt/bitnami/scripts/scylladb/run.sh", "--smp", "1", "--memory", "1G" ]
    restart: on-failure
    environment:
      - SCYLLADB_CLIENT_ENCRYPTION=true
    volumes:
      - type: bind
        source: ./tls.key
        target: /bitnami/scylladb/certs/tls.key
      - type: bind
        source: ./tls.crt
        target: /bitnami/scylladb/certs/tls.crt
```

### What is the expected behavior?

I expect to see the respective parts of the scylla.yaml file is indented correctly. 
```
 server_encryption_options:
   internode_encryption: 'none'
   certificate: '/bitnami/scylladb/certs/tls.crt'
   keyfile: '/bitnami/scylladb/certs/tls.key'
 
 client_encryption_options:
   enabled: false
   certificate: '/bitnami/scylladb/certs/tls.crt'
   keyfile: '/bitnami/scylladb/certs/tls.key'
```

### What do you see instead?

Take a look at the "/opt/bitnami/scylladb/etc/scylla/scylla.yaml" file within the container when started up with the SCYLLADB_CLIENT_ENCRYPTION env variable set to true.

The client encryption section is not correctly indented. I believe this is the case for the server_encryption_options too. 

The relevant section of the scylla.yaml file:
```yaml
# Enable or disable inter-node encryption. 

# You must also generate keys and provide the appropriate key and trust store locations and passwords. 

#

# The available internode options are : all, none, dc, rack

# If set to dc scylla  will encrypt the traffic between the DCs

# If set to rack scylla  will encrypt the traffic between the racks

#

# SSL/TLS algorithm and ciphers used can be controlled by 

# the priority_string parameter. Info on priority string

# syntax and values is available at:

#   https://gnutls.org/manual/html_node/Priority-Strings.html

#

# The require_client_auth parameter allows you to 

# restrict access to service based on certificate 

# validation. Client must provide a certificate 

# accepted by the used trust store to connect.

# 

server_encryption_options:

internode_encryption: 'none'

certificate: '/bitnami/scylladb/certs/tls.crt'

keyfile: '/bitnami/scylladb/certs/tls.key'

#    truststore: <not set, use system trust>

#    certficate_revocation_list: <not set>

#    require_client_auth: False

#    priority_string: <not set, use default>



# enable or disable client/server encryption.

client_encryption_options:

   enabled: false

certificate: '/bitnami/scylladb/certs/tls.crt'

keyfile: '/bitnami/scylladb/certs/tls.key'

#    truststore: <not set, use system trust>

#    certficate_revocation_list: <not set>

#    require_client_auth: False

#    priority_string: <not set, use default>
```
