### ISSUE TITLE
[bitnami/postgresql] postgresql permissions and background worker "logical replication launcher" (PID 204) exited with exit code 1

### ISSUE THREAD

**Issue by mustafakibar** [bitnami/containers#80708]
### Name and Version

bitnami/postgresql:14.17.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Previously, when using an official postgresql image, my `postgres-core` and `postgres-extd` services ran normally with the configuration mentioned below. However, after switching the image to `bitnami/postgresql`, I began encountering permission errors. 

Despite attempting various solutions, including adjusting permissions (like `chown`, `chmod`), I consistently observed the same error logs as shown below. For each attempt involving `chown` or `chmod`, I made sure to remove and recreate the services beforehand, but the issue persisted.  

In addition to the variables used by the `bitnami/postgresql` image, like `POSTGRESQL_DATABASE`, I also added variables like `POSTGRES_DB`, thinking this might be the source of the problem, but it didn't work. 

The `postgres_core_data` and `postsgres_extd_data` directories appear empty (contents not included here). The system has over `4GB` of available memory.

I've only included the relevant sections of my service definitions and .env file.

`Docker version: 27.5.1, build 9f9e405`

### What do you see instead?

postgres-core logs:
```
postgresql 12:11:24.98 INFO  ==> 
postgresql 12:11:24.98 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 12:11:24.98 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 12:11:24.99 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
postgresql 12:11:24.99 INFO  ==> 
postgresql 12:11:25.00 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:11:25.02 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 12:11:25.02 INFO  ==> Loading custom pre-init scripts...
postgresql 12:11:25.03 INFO  ==> Initializing PostgreSQL database...
postgresql 12:11:25.04 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 12:11:25.04 INFO  ==> Generating local authentication configuration
postgresql 12:11:25.66 INFO  ==> Starting PostgreSQL in background...
postgresql 12:11:26.77 INFO  ==> Creating user kibar_core
postgresql 12:11:26.78 INFO  ==> Granting access to "kibar_core" to the database "kibar_core"
postgresql 12:11:26.81 INFO  ==> Setting ownership for the 'public' schema database "kibar_core" to "kibar_core"
postgresql 12:11:26.83 INFO  ==> Configuring replication parameters
postgresql 12:11:26.85 INFO  ==> Configuring synchronous_replication
postgresql 12:11:26.85 INFO  ==> Configuring fsync
postgresql 12:11:26.87 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 12:11:26.98 INFO  ==> Loading custom scripts...
postgresql 12:11:26.98 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 12:11:26.99 INFO  ==> Starting PostgreSQL in background...
postgresql 12:11:28.35 INFO  ==> Enabling remote connections
postgresql 12:11:28.36 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 12:11:28.46 INFO  ==> ** PostgreSQL setup finished! **
postgresql 12:11:28.48 INFO  ==> ** Starting PostgreSQL **
2025-05-05 12:11:28.499 GMT [1] LOG:  pgaudit extension initialized
2025-05-05 12:11:28.503 GMT [1] LOG:  starting PostgreSQL 14.17 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-05-05 12:11:28.503 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-05-05 12:11:28.503 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2025-05-05 12:11:28.507 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2025-05-05 12:11:28.510 GMT [198] LOG:  database system was shut down at 2025-05-05 12:11:28 GMT
2025-05-05 12:11:28.514 GMT [1] LOG:  database system is ready to accept connections
2025-05-05 12:13:38.604 GMT [1] LOG:  received smart shutdown request
2025-05-05 12:13:38.607 GMT [1] LOG:  background worker "logical replication launcher" (PID 204) exited with exit code 1
2025-05-05 12:13:38.608 GMT [199] LOG:  shutting down
2025-05-05 12:13:38.620 GMT [1] LOG:  database system is shut down
```

postgres-extd logs:
```
postgresql 12:11:31.15 INFO  ==> 
postgresql 12:11:22.40 INFO  ==> 
postgresql 12:11:31.15 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 12:11:22.40 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 12:11:31.15 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 12:11:22.40 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 12:11:31.15 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
postgresql 12:11:31.15 INFO  ==> 
postgresql 12:11:22.40 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
postgresql 12:11:31.16 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:11:22.40 INFO  ==> 
postgresql 12:11:13.57 INFO  ==> 
postgresql 12:11:31.18 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 12:11:22.41 INFO  ==> ** Starting PostgreSQL setup **
postgresql 12:11:31.19 INFO  ==> Loading custom pre-init scripts...
postgresql 12:11:13.57 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 12:11:31.19 INFO  ==> Initializing PostgreSQL database...
postgresql 12:11:13.58 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 12:11:22.43 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 12:11:31.20 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 12:11:22.44 INFO  ==> Loading custom pre-init scripts...
postgresql 12:11:22.44 INFO  ==> Initializing PostgreSQL database...
postgresql 12:11:31.20 INFO  ==> Generating local authentication configuration
postgresql 12:11:22.45 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 12:11:31.87 INFO  ==> Starting PostgreSQL in background...
postgresql 12:11:22.45 INFO  ==> Generating local authentication configuration
postgresql 12:11:23.14 INFO  ==> Starting PostgreSQL in background...
postgresql 12:11:32.97 INFO  ==> Creating user kibar_extd
postgresql 12:11:24.25 INFO  ==> Creating user kibar_extd
postgresql 12:11:24.27 INFO  ==> Granting access to "kibar_extd" to the database "kibar_extd"
postgresql 12:11:32.98 INFO  ==> Granting access to "kibar_extd" to the database "kibar_extd"
postgresql 12:11:24.29 INFO  ==> Setting ownership for the 'public' schema database "kibar_extd" to "kibar_extd"
postgresql 12:11:33.01 INFO  ==> Setting ownership for the 'public' schema database "kibar_extd" to "kibar_extd"
postgresql 12:11:33.03 INFO  ==> Configuring replication parameters
postgresql 12:11:33.06 INFO  ==> Configuring synchronous_replication
postgresql 12:11:33.06 INFO  ==> Configuring fsync
postgresql 12:11:33.09 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 12:11:33.19 INFO  ==> Loading custom scripts...
postgresql 12:11:33.20 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 12:11:33.20 INFO  ==> Starting PostgreSQL in background...
--- Grafana DB Setup on postgres-extd Starting ---
Target Grafana DB: kibar_grafana
Target Grafana User: kibar_grafana
Connecting as user: kibar_extd to DB: kibar_extd
ERROR:  permission denied to create role
CONTEXT:  SQL statement "CREATE USER kibar_grafana WITH PASSWORD '#REMOVED#"
PL/pgSQL function inline_code_block line 4 at SQL statement
postgresql 12:11:34.25 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
```

### Additional information

.env file:
```
POSTGRES_CORE_USER=kibar_core
POSTGRES_EXTD_USER=kibar_extd
POSTGRES_CORE_DATABASE_NAME=kibar_core
POSTGRES_EXTD_DATABASE_NAME=kibar_extd
POSTGRESQL_GRAFANA_DATABASE=kibar_grafana
POSTGRESQL_GRAFANA_USERNAME=kibar_grafana
```

Service yml file:
```
services:
  postgres-core:
    image: bitnami/postgresql:${POSTGRES_VERSION}
    networks:
      - apps_overlay
    configs:
      - source: postgres-core
        target: /etc/postgresql/conf.d/sn-postgres.conf
    secrets:
      - postgres_core_password
    volumes:
      - ./db/core-init-scripts:/docker-entrypoint-initdb.d:ro
      - postgres_core_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_CORE_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_CORE_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_core_password
      POSTGRESQL_DATABASE: ${POSTGRES_CORE_DATABASE_NAME}
      POSTGRESQL_USERNAME: ${POSTGRES_CORE_USER}
      POSTGRESQL_PASSWORD_FILE: /run/secrets/postgres_core_password
      POSTGRESQL_TIMEZONE: ${TZ}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_CORE_DATABASE_NAME} -U $${POSTGRES_CORE_USER}']
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 60s
    deploy:
      replicas: ${POSTGRES_CORE_REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        logging: promtail
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  postgres-extd:
    image: bitnami/postgresql:${POSTGRES_VERSION}
    networks:
      - auth_overlay
    configs:
      - source: postgres-extd
        target: /etc/postgresql/conf.d/sn-postgres.conf
    secrets:
      - grafana_db_password
      - postgres_extd_password
    volumes:
      - ./db/extd-init-scripts:/docker-entrypoint-initdb.d:ro
      - postgres_extd_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_EXTD_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_EXTD_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_extd_password
      POSTGRESQL_DATABASE: ${POSTGRES_EXTD_DATABASE_NAME}
      POSTGRESQL_USERNAME: ${POSTGRES_EXTD_USER}
      POSTGRESQL_PASSWORD_FILE: /run/secrets/postgres_extd_password
      POSTGRESQL_GRAFANA_DATABASE: ${POSTGRESQL_GRAFANA_DATABASE}
      POSTGRESQL_GRAFANA_USERNAME: ${POSTGRESQL_GRAFANA_USERNAME}
      POSTGRESQL_GRAFANA_PASSWORD_FILE: /run/secrets/grafana_db_password
      POSTGRESQL_TIMEZONE: ${TZ}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_EXTD_DATABASE_NAME} -U $${POSTGRES_EXTD_USER}']
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 60s
    deploy:
      replicas: ${POSTGRES_EXTD_REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        logging: promtail
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

secrets:
  postgres_core_password:
    external: true
  postgres_extd_password:
    external: true
  grafana_db_password:
    external: true

configs:
  postgres-core:
    external: true
  postgres-extd:
    external: true

volumes:
  postgres_core_data:
    name: "postgres_core_data"
    driver: local
    driver_opts:
      type: none
      device: /mnt/kibar/postgres_core_data
      o: bind
  postgres_extd_data:
    name: "postgres_extd_data"
    driver: local
    driver_opts:
      type: none
      device: /mnt/kibar/postgres_extd_data
      o: bind

```

init script for postgres-extd:
```
#!/bin/bash

set -e

EXTD_PASSWORD=$(cat /run/secrets/postgres_extd_password)
export PGPASSWORD="$EXTD_PASSWORD"

GRAFANA_DB=${POSTGRESQL_GRAFANA_DATABASE}
GRAFANA_USER=${POSTGRESQL_GRAFANA_USERNAME}
GRAFANA_PASSWORD=$(cat /run/secrets/grafana_db_password)

CONNECT_USER=${POSTGRESQL_USERNAME}
CONNECT_DB=${POSTGRESQL_DATABASE}

echo "--- Grafana DB Setup on postgres-extd Starting ---"
echo "Target Grafana DB: $GRAFANA_DB"
echo "Target Grafana User: $GRAFANA_USER"
echo "Connecting as user: $CONNECT_USER to DB: $CONNECT_DB"

psql -v ON_ERROR_STOP=1 --username "$CONNECT_USER" --dbname "$CONNECT_DB" <<-EOSQL
    DO \$\$
    BEGIN
       IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$GRAFANA_USER') THEN
          CREATE USER $GRAFANA_USER WITH PASSWORD '$GRAFANA_PASSWORD';
          RAISE NOTICE 'User "$GRAFANA_USER" created.';
       ELSE
          RAISE NOTICE 'User "$GRAFANA_USER" already exists, skipping creation.';
       END IF;
    END
    \$\$;

    DO \$\$
    BEGIN
       IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '$GRAFANA_DB') THEN
          PERFORM dblink_exec('dbname=' || current_database(), 'CREATE DATABASE ' || quote_ident('$GRAFANA_DB'));
          RAISE NOTICE 'Database "$GRAFANA_DB" created.';
       ELSE
          RAISE NOTICE 'Database "$GRAFANA_DB" already exists, skipping creation.';
       END IF;
    END
    \$\$;

    ALTER DATABASE $GRAFANA_DB OWNER TO $GRAFANA_USER;
    RAISE NOTICE 'Owner of database "$GRAFANA_DB" set to "$GRAFANA_USER".';
EOSQL

unset PGPASSWORD

echo "--- Grafana DB Setup on postgres-extd Finished ---"
```

Directory permission:
```
drwxrwx---  2 kibar 1001 4,0K May  5 14:35 postgres_core_data/
drwxrwx---  2 kibar 1001 4,0K May  5 14:35 postgres_extd_data/
```
