### ISSUE TITLE
INFLUXDB_ADMIN_USER_PASSWORD of length < 8 fails without error message

### ISSUE THREAD

**Issue by mwmahlberg** [bitnami/containers#81083]
### Name and Version

bitnami/inflluxdb:2

### What architecture are you using?

None

### What steps will reproduce the bug?

With a docker-compose.yaml

```yaml
services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-123456}
      - INFLUXDB_USER_BUCKET=rms
      - INFLUXDB_ADMIN_USER_TOKEN=123456
    volumes:
      - influxdb_data:/bitnami/influxdb
    networks:
      - rms-refactor
networks:
  rms-refactor:
    driver: bridge
volumes:
  influxdb_data:
```

The startup fails without error message:

```plaintext
Attaching to influxdb-1
influxdb-1  | influxdb 10:57:50.56 INFO  ==> 
influxdb-1  | influxdb 10:57:50.57 INFO  ==> Welcome to the Bitnami influxdb container
influxdb-1  | influxdb 10:57:50.57 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
influxdb-1  | influxdb 10:57:50.59 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
influxdb-1  | influxdb 10:57:50.59 INFO  ==> 
influxdb-1  | influxdb 10:57:50.61 INFO  ==> ** Starting InfluxDB setup **
influxdb-1  | influxdb 10:57:50.67 INFO  ==> No injected configuration files found. Creating default config files...
influxdb-1  | influxdb 10:57:50.68 INFO  ==> Starting InfluxDB in background...
influxdb-1  | influxdb 10:57:51.23 INFO  ==> Deploying InfluxDB from scratch
influxdb-1  | influxdb 10:57:51.23 INFO  ==> Creating primary setup...
influxdb-1  | influxdb 10:57:51.28 INFO  ==> Stopping InfluxDB...
influxdb-1  | Terminated
influxdb-1 exited with code 1
```

whereas `INFLUXDB_ADMIN_PASSWORD=12345678 docker compose up` runs flawlessly.

### What is the expected behavior?

An error message should be printed on the containers stderr that the password length is < 8.

### What do you see instead?

The container fails without a meaningful error message.

### Additional information

I think the password length should be guarded, since it is enforced by the CLI, see influxdata/influxdb#19585
