### ISSUE TITLE
Error: The configuration file config.php already exists with Moodle.

### ISSUE THREAD

**Issue by kevinveenbirkenbach** [bitnami/containers#81439]
### Name and Version

bitnami/moodle:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

When I freshly initialize Moodle with this config:

docker-compose.yml:
``` 
services:

# This template needs to be included in docker-compose.yml, which depend on a mariadb database

  moodle:
    container_name: moodle
    build:
      context: .
      dockerfile: Dockerfile
    image: moodle_custom
    ports:
      - 127.0.0.1:8026:8080
# Base for docker services
    restart: unless-stopped
    env_file:
      - "/opt/docker/moodle/.env/env"
    logging:
      driver: journald


    volumes:
      - 'moodle:/bitnami/moodle'
      - 'data:/bitnami/moodledata'
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET / HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q 'HTTP/1.1'"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      central_mariadb:
      default:


volumes:

  moodle:
  data:

networks:
  central_mariadb:
    external: true
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.102.32/28
```

Dockerfile:
```
FROM bitnami/moodle:latest
```
 .env/env 
```
MOODLE_DATABASE_HOST=central-mariadb
##MOODLE_DATABASE_PORT_NUMBER=3306
MOODLE_DATABASE_USER=moodle
MOODLE_DATABASE_NAME=moodle
MOODLE_DATABASE_PASSWORD=examplepassword
#ALLOW_EMPTY_PASSWORD=no
#MOODLE_SITE_NAME="Global Learning Academy on cymais.cloud"
#MOODLE_SSLPROXY=yes
#MOODLE_REVERSE_PROXY=yes
MOODLE_USERNAME=admin
MOODLE_PASSWORD=adminpass
#MOODLE_EMAIL=administrator@cymais.cloud
BITNAMI_DEBUG=true
#MOODLE_SKIP_INSTALL=true
```

Setup with: 
https://github.com/kevinveenbirkenbach/cymais/tree/master/roles/docker-moodle

### What is the expected behavior?

I expect that the xontainer should start and setup automatic without any bugs.

### What do you see instead?

Instead I see:

```bash
moodle  | moodle 12:09:55.34 INFO  ==> Running Moodle install script
moodle  |                                  .-..-.       
moodle  |    _____                         | || |       
moodle  |   /____/-.---_  .---.  .---.  .-.| || | .---. 
moodle  |   | |  _   _  |/  _  \/  _  \/  _  || |/  __ \
moodle  |   * | | | | | || |_| || |_| || |_| || || |___/
moodle  |     |_| |_| |_|\_____/\_____/\_____||_|\_____)
moodle  | 
moodle  | Moodle 5.0 (Build: 20250414) command line installation program
moodle  | == Environment ==
moodle  | !! unicode !!
moodle  | [System] must be installed and enabled - All data must be stored in Unicode format (UTF-8). For new installations,
moodle  | the database must have UTF-8 as default character set. If you are
moodle  | upgrading, you need to follow the UTF-8 migration process.
moodle  | 
moodle  | 
moodle  | moodle 12:09:56.79 INFO  ==> 
moodle  | moodle 12:09:56.79 INFO  ==> Welcome to the Bitnami moodle container
moodle  | moodle 12:09:56.79 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle  | moodle 12:09:56.80 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
moodle  | moodle 12:09:56.80 INFO  ==> 
moodle  | moodle 12:09:56.81 INFO  ==> ** Starting Moodle setup **
moodle  | moodle 12:09:56.84 DEBUG ==> Validating settings in APACHE_* environment variables
moodle  | moodle 12:09:56.85 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
moodle  | realpath: /bitnami/apache/conf: No such file or directory
moodle  | moodle 12:09:56.86 INFO  ==> Configuring Apache ServerTokens directive
moodle  | moodle 12:09:56.86 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
moodle  | moodle 12:09:56.89 INFO  ==> Configuring PHP options
moodle  | moodle 12:09:56.90 INFO  ==> Setting PHP expose_php option
moodle  | moodle 12:09:56.91 INFO  ==> Setting PHP output_buffering option
moodle  | moodle 12:09:56.94 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
moodle  | moodle 12:09:56.94 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
moodle  | moodle 12:09:56.98 DEBUG ==> Validating settings in MOODLE_* environment variables...
moodle  | moodle 12:09:57.03 INFO  ==> Ensuring Moodle directories exist
moodle  | moodle 12:09:57.04 INFO  ==> Trying to connect to the database server
moodle  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle  | moodle 12:09:57.05 DEBUG ==> Executing SQL command:
moodle  | SELECT 1
moodle  | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
moodle  | 1
moodle  | moodle 12:09:57.06 INFO  ==> Running Moodle install script
moodle  | The configuration file config.php already exists. Please use admin/cli/install_database.php to install Moodle for this site.
moodle  |
```

It doesn't make a difference if I set

  - MOODLE_USERNAME=admin
  - MOODLE_PASSWORD=adminpass

or not, like recommended [here](https://github.com/bitnami/containers/issues/72747).

A configuration file is not present, also if the warning tells so. 

This effects my setup on [academy.cymais.cloud](https://academy,cymais.cloud).
My setup on [academy.veen.world](https://academy.veen.world/) isn't effected. I set it up with the image already a few years ago.

### Additional information

This error is related to [this issues](https://github.com/bitnami/containers/issues/72747) which I can't reopen.

**Comment by kevinveenbirkenbach** [comment]
No. I didn't find a solution yet. I also don't like to hack around, concerning this issue. I would prefer a clean permanent solution, because this seems like an obvious bug.

**Comment by jotamartos** [comment]
Hi,

I just tried to reproduce the issue but couldn't do so. The docker-compose.yml file I'm using is this one, I only added the lines to configure the user and password of the app and the database to the default docker-compose file we provide in the repo based on your comments

```
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=examplepassword
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:5.0
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=examplepassword
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpass
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

```


But everything worked as expected either when launching the solution the first time or after running the `docker-compose down` command

```
moodle-1  | moodle 09:49:09.67 INFO  ==> Ensuring Moodle directories exist
moodle-1  | moodle 09:49:09.93 INFO  ==> Trying to connect to the database server
moodle-1  | moodle 09:49:20.31 INFO  ==> Running Moodle install script
moodle-1  | moodle 09:49:55.39 INFO  ==> Persisting Moodle installation
moodle-1  | moodle 09:50:05.01 INFO  ==> ** Moodle setup finished! **
moodle-1  | 
moodle-1  | moodle 09:50:05.09 INFO  ==> ** Starting cron **
moodle-1  | moodle 09:50:05.18 INFO  ==> ** Starting Apache **
moodle-1  | [Mon Jun 09 09:50:05.382073 2025] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.63 (Unix) OpenSSL/3.0.16 configured -- resuming normal operations
moodle-1  | [Mon Jun 09 09:50:05.383732 2025] [core:notice] [pid 1:tid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```
