### ISSUE TITLE
[bitnami/ghost] Wrong SMTP encryption settings with GHOST_SMTP_PROTOCOL=tls

### ISSUE THREAD

**Issue by Tockra** [bitnami/containers#81470]
### Name and Version

bitnami/ghost:5.120.1-debian-12-r0 

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Start a docker container. e.g.
```yaml
services:
  mysql:
    image: docker.io/bitnami/mysql:latest
#    volumes:
#      - 'mysql_data:/bitnami/mysql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_ghost
      - MYSQL_DATABASE=bitnami_ghost
  ghost:
    image: docker.io/bitnami/ghost:5
    ports:
      - '80:2368'
#    volumes:
#      - 'ghost_data:/bitnami/ghost'
    depends_on:
      - mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_DATABASE_HOST=mysql
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - GHOST_SMTP_FROM_ADDRESS=gitea@it.financeflow.de
      - GHOST_SMTP_HOST=smtp-mail.outlook.com
      - GHOST_SMTP_PORT_NUMBER=587
      - GHOST_SMTP_USER=login
      - GHOST_SMTP_PASSWORD=pw
      - GHOST_SMTP_PROTOCOL=tls #<<<<<<<<<<<< Problem
      - LOG_LEVEL=DEBUG
      - BITNAMI_DEBUG=true
      - mail__options__logger=true
      - mail__options__debug=true
volumes:
  mysql_data:
    driver: local
  ghost_data:
    driver: local
``` 
2. Enter webpanel with `user@example.com` and `bitnami123`
3. Try to trigger a mail send and watch the errors in the logs regarding the smtp config

### What is the expected behavior?

A successful SMTP TLS connection

/bitnami/ghost/config.production.json sets `mail.options.secure=false` 

```
ghost-1  | [2025-05-23 09:31:57] DEBUG Sending mail using SMTP/6.10.1[client:6.10.1]
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] Resolved smtp-mail.outlook.com as 40.99.157.22 [cache miss]
ghost-1  | [2025-05-23 09:31:57] INFO  [2NJiyigUmk] Connection established to 40.99.157.22:587
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 220 FR2P281CA0105.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 23 May 2025 09:31:56 +0000 [08DD99CF309329D8]
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] C: EHLO [127.0.0.1]
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-FR2P281CA0105.outlook.office365.com Hello [79.195.37.115]
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-SIZE 157286400
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-PIPELINING
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-DSN
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-ENHANCEDSTATUSCODES
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-STARTTLS
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-8BITMIME
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-BINARYMIME
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-CHUNKING
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250 SMTPUTF8
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] C: STARTTLS
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 220 2.0.0 SMTP server ready
ghost-1  | [2025-05-23 09:31:57] INFO  [2NJiyigUmk] Connection upgraded with STARTTLS
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] C: EHLO [127.0.0.1]
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-FR2P281CA0105.outlook.office365.com Hello [79.195.37.115]
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-SIZE 157286400
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-PIPELINING
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-DSN
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-ENHANCEDSTATUSCODES
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-AUTH LOGIN XOAUTH2
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-8BITMIME
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-BINARYMIME
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250-CHUNKING
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] S: 250 SMTPUTF8
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] SMTP handshake finished
ghost-1  | [2025-05-23 09:31:57] DEBUG [2NJiyigUmk] C: AUTH LOGIN
...
```

### What do you see instead?

ghost tries to use SSL, which fails. 
```
ghost-1  | [2025-05-23 09:23:15] DEBUG [GV8o2uOQ0B8] Resolved smtp-mail.outlook.com as 52.98.179.134 [cache miss]
ghost-1  | [2025-05-23 09:23:15] ERROR [GV8o2uOQ0B8] 400410B9FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
ghost-1  | [2025-05-23 09:23:15] ERROR [GV8o2uOQ0B8]
ghost-1  | [2025-05-23 09:23:15] DEBUG [GV8o2uOQ0B8] Closing connection to the server using "destroy"
ghost-1  | [2025-05-23 09:23:15] ERROR Send Error: 400410B9FFFF0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
ghost-1  | [2025-05-23 09:23:15] ERROR
```

This is because  
/bitnami/ghost/config.production.json sets `mail.options.secure=true` 

### Additional information

This line does the wrong setting:
https://github.com/bitnami/containers/blame/33ae2c441b37138ac949ceb44f8ed8c5b0821120/bitnami/ghost/5/debian-12/rootfs/opt/bitnami/scripts/libghost.sh#L316
