### ISSUE TITLE
[bitnami/aws-cli] Bitbucket Pipelines fails silently unless `HOME` env is set to user-writeable directory

### ISSUE THREAD

**Issue by jarp0l** [bitnami/containers#81841]
### Name and Version

bitnami/aws-cli:*

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create a Bitbucket Pipeline with the following configuration:
```yml
image: bitnami/aws-cli
pipelines:
  default:
    - step:
        name: Test AWS CLI
        script:
          - export AWS_DEFAULT_REGION=us-east-1
          - export AWS_ROLE_ARN=arn:aws:iam::123456789012:role/oidc-role
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
          - aws sts get-caller-identity
```
3. Commit and push the file and let the pipeline run.
4. Observe that the step appears to fail silently, no output is printed.

### What is the expected behavior?

The step should either:
- Succeed and print the output of `script` block and the expected output from `aws sts get-caller-identity` command, or
- Print an error message indicating why the step failed.

### What do you see instead?

- The step fails silently.
- No output or error message is printed, making it difficult to diagnose the issue.

### Additional information

- The root cause seems to be that the `HOME` environment variable is set to `/` in the image, which is not writable by the non-root user (uid=1001).

- When I override `HOME` in the pipeline step (e.g. `export HOME=/tmp` in the step's `script` block), the step succeeds, although still no output is shown:
```yml
        script:
          - export HOME=/tmp
          - ...
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
          - aws sts get-caller-identity
```

- If I use my custom image in the pipeline based on `bitnami/aws-cli` where I set `HOME` to a writable directory in the Dockerfile (e.g. `/tmp`), both the pipeline/step execution and output work as expected.

- This issue seems to be related to another issue: https://github.com/bitnami/containers/issues/40781

#### Suggested fix
Update the Dockerfile to set the `HOME` environment variable to a user-writable directory, as done in another Bitnami image: https://github.com/bitnami/containers/blob/3202201d57eb4391ad4c69c46f32e32143d1c641/bitnami/dotnet/9/debian-12/Dockerfile#L20

| Without setting `HOME` env variable | After setting `HOME` env variable on my custom base image |
|----------------------|----------------------|
| ![Image](https://github.com/user-attachments/assets/216c1a5d-fb3f-4ec7-85dc-106047c6c29c) | ![Image](https://github.com/user-attachments/assets/7b0de79d-3101-458b-a89c-fdca5ae7467f) |
