### ISSUE TITLE
Minio settings disapeared

### ISSUE THREAD

**Issue by julianoBRL** [bitnami/containers#82422]
### Name and Version

bitnami/minio

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm running minio on a docker container latest. not sure what is cousing this problem, i'm logged in as root.

### What is the expected behavior?

Show the options to manage users and keys.

### What do you see instead?

![Image](https://github.com/user-attachments/assets/1c5e58d0-c0f2-4c95-aedc-7e8ec15db1a7)

Everytime i try a diferent url i get redirected to this same page.
All the other options have dissapered. but somehow the other users/keys still exists.
Other users are having the same problems.

### Additional information

i have tried:
- Restarting the container, 
- Recreating the container.
- Looking thoutgh the configs.

here is my compose: (removed root user/pass declaration)

```
services:
  minio:
    container_name: minio
    user: "root:root"
    image: bitnami/minio:latest
    restart: unless-stopped
    networks:
      - databases
    environment:
      - MINIO_BROWSER=on
      - MINIO_BROWSER_REDIRECT_URL=http://minio.${DOMAIN}
      - MINIO_SCHEME=http
      - MINIO_VOLUMES=/bitnami/minio/data
      - MINIO_OPTS="--console-address :9001"
      - MINIO_DATA_DIR=/bitnami/minio/data
    volumes:
      - /mnt/hd2tb/minio/data:/bitnami/minio/data
    labels:
      # S3
      - "traefik.enable=true"
      - "traefik.tcp.services.minio.loadbalancer.server.port=9000"
      - "traefik.tcp.routers.minio.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minio.entrypoints=minio"
      # WEB-UI
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio.entrypoints=web"

networks:
  databases:
    name: databases
    external: true
```
