### ISSUE TITLE
Bitnami Keycloak Keeps connecting database at localhost

### ISSUE THREAD

**Issue by maxlam79** [bitnami/containers#82536]
### Name and Version

bitnami/keycloak:26.2.5

### What steps will reproduce the bug?

I am attempting to connect `bitnami/keycloak` to a `MariaDB` database on the same network using Docker. But every time it started, it threw an error like:

```
test-keycloak  | 2025-06-24 03:20:45,085 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.hibernate.exception.JDBCConnectionException: unable to obtain isolated JDBC connection [Socket fail to connect to localhost. Connection refused] [n/a]
test-keycloak  | 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:100)
test-keycloak  | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
test-keycloak  | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
test-keycloak  | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
test-keycloak  | 	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doTheWork(JtaIsolationDelegate.java:206)
test-keycloak  | 	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.lambda$delegateWork$3(JtaIsolationDelegate.java:91)
test-keycloak  | 	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.doInSuspendedTransaction(JtaIsolationDelegate.java:125)
test-keycloak  | 	at org.hibernate.resource.transaction.backend.jta.internal.JtaIsolationDelegate.delegateWork(JtaIsolationDelegate.java:88)
test-keycloak  | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:320)
test-keycloak  | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:129)
test-keycloak  | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:81)
test-keycloak  | 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
test-keycloak  | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
test-keycloak  | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
test-keycloak  | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
test-keycloak  | 	at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
test-keycloak  | 	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:52)
test-keycloak  | 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:136)
test-keycloak  | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)
test-keycloak  | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
test-keycloak  | 	at org.hibernate.service.ServiceRegistry.requireService(ServiceRegistry.java:68)
test-keycloak  | 	at org.hibernate.boot.internal.SessionFactoryOptionsBuilder.<init>(SessionFactoryOptionsBuilder.java:290)
test-keycloak  | 	at io.quarkus.hibernate.orm.runtime.recording.PrevalidatedQuarkusMetadata.buildSessionFactoryOptionsBuilder(PrevalidatedQuarkusMetadata.java:72)
test-keycloak  | 	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
test-keycloak  | 	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
test-keycloak  | 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
test-keycloak  | 	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
test-keycloak  | 	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:163)
test-keycloak  | 	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:63)
test-keycloak  | 	at java.base/java.lang.Thread.run(Unknown Source)
test-keycloak  | Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to localhost. Connection refused
test-keycloak  | 	at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:131)
test-keycloak  | 	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:125)
test-keycloak  | 	at org.mariadb.jdbc.Driver.connect(Driver.java:75)
test-keycloak  | 	at org.mariadb.jdbc.Driver.connect(Driver.java:104)
test-keycloak  | 	at org.mariadb.jdbc.Driver.connect(Driver.java:29)
test-keycloak  | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
test-keycloak  | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:585)
test-keycloak  | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:566)
test-keycloak  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
test-keycloak  | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
test-keycloak  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
test-keycloak  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
test-keycloak  | 	... 1 more
test-keycloak  | Caused by: java.net.ConnectException: Connection refused
test-keycloak  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
test-keycloak  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
test-keycloak  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
test-keycloak  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
test-keycloak  | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
test-keycloak  | 	at java.base/java.net.Socket.connect(Unknown Source)
test-keycloak  | 	at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:118)
test-keycloak  | 	... 12 more
test-keycloak  | 
test-keycloak  | 2025-06-24 03:20:47,085 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Socket fail to connect to localhost. Connection refused
test-keycloak  | 2025-06-24 03:20:47,088 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
test-keycloak  | 2025-06-24 03:20:47,182 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
test-keycloak  | 2025-06-24 03:20:47,183 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
test-keycloak  | 2025-06-24 03:20:47,183 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Socket fail to connect to localhost. Connection refused
test-keycloak  | 2025-06-24 03:20:47,183 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection refused
```

To reproduce this:
Just create an external network `test-net`, have the docker-compose.yaml contents like so:

```yaml
services:

    test-mariadb:
        container_name: test-mariadb
        image: bitnami/mariadb:11.4.7
        restart: unless-stopped
        networks:
            - test-net
        environment:
            MARIADB_DATABASE: keycloak
            MARIADB_ROOT_PASSWORD: xWKjj2
            MARIADB_USER: testadmin
            MARIADB_PASSWORD: xWKjj2

    test-keycloak:
        container_name: test-keycloak
        image: bitnami/keycloak:26.2.5
        restart: unless-stopped
        networks:
            - test-net
        depends_on:
            - test-mariadb
        environment:
            KEYCLOAK_PROXY_HEADERS: xforwarded
            KEYCLOAK_ADMIN: kcadmin
            KEYCLOAK_ADMIN_PASSWORD: xWKjj2
            KEYCLOAK_DATABASE_VENDOR: mariadb
            KEYCLOAK_DATABASE_HOST: test-mariadb
            KEYCLOAK_DATABASE_PORT: 3306
            KEYCLOAK_DATABASE_NAME: keycloak
            KEYCLOAK_DATABASE_USER: testadmin
            KEYCLOAK_DATABASE_PASSWORD: xWKjj2

networks:
    test-net:
        external: true
```

### What is the expected behavior?

Should be able to connect to `test-mariadb` within the `test-net` network.

### What do you see instead?

Instead, it was trying to connect to a database at `localhost`. I think it disregarded the `KEYCLOAK_DATABASE_HOST` env variable.
