### ISSUE TITLE
[bitnami/redis] redis use wrong master after failover

### ISSUE THREAD

**Issue by ZWhitey** [bitnami/containers#9067]
### Name and Version

bitnami/redis:7.0.4

### What steps will reproduce the bug?

Enviroment: docker swarm with 3 node, each node have 1 redis and 1 sentinel
```
version: "3.8"
services:
  redis-1:
    image: bitnami/redis:7.0.4
    volumes:
      - redis-1_data:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_AOF_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - host
    deploy:
      placement:
        constraints:
          - "node.hostname==A"

  redis-2:
    image: bitnami/redis:7.0.4
    volumes:
      - redis-2_data:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_AOF_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - host
    deploy:
      placement:
        constraints:
          - "node.hostname==B"

  redis-3:
    image: bitnami/redis:7.0.4
    volumes:
      - redis-3_data:/bitnami/redis/data
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_AOF_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - host
    deploy:
      placement:
        constraints:
          - "node.hostname==C"

  redis-sentinel-1:
    image: bitnami/redis-sentinel:7.0.4
    volumes:
      - redis-sentinel-conf:/bitnami/redis-sentinel/conf
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=600000
    networks:
      - host
    deploy:
      placement:
        constraints:
          - "node.hostname==A"

  redis-sentinel-2:
    image: bitnami/redis-sentinel:7.0.4
    volumes:
      - redis-sentinel-conf:/bitnami/redis-sentinel/conf
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=600000
    networks:
      - host
    deploy:
      placement:
        constraints:
          - "node.hostname==B"

  redis-sentinel-3:
    image: bitnami/redis-sentinel:7.0.4
    volumes:
      - redis-sentinel-conf:/bitnami/redis-sentinel/conf
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=600000
    networks:
      - host
    deploy:
      placement:
        constraints:
          - "node.hostname==C"

networks:
  host:
    external: true
    name: host
volumes:
  redis-sentinel-conf:
    name: redis-sentinel-conf
```

2. How to reproduce
    1. start all service (A is redis master, B, C are slave)
    2. stop A
    3. after failover B or C become new master (e.g. A: offline, B: master, C: slave)
    4. start A (A: slave, B: master, C: slave)
    5. restart C, after restart architecture become weird, A become master and slave at the same time
     (A: slave of B and master of C, B: master of A, C: slave of A)

### What is the expected behavior?

C will become slave of B not A

### What do you see instead?

There are 2 master in my master-slave architecture
A become master of C and slave of B

### Additional information

I think the main problem is fixed redis master host setting in compose file, maybe we can make some script to looking for correct master. Or we can save redis.conf, redis will save master info in redis.conf.

Is there any way I can save master info without maintain redis.conf by myself?
btw, sentnel have some problem, but I can use volume to save data in /bitnami/redis-sentinel/conf, if conf not exist it will create new one, I don't need to prepare my own one. This way not working in redis because redis.conf is generate by redis-default.conf, if I use empty volume to /opt/bitnami/redis/etc/ its can't generate any conf for me.
