### ISSUE TITLE
[bitnami/redis-cluster] Cannot access redis-cluster using traefik v2

### ISSUE THREAD

**Issue by marlonangeli** [bitnami/containers#9786]
### Name and Version

bitnami/redis-cluster:7.0.5

### What steps will reproduce the bug?

1. Environment: Docker Swarm with 3 master nodes, no replicas
2. Config: docker-stack.yml
```yaml
version: '3.7'
services:
  traefik:
    image: traefik:v2.8.4
    ports:
     - target: 6379
       published: 6379
       mode: host
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # [other configs]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --providers.file.directory=/etc/traefik/dynamic
      - --entrypoints.redis.address=:6379
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public
 
  workers:
    image: docker.io/bitnami/redis-cluster:7.0
    hostname: node{{.Task.Slot}}
    networks:
      - traefik-public
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_NODES=node0
    volumes:
      - /mnt/glusterfs/data/redis/data_{{.Task.Slot}}:/bitnami/redis/data
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-public
      - traefik.tcp.routers.redis.entrypoints=redis
      - traefik.tcp.routers.redis.rule=HostSNI(`*`)
      - traefik.tcp.routers.redis.tls=true
      - traefik.tcp.routers.redis.service=redis
      - traefik.tcp.services.redis.loadbalancer.server.port=6379

  manager:
    image: docker.io/bitnami/redis-cluster:7.0
    hostname: node0
    networks:
      - traefik-public
    depends_on:
      - workers
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - REDIS_PASSWORD=my-password
      - REDISCLI_AUTH=my-password
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_NODES=node0 node1 node2
      - REDIS_CLUSTER_CREATOR=yes
    volumes:
      - /mnt/glusterfs/data/redis/data_0:/bitnami/redis/data
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-public
      - traefik.tcp.routers.redis.entrypoints=redis
      - traefik.tcp.routers.redis.rule=HostSNI(`*`)
      - traefik.tcp.routers.redis.tls=true
      - traefik.tcp.routers.redis.service=redis
      - traefik.tcp.services.redis.loadbalancer.server.port=6379

networks:
  traefik-public:
    external: true
```

### What is the expected behavior?

Connect to cluster.

### What do you see instead?

**Protocol error, got "H" as reply type byte. Please report this.**

### Additional information

Using the base image **bitnami/redis**, it connect normally

docker-stack.yml
```docker-compose
version: "3.2"
services:

    redis:
        image: "docker.io/bitnami/redis:7.0"
        networks:
            - traefik-public
        volumes:
            - /mnt/glusterfs/data/redis/data_{{.Task.Slot}}:/bitnami/redis/data
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_PASSWORD=my-password
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true                
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public          
                - traefik.tcp.routers.redis.entrypoints=redis
                - traefik.tcp.routers.redis.rule=HostSNI(`*`)
                - traefik.tcp.routers.redis.tls=true
                - traefik.tcp.routers.redis.service=redis
                - traefik.tcp.services.redis.loadbalancer.server.port=6379

networks:
    traefik-public:
        external: true
```
