### ISSUE TITLE
Missing DAGs in the UI

### ISSUE THREAD

**Issue by lukasheinz92** [bitnami/containers#991]
### Name and Version

bitnami/airflow:latest

### What steps will reproduce the bug?

When I put my DAG file into `/opt/bitnami/airflow/dags`, I don't see it in the web UI. I searched the web but nothing worked for me.

### What do you see instead?

I don't see any DAG files.

**Comment by javsalgar** [comment]
Hi!

Do you have some values or docker-compose that triggers the issue? Are you using the helm chart?

**Comment by lukasheinz92** [comment]
Hi,
below is my docker-compose:
```
version: '2'
volumes:
  airflow_postgresql:
  airflow_redis:
  airflow_dags:
services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: airflow_postgres
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - airflow_postgresql:/bitnami/postgresql
  redis:
    image: bitnami/redis:latest
    container_name: airflow_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - airflow_redis:/bitnami
  airflow-worker:
    image: bitnami/airflow-worker:latest
    container_name: airflow_worker
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_WEBSERVER_HOST=192.168.0.101
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8088
      - AIRFLOW_LOAD_EXAMPLES=no

  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    container_name: airflow_scheduler
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_WEBSERVER_HOST=192.168.0.101
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8088
      - AIRFLOW_LOAD_EXAMPLES=no
  airflow:
    image: bitnami/airflow:latest
    container_name: airflow
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - airflow_dags:/opt/bitnami/airflow/dags
    ports:
      - '8088:8080'
```

**Comment by fmulero** [comment]
Hi

Could you share the logs? Do you see any warning or error in the web console?

**Comment by lukasheinz92** [comment]
Hi,

now in the web GUI I can see this error (I am not sure but I think the error was not there before):

```
The scheduler does not appear to be running.
The DAGs list may not update, and new tasks will not be scheduled.
```

In the scheduler container I can see this:

```
airflow-worker 17:51:35.05 ERROR ==> Could not connect to the Airflow webserver
airflow-worker 18:12:07.01 
airflow-worker 18:12:07.01 Welcome to the Bitnami airflow-worker container
airflow-worker 18:12:07.01 Subscribe to project updates by watching https://github.com/bitnami/containers
airflow-worker 18:12:07.01 Submit issues and feature requests at https://github.com/bitnami/containers/issues
airflow-worker 18:12:07.01 
airflow-worker 18:12:07.02 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-worker 18:12:07.03 INFO  ==> ** Starting Airflow setup **
airflow-worker 18:12:07.06 INFO  ==> Configuration file found, loading configuration
airflow-worker 18:12:07.06 INFO  ==> Trying to connect to the database server
airflow-worker 18:12:09.02 INFO  ==> Waiting for Airflow Webserser to be up
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
```

**Comment by fmulero** [comment]
Could you use the service name and the container port for the internal communication instead of using the host ip and port? Something like this:

```yaml
version: '2'
volumes:
  airflow_postgresql:
  airflow_redis:
  airflow_dags:
services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: airflow_postgres
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - airflow_postgresql:/bitnami/postgresql
  redis:
    image: bitnami/redis:latest
    container_name: airflow_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - airflow_redis:/bitnami
  airflow-worker:
    image: bitnami/airflow-worker:latest
    container_name: airflow_worker
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8080
      - AIRFLOW_LOAD_EXAMPLES=no

  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    container_name: airflow_scheduler
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8080
      - AIRFLOW_LOAD_EXAMPLES=no
  airflow:
    image: bitnami/airflow:latest
    container_name: airflow
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - airflow_dags:/opt/bitnami/airflow/dags
    ports:
      - '8088:8080'
```
